### ISSUE TITLE
All connected game controllers are always in use as input in the game

### ISSUE THREAD

**Issue by Str3amR** [MaFi-Games/Captain-of-Industry-issues#1]
**Describe the issue**
The game seems to listen to every single connected game controllers and respond to their axis inputs without an ability to disable them or select an "active" one, it causes trouble in some setups like in flightsim where some axis might actually be almost always off-center because as soon as an input is touched the game field starts to scroll in that direction and get stuck there. It makes the game basically unusable in my setup unless I disconnect the unused controllers while playing. This is the first game that I see this specific behavior without a way to select another game controller which would have it's axis centered by default.

**To Reproduce**
1. Connect multiple game controllers
2. Start the game and touch most axis on any controller, almost all controllers will have at least some axis that will make the game map move.

**Expected behavior**
A. Like most games, have a way to select a single controller as input to prevent it.
B. I didn't find any documentation about using game controllers with the game so disabling game controller input altogether until they are properly supported might be another solution.

**Additional context**
 - Game version: ALPHA 0.2.0

**Comment by MaFi-Games** [comment]
This has been fixed in `v0.2.0c`. Can you please verify that this is no longer an issue?

**Comment by Str3amR** [comment]
Looks good to me! Thanks for the quick fix!

**Comment by mloftis** [comment]
Tested on my setup as well 0.2.1 - feex confirmed!  TYVM!
