### ISSUE TITLE
Haul Truck won't load from Fluid Storage III

### ISSUE THREAD

**Issue by RedSpid3r** [MaFi-Games/Captain-of-Industry-issues#1007]
### Issue description

Haul Truck will not load goods (Carbon Dioxide) from Fluid Storage III. Other smaller trucks work fine.

### Expected behavior

Haul Truck loads goods from Fluid Storage III

### Reproduction steps

1. Build Fluid Storage III
2. Fill tank with goods and set to Empty / Export Route
3. Assign Haul Truck to Fluid Storage III
4. Observe

### Game version

v0.4.14b (157)

### Attachments

![Trucks](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12657277/9072b402-1927-4e85-b65d-2587c3405c4e)
![Fluid_Storage_3](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12657277/95d7b28d-179b-4cdf-acc9-dd011372727a)

**Comment by MaFi-Games** [comment]
I'm not sure what is going on there, as a save file was not attached. But given this is also an older version of the game, I'm going to close it as not enough info. If you find these issues in the new version, please file a bug, and we will take a look. Thanks!
