### ISSUE TITLE
[UX][QOL] Toggling "Planning mode" cancels building selection

### ISSUE THREAD

**Issue by Xiphoris** [MaFi-Games/Captain-of-Industry-issues#1008]
### Issue description

When I'm in the middle of placing a building, I often realize that my design is not finished, and needs more work, and so I use "B" to toggle "Planning Mode" -- so that placement will create a paused ghost building, that I can edit before it's constructed.

**Observed Behavior:** Toggling "Planning Mode" causes my placement to be deselected, and I have to select the desired building again from the menu.

Toggling "Planning Mode" *does* work while placing blueprints, but does not work when placing normal buildings.

### Expected behavior

**Desired Behavior:** Toggling "Planning Mode" doesn't deselect building placement.

### Game version

All current versions

**Comment by MaFi-Games** [comment]
This was fixed shortly after Update 1. Thanks for your report!
