### ISSUE TITLE
Planning mode available without researching it

### ISSUE THREAD

**Issue by jirinn** [MaFi-Games/Captain-of-Industry-issues#1009]
### Issue description

The planning mode, copy paste etc. is available via hotkeys even "Tools" is not researched yet.

### Expected behavior

Hotkeys should be disabled when "Tools" are not researched yet.

### Game version

1.0.5.0

**Comment by zuff-coi** [comment]
This is intended as we wanted veteran players to still have access to the tools they've been using for dozens of hours and new players will be introduced to them through research.
