### ISSUE TITLE
Evaporation ponds recipe for brine to salt does not show up in the recipe browser

### ISSUE THREAD

**Issue by Ramh5** [MaFi-Games/Captain-of-Industry-issues#101]
**Describe the issue**
Evaporation pond (heated) recipe for brine to salt does not show up in the recipe browser

**To Reproduce**
Check the recipe browser for salt and the evaporation ponds

**Expected behavior**
Every recipe should be in the recipe browser

**Additional context**
Beta 0.3.8

**Comment by MaFi-Games** [comment]
Thanks for the report, I was able to reproduce this issue.

**Comment by MaFi-Games** [comment]
I believe we have fixed this for EA.
