### ISSUE TITLE
RADAR_PRE_LEAK_64 caused reboot on 0.50 update

### ISSUE THREAD

**Issue by L34-Github** [MaFi-Games/Captain-of-Industry-issues#1010]
### Issue description

RADAR_PRE_LEAK_64 just prior to full error. Leak was with Captain of Industry.exe.

### Expected behavior

Not have computer reboot 

### Reproduction steps

Was placing a blast furnace 

### Game version

0.50

### Attachments

![Uploading 16854741232478167550810570697864.jpg…]()

**Comment by MaFi-Games** [comment]
Can you please provide game's and Unity's logs?

**Comment by L34-Github** [comment]
I will try and get to that in next day or two.  Crash has not recurred since, haven't had a ton of play time but did play for several hours later that day after the update on 05/30 around 14:00 Pacific time.
________________________________

**Comment by L34-Github** [comment]
Sorry I didn't get these over to you, at this time, I have not seen this recur and have played since, would the logs still be useful?
________________________________

**Comment by MaFi-Games** [comment]
Closing as not enough information available. Please file a new issue if you hit another crash and get to the logs. Thanks!
