### ISSUE TITLE
Mining Priority has no effect

### ISSUE THREAD

**Issue by RedSpid3r** [MaFi-Games/Captain-of-Industry-issues#1011]
### Issue description

Setting a Mining Priority on excavators does not seem to have any effect. I set 2 excavators to Dirt but they continued to mine Copper.

### Expected behavior

Excavators prioritise the resource selected

### Reproduction steps

1. Build Tower
2. Assign Excavator
3. Set a resource in Mining Priority
4. Observe

### Game version

1 0.5.0 (188)

### Attachments

![mining_priority](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12657277/1063640d-0a59-4b8a-a8a2-09650d4f19eb)
![mining_zone](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12657277/aa5a63ef-e9af-44fd-947b-92a6d0edf429)

**Comment by MaFi-Games** [comment]
This was fixed shortly after Update 1. Thanks for your report!
