### ISSUE TITLE
Trucks unable to dump outside of explicit logistic assignment

### ISSUE THREAD

**Issue by themisfitjoe** [MaFi-Games/Captain-of-Industry-issues#1012]
### Issue description

Trucks (pickups in this case, haven't gotten to later tech, yet), are not dumping product loaded by excavators (in this case Rock).  They are generating an error that there is no place to dump, despite mining towers open with rock as an acceptable dumping product and not being exclusive.

![20230530171510_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135081828/386d6917-2fbb-45c4-91ea-efc9e2cf7d55)
![20230530171522_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135081828/49b33041-b46d-41e0-a106-b714767e58be)

### Expected behavior

Expected behavior is trucks to go down a checklist based on distance (inferring from the update video description of revamp). has happened in both towers that aren't assigned to an export locations, compared to those that are.  This is also affecting the ability of the truck to dump within mining section, say for terrain leveling actions.

### Reproduction steps

1) Load attached save
2)Assuming it loads up directly to the problem spot, you'll see an errored truck at a mining tower waiting to find a location to dump.
3)Immediately to the bottom, dumping into the interior bay, is a mining tower with an assigned dumping zone.  But is not being assigned "free" dumping.  Tower is not designated as an exclusive assigned dumping zone.

### Game version

Update 1 0.5.0 (189)

### Attachments

[Error.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11607584/Error.zip)

**Comment by MaFi-Games** [comment]
You're correct. Thanks for the report and save file. This will be fixed in the next patch!

**Comment by themisfitjoe** [comment]
Always welcome, love the game!
