### ISSUE TITLE
Blurry text in many areas

### ISSUE THREAD

**Issue by knord1** [MaFi-Games/Captain-of-Industry-issues#1015]
### Issue description

The font is blurry and hard to read in many locations.

Changing to any antialias and even none AA doesn't change anything.
Tried UI scale: 120%, 100% and 80%. At 80% all text is blurry and hard to read, at 100 and 120 tutorial text is clear.

Attached images:
01) Tutorial text is clear but ESC menu and "Dumping Waste" text is blurry.
02) Tutorial text is clear but text inside Blast Furnace window is blurry.
03) Loading screen text is clear.

### Expected behavior

Clear and readable text.

### Game version

0.5.0 (189)

### Attachments

![Blurry text 01](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8095995/fcd66e91-4d0a-4283-b55a-984e1ba523a1)
![Blurry text 02](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8095995/235c77f0-3406-4683-8a1f-c69bcecbf3dc)
![Blurry text 03](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8095995/ee0a42f8-2d15-45d4-a4a4-0b4d0c3234c7)

**Comment by MaFi-Games** [comment]
We have swapped our text rendering solution in our latest patch, you can wait or try it on experimental. It should improve how the fonts are rendered.
