### ISSUE TITLE
Captain of Industries/Captainofcheats

### ISSUE THREAD

**Issue by razor4495** [MaFi-Games/Captain-of-Industry-issues#1017]
### Issue description

Fehlermeldung beim starten eines neuen Spiels mit dem Captainofcheats.
![Screenshot 2023-05-31 222931](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135169113/26904ec4-b3e7-44c3-a146-39dbba0b1f62)

### Expected behavior

Könnt Ihr mir eine genaue beschreibung der Installation zeigen?

### Reproduction steps

Installation gemäss Anweisungen 

![Screenshot 2023-05-31 223110](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135169113/cdebff45-a311-4de1-9fb4-4524dca61f6c)

### Game version

v0.5.0A

**Comment by zuff-coi** [comment]
https://github.com/altmank/CaptainOfCheats
