### ISSUE TITLE
Tree planter Doesn't go to nearest source of seedlings

### ISSUE THREAD

**Issue by ksorbo** [MaFi-Games/Captain-of-Industry-issues#1019]
### Issue description

My tree seeder is insisting on going back to the storage area I have linked up to the farm.

I have a storage area right next to the area to be seeded and there are many seedlings in that storage area.

Only think I can think of is that the storage area next to the farm was created before the one next to the planting area. 

### Expected behavior

Expected the planter to go to the nearest source of seedlings

Attached graphic shows the near storage area.

### Game version

v.0.5.1

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1436884/e17040a8-0cbf-4a2b-89cd-bf09587cdb50)

**Comment by zuff-coi** [comment]
It's a priority issue. The farm has a higher priority than the storage does by default (P9 to P10). Either lower the farm's priority or raise the storages priority for keep empty to force the tree planter to gather from there.

We'll look into further ways to make this more intuitive

**Comment by MaFi-Games** [comment]
We have added option to assign sapling storage to the tower. Hopefully that improves this.

**Comment by ksorbo** [comment]
That sounds like a great idea.
