### ISSUE TITLE
Impossible setup building

### ISSUE THREAD

**Issue by Astree13** [MaFi-Games/Captain-of-Industry-issues#102]
**Describe the issue**
As soon as a setup is a bit complicated, the trucks can't access the inside items to build them

**To Reproduce**
As shown on the screenshot, the inner belt is impossible to build without destroying the factories around it
**Expected behavior**

**Additional context**
 - Game version: 0.3.8

**Attachments**

![Capture d’écran 2022-01-07 220610](https://user-images.githubusercontent.com/34662883/148607506-bc438276-1421-4331-817d-59472ca73432.png)

**Comment by MaFi-Games** [comment]
Hi, thanks for the report. Looking at your screenshot, construction and deconstruction should be able to happen in this case, without any problem.

Could you attach a save file where there are some entities that are not being built? Otherwise we are not able to know what is wrong.

**Comment by Astree13** [comment]
Sorry, I didn't keep saves for that (will still check it). I'll come back as soon as I encounter it again, I just started a new game.

**Comment by Astree13** [comment]
Ok, could reproduce it in this save, will send the file under ...
![22-01-11_08-18-45_9509_photo](https://user-images.githubusercontent.com/34662883/148898451-eb0c5404-2c86-46ee-acf9-722ec0ad070b.png)

**Comment by Astree13** [comment]
can't put the file here. Link to get it : 
https://www.dropbox.com/s/jemmbagqtgnrhq7/save_22-01-11_08-19-22%20bug%20belt.save?dl=0

**Comment by TumultuousTitan** [comment]
If you put it in a zip file you can upload it here.

**Comment by MaFi-Games** [comment]
I believe after beta we have increased the distances. As we are in EA right now, we can no longer load that save file. But I do not see any similar issues occuring in new version.
