### ISSUE TITLE
saves

### ISSUE THREAD

**Issue by K39ZZZ** [MaFi-Games/Captain-of-Industry-issues#1020]
### Issue description

Game refuses to autosave or manual save a game 

### Expected behavior

I expect to save a game

### Game version

v.0.5.0

**Comment by MaFi-Games** [comment]
I'm sorry to hear that. Could you please provide your logs? They are in %USERPROFILE%\AppData\Roaming\Captain of Industry\Logs

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. Please file a new bug if you encounter this again and have more information.
