### ISSUE TITLE
When deconstructing a building, the trucks go to the shipyard with the construction materials, even though it has "keep empty" checked, and there's an almost empty unit storage for it that they can get to and has settings that allow dropping off the items

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1021]
**The issue**
See title. Some of the trucks went to the proper storage, most did not. Then they had to go back and remove the parts from the shipyard and put them into the storage because of the "keep empty" option that should have prevented them from dumping stuff there to begin with.

**Expected behavior**
Deliver to a compatible storage, unless all of them are full, in that case, fail to deconstruct, and *not* to deliver to the shipyard

**To Reproduce**
[Insula Mortis-2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11619368/Insula.Mortis-2.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting this! We fixed this in out last patch.
