### ISSUE TITLE
loading the game 

### ISSUE THREAD

**Issue by riktus106** [MaFi-Games/Captain-of-Industry-issues#1024]
### Issue description

loading the game the load screen shows then the load bar finishes then the error 

### Expected behavior

the game should work it was working fine no problems 2 hrs before 

### Game version

v0.5.0A update 1

### Attachments

[23-06-01_13-49-02_6375.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11620825/23-06-01_13-49-02_6375.log)

**Comment by MaFi-Games** [comment]
I see the following: 
 DependencyResolverException: Failed to instantiate CaptainOfCheats.UI.CaptainOfCheatsController.
 
 The mod you are using is broken. Please reach out to the author.
