### ISSUE TITLE
Buzzing sound

### ISSUE THREAD

**Issue by liq3** [MaFi-Games/Captain-of-Industry-issues#1025]
### Issue description

The game is making a low volume buzzing sound. 

### Expected behavior

It doesn't make a buzzing sound. 

### Reproduction steps

No idea, it seems pretty inconsistent. Seems to always happen at some point though. 

### Game version

0.5.0a (194)

**Comment by MaFi-Games** [comment]
We are not aware of such issue. When does it happen? At a specific point? Looking at a specific machine? Do you have a save file when that sound occurs?

**Comment by liq3** [comment]
Ah my bad, I tested it with 2 other games and it's happening, so I guess something is wrong with my PC. You can close the issue then.
