### ISSUE TITLE
Export setting is not saved

### ISSUE THREAD

**Issue by FMPope** [MaFi-Games/Captain-of-Industry-issues#1026]
### Issue description

Found a bug after each time loading my save. 
My "set export" ( red bar ) of overflow on my slag is being not saved and removed each time i load the Savefile. 
I have to set it new for export each time i load in. Noticed it each time on my new heaven map save when my Smelters weren't working :). I still use slag for making concrete slabs.
happens to loose-storage atm; can confirm Fluid Storage not affected

### Expected behavior

setting saved and loaded correctly

### Reproduction steps

Load Save, click on marked storage and save it with set export according to screenshot; load save again and see if export setting has been reset.

Version 1 / 0.5.0a

### Game version

v0.5.0a

### Attachments

[NH1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11622167/NH1.zip)
![grafik](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135207175/1aaa8cdb-ee40-47bf-bd4e-30da5b9fdb23)

**Comment by zuff-coi** [comment]
Can confirm I was able to replicate

**Comment by MaFi-Games** [comment]
Thanks for reporting. This was fixed in the previous patch!
