### ISSUE TITLE
Sand no longer transported

### ISSUE THREAD

**Issue by Darkomage** [MaFi-Games/Captain-of-Industry-issues#103]
**Describe the issue**
The sand filled trucks from mining get stuck, cliaming there are no valid destination, even if I have Loose Storage set to "Sand".
Also, those trucks occasionnaly accept to deliver sand directly to y concrete mixers when they get empty, but don't deliver sand elsewhere.
Also, if I de-assign the truck from the mine, it will unload sand at the dock.
And finally, I noticed that most of my trucks are "Idle" (9 out of 13) even if there are things to haul, buildings to build, and so on.

**To Reproduce**
1. Load attached save "Sand Problem.save"
2. Have a look at the trucks around the copper mine, on the lowerplatform
3. Try to make them do something with the damn sand ! (Concrete mixers are between the sand mine and the iron mine, connected to a sand loose storage unit...

**Expected behavior**
Sand should be delivered to loose storage then brought by conveyor to my concrete mixer. Trucks should not get stuck.

**Additional context**
 - Game version: Beta 0.3.8

**Attachments**
[Sand Problem.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7833664/Sand.Problem.zip)

**Comment by fregate84** [comment]
![Screen Shot 01-09-22 at 02 35 PM](https://user-images.githubusercontent.com/96617483/148684527-44c47dc2-6a4e-44d9-9ec9-d229412cc855.PNG)
your loose storage is configure with a "void over a quantity". In this case, truck never come to put something on it.
You should ask for a minimum quantity (green part) and delever will start.

**Comment by Darkomage** [comment]
Hi.This one is, indeed.But the other one, connected To the concrete mixer  is not. And strangely enough, the sand one with the "keep empty" is *not* hauled to the one feeding the concrete mixer.   Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : fregate84 ***@***.***> Date : 09/01/2022  14:39  (GMT+01:00) À : MaFi-Games/Captain-of-Industry-issues ***@***.***> Cc : Darkomage ***@***.***>, Author ***@***.***> Objet : Re: [MaFi-Games/Captain-of-Industry-issues] Sand no longer transported (Issue #103) 

your loose storage is configure with a "void over a quantity". In this case, truck never come to put something on it.
You should ask for a minimum quantity (green part) and delever will start.

**Comment by fregate84** [comment]
I don't understand. All your storage are configure to "void things" or are full :
![Screen Shot 01-09-22 at 02 55 PM](https://user-images.githubusercontent.com/96617483/148685297-0b4ec282-39b2-4480-a2f6-210e96f5b0c2.PNG)
![Screen Shot 01-09-22 at 02 54 PM](https://user-images.githubusercontent.com/96617483/148685299-3d7c24aa-d643-4286-ae43-ededd545eff9.PNG)
![Screen Shot 01-09-22 at 02 54 PM 001](https://user-images.githubusercontent.com/96617483/148685300-9e36629a-4ea4-4e8b-89f5-4f21d859de14.PNG)

**Comment by Darkomage** [comment]
OK ,my mistake
What I thought is that with a storage containing 0/180 material, with a 
"keep empty" set at a 126 threshold, trucks providing material would 
fill it, and hauling trucks would empty it to keep it at 126.

It's what I observe when a conveyor is connected to a storage set up 
with a "keep empty" threshold. And from tie to time, when trucks are 
overwhelmed, the actual content of the storage unit *can* grow over the 
threshold. But as soon as trucks are available, they come and partially 
empty the storage unit.

I thought that "incoming trucks" would act the same as conveyors.

I think this is what made me think there was a bug.

I guess this issue can be closed.

thank you for your help !

Le 09/01/2022 à 14:58, fregate84 a écrit :
