### ISSUE TITLE
somehting change into trucks IA

### ISSUE THREAD

**Issue by serginhov2** [MaFi-Games/Captain-of-Industry-issues#1031]
### Issue description

I'm Facing some issues with trucks AI, sometimes they stop and do not fill the warehouses with the items, I need to force them to put an export route to do this.

Another thing is the trucks are not depositing the construction items after paying the unity to build fast, they simply stay stopped without action stuck with the loot.

trucks are not occupied status and still not filling the deposits.

### Expected behavior

Something changed after this big update, please check the trucks AI

### Game version

0,5,0

**Comment by zuff-coi** [comment]
Do you have a save file at the moment this is happening? I'd be happy take a look so we can figure out what's going on. 

You can find save files in `"%AppData%\Captain of Industry\Saves"`

**Comment by serginhov2** [comment]
SURE, FOLLOW.

**Comment by serginhov2** [comment]
[save_23-06-01_15-30-02.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11628380/save_23-06-01_15-30-02.zip)

**Comment by MaFi-Games** [comment]
Could you please clarify which warehouses the trucks do not fill without having custom routes assigned?

**Comment by serginhov2** [comment]
> Could you please clarify which warehouses the trucks do not fill without having custom routes assigned?

the issue was resolved in last path, It tas a pathfinder issue

**Comment by MaFi-Games** [comment]
Cool, glad that's resolved and thanks for letting us know!
