### ISSUE TITLE
Pathfinding is not working

### ISSUE THREAD

**Issue by mendo21** [MaFi-Games/Captain-of-Industry-issues#1036]
### Issue description

The vehicles are getting stopped and can not make the distant route that is free. try to make the route shorter and gives a warning that they can not reach. 

### Expected behavior

The vehicles  don't move 

### Game version

0.5

**Comment by serginhov2** [comment]
same problem as me

**Comment by MaFi-Games** [comment]
We have significantly improved path finding in our last patch. This should now all work. If you still have an issue, please create a new report with a save file attached. Thanks!
