### ISSUE TITLE
Leveling tool accessible using hotkey even before being researched

### ISSUE THREAD

**Issue by senshi-x** [MaFi-Games/Captain-of-Industry-issues#1037]
### Issue description

You can access and utilize the leveling tool using the hotkey (default N) even before it is researched in the tech tree. Researching it in the tech tree only adds the clickable button to the UI bar.

### Expected behavior

They hotkey to access leveling tool should only start working after the associated research is completed.

### Reproduction steps

1. Start new Game
2. Press N
3. Use Leveling tool even when it's not researched

### Game version

0.5

**Comment by MaFi-Games** [comment]
Thanks for reporting. This has been fixed in our last patch!
