### ISSUE TITLE
nicht speichern

### ISSUE THREAD

**Issue by jegold3384** [MaFi-Games/Captain-of-Industry-issues#1038]
### Issue description

Hallo nach einer Gewissen Spielzeit kann ich mein Spielstand nicht speichern. Bekomme dann diese Meldung angezeigt
![Screenshot 2023-06-02 081613](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135309047/0d2ea53f-a7a6-4361-856c-690aef64d80a)

### Expected behavior

...

### Game version

v0.5.0B

**Comment by MaFi-Games** [comment]
I'm sorry to see that. Could you please share us your log files? They are in %USERPROFILE%\AppData\Roaming\Captain of Industry\Logs

**Comment by MaFi-Games** [comment]
Closing as there is not enough information available. If you experience this issue again, please file a new bug with more information.
