### ISSUE TITLE
Food types are not evenly consumed in the market

### ISSUE THREAD

**Issue by GustavoRighetti** [MaFi-Games/Captain-of-Industry-issues#1039]
### Issue description

I realised that, despite me stocking 4 different food types, people are only consuming vegetables. the rest of the food types keeps piling up while people consume only one, and then go off to another one when there are no more vegetables. 
I still get unity and health bonus from different food types but this is creating a heavy imbalance in my production.

### Expected behavior

I expected all foods to be evenly consumed to balance demand and production

### Reproduction steps

No idea, i have 2 Food Market II, one with bread and corn, other with potatoes and vegetables

### Game version

v0.5.0a

**Comment by MaFi-Games** [comment]
We are not aware of such issue. Could you please provide your save file?

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. Feel free to file a new bug if you have more info.
