### ISSUE TITLE
Unity menu show wrong numbers (visual bug)

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#104]
[22-01-08_19-25-15_8807-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7833796/22-01-08_19-25-15_8807-autosave.zip)

In this save the unity menu is broken it show that i have a negative income of unity but if you open the menu you see that is postive. I even got unity each month but still the game think that i dont should have. (No unity used for 60 days to test it)

**Comment by McRib33** [comment]
found the reason for it. It seem the edicts are causing it when disable and enable it is working again.

**Comment by MaFi-Games** [comment]
Thanks for the report, I was able to reproduce this issue thanks to your save file, unity delta is negative but it is increasing over time:
![image](https://user-images.githubusercontent.com/90082857/148869169-737c923a-432b-4ebc-ac9b-d6770867ff5c.png)
![image](https://user-images.githubusercontent.com/90082857/148869195-f54afb4e-e3f9-4dee-b89a-b74715dc5d06.png)

We will look into this.

**Comment by MaFi-Games** [comment]
This was hopefully fixed in EA version. Please file it again if it persisted.
