### ISSUE TITLE
Crash Report: Could not load save using COC Mod

### ISSUE THREAD

**Issue by MerixStyle** [MaFi-Games/Captain-of-Industry-issues#1042]
### Issue description

https://gyazo.com/7c372ad9fbb52aa6ab05474aac14609a

Screenshot image of the error

### Expected behavior

Load the save.

### Game version

Latest version

**Comment by MaFi-Games** [comment]
I think you need to reach out to the mod author. Also make sure you are using mod that is compatible with Update 1.

**Comment by MerixStyle** [comment]
I thought that mod was made by the devs lol
