### ISSUE TITLE
Complete breakdown of pathfinding

### ISSUE THREAD

**Issue by ZakaryX2** [MaFi-Games/Captain-of-Industry-issues#1043]
**The issue**
After a rockslide separated half my base my trucks and Excavators became completely unresponsive. Moving the mining control tower from one side to the other didn't help. Changing the "edit area" for mining didn't seem to help either. The trucks seemed to move less and less as time went on from the start of the rockslide until eventually they stopped moving altogether. 

**To Reproduce**
Easy to see by clicking the manual waypoint button and watching as the trucks fail to move at all and get stuck on "Navigating" 

**Additional context**
0.5.0c(198)
Seed 9plfkwasgyp6

**Attachments**
Here's my save. 
[Bugs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11640186/Bugs.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report! We have made lots of improvement in path finding in our last patch so that should fix it. Tried your save and managed to recover it successfully.
