### ISSUE TITLE
Path Finding Breakdown with a save file that shows what is causing it.

### ISSUE THREAD

**Issue by Joyreaper** [MaFi-Games/Captain-of-Industry-issues#1044]
### Issue description

Hello, I had the path finding issues with trucks that a few others reported. Where all of the trucks have jobs assigned but one 3-5 of them will do there jobs at one time from a fleet of 70ish trucks. I realized what the issue was and made a save before fixing it. Using my work in progress ramp as reference, there is a leveling designation to the top left of the ramp that I placed for eventually filling in the hole in that area. For some reason, the trucks were getting a green indicator to dump in that area even though they could not reach it and it seemed to be crashing the pathfinding for every truck I had. As soon as I deleted the leveling zone, all my trucks returned to normal. Hope this helps solve the problem.

### Expected behavior

Truck to pathfind and complete the assigned jobs.

### Reproduction steps

1. Load attached save.
2. Observe the current breakdown of trucks completing their jobs.
3. Delete the leveling area the is to the top left of the ramp to the top level. It is to the top left if you are looking up the ramp.

### Game version

.0.5

### Attachments

[Games Save - Bug Save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11641841/Games.Save.-.Bug.Save.zip)

**Comment by MaFi-Games** [comment]
This was fixed shorly after Update 1. Looking at your save file, other trucks are no longer stalling. Thanks for your report.
