### ISSUE TITLE
how to transfer old save file to new version?

### ISSUE THREAD

**Issue by Ezio1014** [MaFi-Games/Captain-of-Industry-issues#1045]
### Issue description

how to transfer old save file to new version?

thanks.

### Expected behavior

teaching me pls.

### Game version

V0.5.0C

**Comment by MaFi-Games** [comment]
Save from 0.4 cannot be played on 0.5 ((Update 1). If you wish to play the old version you can switch it on Steam by going to ea-legacy version, you can also create blueprints to take your favorite designs with you.

**Comment by Ezio1014** [comment]
OK, got it.
Thank you.
