### ISSUE TITLE
Blueprint Validation: Electrolyser not required, removed on paste

### ISSUE THREAD

**Issue by mnoreke** [MaFi-Games/Captain-of-Industry-issues#1046]
**The issue**
When using a blueprint that requires the electrolyer, it doesn't require it and removes it from the pasted buildings instead.

**Expected behavior**
Validation to not allow using until unlocked.

**To Reproduce**
Use the following blueprint string:
B1652:H4sIAAAAAAAACn1VzW/jVBAfO67ret3UddJsWrKllGXZNqW0xRRY0Cr9Shup3YZNV0hcKjd5mz7W8YvsF2j2iDjxJyAOnBAnDhz2vOLIgT+BA1v+AcSBwwoxzx+JixqkkWzPzG++ZyxJ42ur9uq6fXYqZ/dc0uQ+82gzWKjVMrCsKOaxT9vUc9w9j1Per7W+/F0Zsw5ZmwYc1Wpet8ePWIuAmhswj3s84Y5P7ROP+I5b9ynz0YAFkjZR9xlnvN8lEzNbQUA6Z24/ck0fU9I62ZD08YekSbskkG4UUkFtJNon65IxceI7XvCY+Z0xqw4yKMpXGBqoMB76kHRpcrK+s52GjBU/ChV/fDFUzOpbfrPa8z2nSRAzZTWoS5vMa3SIy6nXRikCzeUQ+CwFNLOx5kPiNDnzETxtxqwTnzi8QzwuoPcQCgiwrCPmcuIdEe64O+eO5xEXpJyOeXxGhIW+DhKgsmTa6Os5+lJUJfSV1xsd9oQ0uNN8gsWZuTn83CVdl3DSanDidArTQ8FBN2TdTLEOI1bRHLKOL/pt4s1aQ84DitVG3lwKuHdx7vQC/krK747jnzFvl7IL2iKYpoUxh2mW1Dp27mQd5JzIBzOS8jbcGq9T13X8ICO+UG0+W3UdvsO8z0mf+agu5Saj9GXzPpgHWIFfU9V+NbtzTjq0iZPkOh7HEZEWrH3f6Z5TTnCeWr0mp8zDQPQ8qFLoIWVSL4G+gCb/TJl8zYhHy+0/JaJ9i9PbPvXIgBvQAO1pGtpTlb9eYCten21gn5w2qXW6zOePcCfcOvGb2Onv/tFvF2Pp3oWQVn3WiYXPvzHemLkCTfbBvDNzBTTgZ94s1oKre7ZLA+fMJS24O5sSRds2kC0VtlyXffGAeTj5tO2RVqQAsrZ8I3b1yKO8nI8/xIO04hKuZOOX0x3W7RIfsACLm1hNVfk7LIBIU2Rj3sEI4S4sCbvltyYT2L7rBEGIWglRL/8HtTqVoLCnIpcQtwjhzGhvzxwyFpAjhxOf4sLEk4JjVRD7JMNYYQ7ySPNgIi3giGXyc/l5c15Vvr4c5XXNiNMOjZfXB/l+3HN8/jSMoJhEIAZIDj/k0hwU50BVvh1tubxhDIvnuMJUMQ9ybErO5aJZVKw8WCXIImHMY7JVwtdYZVKcChxXywDTgFsZCV+SQMRhQGEhC/ksDLnRfFsmWBbIyk+X0cF4Z+mIevRT2j2tsTqOVePc6ZLT6wsqlldYVJVnI5NbLtu5JLnUQQ7LVYnLJfbNjOLJFLeheAD5A0gESc9K21CqyoWqbFXBGoonI7FcsmHOHnDNiJsprUIR6RrBbSgg2Rj7LyNjfzdpedXt0VZ5czCr4baLFEw1blMJe2BGPchgSVQkWfQoi09V+W20i/J7A6ufiPoKqxr+lSRFeXmZOjl4Zd6fDjX+c2X0aiqEXBSColfAQLIhKw5oxqgY9w1bVb7/Q8QB10TxwXQSRYP1/EEkMp4+LNEPI3H3BmsQ/Q9C0HJy0MXKRZd8zCiBMQ/GgqwhzYvSGCUNF+7nEabXyh8OlqLhOm1hWE1+iOkB1m3Q7IG7cBwk5FcU2FTQC1RgM10dBClaBdSKrFRkuSJUtIpcSVRmIxUVbEW2ZQ1pA2MBbUVEDLa28i8Dq5kz9wgAAA==

**Additional context**
 - Game version: 1.0.5.0c (198)

**Comment by mnoreke** [comment]
Please close this issue as it was a pre-Update 1 blueprint.

**Comment by MafiGames** [comment]
Got it! Thanks!

**Comment by MaFi-Games** [comment]
Got it! Thanks!
