### ISSUE TITLE
Pause modes of at least Maintenance Depot (Basic) not cleanly decoupled, might be all upgradeable entities

### ISSUE THREAD

**Issue by thetaphi** [MaFi-Games/Captain-of-Industry-issues#105]
The upgrade of the basic depot is paused by entity pause. No further couplings were tested. Research Lab II exhibits same behaviour.

**To Reproduce**
1. Queue building Maintenance Depot (Basic) or Research Lab (only tried with II).
2. Entity pause it, but do not construction pause it. Watch it getting built.
3. Order an upgrade to it, not changing pause settings.
4. Watch nothing happening until heat death of universe.

**Expected behavior**
Step 4 to be completed slightly sooner.

**Additional context**
 - Game version: v0.3.8

**Comment by MaFi-Games** [comment]
I was able to reproduce this, thanks for the report.

**Comment by MaFi-Games** [comment]
This has been fixed as part of upgrade system refactoring done for EA.
