### ISSUE TITLE
Saved game wont load after v0.5.1 patch.

### ISSUE THREAD

**Issue by The1wt** [MaFi-Games/Captain-of-Industry-issues#1053]
### Issue description

The game was working fine all day, Then it go to the point that I couldn't do anything. Closed the game and steam did the updated patch and now I can only play with a new game. 

### Expected behavior

I expect the game to load my saved game.

### Game version

v0.5.1

**Comment by MaFi-Games** [comment]
Could you please expand on this? Do you expect to play 0.4 save file or was that a 0.5 save file that did not work?  Could you please attach your save file?

**Comment by MaFi-Games** [comment]
Closing as there is not enough information available.
