### ISSUE TITLE
Ship has not enough Diesel error

### ISSUE THREAD

**Issue by agplayswith** [MaFi-Games/Captain-of-Industry-issues#1054]
### Issue description

Hi there, 

maybe I found some bug. I have a shipping dock what it shows 100% diesel in it. But the ship has sign not enough diesel.  

### Expected behavior

fill diesel :)

### Game version

v0.5.1

### Attachments

[23-06-04_12-00-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11645350/23-06-04_12-00-autosave.zip)
[Pictures.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11645352/Pictures.zip)

**Comment by tippyc2** [comment]
same here 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/123210195/1e7aade8-02e1-4377-9547-d208da8c7032)
[canary test.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11858304/canary.test.zip)

**Comment by tippyc2** [comment]
this may be a false indication related to the contract trade not being ready to fulfil.  once the vehicle parts filled up, the ship departed as it should.
