### ISSUE TITLE
Trucks are stopping, stuck

### ISSUE THREAD

**Issue by DrPhroggy** [MaFi-Games/Captain-of-Industry-issues#1070]
### Issue description

For some reason my trucks and excavators are stopping and saying they can't reach a destination (their Mining Control tower usually).  This started during the previous small patch (v 0.5.1 or v 0.5.1a)

### Expected behavior

Normally trucks just return to the tower and then get on with another job.  Now they are stopping and reporting they cannot reach a destination, and will not restart until I click the bullseye (manual drive icon?) and click anywhere.  If I click next to the tower in question they drive up to it, stop, and assume a new job.  (unless they truly are blocked, but that's not the issue I'm reporting, LOL)

### Reproduction steps

Not sure how it starts.  I believe making a change in tower orders may start it.  The vehicles seem to want to return to the tower but think they can't get there for some reason...

### Game version

0.5.1b

### Attachments

[Trucks stopping stuck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11675218/Trucks.stopping.stuck.zip)

**Comment by MaFi-Games** [comment]
Your trucks have no jobs to do, so they want to park next to their mine tower. However that tower is not accessible,  it's on a hill and surrounded with retaining walls. Once that's restored it all works. So doesn't seem to be a bug there.

**Comment by MaFi-Games** [comment]
Closing as there are no action items left. Feel free to file a new bug if you have more info.
