### ISSUE TITLE
Liquid Dump

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1072]
### Issue description

It seems that liquid dump can be set to accept more than one type of liquid, Trouble is a pipe can only carry one type of liquid so you are never going to get more than one liquid arrive.

### Expected behavior

Liquid dump should only be setable to one liquid type

### Game version

Update 1 (0.5.1 (b)

**Comment by MaFi-Games** [comment]
That's for you suggestion but this is not something we plan to implement.  There are ways to dump multiple products via dump, either using trucks or a transport connector.
