### ISSUE TITLE
Unity spam

### ISSUE THREAD

**Issue by GuardianDragonlord** [MaFi-Games/Captain-of-Industry-issues#1073]
**The issue**
upgrade multiple buildings with unity clicking the button maybe too many times

**Expected behavior**
I was expecting the buildings to be build and constructed quickly without any hiccups

**To Reproduce**
I started to put a ramp down then attached a belt to connect one storage to another then started upgrading a bunch of storages for my copper production and then the crash

**Additional context**
1 V0.5.1B

**Attachments**

**Comment by MaFi-Games** [comment]
Sorry, I'm not sure I follow, what is supposed to be the issue here?

**Comment by MaFi-Games** [comment]
Duplicate of #1067
