### ISSUE TITLE
camera bug

### ISSUE THREAD

**Issue by GuardianDragonlord** [MaFi-Games/Captain-of-Industry-issues#1075]
**The issue**
messing around with mining designations and seem to be moving my camera around too quickly

**Expected behavior**
everything would keep going

**To Reproduce**
started adjusting mining destinations adjusting location of mining area and change camera point of view bring it down to a more flat level and then crash

**Additional context**
1 V0.5.1B

**Attachments**

**Comment by MaFi-Games** [comment]
Can you please provide logs for that crash? I assume given you had 3 different instances of crashes during the game, there might be some issues between Unity and your hardware. CoI usually doesn't crash on its own.

**Comment by GuardianDragonlord** [comment]
[logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11690919/logs.zip)

**Comment by MaFi-Games** [comment]
Duuplicate of #1067
