### ISSUE TITLE
negative?unsuable recources

### ISSUE THREAD

**Issue by Crustoqi** [MaFi-Games/Captain-of-Industry-issues#1077]
### Issue description

I cant use some of my recources (iron and the construction oart 1-4).
I included a save file with the bugged recources.

### Expected behavior

idk

### Game version

v0.5.1b

### Attachments

![20230608143449_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135982875/4a9238e2-bcfe-44f8-b5f0-f06b867ba5a0)
[issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11688602/issue.zip)

**Comment by MaFi-Games** [comment]
Interesting. Have you used some cheats or mods that cheat extra resources?

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. Feel free to file a new bug if you have more info.
