### ISSUE TITLE
Truck targeting vehicle moves very slowly/haltingly

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#1079]
### Issue description

When a truck is driving to the position of another vehicle, it makes very slow progress, driving for only a few truck lengths before pausing.  I assume it's doing frequent and aggressive pathfinding to account for a moving target.  However, the behavior is the same when the target is stationary.

In the attached save, the visible truck is assigned to a tree harvester, which is far away.  The tree harvester isn't doing anything, because it's waiting for this truck to arrive and receive the wood.  However, this truck is pausing multiple times a second, and is going to take 5x longer than normal to reach the tree harvester.

### Expected behavior

Truck should move closer to a normal pace, especially if the target vehicle isn't actually moving.

### Game version

0.5.1b (206)

### Attachments

[slow-truck-bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11693283/slow-truck-bug.zip)

**Comment by MaFi-Games** [comment]
Yep, this is strange indeed.

**Comment by MaFi-Games** [comment]
Thanks for your report. This is now fixed on experimental branch!
