### ISSUE TITLE
[bug] Canceling a building on pause will not remove the pause graphic.

### ISSUE THREAD

**Issue by LexiRoxstar** [MaFi-Games/Captain-of-Industry-issues#108]
**Describe the issue**
When you put a building that still needs to be constructed on pause (not the construction but the building itself) and then cancel the construction, the UI graphic element of the pause icon is not removed.

**To Reproduce**
1. Make a building
2. Put it both on construction pause and building pause
3. Cancel the construction

**Expected behavior**
The UI element to disappear

**Additional context**
 - Game version: Beta 0.3.8

**Attachments**
![20220109133459_1](https://user-images.githubusercontent.com/70544474/148682660-481b9f37-a30b-4f20-9873-fce243bd47c0.jpg)

**Comment by MaFi-Games** [comment]
Thanks for the report, we will look into this.

**Comment by zuff-coi** [comment]
The Cancelling Building UI issue has been resolved at some point, but the UI issue for cancelling an upgrade while paused still persists:
![image](https://user-images.githubusercontent.com/108291414/182410798-3fb50bab-765f-497e-9c1a-ff6442493fa7.png)

**Comment by MaFi-Games** [comment]
All these issue should now be gone. Thanks for reporting!
