### ISSUE TITLE
Glass Recycling Ratio Issue

### ISSUE THREAD

**Issue by OhmIsFutile** [MaFi-Games/Captain-of-Industry-issues#1080]
### Issue description

I'm generating more broken glass than I'm consuming glass.

Island has been mostly waiting on terraforming for decades as far as major changes go. I have limited expenses for glass as well, but all of the priorities should be set up correctly to use up broken glass over glass mix which means glass should never back up.

Instead, I seem to be getting 50% more broken glass than I should, which suggests that the recycling formula may not account for the second tier glassmaker which also makes 50% more glass from the same materials compared to the first tier.

### Expected behavior

I should be getting 90% of the used glass back at most, assuming it is spent on things that generate recyclables, so in practice even less than that.

### Reproduction steps

1. Load the attached save (filetype changed to txt for GitHub's requirements, hopefully that doesn't break it when reverting)
2. Compare last year's broken glass production to last year's glass consumption
3. Let the save run and watch the broken glass build up

### Game version

v0.5.1b

### Attachments

[GlassRecyclingBug.txt](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11696911/GlassRecyclingBug.txt)

**Comment by OhmIsFutile** [comment]
After further testing, it seems mostly alright, but I'm not sure how my broken glass could have backed up. I did noticed after a session of over 3 hours assuming there's some kind of issue that only appears over time. I restarted the game and completely closed the loop and the overall amount of broken glass does seem to be very slowly going down.

**Comment by MaFi-Games** [comment]
It's tricky, the broken glass can add up over time in the recyclables and then suddently spike up from recycling. And because it does not compress very well it can suddently seem like there is too much of it. If you find repro where the broken glass really keeps increasing, happy to take a look.

**Comment by MaFi-Games** [comment]
Closing as we don't have anything actionable here. Please file a new bug if you encounter this on the new version again. Thanks!
