### ISSUE TITLE
The excavator still has problems deciding what to do/reaching its destination

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1081]
**The issue**
I have a savegame for you:
[Excavator Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11697108/Excavator.Bug.zip)

The excavator just goes back and forth trying to reach a job

**Expected behavior**
Decide it can't reach destination, pick a *valid* job

**To Reproduce**
Look at savegame

**Comment by MaFi-Games** [comment]
But this happens because there are really no reachable designations. As the excavators on the shore dug themselves in. The designation on the right that would work is outside of the mine tower's area.

**Comment by MaFi-Games** [comment]
Closing as there are no action items left. Feel free to file a new bug if you have more info.
