### ISSUE TITLE
Lighting Glitches, Flichering of Orangish Light

### ISSUE THREAD

**Issue by Joe8707** [MaFi-Games/Captain-of-Industry-issues#1082]
### Issue description

The enviroment/ atomosphere lighting keeps changing, almost like a flicker, with the normal lighting switching to a sunset (orangish) lighting randomly in different rectangular portions of the map. Also the shadows seem to be flashing randomly. I have tried adjusting all the graphics settings and have seen no improvement. The flashing of different lighting and shadows happens many times a second making game play impractical. This is a new bug as I did not have it before last year when I played. 

### Expected behavior

To have normal lighting.

### Reproduction steps

Not sure...

### Game version

v0.5.1B

**Comment by Joe8707** [comment]
After much trying to adjust my graphics card settings, as well as game settings, I still have issues. The game is slow and laggy, and also shadows seems to flash in and out everywhere not making much sense. Also the water in the ocean seems to disappear and reappear randomly as well. Another thing the orange glow flashing randomly only happens if the camera has the horizon in view. Also seem to get a bright white spot like a flash light shining up when zooming in near certain buildings, like building disappears and becomes a bright white opaque light. Not sure how to fix this. Games graphics used to work fine

**Comment by MaFi-Games** [comment]
We are not aware of these issues. What hardware are you running? Are your driver upda to date? Can you share some video of the issue you see and your log files?

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. Please file a new ticket if you have more info. Thanks!
