### ISSUE TITLE
Cooled Caster

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1083]
### Issue description

The Metal caster takes 40secs per cycle. The Cooled caster says (in the tooltip) that it uses water to speed things up!
The Cooled Caster takes 40 secs per cycle. It is no quicker at all.

### Expected behavior

Cooled Caster cycle to be quicker than the Metal caster cycle

### Game version

Update 1 (0.5.1 (b)

**Comment by MaFi-Games** [comment]
The comment that it "speeds up the process" will be removed in the next patch, thanks!
