### ISSUE TITLE
Farm alert when there should not be one

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1084]
### Issue description

Hi Farm working fine. Place the farm on pause and a Red Alert pops up "Farm has no workers", i know, i paused it. 

### Expected behavior

Error should not pop when i pause the farm

### Reproduction steps

Pause a working farm

### Game version

Update 1 (0.5.1 (b)

### Attachments

![Farm lacks workers](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/135761933/408c5efd-72a5-4059-8235-c1040fd10262)
[Fourth.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11703300/Fourth.zip)

**Comment by DeadlyKitten37** [comment]
+1 to fix this, is is annoying to see this error show up when the point of pausing is to remove the workers so they can do something more important.

If it is intended for a paused building to complain about workers, then I request a change in intended behavior.
