### ISSUE TITLE
Assembly building recipe times are wrong

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1087]
### Issue description

Does not matter which assembley building or the recipe the times are wrong.
If the stated time is 40 seconds it actually takes 80 seconds
If the stated time is 80 seconds then it takes 160 seconds
The actual time taken to make something is double the stated time

### Expected behavior

if it says it takes 40 seconds it should take 40 seconds

### Reproduction steps

load save attached and take a stopwatch to the assemblers

### Game version

Update 1 (0.5.1 (b)

### Attachments

[Fifth.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11706522/Fifth.zip)

**Comment by MaFi-Games** [comment]
I cannot reproduce the issue. I loaded the save file and checked several assemblers and their production times matched their recipes durations.
