### ISSUE TITLE
Packed Recyclables on Flat Conveyor Slope visual bug

### ISSUE THREAD

**Issue by Rockeye1** [MaFi-Games/Captain-of-Industry-issues#1088]
### Issue description

Visual display bug.

When Packed Recyclables are transported along a Flat Conveyor or Flat Conveyor II that is sloped (changing elevation), the visual object of the recyclable laying on the belt tilts to the side instead of tilting 'backward' to match the slope of the belt.

With a Conveyor II, the second item in the stack tilts correctly but the first item in the stack still tilts to the side instead. I did not test with Flat Conveyor III.

It only seems to happen with Packed Recyclables. See attached image.

### Expected behavior

The displayed recyclable pack should tilt to match the slope of the belt.

### Reproduction steps

1. Build a Flat Conveyor with an elevation change.
2. Transport Packed Recyclables along the conveyor and observe the strange tilting.

### Game version

v0.5.1

### Attachments

![displaybug](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/136123143/7b1d413b-2226-441d-9aeb-55f7279a3935)

**Comment by Rockeye1** [comment]
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/136123143/452446bf-98d1-4f20-9082-790b281dab7c)

**Comment by MaFi-Games** [comment]
Thanks for your report! This is now fixed on experimantal (v0.5.2a)
