### ISSUE TITLE
Electric Boiler research uses level 3, is in level 4 area

### ISSUE THREAD

**Issue by PTTG-ACTUAL** [MaFi-Games/Captain-of-Industry-issues#1089]
### Issue description

This may simply be a space limitation, but the electric boiler research is clearly in the level 4 research area, but needs only level 3 or better.

See screenshot.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/74290971/5bddad5b-18ab-45d6-b5e5-d34b1ea073e7)

### Expected behavior

Judging from the position, I suspect it's supposed to be level 4, though nothing is stopping it from working in level 3 either.

### Reproduction steps

Open the research menu.
Scroll right...

### Game version

1 0.5.1b

**Comment by MaFi-Games** [comment]
Thanks for your report! This was fixed in v0.5.2a which is now on the experimental branch on Steam.
