### ISSUE TITLE
GUI : Turbine do not have the switch 'show every /60s'

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#109]
**Describe the issue**
Turbine and Urbbine II do not have the little switch to enable or disable the  receipe every 60s.

**Expected behavior**
Have the swit button on GUI to switch between '60s mode' and 'receipe mode'

**Additional context**
latest

**Attachments**
![Screen Shot 01-08-22 at 02 55 PM](https://user-images.githubusercontent.com/96617483/148684060-0e75b7e0-d3aa-42d9-b8ba-691c632712b0.PNG)
![Screen Shot 01-08-22 at 02 54 PM](https://user-images.githubusercontent.com/96617483/148684061-358df720-fbcb-4ede-b7b9-0e2fa061cd4f.PNG)

**Comment by MaFi-Games** [comment]
Thanks for reporting this, it has been added to all turbines and also to diesel generators.
