### ISSUE TITLE
Game stuttering

### ISSUE THREAD

**Issue by xxaugustasxx** [MaFi-Games/Captain-of-Industry-issues#1092]
### Issue description

Have game with less than 24 hours of gameplay. I'm getting a stutter every 3 seconds.

### Expected behavior

I would expect this to be smooth 

### Reproduction steps

Load save. 

Watch screen. 

Stuttering happens

https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/114313631/fa5a8ccf-36b1-4513-9edd-4e85bc3a409f

### Game version

v0.5.2

### Attachments

[save_23-06-09_20-32-21.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11712565/save_23-06-09_20-32-21.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report! This is now fixed on  theexperimental branch. The fix will make it to main branch in few days.

**Comment by MaFi-Games** [comment]
Fixed in v0.5.2
