### ISSUE TITLE
Trucks not being given jobs

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1093]
### Issue description

I have stuff waiting to be built and trucks sitting idle saying "No Jobs". There are building jobs waiting to be done.

in my save look where the assemblers are for building jobs. Now look right to the dump and there are 4 trucks just sitting idle. The building jobs have been waiting for some time.

This gets worse as you build more. This a real negative imho.

### Expected behavior

I expect idle trucks to do the jobs i have given them

### Reproduction steps

Wait until you get as far as i have

### Game version

Update 1 (0.5.1 (b)

### Attachments

[Fifth.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11712908/Fifth.zip)

**Comment by MaFi-Games** [comment]
I don't see any issue there. The belt can't finish because you are out of rubber and the assembler can't finish because it requires CP III which you don't even produce yet.
