### ISSUE TITLE
Possible Pipe/Tanks problem

### ISSUE THREAD

**Issue by c0nnex** [MaFi-Games/Captain-of-Industry-issues#11]
**Describe the issue**
have a descent fuel production setup with a backbuffer of 16 Tanks for raw oil , and 12 tanks for fuel.  All tanks are full. Then after some time (around the time messages start to popup that an oil rig has a full storage because freighter can't offload anymore) suddenly the fuel and raw oil drop to 0 (giving me a hard time because everything stops)

I suspect a pipes problem

**To Reproduce**
1. Load Save from #8 
2. Stop all stuff that ueses fuel until a all tanks (rawoil and gas) are full and warning from oil rigs start to appear
3. Wait until fuel becomes empty even that there was plenty

**Additional context**
 - Game version: 0.2.4

**Attachments**
If applicable, add save files, screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`)
Logfile from longrun session 0.2.4 (10h):
[21-09-23_00-01-26_6756.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7215178/21-09-23_00-01-26_6756.log)
Logfile from longrun session (18h) 0.2.2
[21-09-19_16-42-46_7345.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7215186/21-09-19_16-42-46_7345.log)
2
Logfile forn 8 h Session 0.2.
[21-09-22_04-43-24_2757.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7215191/21-09-22_04-43-24_2757.log)
3

Issue occoured in ALL sessions. Video proof available on my twitch channel
(I can look for timestamps if needed)

**Comment by MaFi-Games** [comment]
This is rather strange. I have loaded the save, paused the two outgoing pipes from the last storage and all storage have filled and are full for ~10 minutes. Only trucks occasionally pickup fuel.

Would you mind trying this again and providing more precise repro steps? I was trying this on v0.2.5.

![2021-09-25_23-43](https://user-images.githubusercontent.com/90082857/134796777-6d8d8512-80d6-4c5e-8071-77b6c888d095.png)

**Comment by c0nnex** [comment]
I'll see if i can pull somehow some stats via the api.
Happened in 2.0.5 again. This really looks like the pipes are "dropping" contents every now an then. Looking at the graphs when it happens, always the "fuel usage" suddenly went crazy (to the available max) , "oil produced" goes max then 0.
Really odd.
I'll recheck with 2.0.6

**Comment by MaFi-Games** [comment]
Thanks for reporting, unfortunately we were not able to reproduce this. If you encounter this again in upcoming beta release, please create another report.
