### ISSUE TITLE
GUI : "storage alert"not localised

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#110]
**Describe the issue**
![Screen Shot 01-08-22 at 11 12 AM](https://user-images.githubusercontent.com/96617483/148684207-2214382c-b0e6-41c4-a1fa-2cd78fbb8ddb.PNG)
the "storage alert" is not available on tools translation for translation.

**Expected behavior**
be present on translate.captain-of-industry.com for translation

**Comment by MaFi-Games** [comment]
Thanks for pointing this out, we will be likely adding new strings closer to the Early Access release.

**Comment by MaFi-Games** [comment]
Should be localized now.
