### ISSUE TITLE
Pressed Waste can be deleted from Shipyard

### ISSUE THREAD

**Issue by altmank** [MaFi-Games/Captain-of-Industry-issues#1105]
### Issue description

I observed that you can delete pressed waste using unity to move it from storage to the shipyard and then deleting the product from the shipyard. I'm assuming this is not intended but wouldn't mind if you leave it :)

### Reproduction steps

1. Press waste, transport into storage
2. Unity delete it from storage to the Shipyard
3. Delete the product from the shipyard

### Game version and build number

v0.5.1b

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Will be fixed in the next patch. Thanks for your report!
