### ISSUE TITLE
vehicles running out of fuel randomly

### ISSUE THREAD

**Issue by Eric-Korsund** [MaFi-Games/Captain-of-Industry-issues#1106]
### Issue description

Trucks and haulers run out of fuel randomly in 1.05 while not a problem in captain and sailor difficulty's could be a problem with admiral levels.  Happens after playing a  an hour or so then becomes common, sometimes happing 3 or four times in a minute other times an hour or two may pass between occurrences. I am attaching a save file with a truck out of fuel it is ironically next to a fuel station.

### Reproduction steps

[beachu1 out of gas.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11729421/beachu1.out.of.gas.zip)

### Game version and build number

v0.52b209

### Operating system

Windows

**Comment by NanoCE** [comment]
I had a similar issue with my forestry assigned trucks but all the other trucks work fine. I was able to circumnavigate the issue by having the forestry assigned trucks deliver to a much closer warehouse rather than the one on the other side of my island.

**Comment by Eric-Korsund** [comment]
still happening with version 0.53b have attached save file with a truck out of fuel warning on screen 
[beachu1 out of gas.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11827869/beachu1.out.of.gas.zip)

**Comment by MaFi-Games** [comment]
We recently improved this so that out of fuel notifications don't fire when a vehicle is about to go or already went for fuel. This should fix these cases. Note that trying to prevent vehicles running out of fuel before they finish any job is difficult and could even be punishing as they would become less utilized.
