### ISSUE TITLE
Game freezes when put in fullscreen instead of windowed.

### ISSUE THREAD

**Issue by Rancourium** [MaFi-Games/Captain-of-Industry-issues#1107]
### Issue description

When I put the game in fullscreen mode, the game freezes but still runs. If I click somewhere the command still happens but I don't see it. If I tab out and back in I can see what happened (menu opened, map zoomed out), but the screen is still frozen.

### Reproduction steps

1. Put the game in fullscreen mode (the game crashed once because I tabbed out and doesnt want to boot up in fullscreen anymore, so the bug keeps happening over and over)

### Game version and build number

v0.5.2 (b209)

### Operating system

Windows

**Comment by Rancourium** [comment]
Reinstalling made it boot back up in fullscreen. I didn't try tabbing out because I wanted to play!
Great game!

**Comment by MaFi-Games** [comment]
Seems like an issue coming from Unity or drivers. Glad you managed to resolve it!

**Comment by Rancourium** [comment]
Actually it's not resolved. The uninstall-reinstall trick worked only once.
I'm now stuck in windowed mode and the game still freezes whenever I modify
that setting.

I'm still enjoying the game a lot like this, although being in fullscreen
would make it even better!

Congrats on the great game, and I hope this gets fixed in some future patch
I guess.

Cheers
