### ISSUE TITLE
Transport of compacted items

### ISSUE THREAD

**Issue by steveconrad** [MaFi-Games/Captain-of-Industry-issues#1113]
### Issue description

I noticed that trucks that collect trash that's been compacted do not collect a whole truck load.
I had a storage hut almost completely filled with compacted trash. Yellow trucks would arrive and load up but they would only take something like 35 units away, not the 60 I was expecting.

### Reproduction steps

Watched this happen on my save for a minute or two. Never saw a truck pick up a full load.

### Game version and build number

v0.5.2 (B209)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This sounds like you have partial trucks enabled in logistics, is that the case? Otherwise a save file that reproduces this would be helpful.

**Comment by steveconrad** [comment]
Yes I think you are correct and that I have partial allowed. 
So if there are 100s to pick up, why would the truck only pick up less than a full load.
I'll have to check tonight if the destination had space, that I didn't notice at the time.

**Comment by steveconrad** [comment]
Ok - had a chance to check the game again. I did have partial on, and I disabled export to let it build up to around 150 units available. Re-enabled export and immediately two trucks came in, both collecting 60 each. Guess it was down to there being no export space when I was looking first. 
OK no bug here :)  Thanks for yout time.
