### ISSUE TITLE
Bakery use corn porridge instad of water

### ISSUE THREAD

**Issue by C2K23J** [MaFi-Games/Captain-of-Industry-issues#1115]
### Issue description

I wanted to produce buns in the bakery, which requires flour and water to make bread. I made a mistake and connected the pipe with the corn porridge. The bakery works anyway. It's not bad now, but maybe you'll take a look at it :)

### Reproduction steps

1. Make the Bakery, connect the wrong pipe, now you have Corn Bread :)

### Game version and build number

0.5.2b

### Operating system

Windows

**Comment by MaFi-Games** [comment]
It's most likely because water got deliver by trucks. If you really found a case where corn mash gets consumed via connected pipe, please provide us with a save file where this occurs.

**Comment by C2K23J** [comment]
That Sound possible, thank you for your fast answer

Greetings Chris

Captain of Industry ***@***.***> schrieb am Mi., 14. Juni
2023, 20:54:
