### ISSUE TITLE
Excavator stuck in infinite loop and failing to do work

### ISSUE THREAD

**Issue by NanoCE** [MaFi-Games/Captain-of-Industry-issues#1116]
### Issue description

I have had multiple instances of excavators getting stuck in trying to reach a specific dig location and failing to do so. It will realize this a second after it starts travel and then moves back. This continues and loops, causing the excavator to fail to do anything but move back and forth within the same few tiles. The game does not notify me of any issue either. I can also confirm that there are valid locations to mine as if I remove the mine designation in question, the excavator will correctly start work elsewhere.

I also reported another instance of this issue [here ](https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/938) a few weeks ago, but it has yet to be replied to.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8260901/059e0fbc-590c-420d-b8ca-84e248a394c4)

### Reproduction steps

It should currently be happening to the only excavator working my only active limestone mine in the attached save file. I'm not sure why it occurs or how to reproduce elsewhere, but it has happened multiple times before. See the other github issue link for another example with save file. It has happened to both the small excavator and larger excavator, so this looks to be happening to all excavator types.

### Game version and build number

Update 1 v0.5.2 (209)

### Operating system

Windows

### Attachments

[save_23-06-14_12-47-22.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11749964/save_23-06-14_12-47-22.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report, this will be fixed in the next patch.

**Comment by NanoCE** [comment]
While the excavator stops moving/looping between two points on the terrain, its now stuck looping at the same point, between "Searching for a valid terrain designation (DoJob, Stopped)", "Driving to Destination (DoJob, Stopped)", and "Loading cargo (DoJob, Stopped). This is with the same save file apart of the original report.

**Comment by MaFi-Games** [comment]
What version are you playing on? This was fixed in `v0.5.2b`. It will be on experimental soon though.

**Comment by NanoCE** [comment]
Ahh, that was just a coincidence then. You mention it will be fixed in the next patch, and steam puts out a patch within the next hour. I just assumed 0.5.2a was said patch. I'll take a look again when v0.5.2b releases. Sorry for the confusion.

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3 which is now on the experimental branch on Steam. It will be available on the main branch in a couple of days. Please let us know if you have any issues again.
