### ISSUE TITLE
Search box selected even though it shouldn't be

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1119]
### Issue description

After clicking on the show /60 checkbox (on or off) in a building
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/ed52754d-9479-41c1-a0f6-31ed08c683ad)
If you press A (to pan left), it will go to the search box instead
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/b9f36898-e1a2-4bdd-ae43-f43177941814)
this shouldn't happen, and is quite annoying

### Reproduction steps

See previous

### Game version and build number

Update 1 0.5.2 (209)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for reporting. Will be fixed in the next patch!
