### ISSUE TITLE
Trucks and Fuel Stations

### ISSUE THREAD

**Issue by iProfessore** [MaFi-Games/Captain-of-Industry-issues#1122]
### Issue description

Trucks do not stop at fuel stations, they go to fuel storage instead.

### Reproduction steps

Place a fuel station and see no trucks fill up there

### Game version and build number

Update 1 0.5.2 (209)

### Operating system

Windows

**Comment by iProfessore** [comment]
I have watched carefully and not seen one single truck go to a fuel stationOn 15 Jun 2023 17:30, Captain of Industry ***@***.***> wrote:
If storage with fuel is closer, they will prefer the storage. That works as intended.

**Comment by MaFi-Games** [comment]
Righ. Feel free to provide a save file of a situation where a fuel station is closer than a storage and is being ignored.

**Comment by NIRE005** [comment]
I am playing in the past 2 weeks every day and yes they don't always use the fuel station, but I mainly use them to assign a few trucks that drive around filling up excavators
