### ISSUE TITLE
Грузовики проезжают сквозь стены и застревают в них

### ISSUE THREAD

**Issue by sallfris** [MaFi-Games/Captain-of-Industry-issues#1123]
### Issue description

Грузовики проезжают через угол стен, застревают в них на некоторое время, потом продолжают движение.

### Reproduction steps

1. Загрузить сохранение
2. Найти место со скриншота
3. Снять игру с паузы
4. Для повторения подождать

### Game version and build number

v0.5.2 (209)

### Operating system

Windows

### Attachments

![2023-06-16_01-13-15](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3198304/ce0c98ec-05e7-4b98-a4af-f1fc68a89172)
![2023-06-16_01-25-07](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3198304/82ab0050-2e45-4ef1-ab8b-02b77f03148f)
[bug-16.06.2023.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11763725/bug-16.06.2023.save.zip)

**Comment by MaFi-Games** [comment]
Duplicate of #338
