### ISSUE TITLE
Truck busy indicator now always shows stable.

### ISSUE THREAD

**Issue by heckad** [MaFi-Games/Captain-of-Industry-issues#1127]
### Issue description

After update to `v0.5.2a` busy indicator not work any more.

### Reproduction steps

1) Assign all trucks to any control tower
2) Wait a while
3) Check the indicator (it won't change)

### Game version and build number

v0.5.2a

### Operating system

Windows

**Comment by Stalkie** [comment]
Same here, been like this the last few versions. Always on "Stable", and a whole bunch of jobs not getting done.

**Comment by MaFi-Games** [comment]
Please provide a save file where this occurs so we can investigate.

**Comment by Stalkie** [comment]
Sure thing. In this save they have quite hard time to emtpy slag, plenty of dumping zones to the west.
Also the fuel stations on the map is not getting refilled despite plenty available to grab from.
No strange routing/assignment put on these either.

I have noticed that there almost always is 1 "available to assign" truck in idle. But he really shouldnt be idle. 
I've not seen the stable-sign change anytime during this save.

Save: [Stable_trucks.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11782492/Stable_trucks.zip)
![bild](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/d6664121-8db2-47dd-a0de-264b630cbcfc)

![bild](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/918e79c6-ae83-45ae-82c9-853c00f5ccf6)
![bild](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/1865d182-6332-4fb0-83c2-5a5308654cf8)

**Comment by heckad** [comment]
After `v0.5.3c` it seems to work as expected.
