### ISSUE TITLE
forestry tower not diconnected from storage after deleting it

### ISSUE THREAD

**Issue by VerisZG** [MaFi-Games/Captain-of-Industry-issues#1128]
### Issue description

look at the image - the line stays, but the tower is deleted

### Reproduction steps

Repo:
1. Export forestry tower to a storage.
2. Delete forestry tower.
3. Look at the storage - the line connecting to now deleted tower still exists.

### Game version and build number

last experimental

### Operating system

Windows

### Attachments

![2023-06-18 01-15-07](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1569499/12f33375-3b31-4847-b8cc-ea70b02ad3e7)

**Comment by lKronerl** [comment]
Yes, it's true... It's happening to me too

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3 which is now on experimental branch on Steam. It will be available on the main brach in couple of days. Please let us know if you have any issues again.
