### ISSUE TITLE
Completing research repins default resources on side of screen that are unpinned.

### ISSUE THREAD

**Issue by zytukin** [MaFi-Games/Captain-of-Industry-issues#113]
**Describe the issue**
If you change what resources are pinned on the right side of the screen, any default resources you have unpinned will get repinned when a research gets completed.

**To Reproduce**
1. Unpin default resources
2. Wait for a research to complete
3. The resources that were pinned by default get repinned

**Expected behavior**
Listing should retain and remember what is and isn't pinned

**Additional context**

 - Game version: 0.3.9

**Attachments**
![20220114061430_1](https://user-images.githubusercontent.com/34819700/149507791-9cdc832e-f829-4a27-9b82-ae92bade3937.jpg)
![20220114061435_1](https://user-images.githubusercontent.com/34819700/149507821-10762090-586f-4600-b9d6-3a9a32e6f9d4.jpg)

**Comment by MaFi-Games** [comment]
Thanks for reporting! Fixed in 0.3.11d
