### ISSUE TITLE
Microchip recipe incorrect time

### ISSUE THREAD

**Issue by sgroef** [MaFi-Games/Captain-of-Industry-issues#1131]
### Issue description

The microchip recipes (all stages) have a time of 30 seconds while they only seem to take 10 seconds.

### Reproduction steps

1. Let a microchip factory make any recipe.
2. Observe how it creates the part in 10 seconds instead of 30.

### Game version and build number

v0.5.2A

### Operating system

Windows

**Comment by MaFi-Games** [comment]
I highly doubt it, but please feel free to provide a save file where this occurs.

**Comment by sgroef** [comment]
Nevermind, it's because I'm playing on triple speed. I guess the summer heat is making me dumb.
