### ISSUE TITLE
Building animation stuck when quickly deconstructing, canceling and uncanceling

### ISSUE THREAD

**Issue by daemonazazel** [MaFi-Games/Captain-of-Industry-issues#1132]
### Issue description

I had some U-shaped conveyors from my coal mine bottom to the top. They were mostly elevated. Since I started digging underneath I started deconstructing them, but then changed my mind and canceled the deconstruction. For some reason I changed my mind again in quick succession and uncancelled the deconstruction letting them deconstruct. I might have thrown in unity at different points.

In the end they were deconstructed but some of the gray blocks used to mark the deconstruction phase remained hanging in the air. They have stayed for more than an hour and have survived multiple save, close game and load cycles.

They are no clickable, neither individually nor with a selection box. I tried using DEL and unitry on them.

Savegame with them attached. They hang above the coal mine.

### Reproduction steps

See description

### Game version and build number

0.5.2A

### Operating system

Windows

### Attachments

[1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11782086/1.zip)

**Comment by daemonazazel** [comment]
Fix with 0.5.3 confirmed. Thanks guys and gals. That was quick. :-)

**Comment by MaFi-Games** [comment]
We fixed the floating concrete but we haven't been able to reproduce how it appeared in the first place. If you ever succeed in making it appear again, please let us know!
