### ISSUE TITLE
fast breeder reactor recipe book entry is wrong 

### ISSUE THREAD

**Issue by nuclear-enthusiast** [MaFi-Games/Captain-of-Industry-issues#1134]
### Issue description

the entry of the fast breeder reactor displays the wrong numbers in terms of steam and water converted 
entry is 256 water to 256 steam at level 4
real values are 384 water to 384 steam at level 4

### Reproduction steps

open recipe book and compare

### Game version and build number

v0.5.2a (b215)

### Operating system

Windows

### Attachments

![grafik](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137007085/18dee14a-ae83-48ab-b0d2-0569ad2f4b9b)
![grafik](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137007085/29447eb8-8316-4f73-8ccc-a2a0b8d04665)

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3 which is now on the experimental branch on Steam. It will be available on the main branch in a couple of days. Please let us know if you have any issues again.
