### ISSUE TITLE
Retaining Wall warning icon gets stuck ON if i enter F11 photo mode

### ISSUE THREAD

**Issue by NSMY** [MaFi-Games/Captain-of-Industry-issues#1135]
### Issue description

Retaining Wall warning icon gets stuck ON if i enter F11 photo mode, only way to remove them is reloading save. also happened before v0.5.2a

### Reproduction steps

1 Load save
2 press F11
3 Look at retaining walls icons are visiable, but No warnings
4 Reload save Icons gone

### Game version and build number

v0.5.2a (b215)

### Operating system

Windows

### Attachments

[sand.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11787169/sand.zip)
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11787184/Logs.zip)

**Comment by NSMY** [comment]
4 consecutive screen shots fresh load, entered Photo mode, Exited Photo Mode, icons Showing with no alert warnings
they will not disappear unless Reload


![20230619205845_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/95662519/ec10cd94-0d63-4d20-b7bc-8c86b55abae3)
![20230619205849_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/95662519/9b1c6015-f226-4939-b1a5-392df362437a)
![20230619205852_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/95662519/ef67d9ed-a741-4448-adec-36b9356442ae)
![20230619205901_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/95662519/cac782eb-7787-4907-ac5c-43e8b0e42c61)

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3 which is now on experimental branch on Steam. It will be available on the main brach in couple of days. Please let us know if you have any issues again.
