### ISSUE TITLE
Permanently stuck vehicle

### ISSUE THREAD

**Issue by TheSilencer108** [MaFi-Games/Captain-of-Industry-issues#1138]
### Issue description

I have a tree harvester which is completely stuck. I initially thought it was a mundane stuck vehicle situation as it was stuck pathing to a tree that appeared to be within harvest range, but when using vehicle recovery, it remained stuck in the depot.

Upgrading the depot; deleting the depot, rebuilding and recovering again; attempting to scrap- no change in behavior. It has persisted across multiple saves/reloads. Recovery just teleports the vehicle inside the depot, where it remains stuck.

There is a similar complaint currently in the Discord involving an excavator as well, so it may not be limited by vehicle type, although I did not see identical issues in Github.

### Reproduction steps

Load save
Observe broken harvester near vehicle depot (just south of copper mine)

### Game version and build number

Update 1 | v0.5.2a(b215)

### Operating system

Windows

### Attachments

[save_23-06-18_16-07-50-BrokenTreeHarvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11792343/save_23-06-18_16-07-50-BrokenTreeHarvester.zip)

**Comment by TheSilencer108** [comment]
I was able to find a save in the initial stuck state/
[23-06-18_02-22-autosave-paused_BrokenTreeHarvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11794041/23-06-18_02-22-autosave-paused_BrokenTreeHarvester.zip)

**Comment by TakbokLouw** [comment]
Seems to be fixed on the experimental branch v0.5.3a (b220) for me.

**Comment by MaFi-Games** [comment]
Thanks for reporting this! Should be fixed in v0.5.3a, please file a new issue if it occurs again.
