### ISSUE TITLE
unknown game crash

### ISSUE THREAD

**Issue by Astree13** [MaFi-Games/Captain-of-Industry-issues#114]
**Describe the issue**
Game freezed while laying down a bsmelters belt on the ground. 

**To Reproduce**
Unknown reason

**Expected behavior**

**Additional context**
 - Game version: 0.3.7

**Attachments**
 last log file
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7873904/Logs.zip)
s

**Comment by MaFi-Games** [comment]
Closing as this is an old beta issue, and we don't have enough information.
