### ISSUE TITLE
The tree harvester gives an erroneous error

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1142]
### Issue description

There are available trees
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/50b1594e-e3a0-4ede-86a2-aeee9a9bcfbd)
This happened after it gave the out of fuel error, and I manually told it to go over to a fueling spot
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/30c23811-cbf0-4f88-9dbf-589bb45eef21)
I also question why it didn't go fuel itself to begin with?
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/0322cb63-56ef-4bbe-b2f7-89b4ac1f2555)

### Reproduction steps

See above

### Game version and build number

Update 1 0.5.3 (218)

### Operating system

Windows

### Attachments

Savegame
[Harvester bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11795669/Harvester.bug.zip)

**Comment by MaFi-Games** [comment]
Would you have a save file before when it had no fuel and you had to give it a manual order to go for fuel? I assume the issue was that the refueling truck couldn't get there in time?

**Comment by Prometheus0000** [comment]
The closest I have is 2 hours before, so I don't think that will help. Also, you can't assign a refueling truck to a tree harvester, you can only assign it to a forestry control tower, and it wasn't assigned to one at the time. I don't think they look for vehicles they're not assigned to to refuel, and it has to go get the fuel itself?

**Comment by TheEvilGreebo** [comment]
I have a similar bug on The Beach.  I've set the save file up with just one tree selected - it's on perfectly level ground and the harvester actually can't find any of the trees immediately in that area around the blast furnace.  You'll find the camera zoomed in on the exact problem spot.

[TreeBug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11857202/TreeBug.zip)

**Comment by MaFi-Games** [comment]
I think this was fixed in one of our previous patches. The save file already got into a state where it's not possible to verify if the fix would work for this or not. So I'm closing this as completed but if this occurs again please definitely file a new bug.
