### ISSUE TITLE
0.5.3 introduced strange belt animations

### ISSUE THREAD

**Issue by VerisZG** [MaFi-Games/Captain-of-Industry-issues#1147]
### Issue description

sometimes i stumble upon empty belts that have ADHD
see attached video

### Reproduction steps

1. just scroll the map, you'll find one

### Game version and build number

0.5.3

### Operating system

Windows

### Attachments

https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1569499/e1db04ec-5afd-49d3-9d83-f2c23ed0a3f2

**Comment by Prometheus0000** [comment]
I can't see your video, but I assume the thing I'm seeing is the same, it started with the 0.5.3 (218) version.

**Comment by MaFi-Games** [comment]
This was fixed in 0.5.3a, please let us know if there are still some issues.

**Comment by VerisZG** [comment]
Thank you. Lighting speed support. You're the best, guys.
