### ISSUE TITLE
Unbuilt building has the uneven terrain collapse warning

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1148]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/ddd71afc-3bf9-490a-842a-3c2eec1059a3)
I'm not really sure it should or not. It should probably get a slightly different warning, like "Building cannot be built here due to uneven terrain" or something (you can't re-place the building there, though I didn't try actually building it.

### Reproduction steps

1) Place a ghost building on the edge of the terrain
2) Dump some stuff next to it, this *still* causes the terrain on the previously good terrain to mess up, even after U1
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/fc81a151-08b3-4e8a-86b1-b1b8a0ca0f5c)
3) Building gives warning

### Game version and build number

Update 1 0.5.3 (218)

### Operating system

Windows

### Attachments

Savegame
[collapse bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11809367/collapse.bug.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report but this works as intended. We will consider better label for this in the future.
