### ISSUE TITLE
Seawater Pump & Seawater Pump (L) have the same output.

### ISSUE THREAD

**Issue by mikitz** [MaFi-Games/Captain-of-Industry-issues#115]
**Describe the issue**
The Seawater Pump and the Seawater Pump (L) both have the same outputs: 120 / 60s

**To Reproduce**
I don't know; I think it's just some XML data issue or whatever you're using to store your structure data.

**Expected behavior**
I would expect the Seawater Pump (L) to produce more.

**Additional context**
 - Game version: BETA 0.3.9

**Attachments**
N/A

**Comment by MaFi-Games** [comment]
This is expected. Their difference is not in throughput but in size (L can overcome taller cliffs). Maybe we should rename it to make it clearer.

**Comment by MaFi-Games** [comment]
Second tier of pump was renamed.
