### ISSUE TITLE
Unable to deselect deleted foresttower from storage unit

### ISSUE THREAD

**Issue by alphatwins** [MaFi-Games/Captain-of-Industry-issues#1150]
### Issue description

I deleted a forest tower that had wood storage attatched. But when i rightclick to remove the link, nothing happens. 

### Reproduction steps

Deleted forest tower, while storage was attached. then was unable to remove the foresttower from the storage.

### Game version and build number

v0.5.2a

### Operating system

Windows

### Attachments

[forest tower wood storage.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11819359/forest.tower.wood.storage.zip)

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3c, thanks for reporting!
