### ISSUE TITLE
I keep having to reset forestry work area.

### ISSUE THREAD

**Issue by PhatzDomino** [MaFi-Games/Captain-of-Industry-issues#1151]
### Issue description

Randomly, it seems I have reset the work area for my forests.  All vehicles tending to said areas will go back to their towers and do nothing until I redo reselect their area.  Then they all go back to work for a while.

### Reproduction steps

Select TOWER 1, then select "edit area" and replace already placed area.  You will see tree planter go back to work.

### Game version and build number

V0.5.3a

### Operating system

Windows

### Attachments

[Manual (Pre Forestry Issue).zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11819677/Manual.Pre.Forestry.Issue.zip)

**Comment by DarkoC21** [comment]
I have also been having the same issue, do not even need to reset the work area much, even just clearing one square can jump start them again. It is only happening on one of my towers too, the first one I placed is working as expected.

Was on 0.5.3a, however still having the issue on 0.5.3b
Windows

The larger one up on the top section is having the issue.
[save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11829571/save.zip)

**Comment by Keranik** [comment]
I am also experiencing this issue.

**Comment by DarkoC21** [comment]
So far seems fixed with 0.5.3c
Thanks 😃

**Comment by MaFi-Games** [comment]
Thanks for reporting. This should be now fixed! Feel free to file new ticket if you still experience some issues.
