### ISSUE TITLE
Dumping designation considered valid but never completed, causing stuck truck

### ISSUE THREAD

**Issue by Keranik** [MaFi-Games/Captain-of-Industry-issues#1153]
### Issue description

When a dumping designation contains two ramp pieces that are perpendicular to each other, the designation is never completed, causing trucks to become stuck attempting to do it forever.

### Reproduction steps

I try to attach save file but it is too large for upload (over 25MB), but I attached a screenshot to show.

If you make two ramp designation perpendicular to each other, truck will try forever to fill the spot but only sit around idle.  Even after removing designation, truck continues to stay stuck.

### Game version and build number

v.0.5.3a

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/36f837e9-ce38-4475-a764-9916eab90d2f)

**Comment by NanoCE** [comment]
This isn't a bug. You gave it two conflicting orders with one to dig and the other to place in the dug spot. The leveling tool looks to be working as intended.

**Comment by MaFi-Games** [comment]
As NanoCE mentioned this seems like loop in how you set up your designations.
