### ISSUE TITLE
The large cooling tower recipes are not listed on the research page

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1155]
### Issue description

I assume someone forgot to re-add them when they were removed from the nuclear one.

### Reproduction steps

Look at the power generation IV research

### Game version and build number

Update 1 0.5.3b (221)

### Operating system

Windows

**Comment by NanoCE** [comment]
I can confirm this issue is also present in the release version of the game, not just in experimental.
