### ISSUE TITLE
Exhaust Scrubber not working

### ISSUE THREAD

**Issue by otsang87** [MaFi-Games/Captain-of-Industry-issues#1156]
### Issue description

Exhaust scrubber no working. cannot input the exhaust gas.

### Reproduction steps

Exhaust scrubber no working. cannot input the exhaust gas.

### Game version and build number

v0.5.2a (b215)

### Operating system

Windows

### Attachments

[12345.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11834008/12345.zip)

**Comment by NanoCE** [comment]
I believe you grabbed and attached the wrong save file. That save is for v0.4.14b and can't be loaded in the latest patch. I tried loading it in 0.4.14b and noticed the save has nearly nothing built.
