### ISSUE TITLE
Copy Cut Past works via CTRL+C / CTRL+X / CTRL+V while not having researched the tools

### ISSUE THREAD

**Issue by Ryflex** [MaFi-Games/Captain-of-Industry-issues#1157]
### Issue description

Copy Cut Past works via CTRL+C / CTRL+X / CTRL+V while not having researched the tools

### Reproduction steps

1. Load new game.
2. Copy/Cut/Paste anything via CTRL+C / CTRL+X / CTRL+V

### Game version and build number

v0.5.2a (b215)

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7933873/cf1bc58b-d1b0-4d77-84dc-0431972df246)

**Comment by NanoCE** [comment]
I can confirm that the key binds work right away after starting a new save.

**Comment by MaFi-Games** [comment]
That works as intended.

**Comment by NanoCE** [comment]
@MaFi-Games Then why have the research in the first place? Just to unlock the UI elements? The research seems silly to have if this is the intended mechanic.
