### ISSUE TITLE
Incorrectly labeled error: Invalid Route Assigned

### ISSUE THREAD

**Issue by NanoCE** [MaFi-Games/Captain-of-Industry-issues#1159]
### Issue description

Even though the import route does not have the empty slider set and allows for truck import, the error still persists of Invalid Route assigned.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8260901/8556aae1-fe74-478b-b90a-6cb0c085f796)

This also seem to persist after reloading the save, see save file attached.

### Reproduction steps

Load attached save, observe.

### Game version and build number

v0.5.2a b215

### Operating system

Windows

### Attachments

[save_23-06-22_15-02-38.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11840775/save_23-06-22_15-02-38.zip)

**Comment by MaFi-Games** [comment]
This seems to be gone once the game is unpaused. I would assume that the slider was unset to export whilst the game was paused and thus didn't update. Fixed the code to update it every-time.

**Comment by NanoCE** [comment]
While it's been a bit since I posted this, so my memory is a bit hazy, I'm almost certain that this was persisting even while unpaused at the time. I only noticed this issue because my vehicles were acting abnormal. If I run into it again, I'll make sure to post here.
