### ISSUE TITLE
Mining outside of tower assigned mining area

### ISSUE THREAD

**Issue by Creat** [MaFi-Games/Captain-of-Industry-issues#116]
**Describe the issue**
Screenshot of described area is attached.
I recently moved the mining area of a mine control tower. There is another mine control tower close (recently built, no excavators and/or trucks assigned). The old one should now mine some rock to make a buildable area, while it previoulsy mined limestone. The excavator has mining priority set to limestone. The old mining designation hasn't been removed, but it's not within the towers area anymore.

Note: moving the tower area has been quite a few minutes ago now. I don't know if/when it'll move over, might be soon, but it's really been a while now.

**To Reproduce**
1. Load attached save
2. Watch the excavator keep excavating limestone (it's priority), but outside of it's towers assigned area

**Expected behavior**
Excavator (and trucks) should move to the mining designation within it's towers assigned mining area

**Additional context**
 - Game version: 0.3.10

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
![image](https://user-images.githubusercontent.com/1364132/149609233-7bc33d7d-9e64-4449-8538-d34ba2c5b2db.png)
[BetaStart 13.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7874255/BetaStart.13.zip)

**Comment by MaFi-Games** [comment]
We made improvements in v0.4.6 where we now reassign excavator way more quicker when the area changes.
