### ISSUE TITLE
no water supply after pipeline update

### ISSUE THREAD

**Issue by Lembert123** [MaFi-Games/Captain-of-Industry-issues#1160]
### Issue description

After the better pipeline was researched, the fluid transport no longer works with the simple and better pipelines.

### Reproduction steps

1. pipeline 2 explored
2. seawater pump built
3. large liquid storage tank built
4. pump and reservoir connected to pipeline 2
5. pipe 1 from reservoir connected to waterworks(settlement)
6. = pipeline fill with water but water does not come to the settlement

### Game version and build number

v0.5.3

### Operating system

Windows

### Attachments

![Screenshot 2023-06-23 111727](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137494262/b822ae56-eeeb-4d13-a2bf-dc9dc5c91a1f)

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. Feel free to file a new issue with save file provided. Thanks!
