### ISSUE TITLE
Artifacting on second monitor

### ISSUE THREAD

**Issue by Harder-Better-FasterStronger** [MaFi-Games/Captain-of-Industry-issues#1161]
When I started a new game and the map loaded my second monitor (above the primary) started having artifacting (random small squares). 

yes my GPU drivers are up to date
no it is not overclocked 
other programs don't do this and I've never had it happen before.

Hardware:
1440p monitor #1
1080p monitor #2
i7-8700k
32bg ram
3080TI

OS: windows 10

**Comment by MaFi-Games** [comment]
Can you share image or video of these artifacts? Is it similar to this one https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/1100 ?

**Comment by Vectrobe** [comment]
I've found this game stresses the GPU extremely hard when using MSAA x8 and the framerate isnt CPU-bound, so its likely triggering an underlying instability. I would check with your GPU's warranty, although nvidia has had quite a lot of bad drivers as of late causing 'clown vomit' types of corruption in other games, so checking with a much older driver might be good.

**Comment by MaFi-Games** [comment]
It's not clear what the issue is here. Feel free to file a new ticket if you have more info. Thanks!
