### ISSUE TITLE
Transport building: R toggle inconsistent next to connector

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#1164]
### Issue description

In this screenshot, you can see I'm building a new pipe, which I want to end adjacent to an already-placed (planning mode) pipe's connector.  I don't want the new pipe to connect to the connector, so I've used the R toggle to disable snapping.  I've clicked once, and you can see that the ghost shows as expected.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3050938/606ae15a-f91b-44a9-90c2-d6e934fbb37f)

However, after I clicked a second time to finalize the placement, the new pipe has gone ahead and connected itself to the connector anyway.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3050938/ddef679b-9ee9-407d-8d58-78afd71ff344)

### Reproduction steps

1. Plan or build a transport with a connector.
2. Plan another line of the same transport type, running parallel, ending adjacent to the connector.
3. Use R toggle to avoid the new line joining to the connector.

Expected: the new transport doesn't connect to the old one.
Actual: it **looks** like it's not going to connect, but as soon as you finish the placement it connects anyway.

### Game version and build number

0.5.3c (b222)

### Operating system

Windows

**Comment by NanoCE** [comment]
While I'm only a third party who also shares enjoyment of this game with you, I would like to say that it is work around by just drawing the pipe farther than where you want it and then deleting it. The pipe will only connect to where you last place it, so drawing it pass a single tile where you want it then deleting it will get you what you want.

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3d, thanks for the report.
