### ISSUE TITLE
Captain of Industry

### ISSUE THREAD

**Issue by luisag581** [MaFi-Games/Captain-of-Industry-issues#1166]
### Issue description

problem with power

power  Fluctuatinon,  when there is plenty of power being generated

### Reproduction steps

D:\Steam\userdata\33896813\760\remote\1594320\screenshots\20230624072745_1.jpg
![20230624072745_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137614816/1cc72f04-b1a8-4f06-8213-4e0f6a573202)

### Game version and build number

v0.5.3C B222

### Operating system

Windows

**Comment by NanoCE** [comment]
Your issue might not necessarily be a bug. If anything, this is a poorly explained feature or one that you haven't read up on. To put it simply, it takes times for your turbines to spin up to match your power draw, so if your power draw spikes, your turbines won't be able to spin up fast enough to meet it. 

Could you please take your save file, zip it, and upload it to this issue post so this can be looked into further? Thanks

**Comment by MaFi-Games** [comment]
Closing as there is not enough information. If you see a bug in power production, please file the bug again and include a save file.
