### ISSUE TITLE
Trucks not pathfinding to a location they can reach

### ISSUE THREAD

**Issue by DeadlyKitten37** [MaFi-Games/Captain-of-Industry-issues#1167]
s### Issue description

my trucks are having trouble pathing from solar panel production to the solar field. No other pathing is showing this issue. Of note is that this is one of the longest paths on the island. This has happened several times. Fixing them is takes manually telling them to path to a location right next to their current location, when they re-path they are fixed.

### Reproduction steps

1. load attached save 
2. click on the affected trucks (only trucks that the top right is complaining about.)
3. observe that the location they are trying to path to is one they can reach.
3b. tell them to path to the open space next to the panel they are trying to reach (them make it)

### Game version and build number

v0.5.3c

### Operating system

Windows

### Attachments

[buggy save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11857274/buggy.save.zip)

Edit: after further issues I think it may be an issue with that particular solar panel.

**Comment by MaFi-Games** [comment]
This was fixed in v0.5.3d, thanks for the report!
