### ISSUE TITLE
Workers jumping from positive to negative and back without reason

### ISSUE THREAD

**Issue by gespensen** [MaFi-Games/Captain-of-Industry-issues#1168]
I'm seeing workers jump from large positive to large negative numbers in one cycle for no reason. No waste in settlement, no active diseases. I have a + population with plenty of food and room. These jumps are unrealistic from +130 workers to -600 workers in one cycle. All settlement states in green. I can find no indication of why this is happening. I also notices the game is pulling more than 3GB of memory.

**Comment by MaFi-Games** [comment]
Can you please provide a save file where this occurs?

**Comment by MaFi-Games** [comment]
Closing as not enough information available. Please file a new bug if you have a save file and more info.
