### ISSUE TITLE
Factories taking precedence over storage even against priority

### ISSUE THREAD

**Issue by daemonazazel** [MaFi-Games/Captain-of-Industry-issues#1169]
### Issue description

I currently face a shortage of maintenance II due to a lack of electronics II. In this situation priorities should make sure the few electronics II produced go to the most important places.

I have therefor set the storage facility of my maintenance II depot to priority 4 while leaving most other places at their defaults.

Unfortunately shipments of electronics II get send to all kinds of places with lower priority. The last shipment went to one of my robotic assemblers building electronics III which has priority 10. This assembler does not use a pre-storage but is usually supplied directly.

I've helped myself by directly linking the electronics II outbound storage to the maintenance II depot inbound storage temporarily. That link is honored correctly.

I assume that factories somehow take precedence over storage facilities requesting equipment. Are they supposed to?

### Reproduction steps

1. Load 1.zip
2. Remove the direct export link from my two electronics II outbound storages to the maintenance II depot inbound storage. I left it in for you to easily find the places I'm talking about
3. Observe where trucks take freshly produced electronics II

### Game version and build number

0.5.3C

### Operating system

Windows

### Attachments

[1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11859569/1.zip)

**Comment by MaFi-Games** [comment]
Yes, this indeed happens. It's not that the assemblers would be prioritized but there is not enough quantity in the output storages in order to deliver it to the high prio ones. Basically, the machines "steal" the quantity before there is enough to trigger the storage balancing. We will have to figure something out here.
