### ISSUE TITLE
Ship won't sail despite having plenty of fuel

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#1170]
### Issue description

See screenshot. The destination is 739Km away and the ship has 1846Km of fuel. Yet it says, Not Enough Fuel. Please explain this. My ship has more than 2x the required amount of fuel.
![no_fuel](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/4413670/458f19a8-3af4-4510-b4be-b74cfd65804c)

### Reproduction steps

Attempt to visit a place which is well within the reach of your ship and be denied.

### Game version and build number

Update 1 v0.5.3c

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Can you please provide a save file so we can take a look?

**Comment by MaFi-Games** [comment]
Took a look. This is because we show "not enough fuel" message for locations that are too far. Changed this so that we show a more informative message.

**Comment by utdrmac** [comment]
But how can it be too far if you have enough fuel?
