### ISSUE TITLE
Upgrading or removing and copying assemblers can result in phantom items

### ISSUE THREAD

**Issue by Vectrobe** [MaFi-Games/Captain-of-Industry-issues#1171]
### Issue description

My depot failed to craft any more haul trucks after all the parts were delivered bar 8 red units, and strangely enough the dedicated assembler next to it was nolonger recieving any parts to make any more. This seemed to occur after I had deleted and moved said dedicated assembler, so the previous one that was unity-deleted may have 'put these 8 parts in the aether' so to speak.
Rather interestingly as well, the vehicle depot was holding onto 880 yellow parts that were not actually on the statistics list until after I deleted it, but this seems an unrelated other problem.

So tldr I have 120 total red parts on statistics, but only 112 of them exist (in the shipyard), all associated buildings and _all_ assemblers were deleted, no dice, _the remaining 8 parts dont exist_

oh and unity cannot access these parts either, despite the button being available.
also possible that a phantom truck has them, but I would have no idea where to look for any this late in the game...

### Reproduction steps

load attached save? you'll have to check the raw data directly I guess

### Game version and build number

v0.5.3C B222

### Operating system

Windows

### Attachments

[save with phantom 8 red parts.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11862823/save.with.phantom.8.red.parts.zip)

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3912867/c3dbc124-1180-41fe-ae62-85b05253e551)

**Comment by Vectrobe** [comment]
adding a console command to force a complete flush and recalculation of the statistic/global values would be good, since this also affects delivery via trucks and also seems to deadlock assemblers?

**Comment by Vectrobe** [comment]
though similarly I have had other issues of using unity delivery with it simply not working, or only partially delivering the items, as opposed to the normal behavior [of there not being enough parts] of not delivering anything and making the error noise

sometimes this is because trucks are in the process of picking items up or delivering them, but sometimes this just does not work correctly at all until much more parts are made

so its entirely possible that the numbers of each item in my save file are _entirely broken_ and I have no idea what the true values are until I delete assemblers and check stores and the shipyard

**Comment by MaFi-Games** [comment]
Would you by any chance have a save file before you deleted the assembler that made the phantom products?

**Comment by Vectrobe** [comment]
I just checked if the v0.5.3D update today added any exception logs for this, but there appears to still be nothing and the 8 items cannot be found.
Was there an exception log event added for whenever a unity deliver fails?
