### ISSUE TITLE
During certain weather, all unfinished buildings appear paused

### ISSUE THREAD

**Issue by MrNukealizer** [MaFi-Games/Captain-of-Industry-issues#1172]
### Issue description

During heavy rain I can't see any visual difference between building ghosts that are paused or under construction, with all of them appearing white as if they were paused. Pipe ghosts have the normal blue tint. In the attached screenshot, about half of the buildings are under active construction and half are paused.

### Reproduction steps

Load attached save and it should be immediately apparent. If not, try setting graphics to the High Quality preset.

### Game version and build number

v0.5.3c b222

### Operating system

Windows

### Attachments

![Screenshot 2023-06-25 234718](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1545777/c894bc08-600e-4335-81b8-17d2be54033c)
[save_23-06-25_23-47-40.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11865309/save_23-06-25_23-47-40.zip)

**Comment by MaFi-Games** [comment]
We are investigating how to make paused buildings more distinguishable. Thanks for the report.

**Comment by MrNukealizer** [comment]
Fixed in v0.5.3d
