### ISSUE TITLE
Failed to initialize new save

### ISSUE THREAD

**Issue by perryBunn** [MaFi-Games/Captain-of-Industry-issues#1173]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/11916553/d3e56985-9e40-43cf-aa44-aa42ab87873e)

### Reproduction steps

1. Load game
2. Click new game
3. Select anything, (Every config ive tried still produces the error)
4. Start the game
5. wait

### Game version and build number

v0.5.3C B222

### Operating system

Windows

### Attachments

[23-06-26_12-44-40_9854.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11871689/23-06-26_12-44-40_9854.log)
[23-06-25_23-03-57_0451.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11871697/23-06-25_23-03-57_0451.log)

**Comment by perryBunn** [comment]
A nice feature to have would be able to easily copy the debug text from an error like this. I was unable to select/highlight the text in-game so I had to post a screenshot.

**Comment by MaFi-Games** [comment]
Looks like your machine is out of memory: `OutOfMemoryException: Out of memory` (open the log files that you shared to see it). We will try to make this issue reporting better.

**Comment by perryBunn** [comment]
Weird I just tried again and the game only allocated another 400MB before giving the same error. I have 32GB of ram and I never saw more than 14GB being used with other stuff open. Is there a way to allocate more to the game?

**Comment by perryBunn** [comment]
I think I found out what was causing the issue. I had set a environment variable for Mono `MONO_GC_PARAMS` where I changed the nursery-size and a couple of other values. I removed the variable and rebooted and it loaded up a save I had from a while ago. Im assuming that one of the params I had set (probably running the GC after some ms delay) didnt like the game loading. Ill close this issue out.
