### ISSUE TITLE
Terrain wont update until pressing ESC

### ISSUE THREAD

**Issue by Stalkie** [MaFi-Games/Captain-of-Industry-issues#1174]
### Issue description

I've noticed that the terraforming changes on terrains sometimes gets stuck and isnt updated properly.
If entering the menu (ESC) everything seem to update.
Never occured before until this map where a larger terraforming project is taking place.

Save game, image and short video clip attached

### Reproduction steps

1. Load attached save
2. Wait for trucks to dump/mine abit on designated areas
3. Press ESC and wait 1 sec and see the terrain changes

### Game version and build number

v0.5.3c

### Operating system

Windows

### Attachments
Savegame: [terrain.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11874018/terrain.zip)
Clip:https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/eeaf35a9-6371-4045-b053-17c32aabdb78
![terrain_issue](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/fd776935-058e-4df7-bf5e-107d8c2c7f1b)

**Comment by MaFi-Games** [comment]
Thanks for the report, we are having troubles to reproduce this. Could you share logs from game session when this is happening?

**Comment by Stalkie** [comment]
Just found out that it seems to be affected by the FPS limit. If i set FPS limit to None, or 100, it works fine. But at 80 or below, the terrain gets "stuck".
(It catches up on game pause, alt tab and escape.)

Attaching logs also a fresh save where it consistently happening every load.

[23-06-27_09-53-37_7351 copy.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11879251/23-06-27_09-53-37_7351.copy.zip)

**Comment by Stalkie** [comment]
There is not much log outputs in later files strangely, had it running for 20min now.
[23-06-29_20-22-38_4592.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11909531/23-06-29_20-22-38_4592.zip)

There's a row:"Failed to raycast terrain" about the time this hill decided to pop in:
1 frame between the screenshots 
![bild](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/26777760/b3f59664-5f7b-4ff8-a20d-4b1932797eba)

Also there is alot bigger logs some days back, if those are useful. Many rows with "Terrain designations validation failed"
[23-06-26_19-13-13_6207.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11909543/23-06-26_19-13-13_6207.zip)

**Comment by MaFi-Games** [comment]
This is very bizarre, we cannot figure out what is causing this but we will keep investigating. Sorry for the issues!

**Comment by Mr-Roan** [comment]
After playing more on this save, I'm no longer able to reproduce it. No matter what frame rate etc.
Maybe a very rare glitch not worth spending too much time on :)
But thanks for the update!

**Comment by Stalkie** [comment]
After playing more on this save, I'm no longer able to reproduce it. No matter what frame rate etc.
Maybe a very rare glitch not worth spending too much time on :)
But thanks for the update!

**Comment by MaFi-Games** [comment]
Closing this as we don't have a repro, and it started to work. We don't have any other reports about this from anyone else. Please file a new issue if it occurs again.
