### ISSUE TITLE
Research UI becomes the wrong size in some situations

### ISSUE THREAD

**Issue by MrNukealizer** [MaFi-Games/Captain-of-Industry-issues#1176]
### Issue description

The size of the sidebar with research item info seems to change incorrectly when switching between certain research items. Cancelling research before switching may be involved somehow.

### Reproduction steps

1. Load the attached save.
2. Open the research screen.
3. Select Vehicles Management IV and cancel it.
4. Select Construction IV.

I'm running at 2560x1440 resolution with 120% UI scale if that affects it.

### Game version and build number

v0.5.3c b222

### Operating system

Windows

### Attachments

![Screenshot 2023-06-27 031235](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1545777/317ef2f4-b08b-4832-83f8-1317e8784ab1)
![Screenshot 2023-06-27 031257](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1545777/03e7f154-1390-4b47-b021-93f5c3796382)
[Research UI Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11880699/Research.UI.Bug.zip)

**Comment by MaFi-Games** [comment]
Yes! Finally a repro for this issue that we have been trying to pin down for some time. Thanks! Will be fixed in the next patch.
