### ISSUE TITLE
Transport placement lagging behind cursor, and other related refresh rate problems

### ISSUE THREAD

**Issue by RandomUsername27** [MaFi-Games/Captain-of-Industry-issues#1177]
### Issue description

The placement ghost of transports lags behind the cursor, because they're not updated as fast as the display is.
The issue is clear if comparing the refresh rate of dragging around a building (a concrete mixer for example) vs a transport. (like a pipe.)

https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/76728892/bf263ca9-eef6-4245-bd6c-166413a3ff0b

This is present elsewhere in different forms:
- Every building is slow to change from buildable to unbuildable and vice versa in case of collision.
- Every click is delayed when building transports (Easily seen when trying to click a specific tile while the mouse is moving)
- Copy - Pasting settings between buildings can't be done in very quick succession, because some clicks will go ignored.

(Side note: I'm playing with uncapped fps, borderless, and my display is 280hz (yes it is.) but the game only runs at 80fps average, with 1% lows at 35-40, being higher than the shown and described sluggishness)

I do think that this could be a performance increasing setting, but if it isn't, I think it's better reported.

### Reproduction steps

1. Select a transport
2. Move the mouse
3. Select a building
4. Move the mouse
5. Compare

### Game version and build number

v0.5.3c (b222)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for the report but this is unfortunately how the game currently works. Simulation is running 10 times per second in a separate thread so UI has to wait 1-2 ticks (100-200 ms) for the validation results. There are ways how to improve this but it is low on our priority list.
