### ISSUE TITLE
FPS Drop

### ISSUE THREAD

**Issue by hkurniapratama** [MaFi-Games/Captain-of-Industry-issues#1179]
### Issue description

When i zoom out the maps in 3x speed, fps got drop in ultra settings.
I'm using msi laptop with specification: 
Processor: Intel Core i5 11400H 2.7GHz 12 CPUs
RAM 16 GB 3200 MHz
SSD NVME M.2 Gen 3
RTX 3050 4GB

### Reproduction steps

Zoom out the maps in late game with 3x speed

### Game version and build number

v0.5.3c

### Operating system

Windows

### Attachments

[Finish.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11891110/Finish.zip)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11891132/Player.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11891133/Player-prev.log)

**Comment by MaFi-Games** [comment]
Thanks for you report, but that's not unexpected at this moment. We allow very generous zoom out and fairly increased simulation speed. It can surely happen that in the endgame, the game can't keep up. We are working on improvements and will keep working on improvements. So no need to track individual bugs here, we track our performance efforts separately.
