### ISSUE TITLE
Electrolyzer: recipe for Water to Hydrogen + Oxyogen is very slow

### ISSUE THREAD

**Issue by PKHenkel** [MaFi-Games/Captain-of-Industry-issues#118]
The usage of the electrolyzer to produce Hydrogen (to create ammonia then fertilizer) is comparable slow. I would have expected the rate to be compareable to the over recipe, which produces 24 Hydrogen vs. 3 in a 60s cycle. As the energy cost for the electrolyzer is 150kW using the water based recipe would need 1200kW (compared the the ammonia recipe).

![grafik](https://user-images.githubusercontent.com/97865455/149706563-a02d8431-7285-42f1-acf5-670532df9478.png)

steam version beta 0.3.10.0

**Comment by MaFi-Games** [comment]
This is expected as hydrogen production from water is very demanding compared to extraction of ammonia. This was balanced balanced based on reality. We might provide some advanced water electrolyzer for end-game with some better ratio maybe.

**Comment by PKHenkel** [comment]
I just realized the output for H2 in the NH3 recipe seems to be low, this should be 72 H2. I would expect something on the basis of 2NH3 to N2 + 3H2

**Comment by MaFi-Games** [comment]
We set  output quantities to ensure game balance. This cannot always follow reality unfortunately.
