### ISSUE TITLE
Dumping does not work correctly in certain conditions

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1180]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/0f4373f7-088e-4894-bfb8-2edb1269a43c)
If you place another dumping zone outside of the area specified by the mining tower, it interacts with the ones inside the dumping area, even though it should not. You can see a nice clean dumping zone above the area, but when I put in the extra dumping designations to demonstrate, it acts all weird and partially dumps into them for some reason.

### Reproduction steps

See above, though it might rely on the ramp?

### Game version and build number

Update 1 0.5.3c (222)

### Operating system

Windows

### Attachments

[Dumping Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11893090/Dumping.Bug.zip)
This is before the trucks go to dump, just run it in speed 3 for maybe a minute

**Comment by MaFi-Games** [comment]
Thanks for the report, this is unfortunately a consequence of how dumping logic tries to maximize its effectivity. We'll investigate what can be done about this.

**Comment by MaFi-Games** [comment]
This was fixed in `v0.5.3e`, thanks for the report!
