### ISSUE TITLE
Vehicle Depot does not allow Quick Deliver when at Vehicle Limit

### ISSUE THREAD

**Issue by Keranik** [MaFi-Games/Captain-of-Industry-issues#1181]
### Issue description

When I click on quick deliver, nothing will happen.  There is a valid storage with rubber available on the map.

### Reproduction steps

1. Be at maximum vehicle limit
2. Set a vehicle to be upgraded
3. Go to vehicle depot and use unity to quick deliver

### Game version and build number

v.0.5.3c

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/17f39f19-bc7a-4f5d-9560-0ad5dd951107)

**Comment by Prometheus0000** [comment]
The vehicles aren't instantly replaced, they go to the depot *after* the first one is produced, not at the same time or before. So you could cancel the scrapping and go over the limit if it didn't forbid you from making more here.
What it should probably do is call the old vehicle over when at 100%, then scrap it and spit out the new one. That's less convenient at any time other than when at the cap though.
