### ISSUE TITLE
A truck is stuck, but shouldn't be

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1183]
### Issue description

It has slag in it
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/57071301-c580-461b-9833-74fc337fcec7)
It wants to deliver here, but it should be able to deliver to the storage. Setting both slag crushers to deliver off causes it to deliver to it.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/523b14ba-7258-4d44-bcaf-859858134de4)
Slag isn't even allowed in this dumping area. I've seen this kind of thing before, where a truck assesses dumping in an invalid area over and over for some reason.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/42b935bf-feb9-4450-8aaf-6448d29167db)
I have a perfectly good slag dumping area here
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/a0e6e6eb-54bd-4f42-b216-757381ad77ec)

BTW, this is right after loading from version 3c to 3d.

### Reproduction steps

Dunno

### Game version and build number

Update 1 0.5.3d (224)

### Operating system

Windows

### Attachments

[Slag Truck bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11915825/Slag.Truck.bug.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report. This looks like a temporary issue of truck having a job to deliver to unreachable crusher. In the save you shared, this got resolved itself once crusher accepted its first cargo from the conveyor belt, disabling truck import.

Feel free to re-open if this issue persists for you.

**Comment by Prometheus0000** [comment]
The thing is I had been using that setup for a while, so I guess it reverts back to allowing truck imports if it doesn't receive belt input for a while? I wouldn't expect that.
