### ISSUE TITLE
Ability to place connectors under/over water

### ISSUE THREAD

**Issue by Bremi1885** [MaFi-Games/Captain-of-Industry-issues#1184]
### Issue description

When trying to paste copied set ups, it is possible to paste the connectors under/over the water. belts/pipe and buildings won't paste, just the connectors

### Reproduction steps

- Copy a set up containing belt/pipe connectors
- hover over water
- place only connectors will be placed.

### Game version and build number

v0.5.3c b222

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This was fixed in `v0.5.3e`, thanks for the report!
