### ISSUE TITLE
The tree harvester doesn't always prioritize designated areas over the tree farm

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1186]
### Issue description

Tree Farm where it is:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/56bf929a-f338-4129-aee0-452c6a023074)
Trees it should be cutting:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/b246681c-26d4-470d-9ac7-17d6f259476c)
It cut half of them and then just wandered off, possibly when it went to go get fuel I guess? It's not assigned to the farm, so it should cut any designated areas first, right? Setting the forestry control tower to no cut makes it go back, but pausing and unpausing does not.

### Reproduction steps

Dunno

### Game version and build number

Update 1 0.5.3d (224)

### Operating system

Windows

### Attachments

[Tree Harvester Bug 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11920087/Tree.Harvester.Bug.2.zip)

**Comment by MaFi-Games** [comment]
This was hopefully fixed in `v0.5.3e`. Feel free to file a new bug if this occurs again.
