### ISSUE TITLE
Some buildings consume electricity when they just stand and do nothing.

### ISSUE THREAD

**Issue by SanchozzDeponianin** [MaFi-Games/Captain-of-Industry-issues#1187]
### Issue description

Some buildings continue to consume electricity, and actually waste it when they just stand and do nothing.

The Cargo Ship is completely unloaded, the Fluid Module is also empty and does nothing, but it consumes electricity.

I have not checked the Unit and Loose Modules, but I suspect that they behave similarly.

Waste Sorting Plant is in the status of waiting for products, when recyclables run out, it stands and does nothing, but also consumes electricity.

Yes, there are some remnants of recyclables left inside. For the sake of experiment, I completely turned off the supply of recyclables to the Waste Sorting Plant, and watched. It can stand for an infinitely long time doing nothing and consumes electricity.

### Reproduction steps

Load the attached save file.
Watch the Waste Sorting Plant.
Watch the Fluid Module.

### Game version and build number

v0.5.3c

### Operating system

Windows

### Attachments

![Empty Cargo Ship](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/73459473/ceecea51-9e52-4043-9a24-bc1f75d50abc)
![Empty Fluid Module](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/73459473/6b6d1c7f-e664-481a-9de1-2e41086182ad)
![Statistics](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/73459473/c4de66c1-ff59-402d-b05a-a7151cd594fb)
![Waste Sorting Plant](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/73459473/15cf2a13-cbad-42ce-a83c-14f2abc980a7)
[save_23-07-01_09-07-52.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11924368/save_23-07-01_09-07-52.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report. The recycling center is meant to consume power all the time but the cargo depot modules are indeed a bug that will be fixed in the next patch.
