### ISSUE TITLE
tree harvester has no trees to harvest even when they are right in front of it

### ISSUE THREAD

**Issue by BrentWinters** [MaFi-Games/Captain-of-Industry-issues#1188]
### Issue description

on the map named curland the tree harvester doesn't want to cut some trees next to the limestone patch. They are marked to harvest. If i look at the navigation overlay it tells  me that the tree harvester is capable of driving to the trees. There are also some single trees that can't be cut down but its manly this patch of trees that doesn't want to go down. The tree harvester can harvest other trees on other parts of the map.

### Reproduction steps

I have no idea what triggers this

### Game version and build number

v0.5.3c b222

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/138317139/a4d498ac-d628-498c-bba7-1b81ff555ab8)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/138317139/ac381115-263c-4d6c-8c69-67df8e988a6f)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/138317139/e5315d85-4c2b-48e0-ad1b-9275c7e48302)
[brent new island.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11926679/brent.new.island.zip)

**Comment by Teladianium** [comment]
Not sure if its the same or not, but I had the tree harvester convinced there were no trees it could cut and went across the map several times to a tree farm to help out vs cutting the marked trees. For me a save, close the game and restart it seems to have fixed the issue. Alternatively I use a forester control tower.

**Comment by Prometheus0000** [comment]
Probably related to #1186

**Comment by MaFi-Games** [comment]
This was hopefully fixed in `v0.5.3e`. Feel free to file a new bug if this occurs again.
