### ISSUE TITLE
Building any Building end in Paused Building Mode

### ISSUE THREAD

**Issue by djdomi** [MaFi-Games/Captain-of-Industry-issues#119]
**Describe the issue**
I started a new game and it is fine, but after some hours, it started to that if i build something, anything is pause for building after placement

I've put an SCreenshot here
https://discord.com/channels/803508556325584926/803519296864518184/932975200906121257

**To Reproduce**
Build Things.

**Expected behavior**
Building without clicking all the time to start building

**Additional context**
Current Beta.

**Attachments**
[If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
](https://discord.com/channels/803508556325584926/803519296864518184/932975200906121257)

**Comment by MaFi-Games** [comment]
That's because you are in planning mode. Works as intended.
