### ISSUE TITLE
Nuclear reactor II runs wrong recipe

### ISSUE THREAD

**Issue by daemonazazel** [MaFi-Games/Captain-of-Industry-issues#1192]
### Issue description

My nuclear reactor II only has uranium rods in storage, but it keeps running the recipe for mox rods, producing spent mox, but using my storage of uranium rods

![1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7012343/8916e0f3-4bad-4ae8-95ff-e84b04e14f04)
[1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11929110/1.zip)

### Reproduction steps

1. Load save
2. Observe count of uranium rods couning down while mox recipe keeps running

### Game version and build number

0.5.3D

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for reporting and for providing the save file, we will look into this.

**Comment by rasilo** [comment]
I have the same issue, but the other way around: The uranium rod recipe keeps being used although having a lower priority than the mox rod one. The process produces spent fuel but consumes from the available MOX rods.

![coi_wrong_nuclear_fuel](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/54287164/3ea272ab-bfd0-4bcc-bf98-542515cb8bf1)

**Comment by brian-m-r** [comment]
I have same issue.
On reactor upgrade it ran MOX recipe when it didn't have any MOX fuel present and produced spent fuel.
It now runs uranium rod recipe, but consumes MOX rods and produces spent fuel not spent MOX.
