### ISSUE TITLE
 Two bugs: Little foundations left behind on terrain bug, and copy/paste bug

### ISSUE THREAD

**Issue by Keranik** [MaFi-Games/Captain-of-Industry-issues#1194]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/a12c9b11-6738-45f3-82e3-c68105c3c093)

This is easier to reproduce when the game is in a paused state. These are the steps to reproduce this issue with the foundations being left behind.  I will refer to three states, as built-state (completed), blue-state (ghosted but unpaused) and gray-state (ghosted).  

Step 1) ![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/9e931fdc-b836-4465-9a0a-eb0006d2a98a)

Step 2) 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/15639e9d-2649-4712-ba95-6fdafed9c5b5)

Step 3) 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/04602272-7678-42ce-b7cc-713e333859cd)

Step 4)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/fd04fd26-4ce9-44fb-83d7-df99cde06d1f)

Step 5)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/137360086/a4bc2cd1-e802-4d13-911b-bcb59e7e5475)

### Reproduction steps

1) Have any conveyor belt in completed state with a Connector on it.
2) Copy the connector using the copy/paste tool.
3) Place the copied section on top of the existing belt.
4) The copy/paste fails to put the connector in the correct spot.
5) While newly placed connector is in blue state, delete it and it will create the permanent foundation.

Summary: Any time a connector is deleted while in blue state it will leave the small foundation behind.  Does not seem to happen to pipes. I also reproduced the bug that the other guy was having with the copy/paste not placing the connector in the correct spot while trying to post this bug reproduction.  Two in one!

### Game version and build number

v.0.5.3d

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for the report, the concrete foundations left behind will be fixed in the next patch!
