### ISSUE TITLE
incompletable construction

### ISSUE THREAD

**Issue by DeadlyKitten37** [MaFi-Games/Captain-of-Industry-issues#1195]
### Issue description

There is a fuel station which I previously unity built but which is stuck at 18/20 parts. I have tried reloading and unity building it a 2nd time, but it is still bugged.

### Reproduction steps

1. load attached save
2. in front of the camera there is a mostly built building (a fuel station)
3. attempt to unity build it
4. observe it failed despite the panel on the right showing there to be sufficient materials for the operation.

manual fixing is NOT possible by deconstruction and reconstruction the building

### Game version and build number

v0.5.3c

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/53106272/5aa23fde-41a8-4586-8685-274920d10d60)
[buggy save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11952583/buggy.save.zip)

**Comment by DeadlyKitten37** [comment]
update: I had the same issue again with trying to unity build some belts seconds after this save was taken

**Comment by Vectrobe** [comment]
I suspect this might be the same issue as mine #1171, but in this case when constructing a building as opposed to delivering to an existing one.
Did you upgrade or remove any constructors that were making the phantom/missing parts?

**Comment by zuff-coi** [comment]
I was not able to recreate this issue. @DeadlyKitten37 where is the building that was bugged in your save file? The save you provided isn't facing it upon load.

**Comment by DeadlyKitten37** [comment]
Sorry, I loaded the wrong "buggy save" file here is the right one
I believe @Vectrobe is correct that the issues are related, I also tried to build some belts which ran into the same issue. I think, after looking through everything, that I also ended up with "phantom" item that exist in the statistic screen and nowhere else (In my case construction parts 2).

[buggy save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11992273/buggy.save.zip)
