### ISSUE TITLE
Pillar location retained even after removing reason for pillars

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1196]
### Issue description

Normal:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/04de2ad7-3038-4b5e-a970-37a229ad1abb)
Pillar 'spots' are still there, even after removing the reason for their existence
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/286abde2-2193-442a-bd10-dc7dae2303b6)
If you try to drag another belt across, it places pillars in the same spots again
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/a815c495-4365-4b1d-9e1e-f39e3f59b21d)

This is frustrating when you're trying to remove as many pillars as possible to have your build look clean, though it might be like this on purpose?

### Reproduction steps

See above

### Game version and build number

Update 1 0.5.3d (224)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for the report, this will be fixed in the next patch!
