### ISSUE TITLE
Uranium enrichment research has a strange research requirement

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#1198]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8517039/9d65ec04-c844-4e9a-ab64-395108419d85)
It looks like it requires both power generation III and IV, but since IV requires III, there should be no reason for it to require III as well.

This is basically just a visual issue.

### Reproduction steps

Look at the research screen when you can research uranium enrichment

### Game version and build number

Update 1 0.5.3d (224)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This seems to be just a UI bug, the research depends only on Power 4 and lab 4.

**Comment by MaFi-Games** [comment]
Looking at this, I don't see any issues. We always highlight all the nodes that are transitively blocking any selected node.

**Comment by MaFi-Games** [comment]
Actually, we found the issue. Thanks!
