### ISSUE TITLE
Tree Harvester wont fill storage

### ISSUE THREAD

**Issue by xXmilchzombieXx** [MaFi-Games/Captain-of-Industry-issues#12]
**Describe the issue**
My tree harvesters wont fill the left storage but the right one gets filled without any problem.

**To Reproduce**
1. Load the attached savegame.
2. Wait and look at the storages like in the attached pictures.
3. The harvesters only move to the right storage but on the left side they only move to the assembly (electric) to fill it up.

**Expected behavior**
I only want that the harvester trucks fill the left storage like the right.

**Additional context**
 - Game version: Alpha 0.2.4

![image](https://user-images.githubusercontent.com/72553828/134588683-5c316936-a41f-4d88-91a7-cae48bab9380.png)
![image](https://user-images.githubusercontent.com/72553828/134588703-1661ff2b-61a4-4929-bab6-791ee341bf56.png)
[21-09-23_23-14-28_2012-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7220990/21-09-23_23-14-28_2012-autosave.zip)

**Comment by MaFi-Games** [comment]
This is indeed strange, I was able to reproduce this thanks to your save. We will investigate this more.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta patch, thanks for reporting!
