### ISSUE TITLE
bug excavator

### ISSUE THREAD

**Issue by riohasmadi** [MaFi-Games/Captain-of-Industry-issues#1203]
### Issue description

![Screenshot 2023-07-13 132643](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12940055/89716067-8bb7-44ad-a032-711709906b12)

### Reproduction steps

![Screenshot 2023-07-13 132643](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/12940055/4515cf48-d811-46b9-a61b-478f91b432e6)

### Game version and build number

v0.5.3e b225

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thanks for the report, would you have a save file or some description how that happen? It is really hard to know how this happened just from screenshots.

**Comment by MaFi-Games** [comment]
Closing as there is not enough information.
