### ISSUE TITLE
Undiggable/Undumpable tiles at edge of New Haven map

### ISSUE THREAD

**Issue by Dalkyr2** [MaFi-Games/Captain-of-Industry-issues#1204]
### Issue description

There are tiles at the very northern edge (or at least the NE corner) of the New Haven map that become unusable. (North defined based on the starting location)

Trucks will dump *some* material, but after a certain point they will stop actually dumping. They do the animation, but don't dump any material. Attempting to dig those tiles back out results in similar behavior: Digger does animation, but does not pick up any material.

### Reproduction steps

1. Load save "Buggy Land.save"
2. Observe Excavator trying (and failing) to dig.
3. Attempt to dump. Trucks will dump *some* material, but will not make a "clean" edge. 

### Game version and build number

v0.5.3e b225

### Operating system

Windows

### Attachments

Cannot attach save because it's ~32MB. Save is available here: https://drive.google.com/file/d/1YDVda08uyNzj6EgdVll5ObiYG2eQSYxo/view?usp=sharing

![23-07-13_15-17-17_y1995_pop8740](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/139436440/bbcea781-9bcc-447c-855c-0109e1f1fe97)
![23-07-13_15-17-44_y1995_pop8740](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/139436440/6901f07d-7239-4519-b944-af9cc57116a2)
![23-07-13_15-18-09_y1995_pop8740](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/139436440/6b779545-5492-40f6-93d1-94af82bcc646)

**Comment by MaFi-Games** [comment]
Thanks for the report, this is likely caused due to the edge of the map, we will investigate this. The save file was very helpful.
