### ISSUE TITLE
Pipe balancer is not working correctly

### ISSUE THREAD

**Issue by Finghin** [MaFi-Games/Captain-of-Industry-issues#121]
**Describe the issue**
Output priorization of pipe balancer does not actually output 100% of the input to the prioritized output.

**To Reproduce**
1. Load attached save
2. Check where the ammonia coming in from the sour water stripper is routed to by the selected pipe balancer. (see screenshot below)
3. 75% of the ammonia goes to X output, 25% goes to to O output, even though the pipe on the X output is not full.

**Expected behavior**
Since the input and output pipes have the same diameter, I would expect 100% of the input to go to the X output unless the pipe is completely full, so 8/8 in this case.

**Additional context**
 - Game version: 0.3.10

**Attachments**
[Central_Mountain_Map-Standard.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7898659/Central_Mountain_Map-Standard.zip)
![grafik](https://user-images.githubusercontent.com/108845/150171735-83c5594f-f3da-49a7-b12e-5164c77542c6.png)

**Comment by dhdarkelf** [comment]
I am seeing this to 
![image](https://user-images.githubusercontent.com/52480102/151696912-86df2c50-15dc-4cb9-953e-89714c6e6b83.png)
"B" should be empty before pulling from "c"

**Comment by Samspos** [comment]
hey guys, if i read it correctly, both of you need to take the other switch, than it should work properly

**Comment by MaFi-Games** [comment]
Thanks for the report, balancers are now (hopefully) fixed in upcoming Early Access version that will be released in May.
