### ISSUE TITLE
Coastal water texture clipping into terrain

### ISSUE THREAD

**Issue by Finghin** [MaFi-Games/Captain-of-Industry-issues#122]
**Describe the issue**
There is a coastal water texture clipping into the terrain near the small excavator as seen in the screenshot below.

**To Reproduce**
1. Load attached save

**Expected behavior**
That texture should not be there.

**Additional context**
 - Game version: 0.3.10

**Attachments**
[water_terrain_texture_bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7899893/water_terrain_texture_bug.zip)
![grafik](https://user-images.githubusercontent.com/108845/150196005-04ae435e-98ab-45e5-9c80-6f83482313a0.png)

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
