### ISSUE TITLE
Missing animations

### ISSUE THREAD

**Issue by moffmaster** [MaFi-Games/Captain-of-Industry-issues#1225]
### Issue description

Description: 
Animations are missing for the pump jack, sour water stripper and Lab2 buildings. Possibly more.

Expected Behavior:
Animations/lights to be present

Reproduction Steps:
Load the game, observe structures

Game Version: 
v0.5.4A

Graphics Cards:
GeForce GTX1660

### Reproduction steps

The bug persists constantly, including in new games and on reload. Some players were able to reproduce the problem, but the captains Jeremy and Marek were not able to do so. Consequently Captain Marek asked me to post the bug report here, with the theory that it might be hardware dependant.

### Game version and build number

v0.5.4A

### Operating system

Windows

### Attachments

[bug_report.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12284694/bug_report.zip)

**Comment by MaFi-Games** [comment]
This has been fixed in the recent patch. Could you please confirm that the animations work for you?

**Comment by moffmaster** [comment]
Looks good to me now! Thank you!
