### ISSUE TITLE
Pipe and Mill colision

### ISSUE THREAD

**Issue by Nopus64** [MaFi-Games/Captain-of-Industry-issues#1227]
### Issue description

collision problem between a pipe and a mill vent on top

### Reproduction steps

1. place mill
2. place a pipe (tier 1 -3) at high 3
3. pipe gets trouht then top vent-channel

### Game version and build number

v0.5.3e

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/44364839/f28dc190-6122-4859-b3be-1a6746fdfc4d)

**Comment by MaFi-Games** [comment]
This was fixed in Update 2. Thanks!
