### ISSUE TITLE
Scrap colors

### ISSUE THREAD

**Issue by Avgvzt0** [MaFi-Games/Captain-of-Industry-issues#1231]
### Issue description

The colours of scrap (iron scap, copper scrap) do not represent the colors of their respective metals.
Example: Copper scrap should be green instead of red. Iron scrap should be red instead of gray

Slightly confusing but it's not a bug!

### Reproduction steps

uhmm.. new on github sorry

### Game version and build number

v1

### Operating system

Windows

**Comment by MaFi-Games** [comment]
I think you might be mixing ore colors with metal colors. Copper is indeed orange as metal and as scrap so is the scrap icon. Iron / steel is tricky as it can undertake corrosion, but we made it gray as the iron icon is also gray. So this is all working as intended.
