### ISSUE TITLE
'The Ship' wont load materials

### ISSUE THREAD

**Issue by moor1100** [MaFi-Games/Captain-of-Industry-issues#1236]
### Issue description

**FIXED USER ERROR**

The warship wont load materials to repair oil regs or to send donations to other islands for trading. I have removed and re-added several times the request. The materials are showing as arrived in the shipyard and i have at least 2 thousand extras. I have waited several years to see if it will just eventually transfer to this ship without luck.

**Comment by moor1100** [comment]
I have fixed the issue. it was an import export issue with the storage units. I am sorry to bother you.

**Comment by MaFi-Games** [comment]
No worries! Glad it got solved!
