### ISSUE TITLE
Water render is not dissappearing

### ISSUE THREAD

**Issue by SpitAlpaca** [MaFi-Games/Captain-of-Industry-issues#124]
**Describe the issue**
I was removing a few layers of ground to expand my island. And when I got to the expanded area, the area where water was before, I could remove the ground but the water is still there. So you can not clear ground where you have created new land.

**To Reproduce**
1. Load (or start) a game
2. Dig down on land, and expand land
3. Remove land that is expanded
4. Water is still there but excavators are still digging below it.

**Expected behavior**
I expected that there was only land and no more water so I could keep the land all on the same level. And created dikes

**Additional context**
 - Game version: Beta 0.3.10

**Attachments**
In the following zip file:
- screenshot
- save file

http://vdk-online.dev/water-land-bug.zip

**Comment by SpitAlpaca** [comment]
*UPDATE*
When re-loading file, water is gone.

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
