### ISSUE TITLE
Trucks dump on tiles managed by paused Mining control tower

### ISSUE THREAD

**Issue by Decavoid** [MaFi-Games/Captain-of-Industry-issues#1243]
### Issue description

Trucks shouldn't dump on tiles that are managed by a paused Mining control tower.

### Reproduction steps

1. Clear global dumping list.
2. Build a Mining control tower
3. Pause the tower.
4. Add dumping designations inside the tower managed area.
5. Add Dirt to "What can be dumped here".

Actual result:
Trucks start delivering and dumping Dirt on tiles managed by a paused tower.

### Game version and build number

v0.5.4g (b243)

### Operating system

Windows

### Attachments

![20230827005032_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1127000/69c8281b-8423-433e-b3e6-77a40cc90e4a)
[Dumping.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12446712/Dumping.save.zip)

**Comment by MaFi-Games** [comment]
This works as intended. If a building is paused, it means it is not working, thus also not affecting anything around it. An example could be if multiple towers are managing one area and one is paused; the paused one would just not interfere. To actually restrict dumping entirely, instead of pausing the building, just clear all the products that can be dumped there.

**Comment by Decavoid** [comment]
I always treated disabled buildings as if they didn't exist and not doing or affecting anything.
Here is 2 towers. Both towers are managing the same area 32m x 32m. Left is dumping Dirt. Right is dumping Rock. The left tower is paused, so I assume that it should stop dumping Dirt and no longer "interfere" with the right tower that is dumping Rock to the same managed area. But actually the paused tower still "interferes" and continues dumping Dirt.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1127000/a4666a87-c918-4725-b8c0-ceed3d2ca7a1)
I think it would be logical if pausing the tower had the same effect as (temporarily) clearing the dumping list of this tower until enabled again.
Clearing the dumping list manually works, but it is not convenient, because if later I decide to continue dumping (Dirt, etc) in this area, I'd have to remember which types of resources I need to put back in this list. Unpausing is so much simpler.

**Comment by MaFi-Games** [comment]
> The left tower is paused, so I assume that it should stop dumping Dirt and no longer "interfere" with the right tower that is dumping Rock to the same managed area. But actually the paused tower still "interferes" and continues dumping Dirt.

That's a bug, and thanks for pointing it out. Will be fixed in the next patch.

**Comment by Decavoid** [comment]
Fixed in v0.5.5.
