### ISSUE TITLE
worldmap

### ISSUE THREAD

**Issue by Methrusax** [MaFi-Games/Captain-of-Industry-issues#1246]
### Issue description

I initiated 2 improvements on the world map: Uranium Mine and Groundwater Well:
in the shipyard first loaded the cargo for the uranium mine and then sent the ship.
After the ship left, I started loading the cargo for the groundwater well.
However, this cannot be improved anymore. Other raw materials on the world map can also no longer be improved.

I'm currently playing on "you can't pass by" with the difficulty Admiral. Current year 1081. The score with the error has been saved and can be sent if required.

### Reproduction steps

1. Load the savegame "bug at worldmap"

### Game version and build number

v0.5.4g b244

### Operating system

Windows

### Attachments

[23-08-29_09-06-bug at worldmap.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12461513/23-08-29_09-06-bug.at.worldmap.zip)

**Comment by Methrusax** [comment]
I have now loaded an older save and tried further improvements on the map there. It is not possible. Nowhere.

**Comment by Methrusax** [comment]
The error can be cleared, it is not an error. The ship has loaded the materials, but was full of electronics 2 and 3 from exploring beforehand, could not unload them into the shipyard and was therefore unable to discard.

Perhaps a hint for the maximum capacity of the ship and the shipyard could be implemented to prevent this. A warning: "The ship is overloaded" would also be great.

**Comment by MaFi-Games** [comment]
This is actually an error we have introduced in one of our last patches. The reason your ship couldn't depart was that it lacked fuel and we did not report it to you.
