### ISSUE TITLE
Arc furnace II outputing exhaust via hi steam port

### ISSUE THREAD

**Issue by Gurrz** [MaFi-Games/Captain-of-Industry-issues#125]
**Describe the issue**
When choosing to make molten glass in arc furnace 2 it will output exhaust from the steam port.
I have not tested it on another save so it might just be on my save.

**To Reproduce**
1. build Arc furnace 2 pick molten glass 
2. check which port outputs what. 
3. it sometimes looks correct but it's just a graphical glitch it always outputs both steam and exhaust from the steam port

**Expected behavior**
That exhaust is not output from the steam port :)

**Additional context**
 - Game version: 0.3.10

**Attachments**

![COI Arc furnace 2 bug](https://user-images.githubusercontent.com/98178119/150569102-0c292f32-a7ec-4a25-9eed-3ca3c9a9a34a.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, this is now fixed!
