### ISSUE TITLE
Mining Limestone issues with Excavator detecting terrain.

### ISSUE THREAD

**Issue by lorentedford** [MaFi-Games/Captain-of-Industry-issues#1257]
### Issue description

Issues Mining Limestone. Basically the small Excavator gets lost and starts mining in one place and then cant detect anything then stops and tries in another location in a giant circle. 

### Reproduction steps

Really not sure.. I sent a saved file to hopefully assist with this issue along with a video. 
[https://youtu.be/qQx9fsEMzGM](url)

### System Details
OS Windows 11 Pro
CPU= 12th Gen Intel Core i7 - 12700F
Memory= 64 Gb 3200 Mhz DDR4
GPU= Nvidia RTX 3070
Motherboard= MSI MAG B660M MORTAR WIFI DDR4 LGA 1700 Intel B660 SATA 6Gb/s Micro ATX Intel Motherboard
Main Monitor= PG259QNR ROG Swift 360hz

Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎20/‎2022
OS build	22621.2215
Experience	Windows Feature Experience Pack 1000.22662.1000.0

Device name	Loren-Gaming-PC
Processor	12th Gen Intel(R) Core(TM) i7-12700F   2.10 GHz
Installed RAM	64.0 GB (63.9 GB usable)
Device ID	20D4C0B5-6338-4CA4-9B7E-9C3C6D28F57C
Product ID	00330-50623-17819-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	Pen support

### Game version and build number

Version: UPDATE 1 V0.5.4G (B244)

### Operating system

Windows

### Attachments

[save_23-09-04_04-34-58.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12512744/save_23-09-04_04-34-58.zip)

**Comment by Prometheus0000** [comment]
I discussed this with them on discord and resolved it (https://discord.com/channels/803508556325584926/883590993063051275/1148232543670378558), but it might be good to give a notification to the player that the excavators can't reach the terrain, put in a red outline for places that can't be reached like dumping (maybe, most of the time it would likely just be annoying, so maybe a toggle?), or something else. Also, it's a giant pain to get the mining designations started on diagonal slightly sloped terrain, but I don't know if there's any way to fix that.
