### ISSUE TITLE
0.3.11.c Buildings Placed in Planning Mode Consuming Workers

### ISSUE THREAD

**Issue by CaptainLame** [MaFi-Games/Captain-of-Industry-issues#126]
Steps to reproduce:
Start 0.3.11.c
Enable planning mode
Place structures that require workers
Watch available worker count drop

**Comment by MaFi-Games** [comment]
Thanks for the report, this is being fixed in 0.3.11.d. If you find more buildings causing this, please report the concrete buildings.
