### ISSUE TITLE
Bug Bei der Forschung

### ISSUE THREAD

**Issue by LaFamilia-Radio** [MaFi-Games/Captain-of-Industry-issues#1264]
### Issue description

Bei der Forschung zeiht sich der grüne Balken über die Ganzen Forschung siehe Bild
[](https://media.discordapp.net/attachments/849893907545980929/1149802790575673365/image.png?width=942&height=671)

### Reproduction steps

Bug

### Game version and build number

v0.5.4G (B244)

### Operating system

Windows

**Comment by LaFamilia-Radio** [comment]
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/118296015/9d03e931-a902-41ab-b122-71102d738134)

**Comment by MaFi-Games** [comment]
I have not seen this ever before.  Given this is older issue we probably won't have repro available. I'm closing this but if you have a save file that reproduces this, please file a new issue and we will take a look.
