### ISSUE TITLE
separated settlements consume many more medical supplies than quoted in clinics

### ISSUE THREAD

**Issue by summonbero** [MaFi-Games/Captain-of-Industry-issues#1266]
### Issue description

i have two settlements detached from each other and their clinics say i should only consume a total of 24 med supplies when they are actually consuming much more than that. when the settlements are then bridged to one another (attached) the problem goes away.

### Reproduction steps

make 2 settlements detached from one another and look at the medical supplies graph consumption. then bridge the settlements together and look at the consumption graph again. only when they are together does their consumption match the value quoted in the clinic.

### Game version and build number

v0.5.4g

### Operating system

Windows

**Comment by ryohpops** [comment]
I have the same issue with v0.5.5c (b258) and I wonder why this is classified as a bad behavior rather than a bug. Each clinic consumes more medical supplies than "Total settlement need" displayed in the clinic dialog.

**Comment by MaFi-Games** [comment]
This was fixed in Update 2. Thanks!
