### ISSUE TITLE
Screen lock

### ISSUE THREAD

**Issue by mic-666** [MaFi-Games/Captain-of-Industry-issues#127]
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Start any game
2. Add Housing let it complete
3. No matter what Video setting the trucks look like they stop and freeze, they are still running in the back ground

**Expected behavior**
Screen Lock

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Comment by Jamile16** [comment]
This is happening to me aswel

**Comment by mic-666** [comment]
Hi Jamile
I fixed this issue by up grading the game by setting it to the experimental branch which the game updates in steam. 
started the game still had the problem so I put it back to the current version steam updated the game again and removed some files.
reset the computer, started the game placed housing down and worked fine, with upgrading and down grading seem to replace a damaged or corrupt file.

P.s make sure your graphics driver is up to date.

Let me know whether that helps you or not.

**Comment by MaFi-Games** [comment]
We fixed this in 0.3.11.d. Thanks for reporting!
