### ISSUE TITLE
Texture map found on Product Module of Cargo Shipyard

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#1271]
### Issue description

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/29ed90a7-a50e-4791-b758-1d49449d3463)

### Reproduction steps

None

### Game version and build number

v0.5.4f

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This is fixed now, thanks for the report!
