### ISSUE TITLE
Construction Sites dissapears

### ISSUE THREAD

**Issue by Lazard1987** [MaFi-Games/Captain-of-Industry-issues#128]
**Describe the issue**
After playing some time alle new builinds i place dont spawn a Construction Site. Sometimes there are connections floating in the air, sometimes you cant see anything. Also the Building wont get build. Other builinds that are building at that Moment  keep building until ready but the blue plane wont disappear.

**To Reproduce**
Not to sure... after starting a new game it happens around the time i get Oil produktion running.
It always stars happening while building something new.

**Additional context**
 - Game version: BETA 0.3.11E

**Screebshots**
[https://steamuserimages-a.akamaihd.net/ugc/1820018636982450111/876F678C7AB59FA7C13060B9E516B976A7BC1E88/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](url)
[https://steamuserimages-a.akamaihd.net/ugc/1820018636982435149/C37111D239D95217BA5368726C2C3C0F62AD634D/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](url)
[https://steamuserimages-a.akamaihd.net/ugc/1820018636982435324/F36E2771E52F59EA323A3287AFF5C461D87ECB7B/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false](url)
**Attachments**
Save File
[save_22-01-23_18-49-24.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7921667/save_22-01-23_18-49-24.zip)

**Comment by Lazard1987** [comment]
Little correction. Was not using Experimental when i had the bug.

**Comment by MaFi-Games** [comment]
There was a regression in our performance patch that introduced this. It should be all fixed in 0.3.11.d. Please let us know if not.
