### ISSUE TITLE
Trucks try to deliver to buildings set to auto.

### ISSUE THREAD

**Issue by GreyFalcon70** [MaFi-Games/Captain-of-Industry-issues#1287]
### Issue description

The building is set to auto. The way I read the tooltip once the building has connections made the trucks should not be able to deliver but they are when the supply is interrupted. 

Is this intended behavior? 

### Reproduction steps

If the supplied items stop.

### Game version and build number

v0.5.5 b246

### Operating system

Windows

### Attachments

![Trucks](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/75661939/3eccbdc1-32b5-4cae-ac16-082f155a02ed)
![Trucks 2](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/75661939/7e2b54aa-6b21-4eee-954f-80f666bec4de)
/

**Comment by JamieRCHI** [comment]
I would say this is normal behavior for how the game was designed. 
I think it would be really helpful, that the default mode would be set to Off, when buildings are placed, after belts are researched.

**Comment by MaFi-Games** [comment]
Yeah, this works as intended. It's not just about connection. It has to successfully receive a product; until then, it will request trucks.
