### ISSUE TITLE
核心燃料与燃料毯如何储存

### ISSUE THREAD

**Issue by lm6870** [MaFi-Games/Captain-of-Industry-issues#1288]
### Issue description

核心燃料与燃料毯用什么设施来储存？

### Reproduction steps

核心燃料和燃料毯生产出来后找不到设施来储存

### Game version and build number

v0.5.5 b246

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Core and blanket fuels are not storable for now. They are molten an radioactive.
