### ISSUE TITLE
No radar module accessible on map

### ISSUE THREAD

**Issue by BiggsSkeedR** [MaFi-Games/Captain-of-Industry-issues#1289]
### Issue description

I have a world map where the only remaining node that I can explore, which hasn't been uncovered as pirates too powerful for my ship, is only accessible via a node with 170 power pirates. I do not have enough firepower to get past them. I am now stuck unable to fully explore the map. The final explorable node is also accessible via an explored node, but the ship doesn't have fuel to proceed from that node.

### Reproduction steps

Unknown, created a new save in V0.5.5 (B246), I think.

### Game version and build number

v0.5.5 b246

### Operating system

Windows

### Attachments

[U1CityAlpha.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12753790/U1CityAlpha.zip)

**Comment by RealisticOptimist** [comment]
I loaded your save. Seems you forgot to add armor to your ship. That brings your battle score to 190.

**Comment by MaFi-Games** [comment]
Closing as OP was just missing armor.
