### ISSUE TITLE
White boxes instand of constructions material

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#129]
It seem with the last update something with the constructions part MK II graphic went wrong they are white boxes on belts.

[try.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7922390/try.zip)

**Comment by CaptainLame** [comment]
Confirmed, T1, T2, and T3 parts:
![image](https://user-images.githubusercontent.com/17200948/150723058-ca1c5273-e56e-425b-8d43-703c2172be16.png)

**Comment by MaFi-Games** [comment]
Fixed in 0.3.11.e. Thanks for reporting!
