### ISSUE TITLE
Player.log grow out of potions

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#1294]
hi, this report come from Glidercat which informed me about a player.log issue. This Player.log grow out of potion and in the end eat up 1.2 terabyte of data on the harddrive (so used up all harddrive space) over night and than crash. This happend within the night so something went wrong here with the log. He forgot to turn off the maschine / and game and came back to it in the morning.

Unfortunaly Glidercat deleted the log so we cant upload that here (1,2 terabyte will be a lot of fun...) so instand we will reproduce it with the save and see if we manage to get this one a 1 hour game run (from the same save as before)

**Comment by MaFi-Games** [comment]
I'm sorry to hear that it grew so much. But this is Unity's log. Unfortunately, we don't have any control over it, and given that it is not even available to see what got in there or what could have caused it, I'm going to close it as non-actionable. But thanks for letting us know!
