### ISSUE TITLE
Not raining anymore

### ISSUE THREAD

**Issue by h8redd** [MaFi-Games/Captain-of-Industry-issues#1296]
I installed captain of cheats mod. I think it broke the game: 3 years so far, not a single drop of rain and my people are dying of hunger. So I removed the mod, still no rain. I checked steam file integrity: All files are checking out. So I re-installed the game, same issue. Can't get any rain to fall anymore. 

As part of my Troubleshooting I did this: 1-Uninstalled the game
                                                               2- Deleted Captain of industry folder in %Appdata%
                                                               3- Deleted all steam related folders to MAfi or Capatin of industry
                                                               4- Deleted registry entry in HK_CURRENT_USER\SOFTWARE : Deleted MAFI folder
                                                               5- Did a search for any MAFI or Captain of industry files/folders that could have remained and deletd 1 other folder ( mostly .logs files in there)
                                                               6- Restarted my computer
                                                               7- Re-installed the game

Same issue, no rain whatsoever. Now I am clueless. Did I forget anything?

The log below is after I re-installed the game.

**UPDATE: I re-did all of those steps and deleted another folder 1594320 in the steam subfolders.
It started to rain right after my first farm was built.

**Comment by h8redd** [comment]
Here's my log file. if it helps.

I 14:14:56,981 S------ ~Mai: Started logging to file
I 14:14:57,062 S------ ~Mai: Started logging to graylog
I 14:14:57,063 S------ ~Mai: Unity logging registered
I 14:14:57,063 S------ ~Mai: Staring game (standalone) ...
I 14:14:57,075 S------ ~Mai: UTC now: 2023/10/05 14:14:57
G 14:14:57,075 S------ ~Mai: Version: 0.5.5a (Update 1)
I 14:14:57,077 S------ ~Mai: Current culture: en-US
I 14:14:57,078 S------ ~Mai: Platform: 2
I 14:14:57,178 S------ ~Mai: Steam client connected
I 14:14:57,198 S------ ~Mai: Default language 'English'
I 14:14:57,758 S------ ~Mai: Loaded 3 core mods:
  CoreMod (Mafi.Core.CoreMod)
  BaseMod (Mafi.Base.BaseMod)
  UnityMod (Mafi.Unity.UnityMod)
I 14:14:57,770 S------ ~Mai: Loading mods from 'D:\Steam\steamapps\common\Captain of Industry\DLCs'.
I 14:14:57,771 S------ ~Mai: Loaded 0 mods (mods loading is disabled).
I 14:14:58,988 S------ ~Mai: Game was initialized in 0 steps and took 0.693 seconds to complete.
I 14:15:45,317 S------ ~Mai: Scene clean step
I 14:15:45,338 S------ ~Mai: Scene clean done
I 14:15:45,342 S------ ~Mai: Total memory: 7 MB, GC collected 7 MB in 2.5179 ms.
I 14:15:45,405 S------ ~Mai: Configs instantiated: GameDifficultyConfig, StaticIslandMapProviderConfig, IslandMapDifficultyConfig, RandomSeedConfig, TutorialsConfig, TerrainGeneratorConfig, IslandMapGeneratorConfig, CoreModConfig, TerrainManagerConfig, MaintenanceConfig, ElectricityConfig, BaseModConfig, StartingFactoryConfig, UnityModConfig
I 14:15:47,686 S------ ~Mai: [2370 ms] Instantiated mods.
I 14:15:47,745 S------ ~Mai: Registered 188 products from assembly 'Mafi.Base'.
I 14:15:48,530 S------ ~Mai: [844 ms] Initialized mods.
I 14:15:48,586 S------ ~Mai: Sim thread enabled: True
I 14:15:48,587 S------ ~Mai: Game ID: 4770187846549607751; Session ID: 1954779575570524766, started at v0.5.5a
I 14:15:48,589 S------ ~Mai: Allocating terrain (2048, 2048)
I 14:15:49,008 S------ ~Mai: Created a new dir for file type 'Console': C:\Users\utilisateur\AppData\Roaming\Captain of Industry\Console
I 14:15:49,011 S------ ~Mai: [481 ms] Instantiated all dependencies.
I 14:15:49,016 S000000 ~Mai: [4.84 ms] NewGameCreated: UnlockedProtosDb
I 14:15:49,044 S000000 ~Mai: [28.0 ms] NewGameCreated: PopsHealthManager
I 14:15:49,061 S000000 ~Mai: [16.9 ms] NewGameCreated: SimulationBackgroundTask
I 14:15:49,077 S000001 ~Mai: [15.3 ms] NewGameCreated: TerrainManager
I 14:15:49,097 S000001 ~Mai: Created a new dir for file type 'TerrainDataCache': C:\Users\utilisateur\AppData\Roaming\Captain of Industry\TerrainDataCache
I 14:15:49,220 S000001 ~Mai: [143 ms] Generating terrain 36/1024
I 14:15:49,329 S000001 ~Mai: [109 ms] Generating terrain 70/1024
I 14:15:49,447 S000001 ~Mai: [118 ms] Generating terrain 103/1024
I 14:15:49,765 S000001 ~Mai: [318 ms] Generating terrain 172/1024
I 14:15:49,964 S000001 ~Mai: [199 ms] Generating terrain 213/1024
I 14:15:50,172 S000001 ~Mai: [207 ms] Generating terrain 258/1024
I 14:15:50,372 S000001 ~Mai: [200 ms] Generating terrain 310/1024
I 14:15:50,685 S000001 ~Mai: [314 ms] Generating terrain 383/1024
I 14:15:50,900 S000001 ~Mai: [215 ms] Generating terrain 430/1024
I 14:15:51,116 S000001 ~Mai: [215 ms] Generating terrain 467/1024
I 14:15:51,629 S000001 ~Mai: [513 ms] Generating terrain 523/1024
I 14:15:52,450 S000001 ~Mai: [821 ms] Generating terrain 564/1024
I 14:15:53,274 S000001 ~Mai: [824 ms] Generating terrain 624/1024
I 14:15:53,892 S000001 ~Mai: [617 ms] Generating terrain 682/1024
I 14:15:54,302 S000001 ~Mai: [410 ms] Generating terrain 720/1024
I 14:15:54,816 S000001 ~Mai: [514 ms] Generating terrain 770/1024
I 14:15:55,944 S000001 ~Mai: [1130 ms] Generating terrain 821/1024
I 14:15:57,076 S000001 ~Mai: [1130 ms] Generating terrain 875/1024
I 14:15:58,106 S000001 ~Mai: [1030 ms] Generating terrain 933/1024
I 14:15:59,543 S000001 ~Mai: [1440 ms] Generating terrain 973/1024
I 14:16:01,345 S000001 ~Mai: [1800 ms] Terrain generated
I 14:16:01,538 S000001 ~Mai: [193 ms] Generated terrain data set
I 14:16:01,987 S000001 ~Mai: [450 ms] Created ocean
I 14:16:04,223 S000001 ~Mai: [2240 ms] Terrain post-processed with: SmoothTerrainPostProcessor
I 14:16:04,544 S000001 ~Mai: [319 ms] Terrain post-processed with: GrassOnRocksTerrainPostProcessor
I 14:16:09,700 S000001 ~Mai: [5160 ms] Terrain post-processed with: MixedGrassTerrainPostProcessor
I 14:16:09,874 S000001 ~Mai: [175 ms] Terrain post-processed with: ForestFloorTerrainPostProcessor
I 14:16:10,059 S000001 ~Mai: [185 ms] Terrain post-processed with: FlowersTerrainPostProcessor
I 14:16:10,063 S000001 ~Mai: [3.80 ms] Terrain post-processed with: ExplicitMapPropsTerrainPostProcessor
I 14:16:10,296 S000001 ~Mai: [233 ms] Terrain post-processed with: TerrainTexturedPorpsTerrainPostProcessor
I 14:16:10,754 S000001 ~Mai: [458 ms] Ocean regenerated
I 14:16:10,981 S000001 ~Mai: [226 ms] Invoked terrain generated event
I 14:16:10,984 S000001 ~Mai: [3.45 ms] NewGameCreated: WorldMapManager
I 14:16:11,005 S000001 ~Mai: [20.9 ms] Generating new world map.
I 14:16:11,076 S000001 ~Mai: [70.7 ms] World map generated.
I 14:16:11,079 S000001 ~Mai: [2.84 ms] NewGameCreated: VirtualResourceManager
I 14:16:11,106 S000001 ~Mai: [27.2 ms] NewGameCreated: EdictsManager
I 14:16:11,139 S000001 ~Mai: [33.2 ms] NewGameCreated: MessagesManager
I 14:16:11,173 S000001 ~Mai: [34.6 ms] NewGameCreated: StartingFactoryBuilder
I 14:16:11,575 S000002 ~Mai: [402 ms] Performing init sim updates: 0, still waiting on: 
I 14:16:11,578 S000002 ~Mai: [2.54 ms] NewGameInitialized: Calendar
I 14:16:11,599 S000002 ~Mai: [20.8 ms] RendererInitState: GameConsoleCommandsExecutor
I 14:16:11,669 S000002 ~Mai: Registered 39 console commands.
I 14:16:11,669 S000002 ~Mai: [70.3 ms] RendererInitState: CameraController
I 14:16:11,672 S000002 ~Mai: [2.97 ms] RendererInitState: WaterRendererManager
I 14:16:11,913 S000002 ~Mai: [241 ms] RendererInitState: WeatherController
I 14:16:11,918 S000002 ~Mai: [4.74 ms] RendererInitState: TreeRenderer
I 14:16:12,133 S000002 ~Mai: [216 ms] RendererInitState: ProductsRenderer
I 14:16:12,143 S000002 ~Mai: [9.77 ms] RendererInitState: TerrainRenderer
I 14:16:13,064 S000002 ~Mai: [920 ms] RendererInitState: TerrainPropsRenderer
I 14:16:13,124 S000002 ~Mai: [60.2 ms] RendererInitState: IoPortsRenderer
I 14:16:13,135 S000002 ~Mai: [11.4 ms] RendererInitState: EntitiesRenderingManager
I 14:16:13,142 S000002 ~Mai: [6.21 ms] RendererInitState: TerrainDesignationsRenderer
I 14:16:13,149 S000002 ~Mai: [7.38 ms] RendererInitState: ConstructionCubesRenderer
I 14:16:13,167 S000002 ~Mai: [17.5 ms] RendererInitState: TowerAreasRenderer
I 14:16:13,188 S000002 ~Mai: [20.7 ms] RendererInitState: GameUiInstantiator
I 14:16:13,205 S000002 ~Mai: [17.9 ms] Resolved 119 UI classes.
I 14:16:13,216 S000002 ~Mai: [10.5 ms] Building UI: 1 / 10
I 14:16:13,356 S000002 ~Mai: [141 ms] Building UI: 2 / 10
I 14:16:13,397 S000002 ~Mai: [40.1 ms] Building UI: 3 / 10
I 14:16:13,477 S000002 ~Mai: [80.3 ms] Building UI: 4 / 10
I 14:16:13,752 S000002 ~Mai: [275 ms] Building UI: 5 / 10
I 14:16:13,924 S000002 ~Mai: [172 ms] Building UI: 6 / 10
I 14:16:14,115 S000002 ~Mai: [191 ms] Building UI: 7 / 10
I 14:16:14,401 S000002 ~Mai: [287 ms] Building UI: 8 / 10
I 14:16:14,665 S000002 ~Mai: [264 ms] Building UI: 9 / 10
I 14:16:14,907 S000002 ~Mai: [242 ms] Building UI: 10 / 10
I 14:16:15,139 S000002 ~Mai: [232 ms] UI built
I 14:16:15,147 S000002 ~Mai: [8.31 ms] RendererInitState: TreeHarvestingDesignatorRenderer
I 14:16:15,168 S000002 ~Mai: [20.9 ms] RendererInitState: OceanAreasOverlayRenderer
I 14:16:15,186 S000002 ~Mai: [17.5 ms] RendererInitState: LayoutEntityPreviewManager
I 14:16:15,215 S000002 ~Mai: [29.4 ms] RendererInitState: GameDateView
I 14:16:15,233 S000002 ~Mai: [17.4 ms] RendererInitState: PlanningModeInputController
I 14:16:15,265 S000002 ~Mai: [32.5 ms] RendererInitState: NotificationsEntityIconManager
I 14:16:15,283 S000002 ~Mai: [17.4 ms] RendererInitState: StaticEntityPauseIconManager
I 14:16:15,316 S000002 ~Mai: [32.8 ms] RendererInitState: VehicleDepotWindowViewBase`1
I 14:16:15,348 S000002 ~Mai: [32.3 ms] RendererInitState: VehicleDepotWindowViewBase`1
I 14:16:15,364 S000002 ~Mai: [16.3 ms] Renderers initialized.
I 14:16:16,531 S000003 ~Mai: [1170 ms] Init game step.
I 14:16:16,566 S000004 ~Mai: [35.1 ms] Init game step.
I 14:16:16,665 S000005 ~Mai: [99.0 ms] Init game step.
I 14:16:16,748 S000006 ~Mai: [82.2 ms] Init game step.
I 14:16:16,757 S000007 ~Mai: [8.97 ms] Init game step.
I 14:16:16,767 S000008 ~Mai: [10.2 ms] Init game step.
I 14:16:16,786 S000009 ~Mai: [18.9 ms] Init game step.
I 14:16:16,804 S000010 ~Mai: [18.6 ms] Init game step.
I 14:16:16,819 S000011 ~Mai: [14.6 ms] Init game step.
I 14:16:16,835 S000012 ~Mai: [15.7 ms] Init game step.
I 14:16:16,852 S000012 ~Mai: [17.3 ms] Game initialized!
I 14:16:16,870 S000012 ~Mai: Game was initialized in 95 steps and took 31.6 seconds to complete.
I 14:23:09,878 S006109 ~Mai: Requesting game quit.
I 14:23:09,907 S006109 ~Mai: Closing file logging

**Comment by JamieRCHI** [comment]
This issue can be closed. Also, there are options in this mod to force rain to start immediately.

**Comment by MaFi-Games** [comment]
Closing as this is mod related issue.
