### ISSUE TITLE
Farms not showing any crops anymore.

### ISSUE THREAD

**Issue by h8redd** [MaFi-Games/Captain-of-Industry-issues#1297]
After levelling terrain right next to a farm, the farm displayed the icon saying it may collapse due to unstable ground. Terrain got fixed and warning disappeared. However, since that event, all my crops are looking empty, even 0.1 month before harvest. Doesn't seem to affect crops production, just the animation seems to be broken. I check file intgrity, 100% successful, same issue. I re-installed the game, same issue. It's nothing major and it isn't breaking the game, but it's kinda annoying.

EDIT: Look at post for Not raining anymore. Did all of those steps, still my farms aren't showing anything: It doesn't affect yield or harvest though. Farms are still working. Now, I only have basic farms, will wait and see if it still happens with irrigated farms.

**Comment by MaFi-Games** [comment]
Crops on farms have been fixed in v0.6.0d. If you are still experiencing issues, please let us know.
