### ISSUE TITLE
connector bug

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#13]
This issue is a bit hard to explain so i make picture of it and upload it here too.

As long the connector (see 1) is there the casting maschines (see 2) will be consider as connected to a Storage/maschine and no truck will pick up this material even if the belt is not finished at all. I know that is connect to some ground mechanic (so not easy to be fix) but maybe there is a way to solve maybe avoid the entire issue but blocking construction of connectes right in front of maschines?
![bug](https://user-images.githubusercontent.com/91292171/134693028-b18daa3d-bec8-48fc-a10a-ee6325131b35.jpg)

**To Reproduce**
1. Load attached save 'bug'
2. Do watch the casting maschine get load up.
[bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7226375/bug.zip)

**Expected behavior**
The casting maschine wont be unloaded it will soon stop working entirely. Until this belt is constructed

**Additional context**
 - Game version: [0.2.4]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
This is part of larger issue that the player has no control over logistics vs transports. It would be nice to finish the connector only if at least one transport is already finished, but this will not entirely solve this situation. And it is not easy to determine such state. We will think about this more. Thanks for the report.

**Comment by MaFi-Games** [comment]
Connectors are now built only after an attached transport is built. So this should make this issue go away.
