### ISSUE TITLE
Planning Mode Indicator Inverted Behavior

### ISSUE THREAD

**Issue by CaptainLame** [MaFi-Games/Captain-of-Industry-issues#130]
**Describe the issue**
When loading a save that was made while Planning Mode was enabled, the next time the save is loaded the behavior is inverted: when Planning Mode icon indicates OFF construction is paused; when Planning Mode icon indicates ON, construction is normal.

**To Reproduce**
[20220123-2053PST_LodeRunner_YSNP_Admiral.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7922740/20220123-2053PST_LodeRunner_YSNP_Admiral.zip)

1. Load attached save from ZIP
2. Note status of Planning Mode
3. Place a structure and see if behavior is opposite

**Expected behavior**
Structure placement should match Planning Mode status icon

**Additional context**
 - Game version: 0.3.11.E

**Comment by MaFi-Games** [comment]
Fixed in 0.3.11.d. Thanks for reporting!
