### ISSUE TITLE
Game crash when trying to see "max" data

### ISSUE THREAD

**Issue by FrightRider** [MaFi-Games/Captain-of-Industry-issues#1306]
### Issue description

there is a bug that crashes the game. this happens when I press the "MAX" button in, for example, the population overview. my game is in the year 19288.

### Reproduction steps

1. load game
2. navigate to any data tab. (for example the population overview)
3. press the "MAX" data button
4. -game crashed-

### Game version and build number

v0.5.5a (b250)

### Operating system

Windows

### Attachments

[23-10-15_21-02-50_7377.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12910477/23-10-15_21-02-50_7377.log)
https://drive.google.com/file/d/1eITdfv3UvM4sF_XvLoUawqCS6dOY4Eg6/view?usp=drive_link

**Comment by zuff-coi** [comment]
Can confirm. Crashes when going to Pollution tab and clicking max for the graph. Logs attached

[23-10-16_12-16-34_5741.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12919253/23-10-16_12-16-34_5741.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/12919262/Player.log)

**Comment by Averagejoe0099** [comment]
Same here

year 25k
Only tried with products but same
statistics 
Select product 
MAX
crash

save to big ==> Dropbox 
https://www.dropbox.com/scl/fo/t0wlh35dlrg0i7ckg3yif/h?rlkey=knkq0incc3apcpsovfaf0xxg1&dl=0

**Comment by MaFi-Games** [comment]
Thanks for the report, the fix is now in the experimental branch (v0.5.5c).
