### ISSUE TITLE
Research not available.

### ISSUE THREAD

**Issue by HenkZaan** [MaFi-Games/Captain-of-Industry-issues#131]
**The issue**
After research some issues, the Cargo Depot, Advanced Diesel an all what is dependend on those, cannot be researched, hence no rubber, no weapons, and so on. 

**Attachments**
This is a screenshot of the researche tree.
![20220125213548_1](https://user-images.githubusercontent.com/98426150/151055528-61c53431-e24c-4bba-8d4b-6b1d7d645204.jpg)

**Comment by MaFi-Games** [comment]
You need to discover an oil rig on the world map before these get available.

**Comment by HenkZaan** [comment]
Yeah, I noticed already. Was not realy clear. Maybe you make a better remark in the techtree or something. But great game so far.
