### ISSUE TITLE
Disappearing Maintenance Depot - Reproduce Steps|Video|Save|Log

### ISSUE THREAD

**Issue by Keranik** [MaFi-Games/Captain-of-Industry-issues#1320]
### Issue description

This issue is related to the disappearing buildings/maintenance depots.  I've included a video, the save file, the game log and some reproduction steps.
 
Link to video: 
https://youtu.be/wXBCMU1lvNg

### Reproduction steps

Step 1) Set speed to fastest
Step 2) Click Depot
Step 3) Upgrade and quick deliver with Unity
Step 4) Spam LMB on Entity while upgrading

### Game version and build number

v0.5.5c

### Operating system

Windows

### Attachments

[gameLog.txt](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13315555/gameLog.txt)
[Depot.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13315563/Depot.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed on Experimental and will be available on the main branch soon!
