### ISSUE TITLE
Two question about the electrolyser

### ISSUE THREAD

**Issue by ufm** [MaFi-Games/Captain-of-Industry-issues#1322]
1. Electrolyser cannot be accelerated using 'Unity.' There's simply no such button. Why?
2. The formula for water is H2O. It seems strange to me that an electrolyser can produce twice as much oxygen as hydrogen from water. It would be more logical the other way around.

**Comment by x3kj** [comment]
2) Weight of one Oxygen atom is much more than 2 H atoms. If you go by weight then the formula makes sense...  and besides that, it's a game. Getting H2 easily in quantity (for the same power) would make the game much more easy.

**Comment by MaFi-Games** [comment]
It can't be boosted as boost skips electricity requirement, so this could potentially provide lots of free power. Regarding the ratios, we balance it based on what the game needs. Also, as explained above by x3kj, it is not really a number of atoms that dictates mass.
