### ISSUE TITLE
Irrigated farm goes invisible at certain camera position and angles

### ISSUE THREAD

**Issue by KptKosmit91** [MaFi-Games/Captain-of-Industry-issues#1324]
### Issue description

In one of my saves, my irrigated farm goes invisible at specific camera positions and angles.

I think the best way to explain it is with this video:

https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/61065404/303477bf-e563-4168-bd8b-26ea02d9b15e

Placing the farm again, and even rotating it around by 180 degrees still causes the issue. Seems to also happen with the basic T1 farm.

### Reproduction steps

1. Load the attached save
2. Move to the farm, the issue occurs near the water collector
Example faulty camera positions (from _camera_position_print_)
 - 639.6182,1056.146,2,20.64941,358.3418,26.27539
 - 640.6113,1049.948,2,20.64941,1.992188,79.73633
 - 662.4922,1045.238,2,20.64941,359.666,58.45508
 - 643.5615,1055.115,2,33.19531,2.109375,79.55469

### Game version and build number

v0.5.5d b259

### Operating system

Windows

### Attachments

Note: I have used a mod to change some of the save's DifficultyGameConfig, and use another mod to tweak some material mining yields, however the save can be loaded without mods, and the mods don't affect the farm in any way.
[Save-disappearing-farm.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13491002/Save-disappearing-farm.zip)

**Comment by MaFi-Games** [comment]
This has been fixed in previous patches. If you run into more issues, please let us know in a new ticket. Thanks for your report!
