### ISSUE TITLE
Stuck with no construction parts 3

### ISSUE THREAD

**Issue by Hobknobber** [MaFi-Games/Captain-of-Industry-issues#1325]
### Issue description

I have explored everything in range, no settlements with construction parts 3 for sale. Just bad luck? Do I have to restart?

### Reproduction steps

It is the state of the game. Bad game seed?

### Game version and build number

v0.5.5d

### Operating system

Windows

### Attachments

[once again.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13497749/once.again.zip)

**Comment by KptKosmit91** [comment]
You are trying to build an Assembly Electric II. You can make Construction Parts III in a Tier 1 Assembly Electric which costs Construction Parts II. Once you can get that up and running you can upgrade to Assembly Electric II

Also as far as i know trades aren't random, they will always be the same for all worlds. Settlement positions will be different though

**Comment by Hobknobber** [comment]
Wow I completely spaced that! I guess its what I get for playing while sick with flu haha. Thank you!
