### ISSUE TITLE
Planned/Paused construction creates un-navigate-able terrain when loading saved game 

### ISSUE THREAD

**Issue by colez12345** [MaFi-Games/Captain-of-Industry-issues#1332]
### Issue description

Loading a saved game will cause vehicle navigation to act as if buildings with paused construction have already been built.

I tend to slowly un-pause sections of large planned constructions and haven't noticed this before. Possibly something in the recent save file or navigation optimizations if I had to venture a guess.

Testing notes (likely irrelevant, but I figured I would be thorough):
- Building type doesn't seem to matter (reproduced with assembly, belts, and brickworks)
- Vehicle type doesn't seem to matter (reproduced with truck, excavator, and tree cutter)
- Navigation overlay correctly indicates that the vehicles are not able to drive over the building
- Occurs for both copy/paste and manual placement
- Occurs for both planning mode and pausing construction

### Reproduction steps

1. Place any building
2. Pause construction on building
3. Vehicles should be able to drive though the area
4. Save game
5. Load game
6. Navigation overlay now treats the paused construction as if the building was already complete

### Game version and build number

v0.5.5d b259

### Operating system

Windows

### Attachments

![pathing](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/154963429/02455254-9bd3-44de-b876-85737ead046b)

**Comment by MaFi-Games** [comment]
Vehicles can't drive through ghosts. They never could. The reason is that when building the factory they would be getting frequently trapped.
