### ISSUE TITLE
Quartz crushed changes to quartz when dump on ground

### ISSUE THREAD

**Issue by kerth5** [MaFi-Games/Captain-of-Industry-issues#1340]
### Issue description

I am crushing quartz, put it on truck, and after dump it appears as quartz (not crushed)

### Reproduction steps

Crush quartz
Put on truck
Dump on ground - appears as normal not crushed quartz

### Game version and build number

Update 1 V 0.5.5D(B259)

### Operating system

Windows

**Comment by cosmosteve1** [comment]
I ran a test on this after OP mentioned it in the Discord server. When mining quartz and then crushing it, it does turn into crushed quartz. However, if you dump crushed quartz the game then magically turns it back into regular quartz. Note that I tested this on iron ore and copper ore, they DO NOT change back to ore when crushed iron or copper is dumped. Please see the attached pictures and test save (Captain of Cheats used in save to speed up testing).

1. See that I have only allowed trucks to dump crushed quartz in this zone. 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/86398256/ca881556-714d-4208-96df-d8d776f6e87d)

2. When I have an excavator mine the dumped material it is picking up quartz and not crushed quartz.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/86398256/203157a9-a254-4ecf-a3f2-6b16c8e13ef2)

3. The layers tool confirms it is quartz by signaling that the pile of "crushed quartz" is just quartz. 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/86398256/2c41e69c-cd06-466f-871e-a7260ce4e7e6)

4. Note that this does not happen with crushed iron. Notice that the excavator is digging up crushed iron and not iron ore. 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/86398256/3080f21d-9a14-45f1-b8ee-490c961a3612)

5. The same applies to crushed copper in which the excavator is digging up crushed copper. 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/86398256/fe152790-337b-4dc0-a34b-b78f55667d26)

Lastly, here is the save I used: 
[Quartz Test.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14735858/Quartz.Test.zip)

**Comment by MaFi-Games** [comment]
This was fixed in Update 2. Thanks for your report!
