### ISSUE TITLE
Upgrade 

### ISSUE THREAD

**Issue by petter566** [MaFi-Games/Captain-of-Industry-issues#1346]
### Issue description

when im using the upgrade toll everything is costing electonics is this a bug 

### Reproduction steps

is happing all over 

### Game version and build number

v0.5.5b

### Operating system

Windows

### Attachments

![20240125135605_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157709900/b327f5a7-e1dc-4cd1-bbd1-bf7d6642eef6)
![20240125135611_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157709900/68aab7bd-6c94-423a-9685-69081853498a)
![20240125135619_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157709900/2ced76f6-ea61-4e49-ac66-18340d89694a)

**Comment by poltime** [comment]
It's not a bug. https://wiki.captain-of-industry.com/Construction_Parts_II

**Comment by MaFi-Games** [comment]
This works as intended.
