### ISSUE TITLE
trucks dumping can't find dump location

### ISSUE THREAD

**Issue by Llewelyn1966** [MaFi-Games/Captain-of-Industry-issues#1348]
### Issue description

I'm building a 2-square-wide causeway across the sea to reach another piece of land.  It's not in an area controlled by a mine tower.  Global dumping is set to allow dumping, among other things, waste.  However I see multiple warnings that trucks can't find somewhere to dump.  One pickup is sitting about 3 squares away saying it can't find anywhere to dump its 20t of waste.  

Since this is a causeway, it can only have stuff dumped at the end, which is of course just 2 squares wide.  I suspect maybe each square has a limited number of trucks that can dump anything there at a given time, and once that number is reached it becomes invisible to other trucks.  That's what it looks like.

### Reproduction steps

Using the Z dumping key, create a 2-wide level dumping location extending out from the land.  Assign multiple trucks to mines etc. and allow dumping of dirt, rock, slag and waste.

### Game version and build number

v0.5.5d b259

### Operating system

Windows

**Comment by wzurborg** [comment]
Savegame is needed

**Comment by MaFi-Games** [comment]
Sorry, can't do much without a save file. If this issue occurs again, please file a new ticket with a save file attached.
