### ISSUE TITLE
Truck is turning around and around

### ISSUE THREAD

**Issue by Blottoo123** [MaFi-Games/Captain-of-Industry-issues#135]
**Describe the issue**
A Fuel Truck is turning around and around and around....

**To Reproduce**
1. Load attached save 'Blottoo Golden Peak Truck driving around'
2. Stare at it with open mouth. :D

**Expected behavior**
On this point of the map i had some problems with landslide, because the excavation area is a bit closely. There where a few Trucks which were stuck and i had to recover them, no problem.
But now one of the Fuel Trucks did not stuck, he is just turning around and around. I think that should not happen.

**Additional context**
 - Game version: 0.3.11f
 - 
**Attachments**
1 Savegame

[Blottoo Golden Peak Truck driving around.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7965848/Blottoo.Golden.Peak.Truck.driving.around.zip)

**Comment by Blottoo123** [comment]
I even figured out that i can´t recover that truck.

**Comment by Blottoo123** [comment]
When i excavate a flat area under the truck, he stopped to turn around and was going back to normal work.

**Comment by MaFi-Games** [comment]
I think this was fixed fo EA. Thanks for report!
