### ISSUE TITLE
Problem of picking up cargod with trucks.

### ISSUE THREAD

**Issue by Habigdog6969** [MaFi-Games/Captain-of-Industry-issues#1350]
### Issue description

I had tried all ways to pick up Slag Crushed with trucks from Crusher, but it didn't work. I only can use U-shaped Conveyors to transport them to Loose Storage and let the trucks pick up them to the other place.

### Reproduction steps

I don't know.

### Game version and build number

v0.5.5d b259

### Operating system

Windows

**Comment by wzurborg** [comment]
Savegame is needed

**Comment by MaFi-Games** [comment]
Sorry, can't do much without a save file. Feel free to file a new issue if it happens again and please attach a save file.
