### ISSUE TITLE
Power and Water Unity not calculating correctly

### ISSUE THREAD

**Issue by paddcc** [MaFi-Games/Captain-of-Industry-issues#1352]
### Issue description

I have more than enough power and water (Connected with a level 3 pipe) but I am only receiving partial unity

### Reproduction steps

Load saved game 
Wait one month - Unity will drop from positive to negative as none of the inputs will receive full credit

### Game version and build number

v0.5.5d(b259

### Operating system

Windows

### Attachments

[24-02-03_19-01-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14157357/24-02-03_19-01-autosave.zip)

**Comment by MaFi-Games** [comment]
Seems to be working as should, I don't see negative unity next month. It could have been fixed in Update 2 as we fixed few things there. If the issue occurs again, please file a new ticket. Thanks!
