### ISSUE TITLE
Refueling station truck ignoring a particular mine's excavator. Persists for newly constructed fuel station.

### ISSUE THREAD

**Issue by II9T5** [MaFi-Games/Captain-of-Industry-issues#1357]
### Issue description

Fuel truck assigned to a fuel station assigned to a mine refuses to refuel the mine's excavator.
It's not ignoring excavators for the other mine assigned to it. 

This persists with a  newly built fuel station too. 

### Reproduction steps

No idea how to reproduce it.

You can see it in the save. Load save, go to NW corner  of the map where there's the big distant coal patch and see for yourself.

The only extraordinary thing is that the area is cut off from the rest of the map because the excavator that was supposed to clear the way has no fuel.

### Game version and build number

v0.5.5d b259

### Operating system

Windows

### Attachments

[save_24-02-10_23-39-06_refuel bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14230724/save_24-02-10_23-39-06_refuel.bug.zip)

**Comment by poltime** [comment]
It happens when a truck from another fuel station has taken a queue to refuel the excavator. Сheck all the trucks that can't get to their destination.

**Comment by II9T5** [comment]
I'm pretty sure this was the case.
