### ISSUE TITLE
Trucks do not transport 13 items from A to B, no job created

### ISSUE THREAD

**Issue by wzurborg** [MaFi-Games/Captain-of-Industry-issues#1360]
### Issue description

I have a Unit Storage II (A) with 13 Enriched Uranium (20%), which I want to get transported to Unit Storage (B) which is empty. A is set to "Empty (0)" and B is set to "Keep Full (180)". 

- "Allow partially loaded trucks" is enabled.
- There is a clear path from A to B.
- There are idle trucks available to assign.

No job is created for the items to be transported! The items remain in storage A forever.

### Reproduction steps

1. Load attached save.
2. Locate storage boxes A and B in the SE corner of the map (in view when savegame is loaded)
3. Verify "Allow partially loaded trucks" is enabled.
4. Observe no job is created and no transport takes place.

### Game version and build number

v0.5.5D (B259)

### Operating system

Linux

### Attachments

[coi-bug-report.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14297409/coi-bug-report.save.zip)

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1320950/07e6e685-c977-4acd-8d2b-14c10dc3ce50)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1320950/eee888cc-02ad-4ad7-8f6a-d5740e4964c5)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1320950/34e83826-0da1-46c8-9c68-70b6208ecac2)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/1320950/6ad33ff5-0ba5-4d8e-99b8-70bc6ae4afe0)

**Comment by wzurborg** [comment]
There seems to be a minimum number of items to be considered a partial load for a truck.

I found out by experiment that a T1 truck needs at least 12 items (60%) to start a job with partial loads enabled. So I guess the minimum is 36 for a T2 truck.

We also know the minimum is 1 if the target only needs a small number to finish completion.

**Comment by MaFi-Games** [comment]
Yes, this is expected behavior. Partial trucks are required to have at least 50% of capacity utilized.
