### ISSUE TITLE
Visual glitch for farm

### ISSUE THREAD

**Issue by ApocalypticApes** [MaFi-Games/Captain-of-Industry-issues#1369]
### Issue description

Irrigated farm will have visual issues where the lines disappear when zooming in. Same with some of the rainwater harvesters.

### Reproduction steps

I can only replicate it by zooming in and out. Don't know what the root issue is.

### Game version and build number

Update 1 v0.5.5d (b260)

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/163105713/3f17d4e2-c079-451f-96ab-3406fb6ebfc2)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/163105713/64934967-feed-42c4-a5ce-4345dd5ef74e)

**Comment by MaFi-Games** [comment]
This has been fixed in previous patches. If you run into more issues please let us know in a new ticket. Thanks for your report!
