### ISSUE TITLE
Trucks deliver dump material to shipyard

### ISSUE THREAD

**Issue by Blottoo123** [MaFi-Games/Captain-of-Industry-issues#137]
**Describe the issue**
I have a problem with my Mining Tower (Delivery Issue Mining Tower). It´s one of the first Tower i build on this map and it worked well all the time. I use the Tower to organize dumping of all my Rock, Slag and Crushed Slag. Since today the trucks do something impossible, they deliver all Rock and Slag to the Shipyard instead of the Dumping-Area (Delivery Issue Dumping Area) of the Mining Tower. I didn´t change anything, i only the changed the Dumping Area. As you can see i have 28k Rock and 4,5k Crushed Slag in  my Shipyard (Delivery Issue Shipyard).

Edit: The solution was to replace the dumping area. But why?  And if i replace the dumping area to the old spot, they start to deliver to the shipyard again.

Edit: Yanderson told that it could be the boundary of the map. And it seems like he is right. I tested it with the Tower on the left of the "issue" Tower. I´m using that one to dump dirt. And i tried to assign that tower to the "Issue dumping Area" and the Trucks did the same.

Summary:  So the problem is that the trucks should stop working instead of deliver the materials to the shipyard when they can´t dump because the reach the boundary of the map.

**To Reproduce**
1. Load attached save "Blottoo Golden Peak Rock Delivery To Shipyard"
2. Select the loose storage as shown on picture (Delivery Issue Storage)
3. See how the Trucks are driving to the shipyard
4. Select the Mining Tower as shown on picture (Delivery Issue Mining Tower) to find the dumping area in the south west as shown on picture (Delivery Issue Dumping Area).

**Expected behavior**
Trucks deliver Rock and Crushed Slag to shipyard instead of assigned dumping area.

**Additional context**
 - Game version: 0.3.11f

**Attachments**
1 Save
4 Pictures

[Blottoo Golden Peak Rock Delivery to Shipyard.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7974376/Blottoo.Golden.Peak.Rock.Delivery.to.Shipyard.zip)

**Comment by Blottoo123** [comment]
Now it seems that the shipyard is just a buffer, because all unassigned truck´s are delivering the material, which is stored in shipyard, to the "new dumping area" of the loose storage where it comes from. That causes a very high truck queue, but it didn´t break the "free transport network". Transport priority will balance it.

**Comment by MaFi-Games** [comment]
I believe we have fixed this recently. There was a fallback that when dumping designations were not valid ores ended up in shipyhard. That should no longer be the case.
