### ISSUE TITLE
Game stops responding Alt Tabbing fixes it

### ISSUE THREAD

**Issue by ShermyPermy** [MaFi-Games/Captain-of-Industry-issues#1370]
### Issue description

When running the game my mouse clicks dont work anymore. this happens after about 30 to 50 seconds. the mouse stil moves on the screen but the clicks dont work and the scrollwheel also is not responding. after pressing alt tab 2 times the game continues as normal. then after a few min this happens again. it often happens in clusters with 30 sec intervals and then it will be fine for a few min. I hope you can help to fix this. best regards Shermy Oh btw it also happens in different screen resolutions. im runnig it in my native 1520x1440 at the moment 

### Reproduction steps

see issue description

### Game version and build number

v0.5.5d b260

### Operating system

Windows

**Comment by ShermyPermy** [comment]
Issue is fixed.Forced update to new graphics driver did the trick.

**Comment by MaFi-Games** [comment]
Glad the driver update fixed it for you! Marking as resolved.
