### ISSUE TITLE
Lagspike when constructing with resource display enabled

### ISSUE THREAD

**Issue by bigsagebeast** [MaFi-Games/Captain-of-Industry-issues#1377]
### Issue description

There's an understandable lag spike when you press "L" to turn on the resource display.
If you select a building to construct, place a building, cut a building, or generally interact with building ghosts at all, the lag spike is repeated.  This can make the game seem extremely unresponsive.

### Reproduction steps

Start a game on the new armageddon map (I think it's worse on larger maps)
Turn on resource display with L - note lag spike
Select a building to place - note lag spike
Place the building - note lag spike

### Game version and build number

v0.6.0 (b307)

### Operating system

Windows

**Comment by Dycart** [comment]
I wanted to add that, while I have the same issue, I have found that it is directly related to the resources shown. If you only show the grid, tree cutting, and mining overlays, it's not happening.

**Comment by MaFi-Games** [comment]
This was fixed in v0.6.1, thanks for the report!
