### ISSUE TITLE
Loading a game hangs for a long time on a full progress bar

### ISSUE THREAD

**Issue by bigsagebeast** [MaFi-Games/Captain-of-Industry-issues#1379]
### Issue description

Loading an early-game map on Armageddon, it took a solid minute with the loading bar full before it finished loading.  Seems like the loading bar needs to hang somewhere else besides the end, because it looked like the game froze.

### Reproduction steps

Probably all saves on a big map?

### Game version and build number

v0.6.0 (b307)

### Operating system

Windows

**Comment by bigsagebeast** [comment]
This got resolved in a recent patch.

**Comment by MaFi-Games** [comment]
Closing as fixed. Thanks!
