### ISSUE TITLE
ore yeld and research multipliers

### ISSUE THREAD

**Issue by hikkiko** [MaFi-Games/Captain-of-Industry-issues#1382]
### Issue description

ore yeld and research multipliers are not working. -75% and +50% give same amount of ore and take same time to mine.

### Reproduction steps

start the game and mine some ore

### Game version and build number

v0.6.0 (b314)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This was fixed in v0.6.0b. Thanks for your report!
