### ISSUE TITLE
Minor: Deleting savegames that is currently on the continue button

### ISSUE THREAD

**Issue by daemonazazel** [MaFi-Games/Captain-of-Industry-issues#1383]
### Issue description

When you delete a savegame from the load screen that is currently on the continue button, it will still be there when you get back to main menu. Only after you click it, it will disappear.

### Reproduction steps

1. Check which savegame is on the continue button
2. Go into load menu
3. delete said game
4. Go back
5. Check save on continue button

### Game version and build number

v0.6.0a b315

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Yeah, that's reasonable behavior to me.
