### ISSUE TITLE
Can't reuse save game folder

### ISSUE THREAD

**Issue by Quill0n** [MaFi-Games/Captain-of-Industry-issues#1386]
### Issue description

When you delete all the saves in a folder, the folder disappears in the in-game menu, but is still on your hard drive. When then trying to restart a folder with the same name, the game won't let you. Easy workaround is to 'Show in folder' and delete the folder from your harddrive manually, but this should probably be done automatically when all saves are deleted. Alternatively, let the player (opt to) re-use the existing folder.

### Reproduction steps

1. Delete all saves from a game folder
2. Folder disappears from load menu
3. Start new game with same name
4. Game won't let you
5. Go to Load
6. Go to Show in Folder
7. Delete folder from HD manually
8. Start new game with same name
9. Workaround achieved.

### Game version and build number

v0.6.0a b315

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This was fixed, thanks for the report!
