### ISSUE TITLE
Load Menu does not respect mod choices

### ISSUE THREAD

**Issue by Keranik** [MaFi-Games/Captain-of-Industry-issues#1389]
### Issue description

When you load a saved game that has mods enabled, and you choose not to load the game with those mods enabled, the menu does not respect the choices and will load the game with the mods anyway.  I've included a zip file with 3 dummy mods that are nothing but unique empty mods to demonstrate this behavior.

EDIT: May be related that the load menu also does not show the correct mod versions and list them as v0

### Reproduction steps

Start any game with any mod enabled
Save the game with the mods enabled
Load the game, but choose not to load with any specific mod
Game still loads with whatever mods it had in it regardless of choices

### Game version and build number

v0.6.0a (b315)

### Operating system

Windows

### Attachments
[DummyMods.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14894815/DummyMods.zip)

**Comment by MaFi-Games** [comment]
I believe we fixed this in recent patches. If not, please let us know, and we will look into it.
