### ISSUE TITLE
Partial Loaded trucks

### ISSUE THREAD

**Issue by Samspos** [MaFi-Games/Captain-of-Industry-issues#139]
i disables the option "partial loaded trucks" but there are trucks in a row with 1 building piece
![Setting](https://user-images.githubusercontent.com/98769682/152859248-57c4e62d-1946-406f-9288-6ca447c3fa7b.png)
![Load](https://user-images.githubusercontent.com/98769682/152859256-97a09e28-80d1-474c-9e66-9222d06cba42.png)
[Partial load.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8018179/Partial.load.zip)

**Comment by Samspos** [comment]
ok, maybe it's just an issue when priority is activatet

**Comment by PublicWorksTim** [comment]
No I think you are onto something here.
With it on or off my trucks move my Contruction 1's in batches of 4 whenever they are produced.
So something does seem faulty.

**Comment by MrJoshua023** [comment]
Came here to report, same issue.  Trucks get very busy loading 1 item a time occasionally, despite the partially loaded disallowed.

**Comment by Detanos** [comment]
I found the fix to this was to turn it Off then On then Off and it seems to fully load them again.

**Comment by MrJoshua023** [comment]
[PartiallyLoadedTrucks.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8867080/PartiallyLoadedTrucks.zip)

It works in some places, but others it doesn't.  Places I see it the most are when you are deconstructing something that you need to wait for trucks to empty it, and when they are taking from the shipyard.

Attached is save of the trucks unloading concrete from the shipyard.  ~6 at a time, dozens of trucks.

**Comment by AlphaZeon** [comment]
Just gonna throw a save with my newest problem in here just in case.  Trucks seemingly in an endless loop of loading and unloading steel from the Vehicle Depot  1-2 at a time
[Steel Truck Loop.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8869193/Steel.Truck.Loop.zip)
.

**Comment by MaFi-Games** [comment]
This has been fixed. The only place this can occur is "priority construction" and there it works as inteded.
