### ISSUE TITLE
Partial loads not taken from storage even when permitted

### ISSUE THREAD

**Issue by Dupie696** [MaFi-Games/Captain-of-Industry-issues#1390]
### Issue description

Partial loads not taken from storage even when permitted.

I've re-enabled partial loads in update 2. Not sure if this ever worked right. Used an update 1 game.

### Reproduction steps

Have mine fill up a bin with dirt.

Change dirt bin to fully empty with red slider to zero.

Create a mine control tower, set bin to export from bin. Set an area to dump. Set export to a disabled dirt bin somewhere else, so they dump locally.

### Game version and build number

v0.6.0a b315

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Partial does not apply to dumping from storage silos. One of the reasons is that there is nothing to gain by doing this in partial, unlike when balancing cargo between machines, for instance.
