### ISSUE TITLE
impossibile caricare il salvataggio

### ISSUE THREAD

**Issue by teonarcos89** [MaFi-Games/Captain-of-Industry-issues#1392]
### Issue description

provo a caricare il salvataggio creato nuovo qualche ora prima e viene fuori questo errore senza entrare nel gioco mandandomi invece nel menu principale

### Reproduction steps

basta solo caricare il salvataggio

### Game version and build number

v0.6.0 b309

### Operating system

Windows

### Attachments

![Screenshot (1)](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/45108024/b9ba4c1a-3ac8-4a21-a6c9-a59f7c4ea74d)
![Screenshot (2)](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/45108024/e4e6d44d-e4ca-4fa8-acba-460487c107e6)
[ok.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14895141/ok.zip)

**Comment by kennyb** [comment]
dup of #1420 and others. should be fixed in latest version.

**Comment by MaFi-Games** [comment]
Yup, this should now work. If not, please file a new issue.
