### ISSUE TITLE
incorrect display of decals

### ISSUE THREAD

**Issue by vitaliivitsenia** [MaFi-Games/Captain-of-Industry-issues#1394]
### Issue description

decals (paint) also draw a border

### Reproduction steps

just painting decals

### Game version and build number

v0.6.0b (b317)

### Operating system

Windows

### Attachments

![Screenshot 2024-04-07 125631](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/115216297/bb867b2d-7e74-4eaa-9737-05e9be851e11)

**Comment by Zardizz** [comment]
I have the same bug. Win10, same ver.

**Comment by MetallurgyBlockworks** [comment]
Same bug but on Cobblestone.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/162029849/49521674-7780-4bf9-be3e-2c270e411a23)

**Comment by MaFi-Games** [comment]
This should be fixed on the latest v0.6.0c, please let us know if that's not the case!

**Comment by MetallurgyBlockworks** [comment]
Confirming fix worked.

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/162029849/37ae641c-eb87-4d08-88cd-6e0d2b687805)
