### ISSUE TITLE
Trucks ignore freight limit on deconstruction of surfaces

### ISSUE THREAD

**Issue by SamPwcca** [MaFi-Games/Captain-of-Industry-issues#1396]
### Issue description

The first truck that comes to deconstruct a surface always ignores freight limit.

On additional trucks it's 50/50.

### Reproduction steps

1. Construct a surface
2. Desconstruct it
3. Keep an eye on the first truck that arrives to deconstruct it

### Game version and build number

v0.6.0b b317

### Operating system

Windows

### Attachments

![20240407172019_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/166315326/923775da-b6ad-4df3-af6c-ad9058623e71)

**Comment by MaFi-Games** [comment]
I can't seem to be able to reproduce this on my side. Would you have a save file where this occurs?

**Comment by MaFi-Games** [comment]
I have reproduced the issue, it is not necessarily related to the first truck but happens from time to time.

**Comment by MaFi-Games** [comment]
Fixed in one of the last patches. Thanks!
