### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by clockworkhero** [MaFi-Games/Captain-of-Industry-issues#1397]
### Issue description

Spelling mistake:
Incorrect=then
Correct=than

### Reproduction steps

1. New Game
2. Map selection
3. Armageddon
4. Second paragraph, seventh word should be "than" (see attached image for spelling mistake)

### Game version and build number

v0.6.0b b317

### Operating system

Windows

### Attachments

<img width="768" alt="COIerror" src="https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/3513406/d15bea8b-8eba-4b25-9952-b3f87dc25d4c">

**Comment by zuff-coi** [comment]
Thanks for your report!

**Comment by MaFi-Games** [comment]
Fixed, thanks!
