### ISSUE TITLE
pipe display error

### ISSUE THREAD

**Issue by xXmilchzombieXx** [MaFi-Games/Captain-of-Industry-issues#14]
**Describe the issue**
If you look at the pipe beside the farm the windows of it are empty but if I klick on the pipe it is displayed as full.

**To Reproduce**
1. Load attached save.
2. Look at the pipe beside the farm and klick on it.
3. The pipe is displayed as full but the windows that are empty.

**Expected behavior**
The pipe should if it is full display on all windows that it has a fluid in it.

**Additional context**
 - Game version: 0.2.5

**Attachments**
![image](https://user-images.githubusercontent.com/72553828/134744912-9b3e5dc8-695a-4cd6-a54b-fd5e809ad8a4.png)
[21-09-25_00-08-40_7040-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7228616/21-09-25_00-08-40_7040-autosave.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report but unfortunately I was not able to reproduce this. Does this happen to you if you load the attached save? Or is it "fixed" for you in the save as well? I will still check the code and try to see how this might happen but if this happens again, please add it to this thread.

![image](https://user-images.githubusercontent.com/90082857/134797345-0122a7f9-ff73-4823-a7ea-c329052defbc.png)

**Comment by xXmilchzombieXx** [comment]
I dont know it is always in my save game so it could be fixed to my savegame only but it displays a full pipe in the popup but the windows displaying a empty pipe or almost empty pipe.

**Comment by c0nnex** [comment]
I can second this report. Seeing Pipe-Glass not showing contents regulary

**Comment by MaFi-Games** [comment]
Thanks for reporting, unfortunately we were not able to reproduce this. If you encounter this again in upcoming beta release, please create another report.
