### ISSUE TITLE
Trucks get stuck at gas Station

### ISSUE THREAD

**Issue by Smedorin** [MaFi-Games/Captain-of-Industry-issues#140]
**Describe the issue**
After a certain amount of time in the game, the trucks will drive from a specific mining tower to the gas station. But they stay there and nothing happens. I removed the trucks from the demolition tower and turned off the option "All vehicles may refuel" at the gas station. The truck reassigned to the tower, the option at the gas station turned on again. This several times in a row, at some point they resumed their work and drove on. this problem occurred several times in the game.

**To Reproduce**
1. Load attached save '...'
[Smedo Beta_1_.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8104478/Smedo.Beta_1_.zip)
2. Do xxx 'At this time nothing. I try to replace the Mining tower to see if the issue stay there.'
3. Strange thing happens 'Trucks get stuck at gas station.'

**Expected behavior**

**Additional context**
 - Game version: Beta 0.3.11F

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

[Gas Station.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8104483/Gas.Station.zip)

**Comment by MaFi-Games** [comment]
Unfortunately as this is beta we can't reproduce anymore. But I hope we are ironed out lots of logistics issues already. Please file new ticket if you observer anything in the EA version.
