### ISSUE TITLE
gui mismatch in large tree harvester

### ISSUE THREAD

**Issue by Gforce4u** [MaFi-Games/Captain-of-Industry-issues#1404]
### Issue description

try selecting hydrogen truck in gui large tree harvester

### Reproduction steps

open gui large tree harvester 

### Game version and build number

0.6.c

### Operating system

Windows

### Attachments

![gui large trree harvester](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/36045825/9d12d788-90b5-4a4a-9afc-f056f977e647)

**Comment by zuff-coi** [comment]
Was able to reproduce, you can select the paused large tree harvester in this save here to see:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/8382ebb4-8402-4551-be1f-8c142eba4cc1)
[ui_issue_large_tree_harvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14921157/ui_issue_large_tree_harvester.zip)

**Comment by MaFi-Games** [comment]
This was fixed in v0.6.1, thanks!
