### ISSUE TITLE
[U2] Leveling designation with mixed truck loads requires going through Ore Sorter

### ISSUE THREAD

**Issue by cheics** [MaFi-Games/Captain-of-Industry-issues#1408]
### Issue description

When Mixed Ore Sorting is enabled, using the leveling designation means all trucks need to go through the ore sorter, rather than dumping locally

### Reproduction steps

Expected:
- Trucks with contents being loaded by excavators from a Mine Control Tower, that contain entirely items in the "What can be dumped here", should be able to dump their contents within the same mining area

Actual:
- Trucks end up dumping contents in ore sorter

Tower Settings:
![tower](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/904633/0d2bbf6a-6d21-41c7-80f1-3193b74d1a2d)

Truck Contents (driving away from leveling designation):
![truck](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/904633/e8d3e8dd-f5a5-4171-bd88-75c283eba40a)

### Game version and build number

v0.6.0d

### Operating system

Windows

**Comment by poltime** [comment]
Dumping has low priority. Remove ore in the sorter settings.

**Comment by cheics** [comment]
Admittedly, I can disable dirt/rock completely on the ore sorter, but I'd need to do so on all of them. Ideally, there could be a setting on the Mining Tower to "prioritize leveling/dumping at this site". There is no priority level that can be set individually for dumping.

**Comment by kennyb** [comment]
I can also concur that this is a difficult issue. I really would like an option (or maybe even make it default) "Reject dumpable product loads". the best fix for this would be to allow dumping of single-product loads within a mining tower's own or export route to another tower's designations. last option is a kind of distance specifier:
"Dump single-product loads within 1km |--o--------|" (and shows a circle of that radius).

one workaround I've found, is to just check "Reject single-product loads" -- however that only works if there is only one ore sorter (trucks will drive across the map to another compatible sorter with a mixed load). unfortunately, if for example, I'm mining coal or something and they get a full load of coal, then they don't know where to dump it now (or drive across the map to a coal bucket somewhere)

I want to use the sorter as a buffer for all non-dumpable products, so enabling "Reject single-product loads" isn't really what I want, and totally defeats the purpose of hooking belts to the sorter. for now, I just deal with the trucks needing to take an extra trip to dump (it's a little more realistic that way, as well)

**Comment by MaFi-Games** [comment]
This was fixed in v0.6.2. Please let us know if there any other issues. Thanks!
