### ISSUE TITLE
world mine empty, but still works

### ISSUE THREAD

**Issue by barsonian** [MaFi-Games/Captain-of-Industry-issues#1409]
### Issue description

see title. oil well is empty, but still producing

![bug_COI](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/58081627/6cae5afe-6369-4115-90b9-32e28d4ee686)

### Reproduction steps

load save
issue is happening (circled well)

### Game version and build number

v0.6.0d b322

### Operating system

Windows

### Attachments

[bug_save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14916962/bug_save.zip)

**Comment by zuff-coi** [comment]
I can confirm this is repeatable. Thank you for sharing!

**Comment by MaFi-Games** [comment]
Fixed in v0.6.2, thank you for the report!
