### ISSUE TITLE
time-lapse images are illegible and mostly transparent

### ISSUE THREAD

**Issue by PTTG-ACTUAL** [MaFi-Games/Captain-of-Industry-issues#141]
**Describe the issue**
The images produced by the timelapse script I used can't really be read. They are mostly transparent with corrupted looking pixels. See attached images.

**To Reproduce**
1. Load attached save 'succession.save'
2. Allow time to pass and see the resultant images. I am not sure what specific config was used, but maybe that's still in the save?
3. Strange thing happens View the screenshots in the timelapse output folder.

**Expected behavior**
Normally, the screenshots look fine.

**Additional context**
 - Game version: Beta 0.3.11F

Attachments:

[succession.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8121090/succession.zip)
![00001](https://user-images.githubusercontent.com/74290971/155243184-e3a0f1d6-95aa-447b-a39d-f1d7250dc5a3.jpg)
![00119](https://user-images.githubusercontent.com/74290971/155243190-eb3e8fd5-e3cf-44a3-8f7a-b48b34570f1c.jpg)

**Comment by MaFi-Games** [comment]
By any chance do you remember the command you used to set the timelapse up?

**Comment by Dynortice** [comment]
Small update:
Just made another timelapse while playing on 5120x2160 resolution using next command `timelapse_start_at_current_camera_pose main 60 5120 2160`. Result the same but then I tried to crop image to 3840x2160. It turned up that border between two parts of screenshot exactly on 3840 so this bug probably comes from non-standard resolutions. Maybe info about connected display with such resolution saved somewhere in Windows and this bug happens even after unplugging that display.

**Comment by MaFi-Games** [comment]
Does this still happen in the current version?

**Comment by MaFi-Games** [comment]
Closing as we don't have a reproduction in the new version. If this still persists on the latest version, please file a bug with more details.
