### ISSUE TITLE
Burner operating with no input

### ISSUE THREAD

**Issue by Sp4ceCore** [MaFi-Games/Captain-of-Industry-issues#1411]
### Issue description

Burner connected to a belt of sulfur is burning sulfur forever. Internal buffer will not go down.

### Reproduction steps

Internal buffer seems to be stuck when import trucks are turned off. Turning trucks back to auto or on makes the buffer go down.
Didn't see what caused the issue first.

### Game version and build number

v0.6.0d b322

### Operating system

Windows

### Attachments

[Bug unlimited sulfur burning.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14920466/Bug.unlimited.sulfur.burning.zip)

**Comment by zuff-coi** [comment]
The burner had a back up sulfur in its buffer upon load (8 in this image)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/585c10bf-5a01-4475-9938-c7f555168d80)
After I let it run for a bit it eventually burned through the buffer and stopped working:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/108291414/7cc7702f-405e-41aa-bd40-a5175ddd9a66)

I cannot reproduce this issue as I believe it is working as intended.
