### ISSUE TITLE
Flipping a Pipe and a Ghost Building

### ISSUE THREAD

**Issue by Biangateyebeem** [MaFi-Games/Captain-of-Industry-issues#1414]
### Issue description

Flipping pipe via shortcut key while mouse is hovering over another ghost building will flip both.

### Reproduction steps

1. Select a building that supports being flipped via shortcut key, for example: pipes/conveyors
2. Hover mouse over a ghost building, for example: boiler/distillation (stage I)
3. Press the flip shortcut key (Default: F)

My Opinion of Expected Behavior:
  pipe/conveyor are flipped
Actual:
  Both buildings are flipped

### Game version and build number

v0.6.0d b322

### Operating system

Linux

**Comment by MaFi-Games** [comment]
Fixed in v0.6.2a, thanks!
