### ISSUE TITLE
Excavation selection not showing up.

### ISSUE THREAD

**Issue by John66999** [MaFi-Games/Captain-of-Industry-issues#142]
Excavation selection (creation) not showing up totaly nothing, only (rmb) remove draw red square.

To Reproduce
No idea im using old pc capable of support dx10.1.
It must be rendering issue (newest draw functions not supported by dx9-10.1 (opengl crash at start with unity)).
I tried all graphical setting from fast to best, multiple resolutions, even scaling nothing change.

**Expected behavior**
I wish to see selection square while drawing excavation blueprint/plan.

**Additional context**
 - Game version: 0.2.1a, and same in 0.3.11

**Attachments**
There is nothing to see that's the problem.

**Comment by MaFi-Games** [comment]
Closing as this is an older beta issue, and also we don't have a repro.
