### ISSUE TITLE
Health statistics entierly bugged since relase (+, - total)

### ISSUE THREAD

**Issue by akda97** [MaFi-Games/Captain-of-Industry-issues#1422]
### Issue description

Pretty much the same issue, which has been already reported by another user:
https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/205
+, - total health is entierly bugged and not showing the real values in the statistics tab.
For example:
Total - should be the sum of all the negative health modifiers, to quickly see the trends.
It would be nice how the total + and - health effects compare to eachother. I experience this issue since release (2 years ago).

![Screenshot (23) - Copy](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/166658408/88bd906e-90de-4030-891d-8d0545ed3198)

### Reproduction steps

It is present on every save file.

### Game version and build number

v0.6.0d b322

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Fixed in one of the last patches. However historical values will unfortunately remain broken. Thanks!
