### ISSUE TITLE
U-Shaped Sorter Not Working

### ISSUE THREAD

**Issue by jwalthall** [MaFi-Games/Captain-of-Industry-issues#1423]
### Issue description

The U-Shaped sorter is not working as of 0.6.0d. It has power and conveyors are connected, but nothing moves through. 

### Reproduction steps

1. Load attached save. 
2. See sorter next to output of recycling center 

### Game version and build number

v0.6.0d b322

### Operating system

Windows

### Attachments

[Save File.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14938480/Save.File.zip)

**Comment by MaFi-Games** [comment]
Thanks! It is working. The issue is that the belts are not taking the sorter's input because they are not moving and they are not moving because they are not connected to anything.
