### ISSUE TITLE
wont dump when other storage is built.

### ISSUE THREAD

**Issue by loveandwar21** [MaFi-Games/Captain-of-Industry-issues#1424]
### Issue description

Trucks will not dump material in available dumping zones, even when constructed containers are full.

### Reproduction steps

build a storage bin for slag.
let it get full
watch as backup dumping sites don't get used and your smelters grind to a halt.

### Game version and build number

v0.6.0d b322

### Operating system

Windows

**Comment by poltime** [comment]
Check vehicles management, most likely slag is not allowed to be dumped.

**Comment by loveandwar21** [comment]
i have existing dump sites that are no longer being used since i built my
first loose storages.

**Comment by loveandwar21** [comment]
never mind. somehow the dumping designation was 2 levels too low adn the
trucks couldn't dump there. sorry about that.

**Comment by MaFi-Games** [comment]
No worries! Let us know if you run into more issues. Closing as not actionable.
