### ISSUE TITLE
Harvesters reporting "no trees" when in the middle of a marked forest

### ISSUE THREAD

**Issue by bigsagebeast** [MaFi-Games/Captain-of-Industry-issues#1425]
### Issue description

I'm not sure what caused the bug - it happened around the time I ran out of diesel but that may be unrelated.  My harvesters suddenly decided that they couldn't find any trees, even though I had trees marked.  Directing the harvesters into a forest shows that they can path there, but they won't start harvesting.
Failed attempts at fixing it:
- Reloading the game
- Making the harvesters navigate somewhere
- Ensuring their attached trucks have empty inventory
- Recalling the harvesters to the vehicle depot
- Deselecting all trees for harvesting, and reselecting them
I'd love to know a workaround if you find one so that I can continue my game!

### Reproduction steps

Load the save, observe that the harvesters are generating an error message.

### Game version and build number

v0.6.1 (b323)

### Operating system

Windows

### Attachments

[no tree to harvest.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14940563/no.tree.to.harvest.zip)

**Comment by bigsagebeast** [comment]
Just realized that I started playing with the DoubleQoL mod, so you probably can't use my saved game and the bug might be in the mod.  Sorry about that!  (That's the only mod I'm using.)

**Comment by MaFi-Games** [comment]
Alright then. I will close this as not reproducible. If this happens in vanilla, please file an issue, and we'll take a look. Thanks!
