### ISSUE TITLE
Trucks constantly "out of fuel"

### ISSUE THREAD

**Issue by OldManBussy** [MaFi-Games/Captain-of-Industry-issues#1426]
### Issue description

First off, love the game. 
Since the most recent update, I have constantly had trucks running out of fuel, usually on their way to dump slag or dirt. I strategically placed a fuel station where it normally occurs, only for them to drive right past it, run out of fuel, and then return to get refueled. It's not game breaking by any means, but it is kind of annoying to have the notification constantly popping up. 

### Reproduction steps

Have trucks driving to a designated dumping site that is marginally far away from where they were loaded

### Game version and build number

v0.6.1 b323

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Thank you! In v0.6.2, we have improved the out-of-fuel notification, to make it trigger only when it makes sense. So  I'm marking this as fixed. Please file a new issue if it persists. Thanks!
