### ISSUE TITLE
Population while clicking on housing won’t move separately 

### ISSUE THREAD

**Issue by wawaskittle** [MaFi-Games/Captain-of-Industry-issues#143]
**Describe the issue**
This is pretty low on the list, however when clicking on housing the population tab will not move separately. The “unity requirement” tab will. However when attempting to move only the population tab it will move both. 

**To Reproduce**
1. Click on housing module
2. Move unity requirement tab then attempt to move population. 
3. Both tabs will move with the population tab.

**Expected behavior**
Population tab to move by itself

**Additional context**
 - Game version: current beta build

**Comment by MaFi-Games** [comment]
These windows are now properly connected to move together.
