### ISSUE TITLE
Flashing white circles on pipes when zoomed in

### ISSUE THREAD

**Issue by RaidSoft** [MaFi-Games/Captain-of-Industry-issues#1432]
### Issue description

I'm running into an issue of white flashing circles that only appear when zoomed in very close and (so far) only seems to happen to pipes specifically. They only flash while actively moving the camera around, if I find the exact angle they flashed at I can make them stay visible permanently until I move the camera again.

My hardware is an 7800X3D, 32 GB 6000Mhz CL30 ram, AMD 6800XT GPU running the currently latest 24.3.1 drivers. I had the issue also appear on an older driver version (23.X something, can't remember exact version) but after cleaning with DDU and updating the issue remains. No in-game settings seem to affect the behavior, I went through pretty much every setting that could be toggled to see if anything changed it.

I recorded a video with an example of the issue, it happens even with the AMD recording software disabled. 
https://www.youtube.com/watch?v=zquZVQmO_k0

### Reproduction steps

Zoom in as close as possible to constructed pipes and move the camera around, white flashes appear mostly towards the edges of the screen. 
See linked video for example.

### Game version and build number

v0.6.1 b323

### Operating system

Windows

### Attachments
[Save 2024-04-11, 05-15-45.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14948998/Save.2024-04-11.05-15-45.zip)

_No response_

**Comment by elsender** [comment]
Woohoo..

I'm not the only one with the flashing pipes issue anymore.
see issue #1401.

your Hardware us very similar to mine.

I feel your pain, it is very irritating. I'm just glad I don't have a history of seizures.
They are working on it. hopefully they figure it out soon.

**Comment by RaidSoft** [comment]
Ah I'm surprised I missed your issue about the problem, I thought I looked through it quite closely. 

It's definitely the same problem and I'm glad they are aware and are working on it!

I'm not too used to how issues are tracked and such here, any idea if I should I close this one as duplicate and chime in on your post instead?

**Comment by elsender** [comment]
I would definitely mark it as a duplicate.
at the very least it saves the Moderators and Devs some time from having to do it.
Chiming in would also be helpful, the more the issue is reported the better.
