### ISSUE TITLE
Conveyor lifts changing rotation direction

### ISSUE THREAD

**Issue by kingsepp01** [MaFi-Games/Captain-of-Industry-issues#1433]
### Issue description

If the running direction of the conveyor lifts is changed downwards, the visible direction of rotation remains the same, even if the running direction is changed back up. After restarting the game, everything is normal again. Furthermore, it doesn't really make sense to change the rotation direction of paddle wheels :-)

### Reproduction steps

Construct conveyor lift and connect it to belts. Change rotation direction and switch back

### Game version and build number

v0.6.1 b323

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Fixed in v0.6.2a, thanks!
