### ISSUE TITLE
Negative loan balance

### ISSUE THREAD

**Issue by MihasyaC** [MaFi-Games/Captain-of-Industry-issues#1434]
### Issue description

My debt is growing in the NEGATIVE. Now I have to minus 43,716 t2 electronics. At the same time, I can take out a new loan for these electronics, and my credit rating is also going up
![Screenshot_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/166946885/57cf052e-9307-407e-bebe-f456fe667444)

### Reproduction steps

1.Take out a loan
2.Delay some payments
3.Wait until the end of the loan repayment period

### Game version and build number

v0.6.1 b323

### Operating system

Windows

**Comment by MihasyaC** [comment]
https://drive.google.com/file/d/1S5T_TDxJKEN7_pMRKHdGXXZ2UtT6zmwk/view?usp=sharing
This is my saved game, to reproduce the error

**Comment by MaFi-Games** [comment]
This was fixed in v0.6.2, thanks for the report!
