### ISSUE TITLE
Dock issues one Fluid Module can not be removed , will not unload oil so overall can not destroy docks to replace

### ISSUE THREAD

**Issue by GamiWombat** [MaFi-Games/Captain-of-Industry-issues#144]
**Describe the issue**
The Large Dock I can not remove . It will not allow me to remove one of the fluid modules . It also will not allow me to select a stored product. and has one ship waiting to unload on the last fluid module i can not remove. I can rebuild all other 3 modules but can not remove that last one. nothing seems to work.  

**To Reproduce**
Have not re produced yet. 

**Expected behavior**
Can not destroy the dock or fluid module can not unload the last oil from ship . even if all connected. 

**Additional context**
 - latest build in beta 

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
[Can not destroy this dock _.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8190819/Can.not.destroy.this.dock._.zip)

**Comment by MaFi-Games** [comment]
We have heavily improved this flow for EA. So this issue should be gone.
