### ISSUE TITLE
Key Bindings and menu issues.

### ISSUE THREAD

**Issue by Brandon-way2140** [MaFi-Games/Captain-of-Industry-issues#1440]
### Issue description

I cannot save my game as the pause menu is not working. My escape key does not bring up the menu and my D key brings up my windows calendar. 

### Reproduction steps

I don't believe anything triggered this. I went to save and exit by hitting escape and the menu did not come up so I went to the lower right corner and the menu came up but I could not hit any of the buttons. It showed me hitting them but no other menus came up.

### Game version and build number

V0.6.1(b323)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Sorry to hear that. Does this occur every time, or was it a one-time thing?

**Comment by Brandon-way2140** [comment]
It seemed to be a one time thing bc I got an auto save and was able to
close the game via task manager and reloaded the game and everyone worked,
im thinking there was some keyboard short cut I hit accidentally but could
not pinpoint it.

**Comment by CaptainMarek** [comment]
This was fixed in v0.6.3b, thanks for the report.
