### ISSUE TITLE
Trucks still drive with empty Tank after turning difficulty up

### ISSUE THREAD

**Issue by Wilm4RRrr-Butzen** [MaFi-Games/Captain-of-Industry-issues#1442]
### Issue description

I started my Save with easier options and decided later that trucks should stop with an empty tank but they can still drive when their tank is empty, I get the warning and all but they still drive around.

Added my Save, maybe its an issue with that

### Reproduction steps

1. Start a game where trucks can drive with an empty tank
2. change the setting so that they should stop
3. Trucks with no fuel still drive around

### Game version and build number

v0.6.1 (b323)

### Operating system

Windows

**Comment by Beric01** [comment]
If trucks are on the way to a fuel source to refuel and run out on the way, they can drive even when empty. That is not a bug. I believe it's due to limitations of the pathfinding being able to tell when you will run out of fuel.

**Comment by MaFi-Games** [comment]
Can you please clarify whether this occurs when they go for fuel? As that's expected. If it happens outside of that case, let us know. If you also have a save by any chance that would help as well.

**Comment by Wilm4RRrr-Butzen** [comment]
It mostly happened after the trucks drove over half the map to dump rock, when they were empty they threw the error message and drove to refuel. But that happend yesterday. I'm pretty sure latest patch fixed it. I can't provide a save right now because I'm not at home.

**Comment by Wilm4RRrr-Butzen** [comment]
I dont get the error anymore so consider it fixed
