### ISSUE TITLE
Excavator inaccessible by trucks in open area

### ISSUE THREAD

**Issue by Beric01** [MaFi-Games/Captain-of-Industry-issues#1443]
### Issue description

Seem to have an excavator inaccessible by trucks no matter where it goes. Was stuck previously but moved it and status won't reset even on open terrain, or unassigning and reassigning to tower. Happens on save load. Problem only solved with vehicle recovery. 

### Reproduction steps

Load save, see excavator with stuck status. Should be reproducible on load.

### Game version and build number

v0.6.1 (b323)

### Operating system

Windows

### Attachments

[sav11e.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14972420/sav11e.zip)

**Comment by MaFi-Games** [comment]
Fixed in the previous patch. Thank you!
