### ISSUE TITLE
Goal "Improve Slag Export" has the sub goal "Research Storage" but there is no "Storage" in the research tree anymore

### ISSUE THREAD

**Issue by sauerstein** [MaFi-Games/Captain-of-Industry-issues#1449]
### Issue description

In the latest patch (version 0.6.2) the research tree was refined and apparently "Storage" as a research topic was remove / merged.
As the goal Improve Slag Export need **Storage** to be research, but Storage doesn't exist anymore, you can't finish the goal.
I assume the Goal needs the _Loose Storage_ which was moved into the research topic **Vehicles and Mining**.

### Reproduction steps

Play the game (Easy Starter Map) and follow the goals. At some point the the goal **Improve Slag Export** pops up.

### Game version and build number

v0.6.2

### Operating system

Windows

### Attachments

![ImproveSlagExport](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/55191486/d8049207-8b97-4060-aa4d-9c5ca793b0dd)

**Comment by MaFi-Games** [comment]
I think you had this goal created just when we patched the new changes in. If yes, please just skip this goal and keep going, we can't unfortunately fix this retrospectively.

**Comment by sauerstein** [comment]
Just to be clear, I started (bought) the game yesterday evening and played around 5 minutes. This goal was not there yesterday.
After the game was updated today to version 0.6.2 I continued my previous game and after around 2 hours, this goal was shown to me. So the goal was activated in version 0.6.2. Of course I'm not sure, what's inside the save file.

Nevertheless I don't care about fixing MY play through. If you're sure, it had something to do with my save file, please close this ticket.

Cheers and have a productive week!

**Comment by sauerstein** [comment]
If this ticket is actually valid, I found another one after continuing the game. The goal **Coal Power Plant** also tells me to research **Storage**. Let me know what you think and I'll update the ticket accordingly.

**Comment by MaFi-Games** [comment]
Right, this can get confusing quickly. I have added a workaround to prune obsolete goals. It will be available in the next patch. Thanks for bringing this up!

**Comment by sauerstein** [comment]
Thank you for implementing a workaround 👍  I guess the research tree will change some more times until it's fully released :-). I'll close the issue!
