### ISSUE TITLE
Fast Breeder Reactor bug

### ISSUE THREAD

**Issue by NationalCemetery** [MaFi-Games/Captain-of-Industry-issues#1450]
### Issue description

no steam

### Reproduction steps

Fast Breeder Reactor on > no steam...  The game is so fun that I want to play it quickly, but I can't because of bugs.

### Game version and build number

v0.6.2 b327

### Operating system

Windows

### Attachments

https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/110435655/28cd1691-8e01-4757-a2e8-d71ba77682cf

[24-04-16_11-17-49_3645.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14986156/24-04-16_11-17-49_3645.log)

**Comment by MaFi-Games** [comment]
The video does not seem to be working. Can you please zip and share your save file?

**Comment by NationalCemetery** [comment]
[ezyZip.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15016079/ezyZip.zip)

**Comment by MaFi-Games** [comment]
You are not supplying it with water. It is only getting the emergency cooling water. So it is overheating and having to cool itself. You need to plug the rest of the water input ports.

**Comment by NationalCemetery** [comment]
I was really foolish. Thank you so much for your help, and I am very grateful for making the game for me

**Comment by MaFi-Games** [comment]
No worries at all, glad it got solved for you!
