### ISSUE TITLE
Not using goods at trading doc

### ISSUE THREAD

**Issue by Sam13576** [MaFi-Games/Captain-of-Industry-issues#1453]
### Issue description

I have diesel issues so I took out a loan in June 0041.
However trucks are not loading the diesel into the fuel station..
I have put the export on 1 , sliders are correct and importing 1 however nothing is happening so far

### Reproduction steps

Load attached save and just press play you will see that trucks are not loading the diesel from the cargo dock to the fuel station and so I keep on spiralling

### Game version and build number

v0.6.2(b327)

### Operating system

Windows

### Attachments

[24-04-16_13-15-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/14996058/24-04-16_13-15-autosave.zip)

**Comment by MaFi-Games** [comment]
This is be cause you have a custom route assigned there and there is also "Accept assigned only" checked which prevents any other sources to deliver there. Solution in your case is to uncheck that toggle:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/7f2a30c2-b61d-49a9-97d9-9d0a1bef625e)
