### ISSUE TITLE
loans are ended even though not fully paid.

### ISSUE THREAD

**Issue by glilienthal** [MaFi-Games/Captain-of-Industry-issues#1466]
### Issue description

I got a loan of construction parts II, I did only pay it back partially. (As seen in the view on what I paid when). Even though I did not pay everything back, there was a lot of still outstanding, the loan still disappeared after the planned 10 years were over, and my credit score even increased. 

I'd expect the loan to run longer, until it's completely paid back. 

### Reproduction steps

Just normal playing, admiral difficulty, insane setting on armageddon. 

### Game version and build number

v0.6.2a B328

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Would you have a save file of where this occurred? Ideally with the loan being progress?

**Comment by glilienthal** [comment]
tbh, I am no longer sure this really being a problem. Maybe I misunderstood the whole systematic of the loan system. I'll close this and come back if I see this problem again.
