### ISSUE TITLE
Save load settings menu all grayed out can’t save

### ISSUE THREAD

**Issue by MrMayhem007** [MaFi-Games/Captain-of-Industry-issues#1470]
### Issue description

I can’t click anything in the Continue Save Load Settings window. None of the buttons execute. Window will close if I click the 3 bars button in bottom right of screen to continue play but again nothing else works. 

### Reproduction steps

1. Clicked 3 bars bottom right to bring up save menu. 
2. Click every button and none of them execute. 
3. Reclick 3 bars and can continue playing. 
![IMG_9720](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/167735682/58ec8e84-de96-4a04-b4d3-94158cb1694d)

### Game version and build number

V0.6.2a (b328)

### Operating system

Windows

**Comment by CaptainMarek** [comment]
This was fixed in v0.6.3b, thanks for the report.
