### ISSUE TITLE
После обновления 0.6.2 нет карты

### ISSUE THREAD

**Issue by Vorobey58** [MaFi-Games/Captain-of-Industry-issues#1471]
### Issue description

Здравствуйте. После того как я обновил игру до 0.6.2 версии, исчезла игровая карта. Я переустановил драйвер видеокарты. Gforce GTS-250, Обновил все библиотеки виндовс 11. Ничего не помогает. Ни одна карта не загружается. Я не знаю. что мне делать. 

### Reproduction steps

Проблема появляется при загрузке новой или сохраненной игры или редактора карт

### Game version and build number

v0.6.2 b327

### Operating system

Windows

### Attachments

![Screenshot_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/167806428/14268c8b-3e06-4f25-b01a-7f1b126b075a)

**Comment by poltime** [comment]
Выброси этот древний шлак и купи нормальную видеокарту.

**Comment by MaFi-Games** [comment]
Seems like a hardware / driver issue. We have no other similar reports.
