### ISSUE TITLE
screen capture / P / F11

### ISSUE THREAD

**Issue by stratege1401** [MaFi-Games/Captain-of-Industry-issues#1482]
### Issue description

Not really a bug, but in game mode P is not taking screenshots.
If the informer screen for a merger, a pipe or any object is open, hitting F11 to do a screencaps simply close the informer window.
Could be nice to "pin" this windows ... or do i misse something. ? 

### Reproduction steps

P / F11

### Game version and build number

U2|v0.6.3a

### Operating system

Windows

**Comment by MaFi-Games** [comment]
This works as intended. There are many shortcuts in F11 mode, and they are not added to the game on purpose. Also F11 / photo mode does not support any other UI over it.

**Comment by MaFi-Games** [comment]
This works as intended. There are many shortcuts in F11 mode, and they are not added to the game on purpose. Also F11 / photo mode does not support any other UI over it.
