### ISSUE TITLE
Text out of window boundary in MAINTENANCE DEPOT

### ISSUE THREAD

**Issue by kyklish** [MaFi-Games/Captain-of-Industry-issues#1483]
### Issue description

Text out of window boundary in MAINTENANCE DEPOT

### Reproduction steps

Get too much MAX maintenance at once.

### Game version and build number

v0.6.3

### Operating system

Windows

### Attachments

![Untitled](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/964801/bc8e9abd-1a03-4657-b5fa-00193f04a575)

**Comment by cgrimes85** [comment]
![image](https://github.com/user-attachments/assets/c2dd4688-aa16-45c4-907c-abc46eace9ec)
