### ISSUE TITLE
Flowers show up in the recipe preview for the Greenhouses without supporter edition

### ISSUE THREAD

**Issue by NanoCE** [MaFi-Games/Captain-of-Industry-issues#1489]
### Issue description

When you mouse over either of the greenhouses in the menu, you are given a preview of all the recipes they provide. While I don't own the supporter edition, I can still view that the greenhouses can grow flowers in that preview UI. If I build the greenhouse, the flowers are not available.

### Reproduction steps

View menu recipe preview for greenhouses.

### Game version and build number

v0.6.3 b333

### Operating system

Windows

**Comment by CaptainMarek** [comment]
Thanks for the report, this was fixed in v0.6.3b
