### ISSUE TITLE
Cargo depot unloading animation plays for unit module with no workers

### ISSUE THREAD

**Issue by pyrolitic** [MaFi-Games/Captain-of-Industry-issues#149]
**Describe the issue**
No gameplay effect, just an annoyance. I have a small cargo depot with a unit module that has no workers but is otherwise active. The unloading animation plays continuously, but no products are actually unloaded.

**To Reproduce**
See attached zipped save file.

**Expected behavior**
Don't play the unloading animation when there are no workers in the unit module.

**Additional context**
 - Game version: 0.3.11f Beta

**Attachments**
[save_22-03-20_18-16-52.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8311907/save_22-03-20_18-16-52.zip)
![image](https://user-images.githubusercontent.com/1881704/159176697-f40e9e05-903e-4c7f-b2ec-e3e4d979ac58.png)
![image](https://user-images.githubusercontent.com/1881704/159176731-9fbdbffb-6c25-4187-bda9-6534daaa5f5f.png)

**Comment by MaFi-Games** [comment]
I believe this was fixed before we launched EA.
