### ISSUE TITLE
Trucks want to go to an empty piece of sea

### ISSUE THREAD

**Issue by sgroef** [MaFi-Games/Captain-of-Industry-issues#1495]
### Issue description

Unassigned trucks in my game are trying to move to a random place in the sea. There is, and never has been anything in that particular spot. It's about 5 tiles away from freshly reclaimed land. [Screenshot of the place](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7044538/f46a99a9-d533-4662-855f-2fa966771d28)

The trucks still snap out of it to do actual jobs (no offense), but about half a minute after they're idle they will try to go to the magic spot again. I can also manually point them to another place, same result.

The problem randomly started while I was pretty deep in this run.

### Reproduction steps

Load the savegame and check the trucks that can't reach their destinations. 

### Game version and build number

v0.6.3a

### Operating system

Windows

### Attachments

[bugged.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15190044/bugged.zip) savegame

**Comment by sgroef** [comment]
I think they're trying to find a route to put concrete surface in the sea, caused by me overshooting the surface from the land into the sea.

So the actual issue is that it's possible to apply surfaces underwater and you're not able to see the light, not layed versions, of the surface there.

**Comment by CaptainMarek** [comment]
Thanks for the report, this was fixed in v0.6.3b
