### ISSUE TITLE
Loading savefile crashes computer (freezes until i reset or it BSOD)

### ISSUE THREAD

**Issue by Ueland** [MaFi-Games/Captain-of-Industry-issues#1496]
### Issue description

I have a save I have been plying on since update II, suddenly today it crashes my computer completely when loading it. So as of now it's corrupted.
(For some strange reason, this also corrupts my Discord installation, impressive!)

### Reproduction steps

1. Load savefile
2. Panic?

### Game version and build number

v0.6.3a (b333)

### Operating system

Windows

### Attachments

[24-05-02_21-19-32_3354.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15193032/24-05-02_21-19-32_3354.log)

**Comment by Ueland** [comment]
Added the wrong savefile, correct ones incoming

**Comment by Ueland** [comment]
[working.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15193080/working.zip)
[corrupted.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15193081/corrupted.zip)

Attached here is two savefiles, corrupted.zip is the broken one, working.zip is the version from before, which still works.

Now for reinstalling Discord again...

**Comment by Ueland** [comment]
A user on Discord tested the corrupted zip without issues. So i tested a freshly installed Windows instance (another machine), and it loads without issues there also. Will do some more troubleshooting to try and pinpoint the cause.

**Comment by MaFi-Games** [comment]
This is definitely a hardware or driver issue. A game on its own can't crash your computer. I would recommend going to the event viewer on Windows to get more insight into why it crashed:
https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by Ueland** [comment]
Can confirm that it seems so. The issue disappeared next day. Will re-create it if it happens again and *if* i have proof that its related to the game, doubt it :)
