### ISSUE TITLE
Trucks unable to deliver upgrade materials to one greenhouse out of many

### ISSUE THREAD

**Issue by tvo** [MaFi-Games/Captain-of-Industry-issues#1497]
### Issue description

I've got an area with 10 greenhouses in 5x2 configuration. I've scheduled an upgrade of all of them to greenhouse II. For all except one, trucks successfully delivered red construction parts and/or glass (some already successfully finished the upgrade).

Unexpectedly, trucks claim to be unable to deliver to **one** out of the ten greenhouses in this area, and not even the one that I would expect to be hardest to reach. In the attached save you can see that most greenhouses got red construction parts for the upgrade delivered already, and enough red construction parts are available for this last one. But somehow, no truck wants to deliver to this one greenhouse.

To check/demonstrate how reachable the greenhouse is I manually ordered one truck to go right next to it and it was able to do so, while still claiming that it was unable to reach the greenhouse.

See screenshots and/or attached save. 

### Reproduction steps

1. Load attached save.
2. Find the area of 5x2 greenhouses that are in the process of upgrades to greenhouse II, next to the coal mine.
3. Click the greenhouse to observe the red lines from idle trucks to this greenhouse or observe the notification about trucks being unable to reach this greenhouse.

### Game version and build number

v0.6.3a

### Operating system

Windows

### Attachments

![20240502222250_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/43037/6f904316-8de4-4f58-823a-4125681c94b3)

![20240502224807_1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/43037/0fffb56d-27b0-4c54-b561-ac62f144aa61)

[trucks struggling to reach destination.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15195731/trucks.struggling.to.reach.destination.zip)

**Comment by CaptainMarek** [comment]
Thanks for the report, this was fixed in patch v0.6.3b.
