### ISSUE TITLE
Waste sorter plant malfunction

### ISSUE THREAD

**Issue by Pestulance1** [MaFi-Games/Captain-of-Industry-issues#1498]
### Issue description

I am trying to do recycling and i built a Waste sorter plant but it does not have any of the multiple output channels.
I have looked online and does not look like any of the ones i have seen.

### Reproduction steps

I did the research built it and there were no output channels.

### Game version and build number

v0.6.3a (b333)

### Operating system

Windows

### Attachments

![Waste Sorter Plant](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/168820864/edd81473-d7d8-45a2-bf4b-b96cda23119f)

**Comment by poltime** [comment]
It has only 1 output.  You need to build U-shape sorters.

**Comment by MaFi-Games** [comment]
As @poltime mentioned, you need the U-shaped sorter.

**Comment by Pestulance1** [comment]
Thanks for the response, yeah i figured it out but thanks anyway
