### ISSUE TITLE
AVG is blocking the game 

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#15]
**Describe the issue**
The antivirus protection AVG is blocking the game from beeing download compley. After making a exception for it (whiteliste the game) it will work again. 

**To Reproduce**
1. Download AVG.exe (https://www.avg.com) 
2. Install AVG and than try to download COI from steam
3. The download will have still 1 missing file and wont download that because AVG will put that in quarantine.

**Additional context**
 - [0.2.5]

**Comment by MaFi-Games** [comment]
Do you know what file is missing? I am not sure what to do here in general. Does AVG have some way of reporting non-malicious files?

**Comment by McRib33** [comment]
There was missing several files however AVG put only one file in quaranty that was the .exe file. It called a heuristics routine. Old way a anti-virus protection is working looking for very specialy files that the programm as "learned" to reconize. However the heuristics way is to give a tool to a virus protection to detected unknown virus that it doesnt are in there database. 

Here is a link to the website you need to send the .exe files to (i dont think there need more) they will check and make correction to there software to correct the issue. https://www.avg.com/de-de/false-positive-file-form unfortunaly that is in german you need to go over the main website if you want it in english (it detected that im form german)

**Comment by MaFi-Games** [comment]
Thanks! We have filed a report to AVG.
![image](https://user-images.githubusercontent.com/90082857/135889448-5891c107-e52e-4c10-bcfa-473687ee7d20.png)
