### ISSUE TITLE
Trucks: unlogical path finding

### ISSUE THREAD

**Issue by Bluescht** [MaFi-Games/Captain-of-Industry-issues#1500]
### Issue description

The trucks got the task to empty a big storage of limestone at once. They aren't driving the direct way. Look at the picture.

### Reproduction steps

I have no idea

### Game version and build number

v0.6.3a b333

### Operating system

Windows

### Attachments

[Truck bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15204487/Truck.bug.zip)

**Comment by CaptainMarek** [comment]
Thanks for the report, this have been fixed in v0.6.4a (currently in the experimental branch).
