### ISSUE TITLE
Vehicles in the "idle / no job" status consume fuel and maintenance

### ISSUE THREAD

**Issue by poltime** [MaFi-Games/Captain-of-Industry-issues#1502]
### Issue description

IMHO, it's wrong. When vehicles are not moving, they should not consume anything.

### Reproduction steps

Not required.

### Game version and build number

0.6.3 b332

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Maintenance is always consumed, but when vehicles are idle, they consume much less. Just like in reality, leaving a car parked somewhere for a year doesn't mean it won't need an oil change. Fuel consumption depends on what the vehicle does. If it has no jobs it does not consume fuel. There are some jobs that consume small portion of fuel when being idle and some jobs don't consume at all when idle, depends on the context. If you have a repro save file where fuel is consumed for a standing vehicle with no jobs ,please feel free to file a new issue and attach a save file and we will take a look.
