### ISSUE TITLE
Plastic missing from the Recipes [F1] screen. 

### ISSUE THREAD

**Issue by codeg8** [MaFi-Games/Captain-of-Industry-issues#1505]
### Issue description

The recipes for Plastic are missing  in the  Recipes [F1] screen.

### Reproduction steps

1. Open Recipes [F1] screen. 
2.  Search for Plastic. 
3. No  results shown.

### Game version and build number

Update 2 | v0.6.3a (b333)

### Operating system

Windows

**Comment by MaFi-Games** [comment]
I can see plastic on my side. Did you unlock it in research? If yes, please attach a save file so I can take a look.
