### ISSUE TITLE
Landfill  Pollution should reduce  if  landfills  are managed  properly. 

### ISSUE THREAD

**Issue by codeg8** [MaFi-Games/Captain-of-Industry-issues#1507]
### Issue description

This  is not exactly  a bug, but i think  the  game  should award you with better numbers for landfill pollution management for  the extra effort .

I  did not  like the look  of landfills  that  appeared after waste was dumped in an  area, so  i came up with this  trick to  make  my  island  look  more  aesthetically pleasing  to look  at.  

First  i  assign  a  dumping  zone  with one level down  from the  shoreline, to  dump  all  my  trash  into the ocean,  while simultaneously expanding  the  size  of the island.  For E.g.. If the  shoreline is  at  level  3 from  the ocean,  my  initial dumping zone  is  set  to  dump  till level  2.  

Once the landfill is dumped with all  allowed dump materials (usually, Rock, Waste,  Slag & Dirt) I  build a Mine  control  tower  near  the  dump area and  set the mine  location to cover the extended part of island and set the filter on mine  control  tower to only dump Dirt which  overrides the default global  filter.  Then i  increase the  dump  level on  the extended part of island by 1 to  meet  the shoreline  level  (in this case to 3)

Using this trick the trucks will  Dump a layer  of dirt over the landfill the look of the island improves as after some time grass grows back on the dirt making the expanded part of island look aesthetically pleasing.

Ideally this should also in some ways improve  the Numbers for the  landfill pollution  as the landfill is  now covered with a  layer of Dirt and is  no  longer  exposed.   But that does not happen. 

### Reproduction steps

1. Assign  a  dumping  zone  with one level down  from the  shoreline, to  dump  all trash  into the ocean.  For E.g.. If the  shoreline is  at  level  3 from  the ocean,  Initial dumping zone  should  be set  to  dump  till level  2.  Allowed dump materials  can be default (usually, Rock, Waste,  Slag & Dirt) 

2.   Once the landfill is dumped till level 2,  Build a Mine  control  tower  near  the  dump area and  set the mine  location to cover the extended part of island. 

3. Set the filter on mine  control  tower to only dump Dirt which  overrides the default global  filter to default  materials.

4.  Increase the  dump  level on  the extended part of island under mine control tower  area  by 1 to  meet  the shoreline  level  (in this case to 3)

5. The trucks will cover the  ugly looking  dump yard with Dirt which  makes the island look more beautiful. 

6.  Managing dump  this way should have a positive  effect on the landfill pollution, i.e  Landfill  pollution should only apply to areas where  we have an exposed landfill. 

### Game version and build number

Update 2 | v0.6.3a (b333)

### Operating system

Windows

### Attachments

![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7126178/3e616c1c-a910-4cbd-ada1-876d9d5785ab)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7126178/e5ff3ae2-31c2-4b3a-9315-812c0b8d945e)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/7126178/79893dd3-0cfe-4d64-ae5b-6987b1b25b7e)

**Comment by MaFi-Games** [comment]
We already do this. Landfill does not emit pollution when covered by another layer. It might be that you have a large part of it under the water, which still emits pollution.

**Comment by MaFi-Games** [comment]
Closing as WAI. If you have a repro where you think this does not work as mentioned, please file a bug with a save file attached. Thanks!
