### ISSUE TITLE
PIPE BUG？（Have been solved）

### ISSUE THREAD

**Issue by Arctan2Alpha** [MaFi-Games/Captain-of-Industry-issues#1508]
### Issue description

After connecting the pipe to the existing pipeline (or storage tank), the newly built pipeline still displays NOT CONNECTED and will not pass through gases and liquids。
![PIPE BUGS](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/168965506/458f4c3d-2f64-4274-8876-72078b5b0c70)

### Reproduction steps

1.  Establish a new groundwater pump.  
2.  Establish storage tanks.  
3.  Connect the pipe to the storage tank, ensuring the pipeline can pass water normally. 
 4.  Once the storage tank is filled with water, connect a water outlet pipe from the tank, but the water pipe displays "NOT CONNECTED" and cannot pass water.  
5.  Connect another water pipe from the one that can pass water, and the newly established water pipe also cannot pass water.

### Game version and build number

v0.6.3a（b333）

### Operating system

Windows

**Comment by poltime** [comment]
The other end of the pipe is not connected.

**Comment by Arctan2Alpha** [comment]
> The other end of the pipe is not connected.

Thank you for your reply. I initially assumed that the pipeline in the game would be like FACTRIO, capable of holding liquid even when one end is not connected.
