### ISSUE TITLE
Conveyor defect

### ISSUE THREAD

**Issue by sorbid79** [MaFi-Games/Captain-of-Industry-issues#151]
![20220325213523_1](https://user-images.githubusercontent.com/37190070/160198202-de3e9f41-a403-4328-821a-ae98e9ebc113.jpg)
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**
Something should actually be conveyed, but the conveyor belt remains empty. 
Allegedly not connected.

**Additional context**
 - Game version: BETA 0.3.11F

**Attachments**
[neu.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8353767/neu.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report but conveyor will not start moving when it is not connected to anything. Once you connect the other end it will start so this works as intended. Perhaps we can do better job explaining this in the UI.

If you have further issues feel free to re-open this issue.
