### ISSUE TITLE
bug du jeu

### ISSUE THREAD

**Issue by Kira2728** [MaFi-Games/Captain-of-Industry-issues#1511]
### Issue description

Le jeu ne fonctionne plus correctement pourtant hier, lorsque je l'ai acheté, il n'y avait aucun problème. Le jeu est tellement lent qu'il est impossible de jouer et très long à fermer ou sélectionner des options.

### Reproduction steps

1. J'ai redémarré mon ordinateur, mais rien
2. J'ai vérifié les paramètres et tout était bon
3. J'ai vérifié l'intégralité des fichiers 

### Game version and build number

v0.6.3a b333

### Operating system

Windows

**Comment by MaFi-Games** [comment]
Can you please share your logs and save file? By default the game should not be really slow to become impossible to play.

**Comment by poltime** [comment]
Voir dans le gestionnaire des tâches quel processus charge le processeur.

**Comment by Kira2728** [comment]
<img width="456" alt="Capture d’écran 2024-05-08 100106" src="https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/169205227/34360b1e-987f-4d7f-94ae-7aedf19ae26b">


> Can you please share your logs and save file? By default the game should not be really slow to become impossible to play.

- Je ne sais pas si c'est que vous voulez. Sinon, je ne comprends pas la demande.


> Voir dans le gestionnaire des tâches quel processus charge le processeur.

- ID du processus : 7128

**Comment by MaFi-Games** [comment]
We need log files from %USERPROFILE%/AppData/Roaming/Captain of Industry/Logs in zip file.

**Comment by Kira2728** [comment]
Je n'arrive pas à le trouver. J'ai vérifié plusieurs fois dans **steamapps** et je ne trouve rien dans la section du jeu.  De plus, j'ai cherché les éléments que vous avez marqué un par un dans la barre de recherche sans résultat.

**Comment by poltime** [comment]
https://youtu.be/pACz0dZzmok?si=CEJzaFJPYVkMJvCY

https://youtu.be/SLvHzL12028?si=AKYgpkbdd66YC6lx
