### ISSUE TITLE
Spent Nuclear fuel can't be shipped by trucks. 

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#152]
Origin station:
![image](https://user-images.githubusercontent.com/65734844/160750830-2e01ada9-985c-4a4f-86f8-9bc583bdec00.png)

Destination station:
![image](https://user-images.githubusercontent.com/65734844/160750869-c1abba8f-00e1-4265-ab2b-67b41a2ed9c1.png)

They are on opposite sides of the map, the route is traversable. 

![image](https://user-images.githubusercontent.com/65734844/160750969-f068be80-e791-4bf5-b020-cdc1eb2290dd.png)

Even manually assigning a truck to the route produces no results. It just sits there.

![image](https://user-images.githubusercontent.com/65734844/160751191-4240dc22-7a17-439d-8484-961ccda6d1e0.png)

Save file (no mods):
[Nuke Waste Not moving.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8376995/Nuke.Waste.Not.moving.zip)

**Comment by zuff-coi** [comment]
I believe this issue no longer exist and I'm closing it for now. This save file is corrupted as well so I cannot test this exact scenario.

If you run into this issue again, please let us know.
