### ISSUE TITLE
Construction jobs requiring construction parts are no longer being assigned

### ISSUE THREAD

**Issue by underseeg** [MaFi-Games/Captain-of-Industry-issues#1520]
### Issue description

Construction jobs requiring Construction Parts or Construction Parts II are no longer being assigned to trucks.

There are idle trucks and many construction parts available in storage.

Other parts are delivered in a timely manner (e.g. wood for a rainwater catcher or rubber for a belt). Only the construction part jobs have stopped working.

### Reproduction steps

1. Load attached save
2. Observe the four un-paused construction jobs are not being processed by idle trucks
3. Place new jobs for e.g. conveyor belts
4. Observe that other resource types are delivered, but not construction parts

### Game version and build number

v0.6.3b b334

### Operating system

Windows

### Attachments

[Save 2024-05-12, 12-54-31.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15286235/Save.2024-05-12.12-54-31.zip)

**Comment by poltime** [comment]
![git1](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157929411/ea4ea08e-a936-445e-be1d-0d6659ef4b04)

![git2](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157929411/83bb379c-79af-4070-9ad5-03d56f2e7277)

**Comment by underseeg** [comment]
Oh 😳 I'm so sorry. I really thought I reviewed everything before posting.

**Comment by underseeg** [comment]
And thank you for an amazing game ❤️
