### ISSUE TITLE
Game regularly crashes

### ISSUE THREAD

**Issue by tinnvec** [MaFi-Games/Captain-of-Industry-issues#1521]
### Issue description

Playing the game as normal, it will always crash after some time (less than 2 hours).

### Reproduction steps

No specific reproduction steps, the crashes seem to happen randomly.

### Game version and build number

0.6.3b b334

### Operating system

Windows

### Attachments

[coi-crash.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15286900/coi-crash.zip)

**Comment by MaFi-Games** [comment]
The crash is coming from nvwgf2umx.dl this can be driver or hardware issue. I would double check your nvidia drivers, try to clean reinstall them to the latest one. Also it would be interesting to see if it happens for others games as well.

**Comment by tinnvec** [comment]
I actually did a clean reinstall of the latest nvidia drivers for my card as part of troubleshooting before submitting this bug report. I haven't experienced this in any other games or applications though. I did a bit of googling and reading about the `Attempt to access invalid address` errors I saw in the crash logs and there were mentions of issues with Win10 installation that they needed to repair, so maybe that's next for me.

I tend to agree that it's probably not COI causing the crashes exactly but it seems to be the only thing I'm running that makes the issue visible.

**Comment by tinnvec** [comment]
I think this can be closed. I went over my system settings again and found that my GPU fan speed profile had been reset so the fans were not doing their job when they should. Fixing that has gotten the game to run without crashing (I will note that COI seems to heat up my GPU more than any other game even though it only uses 40% of my 3080Ti)
