### ISSUE TITLE
Trucks won't deliver to ore sorter if output is full, even when input is not

### ISSUE THREAD

**Issue by Darkomage** [MaFi-Games/Captain-of-Industry-issues#1523]
### Issue description

When using ore sorters on a mining site, with output connected to loose storage, my trucks won't deliver their mixed load to the sorter when one of the output is full. Even if there's lot of space in the sorter input. The sorter appears as "partially stuck", but does not accept cargo anymore.

In this savefile, at my copper mine, the copper output is full, and the loose storage connected to it is full.
Ore sorter input is only 5% full, but the truck seen on the right is stuck with it's mixed cargo of copper ore and stones.
I think the trucks should continue to dump their mixed cargo in the input tray until it's full. Or maybe it's not how it's intended to work.

![Capture d’écran 2024-05-14 090423](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/24569144/e1b4795c-f071-443c-bc3f-3056e65810e1)

### Reproduction steps

1- Load attached save
2- Have a look at the sorter on the right side of the map, near the copper mine
3- Have a look at the stuck truck

### Game version and build number

v0.6.3b b334

### Operating system

Windows

### Attachments

[Save 2024-05-14 - bug report.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15304123/Save.2024-05-14.-.bug.report.zip)

**Comment by Darkomage** [comment]
Edit: when I say I think the cargo should continue to be delivered to the input tray, it does not mean I think the sorter should continue to sort the "not full" goods. But the tray should continue to fill until full, or until the sorting can resume when the clogged output is freed.

**Comment by CaptainMarek** [comment]
Thanks for the report, this is working as intended, sorter has too much copper and stopped accepting all cargo with copper, to avoid clogging other resources that might be sorted there.

**Comment by Darkomage** [comment]
@CaptainMarek ok, that makes perfect sense

Thank you for your feedback ! Have a Nice Day.
