### ISSUE TITLE
Surfaces are not correctly build (swiss cheese)

### ISSUE THREAD

**Issue by gterminator** [MaFi-Games/Captain-of-Industry-issues#1536]
### Issue description

I setup to build a area for surfaces.
There are some tiles cancelt or not build at all. 
There is no "planning building that tile" anymore.

see screenshot:
![grafik](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/4986251/3ce14273-98cc-4693-ba72-95ce1cddc977)

### Reproduction steps

build some surfaces...

### Game version and build number

v0.6.4

### Operating system

Windows

**Comment by CaptainMarek** [comment]
Is it not possible to build them at all? If so, could you share a save of this state?

**Comment by gterminator** [comment]
@CaptainMarek I build them at all, but I dont know why sometimes I get some swiss cheese.

**Comment by kennyb** [comment]
this happened to me 3-4 times tonight and many times previously.
I click and drag a whole area (they all turn grey), then some time later, some tiles have just disappeared creating those holes.
I can redrag the surface (turning them grey again) and unity build them fine. (it's as if those swiss cheese holes just lost the surface designation).
it happens to me enough I can probably find a reproducible case soon.

**Comment by kennyb** [comment]
I figured out the bug: it happens on loading the game. my intuition is that it's an off-by-one bug, prolly with the array that contains the surface designations. here it is reproducible in 0.6.4c like this:

paint a large area with surface designations
![2024-06-07 10_12_20-Window](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/46397/891959fa-be83-4b88-91f6-0a580ae76f2d)

now, save the game ([upgrade ship 1.1.zip](https://github.com/user-attachments/files/15742373/upgrade.ship.1.1.zip)) and reload it
![2024-06-07 10_13_29-Window](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/46397/c9817438-7ab2-4ba8-a2de-2d31b810fd6a)

observe how the same exact save just seems to miss a few designations every once in a while?

**Comment by gterminator** [comment]
cheese DLC incoming.

**Comment by CaptainMarek** [comment]
Thanks for the report, this was fixed in v0.6.4d.
