### ISSUE TITLE
Haul Trucks not dumping into sorter

### ISSUE THREAD

**Issue by MaddTrker** [MaFi-Games/Captain-of-Industry-issues#1537]
### Issue description

I started upgrading my truck to the Haul trucl, and I have 3 of them that will not dump the mixed cargo into the sorter they are designated to dump to. I have the overload edict on and there is enough room in the sorter for them to dump their cargo, but ther error message say no valid destination. 

### Reproduction steps

I don't know how to recreate this issue.

### Game version and build number

V0.6.4 B337

### Operating system

Windows

### Attachments

![Screenshot (2)](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/166687303/ee3d2912-65b6-44c5-9e56-f94531c0f92b)
![Screenshot (3)](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/166687303/670a1be7-99bc-4362-bdb4-01ac2a631224)
[Armagedon 13 - Copy.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15367364/Armagedon.13.-.Copy.zip)

**Comment by poltime** [comment]
It's because they are loaded with pure ore and a check mark "reject single-product loads" is set in the sorter settings.

**Comment by MaddTrker** [comment]
While I didn't take screenshots of the what the trucks wre carrying, they had a dirt/stone mix. They had something like 227 stone and 7 dirt. Each of the haul trucks that were stuck and not moving had some kind of combination like this totaling the 234 max units. Either way I don't know what I did as I kept changing the setting and they started dumping again.
