### ISSUE TITLE
Game Crash, Reason unknown

### ISSUE THREAD

**Issue by FA-Locke** [MaFi-Games/Captain-of-Industry-issues#154]
While in the middle of playing, game froze for about 5 seconds, then entire computer froze for about 10. After that audio returned for about 5 seconds before Windows reported that the game was no responding, and the Unity Crash Handler showed up. Gave it perhaps ~1 full minute between 'wait for program to respond' commands before ending it. Crash handler did not report any progress until after the COI program was terminated, and then closed itself. 
PC was not under any significant load in any category, no changes in antivirus activity/behavior occurred, game, and particular save file had been running stable for about 6 hours. 
Unity Specific error code: Unity 2019.4.23f1_4e01f1a5ec
Couldnt find any error log file in the Captain of Industry file found the the steamapps/common file.

**Comment by FA-Locke** [comment]
Attached: Screenshot of error, and currently running background main programs, game log for the day.
[22-04-03_10-27-06_1389.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8405797/22-04-03_10-27-06_1389.log)
![crash](https://user-images.githubusercontent.com/102928118/161453291-f4ef0563-0873-430c-a09c-e5ebb3a370ce.PNG)

**Comment by MaFi-Games** [comment]
Unfortunately nothing in the logs + given this a beta issue we will have to close as we don't have enough information. However we also upgraded Unity version in the meantime so that might have helped as well.
