### ISSUE TITLE
Conveyors and pipes auto-place

### ISSUE THREAD

**Issue by poltime** [MaFi-Games/Captain-of-Industry-issues#1544]
### Issue description

It would be great if this option could be disabled in the settings, as it really gets in the way when you try to click on the balancer in a hard-to-reach place.

### Reproduction steps

.

### Game version and build number

v0.6.3b (b334)

### Operating system

Windows

**Comment by CaptainMarek** [comment]
You can disable snapping and port avoidance. You can also force straight-only segments. See the toolbar on the bottom-right for these functions.

**Comment by poltime** [comment]
I'm not talking about that. When you hover the mouse pointer over the port, a conveyor or pipe appears automatically.

**Comment by CaptainMarek** [comment]
That's true. If you are trying to click on a balancer that is occluded by port arrows, exit build mode to hide all arrows and then you will be able to click directly on the balancer.
