### ISSUE TITLE
Storage with previously canceled demolish task, will not accept belt input

### ISSUE THREAD

**Issue by TopKicker** [MaFi-Games/Captain-of-Industry-issues#1548]
### Issue description

Belts stop at the entrance of a storage that had previously deconstruct tasks canceled.

Attached is a save file where I just finished reproducing it with the second (southern) copper storage next to the copper electrolizer. Saved at the point where I am looking at the copper storage.

### Reproduction steps

1. Build a storage without anything hooked up to it. 
2. Choose to demolish it
3. Wait for the red box to cover it 
4. Cancel the demolish before any trucks can arrive. 
5. Try to hook a belt up to the storage entrance and transfer some items across the belt.

### Game version and build number

v0.6.4a b339

### Operating system

Windows

### Attachments

[El Capitan 2024.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/15443954/El.Capitan.2024.zip)

**Comment by poltime** [comment]
It's because of construction paused, click on the pause button.

![git](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/157929411/9bbbb71f-74f0-4634-ad3c-c4ab62a2d8e3)

**Comment by TopKicker** [comment]
Oh I see. The building looks completed but needs construction after cancelling a demolish task.
