### ISSUE TITLE
Inconsistent nuclear reactor UI

### ISSUE THREAD

**Issue by brucemcook** [MaFi-Games/Captain-of-Industry-issues#157]
**Describe the issue**
The UI for the nuclear reactor that pops ups when you hover on the building menu bar shows that 96 units of steam are produced in 20 seconds. However, the UI displayed when you click on the nuclear reactor itself shows 96 units of steam in 60 seconds.

***Expected behavior**
The two UIs should be consistent.

**Additional context**
 - Game version: beta 0.3.11.F

**Comment by zuff-coi** [comment]
This has been resolved as of v0.4.9
