### ISSUE TITLE
Command menu cant be open with german keyboard

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#158]
At the moment is impossible to open the command menu when using a german keyboard. The issue is related to fact that the ´ will be only trigger when the button is hit twice in a row or nothing will happend at all (but in COI it still dont work). My idea is that the command menu should be bind to a second shortcut to make sure german keyboard user can access it.

**Comment by MaFi-Games** [comment]
We have added key-bindings together with an option to rebind console so I hope this can be closed.
