### ISSUE TITLE
Can Copy before unlocking tool

### ISSUE THREAD

**Issue by outlawv** [MaFi-Games/Captain-of-Industry-issues#1597]
### Issue description

I'm brand new to the game (less than an hour played) so I might just be stupid, but I saw in one of the researches you can unlock the Copy Tool. But before researching it you can still press the hotkey for it (Ctrl + C) and it will allow you to copy things, which does work properly.

### Reproduction steps

1. Make new save
2. Press Ctrl + C and use the Copy Tool before researching it.
3. Profit.

### Game version and build number

v0.6.4c b341

### Operating system

Windows

**Comment by zuff-coi** [comment]
This is intended. We wanted to introduce new players to the tools through the tech tree but also not remove them from veteran players.
