### ISSUE TITLE
Slag doesnt get transported when trucks are busy

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#16]
Issue that is killing many plays here at the moment is that if a player start to build tier 2 fuel production there will build a lot of pipes connected buildings and so on. More than materials is in store. That will than cause a gridlock in the truck AI that kill the player in the long run. Since every time materials is at a warehouse/machines 1-2 trucks will try to grab that (even if it only 1-4 pieces) and run back to the construction side. They will still do there dailys routines but slag removal will fall behind because if the query is more than 50-100 sec they wont pick up slag anymore because of lack of time. After that the maintenance will fall apart and that make everything worse. I know working on a AI is a very very hard thing (and can go very bad if you just one small changes) but there need to be put a small change in place that slag removal should be as equal imported as food delivery and another thing on the daily task. To avoid this gridlocks. 

(This save game was product extra for this bug took me 4 hours to show the issue)

1. Load attached save '...'
2. Look at the furnances
3. Slag wont be pickup even after some time the trucks will focus on the construction 

**Expected behavior**
The entire eco will go down.

**Additional context**
 - Game version: [0.2.5]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files
[bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7231661/bug.zip)
.

**Comment by MaFi-Games** [comment]
Thanks for the report, this is issue with our logistics priority system and we will be improving it in Beta release.

Until then your best bet is to connect furnaces with a conveyor so that slag is transported to the storage. You can then set the storage to force-empty. You can even make more storages to help with buffering.

**Comment by MaFi-Games** [comment]
This has been hopefully fixed in upcoming beta release, thanks for reporting! If you encounter this again in the beta, please report it.
