### ISSUE TITLE
Phantom Construction Materials

### ISSUE THREAD

**Issue by BlankSavant** [MaFi-Games/Captain-of-Industry-issues#161]
I seem to be having more Construction Materials than i actually do. i have looked in all my storage facilities and they are all empty.

Version 4.0

![image](https://user-images.githubusercontent.com/106617083/171232572-9959ed05-95f0-4364-8683-2f2a2c64d5f7.png)

**Comment by Gnorok** [comment]
Statistics panel seems to be not correct (value is to high).
Value on the panel is 139, if I try to repair the shipyard the value is 95 (which is what I actually find in my storage).

![COI_1](https://user-images.githubusercontent.com/106625843/171271969-8866becd-d12d-4bcf-b4e3-3e306aa8f211.jpg)
l
