### ISSUE TITLE
Tree Harvesters drive backwards

### ISSUE THREAD

**Issue by Chevron9** [MaFi-Games/Captain-of-Industry-issues#162]
**Describe the issue**
Tree Harvesters drive backwards, as in the cabin and attachment are pointing in the wrong direction. This is odd, as the cabin faces backwards.

**To Reproduce**
Watch Tree Harvesters move to refuel

**Expected behavior**
The cabin and tree harvest thingy should point in the direction of travel.

**Additional context**
 - Game version: EA 0.4.0j

**Attachments**
https://i.imgur.com/aAxY8xx.jpeg

**Comment by MaFi-Games** [comment]
Thanks for the report! This has been fixed in patch v0.4.1.
