### ISSUE TITLE
Construction Parts III (red) - it is not produced without the use of cohesion

### ISSUE THREAD

**Issue by Pesty-x** [MaFi-Games/Captain-of-Industry-issues#1623]
### Issue description

It is not produced without the use of cohesion.
In Assembler II and Assembler III, the production of Construction Parts III will not start. I need to turn on cohesion for higher production.
Image 001 - Assembler II - not produced
Image 002 - Assembler III - not produced
Image 003 - Assembler II - Coherence On - Produced
Image 004 - Assembler III - Coherence On - Produced

Restarting the game didn't help
I don't know at what stage of the game production stopped working.

### Reproduction steps

I don't know when the production stopped working.

### Game version and build number

v0.6.4d (b343)

### Operating system

Windows

### Attachments

[CI-picture.zip](https://github.com/user-attachments/files/16408110/CI-picture.zip)
[CI-data.zip](https://github.com/user-attachments/files/16408111/CI-data.zip)

**Comment by poltime** [comment]
The reason is written there - there is not enough energy. Set the priority to "1" or build another generator.

**Comment by Pesty-x** [comment]
The problem is that when I turn on Assembler to use excess energy (yellow box), even though I have enough energy (red box). Asember is reporting low power. I probably don't understand the explanation, the use of excess energy (blue box). I would expect the Assebler to be disconnected from power in times of shortage to protect other production. If you can explain this to me.
Image 0005

Thank you in advance.

CZ
Problém z mého pohledu je, že když zapnu u Asembleru používat přebytečnou energii (žlutý box), ikdyž mám energie dost (red box). Asember hlásí nízký stav energie. Asi nedostatečně chápu vysvětlivku, použití přebytečné energie (modrý box). Očekával bych odpojení Asebleru od energie v době nedostatku, abych uchránil základní výrobu. Pokud mi toto můžete vysvětlit. 
Obrázek 0005 

Předem děkuji.

![CI-0005](https://github.com/user-attachments/assets/b01e29b0-c1f7-4211-aef8-2929bfc8ee9f)

**Comment by Pesty-x** [comment]
I already understood your intention. It doesn't seem completely logical to me that I have to mark the source (power plant) that is allowed to supply energy to the Assemblers marked in this way.
It would be better to compare from the overall available energy and switch off factories according to priority.

Consider the issue resolved.

CZ
Už jsem pochopil, váš záměr. Zcela logické mi to nepříjde, abych musel označit zdroj (elekrárny) které smí takto označeným Asemblerum dodávat energii. 
Lepší by bylo porovnávat z celkově dostupné energie a dle priority továrny vypínat.  

Problém berte za vyřešený
