### ISSUE TITLE
I find buildings only through search

### ISSUE THREAD

**Issue by StarCat75** [MaFi-Games/Captain-of-Industry-issues#1625]
### Issue description

Hi! Some buildings are not displayed when selecting a building. I find them only through searching.

### Reproduction steps

https://drive.google.com/file/d/11ict7zq-pSvHKgcq5QaEUO-hRB7wrI_i/view?usp=drive_link

### Game version and build number

v0.6.4d b343

### Operating system

Windows

### Attachments

<img width="960" alt="screen" src="https://github.com/user-attachments/assets/ba90a248-3374-4b5d-a8ad-b301b296534c">

**Comment by poltime** [comment]
Which buildings exactly?

**Comment by StarCat75** [comment]
All buildings are on the screenshot.

**Comment by poltime** [comment]
Do you see the icons at the bottom? Click on them. You have a section open for food.

**Comment by StarCat75** [comment]
I clicked on all the icons, but these buildings are nowhere to be found.

**Comment by StarCat75** [comment]
I deleted the game and reinstalled it. Everything worked. Thanks and good luck!
