### ISSUE TITLE
Changing Layer view unselects current build item

### ISSUE THREAD

**Issue by mnoreke** [MaFi-Games/Captain-of-Industry-issues#164]
**Describe the issue**
When placing for example a mine control tower, pressing L to see the layers unselects the mine control tower.

**To Reproduce**
1. Select mine control tower
2. Press L for layers
3. See your mine control tower placement option dissapear

**Expected behavior**
It would be nice if the tower (or other selected items) stayed and did not need to be reselected.

**Additional context**
 - Game version: 0.4 I think, EA release from steam

**Attachments**
None

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
