### ISSUE TITLE
Population overview missing tooltip on "unity"

### ISSUE THREAD

**Issue by LukasIgn** [MaFi-Games/Captain-of-Industry-issues#165]
**To Reproduce**
1. Start any game
2. Open population overview
3. No information tooltip about unity

**Expected behavior**
Display some information about unity, took me about 15-20mins to figure out what i can do with it, how it works.

**Additional context**
 - Game version: [0.4.0k]

**Attachments**
![image](https://user-images.githubusercontent.com/20187082/171280607-1572947e-311c-4cfe-98ab-36f6f04c9f61.png)

**Comment by mrpoppy** [comment]
Still present as of 0.4.6
Also missing from Health.

**Comment by kobihersh** [comment]
Still an issue in 0.4.9c

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
