### ISSUE TITLE
Framerate issues, due to spikes in cpu use

### ISSUE THREAD

**Issue by maxelden** [MaFi-Games/Captain-of-Industry-issues#1654]
### Issue description

I have been playing CoI for about 8 hours on this save, just past all the construction 2, about to begin construction 3 (not a big factory at all), until the game suddenly started showing issues with keeping steady frame rate, having really unstable fps, to the point it briefly freezes for less than a second often. When I look at what is causing the frame drops, is spikes in CPU use. The issues shouldn't be related to hardware, as the laptop I'm using meets recommended requirements easily. I'll add a picture showing the CPU usage showing the spikes. Although the GPU is also heavily used on the game settings I used in the screenshot, I found out it wasn't causing the instability, as on lower settings the game would still persist in having issues keeping stable fps. I also had more extreme spikes(and frame drops) than in the screenshot later on during testing.

![Screenshot (15)](https://github.com/user-attachments/assets/14724e9e-fff4-4f4e-b5f7-8b5e1114e44e)

### Reproduction steps

1. Load save 2. move around in game. 3. notice frame drops happen pretty much after a couple seconds

### Game version and build number

v0.6.4d b343

### Operating system

Windows

### Attachments

[CoI save file.zip](https://github.com/user-attachments/files/17445661/CoI.save.file.zip)

**Comment by poltime** [comment]
See in the "Processes" tab which process loads the processor.

**Comment by maxelden** [comment]
> See in the "Processes" tab which process loads the processor.

It is actually CoI that is causing the use

**Comment by maxelden** [comment]
I am playing again today and i notice that the frame issues do not persist. most likely happens due to long runtime of my device. Still concerns me that this is able to happen on newer gen cpus, and that there's such big spikes in cpu use
