### ISSUE TITLE
Pipes can be build trough trees

### ISSUE THREAD

**Issue by voske123** [MaFi-Games/Captain-of-Industry-issues#166]
I was able to blueprint and build a pipe trough a tree. 

Picture of the blueprinted pipe:
![image](https://user-images.githubusercontent.com/16508028/171285890-8bdc39d3-a150-4880-9668-f08081acf764.png)

Picture of the build pipe:
![image](https://user-images.githubusercontent.com/16508028/171285793-2b588514-b7b2-410e-829f-ec8a9a362d48.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, we are investigating this.

**Comment by MaFi-Games** [comment]
Just tried this on the latest version and couldn't reproduce it. This was probably fixed. Please file a new issue if it happens in the EA version.
