### ISSUE TITLE
Trucks randomly saying they can't find trees to harvest

### ISSUE THREAD

**Issue by zytukin** [MaFi-Games/Captain-of-Industry-issues#17]
**Describe the issue**
3 trucks assigned to harvest trees on higher ground, ramp was mined to allow access.  Trucks travel the ramp fine for a mine on the higher terrain but 1 or 2 of the trucks assigned to harvest trees will randomly pop up that they can't find any trees to harvest.

**To Reproduce**
1. Load attached save
2. Watch the alerts pop up in the upper right saying a truck or two can't find trees to harvest.  Can watch the truck itself and see it with the red alert icon over it and after a bit of time the alert will vanish and the truck will go to fetch wood.

**Expected behavior**

**Additional context**
 - Game version: 0.2.6a

**Attachments**
[Game 5.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7236910/Game.5.zip)

Truck with trees driving from the forest, yet another truck is causing a can't find any trees to harvest alert in the upper right.
![trees](https://user-images.githubusercontent.com/34819700/134925952-4db5bda3-3649-4a18-b972-5cf61921bcaf.jpg)
![trees2](https://user-images.githubusercontent.com/34819700/134926911-55b07733-4205-412e-a536-e14fa76adbd6.jpg)

**Comment by c0nnex** [comment]
See #8 that's the same issue i assume.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
