### ISSUE TITLE
Assembly (electric) II recipes show unlocked when they shouldn't

### ISSUE THREAD

**Issue by EstebanLB** [MaFi-Games/Captain-of-Industry-issues#170]
**Describe the issue**
Assembly (elecetric) II recipes for Vehicle Parts show unlocked on the recipes book when they shouldn't. I even see Assembly (electric) I recipes locked since I just started a new game.

**To Reproduce**
Start a new game, and check recipes for Vehicle Parts.

**Expected behavior**
The recipes should show as locked if the research has not been done yet.

**Additional context**
 - Game version:0.4.0

**Attachments**
![image](https://user-images.githubusercontent.com/5374226/171314588-ef6442bf-305b-4bd3-9e25-c82a8610207d.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
