### ISSUE TITLE
Ship access is blocked - caused by dumping assignment too close to shipyard

### ISSUE THREAD

**Issue by splunkhead** [MaFi-Games/Captain-of-Industry-issues#171]
**Describe the issue**
Getting a 'Ship access is blocked' error after putting a dumping assignment too close to the shipyard.
The assignment encroached into the area reserved for the ship to maneuver in and is now considered blocked.
![image](https://user-images.githubusercontent.com/106659238/171366573-056fd96f-27a9-433b-8a63-f6aa1cf7a338.png)

**To Reproduce**
1. Create a dumping assignment next to the shipyard into the ocean within the exclusion area for boat travel.
2. Eventually the area will be filled/reclaimed and ship access will be blocked.

**Expected behavior**
I assume that if there needs to be section of water that should not be filled in then it should not be possible to place a dumping assignment in the area.

**Additional context**
 - Game version: Early Access 0.4.0k

**Comment by MaFi-Games** [comment]
Thanks for the report, this is an issue, yes. We will see if we can add some mechanic to solve this.

**Comment by JamieRCHI** [comment]
For me, this was not an issue at the prow of the boat near the dock. The area was blocked as expected.

I did have this happen when placing fill on either side of the other small dock that is placeable though.

**Comment by DStrud** [comment]
Yeah I just dumped too close to the dock and cant seem to dig it back out the sea. Did I just loose my main ship? :(

**Comment by MaFi-Games** [comment]
We now provide a button to reclaim the area if neccesssary. So this should be fixed now.
