### ISSUE TITLE
Liquid Dump - Input not Rendering

### ISSUE THREAD

**Issue by Brad-Clarke** [MaFi-Games/Captain-of-Industry-issues#172]
**Describe the issue**
The Liquid Dump input is not rendering. The failure to render occurs even if a pipe is not connected. Screenshot attached below.

**To Reproduce**
1. Place Liquid Dump

**Expected behavior**
Input pipe is rendered.

**Additional context**
 - Game version: Early Access 0.4.0l

**Attachments**
![image](https://user-images.githubusercontent.com/36942566/171408660-1347667e-d015-47f9-ba32-8c74e22898e6.png)

**Comment by MaFi-Games** [comment]
Thanks for the report! This is now fixed and will be available in the next patch!
