### ISSUE TITLE
Pipe support for curving upward direction is facing the wrong way.

### ISSUE THREAD

**Issue by Robinhoodthefletchling** [MaFi-Games/Captain-of-Industry-issues#177]
![Pipe Support](https://user-images.githubusercontent.com/96559670/171521298-d49d59db-b3b4-4569-b2b3-b15cfa22f996.png)

**Comment by Robinhoodthefletchling** [comment]
Only happens in 2 direction
![Pipe Support2](https://user-images.githubusercontent.com/96559670/171521497-c19a9257-9d16-4e83-a7e6-de9fddb036c9.png)
s

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
