### ISSUE TITLE
Scrapping vehicle message spells scrapped as "scraped"

### ISSUE THREAD

**Issue by PrussiaV** [MaFi-Games/Captain-of-Industry-issues#178]
![42ccf6f2f0b1096522dd2c4ab9115d70](https://user-images.githubusercontent.com/106717723/171533237-d0090ef5-ed9e-4ffe-982e-309f00ceec87.png)

**Comment by MaFi-Games** [comment]
Thanks! This is now fixed and will be available in the next patch.
