### ISSUE TITLE
Building Dock off main part of island

### ISSUE THREAD

**Issue by RMH-7597** [MaFi-Games/Captain-of-Industry-issues#18]
Built a small pier off the main island and then went to build the dock for the cargo ships. This built OK but when I went to add the pumps for cargo they added OK but the dock or the ship did not update.

Removed and re-tried a few times with same rewsults. Flattened edge of main island and built dock there and all added OK.

**To Reproduce**
Dump rocks and gravel to build a pier from main island
Build Dock for cargo ships
Wait for cargo ship to dock
Upgrade dock with additional items for storage.

No pumps appear or cargo slots on cargo ship.

**Expected behavior**
Should have worked like it does on main island

**Additional context**
0.2.61a, see main menu]

**Attachments**
files.zip

Contains save and 2 screenshots, where it did not work and does work.

**Comment by MaFi-Games** [comment]
Hi, thanks for the report, did you forgot to attach the ZIP file? Could you re-attach it?

**Comment by RMH-7597** [comment]
[Files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7261969/Files.zip)
Added, not sure what happened last time

**Comment by MaFi-Games** [comment]
Thanks, the save was helpful, this is definitely a bug. This will need more thorough investigation.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
