### ISSUE TITLE
Farm Deletes too easily - Add confirmation window

### ISSUE THREAD

**Issue by JamesWalston** [MaFi-Games/Captain-of-Industry-issues#183]
The farm object deletes too easily and can be mistakenly deleted. Doing so can destroy months of food supply. A confirmation window would be helpful for this and other time-delayed objects.

**Comment by MaFi-Games** [comment]
lease file features ideas here: https://ideas.captain-of-industry.com/ We track bugs here or feature requests that are significant improvement in some major frustrating situations.
