### ISSUE TITLE
trucks loading issue

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#185]
when ever u delete a storage or want a storage to empty or even want stuff removed from dock by activating keep empty many trucks will come and will take 1,2,3 and so parts instead of filling the truck capacity
![image](https://user-images.githubusercontent.com/106634630/171775642-59635d1a-be0b-45e9-82c5-2610a975020a.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, would you have a save file where this happens? Was there more space in the destination where the vehicle pars were delivered?

**Comment by JamieRCHI** [comment]
I have seen this as well. Next time I see it happens, I will try to leave a save file.

It would be helpful for debugging purposes if we could decrease the Autosave interval time to 5 minutes or less. And also increase the number of autosave files to 10 or more.

**Comment by zuff-coi** [comment]
This should be resolved as v0.4.10
> Trucks will no longer transport small cargo loads during deconstruction projects (unless they are high priority).

If you have this issue still, please reopen the ticket and let us know!
