### ISSUE TITLE
Vehicle II unlocked well before Glass making, thus no Large vehicles. Should be reversed?

### ISSUE THREAD

**Issue by JamesWalston** [MaFi-Games/Captain-of-Industry-issues#187]
You can't make glass until much after unlocking "Large Vehicles." 

Vehicle Parts II requires glass. Thus you can't make Large Vehicles until much after unlocking them.

The order should be reconsidered.
![20220603012729_1](https://user-images.githubusercontent.com/106699635/171792709-6fbc3f80-b5cd-44e2-b856-10e108901b24.jpg)
![20220603012755_1](https://user-images.githubusercontent.com/106699635/171792711-00b9682e-6b02-4798-8c54-30c0fe39f875.jpg)
![20220603012746_1](https://user-images.githubusercontent.com/106699635/171792726-2ce8d43f-774b-4366-b49c-8052c2cf7c73.jpg)

**Comment by moffmaster** [comment]
You can _buy_ glass, though. So if you really want to you can afford a few heavy vehicles early. But I agree that it is a bit confusing/disappointing to research the tech and having to wait quite a long time until you can really use it.

**Comment by MaFi-Games** [comment]
We have added a note into the research node for large vehicles to explain that trade is needed.

**Comment by ZexMaxwell001** [comment]
I dont want to re open this issue. but I just want to give my feedback for this specific balance and design choice. here is a link to my stream where you can get my reaction when I learned how this process worked.

https://www.youtube.com/watch?v=G2Ub_0KJ62w&t=10290s
