### ISSUE TITLE
trucks wont refuel in nearest station and go for the far side of map to get refuel

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#188]
trucks wont refuel in nearest station and go for the far side of map to get refuel. also the trucks will stall and go and so o
[Report save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8830740/Report.save.zip)
n

**Comment by tradari** [comment]
This could be due to old route data still being left behind after moving a fuel station please see the image attached where i did this

https://i.imgur.com/CDVbMRs.jpeg

**Comment by knmh84** [comment]
thanks but i did not have routs assigned

**Comment by zuff-coi** [comment]
This issue has been resolved in experiemental branch v0.4.9c 
![image](https://user-images.githubusercontent.com/108291414/182312472-e5e0e85a-166e-40ab-b226-01bf5d5cb026.png)

**Comment by knmh84** [comment]
Thank you for your response
