### ISSUE TITLE
Disable hotkey for Tech tree until after the first research building.

### ISSUE THREAD

**Issue by voske123** [MaFi-Games/Captain-of-Industry-issues#189]
This is more a bad behaviour than a bug imo :)

**Describe the issue**
If you press the 'G' hotkey before putting down a research center you are able to see the tech tree.

**To Reproduce**
1. Start a new game
2. Pause the game
3. Press 'G' Hotkey

**Expected behavior**
Expecting the hotkey is disabled until the first research building is build. Seeing that the research button on the bottom bar only appears after putting a blueprint of the building down.

**Comment by JamieRCHI** [comment]
I want to see the tech tree at any time. I do not agree with this. Other games let you look at the research tree at any time. (Such as Factorio.) I would say that this is normal behaviour.

**Comment by voske123** [comment]
This is just at the initial start of the map, after placing the lab down then the button on the bottom of the map unlocks aswell. in other words its just for the initial 5 minutes or so.

**Comment by BainrowKiss** [comment]
I think it would be nice if a menu button would be highlighted when a new building or the menu itself is unlocked. If you press "buildings", the button is highlighted yellow. So for example; when unlocking mining, I think it would be helpful if the "buildings (for vehicles) is highlighted somehow, maybe with a yellow square around the the menu icon or just a small star in the corner. Same goes for the unlocked buildings, would be really helpful navigating the menu when there's a lot more unlocked.

**Comment by MaFi-Games** [comment]
This works as intended :)
