### ISSUE TITLE
Menus off screen

### ISSUE THREAD

**Issue by RMH-7597** [MaFi-Games/Captain-of-Industry-issues#19]
**Describe the issue**
Selecting buildings to open menus places them in random places. On some occasions these appear partially off screen. In most cases you can move them but these were too high. Closing and reopening placed them in the same place each time.

**To Reproduce**
It does not always happen but when it does closing and reopening the window places it in the same position.

**Expected behavior**
Ideally windows should open in the same area and be fully visable within the viewable screen

**Additional context**
0.26

**Attachments**
files.zip added
Contains
Save game
Screenshot
.
[Files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7239137/Files.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting. We need to put some work in better UI window positioning. Until then, you can also try lowering UI scale in settings in order to avoid off-screen windows.

**Comment by MaFi-Games** [comment]
We have made some UI positioning improvements in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
