### ISSUE TITLE
Food bug, settlements starving to death with access to food because a single settlement elsewhere doesn't have a market

### ISSUE THREAD

**Issue by OuchCrab** [MaFi-Games/Captain-of-Industry-issues#192]
[Food bug_.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8832157/Food.bug_.zip)

Is as title says.

I had a massive food problem, everyone was starving and i lost over 200 pop without being able to figure why, farms were working and markets were full of succulent vegetables, and yet my population was so in denial about greens that over half of them died.

Turns out, i had a single settlement somewhere that i was trying to bulldoze that didn't have a market attached to it, and this one settlement was causing people in well fed areas to starve to death.

Also i know theres issues with waste and all that, but thats because it took me so long to figure out the issue with the starvation and a lot of people died.

Thank you.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
