### ISSUE TITLE
Concrete Mixer upgrade to Concrete Mixer II costs 120 Constructions Parts III

### ISSUE THREAD

**Issue by laskiewicz** [MaFi-Games/Captain-of-Industry-issues#193]
**Describe the issue**
Concrete Mixer upgrade to Concrete Mixer II costs 120 Constructions Parts III

**To Reproduce**
1. Build Concrete Mixer
2. Try to upgrade to Concrete Mixer II

**Expected behavior**
It should cost less than full cost of Concrete Mixer II which is 40 Constructions Parts III

**Additional context**
 - Game version: 0.4.1b

**Attachments**
![image](https://user-images.githubusercontent.com/6371176/171883122-2c6881e4-ecf7-4b00-af5f-4d26e301c07a.png)

**Comment by MaFi-Games** [comment]
This was already fixed but won't work for any buildings that were built before the fix landed.
