### ISSUE TITLE
buildings or belts are not removed or constructed

### ISSUE THREAD

**Issue by mihaitasaratean** [MaFi-Games/Captain-of-Industry-issues#194]
**Describe the issue**
Building demolition or creation stuck

**To Reproduce**
1. Load attached save '...'
2. Look at the bottom right, where the kilns and the mixers are located
3. Observe the building behaviour (the ones that are demolished or built(currently a conveyor and 4 kilns)

**Expected behavior**
Buildings to be removed or built
**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
![2022-06-03 21_06_39-Captain of Industry](https://user-images.githubusercontent.com/19326966/171922547-18dbfcfd-1af8-4816-af75-fa05a1240407.jpg)
![2022-06-03 21_04_21-Captain of Industry](https://user-images.githubusercontent.com/19326966/171922557-38eb61c1-fd3a-44bd-8020-e4545c96e61f.jpg)
[save_22-06-03_21-06-49.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8834722/save_22-06-03_21-06-49.zip)

**Comment by mihaitasaratean** [comment]
I closed the game, let the computer sit for around 20 mins and now it's fixed. Voodoo

**Comment by MaFi-Games** [comment]
Thanks for the report! I believe this was fixed in v0.4.1c. You didn't report game version so I cannot tell whether this is regression or not. Feel free to re-open this issue if the problem persists.
