### ISSUE TITLE
Excavators consuming fuel when idle

### ISSUE THREAD

**Issue by moffmaster** [MaFi-Games/Captain-of-Industry-issues#197]
**Describe the issue**
Mining excavators (and tree harvesters) that are idle and waiting for trucks still consume fuel as if they were working.

**To Reproduce**
Assign an excavator to a task without assigning a truck, or too few trucks.

**Expected behavior**
No fuel usage, or a reduced fuel usage while idle.

**Additional context**
0.41b

**Comment by lowstrife** [comment]
I think this is intended behavior.

**Comment by JamieRCHI** [comment]
I think the fuel usage should go down while idle. I don't care if it is intended behavior or not.

**Comment by RavenDreamer** [comment]
For point of comparison, Pickups do not seem to consume fuel when idle (e.g. having no destination available to unload). I would expect both scenarios to be handled the same way. Currently, they differ.

**Comment by moffmaster** [comment]
Looks like this can be closed with the new update. Thanks!
