### ISSUE TITLE
Vehicle Depot does not automatically import materials when set to "auto"

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#198]
Vehicle Depot does not automatically import materials. The material(s) failing to be imported changes, sometimes it's one item, sometimes it's two. Strangely it's never vehicle parts. And sometimes the vehicle builds without issue. I think the only time that happens is because the depot has internal inventory of rubber\diesel from other vehicles I've scrapped.

![image](https://user-images.githubusercontent.com/65734844/171951747-9eec1301-4603-41e3-95c9-b504311c1cca.png)

I think the issue is, when truck importing is set to "auto", materials are *sometimes* not imported by the logistics system. If you manually force it to "on", the logistics system fixes itself and materials are imported instantly. 

I noticed this happening on the Level 2 and 3 depots, but I did not have issue with the Level 1 depot I started the game with. It was a long time ago, but I don't think the issue started until I started scrapping legacy trucks.

Fix: Either 

A) belt\pipe in materials
B) Set truck import mode from "auto" to "on"

Expected behavior: Auto should import materials if belts are not connected, like every other building, without requiring force "on". I think there is some buggy behavior concerning the internal storage of the depot and the relationship to "auto" importing. 

[Truck Depot.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8835716/Truck.Depot.zip)

[22-06-03_12-19-09_7926.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8835714/22-06-03_12-19-09_7926.log)

**Comment by MaFi-Games** [comment]
I believe we have fixes this some time ago. Please file a new issue if it still happens on newly built depots.
