### ISSUE TITLE
Rain sound pan left-right heavily affected by map rotation

### ISSUE THREAD

**Issue by Str3amR** [MaFi-Games/Captain-of-Industry-issues#2]
Originally reported by @Delvan#8976 but I have the same issue.

**Describe the issue**
The rain sound stereo image seems to be bound to the rotation of the game map, it starts a bit panned to the right but if you rotate the game map you hear the rain sound moving from left to right. Doesn't seems to be affected by the current position in the map, only it's rotation.

**To Reproduce**
1. Starts a new game
2. Wait until it rains
3. Rotate the map to hear that the rain sound shifts from completely from left to right following the rotation

**Expected behavior**
1. The rain sound not to be affected by the map rotation, or in a way that make sense.

**Additional context**
 - Game version: ALPHA 0.2.0

**Comment by MaFi-Games** [comment]
Good catch, the rain sound source needs to be positioned better.

**Comment by MaFi-Games** [comment]
This has been fixed in `v0.2.0c`.
