### ISSUE TITLE
Stuck Pickup Truck

### ISSUE THREAD

**Issue by RMH-7597** [MaFi-Games/Captain-of-Industry-issues#20]
**Describe the issue**
A pickup truck had 1 item onboad, it would not unload it to storage even though there was space and did not need repairs. 

**To Reproduce**
Not sure how it happened to start with as I noticed it was not doing anything, even though there was a backlog of activities to do.
I tried assigning a task to collect trees but that did not change anything. It stayed like this for some time, I watched for a few minutes with game speed set to maximum.

Eventually it seemed to clear itself but I did not notice when it happened.

**Expected behavior**
Pickups should unload unrequired items and carry on with tasks

**Additional context**
0.26

**Attachments**
files.zip added
Contains 
screenshot
Save game file
[Files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7239161/Files.zip)

**Comment by MaFi-Games** [comment]
I was not able to see the stuck truck in the save, but the description and screenshot was helpful. We might need to add functionality to force-clear trucks. I will keep this open until we have some solution.

**Comment by MaFi-Games** [comment]
We have added new functionality for recovering stuck trucks in the upcoming beta release, thanks for reporting.
