### ISSUE TITLE
Farm average produce UI is wrong when using "empty" crop periods

### ISSUE THREAD

**Issue by liq3** [MaFi-Games/Captain-of-Industry-issues#200]
The average crop production readout (bit right of the crop schedule) doesn't take into account "empty" rotations (which currently last 3 months). This means if you're using them, it displays a much higher number than you'll actually produce. 

For example, with potato, empty, veg, empty, it displays 5.4 potato and 5.6 veg / 60s. Based on actual results my vegetable output was closer to 3.6.

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
