### ISSUE TITLE
Menu frames uncapped

### ISSUE THREAD

**Issue by cz776za** [MaFi-Games/Captain-of-Industry-issues#201]
Menu FPS is uncapped, 

**To Reproduce**
1. Took off vsync and  unlimited FPS in settings

**Expected behavior**
I have a 3080 GPU, FPS was hovering over 1400, noticeable sound from GPU and PSU as the boost comes in. Remember this from a previous game launch.

**Additional context**
 - Game version: 0.4.1c
 - Love the game.

**Comment by MaFi-Games** [comment]
This looks like an intended behavior. If you don't specify v-sync and there is no FPS limit, the FPS will go as high as hardware allows. If you wish to limit FPS, use either V-Sync or specify FPS limit.
