### ISSUE TITLE
Tree Harvester stuck refueling while already full

### ISSUE THREAD

**Issue by Fehdaykin** [MaFi-Games/Captain-of-Industry-issues#202]
**Describe the issue**
My tree harvester is trying to refuel, while already full of fuel. Forever

**To Reproduce**
Load attached save '...'
Disabling the refuel stations will make it drive to other fuel sources, refill back up to 104%, but still try to refuel more.

**Expected behavior**
It should get back to work after it is refueled. I expect my fuel trucks to come to the tree harvester, instead of it driving to refuel itself.

**Additional context**
 - Game version: 0.4.1.c

**Attachments**
[save_22-06-04_10-50-38.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8837411/save_22-06-04_10-50-38.zip)

**Comment by Fehdaykin** [comment]
Scrapping the harvester and making a new one solves the issue

**Comment by Sjs06** [comment]
I also just ran into this issue with an excavator doing the exact same thing. Turning off all the fuel supplies (gas station/storage) fixed the issue for me. After turning all the buildings off, the excavator went back to mining.

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed in v0.4.1c
