### ISSUE TITLE
All fuel trucks trying to refuel full excavator

### ISSUE THREAD

**Issue by almightyju** [MaFi-Games/Captain-of-Industry-issues#203]
**Describe the issue**
I have 3 trucks assigned to a fuel station and they are all trying to refuel an excavator that has full fuel. They all keep looping between "Navigating", "Refuelling vehicle 'ExcavatorT1'" and "Preparing for navigation".

Other stuff runs out of fuel and I have to unassign the trucks and re assign for them to refuel the ones out of fuel but then they go straight back to this other excavator.

**To Reproduce**
1. Load attached save [bugged_.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8837494/bugged_.zip)
2. It should auto put you at the copper mine where you can see this happening 
![20220604113631_1](https://user-images.githubusercontent.com/7722347/171995523-12ed0568-1aa9-4281-9457-80df810739e4.jpg) and if you look to the left near the coal mine you will find the fuel station
![20220604113643_1](https://user-images.githubusercontent.com/7722347/171995535-b3b43917-88d5-4879-81e5-8347b1f5ebf0.jpg)
3. unassign the trucks from the fuel station and reassign them, watch as they all go back to the copper mine

**Expected behavior**
The trucks should not be going to refuel the full excavators

**Additional context**
 - Game version: 0.4.1c

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed in v0.4.1d
