### ISSUE TITLE
Total - / + health not showed correctly in the satistics menu

### ISSUE THREAD

**Issue by vevi33** [MaFi-Games/Captain-of-Industry-issues#205]
Total - / + health not showed correctly in the satistics menu.

The total - and + health effect amounts seems to be incorrect. (total amount 5; water pllution 7 air pollution 3 + disease. Thus it should be more than 5)
It's the same with total + health stats. So the sum of - and + health points are always lower than it supposed to be.
I reproduced it in more save files, this problem always present, therefore it wouldn't be helpful to upload any save file here.

Ggame Version: 0.4.1D
![kép](https://user-images.githubusercontent.com/106883955/172020163-fccdf954-d9c2-4aac-ac0c-900199968cb9.png)
![kép](https://user-images.githubusercontent.com/106883955/172020350-37289506-83a4-45da-a3dc-11b0d0ac4b87.png)

**Comment by vevi33** [comment]
Another example:


![kép](https://user-images.githubusercontent.com/106883955/172067501-48500bde-9b96-4471-809f-6c939af8ea60.png)


![COI3](https://user-images.githubusercontent.com/106883955/172067505-46b63ac9-f2ac-4098-a4d9-4fea84947fce.png)

It looks like in both cases in the stats panel the sum of all - health points are =  the leading cause of the highest amount of - health modifier. 
So in this case:
**- total is  = - water pollution  (That's why both values are 8)**
While (- total) should be : (- water pollution) + (- air pollution) + (- disease)

And the same happens with + health modifiers as well.

**Comment by MaFi-Games** [comment]
Fixed in one of the last patches. However historical values will unfortunately remain broken. Thanks!
