### ISSUE TITLE
Save games not showing up anymore

### ISSUE THREAD

**Issue by FaroeNoob** [MaFi-Games/Captain-of-Industry-issues#206]
**Describe the issue**
I have been playing the game now for some 15 hours all on the same save game. Now that I launch the game again tonight I am not seeing any of my saves. Auto-Saves and Manual-Saves are all gone. I am only able to start a new game.

However, when I go into the files the save games are there.

**Expected behavior**
Explain what you expected to happen - ?

**To Reproduce**
1. I have no idea.

**Additional context**
 - Game version: 0.4.1D

**Comment by MaFi-Games** [comment]
Try ensuring that antivirus software is not blocking the game executable from accessing your files. Otherwise, please share logs so we can investigate.

**Comment by FaroeNoob** [comment]
Restarting steam fixed the issue! :)
