### ISSUE TITLE
Stuck Pickup

### ISSUE THREAD

**Issue by Boggett** [MaFi-Games/Captain-of-Industry-issues#21]
**Describe the issue**
I paused a pickup that was out of fuel (also had no fuel reserves on island) near a location i was dumping slag/gravel for a cargo port. When i built the cargo port the pickup became stuck within the building and i am now unable to click on the pickup.

-Haven't yet tried to replicate but it would be quite easy to do.

-I personally expected the pickup to automatically move out the way of the new building.

- Game version: 0.2.6a

**Attachments**
https://imgur.com/a/GEYi52D

**Comment by MaFi-Games** [comment]
This is strange, by any chance do you have a save file with this situation? We do have code in place that should prevent this from happening, but for some reason it did not work here.

**Comment by Boggett** [comment]
Good evening,

Yes i do still have a save file of this situation. It is currently my main save file and the truck is still sitting there stuck.

I am unable to click on the truck as the cargo port is the main thing selected every time.

Sam
________________________________

**Comment by MaFi-Games** [comment]
Could you please attach the save file here (you will need to zip it) or send it over to support@captain-of-industry.com? Thanks!

**Comment by Boggett** [comment]
I'm not exactly sure how to do that sorry.
________________________________

**Comment by MaFi-Games** [comment]
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
