### ISSUE TITLE
repeated interruptions of the game with freeze of the image and return without additional data to the PC desktop

### ISSUE THREAD

**Issue by Unseen74** [MaFi-Games/Captain-of-Industry-issues#210]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by zuff-coi** [comment]
Please provide some information so we can solve this issue. Thanks!

**Comment by MaFi-Games** [comment]
Closing as not enought information avaialble.
