### ISSUE TITLE
Captain of industry crashes after half hour off playing it 

### ISSUE THREAD

**Issue by Bickinator** [MaFi-Games/Captain-of-Industry-issues#212]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Please provide us with logs and save file so we can investigate.

**Comment by Bickinator** [comment]
Will do I will have to start again as I deleted it so will start one up
today and will send you it. Thank you for your response
