### ISSUE TITLE
Low Framerate \ Frametime

### ISSUE THREAD

**Issue by dcraig327** [MaFi-Games/Captain-of-Industry-issues#213]
**Describe the issue**
Low Framerate when zoomed out.

**Expected behavior**
Frametime under 16.67ms for over 90% of frames, preferably for over 99% of frames as would be benchmarked by reviewers

**To Reproduce**
1. Load attached save or Start a New Game (default map, default difficulty)
2. Fantastic settings, No Vsync, No Framerate cap, Borderless, 1080p
3. Zoom out all the way, move towards shipdock to gain a similar view
4. The framerate dips below 60 in some cases

**Additional context**
 - Game version: 0.4.1D
 - I imagine as a base grows the framerate would dip below 60fps more frequently, but just got the game and can't test that yet.
 - Love the game too much not to report this and don't want this issue to become unfixable months or years down the road as is the case with some other Unity games, some games being so bad that it results in noticeable jitter.
 - Unsure if LOD is being used, need to test, I think the trees might not be using LOD, and somehow after clearing them I got increased performance? 
 - The rotation + panning of the camera is one of the smoothest I've ever experienced in a RTS-style camera. Without affecting that, perhaps limiting the z-height of the camera to be dependent on the 99% polled frametime for the user to guarantee 16.67ms - then gauging if that needs tweaking by searching all forums for complaints including: "zoom out" or "zoomed in"?

**Attachments**
[Existing game save](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8839886/22-06-05_02-57-59_8002-autosave.zip)
[Logs of New Game occurring 1st, Existing Game 2nd](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8839893/Logs.zip)

SpecialK screenshots:
[NewGame Fantastic](https://user-images.githubusercontent.com/37514553/172050016-4d4d6a60-a8cb-45b6-9e6c-5e8f97b46385.jpg)
[NewGame Fast](https://user-images.githubusercontent.com/37514553/172050035-57139866-8c75-4ed6-9884-b125dea6982b.jpg)
[ExistingGame Fantastic](https://user-images.githubusercontent.com/37514553/172050050-501b8934-c2f7-476f-ba86-995f45e57bc8.jpg)
[ExistingGame Fast](https://user-images.githubusercontent.com/37514553/172050061-4774cc99-dc87-4ecd-9dbb-ea0e8496f41f.jpg)

**Comment by dcraig327** [comment]
I'm sorry. The logs didn't include my specs.
CPU: 3900x
Mobo: Asus ACE
Ram: 128GB ECC 3200
GPU: 2080 MSI Gaming X Trio 8GB
SSD: SN850
Monitor: LG 27GN750-B (240Hz 1080p)

**Comment by dcraig327** [comment]
Took some screens with Afterburner running, no Steam Overlay, Admin mode. The FPS is a bit higher than previous screens as the GPU is running on a stable o/c in Afterburner (o/c has been running 3 years with no issues). I did see the GPU spike to 99% a couple times, but running in Admin mode, as with most unity games, gives a small performance boost as seen in the last screen.

[Afterburner admin Fantastic New](https://user-images.githubusercontent.com/37514553/172070672-94ddbe8e-125a-4f18-93cb-1324e72fd42a.jpg)
[Afterburner admin Fast New](https://user-images.githubusercontent.com/37514553/172070691-bd5dc432-5760-417d-90b7-dfbcbd8d6577.jpg)
[Afterburner admin Fantastic Existing](https://user-images.githubusercontent.com/37514553/172070709-a8cdf4c7-5869-46b6-9c60-0dad001d0cd5.jpg)
[Afterburner admin Fast Existing](https://user-images.githubusercontent.com/37514553/172070739-d1e0f5ac-b248-4863-a43b-9e4bf289e98f.jpg)

[Afterburner non-admin Fast Existing](https://user-images.githubusercontent.com/37514553/172070925-cf248ca6-2863-4517-ab0d-8fb860d98abb.jpeg)

**Comment by JamieRCHI** [comment]
I am getting increased heating on my computer when zooming out. 
(Not sure how to set up MSI Afterburner to show the same results as above.)

See attached:
![MSI Afterburner zoomed in](https://user-images.githubusercontent.com/38770977/175782484-82610665-18d5-4180-b51f-d93e0c16f957.PNG)
![MSI Afterburner zoomed out](https://user-images.githubusercontent.com/38770977/175782493-4204d7fc-707b-4c6d-8617-5b1919893c81.PNG)

`Processor       AMD Ryzen 7 3800X 8-Core Processor, 3893 Mhz
                Overclocked to 4300 Mhz with Asus AI Suite 3
Total Memory    32 GB - 2132 Mhz
Motherboard     ROG CROSSHAIR VIII HERO
Video Card      NVIDIA GeForce RTX 2070 SUPER, 8 GB memory
Main Drive      1 TB M2 SSD
Game Drives     120 GB SATA SSD
                500 GB SATA SSD 
Video Display   60hz 4K LED Monitor (Am using 1080p mode)`

**Comment by MaFi-Games** [comment]
We have done several performance improvements and will be doing much more. But I'm going to close this one, as we track ongoing efforts separetely and this isn't a specific bug to act on, but more of a "make the game faster", which we will do :)
