### ISSUE TITLE
Inconsistent dialog closing.

### ISSUE THREAD

**Issue by SKMoss** [MaFi-Games/Captain-of-Industry-issues#215]
**Describe the issue**
Multiple window classes for pop up information have an inconsistent close method.

**Expected behavior**
ALL pop up should close with the ESC key.   The need to stop what I'm doing to click a dismiss button or hurray button is aggravating.

ESC key should first close any pop over be it modal or not.  Then it should open the save/close/quit menu.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by JamieRCHI** [comment]
Yes. I think all Dialogs should close with the Escape key.

**Comment by MaFi-Games** [comment]
We have been updating all our dialogs to act properly on ESC. The research and refugees dialogs will be fixed in the next patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
