### ISSUE TITLE
Ship repair problem

### ISSUE THREAD

**Issue by Cruyffie14** [MaFi-Games/Captain-of-Industry-issues#216]
I have like 300 steel in my storage And prio 1 for my ship But still they dont send the steel to my ship And all the other things are like prio 2 How is this possable. 

Maby also add Ports For the repair for the ship

**Comment by Tuvaka** [comment]
I am encountering the same problem.. my workaround has been removing it from the belts and then it gets put in the shipyard.

**Comment by MaFi-Games** [comment]
Thanks. We have fixed this issue in one of our previous patches.
