### ISSUE TITLE
Walls dont block dirt collapse

### ISSUE THREAD

**Issue by quasarea** [MaFi-Games/Captain-of-Industry-issues#218]
**Describe the issue**
Built a wall to prevent dirt collapse along the excavation edge - dirt collapsed anyway

**Expected behavior**
Wall to prevent this to happen

**Additional context**
 - Game version: 0.4.1D

![image](https://user-images.githubusercontent.com/10334982/172059780-26d3a61f-db67-4664-8f16-6482f793d8af.png)

![image](https://user-images.githubusercontent.com/10334982/172059802-c4216844-a8c4-4660-a6f4-c8c5b2210551.png)

**Comment by Erah101** [comment]
excavators actually dig through walls, the walls themselves work to prevent flowing

**Comment by MaFi-Games** [comment]
We made changes to prevent designations from being placed on top of retaining walls to avoids cases like this.
