### ISSUE TITLE
Ground over the pipes dissapears if you add a new connection to the pipe

### ISSUE THREAD

**Issue by Shivansps** [MaFi-Games/Captain-of-Industry-issues#219]
![20220604162135_1](https://user-images.githubusercontent.com/2444336/172060821-d71742c7-c46b-4336-97e8-008cf78e358c.jpg)
![20220604162158_1](https://user-images.githubusercontent.com/2444336/172060823-d1c8b427-2d87-45f0-b498-750903a9540a.jpg)
![20220605132242_1](https://user-images.githubusercontent.com/2444336/172060827-f0761baa-f6bb-4558-aa12-2018f2b2ed0a.jpg)
![20220605132313_1](https://user-images.githubusercontent.com/2444336/172060829-005216b0-5fe7-4882-9687-a40d217b3c09.jpg)

Either by digging, building the pipe and them cover it with dirt or just dropping trash/rocks/wharever over them to make a ramp so vehicles can get trought, the result is the same, adding a new pipe connection to that pipe deletes all the ground it has on top of it.

**Comment by MaFi-Games** [comment]
Thanks for the report, could you please attach a zipped save file that has this issue?

**Comment by Shivansps** [comment]
[ad.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8840528/ad.zip)

**Comment by ashoudy** [comment]
Can confirm this is happening to me as well, it happens regardless of depth or # of pipes.

**Comment by manganap** [comment]
I just tested and I can verify that the problem appears fixed with v0.4.1.e.  Thank you!

**Comment by Shivansps** [comment]
I can confirm this is now fixed so im closing it.
