### ISSUE TITLE
Excavator doesn't get refueled

### ISSUE THREAD

**Issue by mathijs55** [MaFi-Games/Captain-of-Industry-issues#22]
**Describe the issue**
Excavator doesn't get refueled

**To Reproduce**
1. Load attached save 'sand excavator no refuel.save'
2. Check the sand mine, 2 excavators are waiting to be refueled, refuel trucks nearby but don't do anything
3. Strange thing happens '...'

**Expected behavior**
Excavators being refueled by refuel trucks

**Additional context**
 - Game version: 0.2.6a

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Docu
[sand excavator no refuel.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7245253/sand.excavator.no.refuel.zip)
ments (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
