### ISSUE TITLE
cant start a new game

### ISSUE THREAD

**Issue by Nelis61** [MaFi-Games/Captain-of-Industry-issues#220]
**Describe the issue**
A clear and concise description of what the issue goes here.
Just got an error report when i want to start a new game (we are really sorry but the game failed to initialize.
My safe games are not there.
**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Can you please share your logs?

**Comment by MaFi-Games** [comment]
Closing as not enough information provided.
