### ISSUE TITLE
Trucks dumping product where they shouldn't 

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#221]
Trucks are dumping material into storage which has been assigned by other mining towers.

The highlighted truck is assigned to a different mining tower, but it's dumping it's material into this anyway? 

![image](https://user-images.githubusercontent.com/65734844/172064922-20dd1ff9-4493-4d12-ac68-924d5968cd7b.png)

As we can see here, this truck & it's respective mining tower is not assigned to that loose storage.

![image](https://user-images.githubusercontent.com/65734844/172065071-e15024c6-8f9d-481b-8e9a-274305f3e059.png)

This sucks because I use these to keep my ore mines operating smoothly, but my general earthmoving equipment is dumping enormous amounts of rock into these overflows into my general logistics capacity and overwhelms it. The general earthmovers should make the trip to the ocean themselves, and should not dump their material into these controlled silo's. The only option is to disable these silo's entirely which makes my ore mining less efficient. 

Hope this explanation makes sense. 

[Dump Truck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8840518/Dump.Truck.zip)

**Comment by lowstrife** [comment]
I forgot I made an issue for this already. I'll depreciate the old issue and move that info here:

Trucks carrying rock from this mine:
![image](https://user-images.githubusercontent.com/65734844/173923263-16424a01-9ab7-451c-87c7-545b491b2522.png)


Are dumping their contents in this storage which has been manually assigned to a different mine:
![image](https://user-images.githubusercontent.com/65734844/173923181-0a180345-0060-4705-98f3-5ce653e4a2fc.png)

Instead of dumping their contents into the ocean. 

The language of assigned routes, to me, sounds like it's talking about storage <--> storage, rather than mine --> storage. 

![image](https://user-images.githubusercontent.com/65734844/173923501-17492ffa-ba30-4f77-854d-9f4e950004eb.png)

In this example, I would expect that the loose storages would only accept any rock\dirt from the mines of which they are assigned to. Any other rock\dirt from any other mine should be dumped into the ocean (yes there are available dumping areas). 

I use this system because the mines are extremely long distance away from the dumping grounds. And I don't want mining trucks carrying 6 rock or dirt to travel all that distance. So I use these storages as buffers so that a truck can always make the long-distance journey with a full load.

Files:
[Overflow.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8912949/Overflow.zip)
[22-06-14_07-35-24_1383.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8912950/22-06-14_07-35-24_1383.log)

**Comment by lowstrife** [comment]
And this actually spills over into destination routing as well.

This mine should only ever deliver to it's assigned route. Nothing else. Just go and dump it all here, or queue up and wait at the tower.
![image](https://user-images.githubusercontent.com/65734844/173935023-162155c4-8aea-41c6-9556-d7cdfd531d1d.png)



But it doesn't. These trucks refuse to dump it in the clearly empty and demanding limestone loose storage, but instead want to dump it into inaccessible limestone storage yards. WHY? 

![image](https://user-images.githubusercontent.com/65734844/173934614-6e1f5145-ee47-42e2-9a58-dabb5224b693.png)

Force-recovering the trucks with unity doesn't work either. They just reset completely and still continue trying to dump their cargo at the inaccessible loose storage. 

The only thing that allowed them to even visit this site (which has worked for hours previously) was by force-demanding limestone to this storage yard, with #1 priority. Then the trucks dropped their loads off.

![Uploading image.png…]()

Assigned routes have a lot of issues. Trucks refuse to obey the rules I try and program.

**Comment by MaFi-Games** [comment]
Thanks a lot for your detailed reports. These are really helpful. Just tried your save files and I believe we have ironed out these issues already but just forgot to close this ticket. If any issue still persists in the latest version please file a bug with a save file and we will take a look. Thanks a lot!
