### ISSUE TITLE
Gas Injection Pump - Not placeable

### ISSUE THREAD

**Issue by Stalkie** [MaFi-Games/Captain-of-Industry-issues#223]
**Describe the issue**
Gas Injection Pump gives placement error "There is no deposit of limestone" even on deposits.

**Expected behavior**
Beeing able to place the pump on a flat terrain on top of limestone.
I was able to place one on a remote location on another "mountain" of limestone. But not on the "main" deposit.
Does it need a certain depth of limestone to work?

**To Reproduce**
1. Load attached save 'InjectionPump'
2. Try place it on the "man made" limestone platform next to the power plant.
3. Shows red even on the deposit

![bild](https://user-images.githubusercontent.com/26777760/172066552-e4581bf1-073a-4a18-b4b2-6221cb829675.png)

**Additional context**
 - Game version: 0.4.1e

**Attachments**

[InjectionPump.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8840584/InjectionPump.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report. It needs much deeper limestone deposit. We will improve the error message to contain this important info.

**Comment by MaFi-Games** [comment]
The error message has been improved.
