### ISSUE TITLE
Trucks Refusing to Deliver

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#224]
**Describe the issue**
I have plenty of resources, plenty of idle trucks, yet nothing is being built. I can build with Unity, but that's for emergencies. It feels like ever since I used unity to quick build, the trucks have refused to deliver any construction materials.

**Expected behavior**
I expect the trucks to deliver whenever the materials are present.

**To Reproduce**
1. Load attached save.
2. Let game run for 5-10m. Observe several ghost buildings not being constructed; observe the farm not being upgraded to Irrigated farm, despite there being plenty of idle trucks and plenty of resources in warehouses. All unit storage warehouses with Construction Parts are set to 'On/On' for the trucks.

**Additional context**
 - Game version: 0.4.1d

**Attachments**
[trucksNotDelivering.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8840600/trucksNotDelivering.zip)

**Comment by EradicationGod** [comment]
Same issue here in two different and new savegames... It's getting to a point where it makes it so annoying that it is unplayable.

**Comment by utdrmac** [comment]
I discovered my issue with this. I had several warehouses set to 'Keep 90', which means trucks won't take from there if there are less than 90 units. As soon as I removed this restriction, the trucks started delivering again.

**Comment by EradicationGod** [comment]
This is not the case for me. I have no limits on my warehouses. The trucks have all the resources and still don't wanna deliver.
