### ISSUE TITLE
Big trucks get stuck on non-pathable resource when pathable options available.

### ISSUE THREAD

**Issue by altmank** [MaFi-Games/Captain-of-Industry-issues#228]
Big trucks will often get themselves stuck while pursuing a resource without a path when there are alternatives they can path to instead. For example, this truck is trying to get Diesel, but its available from a big truck friendly path somewhere nearby instead. The default behavior should not be to just stop working and complain. 
![image](https://user-images.githubusercontent.com/22986384/172085083-4a625afa-727a-42c3-a903-08878b10ad1a.png)

**Comment by zuff-coi** [comment]
Is this still happening in v0.4.10? If so, could you provide a save in which it is happening? Thanks!

**Comment by MaFi-Games** [comment]
Closing as we don't have enough information available to investigate.
