### ISSUE TITLE
Trucks Try to Refuel Cargo Dock

### ISSUE THREAD

**Issue by CaptainLame** [MaFi-Games/Captain-of-Industry-issues#23]
**Describe the issue**
I have two cargo docks that are attached to a fuel supply. The pipe is full of fuel and when the ship docks, it refuels immediately from the pipeline. However, one or more trucks will load fuel and attempt to deliver it to the dock, even though the ship and the dock are fully fueled. There are no controls on the cargo dock like other storages to control truck delivery. This is specifically the cargo ship dock. I have not observed this happening to the main ship dock.

**To Reproduce**
1. Have a cargo dock piped to a stable fuel supply
2. Wait for ship to get a call and return
3. Observe if some idle trucks suddenly attempt to fuel it

**Expected behavior**
If dock has fuel flowing into it from a pipeline, it should not also generate a call for truck-based fueling.

**Additional context**
 - Game version: 0.2.6a

**Comment by MaFi-Games** [comment]
This is a good point. We will need to add some controls so that this is preventable. Thanks for reporting.

**Comment by CaptainLame** [comment]
A detail I recalled due to starting a new game: I had the cargo dock diesel set to "Keep full" so I'm guessing even though the pipe will fill it quite quickly, in the interval it generates a fueling call, just like any storage that allows truck imports if a belt isn't keeping it full 100% of the time.

**Comment by MaFi-Games** [comment]
This has been fixed in v0.2.9.
