### ISSUE TITLE
Zooming in or out closes windows in the mapview

### ISSUE THREAD

**Issue by voske123** [MaFi-Games/Captain-of-Industry-issues#230]
**Describe the issue**
When in the mapview and a settlement open, zooming in or out closes the settlement tab

**Expected behavior**
Just zooming in or out, not closing the windows.

**To Reproduce**
1. Open mapview
2. Open a settlement
3. On zooming in or out the window for the settlement closes

**Comment by MaFi-Games** [comment]
Thanks but that works as intended.
