### ISSUE TITLE
Mining towers over-riding assigned routing

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#234]
On year 728, I just randomly realized my shipyard was filling up with... ore? Holy shit - that's a lot of ore. It wasn't like this an hour ago, it had zero ore in it.

![image](https://user-images.githubusercontent.com/65734844/172219388-345da8ca-a198-4d39-a399-4632df5fce3b.png)

Well that's strange. I have two mining control towers, each one assigned to the same set of storages. This system has been untouched since year... 10? The start of the game. But for some reason, they are over-riding this manual assignment and overflowing into the shipyard. 

![image](https://user-images.githubusercontent.com/65734844/172219468-80af68d8-456a-42b1-9744-e924e385629d.png)

Here are the save files - I did some testing including deleting, and then re-linking the assigned storage. This does not appear to have fixed the issue. One truck will randomly go from the mine, and instead of waiting at the mining tower, it drives to the dock and unloads there.

The save in overflow.zip is zoomed in directly onto a truck which is about to unload iron ore at the dock. I included several earlier autosaves before I realized the problem and started messing with things.

[22-06-06_11-47-17_8787-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8846557/22-06-06_11-47-17_8787-autosave.zip)
[22-06-06_12-02-24_5534-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8846558/22-06-06_12-02-24_5534-autosave.zip)
[Overflow.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8846571/Overflow.zip)
[22-06-05_15-25-42_9890.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8846561/22-06-05_15-25-42_9890.log)

**Comment by lowstrife** [comment]
Ok so. Did some more testing. 

First I rebuilt the mining towers and moved the excavators over to a new tower, created new links. No success. 

I turned off my mines (paused excavators) and waited to see if the material would be pulled out of the shipyard. It was not, which means the assigned routing wouldn't let the general logistics capacity pull from the shipyard to the storage units. 

I rebuilt the things with T4 storage and I'm going to try and empty out the storage yard again and try with all brand-new infrastructure.

**Comment by lowstrife** [comment]
Rebuilt every part of the infrastructure involving copper. 

No issues anymore running assigned routes.

Shipyard is not filling up:
![image](https://user-images.githubusercontent.com/65734844/172230366-1b2c926e-795d-4996-b7c8-42751cb1f0ff.png)

Though the first time this happened it took 700 days - so I'm unsure to say forsure we're good to go. But at least rebuilding fixed it!

**Comment by zuff-coi** [comment]
Thanks for this report. It helped us fix the issue but it got lost in the mix. We apologize for the delay and you shouldn't run into this issue again as of v0.4.10!

Thanks!
