### ISSUE TITLE
Fuel saver I & II has the same amout of -15% fuel consumption effect.

### ISSUE THREAD

**Issue by vevi33** [MaFi-Games/Captain-of-Industry-issues#235]
**Describe the issue**
Fuel saver I & II has the same amout of -15% fuel consumption effect (in the captain's office)

**To Reproduce**
Just open edicts panel using any save file.

**Additional context**
 - Game version: 0.4.1e

Screenshots:

[https://i.imgur.com/aDH2XQF.png](https://steamcommunity.com/linkfilter/?url=https://i.imgur.com/aDH2XQF.png)
[https://i.imgur.com/RmXFy5g.png](https://steamcommunity.com/linkfilter/?url=https://i.imgur.com/RmXFy5g.png)

**Comment by MaFi-Games** [comment]
That works as expected. Edicts are stackable.
