### ISSUE TITLE
Assigned trucks can't landfill cargo

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#236]
Horray another item reported by me :)

This one is pretty simple - rather than doing a whole writeup, this video should display the problem clearly. I want to dedicate a mega truck to getting rid of settlement waste and dumping it in the ocean (such environment, very friendly), but the truck just... sits there. 

https://user-images.githubusercontent.com/65734844/172232450-0e24d3e7-4a40-4dac-9476-5cafd661ba03.mp4

I'm going to assume because there is no linked destination? It can't just go "nowhere" as per the current rules. Would be nice if you could set a destination of landfill rather than linking it to another storage.

**Comment by lowstrife** [comment]
You can synthetically achieve the desired result (as Filip said in discord) by enabling assigned only. 

![image](https://user-images.githubusercontent.com/65734844/172241148-36c193fa-e67a-4fab-bc29-ac64f1d8c8c0.png)

Thing I want to do is have the mega-truck be the primary mover, but if that isn't quite enough (due to variable distance to dumping yards), the slack be picked up by the general logistics network. And all of this achievable within one building, rather than requiring two loose storage yards and a balancer. 

That's all thanks for listening <3

**Comment by MaFi-Games** [comment]
We have reimplemented this so that if there is a job we firstly make sure that the assigned truck gets it before any other truck.
