### ISSUE TITLE
Concrete Mixer II Recipe

### ISSUE THREAD

**Issue by ibsaggen** [MaFi-Games/Captain-of-Industry-issues#237]
**Describe the issue**
A clear and concise description of what the issue goes here.
When attempting to upgrade a concrete mixer I to concrete mixer II, the recipe is 120 construction parts III.
When attempting to build a concrete mixer II from scratch, the recipe is 40 construction parts III.

**Expected behavior**
Explain what you expected to happen.
The recipe should be the same regardless of upgrade vs build from scratch.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by Chevron9** [comment]
This also appears to be the same the Blast Furnace II

**Comment by MaFi-Games** [comment]
Yes, this was already fixed but pre-existing buildings might still be affected.
