### ISSUE TITLE
Trucks don't deliver fuel to liquid fuel tanks attached to fuel depots

### ISSUE THREAD

**Issue by jonesmz** [MaFi-Games/Captain-of-Industry-issues#239]
**Describe the issue**
I had a diesel fuel refinery filling a liquid storage tank with fuel. My trucks would drive all over the map to refuel from this liquid tank.

I constructed a fuel depot with an empty liquid tank set to store fuel, with the expectation that my trucks would deliver fuel to this empty liquid tank.

**Expected behavior**
No fuel was delivered to the empty liquid tank.

**Additional context**
 - Game version: 4.1e

**Comment by zuff-coi** [comment]
Sorry for the delay, are you still experiencing this issue as of v0.4.10? 

If you are, please reopen this ticket and provide a save file for us to take a look at. Thanks!
