### ISSUE TITLE
Link press kit from media page

### ISSUE THREAD

**Issue by mcunha** [MaFi-Games/Captain-of-Industry-issues#24]
The media kit is at the bottom of the front page. Meanwhile the media page has no link to the media kit. Maybe link the media kit from the media page as well ?

Keep up the awesome work.

**Comment by MaFi-Games** [comment]
Sure, we will consider this. Thanks for the suggestion.

**Comment by MaFi-Games** [comment]
Press kit is now on top of the media page.
