### ISSUE TITLE
Trucks import eggs to chicken farms

### ISSUE THREAD

**Issue by Banemaster** [MaFi-Games/Captain-of-Industry-issues#242]
**Describe the issue**
If chicken farm is set to import trucks will take eggs from storage to farm.

**Expected behavior**
Eggs should not be imported to chicken farms.

**Additional context**
 - Game version: 0.4.1e

**Attachments**
![egg loop](https://user-images.githubusercontent.com/6566926/172342218-5e45193c-e442-433a-af46-41edf51c38ce.png)

**Comment by MaFi-Games** [comment]
Thanks for report! This was fixed in last patch.
