### ISSUE TITLE
chicken farm and truck

### ISSUE THREAD

**Issue by Temmebo** [MaFi-Games/Captain-of-Industry-issues#243]
**Describe the issue**
Trucks deliver the eggs stored on the conveyor belt back to the chicken farm so that they can be stored again on the conveyor belt.

**Expected behavior**
Trucks should not deliver their own eggs to the chicken farm

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: 0.4.1E

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
This should be fixed now.
