### ISSUE TITLE
Two ships, One dock

### ISSUE THREAD

**Issue by Abrigz** [MaFi-Games/Captain-of-Industry-issues#244]
Repaired a second cargo ship while only having one dock. Now its stuck at the dock saying 'nothing to pick up' while the oil rig is full. I assume because the second ship is already occupying that route but now has no where to dock? Now have no way to import crude oil leading to fuel lock out.

**Expected behavior**
One of the cargo ships to remain offshore allowing cargo dock to function normally.

**To Reproduce**
1. Load attached save '...'
2. Watch as cargo boat does nothing.
3. Game over

**Additional context**
 - Game version: 0.4.1e

**Attachments**
[2nd Attempt - Cargo Ships.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8852460/2nd.Attempt.-.Cargo.Ships.zip)

**Comment by Abrigz** [comment]
Resolved. Having both modules set to upgrade stops cargo ship from operating. Removing upgrade orders resumes normal ship duties

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4a
