### ISSUE TITLE
Sea Pump problem

### ISSUE THREAD

**Issue by ZaKeNz78** [MaFi-Games/Captain-of-Industry-issues#246]
**Describe the issue**
The basic sea pump and advanced sea pump have the same rate (120/60)

**Expected behavior**
basic pump need to be 60/60 i think

**To Reproduce**
since i unlocked the advanced pump , the basic goes from 60 to 120 (same as the advanced)

**Additional context**
 - (sorry for my english i'm french and thx for ur game !!!!

**Comment by Chevron9** [comment]
I think the advanced pump reaches down further, which is the upgrade.

**Comment by ZaKeNz78** [comment]
i dont understand , its a sea pump so its useless to reach down further

**Comment by Chevron9** [comment]
It means that you can build it on higher ground, such as the platforms on some islands that go further up.
