### ISSUE TITLE
Connectors store materials which despawn if the connector is destroyed

### ISSUE THREAD

**Issue by Gravn** [MaFi-Games/Captain-of-Industry-issues#248]
Description:
It seems like connectors can store up to ~30 materials, but are not releasing those materials when removed. 
In my case i lost a bunch of electronics because i paused the belt, wanting it to stay in storage, then tried to get them out of a connector.

If this also works for pipe, I guess you can remove pollution for 'free'? 
But mostly just creating sad moments for players unaware, since most buildings needs emptying.

Expected:
Either a truck emptying the connector, or materials placed back on the belt

Steps:
1. Have a belt filled with materials (I used potatoes looping back into storage)
2. Create an offshoot, which creates a connector. The offshoot can stay in planning mode/unbuilt,
2. Pause the belt segment after the connector in order to fill up the connector.
3. Remove the offshoot, which converts the connector into a regular belt tile.
Observe that you now have less materials than before.
Reproduced with flat and u-shaped conveyor, connectors right next to storage seems to hold more?

**Additional context**
 - Version: Early Acess 0.4.1e

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
