### ISSUE TITLE
UI locks up durring blueprinting, possible U-shape conveyors only.

### ISSUE THREAD

**Issue by CrazyOdd** [MaFi-Games/Captain-of-Industry-issues#249]
**Describe the issue**
Blueprinting can some times lock the game. 
UI for U-shaped conveyor sticks around, everything else is locked. 
Game runs, but nothing can get you out of the stuck UI, other then ALT+F4.

**To Reproduce**
Other then what the log says, do a lot of messing around with U-shaped conveyors, I guess.

**Additional context**
 - Game version: 0.4.1e

[22-06-07_17-31-50_2873.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8855608/22-06-07_17-31-50_2873.log)

**Comment by zuff-coi** [comment]
Have you had this issue again since this ticket was opened? If so, could you provide new logs?

**Comment by CrazyOdd** [comment]
Havent had it in a few builds, so probably fixed.
