### ISSUE TITLE
Flywheel has no pause

### ISSUE THREAD

**Issue by Repenix** [MaFi-Games/Captain-of-Industry-issues#25]
**Describe the issue**
When placing a Flywheel down you can't pause the construction of it.

**To Reproduce**
1. Place FlyWheel down
2. Select it.
3. No pause icon

**Expected behavior**
Should be able to pause the construction like all other buildings

**Additional context**
 - Game version: 0.1.7

**Attachments**

![image](https://user-images.githubusercontent.com/91574788/135178688-47bcb8af-a28a-4194-99f0-dd93b3158c7d.png)

**Comment by MaFi-Games** [comment]
Construction has its own pause so this can be closed now.
