### ISSUE TITLE
Pipe II is being filled by adjacent Pipe III, but there is no connection

### ISSUE THREAD

**Issue by jarquafelmu** [MaFi-Games/Captain-of-Industry-issues#250]
**Describe the issue**
For some reason, my sewage pipe is being filled by the adjacent water pipe even though there is no connection, which is hurting my people. The pipe in question is connected to a balancer and I checked in case there was water coming into there, but the only other pipes connected are two intake pipes, both with waste water in them.

**Expected behavior**
Pipes not connected shouldn't mingle

**To Reproduce**
1. Load attached save
2. Remove products from the outlet pipe connected to the pipe balancer, going to the waste water treatment plant.
3. Observe how it fills with water again.

**Additional context**
Version 0.4.1e

**Attachments**
Save: 
[bugged pipe.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8855755/bugged.pipe.zip)

Where it is
![first](https://user-images.githubusercontent.com/5807272/172458807-0f5ac912-c889-4c18-9100-b15982a930fb.png)

Pipe in question
![image](https://user-images.githubusercontent.com/5807272/172458781-5c617fb1-1a22-4a95-a37e-a7917a1f00e3.png)

Balancer 
![image](https://user-images.githubusercontent.com/5807272/172458964-3e16a02c-a400-415a-9fde-7b4305df4b06.png)

In Pipe 1 
![image](https://user-images.githubusercontent.com/5807272/172459081-7b23540e-1198-4fa6-b15d-248667f65e51.png)

In Pipe 2 
![image](https://user-images.githubusercontent.com/5807272/172459127-4d7ac5b6-f07c-4d91-a9da-3a3b83175c2e.png)

Pipe Spaghetti
![image](https://user-images.githubusercontent.com/5807272/172459555-bd854ce1-c313-4cb7-91c8-de0856708a98.png)

**Comment by zuff-coi** [comment]
This is caused by the selected pipe (which is your water output from your Wastewater Treatment) being fed into your wastewater line.
![image](https://user-images.githubusercontent.com/108291414/185334607-7f4346fa-c5f5-4faf-86bf-d9fdd6dad8c0.png)
