### ISSUE TITLE
Building a second transformer allows you to get extra Unity

### ISSUE THREAD

**Issue by Chevron9** [MaFi-Games/Captain-of-Industry-issues#251]
**Describe the issue**
If you build more transformers and attach them to the same settlement, you can gain more Unity than what is presumably the limit. It seems odd to see +4,14/2,07 displayed.

**Expected behavior**
Unity should only be generated up to the displayed limit (e.g. 2,07), regardless of how many transformers you attach.

**To Reproduce**
1. Build two transformers
2. Check Settlement screen

**Additional context**
 - Game version: 0.4.1e

**Attachments**
https://i.imgur.com/0iBuwgd.jpeg

**Comment by MaFi-Games** [comment]
Thanks for report. This has been fixed in one of our previous patches.
