### ISSUE TITLE
Opening and closing the console hides UI elements such as game menus and tutorial popups

### ISSUE THREAD

**Issue by DianaNites** [MaFi-Games/Captain-of-Industry-issues#254]
**Describe the issue**
Pushing the tilde key to open the console, and then closing it, will hide game menus, such as the pause screen, and tutorial popup. Opening the console again reveals the UI elements under the console, and closing it once again hides them.

**Expected behavior**
Closing the console does not hide essential UI elements.

**To Reproduce**
1. Push esc
2. Push the tilde key twice
3. The esc menu is hidden

**Additional context**
 - Game version: 0.4.1e

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
