### ISSUE TITLE
If you build a ramp under a pipe section, then delete pipe section, still no pathing.

### ISSUE THREAD

**Issue by Morz46** [MaFi-Games/Captain-of-Industry-issues#255]
If you build a ramp under a pipe section, but then delete the pipe section, the pathing does not update and taller vehicles are unable to pass.  setting to delete the ramp, then canceling delete fixes the issue.

version 0.4.1E

**Comment by zuff-coi** [comment]
Thanks for reporting this! Sorry for the delay.

Can confirm this is still happening in v0.4.10:
![image](https://user-images.githubusercontent.com/108291414/185335399-4d3abf04-f3bb-4865-ba54-7d3807256540.png)
![image](https://user-images.githubusercontent.com/108291414/185335442-7bcb065f-27a4-46e8-ba82-7871ceb13ce6.png)

Attached save for testing: 
[broken_ramp_without_pipe.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9371375/broken_ramp_without_pipe.zip)

**Comment by MaFi-Games** [comment]
This appears to be already fixed in `v0.4.12`. If the problem persists, please re-open this or file a new report, thanks!
