### ISSUE TITLE
Vehicle Depot - Trucks will pick up Stored Product

### ISSUE THREAD

**Issue by MrJoshua023** [MaFi-Games/Captain-of-Industry-issues#256]
[VehicleDepotBug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8859381/VehicleDepotBug.zip)
**Describe the issue**
Trucks are picking up materials stored in the Vehicle Depot III.

**Expected behavior**
Trucks do not pick up any materials stored in a Vehicle Depot.

**To Reproduce**
Have not attempted to reproduce, however, I have attached the game saved with it happening.

**Additional context**
 - Game version: 0.4.1e

**Attachments**
Save game with the issue happening.

**Comment by AlphaZeon** [comment]
[Steel Truck Loop.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8869255/Steel.Truck.Loop.zip)
Can confirm, trucks are picking up steel from the Vehicle Depot III and redepositing it into the steel storage for the Depot.
Load the save, and pause and unpause the facilities supplying the depot and itself.  All the trucks will store their steel inventory in the shipyard when paused then after unpausing go back to the same behavior.

**Comment by c0nnex** [comment]
#295 Same issue with save and setup

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4. The fix is: conveyors will not push products into vehicle depot if they are not needed thus preventing the loop between conveyors and vehicles.
