### ISSUE TITLE
Upgrade cost 3 times more than build it new.

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#257]
hi Marek and Filip,

two buildings in COI cost when you upgrade them 3 times the amount as if you just build them compley new.

Mixer normaly cost 40 construction Parts 3 when upgrading from MK I you need 120.
Blast furnace cost 180 construction Parts 3 when upgraded from MK I you need 540. 

Would nice if you can fix in in the next patch.

McRib

**Comment by kosch104** [comment]
This is also mentioned by #231 (Foundry = Assembly?)

**Comment by MaFi-Games** [comment]
This is already fixed but any blast furnace built before the fix has this calculation broken. If you rebuild the furnace it should be gone. Please file a new ticket if the issue persists.
