### ISSUE TITLE
New Game: Cursive text not updated when changing settings

### ISSUE THREAD

**Issue by kosch104** [MaFi-Games/Captain-of-Industry-issues#258]
**Describe the issue**
When Starting a new game and customizing options to fit a preset (Sailor, Captain, Admiral) the Preset is being highlighted, but the cursive text below is not updated correctly.

**Expected behavior**
When the game highlights the preset fitting to your custom settings, the cursive text is also updated accordingly.

**To Reproduce**
1. Click on "New Game"
2. In "Game Difficulty" select "Sailor"-preset
3. Change all values to "Standard"
4. The "Captain" preset becomes selected, but the cursive text below is still showing "For players who want a smoot sail - Learning the ropes"

**Additional context**
 - Game version: 0.4.1e

**Attachments**
![grafik](https://user-images.githubusercontent.com/24923925/172636299-907efe47-8546-475b-be86-02a79e0629f8.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
