### ISSUE TITLE
Squares are not displayed

### ISSUE THREAD

**Issue by Urec-borec** [MaFi-Games/Captain-of-Industry-issues#259]
Hello, thank you for your wonderful game =)
I ask you to redo the textures of squares indicating the place of dumps and resource extraction from dx11 to dx10, thank you very much

![Безымянный](https://user-images.githubusercontent.com/37949641/172638908-c9187db4-d6f5-4e6a-9ce4-586113c7fabd.png)

[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8862200/Player.log)
[22-06-08_17-55-19_2104.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8862203/22-06-08_17-55-19_2104.log)

**Comment by JamieRCHI** [comment]
Are you talking about an invisible Mining Control Tower?
Or the view that is shown when the Tower is selected and the overlays are enabled.
Which in your picture they are off. (Bottom left Layer Tool)

**Comment by Urec-borec** [comment]
> Are you talking about an invisible Mining Control Tower? Or the view that is shown when the Tower is selected and the overlays are enabled. Which in your picture they are off. (Bottom left Layer Tool)

Hello, I'm talking about such squares
![Screenshot_20220613-022114](https://user-images.githubusercontent.com/37949641/173256022-ddca440a-aa46-442b-8cfd-0bb372417a73.png)


But I don't have them displayed due to the lack of dx 11

**Comment by GolokIgor** [comment]
Same problems. Wireframes from mining/dumping designation hidden on my Nvidia Quadro. On AMD Radeon all working propertly.

**Comment by JamieRCHI** [comment]
I get it now. I won't touch the Quadro cards. I believe are mostly used to speed up Autocad. I found that Rhino 3d was better written for 3D. (Written by a former Microsofty.)
Autocad was modified for 3d, but was never properly re-written. Thus the need for the Quadro cards for it to work properly.
I demoed the latest version of Autocad, but on a 'Gaming' card it works poorly.  With the latest Rhino 3D, I get very good results.

I might 'guess' that this would be a "Not Likely" by the Developers . I would not expect games to work well with Quador cards. The other issue reported with DX11 versus DX10 might be different (or not). I guess we will have to wait for a developer to chime in.

**Comment by Urec-borec** [comment]
@MaFi-Games 
Developers, I urge you, please answer

**Comment by MaFi-Games** [comment]
Hi, unfortunately it seems that you are running on older hardware that does not support GPU instancing. I see a log of errors like `ERROR: Shader Mafi/TerrainDesignationInstanced shader is not supported on this GPU`

What GPU are you using? Do you have updated drivers?

**Comment by Urec-borec** [comment]
I am using a GT240 graphics card made in 2007
OpenGL: 3.3
GLSL: 330

**Comment by MaFi-Games** [comment]
Ok, I think the game unfortunately won't work on this hardware, it's simply too old. If you have no other way to play this game, you can try to reach out to Steam for a refund. Sorry about that.
