### ISSUE TITLE
Connector corner issue

### ISSUE THREAD

**Issue by cw64** [MaFi-Games/Captain-of-Industry-issues#260]
**Describe the issue**

When connected to a production output and immediately creating a corner on the output tile, a second connector will not join to the corner coming in in line (T junction), A straight line across the output and then connected to the output works fine. Definitely seen this frequently with pipes, pretty sure belts too, and it is assumed to be the same for inputs. It appears to be a problem with the corner piece stopping the engine from changing it to a junction piece.

Now that I have your attention I would like also to submit a new building for your consideration. People talk often about burying pipes underground yet no one seems to be doing it. My guess it's too cumbersome to do manually, so I think a building dedicated for pipe laying a la mining tower should be added. Basically A building that has excavators and trucks assigned to it will give the option to auto dig, lay, and bury pipes simply by dragging out the pipe locations, All upgrades, and modifications have to be dug up and relaid. As this is a lot of work being done for the player it may be a good idea to block using unity to instabuild or give it a higher cost than regular instant completion. Possible future expansion for breaking pipes due to disasters too.

This game looks like lots of fun, I'm pretty good at finding bugs, and would be much better at it if someone were to email me a key :o) 
I'll probably pick it up at some point, why no make that day today?

Really well made game btw, the attention to detail makes it very enticing.

**Expected behavior**
New connector line attaches to existing corner
Steam key in my inbox 

**To Reproduce**

Don't have a save to attach as I don't have a copy of the game to play, but I have noticed this happen consistently watching various streamers

seems to be every time without fail. build anything with an output, attach connector and immediately make a right angle on the output tile, build a new incoming pipe line to make a T junction and the addition will refuse to connect. Build a straight line across the output and then connect and everything is fine. 

1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]
I don't have game version as I don't have the game :(

**Attachments**
Would be much easier to add attachments if I had the game =:oD

**Comment by JamieRCHI** [comment]
Took awhile to figure out what you were talking about. 
You must be talking about the small cube like thing that is added at the 'tee' where belts and pipes are joined.

Yes. This is really bad when the thing you are connecting to is going up or down to another level and the game complains that you are trying to connect to a sloped object. Which is Not the case when you want to connect to the bottom or top of the slope.

We really need the option to Manually place these one tile 'connector' things before placing the belts or pipes so this could be prevented. 

Am I on the right track here?

**Comment by MaFi-Games** [comment]
I think this is related to the issue of a transport that cannot connect to sloped transport corner. We solved this in Update 1 by removing sloped corners entirely. So closing as completed.
