### ISSUE TITLE
Random Hang Issue

### ISSUE THREAD

**Issue by orpy13** [MaFi-Games/Captain-of-Industry-issues#261]
**Describe the issue**
1.Crash of system, game 'pauses' mouse still functional, music still plays, system otherwise completely dead, 

**Expected behavior**
as above

**To Reproduce**
seems random

**Additional context**
 - Game version 0.4.1E

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by orpy13** [comment]
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8863286/Logs.zip)

**Comment by MaFi-Games** [comment]
I can see: WindowsVideoMedia error 0x887a0005 while reading archive:/CAB-c02e8ba9fa5d430a277882ee817153f4/CAB-c02e8ba9fa5d430a277882ee817153f4.resource

This will be gonne once we remove all videos from tutorials.

**Comment by MaFi-Games** [comment]
All videos from tutorials were removed, so hopefully this should no longer be an issue.
