### ISSUE TITLE
Recipe icons overlay on top of text

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#262]
**Describe the issue**
See screenshot. The sub-icon for the assembler is layered on top of the text making it impossible to read that this is for the mark 'II' assembler.

**Expected behavior**
To be able to read the text

**To Reproduce**
View screenshot

**Additional context**
 - Game version: 0.4.1e

**Attachments**
![icon covers text](https://user-images.githubusercontent.com/4413670/172696237-52f7d2bf-c9eb-48fb-bb7c-f62bfad3f397.png)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks!
