### ISSUE TITLE
Trucks unloading cargo from full shipyard only 1-4 units at a time with partial load option disabled.

### ISSUE THREAD

**Issue by jas0971** [MaFi-Games/Captain-of-Industry-issues#263]
**Describe the issue**
Allow partially loaded trucks option is disabled.
When transporting wood from a saw mill or crude oil from an oil rig with the ship, after reaching the shipyard all of my available trucks begin unloading the cargo only taking 1-4 units at a time.
Because they are not taking a full load, all of my trucks become extremely busy lining up outside of the storage to deliver 1-4 goods at a time, then go back to the shipyard to pick up another 1-4 units.

**Expected behavior**
I would expect a full load to be transported, 20 crude or 20 wood at once, not 1-4 units.

**To Reproduce**
1. Load attached save '...'
2. Jesse - all available trucks are unloading tiny amounts of crude oil instead of taking full loads
3. Jesse1 - all available trucks are unloading tiny amounts of wood instead of taking full loads

To reproduce on seemingly any game, sail the ship to a saw mill or oil rig and load up.
Upon returning to the island, with shipyard set to keep empty and partial load disabled, watch as all available trucks gather tiny amounts of resources and queue up outside of storages.

**Additional context**
 - Game version: 0.4.1e

**Attachments**

Screen clips of wood transport:
![WTFwood](https://user-images.githubusercontent.com/107144884/172694644-66d3d07e-e16b-4dbc-98f9-01487ecd437a.png)

Screen clips of crude transport:
![WTFcrude](https://user-images.githubusercontent.com/107144884/172695809-8e601f35-61c6-407b-8c9a-728e56ad880c.png)

Saves:
[COIsaves.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8864348/COIsaves.zip)

**Comment by Praefator** [comment]
Same issue with potatoes as of 0.4.2.

I moved farms around (and unity deconstructed, causing the potatoes to be dumped in the shipyard), then a mad dash occurs with all the trucks seemingly afraid of not having a topped up food market II for more than a few seconds. 

Save and a screenshot included for sake of completeness.
![20220609043820_1](https://user-images.githubusercontent.com/841990/172752599-5713c2d2-4a45-42c0-8b29-fdcf871425b3.jpg)
[YouShallNotPass.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866292/YouShallNotPass.zip)

**Comment by Praefator** [comment]
Seems to be fixed as of 0.4.2a @jas0971

**Comment by MaFi-Games** [comment]
I think we have fixed this in v0.4.4 but will keep this open for a while if anyone runs into this again. If yes, new save file would be appreciated.

**Comment by moffmaster** [comment]
I noticed something similar when decontructing structures. Trucks seem to prioritize getting the materials to machines like assemblers, where only a small amount can be accepted, instead of taking the material to a storage facility in full loads.

**Comment by MaFi-Games** [comment]
In one of the last patches we have fixed this issue. Trucks should no longer unload cargo from shipayd in tiny quantities.
