### ISSUE TITLE
Trucks keep delivering materials to a 'keep empty' shipyard

### ISSUE THREAD

**Issue by Praefator** [MaFi-Games/Captain-of-Industry-issues#265]
**Describe the issue**
Despite setting the shipyard to 'keep empty' and putting the priority to do so at P1 (where everything else is at P9 or above), trucks keep dumping coal into my shipyard as some sort of overflow

**Expected behavior**
For my trucks (set to dump mined coal to an import storage near my coal mine via Advanced Logistics, then distributing coal from an export storage to coal consumers) to simply stop mining **and** to stop distributing coal to a storage I have no way of otherwise controlling (the shipyard) whenever the coal storages attached to the mine are full

**Suggested fix**
Allow the shipyard to become an Advanced Logistics (so that the player can decide whether the shipyard is even a valid destination to dump stuff in, and if coal does happen to make its way there, allow the player to redirect it back into the supply chain(s) where applicable

**To Reproduce**
1. Load attached save 'YouShallNotPass'
2. Let the game run
3. Watch the shipyard get flooded with ever more coal

**Additional context**
 - Game version: 0.4.2

**Attachments**
- Save file
[YouShallNotPass.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8865615/YouShallNotPass.zip)

**Comment by AlphaZeon** [comment]
Have pretty much the same problem here although I haven't tried reproducing it.  It has happened with 3 of my mines so far Iron, Copper, and Coal
[Shipyard Resource Collection.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866059/Shipyard.Resource.Collection.zip)
.

**Comment by Praefator** [comment]
I'm slowly making my way through all the shipyard coal by pausing the coal mining, and alternatively configuring it in such a way that it "keeps full" (pulling 360 coal from the shipyard into a loose storage II), then set to empty, and link up to the coal mining input. Once the separate loose storage II is empty, rinse and repeat. Managed to get down to 11920 coal (out of ~16k when I started) so it's an arduous process with more micromanaging than I care to admit, but at least it's getting _out_ rather than in

**Comment by Praefator** [comment]
Update: despite painstakingly clearing out all the coal from the shipyard, the moment I re-enabled the mining tower the issue started all over again, with the trucks insisting on delivering coal to the shipyard without any command allowing them to do so in the first place

**Comment by utdrmac** [comment]
Similar #253 This is the biggest problem right now with trucks. So many of my trucks are "busy" doing this load/unload loop directly at the dock.

**Comment by Praefator** [comment]
Yeah, seems to be fixed with the 0.4.2a update today though

**Comment by utdrmac** [comment]
This is not fixed. See comments in #253
