### ISSUE TITLE
Large trucks not transporting crude oil

### ISSUE THREAD

**Issue by T401MAYHEM** [MaFi-Games/Captain-of-Industry-issues#268]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by T401MAYHEM** [comment]
I assigned two trucks to a transport route of crude oil (storage tank to storage tank) from the far oil field on the first map to my production area, but the trucks won't seem to go the the fluid container to load the crude. The pickups do the trip without any issues.

If you load the save the cameral should be zoomed in on the two trucks that seem to be having an issue.

I am on version EA 0.4.

[Potential Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866609/Potential.Bug.zip)
2

**Comment by MaFi-Games** [comment]
Just trying it out and they seem to be working but we did few improvements since this bug was submitted. Also worth noting that mixing trucks sizes will bias the smaller onces if there are only smaller quantities to exchange.
