### ISSUE TITLE
Bread consumption post patch shot up.  Game also crashes trying to process 2000+ starving.

### ISSUE THREAD

**Issue by MrJoshua023** [MaFi-Games/Captain-of-Industry-issues#269]
Submitting as requested by dev on discord.

**Describe the issue**
Food, specifically bread shot up in consumption post update.
While trying to solve that problem and entire population starving in go one time.  I experienced several crashes.

**Expected behavior**
Food consumption remains relatively stable.

**To Reproduce**
Open attached save game.

**Additional context**
Game version 0.4.2
I did have 50% increased consumption on from edicts.  Turning those off and food saver on, I was able to save the situation.
At one point I did have several conveyors of food going in and citizens were eating it all as it came in.
My food was somewhat low already which likely exacerbated the situation.

Last note, game is stable again and consumption appears normal after fixing edicts and stabilizing food.  Crashes stopped.

[StarvingSoon.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866592/StarvingSoon.zip)

Game also crashed a few times trying to resolve.  I suspect processing 2000+ dying at the same time and all the notifications that go with that.

Graph showing Bread consumption jump upon loading the game after patch.
![image](https://user-images.githubusercontent.com/62954862/172759405-3b747a90-e84c-4910-b84a-a111a22b68e4.png)

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thanks! We found the issue, will be fixed in the next patch!  :)

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.4 :)
