### ISSUE TITLE
Truck wedged between buildings after picking up mats from storage

### ISSUE THREAD

**Issue by dbanttari** [MaFi-Games/Captain-of-Industry-issues#27]
Got a pathing issue with a truck that got stuck between (mildly awkwardly placed) buildings.  Appears to rapidly change states between "Will navigate to: [thing]" and "Navigating".

Save file attached.  The trucks are wedged  between "Construction Parts II Storage" and "Sand Loose Storage" in the middle of the screen.

[test4.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7249145/test4.zip)

**Comment by MaFi-Games** [comment]
This is a great report and helpful save! In fact there are two stuck trucks there! This is definitely some kind of bug in navigation and will need further investigation. Thanks for reporting!

**Comment by Burnrate** [comment]
Have a lot of stuck trucks.  I tore down the buildings around them but they all seem snagged on each other.  Save attached.
![image](https://user-images.githubusercontent.com/2849955/137195145-5f8245a3-239a-404f-864d-4f55d912d4fa.png)
[G7.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7340620/G7.zip)

**Comment by MaFi-Games** [comment]
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
