### ISSUE TITLE
failed to start newgame

### ISSUE THREAD

**Issue by AhmedGithub2021** [MaFi-Games/Captain-of-Industry-issues#270]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
[22-06-09_06-59-11_5685.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866687/22-06-09_06-59-11_5685.log)

**Comment by MaFi-Games** [comment]
This is because the CheatMenu mod is not up to date and conflicting with the game. We need to provide a better reporting on this.
