### ISSUE TITLE
same unable to start new gme

### ISSUE THREAD

**Issue by HesaHeart** [MaFi-Games/Captain-of-Industry-issues#272]
verified game thru steam still can not start new game after .4.2
[22-06-09_00-30-15_8606.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8866852/22-06-09_00-30-15_8606.log)

**Comment by MaFi-Games** [comment]
The log you sent contains: 
```
Exception during game initialization.
 ---> GameBuilderException: An exception was thrown while initializing mod 'CheatMenu' (CaptainOfIndustryMods.CheatMenu.CheatMenu)
```

The mod you are trying to load is crashing. Please contact the mod owner.
