### ISSUE TITLE
CTRL click to place a transport with changed rotation no longer registers

### ISSUE THREAD

**Issue by MathiasOC** [MaFi-Games/Captain-of-Industry-issues#273]
**Describe the issue**
Since the last patch, holding CTRL to change the rotation of a transport and clicking no longer places the transport.

**Expected behaviour**
Holding CTRL should change the shape of the transport. Clicking while holding CTRL should place the transport in that shape.

**To Reproduce**
Start a game
Place a transport with an angle in it.
Hold CTRL to change the shape of that angle.
Click to place the transport.
No transport is placed.

**Additional context**
 - V0.4.2

Unassigning "Clear designation" from CTRL + Left Click resolves the issue.

**Attachments**
None required

**Comment by quasarea** [comment]
Works fine when using right CTRL

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed in v0.4.2a.
