### ISSUE TITLE
Mine Control Assigned Trucks Cannot Unload into 'Accept Assigned Only'

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#276]
**Describe the issue**
Trucks assigned to a mine control tower cannot unload to a loose storage container which is assigned to same MCT, if Accept Assigned Only is checked.

**Expected behavior**
If truck-A and looseStorage-A are both assigned to mineControl-A, and 'Accept Assigned Only' is checked, I expect truck-A to be able to unload into looseStorage-A. The membership of looseStorage-A to mineControl-A should "override" the AAO for purposes of unloading.

**To Reproduce**
1. Create mine control tower/area. Assign excavator and 1 truck (T-A) to MCT.
2. Create loose storage container (LSC1) near MCT and create assignment between MCT and LSC1.
3. Assign another truck (T-B) to LSC1 and check 'Accept Assigned Only'
4. Create another LSC2 somewhere else (say, near cement processing) and create assignment between LSCs.

Truck-B will function correctly, taking material from LSC1 to LSC2. However, Truck-A will not be able to unload into LSC1 due to AAO restriction. Once you disable AAO restriction on LSC1, T-A is now able to unload.

**Additional context**
 - Game version: 0.4.2

**Attachments**
https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8857817/trucksSandStuck.zip

**Comment by zuff-coi** [comment]
This has been resolved as of v0.4.9c but your save game attached is for issue #253 which is still ongoing
