### ISSUE TITLE
Laggy/semi-frozen game from start

### ISSUE THREAD

**Issue by gs242** [MaFi-Games/Captain-of-Industry-issues#278]
As soon as i start the game everything on the computer becomes very slow and laggy. When clicking in the main-menu nothing happens at first, maybe after 20 seconds, After a few minutes of clicking and waiting i manage to load a map but can't do anything on the map. it takes about 50 seconds for the escape-menu to appear after pressing the button. 
I have an GTX 1060 3gb with the latest driver but i can't find the game in the NVIDIA menus and chose performance. I have 16gb of ram. 

The game version is the latest since i downloaded the game today. 
I apologies if the info is not good enough or if i miss any data, I'm still kind of a noob when it comes to this but try to learn so feedback is welcome as well as ideas how i can fix it.
Br
Gus

**Comment by MaFi-Games** [comment]
Sorry, but there is not enough information to understand what is wrong, but so far, no one else reported this kind of issue, so this might be related to your hardware. If you can still reproduce this on the latest version and have more details, please file a new issue.
