### ISSUE TITLE
No job created to deliver wood input to Assembly building

### ISSUE THREAD

**Issue by dawnmist** [MaFi-Games/Captain-of-Industry-issues#28]
**Describe the issue**
I was trying to start to increase production of construction 1 parts from 1 Assembly building to 2 Assembly buildings.
I built the second Assembly building so that it plugged into the end of the Metal Caster so that only wood would need to be delivered manually.
I had a nearby storage where wood was being dropped off, and multiple trucks that were reporting "no job".
I waited a couple of months.
No job to deliver wood to the new Assembly building appeared to be created.
Trucks are still delivering wood to the original building, and the charcoal burner. But then sit idle waiting for jobs.
During this time, some of the trucks had no jobs at all for the entire period, and simply sat in the area of both the storage and the second Assembly building.

**To Reproduce**
1. Load attached save and watch truck behaviour/Assembly building's status window for a couple of in-game months.

**Expected behavior**
Some of the nearby trucks with no jobs should start to deliver wood to the second Assembly building.

**Additional context**
 - Game version: Alpha 0.2.7
 - Running via Steam Proton on Debian 10 Linux - had been working flawlessly up until this point.
 
**Attachments**
[NotDeliveringLogs.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7259308/NotDeliveringLogs.save.zip)
![TruckNoJobs](https://user-images.githubusercontent.com/5810277/135451829-fd467f45-c4bf-4db2-b1ef-bdf6a0ff8448.png)
![NearbyWoodStorage](https://user-images.githubusercontent.com/5810277/135451844-c655b904-084c-49a0-a796-a71a8ed1b16c.png)
![AssemblyNoWood](https://user-images.githubusercontent.com/5810277/135451885-26271ccc-55dc-4b7a-8908-1090c30a3ee1.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, this is likely caused due to some internal ways how path-finding works, basically goals are not generated on diagonals from buildings. This needs improvements.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
