### ISSUE TITLE
Wont start new game

### ISSUE THREAD

**Issue by DrThraxGLA** [MaFi-Games/Captain-of-Industry-issues#280]
**Describe the issue**
wont start new game

**Expected behavior**
wont let me start new game and uninstalled and verify two time

**Additional context**
 - Game version: 0.4.2

**Attachments**
![captain of industry exe Screenshot 2022 06 09 - 15 05 35 07](https://user-images.githubusercontent.com/65963630/172935239-ae195c4d-d149-4f6d-a417-5d44c3f7288a.png)

**Comment by MaFi-Games** [comment]
Please share your latest logs, otherwise we have no idea what is wrong. They are in `Documents/Captain of Industry/Logs`.

**Comment by DrThraxGLA** [comment]
[22-06-09_18-46-06_3257.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8874556/22-06-09_18-46-06_3257.log)
