### ISSUE TITLE
Saves not showing up (again)

### ISSUE THREAD

**Issue by FaroeNoob** [MaFi-Games/Captain-of-Industry-issues#283]
**Describe the issue**
When I start the game there are no saves. The only option I get is to start a new game. I was able to play earlier today.

I have disabled Anti-Virus. I restarted the PC. I restarted Steam and nothing has helped.

**Expected behavior**

**To Reproduce**
--

**Additional context**
 - Game version: 0.4.2A

**Attachments**
![Captain1](https://user-images.githubusercontent.com/26882768/172948420-4ebbd24c-af21-4361-a73b-ada527bf3db9.png)
![captain2](https://user-images.githubusercontent.com/26882768/172948456-a4e9b94e-bc02-4316-8438-9b49ce673f2b.jpg)
![captain3](https://user-images.githubusercontent.com/26882768/172948463-16b25b11-fd06-4f5a-92ef-b062e9659ed9.jpg)

**Comment by MaFi-Games** [comment]
Could this be caused by "controlled folder access"? Saves are supposed to be stored in `Documents/Captain of Industry/Saves`.

**Comment by mathsk** [comment]
Hello,
I don't have my saves where you indicate.
They should be on a path like this : **C:\Users\maths\Documents\Captain of Industry\Saves**

**Comment by FaroeNoob** [comment]
> Hello, I don't have my saves where you indicate. They should be on a path like this : **C:\Users\maths\Documents\Captain of Industry\Saves**

I have no folder called COI under Documents. 

Upon downloading the game they were automatically put in "steamapps"

**Comment by FaroeNoob** [comment]
> Could this be caused by "controlled folder access"? Saves are supposed to be stored in `Documents/Captain of Industry/Saves`.

I love you. Turning "Controlled folder access" off fixed it!
