### ISSUE TITLE
Autosaving does not work in pause mode

### ISSUE THREAD

**Issue by L32GIT** [MaFi-Games/Captain-of-Industry-issues#284]
**Describe the issue**
The game does not autosave during pause.

**Expected behavior**
I was planning my base for 2+ hours, on pause mode, then lights gone off, restarted, no autosaves from today.

**To Reproduce**
Play on pause. No autosaves happen even when the setting is on.

**Additional context**
0.4.2a

**Comment by JamieRCHI** [comment]
An automatic save when pausing might be a good thing.

**Comment by utdrmac** [comment]
I've noticed this as well. If I pause for 15+ minutes, as soon as I unpause it auto-saves.

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
