### ISSUE TITLE
Design:  Datacenter requires Maintenance III not II

### ISSUE THREAD

**Issue by MrJoshua023** [MaFi-Games/Captain-of-Industry-issues#285]
**Describe the issue**
You need a datacenter that takes Maint 3, before you can make electronics III which you need to make maintenance 3.  
I feel like datacenter should be maint 2

**Expected behavior**
Datacenter takes Maintenance II
This would put it more in line with progression.

**Additional context**
You do get some Electronics III from exploring the world but I would assume its not enough.  It's also needed to get started making servers.

**Comment by camtarn** [comment]
Absolutely. Filed the same thing in the Suggestions tracker:

https://ideas.captain-of-industry.com/suggestions/307551/the-jump-from-research-iii-to-research-iv-is-too-huge-thanks-to-the-robotic-asse

I've literally just quit playing because of this issue.

**Comment by MaFi-Games** [comment]
This works as intended. There is lots of servers and electronics III in the world map. Also electronics III can be bought for gold.
