### ISSUE TITLE
text correction

### ISSUE THREAD

**Issue by Muadhib-games** [MaFi-Games/Captain-of-Industry-issues#286]
**Describe the issue**
A clear and concise description of what the issue goes here.
i notice ortograph errors
the text should be : 
" .... qui est régénérée .... doit-être construite au-dessus ..."

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
<img width="338" alt="Capture d’écran 2022-06-10 083942" src="https://user-images.githubusercontent.com/107240687/173007009-fdcf2227-0917-4507-a384-6af89b7965bc.png">

**Comment by mathsk** [comment]
Hello, 
You can use Weblate (https://translate.captain-of-industry.com/translate/captain-of-industry/game/fr/?offset=1&q=LandWaterPump__desc&sort_by=-priority%2Cposition&checksum=)

I've suggested your correction. You can vote to validate the change.

**Comment by MaFi-Games** [comment]
Fixed in weblate.
