### ISSUE TITLE
Load Game UI design

### ISSUE THREAD

**Issue by dcraig327** [MaFi-Games/Captain-of-Industry-issues#288]
**Describe the issue**
Load Game menu UI design doesn't support different playthroughs simultaneously, the auto-save string is confusing, required mods are not listed.

**Expected behavior**
Add additional information to the Load Game screen.

The following is listed in the ESC menu after loading a game:
 - Difficulty
 - Game Seed
 - Version

What data should be added?
 - Any data listed in the ESC menu in below attachment (Load Game should show all in-game data listed about the save)
 - Any mods, especially those that are required to be installed to load that save without error
 - Remove "Last Modified" as it's a phrase that's assumed to be known by players
 - In the current design, remove the string "Last Modified" as to the left there is no header or description of the "Filename" / "Savename" field, visibly making the design incomplete to users

What other data and how should it be organized?
 - Not for me to say given available time. I'll show examples from other games below

**To Reproduce**
1. Press ESC and Load Game or Load Game on Title Screen
2. After Loading Game, press ESC to see more info about the save

**Additional context**
 - Game version: 0.4.2A
 - Attached are screens of COI's current load game and esc menu. You'll notice my naming convention for saves included the game difficulty and seed name, this was before I was aware that's listed in the ESC menu and the reason I'm posting this issue
 - Attached few sample screens from other games as finding these screens are difficult without running those games yourself. The ONI Load Game screen is a 45 second video as it's too much to cover in a screenshot
- Finishing a redesign of Load Game screen will make it easier to allow a user selectable autosave duration, the game saves hyperfast, but is limited to 15 minute autosaves. If reducing that to 1 minute autosaves, would become cluttered. Lowered autosave frequency could allow another option to cap the number of autosaves as seen in ONI below

**Attachments**
[COI Load Game](https://user-images.githubusercontent.com/37514553/173027203-9a0e8df3-252c-4a5b-b3a7-3a6cd997ae13.jpg)
[COI ESC Menu](https://user-images.githubusercontent.com/37514553/173027267-6755712e-ce55-4799-883e-e0bb8498af07.jpg)
[Factorio Load Game](https://user-images.githubusercontent.com/37514553/173026587-b695efb8-ed7c-4fbd-bd15-67269346e118.png)
[Oxygen Not Included Load Game](https://user-images.githubusercontent.com/37514553/173030873-44180355-9359-40c9-b858-360313f0f1f7.mp4)
[Anno 1404 Load Game](https://user-images.githubusercontent.com/37514553/173026734-cf79ade9-d468-48d3-841a-a0cf8dc86654.jpg)
[Civ6 Load Game](https://user-images.githubusercontent.com/37514553/173026670-5247e572-7e90-41a5-a330-f1796b56297f.png)

**Comment by JamieRCHI** [comment]
I would like to see an option to hide autosaves.
An option to set any value of the autosave time to as low as 1 would be very helpful when debugging and issue.
Give us the option to decide how many autosaves to keep.
Maybe the autosaves should be in a list to the right of the manual saves.

**Comment by MaFi-Games** [comment]
Glad to say that we have reworked save / load menus a lot! Closing.

**Comment by JamieRCHI** [comment]
And you ignored my last comment. The Saves menu still needs work.
