### ISSUE TITLE
Oil Rig doesn't display correct production

### ISSUE THREAD

**Issue by basox70** [MaFi-Games/Captain-of-Industry-issues#289]
**Describe the issue**
When changing the production speed (0x, 1x, 2x ...) of Oil Rig, the production still display "9/20"

**Expected behavior**
Changing production speed should change the display (9/20 for 1x, 18/20 for 2x ...)

**To Reproduce**
1. Load attached save 'EA3.1.save'
2. Go on map
3. Change oil rig speed (only production level won't change, but the real production is not impacted)

**Additional context**

 - Game version: last of the day (V0.4.2a)

**Attachments**
[EA3.1.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8877989/EA3.1.save.zip)
![Screenshot_109](https://user-images.githubusercontent.com/6689304/173046099-8f0d52b8-32df-4df0-9872-f3c7b10e9b66.png)
![Screenshot_110](https://user-images.githubusercontent.com/6689304/173046105-3588353e-fdd5-4851-b938-6881f3e847d5.png)

**Comment by MaFi-Games** [comment]
Thanks! Fixed in last patch :)
