### ISSUE TITLE
Dirt not growing grass after landfill

### ISSUE THREAD

**Issue by Coheed1988** [MaFi-Games/Captain-of-Industry-issues#29]
After back filling iron quarry grass does not grow on top layer of dirt. Dirt layer is on layers 2 to -3 with a mixture of rock and slag between -3 and -8. Top soil may also be "unfarmable".
Originally excavated to -8 and using dumping designations I sequentially put down a layer up to -3 designating slag or rock, then overlaid with a second dumping designation of soil from -3 to ground level of 2.
Dirt came from various sources, including copper, sand and coal mines, from a dirt heap created as a temporary store between coal and copper mines and from wastewater treatment.

[No Grass Issue.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7265314/No.Grass.Issue.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report. Unfortunately we did not have time to look into this before beta, if you encounter this again in the beta build, please submit another report with attached save file.
