### ISSUE TITLE
Goods not removed from Cargo Depot Module when trading on world map

### ISSUE THREAD

**Issue by TimS84** [MaFi-Games/Captain-of-Industry-issues#290]
**Describe the issue**
When trading on the world map (e.g. selling wood for concrete with the first village), if the only wood left in the island inventory is on the cargo depot, you can trade until the bought goods are "sold out" without the goods for payment being deducted.

**Expected behavior**
Goods to be deducted from the cargo depot as well. Alternatively, goods stored on the cargo depot not being counted towards the island inventory (similar to goods on transporters not counting towards this, e.g. diesel in a pipe).

**To Reproduce**
1. Have/build a cargo depot with an active pick-up from world map (here: sawmill)
2. Have none of the goods to sell in storages anywhere on the island
3. Trade with the village and see that it's possible to keep selling without the amount in inventory (in brackets) decreasing

**Additional context**
 - Game version: 0.4.2a

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
[Trade Bug Save Game.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8879107/Trade.Bug.Save.Game.zip)
[22-06-10_08-01-37_5636.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8879110/22-06-10_08-01-37_5636.log)

**Comment by MaFi-Games** [comment]
Thanks a lot for reporting this. This was fixed in one of our last patches.
