### ISSUE TITLE
CTD during gameplay

### ISSUE THREAD

**Issue by wormzjl** [MaFi-Games/Captain-of-Industry-issues#292]
**Describe the issue**
CTD after entering the save and doing stuff for a while 

**Additional context**
0.4.2a

**Attachments**
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8880287/Player.log)
[Crash_2022-06-10_153616882.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8880292/Crash_2022-06-10_153616882.zip)
[22-06-10_23-13-17_3187-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8880318/22-06-10_23-13-17_3187-autosave.zip)

**Comment by MaFi-Games** [comment]
Closing as not enough information. Feel free to file a new issue if this persists on the latest version.
