### ISSUE TITLE
Large Truck wants to unload to Shipyard still (0.4.2a)

### ISSUE THREAD

**Issue by c0nnex** [MaFi-Games/Captain-of-Industry-issues#294]
**Describe the issue**
Large Truck assigned to mining operation (copper)
Minig operation has a designated target storage, which has not enough space for unloading full large truck (180)
Truck wants to unload to shipyard (can't in my save because raod blocked, that why i noticed it)
Only way to get the large truck back to "normal operation" is:
- Unassign dedicated storage from minig op
- Unassign large turck from mining op
- wait until it unloaded to nearby storage
- reassign large truck to mining op
- reassign dedicated storage

**Expected behavior**
Large truck will wait until there is enough space in designated target storage

**To Reproduce**
1. Load attached save '...'
2. At copper site,  wait until large truck is full and no space in designated storage to unload
3. Large truck complain about pathing -> wants to unload to shipyard

**Additional context**
 - Game version: 0.4.2a

**Attachments**
Save Gam
[r1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8881895/r1.zip)
e

**Comment by MaFi-Games** [comment]
![redLineCopper](https://user-images.githubusercontent.com/90082857/173464873-f2ead818-fec7-4cdf-b5b7-9951a162caf5.jpg)
Are you sure this is happening? I have checked your save file and the blocked access leads to another copper storage as on the screen above.

**Comment by c0nnex** [comment]
The save is from about 10 hrs after i observered the issue, was just too lazy to report it before. I'll see if I can reproduce again

**Comment by MaFi-Games** [comment]
Closing as I believe this is fixed. Please file a new bug if you have a save file from latest version to reproduce. Thanks!
