### ISSUE TITLE
Trucks play Ping-Ping with ressource

### ISSUE THREAD

**Issue by c0nnex** [MaFi-Games/Captain-of-Industry-issues#295]
**Describe the issue**
Vehicle Depot III
Connected Storage for Steel plates for vehicle building
Storage set to "Keep 50% full"

Storage is filled by trucks. 
Storage refills depot (thus falling beyonfd 50%)
Trucks wil pickup Steel from Depot, put it back into the connected storage
Storage will refill depot -> Trucks pick it up again and put back in storage

**Expected behavior**
Trucks should not play round robin with ressources, or the depot shout have a "Disallow Truck Pickup"-Setting

**To Reproduce**
1. See attached Save for Ticket #294 
2. Reconnect storages at depot upper left
3. Wait until ping pong starts

**Additional context**
 - Game version: 0.4.2a

**Attachments**
see #294

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4
