### ISSUE TITLE
The Chicken farm after all my chickens starved to death now instantly uses all food when ever there are any chickens in it. 

### ISSUE THREAD

**Issue by Profit0004** [MaFi-Games/Captain-of-Industry-issues#297]
**Describe the issue**
The Chicken farm after all my chickens starved to death (might be bug related) now instantly uses all food when ever there are any chickens in it. 

**Expected behavior**
I would expect the food usage to be .7 every 60 seconds like it says it should be. 

**To Reproduce**
I just reloaded the game to make sure this works. 
When you load the save if you add 50 chickens to the farm on the left of the group of farms, you will  see the food, no matter how much is in there will fall to zero.   The old farms before I built the new ones appear to be working fine.   The ones that still work never had all their chickens die, and are off to the left side by themselves. 

**Additional context**
 - Game version: 0.4.2a

**Attachments**
[save_22-06-10_15-55-16.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8881995/save_22-06-10_15-55-16.zip)

**Comment by Matzi1986** [comment]
I had the same issue. After rebuilding it worked again. But now i have the issue with the nuclear reactor and rebuilding doesn't work.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4
