### ISSUE TITLE
one tile long transports got higher throughput than stated

### ISSUE THREAD

**Issue by Erah101** [MaFi-Games/Captain-of-Industry-issues#298]
**Describe the issue**
A 1 tile long transport (like the pipe in the screenshot below) has a higher throughput than stated:
the 1t long pipe is connected to a balancer set to have priority output on a long pipe (there is another smokestack at the end of that one so it's never full)
another output leads to a smokestack, all pipes are level 1
in theory all the input should go to the priority output yet some ends up in the smokestack as proved by the smoke animation
only way that is possible is if the 1t pipe is moving products at a faster rate

**Expected behavior**
all tier 1 transports should have the same throughput so nothing should end up in the wrong output port on balancers

**To Reproduce**
setup some pipe like shown in the screenshot

**Additional context**
 0.4.3 but seen it before too

**Attachments**
![20220611021502_1](https://user-images.githubusercontent.com/106938562/173165778-c7c95a79-da48-49f3-a386-2c9aafa79c34.jpg)

![20220611021758_1](https://user-images.githubusercontent.com/106938562/173165761-0ee0c475-053e-4fcc-b182-4f0da7ae60a6.jpg)

**Comment by c0nnex** [comment]
Can confirm. Having the same issue.

**Comment by JamieRCHI** [comment]
Isn't there a buffer inside the balancers that holds extra stuff which could cause this to happen?

**Comment by CaptainLame** [comment]
An unboosted Air Separator doesn't exceed the flow of a T1 pipe. If the downstream consumer is using all of it, it should never overflow to the stack, but with the one tile length pipe it overflows anyway.

If I understand the given example, the N2 output balancer is feeding two smokestacks, with priority going to the one on the longer pipe. As outputs 36/60 so the smokestack and Pipe I shouldn't be 100% used. So no overflow to the stack with the short pipe should happen, but clearly it is.

**Comment by MaFi-Games** [comment]
Thanks for the reports, this has been fixed in v0.4.7!
