### ISSUE TITLE
Saving a game without a name breaks the game.

### ISSUE THREAD

**Issue by CumpsD** [MaFi-Games/Captain-of-Industry-issues#3]
**Describe the issue**

When you save a game without a name, you destroyed the game.

**To Reproduce**
1. Save a game without a name.
2. Restart
3. Get into an infinite loop because it tries to load saved games, but has a check to refuse empty strings.

**Expected behavior**

A game which starts :)

(Reproduced on discord)

**Comment by MaFi-Games** [comment]
Thanks, this was fixed in v0.2.0a pushed just now. Can I ask how did you manage to save game without name? Normally the save button is grayed-out when the name is empty.

**Comment by Str3amR** [comment]
> Thanks, this was fixed in v0.2.0a pushed just now. Can I ask how did you manage to save game without name? Normally the save button is grayed-out when the name is empty.

You were able to hit enter to generate the empty save even if the button was grayed out (not tested on the latest version)

**Comment by CumpsD** [comment]
Yes, sounds possibly. My hand slipped when I wanted to type and I hit enter :)

**Comment by Str3amR** [comment]
Ok I tested it again on the latest alpha and there is still a bug in the save screen where you can click "New save", click on the textbox and press Enter without entering anything and it bypass the disabled save button.

Maybe this should be filled as another bug and let this one close since it no longer break the game?

**Comment by MaFi-Games** [comment]
> Maybe this should be filled as another bug and let this one close since it no longer break the game?

It's fine, I will try to fix this one as part of this issue, but it is a little mysterious what is causing the enter to submit the button, since we don't do that. It must be some default behavior in Unity.

**Comment by MaFi-Games** [comment]
This has been fixed in `v0.2.0c`
