### ISSUE TITLE
Trucks won't deliver last few parts to complete construction

### ISSUE THREAD

**Issue by dawnmist** [MaFi-Games/Captain-of-Industry-issues#30]
**Describe the issue**
Trucks have stopped delivering the Construction 1 parts to the concrete mixer to complete construction. It's got free access on all 4 sides with only one pipe attached - and some of the other parts were being delivered with the pipe there. There are parts available (100 of them in the attached save), and trucks idling without a job, all other planned buildings are paused (hence why there are now 100 parts in storage) with the exception of the vehicle ramps - but those use construction 2 parts rather than construction 1 parts, so they are no competition for the parts needed to complete the concrete mixer.

![ConcreteConstructionNotCompleting](https://user-images.githubusercontent.com/5810277/135549712-dbbf9536-ddd0-44bf-8519-941d8b1339de.png)
![ConcreteConstructionTrucksIdling](https://user-images.githubusercontent.com/5810277/135549719-ca7096c4-33d1-493c-a1cf-e5d0130c57d9.png)

The concrete mixer to the left of the one that won't complete built straight away when I unpaused construction for that building - but the first still didn't get the last 4 parts.

This building remained not constructed for multiple in-game years. It was eventually solved by opening the Concrete Mixer window for the building, clicking the "Cancel" button to mark the partially-built building as one to be destroyed, then clicking "Cancel" in the deconstruction window so that it was again set to build. Once this was done, trucks delivered the last 4 construction 1 items immediately.

Potentially related to issue #28.

**To Reproduce**
1. Unzip and Load attached save 'ConcreteMixerNotBuilding.save.zip'
2. Watch some trucks idling with none delivering the last 4 parts for the Concrete Mixer to be constructed.

**Expected behavior**
The Concrete Mixer is supposed to have 4 more Construction 1 parts delivered so that its construction can be completed.

**Additional context**
 - Game version: Alpha 0.2.7, persisted in Alpha 0.2.8 when reloading the autosave in order to verify that it was one containing the issue and attach it to this issue.
 - Running via Steam Proton on Debian 10 Linux

**Attachments**
Save game: [ConcreteMixerNotBuilding.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7263356/ConcreteMixerNotBuilding.save.zip)

**Comment by MaFi-Games** [comment]
This is rather strange, thank you for the report and save file, we will investigate.

**Comment by MaFi-Games** [comment]
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
