### ISSUE TITLE
Truck partial load setting is ignored when keeping shipyard empty

### ISSUE THREAD

**Issue by L32GIT** [MaFi-Games/Captain-of-Industry-issues#300]
**Describe the issue**
When shipyard setting is set to "keep empty" and global truck setting of allowing partial load is disabled, trucks still do deliver 1 item at a time, trying to clear a shipyard.

**Expected behavior**
Global truck setting of allowing partial load is respected even if shipyard can't be cleared at the fastest possible way.

**To Reproduce**
Manually load coal from the world mine with your primary ship, sail back to the shipyard.
Have your coal storages in the island almost full, but with a steady consumption.
Set a setting of not allowing partially loaded trucks.
Observe trucks with 1 coal running back and forth, as they pick the coal as soon as there is at least 1 empty spot in the storage.

**Additional context**
0.4.3

**Comment by MaFi-Games** [comment]
That works as intended. Keep empty forces partially quantities otherwise it would behave the same as the default behavior and wouldn't be needed at all. We need to explain better what Keep Empty does.

**Comment by L32GIT** [comment]
Okay then, feel free to edit this issue into "Create a better hint for the keep empty setting".

**Comment by MaFi-Games** [comment]
Ok, there is something broken. They do deliver 1 quantity even when they can deliver more.
