### ISSUE TITLE
Toxic Slurry Dumping research

### ISSUE THREAD

**Issue by Honjura** [MaFi-Games/Captain-of-Industry-issues#304]
**Describe the issue**
Liquid Dumps cannot process Toxic Slurry until the user researches Uranium enrichment, however, the toxic slurry is also produced by refining Gold. The research for Gold Smelting does not provide the process of toxic slurry in Liquid dumps.

**Expected behavior**
Researching Gold Smelting should provide the process of Toxic Slurry in Liquid dumps.

**Additional context**
Game Version 'v0.4.3'

**Attachments**
[save_22-06-11_12-27-58.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8883233/save_22-06-11_12-27-58.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4
