### ISSUE TITLE
Custom keybinding for "Move right" doesn't save

### ISSUE THREAD

**Issue by squished-01** [MaFi-Games/Captain-of-Industry-issues#305]
**Describe the issue**
Custom keybinding for "Move right" doesn't save

**Expected behavior**
Custom keybinding for "Move right" should save

**To Reproduce**
1. Rebind Move left from D to F (in the left of the two columns on the settings/miscellaneous screen)
2. save the game, exit to desktop
3. run the game, load the save file
4. "Move right" is bound to D again

**Additional context**
 - version 0.4.3
 - also had up left down rebound to E S D respectively

**Attachments**
hopefully none needed

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4
