### ISSUE TITLE
Stored goods in Assembly become unavailable when recipe is deselected

### ISSUE THREAD

**Issue by MarcCeras** [MaFi-Games/Captain-of-Industry-issues#307]
Stored goods in Assembly become unavailable when recipe is deselected.
When you start to build more Assemblies and specialise them, the stored raw material and allready produced goods become unavailable. 

**Expected behavior**
It should be possible to give the order to "clear" the Assembly from certain raw materials and goods to store them elsewhere or consume them. 

![Screenshot (487)](https://user-images.githubusercontent.com/107309638/173189519-e85ab8a3-65de-429a-8753-2edff7cc335a.png)

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates. We have added a trash button to clear the products.
