### ISSUE TITLE
Upgrading a Blast Furnace to a Blast Furnace II takes three times the materials of making a new one

### ISSUE THREAD

**Issue by Kieriel** [MaFi-Games/Captain-of-Industry-issues#309]
**Describe the issue**
Building a new Blast Furnace II takes 135 Construction Parts III. Upgrading a normal Blast Furnace takes 405 Construction Parts III. That is three times the materials needed to build a new one.

**Expected behavior**
Upgrading to the next level to take less materials than building a new buildings, as established on assemblies and similar upgradable buildings.

**To Reproduce**
Try to upgrade a Blast Furnace into a Blast Furnace II, observe the projected cost.

**Additional context**
 - Game version: EA 0.4.3
 - I admit I haven't tried actually upgrading one to see if it's just a display issue and actually takes less materials. But it's consistent between what it tells you before upgrading and what it says it wants once you confirm the upgrade.

**Attachments**
![Captain_of_Industry_GfyE3Iu49k](https://user-images.githubusercontent.com/107315636/173196601-4261fe66-7600-4cb5-a9f8-fe22e275584d.png)
![Captain_of_Industry_xLDkCmQtWp](https://user-images.githubusercontent.com/107315636/173196611-c336d745-73e4-46f4-a760-c0b0fdc4f926.png)

**Comment by ShawnTheShadow** [comment]
I'm getting the same thing, though the amount is even worse 
![Captain_of_Industry_7XHxt0FUhX](https://user-images.githubusercontent.com/22384794/173199223-4bf2f5a1-ef69-4036-a9fb-4e47d7eb73b8.png)

**Comment by Erah101** [comment]
i'm also getting that issue but oddly not on all furnaces, some take 540 parts and some 180 parts

**Comment by Chevron9** [comment]
This is an artifact of an earlier issue - it was fixed, but not for structures which already existed when the patch was applied. those you will simply have to demolish and then build the T2 version in that place.

**Comment by MaFi-Games** [comment]
As the last comment mentioned, this should be fixed however entities built before the patch might still be affected.
