### ISSUE TITLE
Rechtschreibfehler

### ISSUE THREAD

**Issue by Godlike2507** [MaFi-Games/Captain-of-Industry-issues#310]
#**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
![captain of industry](https://user-images.githubusercontent.com/92685381/173197672-d2bdbd8f-5bd2-4ab9-b750-6dfa4ebde1ae.png)

**Comment by MaFi-Games** [comment]
I'm sorry but we deal with English tickets here only. For translation corrections check out https://translate.captain-of-industry.com/projects/captain-of-industry/game/
