### ISSUE TITLE
Right-click to load recipe doesn't work in informational building windows 

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#312]
**Describe the issue**
If you right click on an item inside a recipe line, the cookbook opens up as expected. But if you right-click on an item which is being displayed as a status, nothing happens.

**Expected behavior**
I expect that right-clicking on an item, anywhere, opens the cookbook.

**To Reproduce**
1. Place down a chicken farm.
2. Left-click the farm to open the information panel
3. Attempt to right-click any of the icons for 'Animal feed', 'water', 'eggs', 'chicken carcass'
4. Place down High-pressure turbine and open information panel.
5. Attempt to right-click any icons in the 'Output' and 'Input' sections.

**Additional context**
 - Game version: 0.4.3

**Comment by JamieRCHI** [comment]
Yes. I put a suggestion about this on the Suggestion site. 
One should be able to right-click things and either open a new dialog or see a context dropdown that would allow you to select what you want to do.

**Comment by JamieRCHI** [comment]
Thank you.
