### ISSUE TITLE
Vehicle recovery fails when the vehicle is stuck next to a vehicle depot.

### ISSUE THREAD

**Issue by BertusVanZyl** [MaFi-Games/Captain-of-Industry-issues#314]
**Describe the issue**
When a truck is stuck, and it is also close to a vehicle depot, recovering the vehicle spends the unity, but the vehicle just stays where it is, since it is already close to a vehicle depot.

**Expected behavior**
Vehicle should not be stuck after recovery.

**To Reproduce**
1. Trap a vehicle close to a vehicle depot.
2. Recover the vehicle.

**Comment by MaFi-Games** [comment]
Thanks for reporting. This has been fixed in one of our previous patches
