### ISSUE TITLE
pickup's going back and forth

### ISSUE THREAD

**Issue by GeertJanVanDerWolf** [MaFi-Games/Captain-of-Industry-issues#317]
**Describe the issue**
pickup's start moving back and forth. They have space to move around. 

**Expected behavior**
Standing still waiting for the next assignment or driving or displaying a error message.

**To Reproduce**
1. Unzip and load attached save ...
2. Do ???
3. Strange thing happens with the pickup's

**Additional context**
 - Game version: ea 0.4.3.

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
[save_22-06-11_11-50-32_00_002.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8885624/save_22-06-11_11-50-32_00_002.zip)
[22-06-12_09-28-14_2282.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8885627/22-06-12_09-28-14_2282.zip)

**Comment by MaFi-Games** [comment]
I loaded the save and I can't see any vehicles moving back and forth. Just vehicles doing their job. Also nothing in the logs. Maybe we fixed that? Anyway closing. Feel free to open a new one if you can still reproduce and have some specific information.
