### ISSUE TITLE
Delete key shortcut does not work for transports

### ISSUE THREAD

**Issue by TheWyrdsmith** [MaFi-Games/Captain-of-Industry-issues#32]
Current behaviour in v0.2.8:
While holding a smoke stack blueprint, pressing delete cancels placement and puts the user into bulldoze mode
While holding a pipe or molten channel blueprint (before any item is placed, not in the "next waypoint" mode), pressing delete does nothing

Expected behaviour:
Pressing delete while before first transport placement takes the user straight to bulldoze mode, as it does for other buildings

**Comment by MaFi-Games** [comment]
Thanks for reporting, we will look into this.

**Comment by MaFi-Games** [comment]
This has been fixed in the upcoming beta release. Thanks for reporting!
