### ISSUE TITLE
'There is nothing to pick up' on cargo ship

### ISSUE THREAD

**Issue by camtarn** [MaFi-Games/Captain-of-Industry-issues#322]
My cargo ship that was bringing oil to the island suddenly decided to no longer work. I had recently had to demolish my oil dock and rebuild it elsewhere due to the dock getting blocked, but I think I saw a good few deliveries before the ship decided it had had enough. The cargo ship is currently saying 'There is nothing to pick up' despite the oil rig storage being full.

Unsurprisingly, this sent the island into a death spiral.

Save is here:

https://drive.google.com/file/d/1Rawd9WKhu_TXP8WhT5hwplJiBDd69HKJ/view

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.4a
