### ISSUE TITLE
World Map Repairs & Upgrades Display Bug

### ISSUE THREAD

**Issue by rathe** [MaFi-Games/Captain-of-Industry-issues#323]
Related to repair of World Map stations (Oil Rigs, Sulfur Mines, Quarts Mines, etc) while having multiple station repair jobs open. The shipyard falls out of sync with which actual repair jobs are still awaiting cargo, and provides an incorrect list. Attached images show my map (with the ship delivering cargo at the Quartz Mine, and a Coal Mine that is still unrepaired; no other stations require repair), and my Shipyard (with an Oil Rig and a Coal Mine awaiting cargo loading).

I am unsure if this happened because I forgot which station I had loaded cargo for, and delivered to another one with a smaller or equal requirement of the same resource (may have been the second Oil Rig, or a Settlement upgrade); or if I cancelled/switched ship loading while the shipyard was full. 

![Captain of Industry, Shipyard](https://user-images.githubusercontent.com/4379841/173250634-5840cec0-f081-4f0f-8365-721f5c99bbb6.png)
![Captgain of Industry, Map](https://user-images.githubusercontent.com/4379841/173250638-49db7a3a-ba8f-4c50-9d32-4af32dd8aa91.png)

**Comment by rathe** [comment]
Description inaccurate and screenshots invalid. I feel like there WAS a bug around this, but my examples provided are false. I have an Oil Rig Upgrade in process. Would delete this if I could.

**Comment by JamieRCHI** [comment]
On other Github projects I have usually been able to close issues I created myself. Maybe the settings are different in this project.
