### ISSUE TITLE
Overlays dialog covers Tools on lower left of screen after v0.4.3

### ISSUE THREAD

**Issue by JamieRCHI** [MaFi-Games/Captain-of-Industry-issues#324]
**Describe the issue**
When pressing the Layers button the Overlays dialog is placed on the lower left and cannot be moved. You now have no access to the Tools button unless you close the Overlays dialog.

**Expected behavior**
The Overlays Dialog should not cover other dialogs and I should be able to move it.

**To Reproduce**
1. Either click on the Layers Tool button or press the hotkey assigned to that tool.
2. Note that this always happens at game start and eventually corrects itself after playing the game for several minutes.

**Additional context**
Video set to 1920 x 1080 and also tried 3840x2160 with and without second minitor enabled. Bordered and Fullscreen tested.
User Interface was set to 80, 90 or 100 percent in 1920x1080. Higher resolution tested at 150 and 200.
Game version: v0.4.3 - Worked as expected in last version released.

**Comment by MaFi-Games** [comment]
Could you please let us know what is your screen resolution and what UI scale is set in the settings?

**Comment by JamieRCHI** [comment]
Video is set to 1920 x 1080. UI  was set to either 80 or 90 percent. 
Also sometimes click Layers before I unpause the game. 

I should regress this bug and check if it happens if I set to 100 percent and if I unpause before clicking on layers right after I start the game.

(I knew I forgot to do something.)

**Comment by JamieRCHI** [comment]
Seems to fix itself much quicker now. Checked with a new save, build v0.4.4. Just ordered the harvesting of 2 trees, and built the first log burner to coal . Then checked the Layers button and the Overlay dialog went to the proper place.

**Comment by MaFi-Games** [comment]
Thanks for reporting. I believe we have fixes this in one of our previous patches.
