### ISSUE TITLE
Can't scrap or recover tier 3 trucks when desitnation is unreachable

### ISSUE THREAD

**Issue by SwiftNicholas** [MaFi-Games/Captain-of-Industry-issues#327]
Can't scrap or recover tier 3 trucks when destination is unreachable. Click on buttons and nothing happens, had to disable destination to 'unlock' the truck and then buttons work.

**Comment by MaFi-Games** [comment]
Do you have a screenshot or save file of this happening?

**Comment by MaFi-Games** [comment]
Closing as not enough information provided
