### ISSUE TITLE
Circular logic on Vehicle Bays

### ISSUE THREAD

**Issue by SwiftNicholas** [MaFi-Games/Captain-of-Industry-issues#329]
When piping rubber or other things into a vehicle bay trucks will come and remove it from there and put it back into a storage unit, they will repeat this until the belts are disconnected and the vehicle bay is empty (or under a certain threshold) the vehicle bay needs the option to remove exports.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.4
