### ISSUE TITLE
Cooling Tower II

### ISSUE THREAD

**Issue by Adrian1Brown** [MaFi-Games/Captain-of-Industry-issues#33]
**Describe the issue**
The cooling tower II is present at the beginning of the game

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attach
<img width="569" alt="Screenshot_26" src="https://user-images.githubusercontent.com/9059689/135670247-590a0723-83b9-485c-bd35-b7536a691d77.png">
ed files.

**Comment by MaFi-Games** [comment]
Thanks for the report! This has been fixed in v0.2.8a.
