### ISSUE TITLE
Excavation for t3 is in-efficient

### ISSUE THREAD

**Issue by SwiftNicholas** [MaFi-Games/Captain-of-Industry-issues#330]
If there is a small amount of rock or dirt mined by T3 excavators the trucks will waste gas and time by returning to dump the material. If there is a way to assign trucks to materials or specific excavators at a mining site this coule be solved. 

Expected behavior here is tricky, I get that, but I would not expect a truck that holds 60 to take 5 of something without a setting to offset the behavior.

**Comment by lowstrife** [comment]
You can set a priority to what an excavator will pull out of the ground. But it's still an imperfect system. 

What would be awesome is if you could assign one or two T2 trucks to "misc loads". They will take that 1 dirt away instead of wasting a huge dump truck.

**Comment by MaFi-Games** [comment]
Happy to close this as resolved. This was improved as we introduced mixed cargo feature in Update 1.
