### ISSUE TITLE
Game Crashes as soon as the Population begins to starve on Save.

### ISSUE THREAD

**Issue by darbreed** [MaFi-Games/Captain-of-Industry-issues#332]
**Describe the issue**
I was playing as normal but when the day ends and the population begins to starve the game crashes. I have not been able to get past it.  If you unpause and do nothing the game will crash.

**Expected behavior**
For the game to continue and not crash.

**To Reproduce**
1. Load attached save '...'
2. Un Pause game and let the population begin to starve.
3. game crashes every time

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]
[Launch Crash save_22-06-13_01-42-40.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8889594/Launch.Crash.save_22-06-13_01-42-40.zip)

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thank you for your detailed report. We have found the issue and it will be fixed in the next patch! :)

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.4
