### ISSUE TITLE
Loading a second save crashes everytime

### ISSUE THREAD

**Issue by cw64** [MaFi-Games/Captain-of-Industry-issues#333]
**Describe the issue**
Loading another save when a game is already running crashes everytime.

**Expected behavior**
Loading a second game when a game is already running loads the game and the client doean't crash 

**To Reproduce**
Start client. Load or continue a previous save. When game is running load another save = crash.
Start client. Load or continue a previous save. When game is running exit back to the main menu, load another save = crash.

3. Strange thing happens '...'
Engine isn't terminating correctly

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]
0.4.2a

**Attachments**
[22-06-12_21-05-02_7324.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890017/22-06-12_21-05-02_7324.log)

If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`
[22-06-13_10-45-02_3481.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890022/22-06-13_10-45-02_3481.log)
[22-06-13_10-46-24_5921.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890023/22-06-13_10-46-24_5921.log)

[22-06-13_09-26-52_8642.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890020/22-06-13_09-26-52_8642.log)
[22-06-13_09-49-48_0210.log](https://githu
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890032/Player-prev.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8890034/Player.log)
b.com/MaFi-Games/Captain-of-Industry-issues/files/8890021/22-06-13_09-49-48_0210.log)
. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Hmm, I can see in the logs:
E 07:45:41,601 S862272 ~Mai: Could not allocate memory: System out of memory!

Could you  please share with us how much RAM do you have?

**Comment by MaFi-Games** [comment]
Closing as not enough information available.
