### ISSUE TITLE
Farm "Avg. Production / 60" incorrect values when including "Empty" schedule options

### ISSUE THREAD

**Issue by jkingry** [MaFi-Games/Captain-of-Industry-issues#334]
**Describe the issue**
With out "Empty" option
![image](https://user-images.githubusercontent.com/111865/173361078-872e739e-2fe9-49b7-916a-93d25052a813.png)

With "Empty" option
![image](https://user-images.githubusercontent.com/111865/173360796-f52520d0-24d4-45b9-95a9-15b2e2c97a8d.png)

![image](https://user-images.githubusercontent.com/111865/173358560-5a75a3cd-6fb5-4dee-839e-f204c331285d.png)

Selecting "Empty"  schedule option does not impact the "Avg. Production /60" yield number. 

**Expected behavior** && **To Reproduce**

See clip from @Nilaus
https://clips.twitch.tv/SlickTemperedBadgerPicoMause-XJgpBIRzGU5sqE37

- Select "Vegetables", "+", "Potatoes" as schedule,
->Then "Avg. Production /60" Vegetables = 10.8, Potatoes = 10.4

- Then  select "Vegetables", "Empy", "Potatoes" as schedule, this should add 3 months to the rotation, which should decrease "avg. production / 60", but it does not, Total rotation should be 10 months long now (4 + 3 + 3) vs 7, so expecting lower numbers.

It appears if `IsEmptyCrop` == `true` then `TotalRotationDurationDays` is not incremented correctly during `recomputeRotationStats` ;)

**Comment by Broodja** [comment]
Duplicate #200

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
