### ISSUE TITLE
Circular Reference for Microchips

### ISSUE THREAD

**Issue by Jay12121212** [MaFi-Games/Captain-of-Industry-issues#336]
**Describe the issue**
When i am trying to build microchips, in order to build red maintenance, all of the machines require a data center which in turn needs red Maintenance.  Thus there isn't a path forwards

**Expected behavior**
I expect the data center should be using Yellow maintenance or have a smaller earlier version of it in order to make microchips.

**To Reproduce**
With only Electronics II building, try to make a machine to make microchips, a data center is needed which requires red maintenance.

**Additional context**
 - Game version: 0.4.3

**Comment by zeox115** [comment]
I agree with this, I think the data centres should just use Maintenance II.

The end game production trees already seem quite difficult to access with the **11** stages for the microchip.

But that's just my opinion :). Your game rocks guys!
