### ISSUE TITLE
Pickup unable to reach Tree Harvester inside Housing I unit

### ISSUE THREAD

**Issue by Vazhi** [MaFi-Games/Captain-of-Industry-issues#339]
**Describe the issue**
Built a Housing I near where Tree Harvester was assigned to cut trees. The Tree harvester moved into the blueprint of the Housing I and now I cannot select it and pickups can't reach it so that it'll move on its own to find a tree.

**Expected behavior**
Tree Harvester should move out of locations unreachable by any Pickup if able to. If Tree Harvester cannot move to a clear line of navigation, there should be a way to reclaim it when you can't click directly on the vehicle.

**To Reproduce**
1. Load attached save 'save_22-06-14_01-09-29 Bug.zip]'
2. locate the Housing I units with a tree harvester inside.
3. Try to reclaim, move, or otherwise make use of the Tree Harvester, but cannot.

**Additional context**
 - Game version: 0.4.4

**Attachments**
[save_22-06-14_01-09-29 Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8896563/save_22-06-14_01-09-29.Bug.zip)
![treecutter](https://user-images.githubusercontent.com/10589311/173498355-ef0d747b-eacc-45e4-8c3a-37e4636bada5.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.

**Comment by alex7071** [comment]
Still happening. Built a farm ghost over a tree harvester, built it and because it has a tree, it didn't move out of the ghost and now it's not moving and cannot be selected. 
[stuckHarvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13692966/stuckHarvester.zip)
