### ISSUE TITLE
Repairing Oil Rig does not reset to do 2nd Rig

### ISSUE THREAD

**Issue by RMH-7597** [MaFi-Games/Captain-of-Industry-issues#34]
**Describe the issue**
When you have 2 Oil Rigs to repair and load the resources to repair the first one. When you repair the first one the game still thinks you have the resources loaded on your ship to repair the 2nd Oil Rig.

**To Reproduce**
1. Explore locations and find the 2 Oil rigs that require 120 Constrruction Parts 2 to repair.
2. Load the ship with 120 construction parts
3. Go repair the 1st Oil Rig (I repaired bottom left one)
4. Once repair complete return to home island
5. Click on Dock and it will show that items are ready to be delivered to Oild Rig for repair.
6. This will not work to repair Oil rig
7. You have to cancel repair task then select it again to be able to add resources to repaur Oil Rig.

**Expected behavior**
When repairing an Oil Rig that requires same resources as another Oil Rig. Game should reset the repair ready to select the next Oil Rig to be repaired. It looks like there is no reset or compleation of the task so the tasks still things it is running. It just moved to the next Oil rig but resources were not available.

**Additional context**
 - Game version: 0.2.8

**Attachments**
Files.zip added

This contains 4 screenshotrs and save game file. The save game file is at the point the issue is there and I have not reset the task.
There are multiple screenshots as I had this happen on a previous game and had not captured the details. So this is repeatable as I have had it twice now and followed the above steps to trigger it the 2nd time.
[Files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7270020/Files.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting, we need to look into this.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
