### ISSUE TITLE
Transport auto select does not work while snapping is off.

### ISSUE THREAD

**Issue by KYordanov** [MaFi-Games/Captain-of-Industry-issues#341]
**Describe the issue**
Transport auto select, form port arrows, does not work while snapping is off.

**Expected behavior**
Transport auto select is always active when I hover over port arrows and transports build menu is open.
**To Reproduce**
1. Open transport build menu and select a transport to build
2. Toggle snapping off -> press R
3. Unselect the choosen transport to build
4. Try to auto select transport by hover over port arrows
**Additional context**
 - Game version: 0.4.4

**Comment by asafteirobert** [comment]
This issue was driving me crazy; I didn't know what it was and was restarting the game thinking it's the only way to fix it.
Can be worked around by toggling snapping back on, but it's definitely an UX issue.

**Comment by MaFi-Games** [comment]
Thanks for report. We have fixed this in one of our previous updates.
