### ISSUE TITLE
Crash while starting a new game

### ISSUE THREAD

**Issue by Tidus084** [MaFi-Games/Captain-of-Industry-issues#343]
![Unbenannt](https://user-images.githubusercontent.com/107524183/173723549-9db689d1-e341-4db0-bf22-5a46434d944a.jpg)
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Closing as no information provided. Please file new ticket if you have more information.
