### ISSUE TITLE
Misplacing in Statistics

### ISSUE THREAD

**Issue by Dynortice** [MaFi-Games/Captain-of-Industry-issues#344]
**Describe the issue**
Liquid Nitrogen misplaced in statistics menu. It placed between Nitrogen and Oxygen for me.

**Expected behavior**
Should be placed between Limestone and Mechanical Parts as all other products sorted in alphabetical order.

**To Reproduce**
1. Research "Research Lab III" technology.
2. Open statistics menu.

**Additional context**
 - Game version: 0.4.4

**Attachments**
<img width="389" alt="image" src="https://user-images.githubusercontent.com/10525018/173735852-a3073f61-01fa-4b18-8069-fdf45975cd56.png">

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
