### ISSUE TITLE
All Iron consumed in Vehicles Depot 3 for no reason

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#345]
**Describe the issue**
I've scheduled some work for my vehicle depot and shortly after got an alert for low Iron supply (which I usually have plenty of). I've checked trucks' routes and all end in VD3 for no reason. No Iron is needed here for work while almost 8K was dumped and seems like every new production is being transported there.
![obrazek](https://user-images.githubusercontent.com/19796452/173775950-4ea7f0d1-3331-4ae8-a3d3-beb3dd081b70.png)
Seems like it somehow exists somewhere as the quantity in the chart still shows it, however in pinned, it's not available.
![obrazek](https://user-images.githubusercontent.com/19796452/173779545-26933261-66eb-4d2a-a67f-1f84d3bac8b1.png)

**Expected behaviour**
Accept only needed resources.

**To Reproduce**
Load save and check trucks from my iron production to the vehicle depot.

**Additional context**
0.4.4A

**Attachments**
[22-06-15_09-34-32_1715-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8907184/22-06-15_09-34-32_1715-autosave.zip)

**Comment by MaFi-Games** [comment]
Would you know when approximately did you build that depot? We fixed a bug in this behavior few days ago but it does not apply to depots that were already built and scrapped some vehicles. I just want to check to see if this is a new bug or not. Thanks!

**Comment by ParanoikCZE** [comment]
A long time ago, so I think we can ignore this, I'll load later save and rebuild depot. Thanks for the info.

**Comment by MaFi-Games** [comment]
Cool, please let us know if it reappears on a newly built depot, that would be a big issue.

**Comment by ParanoikCZE** [comment]
Looks good, closing.
