### ISSUE TITLE
Captain of INduustry Sand bug

### ISSUE THREAD

**Issue by qris1988** [MaFi-Games/Captain-of-Industry-issues#346]
if I want to mine sand on the beach in the game, the water still washes through. no matter whether I dump around it with bulk material or not. 

vehicles that are in newly built buildings can not be reset.

the glass processing in the game comes a little too late in my opinion.

**Comment by MaFi-Games** [comment]
We have improved flooding algorithm and  water detection in one of our previous patches. Should be better now. Thanks!
