### ISSUE TITLE
Furnace recipe stuck after upgrade

### ISSUE THREAD

**Issue by mattcarmanSASES** [MaFi-Games/Captain-of-Industry-issues#347]
**Describe the issue**
When upgrading a blast furnace to level 2, the furnace is still requesting ingredients from the level 1 recipe (ie copper ore), with no way to deselect it. If this building is unreachable by vehicle it will cause the vehicle to become unable to route

**Expected behavior**
The furnace should explictly deselect the unavailable recipie

**To Reproduce**
1. Load attached save [save_22-06-15_00-49-59.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8909245/save_22-06-15_00-49-59.zip)
2. check stuck vehicles
3. pause applicable furnace if required

**Additional context**
 - Game version: [e.g. 0.4.4a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
