### ISSUE TITLE
Cargo ship not unloading after upgrade to cargo dock 2

### ISSUE THREAD

**Issue by RMH-7597** [MaFi-Games/Captain-of-Industry-issues#35]
**Describe the issue**
Cargo ship docked with some Oil in the bunkers on the ship. After upgrade to Cargo Dock 2 the Oil is not unloaded.

**To Reproduce**
1. Cargo ship docked with oil onboard
2. Upgrade cargo dock to level 2
3. Upgrade and add 2 additional fluid module M
4. Oil remains on Cargo ship even though space available

**Expected behavior**
Ship should unload oil as more space now available

**Additional context**
 - Game version: 0.2.8

**Attachments**
Files.zip added
Contains:
Screenshot showing Oil in Cargo Ship
Screenshot showing spce in fluid module
Save game file
[Files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7270298/Files.zip)

**Comment by RMH-7597** [comment]
After I removed the 2 fluid modules that were no accepting oil (original 2 on the ship). The cargo Ship then left to collect more oil. Rebuilding the original 2 Fluid Modules as M type they then worked as expected and oil was collected and unloaded OK.

**Comment by MaFi-Games** [comment]
Thanks for the report, we will look into this.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
