### ISSUE TITLE
Unity Boosted Buildings' Icon doesn't show upon loading saved game

### ISSUE THREAD

**Issue by zuffdaddy** [MaFi-Games/Captain-of-Industry-issues#350]
**Describe the issue**
When loading a saved game, any building that was boosted with Unity does not have the unity icon on said building.

**Expected behavior**
Unity icon to always appear on unity boosted buildings

**To Reproduce**
1. Load attached save
2. Check the assembler that is producing construction parts
3. Notice it is boosted, yet the icon isn't there

**Additional context**
 - Game version: 0.4.4a,

**Attachments**
Save file: [new4.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8910331/new4.zip)
Screenshot: 
![coi_unity_bug](https://user-images.githubusercontent.com/99009/173853575-94c23a22-4932-4adb-95e2-8430a122f1a3.png)

**Comment by zuffdaddy** [comment]
Probably, also I just noticed Prioritized buildings' icons do not show up either

**Comment by MaFi-Games** [comment]
Thanks for you report. This happens due to migration to v0.4.4a however we have improved the migration code and it will land in the next patch. However if migration was done and game was saved in v0.4.4a that will unfortunately not restore the notifications.

**Comment by CaptainLame** [comment]
Got a variant of thise, Unity icons floating in random places:
![image](https://user-images.githubusercontent.com/17200948/173981246-32aca0cb-f3f9-404d-8b47-2c92cf34a0b5.png)
When that assembler is boosted:
![image](https://user-images.githubusercontent.com/17200948/173981342-27963d5d-fde8-4132-acab-c57e7d6f82db.png)

![image](https://user-images.githubusercontent.com/17200948/173981274-46faa537-8dda-46d1-9791-a8cb834c2398.png)

**Comment by kwolkan** [comment]
+1 for the above... I have unity icon in the middle of the field (I think I had an assembler there, but it has been long removed) and another on top of existing assembler (which was removed in the past as well). I suspect when unity boosted building is deleted the icon remains. Loading the game doesn't help unfortunately. current ver: 0.4.4b

**Comment by kwolkan** [comment]
my issue is fixed in 0.4.4c. thanks and well done 🥇

**Comment by zuffdaddy** [comment]
Can confirm, thanks team!
