### ISSUE TITLE
No video clips in tutorials

### ISSUE THREAD

**Issue by lsaranto** [MaFi-Games/Captain-of-Industry-issues#351]
**Describe the issue**
In tutorials I have blank space were I believe should be video clips.

**Expected behavior**
According to Let's play videos on Youtube etc there should be video clips.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
0.4.4a
I play in window mode. Maybe that has something to do with it.
Also Windows 7.

**Attachments**
![image](https://user-images.githubusercontent.com/52409168/173901946-13830549-5c84-4473-b3d7-2e7c0aa3fdc5.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
