### ISSUE TITLE
Cant scroll the shipyard

### ISSUE THREAD

**Issue by daltay15** [MaFi-Games/Captain-of-Industry-issues#354]
**Describe the issue**
With many items under the world map repairs/upgrades I can't scroll down and get to the one I want.

**Expected behavior**
Able to scroll the list.

**Attachments**
![image](https://user-images.githubusercontent.com/77849115/173996942-68f75074-b1ae-482a-93d8-8eae5884a3b2.png)

**Comment by MaFi-Games** [comment]
Thanks for reporting. This was fixed in one of our previous patches.
