### ISSUE TITLE
Mismatch of belts

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#356]
Hi Marek and Filip,

the eggs from the chickenfarms have a mismatch belt. The chickenfarm output of the egg exit is consider as a flat belt outgoing belt but the input of the food market II to get the eggs in is considers to be u-shape. Would be nice if you can squezz that fix into your next patch.

Thx. P.s im very surprise nobody found that one yet ;)

[belt mismatch.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8917668/belt.mismatch.zip)

**Comment by gergelycsata** [comment]
Hey I have this very exact issue in the newest patch of the game... I cant reopen the issue.
