### ISSUE TITLE
T3 dump truck refueling at diesel storage over fuel stations

### ISSUE THREAD

**Issue by popboat** [MaFi-Games/Captain-of-Industry-issues#357]
**Describe the issue**
T3 dump truck is getting stuck trying to reach diesel in fuel storage that it cannot path to, instead of using much closer fuel station

**Expected behavior**
Vehicle should prioritise closest available fuel storage / fuel station

**To Reproduce**
1. Have liquid storage with diesel which T3 truck cannot path to
2. Allow export on the storage with diesel
3. T3 truck will get stuck unable to path to storage regardless of available Fuel Stations

**Additional context**
 - Game version: 0.4.4b -

**Attachments**
[T3 dump truck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8917888/T3.dump.truck.zip)
![](https://media.discordapp.net/attachments/977273173638799440/986896251826090024/unknown.png)

**Comment by MaFi-Games** [comment]
We have improved this in one of our previous updates by providing fuel stations with higher export priority (that does not always work 100% if some storage is much much closer). Please file a new issue if this still persists.
