### ISSUE TITLE
Swapped colors for Naptha and Fuel Gas

### ISSUE THREAD

**Issue by mnoreke** [MaFi-Games/Captain-of-Industry-issues#358]
**Describe the issue**
The colors appear swapped for Naptha and Fuel Gas when in storage containers.

**Expected behavior**
Color should match icon

**To Reproduce**
1. See attached image

**Additional context**
 - Game version: 0.4.4b

**Attachments**
<img width="452" alt="temp" src="https://user-images.githubusercontent.com/5225366/174072238-2952375f-693d-4bda-9fc3-b554685bde27.png">

**Comment by MaFi-Games** [comment]
This has been fixed in previous patches. Thanks!
