### ISSUE TITLE
Excavators stop refuling before Fueling Depot is complete

### ISSUE THREAD

**Issue by PTTG-ACTUAL** [MaFi-Games/Captain-of-Industry-issues#36]
**Describe the issue**
When you place a blueprint for a fueling depot, all excavators will stop getting their own fuel. This can be a problem if it takes a long time to build the depot, allowing the excavators to run out of fuel and potentially soft lock the game.

**To Reproduce**
1. Have 0 fueling depots and at least one working excavator.
2. Place a blueprint for a fueling depot, then pause it.
3. Wait for excavator to run low on fuel...
4. Excavator will run out of fuel and stop.

**Expected behavior**
Excavators should change behaviors when the number of completed depots is greater than 1.

**Additional context**
 - Game version: Alpha 0.2.9

**Attachments**
N/A

**Comment by MaFi-Games** [comment]
That is good point, we will look into this.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
