### ISSUE TITLE
Recipes showing as locked even tho they are actually unlocked and being used.

### ISSUE THREAD

**Issue by NZ-Wanderer** [MaFi-Games/Captain-of-Industry-issues#366]
As the title says, in recipes there are items showing as locked when in-fact they should be unlocked. as an example here are pictures showing it...
![image](https://user-images.githubusercontent.com/447796/174401013-b4e55c9e-7e33-4c16-bda1-99db9019a37f.png)
![image](https://user-images.githubusercontent.com/447796/174401045-449a87e4-30c2-4e3a-adb7-a11fbd35e8d7.png)
![image](https://user-images.githubusercontent.com/447796/174401069-23b6e032-a41b-4553-ae24-f8960fe58c5b.png)

**Comment by PaludanC** [comment]
![image](https://user-images.githubusercontent.com/10159539/174401255-de04a621-4b67-40d1-a4a4-b9047bb719b5.png)
From full unlcok tree

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
