### ISSUE TITLE
2 trucks missing.  Maybe spawned underground?

### ISSUE THREAD

**Issue by zytukin** [MaFi-Games/Captain-of-Industry-issues#37]
**Describe the issue**
Built 2 large trucks in the vehicle depot, set them to work for a mine, but they never went to the mine.  Clicking on them in the vehicle list shows they are still at the vehicle depot.  Destroying the vehicle depot does not reveal the trucks and clicking in the vehicle listing still puts the camera at the spot where the vehicle depot had existed.  Was able to build more trucks without issue but those first 2 trucks are still 'missing'.  Wondering if they spawned underground.

**To Reproduce**
1. Load attached save
2. Click the vehicle management and click though the large trucks.  4 exist and 2 will be found on the island next to the dock, the other 2 will put the camera at a bare spot of land (where the vehicle depot and research lab used to be).

**Additional context**
 - Game version: 0.2.9
[Game 6.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7272417/Game.6.zip)

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta patch, thanks for reporting!
