### ISSUE TITLE
Game released before it was ready

### ISSUE THREAD

**Issue by earl2586** [MaFi-Games/Captain-of-Industry-issues#371]
**Describe the issue**

Are you serious, Github!!

Are you like starting out in a basement or garage?

I don't have time to write a book.

So many problems with the trucks.

They just stop working.

Not blocked by anything.

Do not fallow the priory.

I work 6 days a week.

I like to relax a little before I hit the hay.

I play a game or to.

If you don't fix it soon,

I will get my money back from Steam.

Earl...

**Comment by JamieRCHI** [comment]
This is an early beta release. Did you read the Steam Valves statement when you bought the game?
Even if the game was at 1.0 plus release, this is extremely rude.
Moderators please close and lock this.

**Comment by MaFi-Games** [comment]
We are sorry to hear that you are having issues but your report does not help us with investigation. If you are having issues please file a proper report that describes what is wrong, ideally with attached save file so we can take a look.

If you need some help, read in-game tutorials carefully, or you can ask concrete questions to our wonderful community at our Discord server: https://discord.gg/JxmUbGsNRU

**Comment by earl2586** [comment]
Its all over the net about players having problems with your the trucks.

Ok, I played one game for four hours.

The two trucks by the Tree Harvester went down first.

You click recover and then you have to re-assign them.

This don’t last for long and then you got to do it again.

After a short time they stop and you click on re-assign nothing happens.

You click on scrap and nothing happens.

That truck is stuck in the game and theirs now way to move it or get rid of it.

None of the trucks have any material in them.

The Maintence Depot is full.

All the trucks have gas.

So what’s going on ??

Earl..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by earl2586** [comment]
Issue#371

When I got the game. Steam didn’t tell me it didn’t work wright.

Is not rude its just giving you the facts.

Instead of helping me.

This is what you said.

This is an early beta release. Did you read the Steam Valves statement when you bought the game?
Even if the game was at 1.0 plus release, this is extremely rude.
Moderators please close and lock this.
Moderators please close and lock this.

Wow that was fast.

Shut me up.

Earl..

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
