### ISSUE TITLE
Disabling "Allow Partially Loaded Trucks" prevents trucks from delivering lab equipment to research facilities.

### ISSUE THREAD

**Issue by BLADERUNNER1987** [MaFi-Games/Captain-of-Industry-issues#375]
**Describe the issue**
I've noticed that when disabling the "allow partially loaded trucks" option, that the trucks will not deliver lab equipment to the research facilities.

**Expected behavior**
Disabling the option (force full load) should just mean that a truck will pickup the lab equipment from an available storehouse and deliver it when a full load of lab equipment or more is available to be delivered to any research facility

**To Reproduce**
1. Load my save
2. Disable the option "allow partially loaded trucks"
3. Monitor the behavior between the lab equipment stored in the storehouse and the available lab equipment in the research facilities.

**Additional context**
 - Game version:  0.4.4c.
 - Cheat engine is being used for speed increase only, no modification of values.

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
[SAVEGAME.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8934624/SAVEGAME.zip)

**Comment by MaFi-Games** [comment]
This has been fixed in v0.4.7b, thanks for the report.
