### ISSUE TITLE
several connectet Pipes, no flow

### ISSUE THREAD

**Issue by ArGolarium** [MaFi-Games/Captain-of-Industry-issues#376]
**Describe the issue**
If you connect several Pipes together, sometimes the flow just stop, the destination Pipe is empty. It happens with a splitter/connector as well.

**Expected behavior**
The flows comes together without stucking.

**To Reproduce**

**Additional context**
 - Game version: 0.4.4C

**Attachments**

![Full pipe](https://user-images.githubusercontent.com/107788850/174471590-5be4a933-34e0-4d18-8c2e-9ea53b0629b9.jpg)
![empty pipe](https://user-images.githubusercontent.com/107788850/174471594-3a5e7ff6-8f84-4627-a312-6d46b2591f77.jpg)

[Bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8934963/Bug.zip)

**Comment by utdrmac** [comment]
It is possible that you did not "connect" them. Make sure you see the green icons otherwise they won't connect.

**Comment by ArGolarium** [comment]
Yes, rebuilt the whole System, it works for a time, but then, it stuck again.

**Comment by utdrmac** [comment]
Are you sure there's not some other output which is being blocked? Check the status of the machine. Make sure it doesn't say 'Missing Input' or 'Output Full'.

**Comment by ArGolarium** [comment]
Ok, solved the problem. A Gasboiler with several recipe sometimes produce Carbon dioxine into the same Pipe... sorry for false alarm. Really nice game by the way!
