### ISSUE TITLE
Cargo Depot upgrade not working correctly

### ISSUE THREAD

**Issue by maxhawk** [MaFi-Games/Captain-of-Industry-issues#38]
**Describe the issue**
When upgrading Cargo Depot(2) to Cargo Depot(4) after all materials are delivered upgrade animation plays, but model isn't updated and upgrade button is still displayed and is working. Highlights for additional modules do appear.  Saving and loading fixes Depot model itself, but upgrade button is still visible. Docked ship stays as small Cargo Ship, but moves forward so original two modules dont allign with reservoirs on ship.

**To Reproduce**
1. Load attached save
2. Upgrade Cargo Depot near Shipyard or near Coal Deposit (Cargo Depot in the middle works OK)

**Expected behavior**
Upgraded Cargo Depot has correct model and not displaying Upgrade button. Cargo ship upgraded to larger version or modules that doesn't fit ship should not work.

**Additional context**
 - Game version: 0.2.9

**Attachments**

[CoI_Dock2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7274114/CoI_Dock2.zip)

**Comment by MaFi-Games** [comment]
Thanks! Thanks you your log file we have found the issue. It will be fixed in our next patch! In the meantime this happens when upgrading a depot that does not have all the 2 modules so temporary fix to avoid that is to always upgrade depot with 2 modules.
