### ISSUE TITLE
Truck carrying small amount of wood even with partially loaded trucks disabled

### ISSUE THREAD

**Issue by michalrehacek** [MaFi-Games/Captain-of-Industry-issues#381]
**Describe the issue**
Even when the option to use partially loaded trucks is disabled, there are somehow a lot of trucks (tens of them) carrying just a few items of wood. This eventually saturates the truck network.

I do not 100% know what caused this. I was deconstructing some areas, but they didn't contain that many options to pick up a few wooden logs. I believe this is connected to setting a depot to import wood and keep it at 100% of capacity; when you load the attached save, it is the 3rd depot from the bottom left from the coal mine (you'll see it as a lot of trucks are heading that way). The cause is however my speculation only.

**Expected behavior**
The option to use partially loaded trucks should either be respected, or when it's not possible, it should not cause a significant breakdown in the carrying capacity of the whole truck network.

**To Reproduce**
1. Load attached save from the zip
2. Observe the tens of trucks next to the coal mine (the save is created with those trucks in view)

**Additional context**
 - Game version: v0.4.4c

**Attachments**
- zipped save: [save-partial-wood-trucks.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8936084/save-partial-wood-trucks.zip)
- screenshot: ![save-partial-wood-trucks](https://user-images.githubusercontent.com/47793479/174494100-aaff865e-b9f3-49e3-80b4-66e6011276de.jpg)

**Comment by MaFi-Games** [comment]
I believe we have fixed this issue some time ago when we stopped enforcing partial trucks for deconstruction. Please file a new ticket if it happens again.
