### ISSUE TITLE
recipes with Assembly (robotic) and PCB are not shaded in recipes book

### ISSUE THREAD

**Issue by mathsk** [MaFi-Games/Captain-of-Industry-issues#382]
**Describe the issue**
Assembly (robotic) I and II are  not displayed as blocked in the recipes book for all recipes

**Expected behavior**
Assembly (robotic)  should be displeyd as blocked until we finish the research "Construction IV"

**To Reproduce**
1- new game
Create a new game and search "Copper" un the recipes book.
The recipe for PCB is not blocked

2- when I can see a lot of recipes, I found somme recipes with Assembly (robotic) not blocked. The list could be not exhaustive :
- Disinfectant => Medical supplies (CONSUMPTION)
- Electronics II => Vehicle Parts III (CONSUMPTION)
- Glass =>  Vehicle Parts II (CONSUMPTION)
- Glass =>  Lab equipment III (CONSUMPTION)
- Glass =>  PCB (CONSUMPTION) [Assembly (robotic) II]
- Lab equipment II =>  Lab equipment III (CONSUMPTION)
- Lab equipment III => Lab equipment III  (PRODUCTION)
- Medical equipment => Medical equipment  (PRODUCTION)
- Medical equipment=> Medical supplies (CONSUMPTION)
- Medical supplies =>  Medical supplies (PRODUCTION)
- Plastic =>  Medical equipment  (CONSUMPTION)
- Plastic => PCB (CONSUMPTION) [Assembly (robotic) II]
- Steel => Vehicle Parts II (CONSUMPTION)
- Steel => Medical supplies (CONSUMPTION)
-  Vehicle Parts =>  Vehicle Parts II (CONSUMPTION)
-  Vehicle Parts II  =>  Vehicle Parts II  (PRODUCTION)
-  Vehicle Parts II =>  Vehicle Parts III (CONSUMPTION)
-  Vehicle Parts III  =>  Vehicle Parts III  (PRODUCTION)

**Additional context**
I 20:51:15,859 S------ ~Mai: UTC now: 2022/06/19 20:51:15
I 20:51:15,859 S------ ~Mai: Version: 0.4.4c (Early Access)
I 20:51:15,860 S------ ~Mai: Current culture: fr-FR
I 20:51:15,860 S------ ~Mai: Platform: 2
I 20:51:16,189 S------ ~Mai: Steam client connected
I 20:51:16,219 S------ ~Mai: Default language 'English'

**Attachments**
1- new game:
![image](https://user-images.githubusercontent.com/76636030/174500977-b7d3a5d8-597a-4da9-b352-a379a75ad9f7.png)

2- my game, example with plastic:
![image](https://user-images.githubusercontent.com/76636030/174501023-ccbc9446-9fd2-46a3-8a48-e9789380f4f5.png)

**Comment by mrpoppy** [comment]
Agree, this is confusing. Also, why does Research Lab IV unlock assembly robotic recipe when you don't get robotic assembler until 7 tiers later. Just adds to the confusion.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
