### ISSUE TITLE
Trucks can drive down sand landslides and get suck. 

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#385]
Digging a sand pit. Natural landslide just happened, which must have created a shallow enough slope to allow a truck to drive down it.

A truck did. And now it's stuck (and requires unity to get it un-stuck). 

![image](https://user-images.githubusercontent.com/65734844/174506119-bb47fc3b-721c-46d7-a17c-0438bc3ccf68.png)

Considering my dumping area is on the opposite side of the ramp, whenever I get a landslide of sand (sandslide?), this may end up happening repeatedly requiring the use of unity to un-stuck the trucks.

[Stuck Truck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8936697/Stuck.Truck.zip)

**Comment by utdrmac** [comment]
Use retaining walls to prevent landslides. ;)

**Comment by MaFi-Games** [comment]
I think the alterantive way you have in the image isn't working because there is a tree in the middle. This all looks like working as intended to me. It is part of the game to mine in a way to avoid landslides that prevent vehicle access.
