### ISSUE TITLE
Transformers crash the game

### ISSUE THREAD

**Issue by qxking** [MaFi-Games/Captain-of-Industry-issues#388]
您好，我是一名中国的游戏爱好者，在多次尝试并验证后发现社区中如果建造变压器有大概率导致游戏崩溃，具体为什么还没有搞清，希望官方可以修复该问题。
Hello, I am a Chinese game enthusiast. After many attempts and verifications, I found that if the building of transformers in the community has a high probability of causing the game to crash, the specific reason has not been figured out. I hope the official can fix the problem. (by Google Translate)

**Comment by MaFi-Games** [comment]
I'm sorry but without any proper repro steps it is hard for us to fix this. Can you provide logs or save file of it crashing?

**Comment by TheRealLoeFFEl** [comment]
HI, it happend that I have the same Problem. I atached the corresponding save game. 

[Transformer Crash Save 5.6.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8985173/Transformer.Crash.Save.5.6.zip)
