### ISSUE TITLE
Lieferwagen-Probleme

### ISSUE THREAD

**Issue by OilForFuture** [MaFi-Games/Captain-of-Industry-issues#389]
**Describe the issue**
Die Lieferfahrzeuge erreichen ihr Ziel nicht. Sie wurden zurückgesetzt oder verschrottet als sie sich nicht selbst neu ein Ziel zugewiesen haben.

**Expected behavior**
Es wäre schön, könnte man die nicht zugeteilten Fahrzeuge besser koordinieren/steuern, wo sie Tanken fahren oder Ladung aufnehmen sollen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Sorry, this does not seem really actionable. Either the translator isn't doing a good job or this is just a general suggestion on making things better.
