### ISSUE TITLE
Excavator on the list, but missing and not showing up for work

### ISSUE THREAD

**Issue by ThePiachu** [MaFi-Games/Captain-of-Industry-issues#39]
**Describe the issue**
I built a few excavators (with unity). One of them turned out to be some kind of ghost excavator - it counts as being on the list of excavators, I can assign it to work, BUT it never shows up to work and doesn't dig anything. I can't find it to figure out what is wrong with it.

**To Reproduce**
???

**Expected behavior**
All excavators should be available for work.

**Additional context**
 - Game version: The one from September 22nd-ish

**Attachments**

[Saves.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7274356/Saves.zip) - all of them should have the same excavator being the issue. It used to work on the sand, but later went to work on coal.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
