### ISSUE TITLE
Port access blocked but not really

### ISSUE THREAD

**Issue by SeppiFox** [MaFi-Games/Captain-of-Industry-issues#390]
**Describe the issue**
After accidentally dumping next to the port it constantly displays an error that the ship cannot depart however it can depart normally and the button to clear the area around the port does nothing except remove the unity cost.

**Expected behavior**
Pressing the clear area button clears the area and the error message is removed.

**To Reproduce**
1. Open save file.
2. Press the clear port area button.
3. Nothing happens except unity is removed.

**Additional context**
 - Game version: 0.4.3 & 0.4.4 a/b/c

**Attachments**
![22-06-20_20-52-06_9618_photo](https://user-images.githubusercontent.com/45108808/174664478-a9fba2ce-5335-49a8-8e06-3a21b9d457ef.jpg)
![Port](https://user-images.githubusercontent.com/45108808/174664620-7695ffc8-6cca-4faa-8a07-ab6cf521d398.png)

[save_22-06-20_21-02-29.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8943101/save_22-06-20_21-02-29.zip)

**Comment by Boneslice** [comment]
Bump on this issue. I had the same problem occur. Can't dig material out of the water that was dumped to clear port access. Can't send ship on exploration missions till this is fixed.

**Comment by MaFi-Games** [comment]
Just tried it out and you just need to perform the action multiple times. We have explained this in a tooltip above but I'm just adding extra tooltip for the button itself to be extrra sure.
