### ISSUE TITLE
settlement module : recycables not working

### ISSUE THREAD

**Issue by interal227** [MaFi-Games/Captain-of-Industry-issues#396]
i'm not getting any input or output from this building
tried to rebuild and reconnect but no change
savegame : 
[2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8948104/2.zip)

**Comment by MaFi-Games** [comment]
You need to send some products like household goods into the settlement to get recyclables back. It does not make them out of thin air.

**Comment by kbolino** [comment]
> You need to send some products like household goods into the settlement to get recyclables back. It does not make them out of thin air.

In that case, I think the Recyclables Collection building unlocks too early. The Recycling technology, which currently unlocks it, is in the middle of research tier II while Household Goods is in the middle of tier III.

At the very least, I think the building description should indicate that it won't be useful as soon as you unlock it.

**Comment by MaFi-Games** [comment]
Documentation was improved.
