### ISSUE TITLE
Games cause computer systems to crash

### ISSUE THREAD

**Issue by c00100c** [MaFi-Games/Captain-of-Industry-issues#397]
**Describe the issue**
Games cause sudden shutdown of computer system programs

**Expected behavior**

**To Reproduce**

1. Open the Steam client and run the game
2. ①If I change the VSync count in the settings menu, the computer system is forced to shut down
3. ②If I play the game normally, after 30-60 minutes of normal game operation, my computer system programs will be suddenly closed, but my computer runs other programs without any problems

**Additional context**
 - Game version: [0.4.5a, ]
 - Language Environment：[ Simplified Chinese ]
 - System version：[ Win10 Professional Edition  Version No.21H2 ]
 - Operating system internal version:19044.1766

**Attachments**

**Comment by vitorboschi** [comment]
It looks like you have heating problems in your machine. Disabling VSync normally makes the game demand more resources (generates more heat), which could explain why it crashes your computer faster that way.
Other applications might be less demanding, so the problem does not manifest (or take much longer to do)

**Comment by MaFi-Games** [comment]
Please provide your logs

**Comment by c00100c** [comment]
Thank you for your reply, my problem has been solved
The reason is that my computer's discrete graphics card is broken, because the game is well optimized, I never found the game is running with the core graphics card
good luck with your development work, thanks!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MaFi-Games/Captain-of-Industry-issues"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月9日(星期六) 凌晨5:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MaFi-Games/Captain-of-Industry-issues] Games cause computer systems to crash (Issue #397)





 
Please provide your logs

**Comment by MaFi-Games** [comment]
Thank you for the update. Closing.
