### ISSUE TITLE
Input is taken from joysticks when undesired

### ISSUE THREAD

**Issue by mloftis** [MaFi-Games/Captain-of-Industry-issues#4]
**Describe the issue**
Plug in something like say flight pedals, or any joystick device.  Flight pedals specifically have brakes which are always at one end unless being pushed, a throttle does the same thing.  CoI takes the input and uses it as pan input.

**To Reproduce**
1. plug in joystick device like a throttle or rudder pedals w/ brakes
2. watch CoI pan randomly and be unable to pan with keyboard.

**Expected behavior**
Either ignore joysticks entirely, or, if gamepad support is desired there must be an option to select/disable.

**Additional context**
0.2.0

**Comment by mloftis** [comment]
Specifically this occured with a pair of Saitek (now logitech I think) Flight Rudder Pedals.

**Comment by Str3amR** [comment]
Probably related to https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/1

**Comment by mloftis** [comment]
Yup, same related issue.   It's capturing all controllers.

**Comment by mloftis** [comment]
Normally I leave my pedals plugged in because it's a bear to crawl under and find the right USB cable.

**Comment by MaFi-Games** [comment]
Sorry about this, I will be looking into it. Unity is trying to be too "smart".

**Comment by MaFi-Games** [comment]
Duplicate of #1
