### ISSUE TITLE
Unit storage building not having Microchips as an option for storing after producing them

### ISSUE THREAD

**Issue by donsmoore** [MaFi-Games/Captain-of-Industry-issues#400]
**Describe the issue**
None of the unit storage buildings have an option for storing "Microchips Stage NN"

**Expected behavior**
There was the option to store "Microchips stage NN" option a few hours ago before I had to restore a previous save but now they are gone even though i am producing them.

**To Reproduce**
1. Load attached save no_microchip_storage
2.Try to set a storage unit to accept microchip stage 1a and it does not have that option

Game breaking bug for me

**Comment by donsmoore** [comment]
![20220621134407_1](https://user-images.githubusercontent.com/31714868/174874750-2e93787c-0a19-4ca2-8574-6d8bf7651909.jpg)

Screenshot of the issue...

**Comment by Lexatris** [comment]
I was able to get around not storing microchips by using a Flat Sorter and a Flat Balancer. On the output of the microchip machine put the Flat Sorter and sort for all the microchips. This will sort out the finished product to be able to store in a building while sending back in the unfinished microchips. On the Flat Balancer you have the silicon wafer input and then the microchip input. Put the microchip input on priority so anything incoming on that input will be put back into the microchip machine first. After that it should be self sustaining to produce microchips. 
![image](https://user-images.githubusercontent.com/107374834/174885379-0defb9bf-dd76-4019-aaaf-89595a2ad0fa.png)

**Comment by donsmoore** [comment]
That is an interesting solution .. to the bug. I may look into that later.
