### ISSUE TITLE
Trucks getting stuck in dump zone with control tower

### ISSUE THREAD

**Issue by aingolmo** [MaFi-Games/Captain-of-Industry-issues#401]
Problem: When trucks dump in a zone with a control tower linked from another tower or storage, they frequently get stuck with "nowhere to dump" and a partial or full load. Recovering the truck does not help. Dumping the truck's cargo manually does reset the truck so it can take another job.

Details: The trucks seem to pick a specific location within the dump zone when they begin their journey. As long as they can empty their load at the location, they behave correctly. However, if the location does not permit them to empty their load completely or another truck has already filled it, they seem to stop looking for another place within the dump zone and get stuck. This is especially noticeable with larger capacity vehicles. (I have observed the behavior with trucks and mega trucks. I don't have any pickups on my island now so I am not sure if they are affected.) If the dump site is not linked from a tower or storage, the trucks will continue to seek dump locations within the zone until they are empty (or the zone is completely full) as expected. (It is worth noting that this may affect transfer to storage too. I think I have had trucks get stuck if another fills the storage first. However, I haven't been able to test it enough to confirm what is causing it.)

Current workaround: Do not link to a dump zone. As long as it is unlinked, the vehicles appear to work correctly.

Edit: fixed typo

**Comment by MaFi-Games** [comment]
I believe we have fixed this in one of our previous updates. Please file a new ticket with a save file if not. Thanks!
