### ISSUE TITLE
ShiftCopy balancer doesn't clone its settings

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#402]
**Describe the issue**
See STR

**Expected behavior**
Copy content 1:1

**To Reproduce**
Place balancer with some inputs and outputs, set priorities, click shift+C, select whole setup, copy elsewhere => balancer has default settings.

**Additional context**
0.4.5.a

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.6
