### ISSUE TITLE
Restore access to ocean doesn't work.

### ISSUE THREAD

**Issue by GunthorNC** [MaFi-Games/Captain-of-Industry-issues#403]
Playing on the beach map, I started dumping a couple tiles worth of material next to the default dock. (Right side) I noticed that it blocked off access to the ocean. I stopped dumping, and pressed the "restore access to ocean" button, it did not restore access. I've pressed it 30+ times no luck though (Unity does spend though) It has cleared out a small chunk, (Where the red grids overlap) but I can not seam to get it to work.

**Comment by MaFi-Games** [comment]
If it happens again and is reproducible, please provide a save file so we can take a look. Closing for now.
