### ISSUE TITLE
Fluid storage is missing colors after loading game

### ISSUE THREAD

**Issue by alexebird** [MaFi-Games/Captain-of-Industry-issues#404]
**Describe the issue**
When I load my game, it starts out paused, and fluid storage of all sizes do not show the color/texture until unpausing.

**Expected behavior**
Expecting fluid storage texture to show up in the little windows on the top of fluid storage buildings.

**To Reproduce**
1. Load any saved game.
2. Observe that game starts out paused.
3. Observe that non-empty fluid storage are showing no texture indicating fluid type.
4. Unpause, and the textures appear.

**Additional context**
 - Game version: 0.4.5b

**Attachments**

![20220621144550_1](https://user-images.githubusercontent.com/120678/174902600-b69719f8-f4d6-4617-bd6d-b976c197812c.jpg)

**Comment by MaFi-Games** [comment]
Thanks for your report! This was fixed in one of our previous updates.
