### ISSUE TITLE
trucks not able to drive even though it is flat

### ISSUE THREAD

**Issue by r0guec0bra** [MaFi-Games/Captain-of-Industry-issues#408]
![image](https://user-images.githubusercontent.com/31194285/174948089-9770d2db-329d-4498-840f-253d655b3f7f.png)
![image](https://user-images.githubusercontent.com/31194285/174948129-64427c30-c00e-4e11-a4fa-d09382249d4b.png)
![image](https://user-images.githubusercontent.com/31194285/174948155-606251c8-dc3e-447d-aa97-7bcf200fb5a4.png)
![image](https://user-images.githubusercontent.com/31194285/174948181-faf78e5f-093b-4489-aa84-47eb6d6b45bd.png)

**Comment by MaFi-Games** [comment]
Can you please provide a save file where this is happening?

**Comment by r0guec0bra** [comment]
how do i do that never done it before

**Comment by MaFi-Games** [comment]
Closing as not enough information available. Please feel free to file a new request with a save file.
