### ISSUE TITLE
Fluid-/Gas-storage blancing.

### ISSUE THREAD

**Issue by G2KG** [MaFi-Games/Captain-of-Industry-issues#409]
**Describe the issue**
When using Flare and/or Smoke stock on a fluid storage, as an content "blance", they just continiusly empty the storage despite the limit settings on the storage. 
It only works if NOT piped and uses truck to diliver the fluid/gas to a stock/flare. witch is annoying and redicolus having one single square empty between storage and stock having it occupied with a truck to loop.

**Expected behavior**
 it should work directly attatched on storage.

**Comment by Hayate316** [comment]
It's only for trucks
I guess you can move smoke and flare to otherplace
Burning all or just the excess or try balancer depend on location

**Comment by MaFi-Games** [comment]
Sliders don't affect belt and pipes - only trucks.
