### ISSUE TITLE
Trucks unnecessarily running fuel between cargo dock and fuel silos

### ISSUE THREAD

**Issue by zytukin** [MaFi-Games/Captain-of-Industry-issues#41]
**Describe the issue**
Cargo ship arrives at the dock and refuels.  Dock is supplied fuel via a pipeline.
Trucks pick up fuel from the fuel silos and bring it to the dock despite the pipeline.
Trucks can't load all fuel into the dock because the pipeline refills it so it gets added as inventory.
Dock is set to "keep empty" so trucks pick back up the fuel to try and take it back to the fuel silos.
Fuel production refills the silos so the trucks can't drop it off at the silos so return it to the dock as inventory.
Process repeat and trucks get stuck running fuel back and forth for a while.

**To Reproduce**
1. Watch video
 - Game version: 0.2.9

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files

https://user-images.githubusercontent.com/34819700/135781525-cc9686a4-85f5-428e-a662-6c130fd4a356.mp4

.

**Comment by MaFi-Games** [comment]
By "Cargo dock" you mean the shipyard for your battleship, right? Shipyard is a little complex entity and logistics control is complex since there is storage and fuel that would need separate controls. We will see what we can do to avoid this situation. Thanks for the report.

**Comment by MaFi-Games** [comment]
This is happening because you have the green "keep full" slider on in your shipyard. If you put it back then trucks will stop fetching fuel and the pipe will do its job. Please let us know if that is not the case.
![image](https://user-images.githubusercontent.com/90082857/135897275-09792abd-a29f-4216-8091-39bafd6585e5.png)

**Comment by zytukin** [comment]
> This is happening because you have the green "keep full" slider on in your shipyard. If you put it back then trucks will stop fetching fuel and the pipe will do its job. Please let us know if that is not the case. ![image](https://user-images.githubusercontent.com/90082857/135897275-09792abd-a29f-4216-8091-39bafd6585e5.png)

Yea, before doing that fuel wasn't pumped into the shipyard as fast.  Setting it to keep full made it fill up right away before fuel went to gas stations, thus speeding up refueling the ship to explore the map.

**Comment by MaFi-Games** [comment]
Closing this as this is a beta issue, and we polished lots of stuff around logistics already.
