### ISSUE TITLE
New Route Assignments problem

### ISSUE THREAD

**Issue by Hayate316** [MaFi-Games/Captain-of-Industry-issues#413]
**Describe the issue**
One storage mining control tower exporting things to other tower's storage

**Expected behavior**
Assign a tower for mining iron ore
Build a storage for ore and wish it dump dirt and rock nearby

And now every truck are transport rock to far far away storage which are build for dumping transport

**To Reproduce**
1.build some Mine tower
2.export link to a storage for something like ore
3.mining something not ore,but had another tower's two storage dumping it
4.truck will transfer to other tower's linked storage 
5.it can prevent by build one storage for dirt and rock,even full it won't export anymore
6.or just not assign any storage,it won't go to linked storage and can dump nearby

**Additional context**
 - Game version: [0.4.5b]

**Attachments**
![IMG_20220622_214004_460](https://user-images.githubusercontent.com/108011449/175064265-34e147a8-523e-4d09-9a94-265e27d0ce01.jpg)
![IMG_20220622_214006_429](https://user-images.githubusercontent.com/108011449/175064312-38b65cd0-ff17-40d8-a211-df7ddce38941.jpg)

And also the import for mine tower,can excavator refuel itself without the pickup?

**Comment by Hayate316** [comment]
> Can you please provide a save file? I'm not sure I follow what is the issue from the description here.

https://drive.google.com/file/d/1yjuMmcU3UBqtmEWK2B-yC3SaKQ7b8l__/view?usp=drivesdk
I don't know where to upload so I drop to Google drive

truck tries to dump cargo to storage that has strict rule to import only from other tower

One storage tower can ignore the restrict rule is weird

**Comment by MaFi-Games** [comment]
THIS WAS IT! :) => "I found that when I have no assigned storages on one tower, and an assigned storage on another tower, when I create a storage in the first tower, and assign it, then the waiting trucks in the first tower immediately head for the storage in the second tower."

We have fixed this in 0.4.9. Please open new bug if you still encounter some issues.
