### ISSUE TITLE
cargo ship went out got damaged sent iron like it asked day later says still waiting for iron

### ISSUE THREAD

**Issue by jimg2468** [MaFi-Games/Captain-of-Industry-issues#416]
**Describe the issue**
cargo ship went out to explore  then says got damaged i sent 220 iron to repair day later says it has not arrived yet
just thought you like to know alos i do not see any error pop up.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
set as sailor
 - Game version: v0.4.5b

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Cargo ships cannot get damaged. You have just discovered one and need to repair it.
