### ISSUE TITLE
Feature: allow WASD scrolling in Research Tree and World Map

### ISSUE THREAD

**Issue by jweather** [MaFi-Games/Captain-of-Industry-issues#419]
After flying around my island for a few hours I find myself tripped up by the mouse navigation required on the Research Tree and World Map pages.  It would be great if WASD could continue to work for scrolling around these screens.  Thanks!

**Comment by utdrmac** [comment]
Absolutely same feelings. Don't get why navigation around island is WASD but map and research is mouse-based.

**Comment by MaFi-Games** [comment]
This has been added in v0.4.7, thanks for the feedback!
