### ISSUE TITLE
Game get very laggy

### ISSUE THREAD

**Issue by onelazysamurai** [MaFi-Games/Captain-of-Industry-issues#420]
Playing on the most recent patch as of 22 June 22 for most of the day the game was running perfectly fine later in the day after reopening the game the game seems to use a lot of power from cpu and power supply. dont know if this is coming from the game or something i have done. Thanks 

**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Can you please attach your save file so we can take a look?
