### ISSUE TITLE
Copy/paste settings on turbines does not work

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#422]
**Describe the issue**
When you press the 'v' key while hovering over a turbine (any kind), you expect all of the settings to be copied. The 'Auto-balance' toggle is not copied.

**Expected behavior**
I expect the feature 'copy settings' to actually copy the settings.

**To Reproduce**
1. Place down a high turbine. Enable auto-balance
2. Place down another turbine. Press 'v' while hovering over #1 turbine.
3. click 2nd turbine to copy settings. note that setting is not copied.

**Additional context**
 - Game version: 0.4.5b

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.6
