### ISSUE TITLE
Diesel storage truck pileup

### ISSUE THREAD

**Issue by rodelle** [MaFi-Games/Captain-of-Industry-issues#425]
**Describe the issue**
I have a bunch of trucks piling up around a diesel storage. When I turn off export/import for the storage, the trucks scatter, but some still get stuck heading towards other diesel storages. 

**Expected behavior**
The trucks refuel (prioritizing fuel stations...) and continue on their merry way.

**To Reproduce**
1. Load attached save [diesel-storage-truck-pileup.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8973706/diesel-storage-truck-pileup.zip)
2. Turn off export and import for the diesel storage and wait a few seconds
4. The trucks scatter. Some refuel at a nearby fuel station. Others start stuttering towards another diesel storage

**Additional context**
 - Game version: 0.4.5.b

https://user-images.githubusercontent.com/839150/175476427-e072cc2d-c363-4e2c-8a1a-39b7f81020a4.mp4

**Comment by XsExcess** [comment]
I was going to make a similar ticket. But with the inclusion that the "queue" system also leads to this making satelite fuel depos difficult. Additionally causing issues with large (t3/4) storage having the same max loading simultanious vehicles as their smaller varients, so any longer distance routes, end up with multiple trucks slowly inching their way across the map, a few steps at a time as their pathing gets interrupted by the queue advancing and triggering a recalculation. No matter how many fuel depos added, with shorter routes, the same issue persists as they seem to have a lower priority than storages themselves.

**Comment by sclauss** [comment]
I have the same issue still in 0.4.8. I even noticed it getting worse after upgrading to that version. If a savegame file is needed I will provide one.

**Comment by zuff-coi** [comment]
I could not reproduce this issue in v0.4.9c. If you still have issues in that version please reopen this ticket and let us know!
![image](https://user-images.githubusercontent.com/108291414/182473915-67b6edad-b850-429e-aad1-b56ffca9b760.png)
