### ISSUE TITLE
Max Height Transport Clips into Maintenance Depot Roof

### ISSUE THREAD

**Issue by CaptainLame** [MaFi-Games/Captain-of-Industry-issues#426]
**Describe the issue**
Transports at Height 3 clip through top of Maintenance Depot

**To Reproduce**
1. Place Maintenance Depot
2. Run a belt over it where the roof fan is

**Additional context**
0.4.5b

**Attachments**
![image](https://user-images.githubusercontent.com/17200948/175559811-70302ebb-6607-474e-8ac9-0272fbf11fae.png)

Proposed fixes:
Either reduce profile of Depot roof to be below a transport at height 3 or put an exclusion zone causing the transport to go to height 4 like when one max height transport jumps another.

**Comment by MaFi-Games** [comment]
This requires increase of the bounding box on the maintenance depot. Question is how safe this change is for backwards compatibility.

**Comment by CaptainLame** [comment]
I guess the safest in that case would be to reduce the model’s height to match the bounding box. Unless the bounding box can be increased without it removing/breaking existing transports while forcing new ones to conform. I’ve certainly seen examples of the latter in Satisfactory updates but that’s quite a different game engine.

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
