### ISSUE TITLE
Air separator colours reversed

### ISSUE THREAD

**Issue by Gnrnr** [MaFi-Games/Captain-of-Industry-issues#43]
**Describe the issue**
When looking at the air separator after construction, the red coloured pipe outputs nitrogen and the blue coloured pipe outputs oxygen.  Colours on the model are reversed.

**To Reproduce**
1. Just place an air separator
2. Connect it up and start running it.  Connections will be as per displayed icons ie icon for nitrogen will out put nitrogen.
3. Once done look at the building.  The colours on the pipes are reversed.

**Expected behavior**
Expected behavior is the blue coloured pipe matches with nitrogen.  Red coloured pipe matches with oxygen.
**Additional context**
 - Game version: 0.2.10

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
https://steamcommunity.com/sharedfiles/filedetails/?id=2619182694

**Comment by Burnrate** [comment]
I think the best way to fix is to swap the colors so the pipes wouldn't have to be changed in an update :)

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
