### ISSUE TITLE
Excavator loses resource if mining designation is removed

### ISSUE THREAD

**Issue by pakb** [MaFi-Games/Captain-of-Industry-issues#434]
**Describe the issue**
Prerequisite : mine a tile, until the excavator is waiting for a truck to load what was excavated. Then remove the designation. The resource disapear from the excavator bucket

Before
![image](https://user-images.githubusercontent.com/11540521/175790572-75dec1db-5ef6-4c69-9544-39bdb11df9a1.png)

After (without unpausing)
![image](https://user-images.githubusercontent.com/11540521/175790583-8ab092bc-17c0-439c-b1b0-73af53eaeb18.png)

**Comment by MaFi-Games** [comment]
Thanks for reporting but this is not really something we aim to fix. We have this way to keep the code around this simple and robust.

**Comment by pakb** [comment]
Yes, if you don't want to implement a job description for each resources but keep it at the designation level, that make sense too (way more complex to attach that to each resource...)
I will be cautious not to clean my mines too early then 😉
