### ISSUE TITLE
Server

### ISSUE THREAD

**Issue by Kay112233** [MaFi-Games/Captain-of-Industry-issues#436]
Ich kann leider kein gutes Englisch deswegen schreibe ich das auf Deutsch

Ich bin jetzt soweit im Spiel wo man einen Server Bank Aufbauen kann aber leider ist da irgendwie ein Bug drin ich kann nur 10 Server rein packen und ich habe mehr davon.
Auch wenn ich ein zweites Gebäude davon aufbaue bekomme ich keine Server hinein.
Und da kann man leider auch kein Förderband dran Anschlissen.
Vielleicht das vergessen worden.

**Describe the issue**

A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Closing as no repro steps provided. Feel free to open a new ticket with more information.
