### ISSUE TITLE
Logistics storage markers

### ISSUE THREAD

**Issue by cw64** [MaFi-Games/Captain-of-Industry-issues#439]
**Describe the issue**
The "keep full" and "empty" markers do not function correctly. Moving either one a single place will casue the trucks to constantly fill or empty the storage regardless of the markers position. It seems the inport or export priority (including the priority on any logistc tied storage) has more effect than where the marker is positioned.

**Expected behavior**
When the "keep full" marker is set to x then the storage will request filling ONLY when the sotrage level drops below x
When the "empty" marker is set to y the the storage will request emtying ONLY when the storage level goes above y

Import/Eport priority has no bearing other than priority position on the truck schedule

BOTH markers should be able to be set at the same time. This makes the game much easier as buffers can be made that can't jam a production chain by being full/empty. The priority should ONLY effect the queue position for the next truck. AND when a truck is requested it WILL import/export up to a full load if alow partially filled trucks is set to off, OR import/export only the required amount needed to reach the marker WHICH is determined when the truck interacts with the storage building and NOT when the job is added to the truck queue in ALL cases.

**To Reproduce**
Load attached save, select fluid storage II (water) at save loation, set markers (+/- logistics ties) and watch the trucks ignore the storage level and import/export past the markers. (Adjust priority and other water storages inport/export accordingly)

**Additional context**
0.4.5b
Engine RAM usage needs work. There is no good reason for the game to crash saving/loading when swap file is disabled with 8Gb RAM and nothing else running on the system. 

**Attachments**

[1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8987966/1.zip)
\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thanks for the report! This has been fixed in one of our previous update.
