### ISSUE TITLE
Unneed ingridients delivered to production buildings

### ISSUE THREAD

**Issue by maxhawk** [MaFi-Games/Captain-of-Industry-issues#44]
**Describe the issue**
Ingridients get delivered to production buildings for recipies that aren't currently enabled, but were enabled previously.

**To Reproduce**
1. Build Assembly or Maintenance Depot
2. Enable and Disable one of the recipes
3. Toggle Truck Import to ON
4. Observe that ingridients for recepies in 2 get delivered to the building

**Expected behavior**
Ingridients shouldn't be delivered for recepies that aren't enabled.

**Additional context**
 - Game version: 0.2.10a

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thanks for the report, this is a little complex issue and we will more time to get it right.

**Comment by MaFi-Games** [comment]
This was hopefully fixed.
