### ISSUE TITLE
Excavators stuck on mining tile of steep cliff after mining zone has been moved/edited

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#442]
If an excavator is mining a tile next to a steep cliff and rock continuously falls in, they will continue to mine that area even if the mining area zone has been moved away.

This can trick the user into thinking that there's a lag/delay on the excavtors' queue, not realizing they are just trying to finish that tile before moving on.

A solution could be to have all excavators abandon their current tile if the mining zone is move/edited.

**Comment by zuff-coi** [comment]
This issue was brought to light by Cazineer on Discord. They also provided a save file which has various other performance issues as it is a late-game save file
[Somewhat_Stable_3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8994757/Somewhat_Stable_3.zip)
.

**Comment by MaFi-Games** [comment]
Thanks for the report. This has been fixed in v0.4.6.
