### ISSUE TITLE
Recycling Collection Center Not Working

### ISSUE THREAD

**Issue by Reubric** [MaFi-Games/Captain-of-Industry-issues#444]
**Describe the issue**
I have connected a recycling collection center to my settlement but it never produces recyclables. I also tried putting in a second one in a different spot on the settlement with the same result. I also researched the recycling edicts and additional recycling research with no effect. It has been like this for over an hour of gameplay time.

**Expected behavior**
I expected when I connected the collection center to my settlement that it would produce recyclables and reduce waste output.

**To Reproduce**
1. Load attached save 'First Try'
2. See that the recycling collection center is not working.

**Additional context**
 - Game version: [Early Access 0.4.6]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.
[First Try.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/8997743/First.Try.zip)

**Comment by MaFi-Games** [comment]
You need to provide your settlement with goods in order to receive any recyclables back.
