### ISSUE TITLE
Vehicles at the maintenance building remains standing for recovery

### ISSUE THREAD

**Issue by ManBo39** [MaFi-Games/Captain-of-Industry-issues#445]
I have problems with the vehicles at the maintenance building
remains standing for recovery and nothing happens, but consume diesel and not go back to their job.

Excavator was without diesel, than i clicked recover and it still is standing at the maintenance building using diesel  and waiting for recovery but it's already recovered.

I notice that after the last update v4.6 the screen also stutters when you scroll over the island

[Manuel 259.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9000944/Manuel.259.zip)
![20220628134718_1](https://user-images.githubusercontent.com/107951019/176177786-bc8e0402-941d-4144-a3af-614576d52b37.jpg)
![20220628134546_1](https://user-images.githubusercontent.com/107951019/176177794-6c45820a-ed42-4a19-aea1-e62ba2d1e912.jpg)

**Comment by dgzeij** [comment]
All vehicles gets de-assigned from their jobs when recovery is clicked. Need to assign something to replace what it did. I wish it wasn't the case, or that there was another button for "recovery but let it keep the job" (don't fire the useless driver).

**Comment by dgzeij** [comment]
Just tested your save. The game is stuck in a recover loop for that specific vehicle. Other new vehicles work as they should. Looks like triggering scrap is just another variable in the recover function. The game notices that something is wrong, but it just tries harder instead of something else.

**Comment by ManBo39** [comment]
Indeed, I had also noticed that new vehicles were not affected, I started an older save and continued from that point, the problem has not occurred yet.

**Comment by ManBo39** [comment]
Today it occurred again, vehicle was standing at the depot, order it to be scrap and it is still standing still recovering vehicle.
[Manuel 266.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9021497/Manuel.266.zip)
![20220630180312_1](https://user-images.githubusercontent.com/107951019/176725005-cee8505c-3570-47df-8a1d-14397a153079.jpg)

**Comment by ManBo39** [comment]
Also I notice that a lot of trucks after they have done there jobs they are queued and waiting for a while!

**Comment by Berlakay** [comment]
Having the same issue! Got about 8 dump trucks stuck like this :(

**Comment by ManBo39** [comment]
I tested this with the crushed iron ore. Placed small storage and only 4 trucks have been designated and the problem persists! As you can see the trucks are still stopping and waiting. You can see in my save that I use the large storage a lot. To replace it with small storage is a time-consuming job and the question is whether it will work and the storage will keep up with consumption!
[Manuel 268.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9034431/Manuel.268.zip)

**Comment by MaFi-Games** [comment]
I belive the issue here was fixed in v0.4.7d. Please file a new ticket if not.
