### ISSUE TITLE
Fertilizer are not transportable to farms (small issue)

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#446]
Hi Marek and Filip,

in my last game i had some fertilizer (organic) stuck in my shipyard. I was unable to remove it until i build a storage for that. The farms (even greenhouses) are not set to request fertilizer at the moment.  

So could you make it possible to be pick up and deliver it to the farms direcly? It is of course very small issue but i find it a bit strange. 

I that is a old savefile (lucky i dont throw them away :) ) but the "bug" is still there
[save_22-06-10_21-04-34.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9002267/save_22-06-10_21-04-34.zip)

**Comment by MaFi-Games** [comment]
This is working as intended. We do not want to support trucking of fertilizer and water to farms. The fact that it ends up in shipyard is a bit unlucky. Maybe we need to consider to discard fertilizer by default.

**Comment by MaFi-Games** [comment]
Next patch will make fertilzier discardable.
