### ISSUE TITLE
Constant pathing issues 

### ISSUE THREAD

**Issue by GameOverAUS** [MaFi-Games/Captain-of-Industry-issues#450]
First off, have to say i've become quickly addicted to this game and really this issues is the only major gripe, anything else is just niggles i can overlook

Basic PC stats - Windows 11 Pro, GTX 1070, 64GB system ram, Ryzen 5 5600x,
Issue-Vehicle pathing needs to be addressed

Would've been reported time and time again no doubt but pathing of vehicles is hit and miss at best

As you can see in the attached save, i have at that time numerous vehicles that can't find there way, i'd just fixed 8 others just before this save, even tho they came from where they are trying to get to in order to not be able to get back.  At this point in the save i'm spending so much unity and time just fixing vehicles that are lost, and in some cases they can't even get reset or scrapped as they can't find there way to that either.

There is room to get around buildings and there is ramping that is also ignored in some cases.  Some of the issues obviously relate to the import/export function of most buildings so i get that, but i've only had a few instances where that was the site that couldn't be accessed

Thank you :)
[Broken pathing.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9013646/Broken.pathing.zip)

**Comment by GameOverAUS** [comment]
I've come to the conclusion that even tho there are paths, if you have raised pipes sometimes the vehicle just refuses to consider it even if it has driven under it before.  I realise Excavators can't go under pipes but i've never had an issue with them, only trucks.

I removed some of the raised pipes and layed ground pipe with a bridge and go figure SOME of the vehicles moved again but didn't use the bridge, they went under a raised pipe section nearby <FACEPALM> so it's not a fix

**Comment by MaFi-Games** [comment]
Thanks! I loaded your save file and there was actually no path to your stroage with potatoes, adding another bridge solved the issue. However, also since you filed this bug we improved PF and reporting, so maybe there were more issues and they are now gone. Anyway, if you have issue again in latest version please feel free to file a new ticket. Thanks!
![image](https://user-images.githubusercontent.com/90082857/204111612-bca561c6-5f5d-47a9-9f08-49454a1699a5.png)
