### ISSUE TITLE
Trucks ignore custom routes

### ISSUE THREAD

**Issue by EricCoon** [MaFi-Games/Captain-of-Industry-issues#451]
Hi,

I have a small storage setup, where dirt can be dropped and redistributed. If the storage is full, i have a overflow with an custom export route to a dumping area with mining tower. 

Now the issue: The trucks take out of the overflow with the route but deliver everywhere (including the input of the redistribution node). They very rarely transport to the dumping zone, where they are supposed to go. 

[The sun shines upon us.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9016219/The.sun.shines.upon.us.zip)

**Comment by MaFi-Games** [comment]
This has been fixed in v 0.4.8, thanks for the report!
