### ISSUE TITLE
Cargo Depot III building footprint too large

### ISSUE THREAD

**Issue by Mr-McBaldspot** [MaFi-Games/Captain-of-Industry-issues#454]
**Describe the issue**
Can't build Cargo Depot III in a space that would clearly allow for it. I noticed that CDIII had the same build footprint has CDIV.

**Expected behavior**
I expected Cargo Depot III to be built.

**To Reproduce**
1. Make an attempt to build CD III in an area that is big enough for it, but not big enough for CDIV

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by moffmaster** [comment]
The cargo depots I and III leave room to upgrade. I guess you are right, that one would expect that you can build a CDIII without having the space to uprade to a CDIV later. But I think its kinda intended behaviour.

**Comment by Mr-McBaldspot** [comment]
Thanks for the clarification!

**Comment by MaFi-Games** [comment]
Yes, this inteded behavior. Cargo Depot III reserves space for Cargo Depot IV.
