### ISSUE TITLE
Ghost truck

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#458]
**Describe the issue**
Assigned truck to mining tower does not exist or is not visible
![image](https://user-images.githubusercontent.com/108291414/176740169-f619c725-2463-40d0-9440-47b8603a8f12.png)
(middle assigned truck)

Screenshot of Mining Tower ghost truck is assigned to:
![image](https://user-images.githubusercontent.com/108291414/176740314-4258cbcf-dcc2-49ac-9655-a36824a46015.png)

Originally reported by MFeltmann#6600 on discord

**Additional context**
 - Game version: 0.4.6

**Attachments**
Save game: [Uploading 4th_save.zip…]()

**Comment by McRib33** [comment]
A another Gamer had the same issue i made report. I closed that but link it: https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/470

**Comment by MaFi-Games** [comment]
Thanks for the report, this has been fixed in `v0.4.7c`!
