### ISSUE TITLE
Farms not letting dirt/ground fall beneath them

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#462]
**Describe the issue**
![image](https://user-images.githubusercontent.com/108291414/176778990-bf7203cf-a45d-4536-8d25-47508537e4c4.png)

**Additional context**
 - Game version: 0.4.6

**Comment by dgzeij** [comment]
This ground retention sticks after building deletion.

![20220701002339_1](https://user-images.githubusercontent.com/85814950/176788910-2419717c-af8d-4ec5-a289-7ca0baec18bf.jpg)

Excavators are able to dig through it, and after the ground is disturbed the dirt and rocks collapse as normal, but still form that sharp edge behind it.

![20220701003127_1](https://user-images.githubusercontent.com/85814950/176789473-1ce07f5d-5006-4bea-b0ee-bec077fca624.jpg)

**Comment by zuff-coi** [comment]
Fixed with patch [0.4.7](https://store.steampowered.com/news/app/1594320/view/3318605091441379224)
