### ISSUE TITLE
Large Log File Folder size

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#463]
**Describe the issue**
User reported 8gb of log files in their log folder

**Additional context**
 - Game version: 0.4.6

**Comment by MaFi-Games** [comment]
It would be helpful to know what is in those files. We don't need entire 8 gigs, but perhaps a first 1 MB. It is likely that some issues are causing logs to grow too fast. It is safe to just delete them.
