### ISSUE TITLE
Save Game lädt nicht

### ISSUE THREAD

**Issue by SmokyElzecho** [MaFi-Games/Captain-of-Industry-issues#465]
**Describe the issue**
Ich konnte ein Lager nicht abreißen habe gespeichert, das spiel neu gestartet auf fortsetzen geklickt, dann kam der lade Bildschirm nach 10,20 sec. Erschien die Fehlermeldung.

**Additional context**
 - Game version: [e.g. 0.4.6]

**Attachments**
[Selz.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9023608/Selz.zip)
[22-06-30_22-37-03_8490.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9023632/22-06-30_22-37-03_8490.log)

**Comment by MaFi-Games** [comment]
Duplicate of #453

**Comment by MaFi-Games** [comment]
This has been fixed in `v0.4.7b`, thanks for the report.
