### ISSUE TITLE
Underground pipes delete dirt above them if deconstruction undone.

### ISSUE THREAD

**Issue by Trollsamaa** [MaFi-Games/Captain-of-Industry-issues#467]
**Describe the issue**
If a pipe that is underground is deconstructed, and deconstruction is reverted part way.  The pipe will delete the ground above it.
In the situations I have experienced the pipe was 1 layer deep.  Not sure if pipe depth is a factor.  I also used unity to rebuild the pipe.

**Expected behavior**
Pipes that have deconstruction reverted remain underground and continue through the reconstruction process.

**To Reproduce**
1. burry pipe underground
2. que part of the pipe for deconstruction using the delete tool.
3. before deconstruction is finished, pause it.
4. undo deconstruction
5. use unity to rebuild pipe.

**Additional context**
 - Game version: EA 0.4.6

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed and will be available in the next patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
