### ISSUE TITLE
Crash Continue Game 

### ISSUE THREAD

**Issue by arsaca2122daw2** [MaFi-Games/Captain-of-Industry-issues#469]
**Describe the issue**
Crashes when click on Continue Game

**Expected behavior**
Continue my own game I started 

**To Reproduce**
1. Start Game
2. Continue Game
3. Crash

**Additional context**
 - Game version: ALPHA VERSION 0.4.6

**Attachments**
![image](https://user-images.githubusercontent.com/91496705/176880682-d6732031-86f7-495a-b61e-60f190bafa26.png)
![image](https://user-images.githubusercontent.com/91496705/176880770-3e2df0c2-a4d2-4f60-b3de-6a2d17984cc5.png)

**Comment by MaFi-Games** [comment]
This has been fixed in `v0.4.7b`, thanks for the report.
