### ISSUE TITLE
t3 Trucks are underground

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#470]
hi Filip and Marek,
It seem that with the last patch we got a issue that t3 Trucks just go under the earth and stay there. 2 out of 6 t3 trucks are gone missing.

This bug occure after the last patch however it is not right when the issue must have happend since at that time the player had only some t2 trucks and non t3 trucks. (I just report this issue but didnt found it.)

**Expected behavior**
Open the truck UI and click on the t3 trucks 4 of them are in the mine 2 of them are gone.

**Additional c
[nr3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9028503/nr3.zip)
ontext**
 - Game version: 0.4.6

**Comment by McRib33** [comment]
i run some Q & A if this bug is in the another games since it is very hard to detected that if not dont know about it.. After checking 4 another saves which non of them show the issue. The issue must be kind of rare to be triggert.

**Comment by NightElfik** [comment]
Thanks for the report, this was fixed in `v0.4.7c`!

**Comment by MaFi-Games** [comment]
Thanks for the report, this has been fixed in `v0.4.7c`!
