### ISSUE TITLE
Construction Parts disappeared on cut/paste

### ISSUE THREAD

**Issue by Lutenar** [MaFi-Games/Captain-of-Industry-issues#471]
Hi devs!

**The issue**
I came across an issue when constructing buildings on version 0.4.6:
On a paused game I planned a few buildings, when I was satisfied I quick delivered a few of them (game still paused), but then wanted to move them a bit, I cut/pasted the buildings, and the construction parts that were quick delivered just vanished. Not in the shipyard as well.
I had to reload my game (on that note, to be able to autosave every 5 minutes would be fantastic, as well as a quick save bind)

**Expected behavior**
I expect, either not to be able to cut/paste building that have parts already delivered (worst solution), or that the parts are still there when I paste the building back.

**To Reproduce**
1. Pause game using space bar
2. Build something
3. Quick deliver
4. Cut/Paste it somewhere else
5. Parts gone!

Anyways, thank you for this amazing game!!

**Comment by zuff-coi** [comment]
Thanks for bring this issue to our attention

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.7c - cut is no longer allowed after products were delivered.
