### ISSUE TITLE
Gold amount on YSNP depends on cliff elevation and resource elevation

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#472]
**Describe the issue**
The amount of gold on the island changes based on elevation settings

**Expected behavior**
The same amount of gold to be on the island regardless of elevation settings

Map with default generation settings:
![image](https://user-images.githubusercontent.com/108291414/176931077-d0033b15-21df-4d59-83c5-ca8e41352e6e.png)

Map with +50% cliff height and resources at -8 levels:
![image](https://user-images.githubusercontent.com/108291414/176931163-217a876a-82b8-4e5a-a841-25a59608a512.png)

**To Reproduce**
Dr.KhairuAkbar and Dark on discord went through extensive testing to prove this. You can see the beginning of these tests here:
https://discord.com/channels/803508556325584926/883590993063051275/992214823100239922

**Additional context**
 - Game version: 0.4.6

**Comment by knmh84** [comment]
on our tests we completely filled all area around gold mine so we can get access to hidden underwater mine area. emptied the island mine of gold...  and it totals in at 1.36M and in map details it say to have 3.3M or 3300K
![Gold YSNP less gold](https://user-images.githubusercontent.com/106634630/176932711-e6d62895-e22d-496a-97ae-10197ea9fb50.png)

**Comment by knmh84** [comment]
the next result is here....
the total amount of gold on standard map with no setting changed and hardness lvl captain its 5M more that 3.3M

**Comment by RuiApostolo** [comment]
Came here to report this. I just generated maps with the same seeds, I don't have the numbers to back it up, but can share screenshots/savegames if that's useful.

**Comment by MaFi-Games** [comment]
Thanks for reporting, we will fix this as a part of map editor changes in Update 1.
