### ISSUE TITLE
Vehicles stuck and cant recover or scrap

### ISSUE THREAD

**Issue by gab1983** [MaFi-Games/Captain-of-Industry-issues#477]
**Describe the issue**
Hi, I have a couple of stuck vehicles (Mixture of Mega Excavator, Haul Truck and Normal Truck). 2 of which are stuck at "Queued and Waiting" while the excavator is stuck at "Recovering Vehicle (DoJob, Stopped)".
All their Scrap and Recover buttons are disabled.
Tried digging and filling the ground below them and demolish and rebuild depots but still cant recover them.
Additionally I accidentally discovered some hidden vehicles near the depot while using the pause tool.
**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: v0.4.6

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by gab1983** [comment]
![1](https://user-images.githubusercontent.com/103867118/176983147-7d2ae0e9-6b75-4032-9ab3-90ee28f6ee9a.jpg)
![2](https://user-images.githubusercontent.com/103867118/176983151-2661b71b-1f17-4724-a05b-ba6c12c4859b.jpg)
![3](https://user-images.githubusercontent.com/103867118/176983153-6638c6d1-e88b-4a28-a4d2-4da928bd85f6.jpg)

**Comment by Berlakay** [comment]
+1

**Comment by MaFi-Games** [comment]
Please provide us with a save file so we can debug the issue

**Comment by MaFi-Games** [comment]
Issue of this nature has been fixed recently.
