### ISSUE TITLE
so my 100+ hour game just crashed

### ISSUE THREAD

**Issue by fuman200** [MaFi-Games/Captain-of-Industry-issues#478]
**Describe the issue**
There is a 2 specific issue before it crashed.

There was about 2-3 trucks that are invisible and I was able to find them from the truck menu and I even numbered every truck to see if I was seeing things.  

The second issue I had a truck stuck by the trading dock. I clicked recover and it did not do anything.  I also clicked scrap and it did nothing.  It was just stuck there.

As for now Today 7/2/2022 I tried opening my saved file and it just crashed.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by shaunsters** [comment]
i too had invisble excavators last night digging. some pipes i placed were not rendering. saved game and logged off. Today i tried to load up game save and got "We are really sorry, but the game failed to initialize please send us a report with details"

**Comment by MaFi-Games** [comment]
Thanks for your report but we can do very little if we don't get your logs and save files so we can investigate them. Please provide them so we can take a look.

**Comment by MaFi-Games** [comment]
We believe we have fixed load crash and vehicle issues as in other tickets we have received save files to reproduce it.
