### ISSUE TITLE
No Ingedient Icons After Placement of Sour Water Stripper

### ISSUE THREAD

**Issue by TheOldGuy56** [MaFi-Games/Captain-of-Industry-issues#48]
**Describe the issue**
When placing a sour water stripper the ingredient icons for the pipe connection are visible. But after the sour water stripper has been placed on the ground the icons no longer appear, making it very hard to determine which pipe goes where

**To Reproduce**
Build a sour water stripper
View the attached screenshots

**Expected behavior**
Icons should be visible so that the player knows which ingredient goes to each pipe connection

**Additional context**
 - Game version:  Alpha 0.2.10a

**Attachments**
Screenshot of placing the stripper, which shows the icons. Screenshot of the stripper after placement, where the icons have disappeared
![Sour Water Stripper after placement](https://user-images.githubusercontent.com/91866893/136058110-d5701baa-9776-4cdf-9e95-38967bd74f1b.png)
![Sour Water Stripper before placement](https://user-images.githubusercontent.com/91866893/136058121-565a4ae0-53a1-4503-8a56-7717352aeb43.png)

**Comment by MaFi-Games** [comment]
This has been (hopefully) fixed in the upcoming beta patch, thanks for reporting! If you encounter this again in the beta, please report it.
