### ISSUE TITLE
Truck stuck in "dumping" state, not moving

### ISSUE THREAD

**Issue by Madrawn** [MaFi-Games/Captain-of-Industry-issues#482]
**Describe the issue**
_I already send this to zuff+support@captain-of-industry.com before I realized you guys have a github issues page._

The attached save loads zoomed in onto a dump truck that has the state "dumping" but will not move. The really weird thing is, when you select the dump truck and click the "unassign - Mine control tower" button he drives off, after a few seconds of thought, finally dumping his cargo. Directly reassigning him to the same control tower while he's still loaded (driving to the dump marker) sometimes "re-stucks" the truck. Only after he dumped his cargo a reassignment seems to be completely bugfree. 

This bug either didn't happen before one of the two last updates, or only starts to happen when my cpu starts to struggle with the amount going on.

Another interesting bit is, that you can tell if a truck is stuck like that when you open up this screen: 
[image.png](https://github.com/Madrawn/convenience/blob/main/unnamed.png?raw=true)
The number representing the amount of jobs done dumping rock will climb unreasonably, even if not a single truck is successfully dumping rock anywhere. It behaves as if every stuck truck reports its job as finished and his cargo dumped multiple times per second, even though he doesn't actually do anything. So if I feel mining is getting slow I can open that overview and check if I have to hunt for stuck trucks.

They usually seem to get stuck at several distinct locations.
1. Directly next to the excavator not driving off after being fully loaded like the example here.
2. Next to a fuel depot or station, it seems to happen more reliably when the fuel station can barely keep up with the demand and the trucks have to wait.
3. Directly next to a dumping marker, there it seems to happen when the truck drives to a marker, then when he arrives the marker is already fulfilled, the truck now decides to service another marker and before he can start driving that one also gets done.

Sometimes designating a new dumping marker will also manage to get all of them them out of their trance at once without having to unassign them, but a simple removal of an existing marker and then remarking the same spot will not work, even if you do it for a whole region.

Hope you can figure that one out, it seems like a drag to debug, but it's also really annoying to babysit your trucks while your economy is stalling.

Btw, I love the game and sunk too many (over 120h) hours into it already so pass that on as well. :) 
Greetings from Germany!

**Expected behavior**
Truck should dump his cargo if possible or notify me why he can't, not silently fail to continue working

**To Reproduce**
1. Load attached save '...'
2. Gaze upon the not moving truck
3. Realize the truck is in state "dumping"
4. Gaze some more upon him not moving, also check out the truck job analytics overview and see how the rock jobs rise like crazy
5. Click him and unassign him
6. Gaze upon him starting to move 

**Additional context**
 - Game version: 0.4.6

**Attachments**
A save that looks directly at a broken truck
[bugtrug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9033335/bugtrug.zip)

**Comment by zuff-coi** [comment]
This is no longer an issue as of v0.4.9c! This issue was duplicated by myself in #501
