### ISSUE TITLE
Cannot overwrite saved game (CZE)

### ISSUE THREAD

**Issue by japadoch44** [MaFi-Games/Captain-of-Industry-issues#486]
![IMG_20220703_071506](https://user-images.githubusercontent.com/108605500/177028291-4fe498ff-347c-4701-ae56-740a1fd51501.jpg)
nejde prepsat ulozeni hry
![IMG_20220703_071506](https://user-images.githubusercontent.com/108605500/177028312-a8d6feb1-5136-4460-990b-64c2b553c411.jpg)
**Popište
 problém** Jasný a stručný popis toho, co se zde děje.

 **Očekávané
 chování** Vysvětlete, co jste očekávali, že se stane.

 **
 Reprodukovat** Kroky k reprodukci chování:
 1. Načíst přiložené uložení '... '
 2. Udělej xxx '....
 3. Zvláštní věc se stává.... '

 **Další
  kontext** - Verze hry: [např. 0.

 2
.1a, viz hlavní menu] **Přílohy** Případně přidejte uložit soubory (zip), screenshoty nebo soubory protokolu, které pomohou problém vysvětlit. Najdete je ve svých dokumentech (`%userprofile%\Documents\Captain Of Industry\`). Pokud je váš problém vážný, jako jsou havárie nebo rednering závady, také unclude Unity logy z `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. Možná budete muset připojené soubory zapínat.
![IMG_20220703_071506](https://user-images.githubusercontent.com/108605500/177028321-def91ca2-074c-4dc2-97a0-f9f6e9073566.jpg)
![IMG_20220703_071506](https://user-images.githubusercontent.com/108605500/177028328-fe0f5b01-c15a-4f7d-ac23-a20c3ae890f6.jpg)

**Comment by MaFi-Games** [comment]
As explained in the dialog it seems that the game is being prevented to rewrite files, check your windows for ransomware protection and antivirus settings.
