### ISSUE TITLE
Trucks cant seem to pass the are which they were doing fine before update

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#487]
the trucks were driving fine to that waste management facility before update now they wont... i checked the area with mining and dumping designation.... there is nothing thats blocking the area still my haul trucks cant reach the destination
here are the images and save file
![1](https://user-images.githubusercontent.com/106634630/177028730-1f1fc196-7b2a-4059-8025-5d8933daf7bc.png)
![2](https://user-images.githubusercontent.com/106634630/177028739-64f4c7f1-a1c3-4c55-930f-6d7cc3ed69f1.png)
![3](https://user-images.githubusercontent.com/106634630/177028759-6271d9fc-32f7-4594-9d11-d8d4b1f578e7.png)
[trucks cant pass straight plane.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9034203/trucks.cant.pass.straight.plane.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report! This has been fixed in our previous patch. Please let us know if you still have any issues.
