### ISSUE TITLE
Wood cutter stuck into a farm.

### ISSUE THREAD

**Issue by Ajrarn777** [MaFi-Games/Captain-of-Industry-issues#488]
**Describe the issue**
My wood cutter was waiting with a tree in his claw. I build a farm over the wood chopper. It doesn't move away. The farm build over it, and now I can't select or delete it. 
Fuel trucks try to deliver fuel to it, but they can't find the path. Everything is stuck. 

**Expected behavior**
The vehicle should move away when farm is build over it, or be disassembled. 

**To Reproduce**
Check in the East Farm. 

**Additional context**

**Attachments**
[coi_save_25.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9034844/coi_save_25.zip)

**Comment by zuff-coi** [comment]
Thanks for reporting this and providing your save file

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
