### ISSUE TITLE
kraan staat zonder brandstof en de tank auto vult hem niet en wil niet meer rijden

### ISSUE THREAD

**Issue by sybren1969** [MaFi-Games/Captain-of-Industry-issues#489]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by sybren1969** [comment]
zeer leuk spel en zeker niet ( wel) verslavend

**Comment by MaFi-Games** [comment]
Please provide a save file of this happening.

**Comment by sybren1969** [comment]
Sent from Mail for Windows

**Comment by MaFi-Games** [comment]
Sorry but did not receive any save file.
