### ISSUE TITLE
Missing Excavator (Ghost Excavator)

### ISSUE THREAD

**Issue by freeozy** [MaFi-Games/Captain-of-Industry-issues#490]
I read this issue happened before but find no solution about it. I have an excavator on the list but it is not there. And not working when assigned. It seems like it is underground or something. I didnt check my trucks has the same issue because they are too many to figure out if they are missing or not. Also because i cant click the excavator, I cant pause it. Dont know if it use diesel as well.

Hope you fix this issue asap.

**Comment by freeozy** [comment]
by the way if i can some how access the vehicle from vehicle overview panel i can at least send it to scrap or destroy.

**Comment by Afforess** [comment]
Same issue, except with a tree harvester. I have two tree harvesters in my save, you can select the vehicle management window and it shows "2" correctly. Clicking on the tree harvester icon to cycle between them, one goes to the working tree harvester, and the next click goes to the vehicle depot w/no tree harvester visible or selectable anywhere on the map.

Save attached, no mods, still an issue in v0.47a
[save_22-07-03_01-31-52.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9035312/save_22-07-03_01-31-52.zip)

**Comment by Noko187** [comment]
I have two missing haul trucks some how they must of ended up in town got stuck and vanished underground. I can't click on them to scrap when it shows me on the map where they are located. Was about to dig a hole to see if they were underground.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.7d
