### ISSUE TITLE
I have liquid balancers feeding coal boilers for my generators. If for some reason I have a power problem the balancers shut down even though I have them as a priority 1. Other balancers of different types work and a lot of other bigger equipment seem to still have power. I have to pretty much pause my whole Island to get them up and running. Awesome game though.  

### ISSUE THREAD

**Issue by sparkyincolorado** [MaFi-Games/Captain-of-Industry-issues#494]
**Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Could you please provide a save file of this issue happening?

**Comment by sparkyincolorado** [comment]
I have a "saved file" on my computer but not sure how to send it, I did try to copy and paste it to this at the bottom, but it says it doesn't support that type of file. I access the game through steam and tried to find a save file from the cloud but I'm not smart enough to figure that out. lol

**Comment by sparkyincolorado** [comment]
[Balancers.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041041/Balancers.zip)

I hope this is it

**Comment by MaFi-Games** [comment]
Does not seem to be a bug.  The issue here is that you have several high capacity consumers - settlement power module (1.87 MW) , data centre, several research labs. All these were on P1 and competing with the balancers. The reason you didn't see outage on some other balancers was because they were not working (balancers only consume when they work).

**Comment by sparkyincolorado** [comment]
that makes sense, Thanks for clearing that up. And thanks for the Great Game.

**Comment by MaFi-Games** [comment]
Thanks! Let us know if you have any other issues!
