### ISSUE TITLE
Trucks not hauling waste

### ISSUE THREAD

**Issue by JTanwe** [MaFi-Games/Captain-of-Industry-issues#496]
I cannot get settlement waste dumped. Always loose due to settlement waste. Trucks start to build the ramp indicated but then suddenly stop or they never start hauling trash to begin with. Tried everything. Will stop playing now.
My issue is the same as the "Odd truck behavior" posted about six hours ago.

Please fix this issue.

JTanwe

 *Describe the issue**
A clear and concise description of what the issue goes here.

**Expected behavior**
Explain what you expected to happen.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Please provide a save file of this issue happening. From the description this is hard to tell. Many folks dump waste regularly without any issues so this has to be some particular setup.
