### ISSUE TITLE
In mines, truck don't ignore paused excavators

### ISSUE THREAD

**Issue by Lutenar** [MaFi-Games/Captain-of-Industry-issues#498]
**Describe the issue**
Title says all, I have a bunch of paused excavators (to save some fuel), but all trucks are waiting for them, although there's a perfectly beautiful and functioning one not far!

**Expected behavior**
Trucks should know an excavator is paused and not attempt to get anything from it.

**Additional context**
 - Game version: 0.4.7A

![coi](https://user-images.githubusercontent.com/35697693/177182433-c72c2ed7-a32b-481a-82bf-338ee74f5a7e.jpg)

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
