### ISSUE TITLE
Unexpected excavator behavior

### ISSUE THREAD

**Issue by Dunbant** [MaFi-Games/Captain-of-Industry-issues#50]
**Describe the issue**
Designated a mine access ramp to be dug farther back along the existing ramp. The excavator started to dig the new ramp but stopped and went idle.

**To Reproduce**
1. Load attached save 'Unexpected excavator behavior.'
2. Designate existing access ramp to be mined and moved back. A screenshot of the order is attached.
3. The excavator prioritizing coal will start to mine the new ramp before both move up out of the mine and idle next to the mine control tower behaving as if the mining area is inaccessible.

**Expected behavior**
Expected the excavator to mine the new ramp.

**Additional context**
 - Game version: 0.2.10A

**Attachments**
If applicable, add a save file (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
[Unexpected Excavator Behavior.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7295846/Unexpected.Excavator.Behavior.zip)
![21-10-06_11-20-59_4179](https://user-images.githubusercontent.com/50967329/136249774-5eb13b3d-260b-446e-8110-885d1b0f4445.png)
![21-10-06_11-21-22_1493](https://user-images.githubusercontent.com/50967329/136249782-eb4bbe46-90a5-4a6a-b260-1812337736a5.png)
![21-10-06_11-25-25_5815](https://user-images.githubusercontent.com/50967329/136250107-baf33a4a-de89-470b-9083-feda19f50882.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, this is caused by excavators not being able to reach the mining tower since it is being mined under. We have improved this behavior in the upcoming beta release where excavators no longer require accessible mining tower while mining.
