### ISSUE TITLE
Game is still running but vehicule won't move (but the goods are still moving)

### ISSUE THREAD

**Issue by Kraalin** [MaFi-Games/Captain-of-Industry-issues#500]
**Describe the issue**
The games is running, you can see goods move on belt world animation is also good, but all other thing that need to move won't. Truck stand still with moving animation some time, but their delivery job are still going fine except the truck is still somewhere on the map. Also if you dele or build nothing really happen but if youi save and reload the game the new or deleted building is updated.

**Expected behavior**
truck moving on the map and contruction work as intended

**To Reproduce**
1. Load attached save Stuck.zip
2. Unpause the game
3. Enjoy, they are all over the map

**Additional context**
 - Game version: 0.4.7A

**Attachments**
Save game included

**Comment by zuff-coi** [comment]
Hi Kraalin,

We need a save file in order to figure out this issue. Could you upload one to this ticket? Thanks!

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.7c

**Comment by Kraalin** [comment]
Super fast works ! 
thanks a lot.
