### ISSUE TITLE
Truck stuck in "Dumping" State

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#501]
**Describe the issue**
The save loads zoomed in onto a dump truck that has the state "dumping" but will not move. The really weird thing is, when you select the dump truck and click the "unassign - Mine control tower" button he drives off, after a few seconds of thought, finally dumping his cargo. Directly reassigning him to the same control tower while he's still loaded (driving to the dump marker) sometimes "re-stucks" the truck. Only after he dumped his cargo a reassignment seems to be completely bugfree. 

This bug either didn't happen before one of the two last updates, or only starts to happen when my cpu starts to struggle with the amount going on.

Another interesting bit is, that you can tell if a truck is stuck like that when you open up this screen: 
![image](https://user-images.githubusercontent.com/108291414/177191743-1c5aff54-85e6-4f30-b0e4-b83cb867b147.png)

The number representing the amount of jobs done dumping rock will climb unreasonably, even if not a single truck is successfully dumping rock anywhere. It behaves as if every stuck truck reports its job as finished and his cargo dumped multiple times per second, even though he doesn't actually do anything. So if I feel mining is getting slow I can open that overview and check if I have to hunt for stuck trucks.

They usually seem to get stuck at several distinct locations.
1. Directly next to the excavator not driving off after being fully loaded like the example here.
2. Next to a fuel depot or station, it seems to happen more reliably when the fuel station can barely keep up with the demand and the trucks have to wait.
3. Directly next to a dumping marker, there it seems to happen when the truck drives to a marker, then when he arrives the marker is already fulfilled, the truck now decides to service another marker and before he can start driving that one also gets done.

Sometimes designating a new dumping marker will also manage to get all of them them out of their trance at once without having to unassign them, but a simple removal of an existing marker and then remarking the same spot will not work, even if you do it for a whole region.

**Additional context**
 - 0.4.7a

**Attachments**
Save File: [bugtrug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041002/bugtrug.zip)

**Comment by MaFi-Games** [comment]
In v0.4.7c we have fixed the quantities analytics but the stuck dumping truck is something we are still investigating.

**Comment by MaFi-Games** [comment]
This has been fixed in v 0.4.8, thanks for the report!
