### ISSUE TITLE
Upgrade buildings with previous tier's cost

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#503]
![image](https://user-images.githubusercontent.com/108291414/177194758-6d318cc8-bd12-4706-9345-2fa45e49562b.png)

**To Reproduce**
1. Place EA level 1
2. Upgrade it, make priority, speed up (dont close the UI)
3. When done, next upgrade should cost the same like the previous tier

**Additional context**
 - Game version: 0.4.7a

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.7d
