### ISSUE TITLE
Cargo Depot II can  be researched before Cargo Depot I

### ISSUE THREAD

**Issue by K-DaK** [MaFi-Games/Captain-of-Industry-issues#506]
**Describe the issue**
Cargo Depot II can  be researched before Cargo Depot I

**Expected behavior**
I expect that the second tier has the first tier as a prerequisite. (Need to research Tier 1 before Tier 2) 

**To Reproduce**
Research away but ignore the Cargo Depot I tech.
Maybe explore the first islands to unlock the "Cargo ship tech"
Continue researching in the tier 2 field until you get to Cargo Depot II

**Additional context**
 - Game version: 0.4.7a

**Attachments**
[Temp.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041299/Temp.zip)
[Cargo Depot research.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041314/Cargo.Depot.research.zip)
[Cargo Depot research 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041316/Cargo.Depot.research.2.zip)

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.7d
