### ISSUE TITLE
Mess when I removed ~20 walls. All trucks are "waiting to unload". So I have a lot of truck blocked.

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#508]
**Describe the issue**
Mess when I removed ~20 walls. All trucks go to take back walls parts, and then they are "waiting to unload". So I have a lot of truck blocked.

**Expected behavior**
I expect trucks will go to a storage to unload, and be able to go together to a storage, and not one by one.
I expeect also that one truck can remove multiples walls to avoid that.
![Screen Shot 07-04-22 at 10 20 PM](https://user-images.githubusercontent.com/96617483/177214994-1b0a670d-a892-4be8-83ab-35b88104186e.PNG)

**To Reproduce**
delete ~20 walls and follow the truck deleting the walls.

You can also load the save and see the truck who are waiting.

**Additional context**
 - Game version: 0.4.7a

**Attachments**
[save_22-07-04_22-20-05-bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9041974/save_22-07-04_22-20-05-bug.zip)

**Comment by CaptainPuls** [comment]
Build storages for the material in the trucks.

**Comment by fregate84** [comment]
> Build storages for the maternial in the trucks.

I have a storage who are not full. But truck don't want to use it.
![Screen Shot 07-06-22 at 07 16 PM](https://user-images.githubusercontent.com/96617483/177607353-65d43af0-9c3c-49d5-a317-233e6e6c5c8b.PNG)

![Screen Shot 07-06-22 at 07 17 PM](https://user-images.githubusercontent.com/96617483/177607362-ee758413-20a7-42eb-b186-461e5eb67fe3.PNG)

**Comment by zuff-coi** [comment]
This issue has been resolved as of v.0.4.10 as multiple vehicles will travel at the same time to a storage and unload instead of waiting in line. This mess was cleared up in a minute in the latest version. 

Thanks for the report!
