### ISSUE TITLE
Blue Truck invisible

### ISSUE THREAD

**Issue by veldthui** [MaFi-Games/Captain-of-Industry-issues#509]
I have been trying to remove all my blue trucks and replace them with the next size up. Whenever I try and find it by clicking on the eye button it takes me to the building which creates the trucks. I assigned the truck to a mining tower and it does not go there and is not visible anywhere.

I would expect the truck to be visible and to be able to select it so I can scrap it.

Game version is v0.4.7a
[Nilaus Follow.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9042100/Nilaus.Follow.zip)

**Comment by MaFi-Games** [comment]
Duplicate  of #490

**Comment by MaFi-Games** [comment]
Duplicate of #490

**Comment by veldthui** [comment]
The latest update fixed the issue and the truck was seen dumping rocks so I was able to scrap it.
