### ISSUE TITLE
New rock formation appearing under dirt dumping site upon removal of dump site

### ISSUE THREAD

**Issue by Coheed1988** [MaFi-Games/Captain-of-Industry-issues#51]
**Describe the issue**

I created a dirt only dump zone on the second level of the island, ground was all dirt when I started. Several years later I start to use the dirt pile to refill various sections of the lower area. On digging back to ground level sections of the original terrain have converted to rock from dirt, with the natural stone texture.

**To Reproduce**
1. Load attached saves 'Sixth Run Magic Rock' and 'Sixth Run Magic Rock 2'
2. Inspect excavation zone on tier 2 of island.
3. See new rock.

**Expected behavior**
terrain to remain the original material prior to existence of dump zone.

**Additional context**
 - Game version: 0.2.11, however originally observed in 0.2.10a

**Attachments**

[Sixth Run More Magic Rock 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7310163/Sixth.Run.More.Magic.Rock.2.zip)
[Sixth Run More Magic Rock.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7310166/Sixth.Run.More.Magic.Rock.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting, this has been fixed for some time now :)
