### ISSUE TITLE
Resources voided when adding pipe to pipe that is beeing updated.

### ISSUE THREAD

**Issue by boldviking** [MaFi-Games/Captain-of-Industry-issues#510]
So this happened on stream today. I had a very long Tier 1 Pipe, which was in the process of being upgraded to Tier 2. The upgrade was already going along, all the resources where in place and the progress bar of the update was filling up.

I then connected a new Tier 1 pipe to the pipe that was being upgraded. It completely cancelled the upgrade, voided the resources spent on the upgrade and turned it back into a Tier 1 pipe.

I don't mind the cancelling of the upgrade. I do mind the voiding of resources ^^. I am pretty sure that connecting to pipe in upgrade, changed the pipe itself by adding a new segment to it. This segment was a full new segment that was unaware of the old segment and its upgrade.

**Comment by MaFi-Games** [comment]
Thanks for report, this was fixed and will be available in the next patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
