### ISSUE TITLE
Population count

### ISSUE THREAD

**Issue by teelCee** [MaFi-Games/Captain-of-Industry-issues#511]
**Describe the issue**
I paused normal pop growth in captains house.

**Expected behavior**
Worker count went down but pop count remained the same
**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Additional context**
 - Game version:: 0.4.7a

**Attachments**
If applicable, add save files (zipped) , screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like crashes or rednering glitches, also unclude Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. You might need to ZIP the attached files.

**Comment by L32GIT** [comment]
You either have no issue at all or you've poorly described your issue.
Pause pop growth edict has nothing to do with worker count. It only disables naturan increase of population (most left icon on the top bar)

**Comment by MaFi-Games** [comment]
Sounds like you have quarantine edict turned on

**Comment by MaFi-Games** [comment]
Closing as not enough information provided. Feel free to open new ticket with a save file or excact repro steps.
