### ISSUE TITLE
Concrete below U-shape connector sometimes stay after connector-deletion

### ISSUE THREAD

**Issue by dgzeij** [MaFi-Games/Captain-of-Industry-issues#513]
I've wondered for a long time where these concrete mini-tiles came from.

![20220705081629_1](https://user-images.githubusercontent.com/85814950/177262402-8d41da39-1817-449e-8007-425bd81cb5e5.jpg)

Now I got to see one in action:

![20220705081617_1](https://user-images.githubusercontent.com/85814950/177262472-55b8e1b0-ff93-425e-8703-79efc0f87b2f.jpg)

That is below where the connector was.

I tried to force this to happen on a similar setup nearby, but it didn't happen then. So not sure what exactly makes this concrete mini-tile stay behind after connector-deletion.

**Comment by dgzeij** [comment]
Was able to delete the concrete mini-tile on the first picture by recreating the connector and then delete it.

**Comment by zuff-coi** [comment]
This should be resolved as of v0.4.10
