### ISSUE TITLE
Truck stuck without recovery option

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#516]
**The issue**
A truck is stuck riding in a circle trying to deliver cargo to the building site even after being out of fuel. See video
https://user-images.githubusercontent.com/19796452/177497397-3459efa4-20c2-424c-a114-07af02dc9128.mp4
When paused at the proper moment, it's possible to select it, but the recovery button is disabled

**Expected behaviour**
Well, the truck should deliver its cargo, so .. Make this not happen.
But a solution for the future might automatically enable the recover button when a truck is out of fuel. But this might be tricky as the truck is barely visible and not reported anyhow, so there might be some truck manager that reports the truck if it don't finish any job e.g. last year.

**To Reproduce**
Load save, check solar building site on north.

**Additional context**
 - Game version: observed in 0.4.6, still present after upgrade to 0.4.7c

**Attachments**
[weeeeeeee.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9052706/weeeeeeee.zip)

**Comment by ParanoikCZE** [comment]
I think it would work but the bigger problem is that this should not happen as the truck was almost invisible. If it wasn't a truck delivering to a construction site, I would never find it.

**Comment by MaFi-Games** [comment]
This has been fixed in v0.4.8, thanks for reporting!
