### ISSUE TITLE
Pause icon not disappearing on cancellation

### ISSUE THREAD

**Issue by Yoekkul** [MaFi-Games/Captain-of-Industry-issues#517]
### Issue description

Paused construction icon does not disappear when cancelling upgrade

### Expected behavior

Paused construction icon should disappear when cancelling upgrade

### Reproduction steps

1. Select a housing block. 
2. Click upgrade. 
3. Click on pause construction. 
4. Cancel upgrade. 
5. The paused construction icon will remain above the building

### Game version

v0.4.7c

### Attachments

https://imgur.com/a/DStGWou

**Comment by jfischlmayr** [comment]
I think it's an overall problem not only with upgrading housings. It happened to me while upgrading from blast furnace 1 -> 2
![image](https://user-images.githubusercontent.com/43263789/183159443-8270f311-4594-465e-8578-bd445a6ee709.png)

**Comment by MaFi-Games** [comment]
Pause icons were removed so this should be obsolete.
