### ISSUE TITLE
cannot use "cut" either through side panel or using x key

### ISSUE THREAD

**Issue by navekio** [MaFi-Games/Captain-of-Industry-issues#519]
**The issue**
cannot use "cut" either through side panel or using x key

**Expected behavior**
I would expect to be able to move whole building and factory

**To Reproduce**
I press x button
draw yellow square around smelting config
then nothing.

(copy and shift copy work fine)
**Additional context**
 v0.4.5 supporters edition

**Attachments**
If applicable, attach a save file (zipped), screenshots, or log files to help us resolve the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like a crash or rendering glitches, also include Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. Thanks for taking your time writing this report!

**Comment by MaFi-Games** [comment]
Are you using it over blueprint or over already built entity? Can you provide screenshot?

**Comment by MaFi-Games** [comment]
Closing for now as there are no repro steps provided. Please open a new ticket once you have more information.
