### ISSUE TITLE
Vehicle refuels at nearest depot, not shortest path

### ISSUE THREAD

**Issue by JayJones65** [MaFi-Games/Captain-of-Industry-issues#52]
Vehicle paths to refuel appear to be calculated on straight-line distance computed at the time of need rather than length of path. 

Observed: Excavators (especially) will drive right past a fuel depot to get to a depot that was closer to where the excavator was working at the time it ran low on fuel. 

Repro: Mining pit with a single ramp in/out. Excavator is working at the far end (from the ramp) of the pit. Fuel depots are located next to the ramp (a) as well near the far end (but outside) of the pit (b). Excavator will drive up the ramp out of the pit, past the fuel depot (a) that it right there, and continue around the perimeter of the pit to refuel at the depot (b) that was nearest to where it HAD been working. 

Expected: Vehicles use the depot that is the shortest path, not the nearest straight-line distance.

**Comment by MaFi-Games** [comment]
Thanks for the report. It is unfortunately computationally prohibitive to test actual distance for refueling. However the behavior you described is not great either.

We will consider giving the player more control over refueling locations, perhaps assign mining tower to a certain fuel station could help.

**Comment by MaFi-Games** [comment]
Assigning on mining towers to fuel stations has been implemented some time ago. Closing.
