### ISSUE TITLE
wrong collapse message

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#521]
**The issue**
The game said my wall will collapse, but the graphique didn't show that.
![Screen Shot 07-06-22 at 07 34 PM](https://user-images.githubusercontent.com/96617483/177646271-81c26d3f-b0c3-4566-b7f3-df40732b9b91.PNG)
![Screen Shot 07-06-22 at 07 34 PM 001](https://user-images.githubusercontent.com/96617483/177646273-1e132c41-9a24-4b75-a037-6b8e0c6db98f.PNG)

**Expected behavior**
no message "wall will collapse"

**To Reproduce**
open the save

**Additional context**
Game version: 0.4.7a

**Attachments**
[bug mur.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9058103/bug.mur.zip)

**Comment by MaFi-Games** [comment]
I'm not sure I follow what is the issue?

**Comment by fregate84** [comment]
> I'm not sure I follow what is the issue?

I didn't see any white & red on the bottom of the wall, so why do I have a warning that the wall may collapse ?

**Comment by fregate84** [comment]
I don't see any overfilling  on my side. But I have not a good graphic card. could be hide by the texture quality.
![Screen Shot 07-08-22 at 07 38 PM 001](https://user-images.githubusercontent.com/96617483/178042752-60d35b33-02d7-4cc6-9246-82b6035fc595.PNG)
![Screen Shot 07-08-22 at 07 38 PM](https://user-images.githubusercontent.com/96617483/178042755-59061b9c-07ca-47ee-a566-91b1504ed4b1.PNG)

**Comment by zuff-coi** [comment]
The short edge has a little bit over the top of it. Perhaps we should have a warning for retaining walls collapsing because of overfill.

**Comment by MaFi-Games** [comment]
I don't think there is issue though. Yes overfill can cause a collapse but that's normal. I think tutorial on retaining walls will explain that.
