### ISSUE TITLE
0.4.7d Causing BSOD

### ISSUE THREAD

**Issue by spd3432us** [MaFi-Games/Captain-of-Industry-issues#523]
### Issue description

Ran just fine yesterday on 0.4.7c  Tried to start and as it loaded blue-screened my computer.  Did a fresh (clean) restart.  Verified video drivers current, relaunched with the only things active being steam and anti-virus software.  Blue-screened again.  Similar issue to what happened two weeks ago.  AMD A8-6600 with 16gb RAM.  Nvidia GeForce GTX 1060 with 6gb memory.  Attaching 3 log files (2 crashes tonight and the clean log from last night).
[22-07-06_20-26-06_0761.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060363/22-07-06_20-26-06_0761.log)
[22-07-06_20-56-23_3470.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060364/22-07-06_20-56-23_3470.log)
[22-07-05_21-37-47_0370.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060365/22-07-05_21-37-47_0370.log)

### Expected behavior

I expected the game to load and for me to be able to play.

### Game version

v0.4.7d

**Comment by spd3432us** [comment]
The save file as requested.

[YNSP - 039 - ship upgraded.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060502/YNSP.-.039.-.ship.upgraded.zip)

**Comment by spd3432us** [comment]
Autosave from 0.4.7c also crashed.  This zip has that saved game file and the two most recent log files.

[22-07-05_22-09-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060561/22-07-05_22-09-autosave.zip)

**Comment by MaFi-Games** [comment]
I was able to load this and re-saved it here in v0.4.7d: [YNSP - 039 - ship upgraded resaved.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9060565/YNSP.-.039.-.ship.upgraded.resaved.zip)

**Comment by MaFi-Games** [comment]
Can you check your windows system log? Game loading is very CPU intensive and can cause CPU overheating.

**Comment by spd3432us** [comment]
Didn't see anything in the system log.  CPU is not overclocked.  ASUS utilities show the CPU was at 127 degrees prior to launch.  Tried to load the file you re-saved for me and the CPU got to 163 degrees then the computer locked up.  Going to try changing fan settings in the BIOS to see if I can have it try to keep things cooler.

**Comment by MaFi-Games** [comment]
BSOD cannot be caused by a user software. That comes from drivers or hardware. Check Windows Event viewer for diagnostics infromation on the last crash: https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by spd3432us** [comment]
Ripped computer apart.  Applied new thermal paste between CPU and cooler.  Was able to load the save file that had locked it up.  Let it run for 35 minutes at triple speed.  CPU temp reached 150 degrees and stabilized.  After closing game, it dropped back down to 116 degrees within 5 minutes.
