### ISSUE TITLE
Trucks count in Vehicle managment window 

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#524]
### Issue description

i recently scraped all my blue pickup trucks. the screen show all Vehicle count right but when it comes to the idle state it is wrong as i have 0 blue pickup and it shows 3 are still idle
![image](https://user-images.githubusercontent.com/106634630/177696954-24424eb0-1e64-4a91-b2b7-d0495e4b00ee.png)

### Expected behavior

the window should display 0 idle or not show the truck and its status at all
as seen in this picture
![image](https://user-images.githubusercontent.com/106634630/177697103-64f49458-caf8-4fc5-9643-cc2897c1d768.png)

### Game version

v0.4.7D

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
