### ISSUE TITLE
Recipe calculations are not updated

### ISSUE THREAD

**Issue by ReeversXtreme** [MaFi-Games/Captain-of-Industry-issues#526]
**The issue**
Enrichment plant and settling tank:
Recipe calculations are not updated when toggling the timer switch.
Or is it possible that these machines are always working at 60 for the recipes? I have not been able to test it yet. Therefore it is mentioned here.

**Additional context**
 Game version: 0.4.7d

**Attachments**
![01](https://user-images.githubusercontent.com/108574177/177759397-52359079-a11b-4380-8dcf-044550fc89a3.jpg)
![02](https://user-images.githubusercontent.com/108574177/177759407-f9abc617-35cc-489b-8f1c-770973392338.jpg)

**Comment by MaFi-Games** [comment]
These recipes are correct, they work in 60 sec duration.
