### ISSUE TITLE
Landfilling problems

### ISSUE THREAD

**Issue by Torachal** [MaFi-Games/Captain-of-Industry-issues#527]
### Issue description

I am landfilling with rocks and slag to the lvl 1. When filling lvl 2 with dirt the edge square of rocks or slag collapses.

### Expected behavior

That the soild would mayby expand one square since it is loose

### Reproduction steps

1. Landfill with rocks or slag a couple of squares out of the shore.
2. Add an layer with dirt.
3. the edge square at lvl 1 collapses when the dirt is added ontop of it. This does not happen with any other square then the ones on the edge.

### Game version

v0.4.7.d

### Attachments

![coi error](https://user-images.githubusercontent.com/108879313/177782696-4c1e0a82-1f6f-4c78-9e22-cde961e7dfb1.jpg)

**Comment by ParanoikCZE** [comment]
Same here. But not only shores, but it's also like any change in the vicinity could start collapsing, even from below. I think that nice for this would be ability to set multiple areas to the tower to have a "repair" squad.

**Comment by zuff-coi** [comment]
Would you happen to have a save file of this happening? I'm having troubles reproducing it on my end.

**Comment by Torachal** [comment]
For that play nope. But it is easy to replicate.

If you dump rocks in the ocean and make a perfect straight shoreline and
then let a truck dump waste, dirt or sand the edge collapses.

Den lör 20 aug. 2022 kl 18:07 skrev Captain Zuff ***@***.***>:

**Comment by MaFi-Games** [comment]
We have improved our terrain simulation for Update 1. Each material now has its own collapse properties. So closing as fixed. Please file a new issue if you still run into it on the new version.
