### ISSUE TITLE
Half of manufactured items disappear on Conveyers II

### ISSUE THREAD

**Issue by G2KG** [MaFi-Games/Captain-of-Industry-issues#531]
### Issue description

If you connect _**flat/u-conveyers 2**_ **directly** to any **factory**(assembly,caster,stripper etc.) **half** of the produced items disappear. I have followed the items to storage but it still only fills up half of what it should be. Cant say if its same issue with pipes.

### Expected behavior

.

### Game version

v0.4.7.c

**Comment by MaFi-Games** [comment]
Fixed in Update 1 as we now render stacked products.
