### ISSUE TITLE
Total Water quantity doesn't match reality

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#532]
**The issue**
Total Water quantity doesn't match reality. There is no way there is 700K water anywhere, so there must be e.g. cooling tower losses not deducted properly.
![obrazek](https://user-images.githubusercontent.com/19796452/177875692-3f8c13c6-5ec9-47ce-9342-bd3ba39153f8.png)

**Expected behavior**
* Real values displayed
* Production tab contains Rainwater harvesters and Cooling towers production and consumption
* Statistics overall table contains Last year and Year before last year (maybe name it 'year -1' and 'year -2')
* Statistics overall table contains estimate for this year (like ThisYearValue * 360 / DaysOfCurrentYear)
* Statistics overall table contains contains "lifetime" value for a selected interval (so 120m/100y/Max)

**To Reproduce**
Load save, open statistics from products, select Water, select quantity tab

**Additional context**
0.4.7d

**Attachments**
[water.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9067532/water.zip)

**Comment by MaFi-Games** [comment]
Are you by any chance using some cheat engines for products?

**Comment by ParanoikCZE** [comment]
Nope, just vanilla, it's my first playthrough, started in 0.4

**Comment by MaFi-Games** [comment]
Circling back to this. This happened due to a bug in tracking quantities when executing partial recipes. So for instance cooling towers were causing this product leak. We have discovered this issue and fixed it in Update 1. So I'm marking it as resolved.
