### ISSUE TITLE
Food market accepting food before it is built via a transport

### ISSUE THREAD

**Issue by Memnoch72** [MaFi-Games/Captain-of-Industry-issues#533]
### Issue description

A market is still being constructed, but the belt to it is already finished, vegetables in this particular case.  The farm was harvested via the belt, and the belt transported the vegetables to the market that had yet to be built.  It was set to vegetables, and I already had one built, but the one it went to wasn't finished yet.  Sorry I missed the screen capture right before they finished going in, I had just noticed it
![20220707155933_1](https://user-images.githubusercontent.com/46352133/177885442-7e730273-e87a-4182-bb6c-012507ee43ef.jpg)
.

### Expected behavior

Pretty self-explanatory

### Game version

v0.4.7d

**Comment by JoeRoyle** [comment]
I managed to get a screenshot of it actually doing it
![20220707160716_1](https://user-images.githubusercontent.com/46352133/177885998-08e0b917-71b0-4073-a2af-fe84b88ad84f.jpg)
.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
