### ISSUE TITLE
Radar system 3 bug

### ISSUE THREAD

**Issue by Shadow-Blight** [MaFi-Games/Captain-of-Industry-issues#534]
### Issue description

When trying to research radar system 3, it tells me I need to research radar systems 2 first. I have researched ship bridge 2, and am not sure if radar systems 2 is a separate tech or got renamed or something. I don;t know if I am just overlooking the tech i need, or if this is a bug. 

### Expected behavior

I thought that I had the prerequisites needed for this tech and I would be able to research it. 

### Reproduction steps

I can't attach my save file for some reason. But I put in a word doc with some screenshots of my tech tree. 

### Game version

v0.4.7d

### Attachments

[CoI pics.docx](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9068308/CoI.pics.docx)

**Comment by ParanoikCZE** [comment]
As caption doesn't contain "Research" it means you need to discover this first on world map. Just go sink few ships and you'ľl get it. 

Anyway better caption or mouse hover hint would be nice in such cases as I was strugling there too.

**Comment by Shadow-Blight** [comment]
> I

I have explored all locations I can reach, and sunk every ship I've come across. See attached world map for reference. Maybe I'm missing something here
[CoI pics 2.docx](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9075242/CoI.pics.2.docx)

**Comment by ParanoikCZE** [comment]
I think I was in same situation. In some moment, my Fuel reserves just improved and I was able to explore further. Since today, I don't know what happened.
(btw you can insert images here, no need to put them in word)

**Comment by MaFi-Games** [comment]
We have added a tooltip to explain that it needs to be discovered on the world map. But we have plans to improve visualization of these techs even further.
