### ISSUE TITLE
Maschine BUG

### ISSUE THREAD

**Issue by Nemesssis** [MaFi-Games/Captain-of-Industry-issues#535]
### Issue description

Sometimes Fabrics say they havnt materials, although they get the materials over belts and boths belts are full. If u then  activated LKW Import "ON" then the materials goes in and the fabric work

### Expected behavior

Materials goes in on Lkw import off too

### Game version

v0.4.7d

**Comment by MaFi-Games** [comment]
Please provide us screenshot or save file.

**Comment by MaFi-Games** [comment]
Closing as we don't have enough information.
