### ISSUE TITLE
Clicking the abandon project button doesn't do anything

### ISSUE THREAD

**Issue by ericjorgensen** [MaFi-Games/Captain-of-Industry-issues#536]
### Issue description

Projects initiated from the world map appear when clicking on the shipyard:

![image](https://user-images.githubusercontent.com/1682088/178026939-945bb479-1506-43fe-9604-ff3ffb8f8b96.png)

Clicking the red X button doesn't abandon projects, so they will just sit there until fulfilled.

### Expected behavior

Clicking the red X button should abandon the project and make it disappear until the player initiates it again from the world map.

### Reproduction steps

1. Initiate a settlement request from the world map (e.g. providing 100 construction II parts)
2. View the request by clicking on your cargo shipyard
3. Click the X button to abandon the project
4. Nothing happens (the project doesn't disappear)

### Game version

v0.4.7d

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
