### ISSUE TITLE
Liquid dump does not accept sea water

### ISSUE THREAD

**Issue by Burnrate** [MaFi-Games/Captain-of-Industry-issues#54]
**Describe the issue**
Liquid dump does not accept sea water

**To Reproduce**
1. Pump some sea water into storage
2. Try to delete storage
3. No one picks up the sea water!  Needed to build a desal plant to pump it out and dump the results.

**Expected behavior**
Sea water should be dumpable

**Additional context**
 - Game version: 0.2.12

**Attachments**
-

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
