### ISSUE TITLE
Game crashes - First time I get a bug report

### ISSUE THREAD

**Issue by jck5000** [MaFi-Games/Captain-of-Industry-issues#541]
### Issue description

UPDATE: This actually is a new issue. I had problems before:

Some days, when I start the game, it'll crash a few seconds to minutes into the game. Sometimes, it goes back to windows, sometimes with a small CoI window, a progress bar and a "unity" headline with too many numbers to read that quickly. Sometimes, my computer reboots, sometimes, it tries to reboot but is stuck an some black screen.

Couldn't figure out yet what causes it. It's not updates.

Running on SSD secondary drive i5-2500K / 12 GB with a GTX1060 6GB. 

See images for the error message - never got one before. Maybe make that copy-pasteable.

![fehler1](https://user-images.githubusercontent.com/107056028/178099931-f268f249-fd3c-49ee-86ee-f1d1ce51ef64.PNG)
![fehler2](https://user-images.githubusercontent.com/107056028/178099933-927d4f5b-8f54-47e2-b134-158feb8aed93.PNG)

Now, the game doesn't even try to start with the attached savegame (clicking "continue" and "load" both will result in the error message

### Expected behavior

The game not crashing would be nice

### Game version

v0.4.7d

### Attachments

[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9076201/Player-prev.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9076202/Player.log)

I guess the savegame is corrupted: - Doesn't change the crahing issue.

[Sa 09 c.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9076211/Sa.09.c.zip)

**Comment by MaFi-Games** [comment]
This seems like a harddrive issue to be honest.

**Comment by jck5000** [comment]
My current best guess is that my old hardware has an issue with the latest steam client, because the crashes also happen without starting the game (it's my gaming desktop, i have a secondary one for work and "quiet power saving mode", so I tend to immediately start the game. But the crashes also happen without the game. **You can close this ticket**; nothing you can do here (maybe make a non-steam version; I never liked steam anyways). And thank you for reading; great customer service. And great game!

**Comment by MaFi-Games** [comment]
Thank you. I would consider scanning the drive via CHKDSK utility or other tools. That could be the cause. Because we don't expose a save file until it is fully written to hdd.  So crashes should not affect the fact that it got corrupted. https://www.thewindowsclub.com/disk-error-checking-windows-8#:~:text=To%20begin%20the%20scan%2C%20right,asked%20to%20check%20the%20disk.

**Comment by Bracket5** [comment]
Same issue but can not find why it crashes? (PC spec below)
**CPU**|[Intel Core i7-9700K 
**GPU**|[Nvidia RTX 3060 12GB 
**SSD**|[Samsung 980 Pro NVMe PCIe M.2 1TB 
**RAM**|[Corsair CMW16GX4M2D3600C18 2x8GB106.9%
**MBD**|[MSI MPG Z390 GAMING PLUS (MS-7B51)
