### ISSUE TITLE
captain of industry

### ISSUE THREAD

**Issue by Michaelboon01** [MaFi-Games/Captain-of-Industry-issues#543]
### Issue description

On a mine control tower you can designate what products you want to dispose of but when i click to dispose of limestone it doesnt it just says No available place to dump product 

### Expected behavior

i except the tucks to dump limestone in the landfill

### Game version

v0.4.7

**Comment by utdrmac** [comment]
@Michaelboon01 Make sure you have designated dumping zones. Just because you tell the mine tower it can dump doesn't mean it will. You must make space for it. Press 'z' to bring up the "green dump zones" and place down an area.

**Comment by MaFi-Games** [comment]
Closing as there is not enough information.
