### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by cw64** [MaFi-Games/Captain-of-Industry-issues#544]
### Issue description

0.4.5b

1. Trucks assigned to excavators leave with materials to be dumped before being full when allow partial loads is off.

2. Resource overlay settings (show coal, hide sand etc.) and entity window positions are not saved and have to be set everytime the game starts.

3. 1280*720 resolution is playable but has some issues with additional context windows (i.e. constructing/destructing/upgrading) being off screen in cases where the entity window is large (e.g farms).

4. Haul trucks (all trucks?) do not prioritise fule stations over diesel storage when refueling

5. Memory. Can't overwrite existing save because out of memory, can save to new file, Less than 2 of 8Gb system memory used and1Gb swapfile

0.4.7a

6. Boiler won't pass exhaust output into connected pipe if fuel gas is only selected fuel source (CO2 output) causing boiler to stop running if full of exhasut.

7. Ship access blocked, no warning given when marking ocean tiles to be filled, once filled it's impossible/extremely difficult to recover.

8. Excavators can climb out of the reach of fuel trucks, and will climb over terrain that is marked for excavation to reach tiles at a higher elevation moving out of the reach of fuel trucks.

0.4.7d

9. All trucks stop moving when collecting from the same storage as each truck is getting loaded.
A line of several trucks all heading for the same collection point all stop moving when one reaches it and collects a load.

10. Tankers assigned to transport oil between a full storage and an empty one sit there doing nothing while regular trucks come and transport the oil instead.

11. Fuel truck takes fuel to import location only to be beaten to it by a fluid tanker and has to dump its load at the ship yard.

12. Excavaion/Dumping markers persist after level has been reached / Existing markers interfere with the marker setting set at the pointer.

### Expected behavior

1, Trucks wait to be filled completely defore dumping materials. Saving fuel and reducing strain on the logistics system

2. Overlay settings and window positions are either saved globally (preferred) or in the save file

3. Secondary windows are auto placed to the right side of main window when the display resolution and scale causes them to be off screen. Having scaling options lower than 80% may also help.

4. Fuel stations set to allow all vehicles to refule have a refule priority lower than all diesel storage, AND/OR trucks go to the nearest available diesel location when refueling ignoring export priority.

5. Game uses sytem memory correctly, freeing memory spaces that aren't acessed frequently regularly, and not writing to memory when should be writing to disk.

6. Boiler setting has no effect on the ability to export materials to connected pipes (should be the same for all buildings with connected outputs)

7. The game does not allow dumping at tiles which can interfere with ship transports due to run off because of the assigned tile's height.

8. Excavators can not traverse terrain that puts them out of reach of fuel trucks, nor dig below the set depth (excavators will also remove material beyond a wall when digging to the walls base in an adjacent tile, or from the other side of a wall when the wall bisects a tile and the tile is being excavated.

9. Trucks do not stop moving across the map. Nor queue up waiting to collect and neglecting other jobs. Truck queue length for a specific job needs to be limited to 2 or 3 maximum so that trucks don't neglect other jobs while sitting in a queue doing nothing. And trucks shoud continue towards their pick up point regardless and not stop halfway across the map.
Check to see if the same thing happpens when there is a queue to tipp the load.

10. When import/export routes are set, AND a vehicle is assigend to it, the vehicle fills up as soon as possible and delivers the material to the import location regardless of there being space to accept the load. If there is no room to take the load the vehicle will sit there and wait at the delivery location untill it can. The general pool of vehicles have no access to defined routes with assigned vehicles.
When import/eport routes are set, AND there is NO vehicle assigned to it. The logistics pool can NOT take material from the export point to any other location than the defined import point.

11. Again this is another example of multiple assignments being made instead of a single one or two that fits the exact load required. Logistcs has to be rewritten on a per vehicle load basis. Storage is requesing an import/export -> import/export is assigned to an available vehicle -> As far as the logistics system is concerned the request has now been filled and other vehicles are NOT assigned. Fully loaded trucks takes priority. If set, a full load is taken and delivered regardless of other settings, the only exception being when a storage is being trashed and there is a residual amount to be removed. If an import location can not accept a full load the vehicle will tipp what it can and will wait at the location to periodically tipp again or deliver the rest to another location if a new request is made.

12. When dump/excavate level has been attained marker is auto removed. If I set the dump/excavate tool to flat at level 02 nothing changes it. It's not 02 based on where the pointer happens to be when I set it and higher or lower if the pointer moves to higher or lower terrain its flat and 02 absolute. It's also not changed when connecting with existing markers. If I wanted to have a incline I wouln't have set the tool to be flat. The minor ease of having the tool change to fit the existing layout is vastly overshadowed by the annoyance of it happening when not required. Terrain editing is extremely cumbersome due to the effort required to stop the game from changing the tool settings, aswell as having to remove every marker manually once it has served its purpose and is no longer needed.

### Reproduction steps

1. Excavate a resource with a single excavator on a tile with multiple resources with one 1 or more trucks, turn patial loads off. Trucks still leave with partial loads

2. Start a game, open resource overlay, hide some stuff. Click on an entity, move the window to another location on screen. Save the game, quit,, load the save, do it all again because the changes were not kept.

3. Set resolution to 1280*720 and scale to 80%. Build/upgrade/destroy any building with a large window size and the seconday options are off the screen with main window as high as possible on screen

4. Have haul trucks working at A, diesel storage with export priority 1 at B, and a stocked fuel station set to allow all vehicles to refule somewhere on the path between the two at C. Watch haul trucks (all trucks?) ignore the fuel station and go to the diesel storage

5. Set system resources to 8Gb memory and 1Gb swapfile, play for hours, save the game to an existing save, and fail becaue of out of memory, but magicaly succeed when saving to a new file. If it's possible to save to a new file then there is no good reason to not be able to overwrite an old one. something is clearly wrong here and it isn't the lack of system memory.

6. Set up a boiler with connected fuel gas and heavy oil supply. Run the boiler on oil untill exhaust is full, disable oil burning and select fuel gas only, ensure waste gas output is available, boiler will not run and will not vent exhaust.

7. Dump at level 02 on the shoreline close/next to a dock, or higher further away.

8. See attached excavator save. Some how the excavators managed to dig below the level set and create a dip in the terrain. This may have been caused by digging uphill to a point level with the ground that is outside of the mining area. Or it may have been causd by two excavators working on the same tile.

9. See attached stutter save. Hoard a large amount of a resource that can be dumped, then empty it all with priority 1

10. See attached nojobs save. Assign logistics route from a full fluid storage to an empty one, assign fluid truck, watch it sit there and do nothing as regular trucks come and do the job instead.

11. See attached fueltruck save. It was caught just after the truck failed to deliver and is now heading to the port to dump the load. This was the second time it happend and will no doubt happen again if the game is left to run.

12. Use the excavate/dump marker tool with any degree of fidelity or complexity.

### Game version

See each numbered issue above, game version is the same as previous issue unless stated otherwise

### Attachments

Attachments pending.

**Comment by cw64** [comment]
[stutter.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9078864/stutter.zip)
[excavators.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9078869/excavators.zip)
[fueltruck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9078875/fueltruck.zip)
[nojobs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9078877/nojobs.zip)

**Comment by ParanoikCZE** [comment]
1) Not bug, feature .. they are leaving not full because excavators require to dump another material and there is no truck to do .. assign more trucks
4) They are taking the closest. Disable export on storage.
6) I'm not getting your description. Not sure if you have two recipes selected or try to combine CO2 and Exhaust pipes from different boilers. However, gases cannot be mixed. Still, I think there might be a slight improvement in UI that disallows the usage of an incompatible recipe with different exhaust types.
7) I didn't run into this issue but afaik there is somewhere button to clean it up. And also, you can rebuild your shipyard elsewhere.
8) Yes, idiot driver syndrome :)
9) #474
10) I think it's kind of priorities and reserved jobs, but you can set storage to not use not assigned trucks.
12) This is a feature, it might be to have this as a nice to have option, but I don't think removing markers is such a big deal.

Anyway. I'm not talking for the team, but reports like these might get most probably ignored (at least I would not track them anyhow) as they would require too much work to manage. Please split them so they can be handled and/or answered/searched/tracked one by one. Also, if you join Discord, you can discuss most of these and get explained how things work.

**Comment by utdrmac** [comment]
Github issues are meant to have 1 item, not multiples. Multiple entries in a single issue make it difficult to track fixes. Plus, did you search github first to see if any of these are already reported? Some of them look like duplicates of already reported issues.

**Comment by cw64** [comment]
> 1. Not bug, feature .. they are leaving not full because excavators require to dump another material and there is no truck to do .. assign more trucks
> 
>     2. They are taking the closest. Disable export on storage.
> 
>     3. I'm not getting your description. Not sure if you have two recipes selected or try to combine CO2 and Exhaust pipes from different boilers. However, gases cannot be mixed. Still, I think there might be a slight improvement in UI that disallows the usage of an incompatible recipe with different exhaust types.
> 
>     4. I didn't run into this issue but afaik there is somewhere button to clean it up. And also, you can rebuild your shipyard elsewhere.
> 
>     5. Yes, idiot driver syndrome :)
> 
>     6. [Trucks pathfinding stuttering #474](https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/474)
> 
>     7. I think it's kind of priorities and reserved jobs, but you can set storage to not use not assigned trucks.
> 
>     8. This is a feature, it might be good to have this as a nice to have option, but I don't think removing markers is such a big deal and also when you are digging bigger stuff, random collapses occur also into already done sectors, so it doesn't make sense.
> 
> 
> Anyway. I'm not talking for the team, but reports like these might get most probably ignored (at least I would not track them anyhow) as they would require too much work to manage. Please split them so they can be handled and/or answered/searched/tracked one by one. Also, if you join Discord, you can discuss most of these and get explained how things work.

1. If game isn't obeying it's own defined option it's a bug not a feature. The whole point of having the option is being ale to play the game in a fashion supporting that option. If the player wishes to have partially loaded trucks they can by selection that option. If the player wishes to have only fully loaded rucks then currently they can't because actually the option doesn't exist. Make the option actually work.

2. No they're not that's why I reported them not doing that.

3. Read through it again until you do. It is stated plainly and clearly.

4. where exactly is the option to do this? Rebuilding the shipyard isn't an option. I already stated that reverting this once it happens is extremely difficult/impossible.

5. No. Please Keep your glib remarks to yourself if you can't actually fix the problem. I don't need your inane chit chat. If you want to socialise go use a social media website.

6. No. They're not stuttering because of path finding, they're stuttering because of the way they interact with the buildings and/or because each vehicle is not coded as an independent entity.

7. The point was to use the assigned trucks

8. It's bad design, and created needless chores

If the devs want issues to be reported in a certain way then they should state this to be the case. I don't have a lot of time to spare working on this, and discord is not an option. I've been playing video games for longer than most of you have been alive. Take my advice or leave it. I'm not interested in a discussion about whether you think it's good or not.

**Comment by ParanoikCZE** [comment]
> 
I think Github broke my numbering in the previous post :/ 

1 - So, how would you imagine having one excavator with one truck, but digging 3 different materials? 
8 - No, your idea makes no sense, as I described and like 99% of people will not use it.

And, I'm ignoring the rest. Again, an issue tracking system is not a trashbin where you just throw every issue you found and leave it to others to sort. If you want to do such reports, do it on discord. One issue per item is not project related, it's a general common and commonsense rule.

**Comment by zuff-coi** [comment]
Please divide this post into multiple issues. It is impossible for us to track a post like this. If you open an individual issue for each one we will be able to help!

Thanks.
