### ISSUE TITLE
Problem im Spiel mit dem Essen

### ISSUE THREAD

**Issue by Pillepalle12345** [MaFi-Games/Captain-of-Industry-issues#546]
### Issue description

Hallo, ich hab da zwei Probleme im Spiel.

1. Mir wird angezeigt das kein Vorrat an Essen da ist, obwohl  die Lager voll sind. Dies geschieht von einer Sekunde auf die andere.
2. Einige Bergbaukontrolltürme verschwinden einfach im Spiel.

### Expected behavior

1. Zu erwarten ist das bei vollem Speicher das Essen vorhanden ist.
2. Die Kontrolltürme nicht einfach verschwinden.

### Game version

v0.4.7d

### Attachments

[Kein Essen.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9079398/Kein.Essen.zip)
![20220710173749_1](https://user-images.githubusercontent.com/109033324/178152671-f04cb82a-b181-4fd3-879b-7a308b415f12.jpg)

**Comment by MaFi-Games** [comment]
![image](https://user-images.githubusercontent.com/90082857/178358978-782c770e-9faa-421e-8f9a-616367964e45.png)
It's because you have a separate settlement with people living there and you didn't connect any food market there.

**Comment by Pillepalle12345** [comment]
Hallo,

 

OK, that's strange, how is one supposed to know and see that? There is no indication of this anywhere.

 

And what about the second problem, that the mining control towers just disappear?

 

Von: Captain of Industry ***@***.***> 
Gesendet: Montag, 11. Juli 2022 23:11
An: MaFi-Games/Captain-of-Industry-issues ***@***.***>
Cc: Pillepalle12345 ***@***.***>; Author ***@***.***>
Betreff: Re: [MaFi-Games/Captain-of-Industry-issues] Problem im Spiel mit dem Essen (Issue #546)

 

 <https://user-images.githubusercontent.com/90082857/178358978-782c770e-9faa-421e-8f9a-616367964e45.png> 
It's because you have a separate settlement with people living there and you didn't connect any food market there.
