### ISSUE TITLE
Can't demolish building with assigned truck

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#547]
**The issue**
Deconstructing a building won't start if there is a truck assigned and 'Accept assigned only' option is enabled.

**Expected behavior**
The assigned truck deconstructs the building itself.

**To Reproduce**
- Build any storage (tested with Loose T1)
- Assign truck
- Enable 'Accept assigned only' option
- Deconstruct building
- Wait for eternity to get it done

**Additional context**
 - 0.4.7d

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
