### ISSUE TITLE
a loop is created with storage and belts and trucks even when trucks are assignt

### ISSUE THREAD

**Issue by HarmLast** [MaFi-Games/Captain-of-Industry-issues#549]
### Issue description

I have an issue i want to mine efficent so i set up loose storage near the mine and the trucks are filling these storage. The storage is connected to belts to a central place with bulk storage and as overflow some lose storage to get rid of the materials.
so i assigend 8 trucks to the loose storage and set up an export route to a mine tower with dump enabled but te trucks of te overflow storage are filling the loose storage of the mine tower where the excavators are mining. so materials go round and round
[01-024.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9079914/01-024.zip)

### Expected behavior

the trucks dump the materials at the designed mine tower

### Reproduction steps

1 load the file,
2 if you see the main shipyard in front of you watching from the see, on your right are 4 iv loose storage units, on top is one full of rock. that is the one where this is all about

### Game version

v0.4.7D

**Comment by ParanoikCZE** [comment]
Just assign mine's export route to it, nothing else will be dumped here.

**Comment by HarmLast** [comment]
Yes thats the simple way, but thats not what I want to achieve. I have set a route from the loose storage to the dump mine. And that route is being ignored.

**Comment by ParanoikCZE** [comment]
Ok, I've checked your save, it happened to me once for storage next to iron mining site. So, just set right one to not import or assign it to mining tower as well. If there are more such storages, please describe it more accurate.

Still, this looks pretty weird to me. See my observations: 
![obrazek](https://user-images.githubusercontent.com/19796452/178213228-e416675c-2a24-41d6-91e3-44fd64c11d0a.png)
Trucks are assigned to storage on right (start of blue curve), storage assigned to dumping tower, tower has valid dumping area (marked green).
There is no valid short route so they are taking long trip (blue curve), but sometimes, they decide to dump cargo in orage area, that has unassigned storage accepting rock. Storage is cascade buffer storage (among real mining storage and belt). What I've seen is that truck then went to refuel station (in red), so maybe refuelling actually breaks some routing rules.

**Comment by HarmLast** [comment]
Thanks for your response! I tested it and it turned out with truck import off the cascade buffer storage did not receive any goods anymore. So the loop stopped. 
But if I assign a route to dump can trucks ignore the route? And fill other storage first? 
If that's not the case I will see if I can reproduce the case again.

**Comment by ParanoikCZE** [comment]
As I said, it's weird at least, someone from the team needs to confirm/investigate.

**Comment by zuff-coi** [comment]
This issue doesn't seem to be occurring in your save file in v0.4.10, could you test and see if this is still happening?

If so, can you provide another save file so we can test more? Thanks!

**Comment by MaFi-Games** [comment]
Seems like the issue was fixed (we did lots of improvements in logistics). Please file a new ticket if it happens on latest version. Thanks!
