### ISSUE TITLE
repair Cargo Ship Mission Bug

### ISSUE THREAD

**Issue by Hauklotz** [MaFi-Games/Captain-of-Industry-issues#55]
**Describe the issue**
i accept 2 mission of the damaged cargo ship at the same time and load the materials in the harbor at the same time. i repaired one cargo ship, but the i can´t repair the second. the harbor said all cargo are load, but it isn´t on my ship

**To Reproduce**
1. accept 2 repair mission at the same time
2. activate the ironplate loading for both cargo ships at the same time in the harbor
3. deliver the iron plates to one of the ships an go back to base
4. the shipyard says all requiered cargo are loaded but there is no ironplate on the ship (see second screenshot)

**Additional context**
 - Game version: v0.2.12

**Attachments**
3 screens about the behaviour and the broken savegame
![Screenshot_1](https://user-images.githubusercontent.com/8274799/136815260-7052c743-a8f5-49a7-948a-bcb176efacba.png)
![Screenshot_3](https://user-images.githubusercontent.com/8274799/136815266-26043cd1-1a3d-47d2-b48e-8c713316e7c1.png)
![Screenshot_4](https://user-images.githubusercontent.com/8274799/136815271-cec1bbbd-cc6b-4f62-ba8f-b8cb270b4719.png)
[cargo_ship_bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7323601/cargo_ship_bug.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report, we need to investigate this further
