### ISSUE TITLE
[Minor] Unsaved progress lost message is displayed after a while in menu

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#550]
**The issue**
When you save and leave, no message is displayed, however, if you save and wait in the menu for a while doing nothing, the message is displayed when trying to quit.
![obrazek](https://user-images.githubusercontent.com/19796452/178247947-40fdf66a-3c58-4052-9827-24d1a998e5dc.png)

**Expected behavior**
The internal clock stopped in the menu.

**To Reproduce**
Save the game, click dismiss, go grab a beer or lunch, press quit => unsaved progress message displayed.

**Additional context**
0.4.7d

**Comment by MaFi-Games** [comment]
This works as intended. It is fairly niche case to support.

**Comment by ParanoikCZE** [comment]
Ok then :)
