### ISSUE TITLE
Typo on Consumption Rate for Waste Sorting Plant

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#551]
Reads "20" when it should be "60"
![image](https://user-images.githubusercontent.com/108291414/178310196-16fab786-0692-4d2b-a45f-54f87d45702c.png)

**Additional context**
 - Game version: 0.4.7c

**Comment by ParanoikCZE** [comment]
I don't see any issue, for me, it's 48/20 as a single production batch. Only thing is that rest of the values are in /60 and the whole recycling centre doesn't have 'show /60' switch nor use settings from elsewhere.
![obrazek](https://user-images.githubusercontent.com/19796452/178328034-76467afd-66d9-4634-80af-d8ef64b7132d.png)

**Comment by MaFi-Games** [comment]
This should now be fixed in v0.4.8 which is available in the Experimental branch on Steam. You can also wait a few days for the patch to make it to the production version.
