### ISSUE TITLE
Nuclear Reactor/Transport Oddity -- potentially multiple bugs 

### ISSUE THREAD

**Issue by storm6436** [MaFi-Games/Captain-of-Industry-issues#552]
Version: v0.4.7d
Expected behavior: Feed uranium rods to reactor on initial power up, get tons of steam

Observed behavior: Feed uranium rods to reactor, watch it eat them.

Actions leading to observation: (Some details included to present order of construction and usage, just in case this is a transport bug not a reactor bug)

1. place reactor ghost
2. Realize you've got problems elsewhere, pause construction and pause operation (purple and yellow pause icons)
3. Come back after fighting the maintenance shortfall, unpause construction.
4. Facepalm because your 3AM self the night before evidently forgot uranium pellets need to be made into rods first.
5. Build manufacturer, empty pellets belt  into manufacturer via building new stretch of belt and reversing original belt onto it.
6. Splice in new storage for rods, connect manufacturer to storage, storage to old belt, and delete unneeded belts.
7. Save game.
8. Unpause reactor operation, set to 1x output, go fight fires elsewhere
9. Realize you're still getting steam shortfalls in attached refinery several minutes later when the extra 96 steam should have forced several boosted coal plants to shut down instead.
10. Check coal plants, still running at full capacity, plenty of coal/biomass
11. Check nuclear plant, see a pair of rods enter reactor while clicking on reactor to get UI panel.
12. Reactor inventory empty, no rods present.
13. ???
14. Watch next pair of rods enter. Reactor inventory remains at zero
15. ?!?
16. Next pair of rods enter reactor. Reactor spins up, inventory: 1 rod.

Further QA/Isolation steps: (Note: this is from memory, some details are a smidge fuzzy because I figured it'd be quick and didn't bother to write them down. <Narrator voice: it wasn't quick and he should've written it down>)

Attempt 1
1. Revert to save made in initial action 7 above. Spend a long time watching loading screen -- 1+ minutes per reload, with an Samsung SSD and an AMD 3950x... not sure why reloading saves takes so long, and why the first tick on the loading bar sits there for almost a full minute before moving at all, do notice the wait time gets worse with each additional reload, might be a memory leak or something similar; didn't check task manager to verify heap growth, was focused on isolating reactor bug, sorry. Also, game is unresponsive during that first tick, can't open steam overlay, and actions may result in windows deciding the process is hung and asking if you want to kill it.
2. Leave reactor paused, set power to 1x, queue ~8 rods on the belt.
3. Unpause reactor. Reactor eats all rods, no spin up.
4. Pause belt.
5. Let more queue up in storage (don't remember exact number, forgot to write that down before going to bed)
6. Unpause belt. Reactor eats them all.
7. Next pair enters reactor while I'm scratching head, reactor spins up, inventory: 1 rod.

Attempt 2
1. Revert to save from initial action 7.
2. Boost rod factory, queue ~12 rods onto belt.
3. Set reactor power to 1x, unpause reactor.
4. Reactor eats them all.
5. Next pair enters, reactor spins up, inventory: 1 rod.
6. Look through UI mouseovers, hoping to find an entry saying "Requires X rods on initial startup to spin up." Find nothing. Realize that the number of rods eaten so far hasn't been consistent anyway, so that was unlikely in the first place.

Attempt 3
1. Revert to save from initial action 7.
2. Boost rod factory, queue ~16 rods onto belt.
3. Set reactor to 1x power, unpause reactor.
4. Queue belt section for deconstruction (and pause deconstruction) to send rods into reactor 1-2 at a time.
5. Reactor eats them all.
6. Next pair enters while scratching head, reactor spins up, inventory: 1 rod.

Attempt 4
1. Revert to save from initial action 7.
2. Boost rod factory, queue ~20 rods onto belt.
3. Set reactor to 1x power, unpause reactor.
4. Pause belt to stagger rods into reactor 1-2 at a time.
5. Reactor eats them all.
6. Next pair enters while scratching head, reactor spins up, inventory: 1 rod.

Attempt 5
1. Revert to save from initial action 7.
2. Boost rod factory,
3. Get tired of constant wait for rods and reloading
4. Pause storage->reactor belt, build up ~20 rods in storage, make new save with rods in storage.
5. Set reactor priority to 1, enable truck import.
6. Let trucks take rods from storage. No spin-up.
7. After a few 4-letter words, click on reactor. Rod inventory: ~20! 
8. Realize I forgot to set power output to 1x; it's still at 0x.
9. Set output to 1x
10. Rod inventory disappears altogether.
11. More 4-letter words and head scratching.
12. Truck delivers unknown number of rods a minute or so later
13. Reactor spins up. Inventory: 1 rod.
14. Expand number of letters in words used to n letters, where level of dissatisfaction correlates with higher n.

Attempts 6+
1. Revert to save from Attempt 5 (Or save from step 3 for attempts 7+)
2. Deconstruct storage->reactor belt altogether.
3. Make new save
4. Rebuild storage->reactor belt
5. Follow same pattern from attempts 1-3 to verify if new belt behaves the same way. It does.
6. Eventually have an attempt that eats noticeably fewer rods than previous attempts.
7. Say 'fsck this, I'm not getting paid. I'll file a bug report and go with this save since I've lost fewer rods.'
8. Give reactor the middle finger, file bug report.

[Start Nuke.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9088762/Start.Nuke.zip)

**Comment by MaFi-Games** [comment]
I think this confusion happened because we were not showing rods in the reactor (there is at least 16 rods needed for the reactor to work) but they are not displayed in the inventory. This has been fixed some time ago. Please file a new issue if there is still some confusion around it.
