### ISSUE TITLE
Copy/paste Mine Control Tower does not copy import/export settings

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#553]
### Issue description

When I shift-V on a mine control tower to copy its settings to another tower (because I want to move this tower), I expect all settings, including import/export routes to also be copied. This is not the case.

### Expected behavior

See above.

### Reproduction steps

1. Place MCT. Assign route from a storage box.
2. Place another MCT.
3. shift-v over first mine control to enter copy/paste mode
4. click second MCT to paste
5. esc, then click on second MCT. Notice that no import/export was copied.

### Game version

v0.4.7.d

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8.
