### ISSUE TITLE
Rainwater harvesters average water yield has very poor accuracy

### ISSUE THREAD

**Issue by tjayharvey** [MaFi-Games/Captain-of-Industry-issues#554]
### Issue description

Rainwater harvesters list an average water yield that is either way too low or doesn't account for map settings. I am playing a map on max rain (Less Dry, and 80% more water yield from rain), and the rainwater harvesters consistently underreport their output by a large amount. I ran 3 concrete mixers with efficient concrete (total 18 water use / month) off 2 rainwater harvesters (total estimated water production 8.2 / month) - though possibly not full time.  2 copper lines (12 water / month) run off 2 rainwater harvesters (8.2/month). I don't know whether the estimate for rainwater is just way off or doesn't account for the map settings properly. Some uncertainty is reasonable because rainfall varies per year, but it ought to be closer than it is.

A quick test with one rainwater harvester hooked up to lots of storage yielded the following yearly values over 5 years:
94
95
94
96
93

This suggests the correct average should be closer to 7.9 water produced per month.

### Expected behavior

Rainwater harvesters accurately report their expected average monthly yield given the map settings.

### Reproduction steps

1. Start a new game with settings 80% more water from rain and Less Dry
2. Research up to the point where rainwater harvesters become available.
3. Build a couple rainwater harvesters, a lot of storage, and connect the two.
4. Observe the yearly water accumulation.

### Game version

v.0.4.7d

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
