### ISSUE TITLE
computing power requirements for the launch vehicle shop are not shown

### ISSUE THREAD

**Issue by nezamay** [MaFi-Games/Captain-of-Industry-issues#555]
### Issue description

computing power requirements for the launch vehicle shop are not shown

### Expected behavior

computing power requirements for the launch vehicle shop are not shown

### Game version

v0.4.7d

### Attachments

![cap3](https://user-images.githubusercontent.com/17605020/178421567-97875452-eec1-48fe-9367-7a3c8e8fbb44.png)
![cap4](https://user-images.githubusercontent.com/17605020/178421574-f7828cba-10b5-424f-890e-443828521538.png)
![cap5](https://user-images.githubusercontent.com/17605020/178421580-6245e52e-16c8-48cc-b3d0-364a424899fd.png)

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in v0.4.8.
