### ISSUE TITLE
Pipe Connector is leaking

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#556]
### Issue description

There is a group of eight Diesel generators. They are paused. The pipe supplying them consumes 60 Diesel per 60s.

### Expected behavior

There should be no Diesel consumption at all on that pipeline.

### Reproduction steps

Load the attached PipeLeakBug save file. Observe how Diesel keeps flowing towards the paused Diesel generators.
E.g. toggle direction of pipe to fluid storage, to see how fast the storage gets drained.

I think 1st I'd had more than one leaking connector there. Then I tried fixing it (forgot details), but just in time realized, I need a save file.

I attached the autosave file where this group of generators was still just a blueprint, copied from the other eight generators. Just in case the bug is already in there. Though I think it is a building sequence issue.

### Game version

v0.4.7d

### Attachments

[save_22-07-12_00-25-01_PipeLeakBug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9093236/save_22-07-12_00-25-01_PipeLeakBug.zip)
[22-07-11_23-38-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9093263/22-07-11_23-38-autosave.zip)

**Comment by RealisticOptimist** [comment]
I disagree with "work as intended". Thank you for making the devs aware.

The four pipe sections in question have a capacity of 2 each, all but the 2nd (1/2) are 2/2. The generators are all fully loaded with 20/20.
About 60 Diesel get emptied from the storage tank before it stops. Where do the 60 Diesel go? What is the capacity of the connectors? More than 1?

That it stops leaking at all in the save game surprises me. In the actual game, Diesel kept disappearing, and it did not stop by itself.

**Comment by zuff-coi** [comment]
I loaded the game 3 times and each time the diesel stopped flowing. I've reopened it and labeled it as Needs Investigation and the devs are now aware.

**Comment by ParanoikCZE** [comment]
The capacity of connectors is around those mentioned 20, both connectors and balancers have their own internal storage. I've made a demo for you.

Let's create supply to storage with multiple connectors, pause all end inputs, and then disconnect the input pipe. There is 15 worth of fluid in end pipes. Then unpause, and check storage. 69 minus 15, 54 by 3 connectors, 18 fluid per connector. For me, works as intended.
![obrazek](https://user-images.githubusercontent.com/19796452/178680355-d6945fe1-0ff7-48d6-8b2d-caa44601a39f.png)

**Comment by RealisticOptimist** [comment]
Thank you for the explanation. I'm surprised there is so much fluid in there.

So the save file does not reproduce what I have seen in game. Too bad. Please close for now.
