### ISSUE TITLE
Truck dumping issue

### ISSUE THREAD

**Issue by HardCoreGaming** [MaFi-Games/Captain-of-Industry-issues#557]
**The issue**
Assigned truck still can't unload here. Adding a medium truck doesn't solve the problem either. But I can mark the cells nearby and they can easily unload there. There are no problems with settings, before trucks unloaded here perfectly. But the problem seems to have occurred before this update, but the update did not solve it.

**Expected behavior**
Possibility of unloading transport here (at screenshot)

**To Reproduce**
Describe steps to reproduce the issue here, for example:
1. Load attached save 'dump.zip'
2. You will get a truck that cannot unload anywhere.

**Additional context**
 - Game version: [0.4.8]

**Attachments**
If applicable, attach a save file (zipped), screenshots, or log files to help us resolve the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like a crash or rendering glitches, also include Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. Thanks for taking your time writing this report!
[dump.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9093598/dump.zip)
![2032-kZ54ybX9](https://user-images.githubusercontent.com/78960081/178506585-4f1f2273-26bb-4a52-b032-76792a9ebb01.jpg)

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.8, thanks for reporting!
