### ISSUE TITLE
New dock says it has no modules with modules built.

### ISSUE THREAD

**Issue by Burnrate** [MaFi-Games/Captain-of-Industry-issues#56]
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
I don't have an older save because I was letting it run for a while but you can delete and rebuild the modules and the dock will still say you have no modules.
1. Have 3 cargo ships and 3 ports.
2. Build a new port with modules.
3. Delete old port so ship goes to new port.
4. Ship arrives and new port but the port says it has no modules.

**Expected behavior**
The newly built dock should work as expected.

**Additional context**
 - Game version: 0.2.12

**Attachments**

[G6_22.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7324528/G6_22.zip)

![image](https://user-images.githubusercontent.com/2849955/136835654-79fd299d-3c2a-4a3a-8deb-d9a756013a86.png)

**Comment by Burnrate** [comment]
I'm wondering if I may be too close to the map edge?

**Comment by Burnrate** [comment]
Ok from what I can tell it looks like it's not location but rotation.  Not sure if there is more to it
![image](https://user-images.githubusercontent.com/2849955/136838751-945355ea-2d60-44cd-861f-aa0e06a207c7.png)

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
