### ISSUE TITLE
Tree Harvester stops working if tree is unreachable

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#560]
### Issue description

If a tree is not reachable, the tree harvester will stop working until you undesignate that problematic tree. The tree is usually on an unreachable plane or on the side of a cliff.

### Expected behavior

If the harvester cannot reach the tree, it should unmark it (or possibly highlight it red for the user to notice) and move on to the next one.

### Game version

v0.4.8

**Comment by PrussiaV** [comment]
Thank you for pointing this out, I have had such a problem with tree designations in a unreachable area preventing trees from being harvested  in general

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.13.
