### ISSUE TITLE
Population text alignment issue

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#561]
### Issue description

See attached screenshot. Icons/numbers are not bottom aligned and the spacing is inconsistent.

### Expected behavior

Icons and numbers to be aligned :)

### Game version

v0.4.7.d

### Attachments

![image](https://user-images.githubusercontent.com/4413670/178639366-af4f56c7-d288-483c-852b-b950a3047b7b.png)

**Comment by MaFi-Games** [comment]
Cannot reproduce. Was probably fixed? If not, please provide your resolution & UI scaling settings.

**Comment by MaFi-Games** [comment]
Closing as not reproducible for now.
