### ISSUE TITLE
Mixer always runs non-acid glass mixture recipe first regardless of the priority set

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#564]
### Issue description

It will always run the non acid recipe because the belt clears the 36 glass mix first, never giving the more efficient acid recipe to run.
![image](https://user-images.githubusercontent.com/108291414/178756834-113047ab-2f93-4290-a08a-019a3e94ea3f.png)

### Expected behavior

To run the top prioritized one more than the second prioritized one.

### Game version

v0.4.8

**Comment by ParanoikCZE** [comment]
To me, this looks more like an issue with output. As you can see on the right side, the top one is clogged. Not sure why there are different output capacities, most probably they are auto-calculated from inputs.

**Comment by zuff-coi** [comment]
Added save file that reproduces the issue
[glass_mix.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9127132/glass_mix.zip)

**Comment by zuff-coi** [comment]
This issue is resolved with v0.4.9c 
![image](https://user-images.githubusercontent.com/108291414/182315039-fa49e691-9c5f-4c62-9183-b699ce4a1423.png)
