### ISSUE TITLE
Copy/paste on farms does not copy 'notify if cannot store' setting

### ISSUE THREAD

**Issue by utdrmac** [MaFi-Games/Captain-of-Industry-issues#566]
### Issue description

When you copy settings from farm A to farm B, the schedule and target fertility are copied, but the 'Notify if cannot store more' slider is not copied.

### Expected behavior

For all settings to copy and paste

### Reproduction steps

1. Place down a farm and give it a schedule. Do not attach any belts and disable truck export.
2. Wait for farm to harvest a couple times. Note that while waiting for harvest there is NOT any 'Outputs' section in the info viewer.
3. You will eventually get alarm that farm cannot store more.
4. Open farm A info box and un-tick 'Notify if cannot store more'
5. Place down another farm.
6. Copy settings from farm A and paste to farm B
7. Wait for farm B to fill up harvests. Eventually farm B will alarm because this setting was not copied from farm A.

### Game version

v0.4.7d

**Comment by MaFi-Games** [comment]
Just checking and it seems like this was fixed recently, so we can close this.
