### ISSUE TITLE
Weird truck behavior

### ISSUE THREAD

**Issue by glboricua** [MaFi-Games/Captain-of-Industry-issues#568]
### Issue description

Trucks that are on their way to a storage to pick up or drop off items stop moving when another vehicle is loading or unloading from the storage they are driving towards. This happens with all storage types. Storages have sufficient stock for multiple pick ups.

### Expected behavior

I expect trucks on their way to pick up items to keep moving regardless of if there's another truck currently picking something up at the destination so long as there are enough resources.

### Reproduction steps

1. Have a storage (items, loose, liquid) with a given material. 
2. have trucks pick items up from that storage, i.e. from the coal mine loose storage to the power plant loose storage.
3. trucks on their way will stop in their tracks whenever another truck is using the storage.

### Game version

0.4.7D

**Comment by zuff-coi** [comment]
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/4972554042131344663) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!
