### ISSUE TITLE
saving data to steam

### ISSUE THREAD

**Issue by Grollstein** [MaFi-Games/Captain-of-Industry-issues#571]
### Issue description

8 of 10 tries didn't work only the storage on my computer is working

### Expected behavior

when restarting the game should be synchronised with steam

### Reproduction steps

1.starting game
2 error from steam
3 start without the database from steam
4 all ok

### Game version

047D

**Comment by Grollstein** [comment]
Thank you for your feedback. I tried to create the error again, but had no success. Unfortunately, I deleted the old memory levels where this had occurred.
Yes, it was the cloud synchronisation and it was the saved game saves.
btw: you have created a really beautiful game. Congratulations! Keep up the good work. Good luck
Wolfgang Schmidt Hüser
Captain Zuff wrote:
Some more details on this would be helpful:
What is your error from Steam?
Is this about Cloud-Sync?
What Database are you talking about?
If you could also provide some log files that would be useful:
You can find your logs in "Documents\Captain of Industry\Logs" and %USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\

**Comment by zuff-coi** [comment]
I'll chalk this up to a steam issue. If you continue to have the problem you may want to try steam support: https://help.steampowered.com/en/
