### ISSUE TITLE
Vehicle refuelling in the early game

### ISSUE THREAD

**Issue by Lutenar** [MaFi-Games/Captain-of-Industry-issues#573]
**The issue**
Hey! This might be a bad behavior, at least I'm expecting otherwise.
Early game (no fuel station yet), I built a fuel tank near a mine so that the excavators can refill rather quickly. This tank is manually filled by pickups, and for that I need to either:
- put a "keep full" priority on this tank but no vehicle will refuel there (and I have no problem with that), or
- put an "empty" priority on another tank, and all vehicle will then go refuel at that distant tank (and that is my problem)

**Expected behavior**
I expect that:
- transport-wise, the "empty" priority means that the second tank must be emptied to fill other tanks, BUT
- refuelling-wise, any vehicle should go refuel at the nearest diesel tank, if this tank doesn't have any "keep full" or "empty" priority of course, REGARDLESS of the "empty" priority of the other diesel tanks

**Additional context**
 - Game version: 0.4.8

I understand it probably is how the early game is supposed to be, but it is pretty frustrating ahah!

**Comment by MaFi-Games** [comment]
I believe we have fixed this in one of our previous patches. Storage export priority is no longer used to determined refueling.
