### ISSUE TITLE
Trucks only picking up from one excavator, ignoring the other.

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#575]
### Issue description

I have two excavators working one tower and mining two different resources: limestone and sand. I have four trucks assigned to the tower.
![image](https://user-images.githubusercontent.com/108291414/179149677-65304978-96f5-4224-b2b8-d91c9f403296.png)

The excavators are prioritizing limestone and sand respectively but the trucks are only offloading the sand focused excavator, leaving the limestone excavator constantly waiting with a full bucket.

### Expected behavior

Trucks to be split their duties evenly and service both excavators. In this instance, two would service the sand excavator and two would service the limestone one.

### Game version

v0.4.8

### Attachments

[two_trucks_one_excavator.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9117751/two_trucks_one_excavator.zip)

**Comment by zuff-coi** [comment]
A way to solve this could be having trucks prioritizing items, similar to the excavators. Or just have the tower divide the trucks and have them work with all available excavators.

**Comment by MaFi-Games** [comment]
Maybe obsolete? I cannot reproduce this. On my side both excavators are frequently assigned with trucks.
