### ISSUE TITLE
escavator dig through walls !

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#576]
**The issue**
Escavator dig through walls !
My Escavator dig through retenting walls. It should be possible. It lead to problem on the other side.

![Screen Shot 07-14-22 at 02 28 PM](https://user-images.githubusercontent.com/96617483/179234990-e396ed5d-c787-492f-8c9c-eb78f3223e82.PNG)
![Screen Shot 07-14-22 at 02 28 PM 001](https://user-images.githubusercontent.com/96617483/179234996-d679b06d-27f0-4ebf-9d88-daf8661a228b.PNG)

**Expected behavior**
Escavator should NOT be able to dig through retenting walls, even if the patern configured on ground allow it.

**To Reproduce**
load the savegame.

**Additional context**
 - Game version: 0.4.8 (Early Access)

**Attachments**
[save_22-07-14_14-28-38-bug traverse mur.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9121288/save_22-07-14_14-28-38-bug.traverse.mur.zip)

**Comment by MaFi-Games** [comment]
I believe we have fixed this by preventing walls and designations to intersect in this way.
