### ISSUE TITLE
Unable to write save file

### ISSUE THREAD

**Issue by sharkking76** [MaFi-Games/Captain-of-Industry-issues#577]
### Issue description

From time to time the game tells that it is unable to write the save file when manually saving.

After restart it usually works

Seems to be quiet often after a patch

### Expected behavior

Save should be written. Or game should notify when autosave could not be written

### Game version

v0.4.8

### Attachments

[22-07-15_15-19-43_1498.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9121326/22-07-15_15-19-43_1498.log)

**Comment by sharkking76** [comment]
Antivirus or Malewareprotection did not block, i had a look in the logs. After restarting the game saving works again. However there is a lot of progress lost when the autosave does not work. It would be good to add a error popup on autosave failure.Am 15.07.2022 17:38 schrieb Captain Zuff ***@***.***>:
This could be due to a permissions issue or windows randsomware protection. Something on your machine is preventing access to the documents folder where your saves are located.

**Comment by MaFi-Games** [comment]
We do show error notification in case autosave fails. If you are loosing files consider checking your HDD for integrity.

**Comment by MaFi-Games** [comment]
Closing as not enough information but it was most likely permission issue.
