### ISSUE TITLE
Trucks refuses to dump rock near map end

### ISSUE THREAD

**Issue by ParanoikCZE** [MaFi-Games/Captain-of-Industry-issues#578]
**The issue**
There seems to be some weird (probably circle) boundary around the map that cannot be dumped over by rock. I've experienced this issue already few times in the past in several places and seems like the area can be filled with dirt.
![obrazek](https://user-images.githubusercontent.com/19796452/179259187-d666b539-75eb-4806-b40c-9fdd8613d465.png)

**Expected behavior**
Rock could be dumped anywhere.

**To Reproduce**
Check save and top end of the map near the iron mine.

**Additional context**
0.4.8

**Attachments**
Save: http://gofile.me/6S5mX/IN4gt4qUf (There is 25MB limit, so storing it elsewhere)

**Comment by dgzeij** [comment]
More datapoints:

My map has been fine, although sometimes dodgy around the rock slope deep underwater close to the edge of the map. Until I arrived at this spot, when the trucks simply refuses to dump as shown in the picture and savefile. The trucks wait forever, including forgetting to refuel, which reminds me about certain 24h game sessions of this addicting game.

![20220722225039_1](https://user-images.githubusercontent.com/85814950/180567798-f48099bd-ed91-4128-9c85-c26111d54ba5.jpg)

[save_22-07-22_22-50-15 trucks refuse to dump rocks.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9172133/save_22-07-22_22-50-15.trucks.refuse.to.dump.rocks.zip)

**Comment by zuff-coi** [comment]
I believe this is the same issue occurring in #591

**Comment by dgzeij** [comment]
I checked several variations before posting mine. Maybe they have a common cause at the bottom, but the angle of issue description was different enough to warrant several issues.

**Comment by MaFi-Games** [comment]
This issue has been fixed in Update 1 after we added buffer areas around map edges. Thanks for your report!
