### ISSUE TITLE
Cannot recover Shovel Ground to recover ocean access with Unity

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#579]
### Issue description

Cargo Depot is stuck in "Ship Access Blocked" even though nothing is blocking it. Building a tall water pump nearby caused the blockage but after removal clicking the "Shovel Ground" button in the Depot does nothing. 
![image](https://user-images.githubusercontent.com/108291414/179265952-9b45b49d-45b0-4947-931c-3f90179ab935.png)

### Expected behavior

The Cargo Depot to not be blocked when nothing is there to block it

### Reproduction steps

1. Load attached save
2. Click "Shovel Ground" button on Cargo Depot

### Game version

v0.4.8

### Attachments

[4th_save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9122459/4th_save.zip)

**Comment by MFeltmann1** [comment]
it happened after i put a tall water pump where a normal water pump is blocked by shipyard and tall is not

**Comment by wzurborg** [comment]
Same here, let me know if you need a savegame.

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11, thanks for reporting!
