### ISSUE TITLE
Truck priority causes everything to break down.

### ISSUE THREAD

**Issue by Pecomica** [MaFi-Games/Captain-of-Industry-issues#58]
Getting low on Maintenance warning and eventually run out of it. Causing trucks, machines and everything to break down.
Trucks chose to deliver the missing iron plates to the assembler instead of the maintenance depot, causing a larger and larger reaction of breakage to machines and equipment.

only solution I found is to pause my assembler to 'force' the trucks to deliver the much needed plates to the depot.

Please allow us to set up priority on buildings for where we need resources. This is still relatively early in game, before belts. So can't use storage to highlight keep full or such to help with the issue. Make the priority a number between 1-5 or 1-10, so we can set up more details on where our much needed resources and components are going.

**Comment by MaFi-Games** [comment]
Thanks for the report, we have added priorities to the upcoming beta release so you can now prioritize where the products should go. This should eliminate explained issue.
