### ISSUE TITLE
Miners stalling, switches constantly between two tasks without moving

### ISSUE THREAD

**Issue by Lancar223** [MaFi-Games/Captain-of-Industry-issues#580]
### Issue description

T1 Miners bunch up in mining area, only 1 of them working. The rest switch back and forth between two jobs  "loading cargo, dojob stopped" and "searching for a valid terrain designation, dojob stopped"

### Expected behavior

Not this

### Reproduction steps

load attached save

### Game version

v0.4.8

### Attachments

[Golden Peak2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9123060/Golden.Peak2.zip)

**Comment by zuff-coi** [comment]
This issue has been resolved as of v0.4.9c 
![image](https://user-images.githubusercontent.com/108291414/182315413-b2ef6dcd-1b5d-415e-b901-9533c35c8c88.png)
