### ISSUE TITLE
UI: (Irrigated) Farm, Harvest Stats: text orientation

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#581]
### Issue description

See screenshot. "Vegetables" is written vertically. Even outside the Harvest Stats popup window (how can that be?).

(At least) Farm and Irrigated Farm show same error.

![HarvestStatsFarm](https://user-images.githubusercontent.com/109154186/179309166-3c18d60a-51c0-4362-8eb6-97eed1dcba52.png)

### Expected behavior

Like "48 Vegetables"?!

### Game version

0.4.8

**Comment by MaFi-Games** [comment]
I cannot reproduce this issue, does it still happen?

**Comment by RealisticOptimist** [comment]
Iirc, it disappeared 4.9 or 4.10. I thought it got fixed, but issue not updated.
v4.12e:
![Veggie](https://user-images.githubusercontent.com/109154186/204006568-5a62344c-9d39-4f6c-afe1-c3241aff9b13.jpg)
Text permanently covering the image does not look nice, but the original complaint is not observed anymore.
Close as fixed.
