### ISSUE TITLE
Closest idle truck should get the job

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#585]
### Issue description

All three visible trucks (near the generators) are idle. Beacon is the only building under construction. It needs three truck loads, all from the shipyard.

![2022-07-16 16_05_45-Captain of Industry](https://user-images.githubusercontent.com/109154186/179358365-e6779638-3b37-482f-a23c-190e38f70b04.png)

Instead of using these three trucks, one truck got called from near the abandoned communication station. In the 2nd screenshot is a 4th truck, while one close to the shipyard is still parked there.

![2022-07-16 16_06_53-Captain of Industry](https://user-images.githubusercontent.com/109154186/179358368-9d63906a-83d6-466d-aa70-9975662560ee.png)

### Expected behavior

I expected the three idle trucks nearest to the shipyard to all get a job.

To me this is important for the game experience to feel more realistic/intelligent.

### Game version

v0.4.8

**Comment by MaFi-Games** [comment]
We are not sure if we will ever support this, it is very hard from computational perspective.

**Comment by MaFi-Games** [comment]
This has been implemented in Update 1. Thanks for your report!
