### ISSUE TITLE
Finding closest tree to harvest can be sometimes a bit off

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#586]
### Issue description

One harvester, three trees marked.
![2022-07-16 16_36_23-Captain of Industry](https://user-images.githubusercontent.com/109154186/179359530-d6a87f7b-a599-4dcf-b4af-4c34abe93f58.png)
The left one gets cut last, not the top one.

![2022-07-16 16_38_55-Captain of Industry](https://user-images.githubusercontent.com/109154186/179359534-2fee5d87-aa5b-42b9-bd5b-1ad7960d3ee1.png)

### Expected behavior

The two bottom left trees get cut first, the top right one should be last. Kind of "always pick the closest to drive to".

### Game version

v0.4.8

**Comment by MaFi-Games** [comment]
We are already serach for closest trees but for performance reasons the search is done via chunks (larger units of terrain). It could happen here that the bottom tree was on a different chunk and thus not discovered.

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
