### ISSUE TITLE
Vehicles Management should list all vehicle assignments

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#587]
### Issue description

At the moment Vehicles Management lists:
- Owned
- Available to Assign
- Assigned to Mining
- Assigned to Fuel Stations

What I'm missing:

- Assigned to Harvesters (including those harvesters)
- Assigned to Storages (once you have adv. logistics)

Is there more vehicles can be assigned to?

### Expected behavior

All possible (or all used?!) assignment categories should be listed.

The sum of the vehicles in those assignment categories should equal vehicles Owned.

For all vehicle types, of course.

### Game version

v0.4.8

**Comment by zuff-coi** [comment]
Fixed as of v0.4.9c experimental 
![image](https://user-images.githubusercontent.com/108291414/182315558-bc34024b-e1b6-4fd6-a403-7367a9bfdda4.png)
