### ISSUE TITLE
Construction without the use of resources / Infinite resources!

### ISSUE THREAD

**Issue by Kcadar** [MaFi-Games/Captain-of-Industry-issues#588]
### Issue description

Instant construction of buildings without the need for all resources

### Expected behavior

000

### Reproduction steps

1) Place a building
2) Wait for the material to arrive (20% is enough)
3) Pause construction
4) Cancel building
5) For unity, return spent resources
6) Resume building
7) Cancel building
8) Resume building

Building completed!!! Resources NOT spent!!!
The building can be demolished and get resources from nowhere

Original text in case of Google translator error

1) Поставить здание
2) Дождаться привоз материалом (20% достаточно)
3) Поставить строительство на паузу
4) Отменить постройку
5) За единство вернуть потраченные ресурсы
6) Возобновить постройку
7) Отменить постройку
8) Возобновить постройку

Здание построено!!! Ресурсы НЕ потрачены!!!
Здание можно снести и получить ресурсы из ниоткуда

### Game version

0.4.8

### Attachments

[Xabar.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9126640/Xabar.zip)
![image](https://user-images.githubusercontent.com/109439914/179372922-bb889ab4-5ea4-4a1d-9c77-5a28244dc256.png)
![image](https://user-images.githubusercontent.com/109439914/179372948-9c48bf48-3868-4a4c-910f-35ae159d9b9b.png)
![image](https://user-images.githubusercontent.com/109439914/179372966-36584c74-045e-44a4-9454-08c492c123a9.png)
![image](https://user-images.githubusercontent.com/109439914/179372982-be0fdfd7-13eb-4256-b601-134fec639e00.png)
![image](https://user-images.githubusercontent.com/109439914/179372993-7121360b-b3f3-4ec5-8708-2c355550a74a.png)
![image](https://user-images.githubusercontent.com/109439914/179373027-1f0aae13-8c59-40e7-ae64-7cf6e9e83ac1.png)

**Comment by Kcadar** [comment]
The error occurs during the demolition phase
When resources are returned for unity, the building has nothing available
When you cancel the demolition, the building is instantly built

**Comment by MaFi-Games** [comment]
Thanks for your report! This was fixed in v0.4.12e.
