### ISSUE TITLE
Conveyor belt connector eats materials

### ISSUE THREAD

**Issue by Cree81889** [MaFi-Games/Captain-of-Industry-issues#589]
### Issue description

My conveyor belt connector transporting Construction parts III to a connecting storage house eats materials as their produced. The Storage house is full and the conveyor belt has 6/6 already stored. when the materials enter another connecting belt they disappear. creating an endless cycle of production and material loss. I double checked to make sure they were being stored as a buffer within the assembly factory. 

### Expected behavior

The material should be filling up the belt and eventually the buffer within the assembly plant. 

### Reproduction steps

I am not sure what's triggering the issue. I have deconstructed and reconstructed the belts. I watched 5 cycles of each attached assembly factory with all material being lost and none stored as a buffer after the first 6/6 belt is full. The factory's next to these produce the same material but seem to be functioning properly.

### Game version

v0.4.8

### Attachments

[Connector of the void.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9126775/Connector.of.the.void.zip)
![Connector of the void](https://user-images.githubusercontent.com/109441976/179374914-59493d2a-2741-4109-a442-35ef1e446522.png)
![Screenshot 2022-07-16 181451](https://user-images.githubusercontent.com/109441976/179374916-e51b0a2c-7aa9-4c57-b36a-b70d7d507927.png)
![Screenshot 2022-07-16 181550](https://user-images.githubusercontent.com/109441976/179374918-984c1705-5236-4bc0-8ee3-14c0c1f820a1.png)
![Screenshot 2022-07-16 181646](https://user-images.githubusercontent.com/109441976/179374920-26dbe3c2-ba9c-4c18-9f6c-986ec48ede33.png)
[22-07-16_17-10-11_3831.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9126776/22-07-16_17-10-11_3831.log)

**Comment by ParanoikCZE** [comment]
Not a bug, connector has its internal storage (which is not reported anywhere). 
If you stop source and let it go out, it will eventually empty all you've "lost".
If you connect your bottom storage to feed it and stop output, it will eventually also stop as connector will be filled.

However, this feature is afaik not being documented anywhere, so it might use same UI as balancer to report its cargo.

**Comment by RealisticOptimist** [comment]
Having made a similar issue #556, I very welcome the idea to add the UI for fill level and remove products to the connectors.

It would be much easier to collect evidence for and against a suspected bug, even if non reproducible from a save file.

A connector capacity of ~20 is surprisingly high (for the early game). I did not expect (much) more than the transports connected. Maybe connectors should come with variable internal sizes? Like sum of connected transports.

**Comment by MaFi-Games** [comment]
Thanks, we have added UI that now shows the internal buffer of connectors.
