### ISSUE TITLE
Fluid storage does not have a selection for steam or exhaust

### ISSUE THREAD

**Issue by Kilinater** [MaFi-Games/Captain-of-Industry-issues#59]
The fluid storage does not have a selection for any of the power-related gases (Any steam and exhaust). I don't know if this is a bug but if it isn't I think it should be added.

**Comment by MaFi-Games** [comment]
This is actually working as intended. We do not want to allow storing steam or exhaust. Also, logistics is not able to transport these.

We will think about a better way how to communicate this to the player.
