### ISSUE TITLE
oil steam

### ISSUE THREAD

**Issue by Stephenlong202** [MaFi-Games/Captain-of-Industry-issues#590]
### Issue description

steam in the pipes for oil processing keeps goig from steam hi to steam low. 

### Expected behavior

steam in pipes needs to stay high and not drop to low

### Game version

v.0.4.8

**Comment by ParanoikCZE** [comment]
That's shouldn't be happening, I think you might be mixing two steam sources. So, to confirm, save is needed.

**Comment by MaFi-Games** [comment]
This was never implemented into the game. Please provide a save file.

**Comment by MaFi-Games** [comment]
Closing as not enough information provided.
