### ISSUE TITLE
Dock seemingly blocked by invisible wall, but not edge of map

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#591]
### Issue description

Thanks to JD-Plays for this: 
Trying to build a dock here:
![image](https://user-images.githubusercontent.com/108291414/179387310-76f4c5b4-2698-409d-b59b-48b931a218ad.png)
Getting red squares everywhere, "Something is in the way"
Yet I can dump past this point:
![image](https://user-images.githubusercontent.com/108291414/179387321-6a9f88f8-0489-4655-92ac-9f26eb7ce462.png)

This corner is FAR from the original coastline, yet on the backside: 
![image](https://user-images.githubusercontent.com/108291414/179387335-33599e01-02a7-4836-af8d-9937ccd00240.png)

Map settings: Default except 25% bonus resources AND 25% lower sea floor

### Expected behavior

To be able to build the dock there

### Game version

v0.4.8

### Attachments

Save file: [cant_build_dock.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9127148/cant_build_dock.zip)

**Comment by zuff-coi** [comment]
It may not be a bug but its hard to tell where the end of the buildable area is. Maybe if the dock is blocked because of edge of map, tell the user that instead of "Something is in the way"

**Comment by JD-Plays** [comment]
or a Hard limit for placing extra tiles and a soft limit on the shipyards/docks extending past that, as those tiles are not used by the trucks at all

**Comment by ParanoikCZE** [comment]
For me, it would make sense to have an end of terraformable map that differs from the buildable area. So even with max expanded island, you would be able to build on any edge.

**Comment by dgzeij** [comment]
More datapoints:

My map has been fine, although sometimes dodgy around the rock slope deep underwater close to the edge of the map. Until I arrived at this spot, when the trucks simply refuses to dump as shown in the picture and savefile. The trucks wait forever, including forgetting to refuel, which reminds me about certain 24h game sessions of this addicting game.

![20220722225039_1](https://user-images.githubusercontent.com/85814950/180567798-f48099bd-ed91-4128-9c85-c26111d54ba5.jpg)

[save_22-07-22_22-50-15 trucks refuse to dump rocks.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9172133/save_22-07-22_22-50-15.trucks.refuse.to.dump.rocks.zip)

**Comment by emdas20** [comment]
hola un pregunta como saber de ante mano cual es el limite de expandir la isla y donde se puede construir, hay alguna forma?

**Comment by CrazyOdd** [comment]
I created a YSNP map with max sea chunks. I can dump out to about 138 tiles from the main dock, but a cargo dock complain about something in the way, at around the 89 mark, where the vanilla edge is.
https://pasteboard.co/NPVCIoGGddUV.jpg
https://pasteboard.co/YG26QE2ygPF2.jpg

**Comment by lowstrife** [comment]
Another thing I'd like to point out.

Reloading the map will extend this bugged limit. I have continually re-loaded my map over the past several weeks. Here is a old screenshot showing the previous limit: 

![image](https://user-images.githubusercontent.com/65734844/188988469-6bfed73e-86be-4a23-a7f7-20575e190ae3.png)

![image](https://user-images.githubusercontent.com/65734844/188988508-93244614-5298-4c00-81c7-aa3ccab49ec4.png)

In all situations, I've been able to extend the limiting boundary by simply just saving the game and fully reloading it. And continue landfilling and expanding the land available. 

Here are two save files. They are separated by a reasonable amount of time. I don't have anything older I'm sorry. But I can confirm that reloading the game extends this artificial limit and allows me to landfill deeper into the sea. 

[Version 1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9520440/Version.1.zip)
[version 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9520441/version.2.zip)

**Comment by emdas20** [comment]
> Creé un mapa YSNP con fragmentos máximos de mar. Puedo descargar alrededor de 138 mosaicos desde el muelle principal, pero un muelle de carga se queja de algo en el camino, alrededor de la marca 89, donde está el borde vainilla. [https://pasteboard.co/NPVCIoGGddUV.jpg ](https://pasteboard.co/NPVCIoGGddUV.jpg) https://pasteboard.co/YG26QE2ygPF2.jpg

gracias por los datos

**Comment by emdas20** [comment]
> Otra cosa que me gustaría señalar.
> 
> Recargar el mapa extenderá este límite de errores. He recargado continuamente mi mapa durante las últimas semanas. Aquí hay una captura de pantalla antigua que muestra el límite anterior:
> 
> ![imagen](https://user-images.githubusercontent.com/65734844/188988469-6bfed73e-86be-4a23-a7f7-20575e190ae3.png)
> 
> Y aunque no he hecho grandes progresos, créanme, he extendido el área del vertedero mucho más allá de donde el juego no me lo permitía antes.
> 
> ![imagen](https://user-images.githubusercontent.com/65734844/188988508-93244614-5298-4c00-81c7-aa3ccab49ec4.png)
> 
> En todas las situaciones, he podido extender el límite limitante simplemente guardando el juego y recargándolo por completo. Y seguir rellenando y ampliando los terrenos disponibles.
> 
> Como podemos ver aquí, el objeto en el camino se adapta perfectamente a la tierra que he creado... recargar el juego me da otras 3-4 fichas de espacio antes de que esté limitado nuevamente.
> 
>  Capitán_de_la_industria_2022-09-07_15-49-34.mp4 
> Aquí hay dos archivos guardados. Están separados por una cantidad razonable de tiempo. La imagen antigua que publiqué arriba es de hace semanas y no tengo guardados de hace mucho tiempo para tener un mayor contraste, lo siento.
> 
> [Versión 1.zip ](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9520440/Version.1.zip) [versión 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9520441/version.2.zip)

gracias por las partidas guardadas, estan muy impresionante, cual mapa es el original?

**Comment by lowstrife** [comment]
You Shall Not Pass

**Comment by emdas20** [comment]
> You Shall Not Pass

thanks for the saved games, they are very impressive, which map is the original?

**Comment by emdas20** [comment]
> El mapa es No pasarás.

thanks and sorry for my confusion

**Comment by MaFi-Games** [comment]
This issue has been fixed in Update 1 after we added buffer areas around map edges. Thanks for your report!
