### ISSUE TITLE
Transport problem

### ISSUE THREAD

**Issue by usmankhodjaev** [MaFi-Games/Captain-of-Industry-issues#592]
### Issue description

Trucks stand still and do not move, there is fuel in the tanks.

### Expected behavior

1

### Game version

v 0.4.8

**Comment by MSC-Michael** [comment]
I have the same issue with v0.4.8 a lot of my trucks do only stop and go. After analyzing their destination it seems the new early detection of invalid targets is the issue. I found when the target is occupied by another truck it cannot be reached => truck stops and waits because only one truck can go to a building at a time. This is stopping my whole Logistics, because almost all Tucks take about double the time to pick up goods
I made some screen recordigns showing the stop and go with destinations. If Save is required, I have one directly after the videos.

https://user-images.githubusercontent.com/109460229/179392967-556a01b6-175c-4f8f-8133-064780579b99.mp4
https://user-images.githubusercontent.com/109460229/179392958-4bc0187a-1c6b-431d-bb94-150284063f0a.mp4

**Comment by ParanoikCZE** [comment]
> I have the same issue with v0.4.8 a lot of my trucks do only stop and go. After analyzing their destination it seems the new early detection of invalid targets is the issue. I found when the target is occupied by another truck it cannot be reached => truck stops and waits because only one truck can go to a building at a time. This is stopping my whole Logistics, because almost all Tucks take about double the time to pick up goods I made some screen recordigns showing the stop and go with destinations. If Save is required, I have one directly after the videos.
> 
> https://user-images.githubusercontent.com/109460229/179392967-556a01b6-175c-4f8f-8133-064780579b99.mp4 https://user-images.githubusercontent.com/109460229/179392958-4bc0187a-1c6b-431d-bb94-150284063f0a.mp4

This is #364, not sure about the initial issue

**Comment by MaFi-Games** [comment]
Please provide a save file otherwise we just dupe it against #364 as that seems to be the most similar issue.

**Comment by MSC-Michael** [comment]
[New_Curland.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9128020/New_Curland.zip)
Here the requested Save file. Most of the trucks seen in the active view all stop most of the time and don't deliver anything.
I'm sure last week when I played last, it didn't happen or at least I could not notice it and I have seen trucks waiting in line, but not all stopping at the same time in mid route.

**Comment by MaFi-Games** [comment]
Thanks but I was mainly asking OP for the save file, because they have mentioned that trucks are still and don't move. The stop and go situation happens when trucks queueing for destinations and that issues is covered by issue #364

**Comment by usmankhodjaev** [comment]
> Thanks but I was mainly asking OP for the save file, because they have mentioned that trucks are still and don't move. The stop and go situation happens when trucks queueing for destinations and that issues is covered by issue #364

It seems to me that this is not the problem described in #364.  There are also trucks that are not tied to storages, and they also do not stand near storages, they can stop along the middle of the route.

**Comment by MaFi-Games** [comment]
Right, but we really need a save file, otherwise it is hard to investigate this.

**Comment by PTTG-ACTUAL** [comment]
I think I have a repro. The issue appears to be that trucks stop while their destination is being used, even if they are still en route. The camera is over a line of trucks headed to a fuel depot that are demonstrating that
[YSNP Megopolous d.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9175985/YSNP.Megopolous.d.zip)
.

**Comment by zuff-coi** [comment]
We [released an update on the experimental branch](https://steamcommunity.com/games/1594320/announcements/detail/3397421255147457180) which has fixes aimed at this issue. If you could please try it out and let us know if your issue is resolved that would be great!

**Comment by MSC-Michael** [comment]
After playing Experimental a few hours I can confirm that my issue is solved

**Comment by zuff-coi** [comment]
@MSC-Michael That's great to hear! Thanks!

**Comment by PTTG-ACTUAL** [comment]
This was resolved! Sorry for the late report, been busy.
