### ISSUE TITLE
Gas station trucks travel too far

### ISSUE THREAD

**Issue by NortonDK** [MaFi-Games/Captain-of-Industry-issues#593]
### Issue description

Sometimes the trucks assigned to fuel stations, travel very far to fuel miners. when there is a closer gas station that also has assigned trucks to it. 

### Expected behavior

That the closest gas station truck fuels the  miners instead of the ones further away. Maybe a way to force the gas stations to service a certain area?

### Game version

v0.4.7D

**Comment by MaFi-Games** [comment]
You can assign gas stations to mine control towers via custom routes unlocked with advanced logistics.

**Comment by MaFi-Games** [comment]
Duplicate of #188

**Comment by NortonDK** [comment]
Thanks i was not aware.

søn. 17. jul. 2022 17.58 skrev Captain of Industry ***@***.***
