### ISSUE TITLE
Adopt Pops string shows previous content

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#594]
### Issue description

In the Adopt Population dialog:

On very first opening after loading a game:
![2022-07-17 13_57_11-Captain of Industry](https://user-images.githubusercontent.com/109154186/179397410-9b5f09e9-d059-485f-8f91-a2c73db7fad2.png)

Some other save, I want to actually adopt again:
![2022-07-17 13_47_12-Captain of Industry](https://user-images.githubusercontent.com/109154186/179397442-85bf644e-a4f3-4efd-ba7f-3825f8724837.png)
After adoption of those six:
![2022-07-17 13_49_24-Captain of Industry](https://user-images.githubusercontent.com/109154186/179397448-1a9aaf9d-41e8-4572-865f-cd88239de479.png)

### Expected behavior

1: Adopt 5 pops
2: Adopt 6 pops
3: Adopt 0 pops

Apparently the string is updated only after being shown. Next time dialog gets opened, you get to see that old content.
1: string is empty (never written anything).
2: string shows content of after a previous adoption.
3: string shows what it should have shown before.

### Game version

v0.4.8

**Comment by zuff-coi** [comment]
Resolved in experimental v0.4.9c
![image](https://user-images.githubusercontent.com/108291414/182315907-7378d33f-4bcc-4cd5-9494-956311109aad.png)
