### ISSUE TITLE
Issue with repairing main ship

### ISSUE THREAD

**Issue by TMEBERT** [MaFi-Games/Captain-of-Industry-issues#595]
### Issue description

Periodically the trucks will not deliver the materials to repair the main ship.  Currently I have the priority set to 1 and have plenty of resources and they will not finish loading all the material so I cannot use the ship to do anything on the world map.  In my current game it stayed at 53% for a long time (hours of real world time) and then randomly delivered all the steel to put it to 80%.  Now it won't load any of the electronics rendering the ship useless.

![Screenshot 2022-07-17 090005](https://user-images.githubusercontent.com/109467846/179399687-d3194efa-d32c-43d5-b71a-4ab3eea57189.png)

### Expected behavior

Auto repair should repair the ship immediately if you have the resources.  Esspeciallly when priority is set to 1.

### Game version

v0.4.8

### Attachments

![Screenshot 2022-07-17 090005](https://user-images.githubusercontent.com/109467846/179399736-334bc5c1-7bc8-4042-8b85-32a78a0871af.png)

**Comment by ParanoikCZE** [comment]
This is for sure not common, so save would be needed.

**Comment by MaFi-Games** [comment]
Please provide a save file so we can investigate

**Comment by TMEBERT** [comment]
How do I get the save file to email it?

**Comment by MaFi-Games** [comment]
As explained when filing the ticket: If applicable, attach a save file (zipped). You attach the file by dragging it to the text box below.

**Comment by MaFi-Games** [comment]
Re [mikanchan-mk2]: It's because your storage with electronics has export route assigned, that prevents it to export into your shipyard.
