### ISSUE TITLE
wrong notice/ starvation

### ISSUE THREAD

**Issue by Grollstein** [MaFi-Games/Captain-of-Industry-issues#598]
### Issue description

while building a second city, I suddenly got the message that my food supply was exhausted and my people were starving, in fact only a food shop was missing to solve the problem.

### Expected behavior

an other message from the game, discribing the problem more correctly

### Game version

v.04.8

### Attachments

[neue Stadt 2_1.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9128645/neue.Stadt.2_1.zip)

**Comment by zuff-coi** [comment]
Not sure what the bug is here? This seems to be working as intended. Each city needs its own food supply and it seems like you figured that out?

Please let me know if I'm missing something.

**Comment by Grollstein** [comment]
Hi,
no, another problem - an Error code from steam. You asked me to contact steam if the error (saved game cannot be loaded) occurs again, which I did. The copy was just for your reference
Wolfgang Schmidt Hüser
Captain Zuff wrote:
Not sure what the bug is here? This seems to be working as intended. Each city needs its own food supply and it seems like you figured that out?
Please let me know if I'm missing something.

**Comment by zuff-coi** [comment]
> Hi, no, another problem - an Error code from steam. You asked me to contact steam if the error (saved game cannot be loaded) occurs again, which I did. 

I'm sorry but what does that have to do with this issue in particular?
