### ISSUE TITLE
In jedem meiner Speicherstände, geht nach 2 bis 4 Forschungen die Forschung nicht mehr , bei der letzten Forschung bis 98% dan nichts mehr ....

### ISSUE THREAD

**Issue by Domton98** [MaFi-Games/Captain-of-Industry-issues#6]
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files, screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`)

**Comment by koppi99** [comment]
hi, after start the research it stops. tried it with 2 research buildings. also the workers inside do not more increase after pause. Version 0.2.0c
[Neutstart 5.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7189514/Neutstart.5.zip)
i

**Comment by koppi99** [comment]
attached a brand new one with the error. its freezing 0,17 Einigkeit available. 
[Neustart 5 save_21-09-18_10-27-56.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7189543/Neustart.5.save_21-09-18_10-27-56.zip)
t

**Comment by Marestic** [comment]
Du hast zu wenig Unity. Die Forschungsstation verbraucht 0,5 pro Monat. Aktuell hast du 0,17.
Haben die im Discord rausgefunden.

**Comment by MaFi-Games** [comment]
We have fixed lab status in `v0.2.2`.
