### ISSUE TITLE
Can't unasign route if material is changed

### ISSUE THREAD

**Issue by Kilinater** [MaFi-Games/Captain-of-Industry-issues#60]
If you have a selected route between storage containers and change the selection on one of them it is impossible to remove the route between them until the selected material is changed back to what it was.

To reproduce:
1. Have storage A and B with the same selection
2. Create a route from A to B
3. Change the material of storage B
4. Try and delete the route from A to B (Does not work)

**Comment by MaFi-Games** [comment]
Thanks for the report, we will investigate.

**Comment by mnoreke** [comment]
Can confirm this is still a valid issue in v 0.4.1d

**Comment by MaFi-Games** [comment]
This has been fixed in our directional routes patch.
