### ISSUE TITLE
Trucks Cargo History, split general jobs

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#600]
### Issue description

Feature request for Vehicles Management, Trucks Cargo History:

General idea:
I'd like to see just the jobs that could be transported without trucks.
Esp. construction jobs are the main contributor for "extremely busy". I'd like to see their impact better.

At the moment I see five groups for that, instead of now three:

- General jobs which could use other transports
- Construction & deconstruction
- Shipyard, vehicles depot, ...
- Mining trucks (we do have)
- Refueling trucks (we do have)

At the moment the history feels like being half way.

### Expected behavior

See above.

### Game version

v0.4.8

**Comment by MaFi-Games** [comment]
Not sure what you mean by "jobs that could be transported without truck". Just the definition of this is fairly tricky. No matter how we define this concept, getting this information is computationaly hard for many reasons and the logistics does not have such data available - e.g. knowing which entity has belts and which not. This is in our opinion not worth the investment.

Also, please file features ideas here: https://ideas.captain-of-industry.com/ We track bugs here or feature requests that are significant improvement in some major frustrating situations.
