### ISSUE TITLE
Research Lab accepts equipment before being built

### ISSUE THREAD

**Issue by FabianSchriever** [MaFi-Games/Captain-of-Industry-issues#602]
### Issue description

When building new research labs they are already able to accept lab equipment into their internal storage without being fully built. See screenshot.

### Expected behavior

Either don't accept the equipment, or only accept the 10 needed to build it.

### Reproduction steps

Route lab equipment via conveyor belt into not yet built research lab.

### Game version

0.4.8

### Attachments

![20220718215148_1](https://user-images.githubusercontent.com/109552309/179606463-d4fa28ed-5408-4109-af42-5dc32e5cd21d.jpg)

**Comment by FabianSchriever** [comment]
I noticed the same behaviour on the statue of maintenance.

**Comment by zuff-coi** [comment]
Resolved as of experimental v0.4.9c
![image](https://user-images.githubusercontent.com/108291414/182316144-546aa390-f645-4208-a3d0-26fbe2e36d2d.png)
