### ISSUE TITLE
Connector placing should be improved

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#603]
### Issue description

UX topic when building transports.

A)
![2022-07-18 21_53_10-Captain of Industry](https://user-images.githubusercontent.com/109154186/179606131-ee64ab51-fdde-47ce-a71f-23a3e12c7e76.jpg)
The pipe is supposed to end there, As a connector connecting both. There is a work around, I extend the pipe to the right, then that causes a connector and the bottom right generator gets finally connected too. But then I have to delete that dead end pipe, which is quite the click effort.
Fortunately it's not too often (another use case of mine is the water supply for two mixers), but it still anoys me every time.

B)
![2022-07-18 22_21_12-Captain of Industry](https://user-images.githubusercontent.com/109154186/179610569-70a5b146-e781-4659-bcd8-65d03fc10996.jpg)
Why am I not allowed to start the pipe at the two generators? The "incompatible port at start" check is imho too early (seems a bug). The check should be on the 2nd MBLeft, not already the first. A single click can't create a transport anyway.

### Expected behavior

A) Alternative ideas:
- Building the last pipe segment detects it needs to end in a connector.
- user can force a connector (e.g. click twice). In case of directly connecting (with a new building) to an existing transport that would help as well. 

B) Similar to A):
- Detect the need to start with a connector. The probable pipe direction can still be concluded.
- Just let the user build the transport first and then place a connector manually.

Cases with 3 (or 4, though nothing reasonable comes to my mind) buildings should behave reasonable as well.

### Game version

v0.4.8

**Comment by MaciejPolanski** [comment]
Let me add following suggestion: In all situations, where message "incompatible port at start" is needed, game should generate connector instead and continue plowing a pipe. 
This could also help to e.g. connect multiple Rainwater Harvesters in a row.

**Comment by MaFi-Games** [comment]
Thanks for the report and discussion, this was fixed and will be available in the next patch!

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
