### ISSUE TITLE
Docks. Upgrading 6x to 8x leaves the old delivery cycle trigger

### ISSUE THREAD

**Issue by Yar1o** [MaFi-Games/Captain-of-Industry-issues#606]
### Issue description

Currently 8x ships go to the mines with about 1100 products in it and bring less than their maximum volume of 1440.

A value of 1100 can correspond to a 6x ship trigger (capacity 1080 resources)

### Expected behavior

8x ship starts delivery when there is at least 1440 product in the mine.

### Reproduction steps

1. load save
2. wait for wood\uranium delivery (ship just started)

### Game version

v0.4.8

### Attachments

[_STABLE_.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9139575/_STABLE_.zip)

**Comment by MaFi-Games** [comment]
I don't think there is an issue. Ship departs when it can load 80% of cargo which is for ship with 8 modules approx. 1152. So I think  this matches. However we are changing ships to always try to depart for 100%, so this will be obsolete issue anyway.
