### ISSUE TITLE
Crashing after 10 min of play

### ISSUE THREAD

**Issue by Bracket5** [MaFi-Games/Captain-of-Industry-issues#607]
### Issue description

Game crashes without warning
![capt screen shot](https://user-images.githubusercontent.com/109594338/179742320-3c08e0c3-39d4-464a-bf36-5c2ae9da5081.gif)

### Expected behavior

Not to crash with this spec

**CPU**|[Intel Core i7-9700K]
**GPU**|[Nvidia RTX 3060]
**SSD**|[Samsung 980 Pro NVMe PCIe M.2 1TB]
**SSD**|[Samsung 860 QVO 1TB]
**RAM**|[Corsair CMW32GX4M2D3600C18 4x8GB]
**MBD**|[MSI MPG Z390 GAMING PLUS (MS-7B51)

### Reproduction steps

1. load into save game.
2. play save game for 10 minutes
3. error comes up with a green loading bar (as in pic)
4. back to desktop without any crash logs
Maybe unrelated but when I do try and load after a crash, STEAM has lost connection

### Game version

v0.4.8

### Attachments

![capt screen shot](https://user-images.githubusercontent.com/109594338/179743156-d3b6c67a-b38d-4acd-aa21-0f6116795a8c.gif)

**Comment by ParanoikCZE** [comment]
1) Learn to use alt+printScreen or to crop your images.
2) Crash logs are in AppData\LocalLow\Mafi Games\Captain of Industry.

**Comment by zuff-coi** [comment]
Could you provide logs? You'll find them in "Documents\Captain of Industry\Logs" and "%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\"

**Comment by Bracket5** [comment]
[22-07-19_19-24-05_8659.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9152437/22-07-19_19-24-05_8659.log)

**Comment by Bracket5** [comment]
[Uploading 22-07-19_17-48-59_3514.log…]()

**Comment by Bracket5** [comment]
Most recent, happened just now
[22-07-20_18-32-22_9713.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9152823/22-07-20_18-32-22_9713.log)

**Comment by ParanoikCZE** [comment]
Well, these are not crash logs but normal ones and they are cropped somehow to 4KB, so useless.

**Comment by Bracket5** [comment]
[error.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168297/error.log)

**Comment by Bracket5** [comment]
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168299/Player.log)

**Comment by Bracket5** [comment]
[error.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168303/error.log)

**Comment by Bracket5** [comment]
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168306/Player.log)

**Comment by Bracket5** [comment]
[error.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168395/error.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9168396/Player.log)

**Comment by Bracket5** [comment]
last one is most recent

**Comment by zuff-coi** [comment]
I'm seeing a lot of "Attempt to access invalid address." This could be due to the game trying to autosave to a protected folder. This is caused by Windows Ransomware Protection and possibly other AV that are protecting the Documents Folder. 

Disabling this may fix the issue. You can find the settings for in in Windows Security. Please try that and let me know if it works!

**Comment by Bracket5** [comment]
AV software and windows ransomware has been turned off for ages, before I even started playing the game
Is it worth moving the game to a HDD instead of using a SSD M.2?

**Comment by MaFi-Games** [comment]
This is RAM access violation. Seems like this is coming from Unity, we have seen this before already. Hopefully our planned upgrade to the latest version of Unity might help this.

**Comment by Bracket5** [comment]
[error.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9176365/error.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9176366/Player.log)

Crashing after 30 seconds of loading a saved game

**Comment by Bracket5** [comment]
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9270039/Player.log)

It does not support crash log file type after recent update

**Comment by MaFi-Games** [comment]
We have recently upgraded to new version of Unity. Did the crash go away? If not can you please provide logs?

**Comment by Bracket5** [comment]
After days of searching the internet one guy had the solution.
My MSI motherboard had XMP enabled causing the crashing.
Since turning it off in the BIOS not a single crash for days!

**Comment by MaFi-Games** [comment]
Thanks for letting us know!
