### ISSUE TITLE
All vehicles stop working

### ISSUE THREAD

**Issue by Leatherd** [MaFi-Games/Captain-of-Industry-issues#61]
**Describe the issue**
All vehicles stop moving (after completing their current job) all other parts of the game continue.  factories, conveyors, auto-trade ships, food production, even the truck que length is being incremented.  This has happened 3 times in this play through (but only after recent update?) after some time (approximately 2000 seconds in the truck que) they have started to move again but pause again later.  I have loaded this save 3 times and the same thing has happened (I also have 2 other saves, but they are after trucks freeze)

**To Reproduce**
1. Load attached save 'Dave 004.save'
2. wait until early January 0478
3. All Vehicles stop, but game continues

**Expected behavior**
All vehicles continue to work

**Additional context**
 - Game version: 0.2.14

**Attachments**
[Dave 004.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7371731/Dave.004.zip)
.

**Comment by MaFi-Games** [comment]
Thanks for the report, we will need to investigate this further.

**Comment by MaFi-Games** [comment]
Sorry , given this is an older version, we won't be investigating this anymore.
