### ISSUE TITLE
Thermal Desalinator

### ISSUE THREAD

**Issue by papa-sl** [MaFi-Games/Captain-of-Industry-issues#610]
### Issue description

Hello, i found mistake, Thermal Desalinator which converts Seawater and steam Hi in water and brine working not correct. He converts 60 + 12 = 36 +24 in 1 min. Description is different. 

### Expected behavior

please correct

### Game version

v.0.4.8

### Attachments

![Thermal Desalinator](https://user-images.githubusercontent.com/109704559/180102635-faba2c76-e8f0-4544-a0e3-595a74accfa5.png)

**Comment by MaFi-Games** [comment]
I don't think I follow what is the issue? I don't see anything wrong there.

**Comment by MaFi-Games** [comment]
That's certainly not possible. It must return what is stated in the UI. If not that would be major bug in all the machines and that was never reported. If you have a save file where it returns 36 instead of 48, please provide it so we can take a look.

**Comment by MaFi-Games** [comment]
Closing as there it not enough information to proceed.
