### ISSUE TITLE
Mine control tower bad behavior

### ISSUE THREAD

**Issue by Lutenar** [MaFi-Games/Captain-of-Industry-issues#611]
**The issue**
I assigned a new excavator to a mine control tower and it didn't show up. I saw that the tower was associated with a paused excavator, although there was an unpaused idle one available.

**Expected behavior**
Assigning a new vehicle to a mine control tower should ignore (if possible) paused vehicles.

**Additional context**
 - Game version: 0.4.8

**Comment by zuff-coi** [comment]
Resolved in experimental  v0.4.9
> - Assigning of vehicles (for example to storage or mine tower) now prefers non-paused ones.
