### ISSUE TITLE
Poor choice of color combinations on warning msgs (for color blinds)

### ISSUE THREAD

**Issue by FrankBKK** [MaFi-Games/Captain-of-Industry-issues#615]
### Issue description

Warning messages like (MUST BE MANAGED BY A MINING TOWER AREA) are displayed in red on dark grey
which is barely readable for people with color blindness issues 

Can you please change that or add an option in settings to change colors / color combinations ? 

Given that 8% of the male population have this condition I think this is a valid complaint ;-) 

### Expected behavior

readable text 

### Game version

latest

### Attachments

![Captain of Industry - Color Issue](https://user-images.githubusercontent.com/12725516/180592802-1e442fca-4e2d-41bf-aad7-3c2006597edc.jpg)

**Comment by FrankBKK** [comment]
nope, not fixed yet - any warning messages in red on grey are still barely readable :-(

**Comment by MaFi-Games** [comment]
Would you please have an example of error coloring that you are able to see clearly but is not same as the regular text? E.g. would  dark red background with white font work?

**Comment by FrankBKK** [comment]
yes, that would work - any high contrast combination works fine 

![image](https://user-images.githubusercontent.com/12725516/185753199-22ebc052-3ef1-45f0-a876-c0696c884db2.png)

**Comment by FrankBKK** [comment]
Just had a chance to check out 0.4.11 - it is fixed now - the white on read is perfect !
