### ISSUE TITLE
Bug ao inicializar

### ISSUE THREAD

**Issue by GustavoDemarchi01** [MaFi-Games/Captain-of-Industry-issues#616]
### Issue description

Quando vou iniciar o jogo (entrar no meu mundo), ele da uma tela de erro.

### Expected behavior

Eu esperava que ele entrasse no meu mundo

### Reproduction steps

1. Clicar no save do jogo
2. Aparece uma tela de erro

### Game version

v.0.4.8

### Attachments

[](url
![Captura de Tela (3)](https://user-images.githubusercontent.com/84157892/180617597-c732aa70-bcd3-42cb-9d60-f958bef4aa06.png)
![Captura de Tela (2)](https://user-images.githubusercontent.com/84157892/180617604-fa79fe83-0ff7-4696-988e-db2589916fee.png)
)

**Comment by zuff-coi** [comment]
Precisamos de um arquivo salvo e logs para ajudar a corrigir esse problema.

Salvar jogo:
"Documents\Captain of Industry\Saves"

Histórico:
Você pode encontrá-los em "Documents/Captain of Industry/Logs"
e
"%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\"
