### ISSUE TITLE
Typo in flywheel description.

### ISSUE THREAD

**Issue by erkle64** [MaFi-Games/Captain-of-Industry-issues#617]
### Issue description

The description of the flywheel, when hovering it in the toolbar, says "looses power".

### Expected behavior

It should say "loses power".

### Reproduction steps

Hover the flywheel icon in the toolbar.

### Game version

v0.4.8

**Comment by zuff-coi** [comment]
Resolved in v0.4.9c experimental 
![image](https://user-images.githubusercontent.com/108291414/182317423-0baa572b-d612-4763-9f2b-7dbc86aa5020.png)
