### ISSUE TITLE
Trucks stopped building structures

### ISSUE THREAD

**Issue by industrialCoder** [MaFi-Games/Captain-of-Industry-issues#619]
### Issue description

My trucks have stopped building structures entirely.  They will only be built if I use unity/quick deliver.  It seems to be triggered by some sort of game time event (meaning that I loaded an autosave before the issue occurred and was able to build things for roughly the same duration between the time of that autosave and the time they stopped building in the other save).  Vehicle activity indicator says stable, and there are idle, unassigned trucks.

### Expected behavior

Trucks keep building structures as usual

### Reproduction steps

1. Load Save
2. Trucks won't build
3. Second save is from before the issue is triggered.  In this save, I just continued to build my water/steam production facility for 5-10 mins and the issue occurred

### Game version

v0.4.8

### Attachments

[saves.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9176297/saves.zip)

**Comment by zuff-coi** [comment]
I've try to reproduce in the [latest experimental update that was released yesterday](https://store.steampowered.com/news/app/1594320/view/3397421255147457179) and could not. Everything was built fine. Please try out the new update and let me know if it's fixed!

**Comment by industrialCoder** [comment]
I managed to get things working again.  I'm not certain this was the cause, but it may have been because I had some storages containing construction parts set to stay partially full, so even though I had construction parts, my trucks weren't taking them from those storages.  Would be nice to have some indicator of that, like maybe a portion of the bar showing how full your storages for a certain resource are is a different color indicating how much of that inventory is actually accessible to your trucks vs kept in storage because of keep full settings

**Comment by zuff-coi** [comment]
> set to stay partially full
That's the culprit, then. Before the latest experimental, trucks would avoid pulling from storages with the sliders set to "Keep Full" at any percentage. This is no longer the case. Glad that you're issue is resolved. Thanks!
