### ISSUE TITLE
My save is glitchy

### ISSUE THREAD

**Issue by Azanek** [MaFi-Games/Captain-of-Industry-issues#62]
**Describe the issue**
There are lots of glitch around my factory. It is not playable loke that

**To Reproduce**
Are to reproduce, it happens out of nowhere. 

**Expected behavior**

**Additional context**
 - Game version: 0.2.14

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainO
![21-10-21_20-34-50_5332_photo](https://user-images.githubusercontent.com/92343776/138376608-758bab3e-1e7e-4737-8b75-1992e02df607.png)
![21-10-21_20-32-34_5406_photo](https://user-images.githubusercontent.com/92343776/138376610-871f2ebe-7d7a-409d-92e2-f85e28f88673.png)
![21-10-21_20-32-40_8794_photo](https://user-images.githubusercontent.com/92343776/138376612-f5ba0e6a-04ab-4161-8ee1-196a7a4ddf2e.png)
![21-10-21_20-34-16_6091_photo](https://user-images.githubusercontent.com/92343776/138376613-33f441dc-72f1-4194-ada8-f0bed0419c6a.png)
![21-10-21_20-34-23_2220_photo](https://user-images.githubusercontent.com/92343776/138376614-3cb49ae2-7525-4c7e-866d-53fe929a4157.png)
![21-10-21_20-34-34_5389_photo](https://user-images.githubusercontent.com/92343776/138376615-91d6dcd1-9690-40ef-ab05-0a2a8bcbf773.png)
fIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thanks for the report but without attached save file we are unable to reproduce this. If you encounter this again in the upcoming beta release, please report it.
