### ISSUE TITLE
Cargo ship (Oil) departs before fully unloaded.

### ISSUE THREAD

**Issue by K-DaK** [MaFi-Games/Captain-of-Industry-issues#623]
### Issue description

The oil tanker departs before it is fully unloaded.
The dock and its modules is full of oil and the ship will sit there and slowly unload when there is oil consumed. But it departs before it is empty.

### Expected behavior

Ship should wait until it is fully unloaded before it makes another trip.

### Reproduction steps

Load save EarlyDepart.
The ship is just departing here for the second time in a row without getting fully emptied.
Wait for it to come back, wait some more for the normal consumption to use up the crude oil.
And it will leave again too early for a 3rd time.

Note: If I increase the draw by upgrading the 2 cache-tanks in front of the dock, the ship will empty fully.
So it seems to be a problem with low draw/consumption.

### Game version

v0.4.8

### Attachments

![image](https://user-images.githubusercontent.com/8342763/180859047-4dbe870f-abf0-41f6-b88c-fd0178b0344e.png)
[EarlyDepart.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9184263/EarlyDepart.zip)

![image](https://user-images.githubusercontent.com/8342763/180859499-9e56e494-6c35-4d2a-8527-1b0009cdbf27.png)

**Comment by zuff-coi** [comment]
[Yesterday's experimental branch update](https://store.steampowered.com/news/app/1594320/view/3397421255147457179) should have resolved this. Please confirm!

**Comment by K-DaK** [comment]
Yes. 0.4.9a seems to work as it should.

**Comment by zuff-coi** [comment]
Thanks @K-DaK !
