### ISSUE TITLE
Typo in ending credits

### ISSUE THREAD

**Issue by FioraAeterna** [MaFi-Games/Captain-of-Industry-issues#625]
### Issue description

When I launch the rocket, at the end of the credits, it says "... ok, now you can go back and finish flattenning of the entire island."

### Expected behavior

This is a typo, it should be "flattening".

(I might also suggest "flattening the entire island" instead of "Flattening of the entire island" too while you're at it).

### Reproduction steps

1. Launch a rocket, view credits.

### Game version

v0.4.8

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in previous version.
