### ISSUE TITLE
Trucks won't export from storage with minimum fill regardless of level

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#629]
### Issue description

I have a storage for Iron, fed by belt from my iron smelter.  It feeds an Assembly (electric) making Mechanical Parts, but it's also my only Iron storage, and other Assemblies farther away need Iron deliveries by truck.  Because it's feeding that one Assembly by belt, and I'll probably make more iron smelters eventually, I set the Iron storage to Keep Full at the lowest level (18).  Even though the storage is completely full (180), my trucks refuse to export Iron from it (both Truck Export and Truck Import are On -- I even tried toggling them back and forth).

### Expected behavior

I would expect trucks to export from a storage as long as they leave at least the Keep Full amount inside it.  (Truck Export has its own toggle, which doesn't become locked when Keep Full is set.)

### Reproduction steps

1. Set a storage to Keep Full at a low level (say, 50%)
2. Fill up the storage completely
3. Build a machine that requires the stored material as input.
4. Ensure Export/Import settings allow trucks to move that material from the storage to the machine.
5. Observe: Trucks do not move the material.

### Game version

v0.4.8

**Comment by ParanoikCZE** [comment]
It's not supported to export from storage that has full settings set. You need to improve your logistics.

However, it would be nice if the export toggle is switched off if any keep x is set. And same goes for imports if there is an empty rule set.
