### ISSUE TITLE
Clone transport not fully deactivating after right click

### ISSUE THREAD

**Issue by scepter-architect** [MaFi-Games/Captain-of-Industry-issues#63]
Observed behavior, to reproduce this issue:

Press C for copy mode (key or button)
Click an existing transport belt or pipe segment on the map
Then right click somewhere to deselect the tool
Now click an item, a settlement for example
Notice that it is trying to copy the item

Expected behavior:

When cloning a transport belt...
Any right click will deactivate the clone
and the next click is a selection

v0.2.14

Thank
❤️infiniteseries

**Comment by MaFi-Games** [comment]
Thanks for the report, I was able to reproduce this and we will be working on fix.

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta release, thanks for reporting!
