### ISSUE TITLE
Cargo depot telegraph isn't enabled/disabled automatically during gameplay

### ISSUE THREAD

**Issue by dgzeij** [MaFi-Games/Captain-of-Industry-issues#630]
Cargo depots have their restricted ocean access telegraphed on the water. When deleting the cargo depot the telegraph stays behind (is not deleted with the cargo depot as expected).

Before restarting the game:
![20220726232727_1](https://user-images.githubusercontent.com/85814950/181116979-26b6ede9-5027-4798-a23b-47f5e01e7847.jpg)

After restarting the game:
![20220726233237_1](https://user-images.githubusercontent.com/85814950/181116993-65e8ac7e-345c-4619-96c1-06b12ba77ca0.jpg)

[save_22-07-26_23-39-39 cargo depot telegraph test.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9193524/save_22-07-26_23-39-39.cargo.depot.telegraph.test.zip)

When testing with a new cargo depot it's the same when building it. The telegraph isn't enabled when building, so have to restart the game to see it.

COI 0.4.8

**Comment by super-aardvark** [comment]
I just noticed the same thing with the Trading Dock.

**Comment by MaFi-Games** [comment]
Does this require restart of the game? Is it enough to deselect and re-select the entity?

**Comment by super-aardvark** [comment]
> Does this require restart of the game? Is it enough to deselect and re-select the entity?

What entity?  The depot/dock that the telegraph belongs to doesn't exist anymore.

**Comment by dgzeij** [comment]
The telegraph should be a property of the building so that it cannot exist on its own. Then it's easier to activate/deactivate the telegraph.

**Comment by zuff-coi** [comment]
This issue is resolved as of [v0.4.11 experimental patch. ](https://www.captain-of-industry.com/post/diary-30)
