### ISSUE TITLE
Construction UI: height display misleading when joining transports/conveyors

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#631]
### Issue description

When placing a transport ghost, there's a helpful tooltip near the cursor that displays the height at which you're building.  When you change the height (default Q/E), a sound effect plays to indicate that the height was changed (or not changed, if at the limit) and the tooltip changes to show the new height.  However, this tooltip becomes distinctly _un_helpful when you're hovering over an existing ghost in order to join to it.  In that case, the height it displays is whatever the height was set to when you started hovering over the ghost.  Changing the height plays the appropriate sound effect, but the tooltip does not change until you move the mouse away from the existing transport/ghost.

### Expected behavior

I would expect ONE of the following two things to happen:

1. (**Preferred**)  The tooltip shows the height of the transport/ghost you're about to join to.  This would be very helpful, as you could rely on that instead of peering at the little section of ghost that represents what you're about to place, among all the conveyor ghosts you may have already placed at various heights in that area.

OR

2. The tooltip shows the current height setting, and updates as normal when you change it.  Even though the height you'll actually build at if you click is not that, at least the tooltip would be consistent with the audio feedback you get when pressing Q/E.

### Reproduction steps

1. Place a section of conveyor ghost on the ground.
2. Press E to increase the height to 1.
3. Begin to place another conveyor joining the existing ghost in the middle (but don't click).
4. Observe: the tooltip still says "HEIGHT: 1" even though you're about to join to a conveyor at height 0.
5. Press E three times to increase the height.
6. Observe: sound effects play indicating that the height was increased twice and then couldn't be increased a third time.  However, the tooltip still says "HEIGHT: 1" even though that's NEITHER the height at which you're about to build (0) NOR the height at which you'll build if you move the mouse elsewhere (3).

### Game version

v0.4.8

### Attachments

![captain_height_ui](https://user-images.githubusercontent.com/3050938/181148927-43a9215c-ce31-4bff-9242-33ae512f07cc.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
