### ISSUE TITLE
Can't pass pipes over certain city attachments (eg: Waste collection, food market)

### ISSUE THREAD

**Issue by ppboyle** [MaFi-Games/Captain-of-Industry-issues#632]
### Issue description

There is a big open area between where these facilities attach to the settlement and the facility that seems like it should allow passthrough of belts and pipes at suffient height, but you can't.

### Expected behavior

Expected a height 2 or 3 belt or pipe to be able to pass through these areas.

### Reproduction steps

1. Build a settlement.
2. Attach a food market.
3. Try to build a pipe that passes over the pictured area off the market in the attachment.

### Game version

v0.4.8

### Attachments

![Pipe area](https://user-images.githubusercontent.com/16405334/181162057-d0b2b049-2046-4b01-9283-8522859288d4.jpg)

**Comment by MaFi-Games** [comment]
Thanks but we don't want to allow this use case as we might want to change these areas in the future.
