### ISSUE TITLE
CoI crashes

### ISSUE THREAD

**Issue by kbcmdba** [MaFi-Games/Captain-of-Industry-issues#633]
### Issue description

I'm running CoI on a Macbook Pro under Parallels Desktop in a Windows 10 VM. When I suspend my machine, then resume, if CoI is running before going to sleep, CoI crashes on resume with a screenshot from earlier and a display mode change (from fullscreen to windowed). Fixing it requires a Windows-Tab to see the taskbar so I can force close CoI, then restart it from where I last saved.

### Expected behavior

When I resumed Windows, I expected CoI to come back where it left off.

### Reproduction steps

See Description

### Game version

v0.4.8

**Comment by zuff-coi** [comment]
Please provide logs

You can find your logs in `Documents\Captain of Industry\Logs` and `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`

**Comment by kbcmdba** [comment]
Please find the associated files attached.

This is reproducible consistently.

**Comment by zuff-coi** [comment]
Sorry @kbcmdba but I do not see any attached files.

**Comment by kbcmdba** [comment]
Hmmm. I'm sure I attached them yesterday. Attaching them again.

**Comment by kbcmdba** [comment]
FYI - I verified that I did attach the logs both yesterday and today. If
that doesn't work, please let me know how you would like me to proceed. :-)

**Comment by zuff-coi** [comment]
Are you sending them through email? That could be why. Please visit the github issue page here: https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/633 and drag and drop them into the comment section. They sometimes need to be in a zip in order to upload. 

Let me know if you have any questions.

**Comment by kbcmdba** [comment]
[Player.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9255780/Player.zip)

**Comment by kbcmdba** [comment]
There you go 😄

**Comment by MaFi-Games** [comment]
We have recently updated Unity. Could you let us know if the crash is stil occuring and if yes provide new logs? Thanks a lot!

**Comment by kbcmdba** [comment]
Yes

________________________________________

**Comment by kbcmdba** [comment]
Yes, the issue is still happening.

Also – please note that when using CoI in Parallels, I am having the following issues:


  *   When drawing the mining box for a mining tower, the box is immediately active after clicking on the Edit button. I would prefer that it acts more like it does on a Wintel box where you can click on the Edit box and it waits for the button to be released then pressed again before declaring the box active.
  *   Make it possible to file bugs from the game menu during development. I don’t want to have to leave an active game to make suggestions or report bugs.
  *   Give the user power to decide when to draw all trees or not. For example, on my Mac, I would want to draw all trees when in harvest mode.
  *   Give the user the power to decide when to draw grid lines and leave them on. I like the “L” menu, but I would like to hide the menu and leave things on normally like grid lines, underground water, …
  *   Given the “length” of games being more than 20 game years commonly, it seems that being able to plant trees should be an option.

From: KB Benton ***@***.***>
Date: Saturday, August 20, 2022 at 10:01 AM
To: MaFi-Games/Captain-of-Industry-issues ***@***.***>
Cc: KB Benton ***@***.***>, Your activity ***@***.***>
Subject: Re: [MaFi-Games/Captain-of-Industry-issues] CoI crashes (Issue #633)
Yes

________________________________________

**Comment by zuff-coi** [comment]
Please provide new logs from the crashing

**Comment by kbcmdba** [comment]
Attached logs again...
[22-08-30_08-38-33_1627.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9456327/22-08-30_08-38-33_1627.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9456328/Player.log)

**Comment by kbcmdba** [comment]
No crash yet on 0.4.11! 😊

From: Captain Zuff ***@***.***>
Date: Monday, August 29, 2022 at 11:09 AM
To: MaFi-Games/Captain-of-Industry-issues ***@***.***>
Cc: KB Benton ***@***.***>, Mention ***@***.***>
Subject: Re: [MaFi-Games/Captain-of-Industry-issues] CoI crashes (Issue #633)

Please provide new logs from the crashing

**Comment by MaFi-Games** [comment]
In the last logs I see video player issues. This will be gone in next update.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
