### ISSUE TITLE
Cargo Ship 8 making all unity disappear when clicking on it

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#635]
### Issue description

From NZ_Wanderer and JD-Plays:

"when clicking on them When you are paused or NOT you loose unity"
"It seems to be a per ship unity cost"
"this amount will be deducted several times per second till you select something else"

Screenshots
https://cdn.discordapp.com/attachments/1002260702284754954/1002421622382264432/unknown.png?width=810&height=593
https://cdn.discordapp.com/attachments/1002260702284754954/1002421622705238026/unknown.png?width=810&height=511

### Expected behavior

Not to lose unity

### Reproduction steps

Load save
Click on lvl 8 cargo ship
Check unity

### Game version

v0.4.9

### Attachments

Save file: https://mega.nz/file/dTQnDYBT#uL0NFamXni8UbQlWqZgPxWXOZ7GoBtBVSzrZTpmBQTE

**Comment by ukjohnd** [comment]
Occured on a 6 Module Cargo Ship also, please see attached save/screen capture
![20220730021526_1](https://user-images.githubusercontent.com/31622605/181864895-de786934-2099-4b15-97c7-424c53eb5d66.jpg)
[6 Module ship unity drop.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9224092/6.Module.ship.unity.drop.zip)

**Comment by ukjohnd** [comment]
Confirm fixed for my save with v0.4.9a, Thankyou

**Comment by zuff-coi** [comment]
Thanks for the confirmation @ukjohnd !
