### ISSUE TITLE
Dumping Issue

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#636]
### Issue description

the trucks will go to other dedicated storage which are strictly  set to other MCT  

### Expected behavior

they should dump the rock and dirt in the nearby dumping zone

### Reproduction steps

as soon as u load the file you can see the trucks and check where they are going

### Game version

v0.4.9 Experimental 

### Attachments

[Uploading Dumping bug.zip…]()

**Comment by MaFi-Games** [comment]
The save file did not get uploaded, can you please try it again?

**Comment by knmh84** [comment]
[Dumping bug.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9221016/Dumping.bug.zip)
hope this time it got uploaded... sorry for the time it took as we had electricity problems here

**Comment by zuff-coi** [comment]
Just tested and can confirm this is happening. Escalated and thanks for the report!

**Comment by knmh84** [comment]
Welcome.... Glad to be of help...if I found any more I will report back so
we can have the best game of all times

**Comment by zuff-coi** [comment]
@knmh84 this issue has been fixed in the latest experimental update. Thanks for pointing this issue out!

Let me know if you have any issues and I'll reopen the ticket.
