### ISSUE TITLE
Assigned fuel truck partial loads

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#638]
Assigning a fuel truck to a gas station to keep your excavators full of diesel. It refills it's tanks at the gas station and delievers.

Problem: it will only fill up a portion of it's tank even though the gas station had 300+ fuel and was hooked up to T3 pipe.

![image](https://user-images.githubusercontent.com/65734844/181836416-f1a8406e-419c-465b-b82c-1538332a2ec1.png)

Solution: Adding additional fuel stations for general trucks to refuel at, leaving one gas station dedicated for the delivery truck. Force block any general truck to refuel. 

![image](https://user-images.githubusercontent.com/65734844/181836506-ea4446a5-c6cd-4934-abbf-a1bf69e44b03.png)

I'm going to guess incoming trucks going to a station "reserve" their fuel before they get there. This prevents the assigned truck from filling up it's cargo, even if it's hooked up to an endless supply.

In the save game, you can see the 3 fuel stations I've setup. Unpausing the two additional stations, and locking the top gas station with the delivery truck to not allow any vehicle to refuel there will solve the excavators running out of fuel because their fuel delivery truck is only bringing them partial loads.

However, it's understood that you can't always assume the gas station has an unlimited supply of gas. So reserving quantities for trucks that are en-route is very important, especially in the early game. 

Perhaps some transparency into "reserved" fuel quantities that is blocked off by incoming trucks to provide better transparency when a gas station is approaching it's throughput limit. 

[Fuel Issues.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9222964/Fuel.Issues.zip)

**Comment by lowstrife** [comment]
Uh oh. I just experienced a different behavior that actually throws everything I wrote above out the window.

Partial load:
![image](https://user-images.githubusercontent.com/65734844/181840128-7d8d3781-a590-48cd-905c-f96f7c3fdb6e.png)

But... it's the only allowed vehicle to refuel there:
![image](https://user-images.githubusercontent.com/65734844/181840168-5de8456e-ba8a-4b9c-9cfa-4f9600159baa.png)

**Comment by MaFi-Games** [comment]
Awesome! Thanks for your report! Your last post has helped us to find the issue. In the next path, the refuelling truck will wait as long as it keeps getting more fuel from the station and then it will leave This way the truck will be driving full.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
