### ISSUE TITLE
Deconstruction bug

### ISSUE THREAD

**Issue by knmh84** [MaFi-Games/Captain-of-Industry-issues#639]
### Issue description

if i want to deconstruct a pipe and use unity i get the parts back and if in the deconstruction phase the said pipe is damaged by an excavation the pipe reconstruct magically.. but give off all the parts

### Expected behavior

the parts should not be added to inventory or taken out again .... or the pipe should still keep going to deconstruct

more details are on discord.. you can find it with the link https://discord.com/channels/803508556325584926/883590993063051275/1002684658191958147

### Reproduction steps

build a long long pipe.. order to deconstruct it and use unity .. and before it deconstruct completely, have a small part of it collapse... the pipe will reconstruct and give extra parts

### Game version

v0.4.9 Experimental

**Comment by MaFi-Games** [comment]
Thanks for the report, this is fixed now and will be available in the next patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
