### ISSUE TITLE
Storage Demolished Bug

### ISSUE THREAD

**Issue by ThoraninC** [MaFi-Games/Captain-of-Industry-issues#642]
### Issue description

https://imgur.com/a/z85tT4K

Unit Storage Export Bug.

### Expected behavior

When demolish a storage it should automatically delink the storage

### Reproduction steps

1. Build A Unit Storage
2. Use Logistic Export Function to Another Storage
3.Demolish Target Storage
4. The link is exist but the said storage is gone

### Game version

0.4.8

### Attachments

[22-07-30_16-23-37_0250.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9225932/22-07-30_16-23-37_0250.log)

**Comment by MaFi-Games** [comment]
We cannot reproduce this issue and there is unfrotunately no information in the logs. Woud you have older logs available? Did you delete the storage recently or long time ago?

**Comment by ThoraninC** [comment]
https://drive.google.com/file/d/116tIInnFkI2oCaTd4qKvJWo0fUkhrzJD/view?usp=sharing

This is a save file that has a problem, I can't remember exactly when I delete it. But it might be before update

**Comment by MaFi-Games** [comment]
I think we have fixed cases like this but in older save files this can be still broken. If it happens again in newer version please file the issue again. I will consider it fixed for now. Thanks!
