### ISSUE TITLE
Big red icon on balancers.

### ISSUE THREAD

**Issue by K-DaK** [MaFi-Games/Captain-of-Industry-issues#646]
### Issue description

When placing balancers so they cover in/out-ports and open the config on the balancer, you are greeted with huge red icons.

### Expected behavior

Smaller icons pls. :)

### Reproduction steps

Load attached save and see for yourself or check the screenshots.
Or place a balancer on a input or output port on a storage for an example.
Click balancer for configuration window.

### Game version

v0.4.9a

### Attachments

![image](https://user-images.githubusercontent.com/8342763/181995976-9bf0d64a-58ec-41f4-91a6-61fc203ccd7f.png)
![image](https://user-images.githubusercontent.com/8342763/181995981-cbe0aa32-344e-4bf4-b6d5-a8cc6f29a1c1.png)
![image](https://user-images.githubusercontent.com/8342763/181995994-ef880ea1-09dc-42dc-8e6f-3167eb572143.png)
![image](https://user-images.githubusercontent.com/8342763/181996001-399451a2-27a3-4598-89c8-ce296d08ec30.png)
![image](https://user-images.githubusercontent.com/8342763/181996008-1294aabb-0995-409f-a69f-bd6ca3980210.png)
[Big Icon.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9227580/Big.Icon.zip)

**Comment by K-DaK** [comment]
Looks good in experimental now.

**Comment by zuff-coi** [comment]
Glad to hear @K-DaK ! Thanks for reporting it.
