### ISSUE TITLE
buildings not finished being built

### ISSUE THREAD

**Issue by Nershoo** [MaFi-Games/Captain-of-Industry-issues#647]
**The issue**
I'm sure this may have been put here already but randomly it seems trucks will not finish delivering construction material to newly built buildings If I were to make a guess I would say it would have to do with the new AI of allowing trucks to do more then one building at a time and somewhere along the way it just stops

Started a new map > paused > made out plans for the first blast furnace and two casters > everything got built but the last caster and the smoke stack for the furnace sat there on three times speed for 5 mins and the trucks did nothing but grab slag and wood never finishing the building and had to use unity > built 5 assembles and one also didn't get finished until I spent unity on it

**Expected behavior**
for the trucks to continue supplying the buildings until they are built

**To Reproduce**
I have no clue it seems to be at random

**Additional context**
Experimental build v0.4.9

**Attachments**

**Comment by MaFi-Games** [comment]
Thanks for you report. We fixed this issue in the latest experimental patch. Closing this issue as resolved as this bug has occurred only on experimental.
