### ISSUE TITLE
UI: Technology screen - Tooltip shows wrong item

### ISSUE THREAD

**Issue by super-aardvark** [MaFi-Games/Captain-of-Industry-issues#649]
### Issue description

When hovering over an item unlocked by a certain technology (in this case, Ship Bridge II), a tooltip is displayed for a different item (e.g. U-Shape Conveyor II) -- Whichever tooltip of the same type (item unlocked by research) was viewed most recently.

Bizarrely, the tooltip only appears if the mouse pointer enters the UI element at the correct place along the border.  As far as I can tell, either the top or bottom border is correct depending on the x-value.  For example, moving the mouse onto the icon from below, near either the left or right edge of the icon, causes the tooltip to appear, but moving from below in the middle of the icon does not.  Meanwhile, the reverse is true when moving down from the top -- the tooltip appears if you enter the middle of the icon, but near the edges there's no tooltip.  In any case, once the tooltip appears, it remains as long as the mouse stays inside the UI element.

### Expected behavior

- The tooltip should show information about the item the mouse cursor is over.  If there's no information, no tooltip should appear.
- The tooltip should appear any time the mouse is over the UI element; the point of entry shouldn't matter.

### Reproduction steps

1. Load attached save (probably optional)
2. Open technology screen
3. Select a technology which unlocks a building, e.g. Storage
4. Hover over the unlock (Loose Storage) to see the building tooltip showing description, cost, and supported products.
5. Select a Ship technology, e.g. Ship Armor
6. Hover over an unlock (Armor plating).  If no tooltip appears, move the mouse away and try again in a different spot.
7. Observe: depending on where the mouse enters the unlock item UI element, a tooltip appears.  The tooltip shows the information for the previously viewed tooltip (Loose Storage).

### Game version

v0.4.9a

### Attachments

![captain_tech_ui_tooltip_bug](https://user-images.githubusercontent.com/3050938/182001686-14b7a28f-82f9-42d5-9100-c513c5713a4d.png)
[Uploading tech-tooltip-bug.zip…]()

**Comment by zuff-coi** [comment]
Resolved in experimental v0.4.9c 
![image](https://user-images.githubusercontent.com/108291414/182317662-06eee5fb-30f7-4c86-b4b3-291108d72b9e.png)
