### ISSUE TITLE
BETA: difficulty presets

### ISSUE THREAD

**Issue by Hauklotz** [MaFi-Games/Captain-of-Industry-issues#65]
is it possible that some presets of the difficulty settings are reversed ?

at sailor the unity production is normal but on admiral it´s +20% increased

 - Game version: beta 0.3.0
![Screenshot_1](https://user-images.githubusercontent.com/8274799/146908965-ad7480e0-1caa-48cd-b227-972a8a8f0784.png)
![Screenshot_3](https://user-images.githubusercontent.com/8274799/146908969-07aa8485-c495-4926-b108-514ae105985d.png)

**Comment by MaFi-Games** [comment]
Thanks for your report, this is correct and intended. Admiral difficulty has unity production boost.
