### ISSUE TITLE
Demolish time for transports

### ISSUE THREAD

**Issue by Memnoch72** [MaFi-Games/Captain-of-Industry-issues#650]
### Issue description

It is probably a design decision to make the demolishing of belts to be **extremely**, **extremely** slow on the RK2 belts, and even **extremely**, **extremely**, **extremely** slower demolishing of RK3 belts.  I'm sure this will be the same issues if/when higher speed belts/pipes are added.  I can delete a long belt, let's say 50 squares long.  I turn up the speed to 3X and wait.  Then wait some more, then a little more waiting afterward,  After this period of waiting for the belts to demolish, I could have read a novel, made dinner, fixed global warming, and even possibly secured a date with Elizabeth Shue.  The 1994 version of Shue, not the current version, just in case that needed clarification.

Spending unity to demolish anything is a superb idea in your game, it really is a fantastic addition, kudos for it, really.  I am all for having to wait to demolish higher ranked items, they should be more difficult to demolish, but I honestly think that the time to demolish a RK3 belt is really, really, really slow.

So this would definitely be an idea to propose, I also think that there may be a bug in it.  Again, this could have been a design decision, but it doesn't make much sense to me.  A 80 tile long RK3 Flat, vs a RK3 U-shape takes twenty seconds longer.  It takes 30 seconds to demolish a 80 tile long U-shape transport, versus 50 seconds to demolish a RK3 flat transport.  So that is .375 seconds for each square of a U-Conveyor, and a .625 second demolish time for a Flat Conveyor.  All these tests were conducted at 3X speed also, I didn't want to have to wait an hour for belts to demolish ;)

RK3 Flat Transport and U-Shape transport both take the exact same number of construction parts.  The Flat definitely has a much longer demolish time.

I will submit this as an idea also, but having to wait a long time for a belt to demolish on 3X speed is a bit excessive, I think.

As another note, I tested this on every belt/u-shape transport, levels 0-3, loaded and unloaded on the U-shape.  The times were exactly the same whether the belt was loaded or unloaded, and didn't make any difference on whether or not it was raised or not.  I didn't check the loaded times for the belts, but if they were anything, it was probably longer.

### Expected behavior

Nothing really, just the length of time to demolish a transport seems off.  Belts should demolish at the same time, I also think that they should be faster.

### Reproduction steps

Make a long belt.  Demolish and time the belt.

### Game version

V0.4.9 (experimental) but same happens in stable release.

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
