### ISSUE TITLE
Excavators stuck in infinite loop - stop digging

### ISSUE THREAD

**Issue by mmikeyy** [MaFi-Games/Captain-of-Industry-issues#651]
### Issue description

Several (e.g. 4) excavators are working in a mine. Even though a large area is designated for excavation, they all end up bunched up in a small area and some of them stop working, as if they were interfering with each other. There are plenty of trucks waiting to be loaded, so trucks are not the problem.

### Expected behavior

I would expect all excavators to be digging, especially when there are more then enough trucks waiting to be filled.

### Reproduction steps

1) load attached saved game.
2) observe the small excavators in the iron ore mine. You may see 3, but there are 4. Two are inactive, despite numerous trucks waiting for a load. If you open their status window, you'll see messages cycling in an infinite loop.

Note: I had the same problem in the coal mine. Excavators kept ending up bunched up together with only a few digging, wich caused widespread coal shortages. I solved the problem by splitting the mine into two zones, each covered by its own control tower, and splitting the excavators between the two zones. One should not have to do that IMHO

### Game version

0.4.8

### Attachments

[save_22-07-30_23-51-47 iron ore excavator problem.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9228035/save_22-07-30_23-51-47.iron.ore.excavator.problem.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report. This was fixed in the experimental version already and should be available to everyone soon.

**Comment by zuff-coi** [comment]
Confirmed resolved in experimental v0.4.9c
![image](https://user-images.githubusercontent.com/108291414/182318047-06ef5dc8-c02a-4493-afb1-d98c1f7577f0.png)
