### ISSUE TITLE
Unity building uses all construction 2 parts

### ISSUE THREAD

**Issue by DRichmond2** [MaFi-Games/Captain-of-Industry-issues#655]
Regardless of how many construction 2 parts are required to carry out the unity build they all get used. After the unity build there are only 11 construction part 2 left in storage. 

To recreate the issue build somethng that requires construction 2 parts and then unity build it and watch the construction 2 part number drop.

Game version is Early Access 0.4.8
[save_22-07-30_22-10-29.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9228589/save_22-07-30_22-10-29.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting. Did you use any kind of cheats or mods to get more or less resources? I can see a buffer with negative resource amount and we are trying to figure out how happened.

**Comment by DRichmond2** [comment]
No mods or cheats in use.

**Comment by MaFi-Games** [comment]
Thanks. The corrupted state causing this has been hot-fixed in patch v0.4.9b (experimental), but the reason for state corruption is still unknown.
