### ISSUE TITLE
Truck deconstruct storage logic

### ISSUE THREAD

**Issue by Zardizz** [MaFi-Games/Captain-of-Industry-issues#656]
### Issue description

Trucks ignore the green "Keep full" bar when deconstructing a storage
https://streamable.com/kabzmm

### Expected behavior

Trucks emptying a storage to be deconstructed should not exceed max storage import rules.

### Reproduction steps

Load save
Follow the trucks moving limestone as they move 1 unit loads

### Game version

v0.4.9a

### Attachments

[BasicTest.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9229136/BasicTest.zip)

**Comment by zuff-coi** [comment]
Not sure I quite understand the problem, here. "Keep Full" doesn't mean stop filling once the line is met, it's quite the opposite. It means do not pull from this storage if below this line.

What you're wanting to achieve would be to use the "keep empty" slider just at the same point you had your other storage. 

Please correct me if I'm wrong. Also, your save file was corrupt, please try to reupload if you want me to test it again.

**Comment by Zardizz** [comment]
OK, I've simplified the issue even more by removing the keep full / keep empty stuff entirely from the example. On the attachment (hopefully works this time!) there is a save and when you load it you should be by a number of storages, one of them is set to be deconstructed, but as there is no storage room anywhere for them to move it to, they resort to moving loads of 1, rather than wait and use their full load. This leads to in worst case 60x truck use & diesel use with these trucks.

**Comment by Zardizz** [comment]
[BasicTest2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9241545/BasicTest2.zip)

**Comment by MaFi-Games** [comment]
I think the issue here is that trucks are carrying small quantities. We are looking into fixing this.

**Comment by Zardizz** [comment]
Yep. It makes no logical sense to do this really. By the way, the same applies for construction as well. I can send a save state of this as well if you want? let me know ok.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in previous version.  We no longer request trucks to transport small quantities unless the super "priority"  mode is used.

**Comment by Zardizz** [comment]
I will do another example and send that save file trough email? Not sure what corrupted the earlier one. And my bad here! I meant max storage allowed, can't believe I mixed that up.... sorry! There was a video link in the report as well, that shows the issue clearly as they send trucks loaded with 1 limestone, that is the issue, wastes a colossal amount of Diesel and is disobeying storage rules. I will try replicate and send a new save file once I get back home in about 2 hours.
________________________________
