### ISSUE TITLE
Gold recycling doesn't seem to be working properly

### ISSUE THREAD

**Issue by FioraAeterna** [MaFi-Games/Captain-of-Industry-issues#657]
### Issue description

Iron, copper, and glass recycling seem to be working as expected -- that is, with all edicts, 90% of that which is used by the settlement and/or maintenance gets returned in the form of scraps to be reused.

However, this doesn't seem to work correctly for gold. Only about 30% of gold bars used seem to come back in the form of scraps, resulting in consumer electronics being much more hungry for (new) gold ore than it would otherwise be.

### Expected behavior

I would expect gold recycling to follow the same efficiency rules as iron, copper, and glass, given that nothing else in the game's explanations indicates otherwise.

### Reproduction steps

The problem seems universal, so I doubt a specific save is necessary, but if it is, simply load the save and look at the usage graphs. ~6-8 advanced chips get used per cycle for maintenance, yet only 2-3 gold bars get returned as scrap.

### Game version

v0.4.9b

### Attachments

[22-07-31_21-39-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9230928/22-07-31_21-39-autosave.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report & save file! Gold scrap tracking was indeed incorrect, will be fixed in the next version! Thanks!

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
