### ISSUE TITLE
Farm yield

### ISSUE THREAD

**Issue by pcoud** [MaFi-Games/Captain-of-Industry-issues#658]
I was quite happy to see "Fixed farm yield estimates that did not take empty fields into consideration" in v0.4.9b patch notes. I am maybe missing something, but I can't see it working. Playing v0.4.9b, if I add or remove empty fields to whatever farm, I can't see the production estimates changing

<img width="224" alt="Capture d’écran 2022-08-01 102653" src="https://user-images.githubusercontent.com/90111363/182107498-c281af42-325e-425c-a8a0-8204d8b049cc.png">
<img width="537" alt="Capture d’écran 2022-08-01 102818" src="https://user-images.githubusercontent.com/90111363/182107531-7de39933-e49b-4f54-8deb-2718dde84f88.png">
<img width="619" alt="Capture d’écran 2022-08-01 102907" src="https://user-images.githubusercontent.com/90111363/182107548-e6eebf4f-239b-47c2-aab0-09bda8784eb0.png">

**Comment by MaFi-Games** [comment]
Thanks! We forgot to push the update. It should now be all there. Please let us know if not.

**Comment by pcoud** [comment]
It is !
Great, thx !
