### ISSUE TITLE
error when starting beta 0.3.0  

### ISSUE THREAD

**Issue by Killerk83** [MaFi-Games/Captain-of-Industry-issues#66]
![Screenshot_15 1](https://user-images.githubusercontent.com/91583110/146913352-1109982f-5392-481e-a1dc-8511cb088b60.png)
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by Cuda7000** [comment]
I am getting same thing I am on Steam

**Comment by MaFi-Games** [comment]
Thanks for reporting the issue and sorry for the late answer. For example, make sure mod support is turned off. Please let us know if you are still having issues.
