### ISSUE TITLE
Refuel truck stuck

### ISSUE THREAD

**Issue by Zardizz** [MaFi-Games/Captain-of-Industry-issues#661]
### Issue description

Load the save sent, the truck CLEARLY can reach all of the trucks but does not, but seems like what happened was, at some point one of them was unreachable and the truck never re-checks if this is still the case.

Just rising awareness to maybe fix this missing logic check.

### Expected behavior

Fuel trucks should re-check their pathfinding from time to time to avoid this happening.

### Game version

v0.4.9b

### Attachments

[NeedFuel.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9236251/NeedFuel.zip)

**Comment by zuff-coi** [comment]
This zip file is corrupted. Please reupload your save zip and wait until Github tells you it's complete before posting your comment. Thanks!

**Comment by Zardizz** [comment]
[NeedFuel.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9246094/NeedFuel.zip)

To be honest GitHub doesn't specifically tell that, not to me at least, the upload ends and I see the 'file' on this comment box, what am I meant to wait? This can't be this confusing to upload a file. I've tried re-zipping the file, though I have no idea what I could've done wrong. Who knows at this point.

**Comment by zuff-coi** [comment]
Yeah it's a little finicky but it worked that time!

Yep seems like there's something odd going on with pathing here. I think it has something to do with the steep cliff you're digging against and rock falling down around the excavators. I've passed this along to the devs!
![image](https://user-images.githubusercontent.com/108291414/182509402-9967732b-d9cf-446f-887d-8455ddad649e.png)

**Comment by Zardizz** [comment]
Yeah so, if you want you can pass this to the devs:

At one point before this save state, the truck in question WAS stuck there, so was I think every other truck as a lot of dirt fell down on the area from above, but they were still able to dig and dirt trucks came within the range they can still function. And so the excavators were able to dig themselfs out again, I am fairly certain the re-fuel trip start was attempted when they were on that small dirt mound and they all had that x on them, so the logic got stuck and never recovered until I force moved the refuel truck, it woke up to its own normal behavior immediately.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in our previous update. Refueling trucks now have increased distance tolerance.
