### ISSUE TITLE
Electronic parts suddenly on construction part conveyor

### ISSUE THREAD

**Issue by Grollstein** [MaFi-Games/Captain-of-Industry-issues#662]
### Issue description

[fehler auf band.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9237542/fehler.auf.band.zip)

**Comment by zuff-coi** [comment]
After removing the electronics on the belt I could not reproduce as of v0.4.9c.
![image](https://user-images.githubusercontent.com/108291414/182476533-b71801b6-05d9-4e7c-bd26-c446f5c2c0f8.png)

Perhaps you accidently connected this belt to another at some point? 

If it happens again, let us know!

**Comment by Grollstein** [comment]
Hi there ;-)
same mistake happens.
friendly regards
Wolfgang Schmidt Hüser
Captain Zuff wrote:
After removing the electronics on the belt I could not reproduce as of v0.4.9c.
Perhaps you accidently connected this belt to another at some point?
If it happens again, let us know!

**Comment by Grollstein** [comment]
...and again ... maybe it happens after saving game several times ?
Wolfgang Schmidt Hüser
Captain Zuff wrote:
After removing the electronics on the belt I could not reproduce as of v0.4.9c.
Perhaps you accidently connected this belt to another at some point?
If it happens again, let us know!
