### ISSUE TITLE
Tooltip for assigning trucks to tree harvesting is outdated

### ISSUE THREAD

**Issue by TumultuousTitan** [MaFi-Games/Captain-of-Industry-issues#663]
When selecting the harvest trees tool, the (i) tooltip references the old system where assigning trucks to tree harvesters was a global task. Since the change to give a tree harvester at the start was implemented the tooltip hasn't been changed.

**Comment by zuff-coi** [comment]
![image](https://user-images.githubusercontent.com/108291414/182476776-40905efc-b38c-4fdf-938c-0eb583826f61.png)
This is what @TumultuousTitan is referring to.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in our previous update.
