### ISSUE TITLE
Advanced Logistics Mining Trucks stuck in infinite wait loop (queue deadlock)

### ISSUE THREAD

**Issue by boldviking** [MaFi-Games/Captain-of-Industry-issues#664]
### Issue description

I have noticed twice in my last stream that I have truck which are assigned to a mining tower while using advanced logistics to designate a storage container, to be stuck in an infinite waiting loop.

The smallest example I had during the stream was A single mining tower, with one excavator, and two trucks. Both trucks where full and were standing in front of the loose storage to deposit their contents, both trucks where waiting in queue. 

I am pretty sure that this is a queue deadlock that happens in rare occasions. Still it happens and it is very annoying, especially if it happens to your main coal source which powers your whole base.

The workaround to fix the issue is just to reload a safe. This fixes the issue at a whole.

### Expected behavior

Truck logic should not dead lock itself

### Reproduction steps

Start a game, setup a couple of mining operations and wait. I can't provide a safe since the issue gets fixed when you drop a save and load it afterwards.

But have a look for yourself over here:
https://www.twitch.tv/videos/1549263505 at the 4:32:32 mark
or use this clip :)
https://clips.twitch.tv/QuaintObliqueSproutSmoocherZ-gYqJeEDRkIPTdk7P

### Game version

0.4.9b

**Comment by MaFi-Games** [comment]
Thanks for reporting this! Would you have by any chance a save file were this can happen? Even if load solves the issue we can still take a look.

**Comment by MaFi-Games** [comment]
We improved several cases in logistics for Update 1. Also, for this one, we, unfortunately, don't have repro steps. So closing for now.
