### ISSUE TITLE
Windowed Mode UI Issues on Right Side (can't click buttons)

### ISSUE THREAD

**Issue by monty1510** [MaFi-Games/Captain-of-Industry-issues#667]
### Issue description

In a windowed game, happening after update 0.4.9 if the screen is not large enough the menu items are not in the correct place.  At game launch could not close all the error alerts.  I have to increase the right side of the game window over to my 2nd monitor to resolve.  the new sort option for products is off depending on the size of the windowed game.  Full screen is fine

### Expected behavior

On the new .0.4.9 trying to grab the construction part icon, and move it to another location in the list.   or attempting to clear alerts by hitting the " x" .  both failed.

### Reproduction steps

Started after 0.4.9, and right after load completed.  does it on save or new game.  Happens every time in windowed game.

### Game version

v0.4.9c

### Attachments

https://drive.google.com/drive/folders/1_4laKI01XGDmqyVJjAjE2CrLBeQ8stLg?usp=sharing

Please see play through.  this site would not allow 15mb file upload.  in video i am trying to move the coal down. but as you see the products page open.. when i place the mouse below the wood icon, then the coal icon moves.

**Comment by MaFi-Games** [comment]
This is an issue in Unity that luckily has a workaround:
https://issuetracker.unity3d.com/issues/broken-mouse-pointer-input-coordinates-in-graphicraycaster-for-certain-window-sizes-in-build-when-run-in-windowed-mode

We will send a fix in the next patch.

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
