### ISSUE TITLE
The development tree has repetitions in technology

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#668]
### Issue description

Research Biofuel (6) and Research Steelmaking (8) open the same building Air Separation Plant

### Expected behavior

Adjust

### Reproduction steps

![paint](https://user-images.githubusercontent.com/110474947/182394052-62938227-314e-4956-bb60-610a38dbc8a1.png)

### Game version

v.0.4.9c

### Attachments

![paint](https://user-images.githubusercontent.com/110474947/182394226-38ccede7-c9ee-43e4-b489-6b1750f6633a.png)

**Comment by MaFi-Games** [comment]
That works as intended. Some nodes may not depend on each other so if we wouldn't put these technologies to both of these nodes, players would not have them available.
