### ISSUE TITLE
More Consumer Electronics Edicts increase the demand for household appliances. 

### ISSUE THREAD

**Issue by stevetrov** [MaFi-Games/Captain-of-Industry-issues#671]
The three edicts for More consumer electronics each increase the demand for household appliances according the "Total settlement need" tooltip in the Household appliances module.

**Comment by stevetrov** [comment]
I have now got to the stage of the game where I can confirm that its not just the tooltips that are incorrect and the edict applies to household appliances rather than consumer electronics.

**Comment by MaFi-Games** [comment]
Thanks for your report. This should now be fixed in our previous update.
