### ISSUE TITLE
Cannot Bind Free Look to Right Mouse Button

### ISSUE THREAD

**Issue by deimosian** [MaFi-Games/Captain-of-Industry-issues#672]
### Issue description

When trying to switch the right mouse button from `Move camera (hold)` to `Free look mode` the setting cannot be saved due to conflict with the `Alternative action / deselect` which cannot be changed.

### Expected behavior

Allow me to save it so that I can free look more easily as I use WASD for camera movement and the middle mouse button is awkward and prevents simultaneous scrolling with mouse wheel. 

### Game version

v0.4.9c

**Comment by MaFi-Games** [comment]
This was fixed shortly after Update 1. Thanks for your report.
