### ISSUE TITLE
Production speed is not correct

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#676]
### Issue description

Electrical Assembly Shop ( I I ) and Electrical Assembly Shop ( I ) have the same part production rate ( 20 )

### Expected behavior

Electrical Assembly Shop ( I I ) x2 parts speed

### Game version

v.0.4.9c

**Comment by zuff-coi** [comment]
When you say Parts, do you mean Mechanical Parts?

If so this is intended as a new recipe is added where you can use Steel in the Electrical Assembly II for 24/60 compared to the Iron which is 12/60

**Comment by Neek1ta** [comment]
Hi.
I mean  Assembly Electric Iron (5) time (20) sec output (4) mecanical parts 20 kw 6 worker and
            Assembly Electric ( II ) Iron (5) time (20) sec output (4) mecanical parts  BUT 30 kw 8 worker
