### ISSUE TITLE
Click

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#678]
### Issue description

When you exit the game, an unpleasant CLICK in the columns

### Expected behavior

To correct

### Game version

v.0.4.9c

**Comment by MaFi-Games** [comment]
I don't think I follow. Could you explain a bit more, what is the issue?

**Comment by zuff-coi** [comment]
> I don't think I follow. Could you explain a bit more, what is the issue?

I've experienced this myself, as well. When exiting the game (to desktop) sometimes the game audio comes through for a split second before shutting down. This can be somewhat unpleasant depending on what you're currently looking at as everything was muted before while in the menu UI.

**Comment by MaFi-Games** [comment]
This was fixed in one of our previous updates. Thanks!
