### ISSUE TITLE
Farm Production Does Not Appear in Recipes

### ISSUE THREAD

**Issue by deimosian** [MaFi-Games/Captain-of-Industry-issues#679]
### Issue description

Items produced via farms have blank production section in the Recipes screen, and consequently items without other recipes are entirely missing from the Recipes screen, notably Vegetables.

P.S. why can't excess veggies be composted?

### Expected behavior

Recipes screen shows they are produced via farms and shows all farm produced items even if there's no recipes that use them so the player is not left confused, wondering what if anything he can do with his excess crops.

### Reproduction steps

Look in Recipes screen for Vegetables.

### Game version

v0.4.9c

**Comment by zuff-coi** [comment]
Screenshots to clarify what @deimosian is referring to:
![image](https://user-images.githubusercontent.com/108291414/185755395-9446ce21-13be-4795-ab52-dbabcfb4c6a6.png)

![image](https://user-images.githubusercontent.com/108291414/185755398-64cd87f9-a401-48ef-b5d0-2e9b2c22f3a9.png)
