### ISSUE TITLE
Beta Start up Crash

### ISSUE THREAD

**Issue by Cuda7000** [MaFi-Games/Captain-of-Industry-issues#68]
**Describe the issue** 
Unable to start pick all default starting options than it says Game failed to initialize Please send a report 
I am on Steam Beta-0.3.0A

![146913352-1109982f-5392-481e-a1dc-8511cb088b60](https://user-images.githubusercontent.com/96530120/147095464-efeb4be5-066d-43be-850b-81e0cf1a82fc.png)

**Comment by MaFi-Games** [comment]
Is this still occurring? If yes, could you send us a log?
