### ISSUE TITLE
truck stuck trying to access inaccessible refueling station even though new one was built nearby

### ISSUE THREAD

**Issue by mmikeyy** [MaFi-Games/Captain-of-Industry-issues#682]
### Issue description

a truck signals its inability to reach a refueling station. Therefore I build a new one close by. But the truck never realizes it's there.

### Expected behavior

when a new refueling station is completed, the trucks' path to refueling stations should be recalculated.

### Reproduction steps

load attached saved game. There are only 2 mega trucks. One of them needs refueling (near center of screen, at bottom of copper ore ramp). There's a refueling station nearby (added while truck was already stuck). Its fully supplied with fuel. But truck remains jammed.

### Game version

0.4.8

### Attachments

[mega truck refueling problem.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9275663/mega.truck.refueling.problem.zip)
x

**Comment by TheStrato** [comment]
Related to mega trucks: 
Mega haul trucks are not respecting any of the restrictions. They are trying to navigate to fuel stations that don't have the "any truck can fuel here" ticked, they are not respecting dumping filters to only put dirt in a zone for example, and they are not retrying other options for fuel when they fail to reach said fuel station or just calling for a smaller fuel truck.

**Comment by TheStrato** [comment]
Also, point to point relocating the tankers near the fuel station I would like them to use allows them to use that one once, but it might be nice if using the point to point navigation "trained" it a bit if doing so resolved the navigation error perhaps.

**Comment by TheStrato** [comment]
Per the attached pic, it thinks it will just dump iron ore in a dumping designation for dirt only rather than taking the ore to the proper storage location. 
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/34151516/24c6dae1-2531-4173-a1a7-6e059d9c415c)

**Comment by MaFi-Games** [comment]
This might have been an issue with stalling logistics. We have also improved a few cases in refueling. Marking this as completed. If you still experience issues in the latest version, please file a new bug. Thanks!
