### ISSUE TITLE
screenshots

### ISSUE THREAD

**Issue by Grollstein** [MaFi-Games/Captain-of-Industry-issues#683]
### Issue description

Screenshots are **not** saved under documents/captain of Industry/screenshots

### Expected behavior

looking for screenshot, didnt find it

### Game version

v4.9.c

**Comment by zuff-coi** [comment]
This could be caused by a couple of things:

1) Are you hitting the screenshot key? (default P)
2) Is windows Ransomware protection on? This security system sometimes doesn't allow programs to write files to the documents folder.

**Comment by MaFi-Games** [comment]
This is the only bug we have on screenshots not being available. As there is no more information I will close this as not reproducible. But I suspect it was the ransomware protection.
