### ISSUE TITLE
ALerte 7 FPS IMPOSSIBLE TO PLAY

### ISSUE THREAD

**Issue by funky76000** [MaFi-Games/Captain-of-Industry-issues#684]
### Issue description

hello, 
I have a big problem with the game, impossible to play at the moment, waiting for a solution

### Expected behavior

to be able to play again because i love your game

### Reproduction steps

he best places on the map I'm at 40 fps, but the rest of the time I'm running under 10 FPS
I have a good computer
ryzen 5800
32GB DDR4 3600Mhz RAM
Rx 6900Xt
![7 fps](https://user-images.githubusercontent.com/110781991/183303096-0dd92345-986b-4633-a01f-8c68585afddb.png)
![task manager 2](https://user-images.githubusercontent.com/110781991/183303100-8a5e21cf-286b-4612-8fe0-30b266ae9322.png)
![task manager](https://user-images.githubusercontent.com/110781991/183303101-f868944c-7841-44d2-a6b7-ff29f0f0e85f.png)

### Game version

v0.4.9

### Attachments

![7 fps](https://user-images.githubusercontent.com/110781991/183303121-495ff7a5-b060-405f-bd5a-8a89daa7ec1e.png)
![task manager 2](https://user-images.githubusercontent.com/110781991/183303123-020e5f3b-45d6-48d1-b932-26b4b42fac00.png)
![task manager](https://user-images.githubusercontent.com/110781991/183303124-6b73a27e-a9d7-4789-82d1-9ad2a69b7f65.png)

**Comment by zuff-coi** [comment]
We just released a performance update on the experimental branch on Steam (v0.4.10).

Could you please try that branch out and see if performance has improved?

**Comment by MaFi-Games** [comment]
I can see lots of farms being constructed in the background. That introduces construction cubes which were reducing the frame rate quite a lot. Lucky news is that in v0.4.12, we have optimized construction cubes so much that they are no longer an issue. So this should be now working much better.
