### ISSUE TITLE
High maintenance while boosting production and maintenance buildings at same time

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#687]
**The issue**
Graph is showing extremely high Maintenance numbers which shouldn't be possible with current 3 maintenance II buildings:
![image](https://user-images.githubusercontent.com/108291414/183444344-b00c0ba9-5918-421b-9c43-e416798de7cc.png)

**Expected behavior**
Not to have so much store maintenance

**To Reproduce**
Describe steps to reproduce the issue here, for example:
1. Load attached save
2. Look at the maintenance chart
3. See how much maintenance is being produced

**Additional context**
 - Game version: v0.4.9c

**Attachments**
[NoPassForYou.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9282651/NoPassForYou.zip)

**Comment by mox05** [comment]
This bug appears when you boost your maintenance buildings AND other production buildings at the same time:

A = boost buildings and maintenance, B = only maintenance (it's recovering) C = only building (also recovering) D = both building and maintenance boost
https://imgur.com/a/6TAdmRQ

This is imo not only a graphical bug. My maintenance was over 1 hours on 0% and I could not recover from this until i removed the boosts.

**Comment by mox05** [comment]
What I notice is that if you boost them separately there is no problem, if you boost them both, buildings and maintenance, then it goes wrong

**Comment by mox05** [comment]
Me and another player provided more infos here:
https://discord.com/channels/803508556325584926/883590993063051275/1005491437061808208

**Comment by ManueldeHeer** [comment]
![20220806121618_1](https://user-images.githubusercontent.com/109023025/183688101-b6e17cfe-e3d8-4f49-a856-cc8ef25e9746.jpg)
![20220806121638_1](https://user-images.githubusercontent.com/109023025/183688105-83cebade-872b-4650-91d8-07a9493ed8b4.jpg)
![20220806200953_1](https://user-images.githubusercontent.com/109023025/183688137-5055db25-ba52-4309-a366-6bdc657eb028.jpg)
![20220806201056_1](https://user-images.githubusercontent.com/109023025/183688145-4c03cb74-67ba-485b-a1ac-a68798a445bb.jpg)

**Comment by ManueldeHeer** [comment]
This is on my new map You shall not Pass. No boost enabled. Look at the fluctuation.
![20220809173502_1](https://user-images.githubusercontent.com/109023025/183696587-bc454adf-af53-41c4-8da6-387e681818b2.jpg)
![20220809173515_1](https://user-images.githubusercontent.com/109023025/183696624-526df0d4-259e-4ece-84ff-d3d6548840e3.jpg)
[Manuel 414.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9292600/Manuel.414.zip)

**Comment by mox05** [comment]
https://www.youtube.com/watch?v=l7guX7d8e6Q

Video of the bug in action

**Comment by MaFi-Games** [comment]
Thanks for filing this bug and for all the input! There was indeed an issue in how we collected the maintenance stats. Next patch will fix this. The issue on video from mox05 above that is not related to the statistics bug. What is happening there is that your island has a global maintenance deficit (vehicles and machines are not fully repaired) that causes bigger drain on your maintenance.  Unfortunately that drain is not visualzied anywhere so that is probably why it is confusing. We will see how to show these "negative buffers".

**Comment by mox05** [comment]
duplicate issue:
https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/475

**Comment by MaFi-Games** [comment]
This should now be fixed. The only other task is to show the state of global maintenance buffers but we track that separately.  So we can close this now.
