### ISSUE TITLE
Activating Planning mode should not clear the selection on the cursor.

### ISSUE THREAD

**Issue by malaclypse2** [MaFi-Games/Captain-of-Industry-issues#688]
### Issue description

Activating or deactivating planning mode (either by the hotkey or by clicking the button) should not clear the current selection from the cursor. 

### Expected behavior

In particular, if the user has a large section cut or copied and are toggling planning mode on or off, their intent is likely to then plop down that selection, not have it cleared.

### Reproduction steps

Lay down some buildings and pipes so that their blueprints are showing. Use the 'Cut' or 'Copy' tool to select a piece of the larger whole. Realize you're in the wrong mode (either live mode when you would rather be in planning mode, or vice versa). Hit the hotkey to switch modes. Your selection has been cleared. If you used the Cut tool, instead of the Copy tool, you've just completely lost whatever bit of blueprint you had picked up. 

### Game version

0.4.9c

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
