### ISSUE TITLE
Ship upgrades without ship being in port?

### ISSUE THREAD

**Issue by Cengro** [MaFi-Games/Captain-of-Industry-issues#689]
### Issue description

I click on ship upgrade for armor plating on ship and ship will upgrade while out at sea?

### Expected behavior

Upgrade should wait until ship comes into dock.

### Game version

v0.4.8C

**Comment by zuff-coi** [comment]
The dockyard should wait for the ship to return before performing any upgrades.

You can assign upgrades and the shipyard will collect materials ahead of the ship returning
![image](https://user-images.githubusercontent.com/108291414/184543650-909beea5-200e-40de-b565-d07cb0fdd336.png)

Would you mind updating to the latest experimental branch (v0.4.10) and seeing if this issue still occurs?

**Comment by MaFi-Games** [comment]
Closing as not enough info.
