### ISSUE TITLE
Vehicles blocking

### ISSUE THREAD

**Issue by SigurdValiant** [MaFi-Games/Captain-of-Industry-issues#69]
**Describe the issue**
Vehicles are blocked by tree zone when there are no trees. they can't cross the map so.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**

**Additional context**
 - Game version: [Beta 0.3.0a]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Docum
![Screen Shot 12-22-21 at 06 12 PM](https://user-images.githubusercontent.com/51873693/147130188-bb4c0d06-2e4b-45be-bae4-fd417f89c390.JPG)
ents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by MaFi-Games** [comment]
Thanks for reporting, but without attached save file or screenshot we cannot investigate this problem. I will close this for now but if you have a save file feel free to re-open this issue and attach it.
