### ISSUE TITLE
Traceback at start of new game or savegame start - Mafi.Unity.UiFramework.Components.ToggleBtn

### ISSUE THREAD

**Issue by mcamen** [MaFi-Games/Captain-of-Industry-issues#694]
### Issue description

Reproduceable traceback when starting a new game or loading a savegame. See attached screenshot.

### Expected behavior

No traceback :)

### Game version

v0.4.10

### Attachments

![traceback](https://user-images.githubusercontent.com/14624618/184194007-5be015b8-e71a-43ae-81e2-a474ec172a23.png)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9310598/Player.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9310599/Player-prev.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9310630/Player.log)

**Comment by mcamen** [comment]
Turns out this was due to the CaptainOfCheats mod.

Sorry for the noise. :(

**Comment by MaFi-Games** [comment]
We have actually fixed it to be compatible. Try updating the game!

**Comment by mcamen** [comment]
I can confirm it's fixed now. :)
