### ISSUE TITLE
Loose storage ports visual bug

### ISSUE THREAD

**Issue by fara99** [MaFi-Games/Captain-of-Industry-issues#695]
### Issue description

Minor visual bug. Loose storage (didn't check any other) ports saved and reloaded in "deconstructing" state display blue ports.

### Expected behavior

Storage ports not to be blue.

### Reproduction steps

1. Build a loose storage
2. Start deconstructing it
3. Pause deconstruction or have it filled with something so it doesn't disappear instantly.
4. Save and reload your game
5. Ports are blue now

### Game version

v0.4.10

### Attachments

![22-08-11_19-52-27_6651_photo](https://user-images.githubusercontent.com/22475372/184204690-1eeadc44-b0dc-4163-ae27-860582023969.jpg)
[Beach.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9310814/Beach.zip)

**Comment by MaFi-Games** [comment]
This has been fixed, no patch notes, just update your game! Thanks for reporting!
