### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Nytridr** [MaFi-Games/Captain-of-Industry-issues#696]
**Building Transports** - Short runs is no big deal but longer runs I would suggest that instead of starting at one end working toward the other.. take 10% of the entire run and start there working out from the middle.  Every 10% of the transport would be a new build and start independently from each other.. This should help speed up longer transport builds.

**Upgrading tool** - (Upgrade tool could work like the unity tool also for you can select an entire area. [This would not start the chain upgrade action on the transports. {Able to select if you want just transports or transports and buildings to upgrade in the area}]) Start an upgrade at any point on a transport and it would start from there working its way out and when it comes to a connection point it would automatically start that upgrade also and then would also resort to the normal building rules from above for longer runs.  The main thing is it would auto upgrade all transports connected to the transport you start the upgrade on split into 10% increments. (This should also be able to be turned off in settings just in case you only want to do one area or one transport.)  (If the Transport you clicked on is already upgraded, it would also go through and double check each connected transport to make sure those are upgraded also)

**Balancer** - have a Low priority.. Low / Normal / High

**Sorter** - have an upgraded version where you sort to 3 lines instead of just 2 lines.. Or could add sorting to Balancers for an upgraded version.
Storage buildings Have the ability to turn on an Icon for each storage to show whats in the building. Like the alert icon. Also have a % next to it, that way you can see at a glance how full it is without going into the storage menu. (Option to turn on/off)

**Pausing and un-pausing buildings automatically with conditions**. Say if you have things getting full and things start filling up, you could have buildings go into a paused state if they are full for X amount of time, then releasing the workers to work somewhere else. The reassigned workers would automatically go back to the building that is auto paused the moment it can do work.. IF you have reassigned workers you could change the pop display to like an Orange or something saying that you have an issue that needs addressed, hence, your people need to start making some babies.. lol

**Comment by MaFi-Games** [comment]
Thanks for your suggestions.

Building Transports - next patch will speed up transport build
Upgrading tool - we have heard about this few times and it is on our radar but we track this separately.
Balancer - heard this request few times as well but not currently high priority for us, we will see
Sorter - honestly not something we will invest in any time soon
Storage buildings - I think we have a better plan :)
Pausing and un-pausing buildings automatically with conditions - not sure about this, this bypasses the costs for having machines ready to be used. In real world things also don't  pause / unpause this way, things have their  dling costs.

I will close this one as I hope I have replied to all of these and also these combined suggestions are hard to track anyways. Please feel free to file features ideas and uptove them here: https://ideas.captain-of-industry.com/
