### ISSUE TITLE
Recipes button works inconsistently

### ISSUE THREAD

**Issue by markdomansky** [MaFi-Games/Captain-of-Industry-issues#697]
### Issue description

If you mouse over the recipes button and click, the window that is displayed varies based on if the button shows white or yellow.
If the button is white, you get the inventory screen.  If the button in yellow, you get the recipes.  It seems that it only works if you have the cursor over the foreground parts of the button (white parts that turn yellow), and does not work correctly if you have your mouse on the background parts (dark grey).

This behavior has been present since at least 0.4.8x but I've finally narrowed down exactly what's happening.

### Expected behavior

Clicking anywhere on the recipes button should show the recipes screen.
Ideally, I think the button should show yellow when you mouse over it regardless of whether you are on the foreground or background parts of the button.

### Reproduction steps

1. Mouse over the dark part of the recipes button, ensure the button does not show yellow.
2. Click.  Should get the inventory screen
3. Click again to clear.
4. Move mouse to foreground part (light colored part)
5. Click.  Should get the recipe screen
6. Click again to clear.
7. Repeat.

### Game version

v0.4.9c

**Comment by fara99** [comment]
Just adding screenshot to this:
![recipesicon](https://user-images.githubusercontent.com/22475372/187087752-a89c9af3-0b39-45cf-a333-4f667cbb30b4.jpg)
- Clicking the grey icon itself opens Recipes windows as it should
- Clicking the black background opens Statistics window for whatever reason. 
No biggie, just gets annoying after few misclicks

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
