### ISSUE TITLE
Cargo Depot (4 port) gets pernamently stuck in blocked state after a ghost pump is placed and removed

### ISSUE THREAD

**Issue by Vectrobe** [MaFi-Games/Captain-of-Industry-issues#698]
### Issue description

The cargo depot (4 port at least) can get permanently stuck in a "Ship access is blocked" state if a seawater pump (tall) is placed within the vicinity, but not actually blocking the port's ghost tiles, and then removed before it is constructed.
The "Shovel ground..." button does nothing at all in this case, it simply does not function.

### Expected behavior

Well of course this just should not happen, but more importantly, the cargo depot should be able to recover from a locked-up condition such as this.

### Reproduction steps

I've attached the save file, you should be able to see the broken cargo depot and go from there.

### Game version

v0.4.9c

### Attachments

[factory seconds.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9313690/factory.seconds.zip)

**Comment by MaFi-Games** [comment]
Might be similar issue: https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/630

**Comment by MaFi-Games** [comment]
Thanks for the report. By any chance do you remember any other operations around the broken cargo depot that were blocking it? Maybe some terrain dumping, or other buildings? Or you just constructed depot and then a pump, without any other ocean-reaching buildings or terrain operations?

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
