### ISSUE TITLE
Trucks have the status "impossible to drive to the object" 

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#699]
### Issue description

Trucks have the status "impossible to drive to the object" and are idle until manually canceled.

### Expected behavior

1.Add a timer to cancel impossible tasks and switch to next tasks
2.Add truck assignments by priority (1) proximity to the manual destination (take out from here) and (2) body volume

### Game version

v.0.4.10

**Comment by zuff-coi** [comment]
Could you please provide a save file which has this issue occurring in it?

You can find save files in `Documents/Captain of Industry/Saves`

Thanks!

**Comment by Neek1ta** [comment]
1. We have a Building (target for a truck that cannot drive to it) with the status (trucking / shipment is allowed), fenced on all sides with tapes, pipes, other buildings (physically, the truck does not have an auto driveway to it)
2.Truck whose purpose is the building
3.Yellow cross above the truck (cannot pass)
4.Unlimited downtime of this truck
///
I find this truck, look at the red line where it cannot reach and disable it in the settings of the target building (trucking / shipping) and it switches to another task.

**Comment by MaFi-Games** [comment]
I appretiate the description but there is not much we can do without a save file.

**Comment by Loufe** [comment]
@MaFi-Games 
I'm not sure if I'm experiencing the same problem as the OP, but I have fuel trucks occasionally saying they cannot reach destination but the path is not blocked. Might be the same thing.
[dec 2023 c shaped island.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/13628549/dec.2023.c.shaped.island.zip)

Save attached has the issue at the time of saving.

**Comment by MaFi-Games** [comment]
@Loufe Your issue is that you have trapped that vehicle, it can be nicely seen in the overlay view:
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/90082857/1fc12633-d735-4c0b-b286-fb0d548d967e)
