### ISSUE TITLE
i tried to start a new game after the new update & its telling me failed to initialize

### ISSUE THREAD

**Issue by mikeym112** [MaFi-Games/Captain-of-Industry-issues#70]
**Describe the issue**
A clear and concise description of what the issue goes here.

**To Reproduce**
1. Load attached save '...'
2. Do xxx '....'
3. Strange thing happens '...'

**Expected behavior**

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by TheDarkSun85** [comment]
Same problem here

**Comment by Cuda7000** [comment]
Also same problem here

**Comment by Subzero121800** [comment]
Try turning off the Mod Tick mark > Reload game > should load without issues. I was having the same issue and this is all I changed.

**Comment by TheDarkSun85** [comment]
> Try turning off the Mod Tick mark > Reload game > should load without issues. I was having the same issue and this is all I changed.

I tried, did not work. But i searched all data that remained on my harddrive after deinstalling and removed it manually, then reinstalled the game and that worked for me
