### ISSUE TITLE
Ship Dock Fuel Bar not displayed after repair

### ISSUE THREAD

**Issue by brian-m-r** [MaFi-Games/Captain-of-Industry-issues#700]
### Issue description

Experimental version after todays update;
just repaired the ship dock but the fuel bar doesn't appear,
so can't refuel the ship.

### Expected behavior

Fuel bar shoud appear.

### Game version

v 0.4.10

**Comment by MaFi-Games** [comment]
This was fixed, thanks for your report (no patch notes, just update the game).
