### ISSUE TITLE
Quarry mining

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#702]
### Issue description

I will say for sure in my life I do not excavate in quarries. But I know that in reality the prey goes from the edges to the center, going deeper.
The game also has the ability to dig a straight line deepening into many cells. This leads to the sidewalls of the pit falling down. At the same time, the digging excavator rises above the surface of what was falling down, and "it does not look believable"

### Expected behavior

In this case, add that the excavator would be backfilled and the only way to dig it out was with the help of the "evacuation button."

### Game version

v.0.4.10

### Attachments

![deep](https://user-images.githubusercontent.com/110474947/184349816-ca404fb4-1fe5-45fd-98b3-bc559507f311.png)

**Comment by Neek1ta** [comment]
![underwater](https://user-images.githubusercontent.com/110474947/184420029-679c171d-a280-43eb-b7d0-6ac0561a6bb4.png)

**Comment by MaFi-Games** [comment]
I understand the desire for realism but this would punish casual players in great way. We are considering to provide some restriction on mining tall cliffs but that is something to analyze and we track it separately. So I will close this as won't fix.
