### ISSUE TITLE
Toggle price display error

### ISSUE THREAD

**Issue by brian-m-r** [MaFi-Games/Captain-of-Industry-issues#703]
### Issue description

Toggle price display seems like a good idea, but:
when placing buildings it can turn the display off, but not back on again
and toggle state is not remembered between placements, e.g. like auto snapping is.
So placing a pipe with  snapping on and display off and then placing a belt, snapping is still on but display has reverted to on.

### Expected behavior

toggle display state should toggle state when placing buildings and
toggle display state should be remembered.

### Game version

v0.4.10

**Comment by MaFi-Games** [comment]
This was fixed, thanks for your report (no patch notes, just update the game).
