### ISSUE TITLE
hydraulic valve

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#704]
### Issue description

The control valve can connect a pipe, but it does not work without a pipe adapter

### Expected behavior

To correct

### Game version

v.0.4.10

### Attachments

![2](https://user-images.githubusercontent.com/110474947/184396223-2b2ab046-1e73-43a8-b30d-f74161ab448d.png)
![3](https://user-images.githubusercontent.com/110474947/184396234-2acc723c-f810-435e-9276-23ba98ad51f7.png)

**Comment by MaFi-Games** [comment]
Balancer can't be directly connected to machines for several technical reasons. That's why it shows you the red icons everywhere. It is still allowed to be built because in same cases not connecting port to an entity is not necessarily an issue.
