### ISSUE TITLE
Water Magically Created In Pipe

### ISSUE THREAD

**Issue by brian-m-r** [MaFi-Games/Captain-of-Industry-issues#705]
### Issue description

In attached save file I have two concrete mixers with connected pipe (they used to have water collectors attached, but I removed them trying to pinpoint the bug). Connector between the two mixers contains 60 water, the lower section of pipe 17 water and the upper section (size 13) has 4 water, (with another connector between the two pipe sections with 2 water). When either of the concrete mixers finish their cycle they accept 4 water from the connector between them. This is replenished at 1 per second from the lower section of pipe. This lower section reports 16 / 17 water for 4 seconds indicating water flowing into the connector between the mixers. But the upper section of pipe always has 4 water.

### Expected behavior

I expect the water contained in the pipes to reduce as the concrete mixers use water.

### Reproduction steps

1. Load attached save file 'Brian 1 V5 Water.sav'
2. Monitor water in connected pipes as concrete mixers complete their cycle.

### Game version

v0.4.9c

### Attachments

[Brian 1 V5 Water.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9328981/Brian.1.V5.Water.zip)

**Comment by zuff-coi** [comment]
Letting this run for a while in 3x shows that it eventually pulls from the last pipe
![image](https://user-images.githubusercontent.com/108291414/185754684-2a69aae9-ba9e-4c7b-b72b-89fbe97e421c.png)
What I think happened here is the mixers themselves had full water storage (40) and it just took a while for all of the water to be pulled from the pipe/connectors in small amounts.
![image](https://user-images.githubusercontent.com/108291414/185754723-9a2e9b0d-b3c0-4a2a-b9a6-a8cc232d4548.png)

As for the last pipe not emptying at all, that is odd behavior and I'll escalate it as such.

**Comment by MaFi-Games** [comment]
Yep, this is UI issue. The mini zipper in fact contains much more quantity than it shows. Will fix.

**Comment by brian-m-r** [comment]
Hi Captain Zuff,

 

You clearly haven't investigated very thoroughly.

On loading the saved game, running at 1x speed:

before either concrete mixer completes its cycle:

 concrete mixers contain 40, joint between them 60, lower pipe 17, upper
pipe 4, joint between then 2.

After either concrete mixer completes its cycle, using 4 water:

 concrete mixers contain 40, joint between them 60, lower pipe 17, upper
pipe 4, joint between then 2.

This is surely wrong, even though, if you leave it long enough, it
eventually starts using water.

 

I think it is caused by the deleted water collectors. Before deletion the
joint between them contained 61 water. and after deletion it is shown as 2
water, but it seems likely that the water is not actually deleted and it is
this water that the concrete mixers are using.

 

Which begs the question: why does a junction of pipes contain more water
than the tank of a water collector? It seems a little ridiculous.

 

Regards,

Brian M. Reeder

 

  _____

**Comment by brian-m-r** [comment]
Thanks for this, but I have no idea what a 'mini zipper' is.

 

Regards,

Brian M. Reeder

 

  _____

**Comment by MaFi-Games** [comment]
the juction is what we call mini zippers. they have a big buffer when they are connected to multiple pipes (e.g. 4) to accomodate all the throughput for technical reasons. Since you have removed few pipes the capacity was adjusting. Anyway, the UI glith was fixed in v0.4.11. Thanks for your report!
