### ISSUE TITLE
Magically created maintenance

### ISSUE THREAD

**Issue by brian-m-r** [MaFi-Games/Captain-of-Industry-issues#706]
### Issue description

In attached save file a maintenance building has generated 105 maintenance and has its output blocked.
Maintenance level is at max of 1260. Every second it drops to 1257 then back up to 1260, 
but doesn't use any of the generated maintenance.

p.s. I've gone back to v0.4.10 since you fixed the ship dock, but I think the problem exists in previous version
and may be the same mechanism as the 'magically created water' reported yesterday.

### Expected behavior

Maintenance should be used.

### Reproduction steps

1. Load attached save file 'Brian 1 V5 Maint'
2. Open maintenance building in centre of screen and watch maintenance values.

### Game version

v0.4.10

### Attachments

[Brian 1 V5 Maint.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9330597/Brian.1.V5.Maint.zip)

**Comment by zuff-coi** [comment]
Can confirm this is happening in v0.4.10. Did you happen to have more maintenance depots before this save that you had just deconstructed?

**Comment by MaFi-Games** [comment]
We have found the issue. It is related to our fix of maintenance in last patch. Will be fixed in the next one.

**Comment by brian-m-r** [comment]
I can confirm I had another depot that has been recently deconstructed.

 

Regards,

Brian M. Reeder.

 

  _____

**Comment by Bl4zedxY** [comment]
Noticed same issue with 1 of my 3 maintenance buildings.

**Comment by zuff-coi** [comment]
This issue has been resolved in the [latest experimental branch, v0.4.11](https://www.captain-of-industry.com/post/diary-30)
> Fixed internal buffers in the Maintenance depot that could accumulate large amounts of maintenance.
