### ISSUE TITLE
Toggle price display shortcut key error

### ISSUE THREAD

**Issue by brian-m-r** [MaFi-Games/Captain-of-Industry-issues#707]
### Issue description

Toggle price display shortcut key doesn't work for copied transports after a game load.
It does still work by clicking the icon.
It works when creating a transport from the menu and then for everything thereafter.

### Expected behavior

Shortcut key should work all the time.

### Game version

v0.4.10

**Comment by MaFi-Games** [comment]
I have just tried to load  a game and copy transport and the shortcut works for me. Or do you mean that the state of it being toggle was not preserved after game load?

**Comment by brian-m-r** [comment]
Load a game,

hover mouse over transport (pipe or belt),

press 'c' to copy it,

press 'y' - nothing happens.

Select transport from menu - price display state works properly thereafter,
or

click 'price display' icon - price display state toggles and works properly
thereafter.

 

This is true for all my saved games including those I have already sent you
for issues #705 and #706.

 

Hope this helps,

Regards,

Brian M. Reeder

 

  _____

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
