### ISSUE TITLE
Vehicles not refueling from fluid tank.

### ISSUE THREAD

**Issue by Robinhoodthefletchling** [MaFi-Games/Captain-of-Industry-issues#71]
Vehicles Not Refueling From Tanks
Vehicles will do their tasks and not stop at a fluid tank with fuel to refuel themselves

**To Reproduce**
Don't know. reloaded the save and it did not happen again
[Bugs Ahoy.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7766611/Bugs.Ahoy.zip)

 Strange thing happens '...'
 Vehicles will not refill fuel even when tank is available.
**Expected behavior**
Vehicles should be able to get fuel from the tank as the do in the save after it was reloaded.

 Beta 0.3.0a

It happen while it was set up like this
![image](https://user-images.githubusercontent.com/96559670/147186371-92375cb7-789b-47a1-b109-66de80c81cdf.png)

**Comment by MaFi-Games** [comment]
Thanks for reporting this issue and for attaching save file. Unfortunately I was not able to reproduce this, was this happening to you again?
