### ISSUE TITLE
Trucks should have a tasking option. 

### ISSUE THREAD

**Issue by jack198338** [MaFi-Games/Captain-of-Industry-issues#711]
### Issue description

trucks remain idle even with things to do

I have buildings that need built. I have construction parts needing moved. Trucks just remain idle. Ya'll need to add full control of trucks. Like click the truck assign to unload parts from assembler. This game is supposed to be as if we are the foreman. Well a foreman isn't going to just sit around and let trucks remain idle when there are things to do. 

### Expected behavior

I have buildings that need built. I have construction parts needing moved. Trucks just remain idle. Ya'll need to add full control of trucks. Like click the truck assign to unload parts from assembler. This game is supposed to be as if we are the foreman. Well a foreman isn't going to just sit around and let trucks remain idle when there are things to do. 

### Game version

newest

**Comment by jack198338** [comment]
Now i also get "vehicle can't reach destination. 

Path is flat and clear but truck will not move. For $30 I expected better

**Comment by zuff-coi** [comment]
Hi @jack198338

Sorry you're experiencing this issue. Could you please me the save file that this issue is happening in?

You can find your save files in `Documents/Captain of Industry/Saves`

**Comment by MaFi-Games** [comment]
Closing as not enough information provided. Feel free to file a new bug once you have a save file.
