### ISSUE TITLE
Warehouse Functionality expansion

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#714]
### Issue description

The warehouse is connected to the conveyors input output of the same type of products. It is not possible to set a non-unloadable balance of goods (for example, for construction)

### Expected behavior

add the ability to reserve the quantity of goods

### Game version

v.0.4.10

**Comment by zuff-coi** [comment]
Just to clarify you'd like the storages to be able to withhold items from going out on the belt? Like a slider specifically for transports?

**Comment by Neek1ta** [comment]
Да , спасибо

**Comment by MaFi-Games** [comment]
That would make the UI very convoluted. It is maybe up for future considerations but let's please keep GitHub focused on issues and not feature requests. Please file features ideas here: https://ideas.captain-of-industry.com/
