### ISSUE TITLE
Crash when attaching Transformer to housing

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#716]
### Issue description

Game crashes when attaching Transformer to housing. Created from email sent by Matthew via email. They attached log files which are included below.

I've also reached out for Version number and Save file, awaiting response from them.

### Expected behavior

Not to crash

### Game version

Unknown

### Attachments

[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9333644/Player.log)
[22-08-10_02-42-05_7197.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9333645/22-08-10_02-42-05_7197.log)

**Comment by MaFi-Games** [comment]
This seems like an issue in windows actually
https://answers.microsoft.com/en-us/windows/forum/all/help-games-that-use-unityplayerdll-crash/fbcdea60-7a64-4e19-969a-ce5b4c9de137?page=1
In one of the other topics someone pinpointed similar issues to this: ""Windows 7 Crash when using GPU without D3D11.1 support or without KB2670838 installed
