### ISSUE TITLE
Connection of two belts.

### ISSUE THREAD

**Issue by axelxan** [MaFi-Games/Captain-of-Industry-issues#718]
### Issue description

When you connect belt A to belt B, material will not get outputted if there is no building/storage/etc. after connector that would connect to a belt.
![image](https://user-images.githubusercontent.com/23004078/184559315-54e4e5d8-c7b7-4f31-996e-b5dd983e423b.png)
On the second image you can see the behaviour.
![image](https://user-images.githubusercontent.com/23004078/184559353-5554fdf2-3597-493b-bff3-1608b439fc05.png)

### Expected behavior

I expected belt to be loaded with material.

### Game version

v0.4.9c

**Comment by zuff-coi** [comment]
Maybe a dev can chime in on this, but this is intentional. I'll mark it as a feature request.

**Comment by Frankdcoockle1** [comment]
I would disagree to make this a request. I think it is as intended and that is the way it should be. As soon as you attach something to that belt so it has a "demand" the material will flow down. I don't see why you would want to have a belt full of stuff that has nowhere to go

**Comment by MaFi-Games** [comment]
This works as intended and was a deliberate choice. There are more downsides to send products to unconnected belt than upsides. In games like COI where player does not have a charecter to clear these belts easily it can be annoyance to have products sent there. In fact we hardly see a useful situation. You get a smaller delay until you connect something there but that  is better than going through the hassle of consntaly pausing long lines of unconnected transports. ONI made a same decision for instance.
