### ISSUE TITLE
Transformer is not providing power to settlement

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#719]
### Issue description

![image](https://user-images.githubusercontent.com/108291414/184905547-ace48ee3-b677-4a1d-8487-3cacfdd5a319.png)

If you delete the transformer and rebuilt it, the power works. If you build a second one, the power works,

If you delete the second one, this one continues to NOT work.

### Expected behavior

Transformer to provide power to settlement

### Reproduction steps

1. Load save
2. Make sure you have the mod [Captain of Cheats v1.8.0 installed](https://github.com/altmank/CaptainOfCheats/releases/tag/v1.8.0)
3. Check Transformer

### Game version

v0.4.10

### Attachments

[save_22-08-15_07-39-21.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9351966/save_22-08-15_07-39-21.zip)

**Comment by utdrmac** [comment]
Does this behavior exist without the cheat mod? If not, then this is an issue to be investigated by the mod devs, not core.

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
