### ISSUE TITLE
Two days no response to problem

### ISSUE THREAD

**Issue by Cuda7000** [MaFi-Games/Captain-of-Industry-issues#72]
On Steam Beto V 0.3/0A
Wont start playing just crashes when you try New Game

If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
![146913352-1109982f-5392-481e-a1dc-8511cb088b60](https://user-images.githubusercontent.com/96530120/147267601-5858b4c0-e6b0-4730-abc6-66a239c88003.png)

**Comment by Subzero121800** [comment]
Try turning off the Mod Tick mark > Reload game > should load without issues. I was having the same issue and this is all I changed.

**Comment by Cuda7000** [comment]
Thank you that got me back in the game

**Comment by MaFi-Games** [comment]
Thanks Subzero121800, we should probably add a warning about this.
