### ISSUE TITLE
Remove from the conveyor belt

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#720]
### Issue description

We have
1. I click Remove from the conveyor belt
2. An empty unoccupied truck is standing nearby and does not react to the order in any way
3. Some other truck is coming from afar for my assignment
4. I wait and get angry

### Expected behavior

Add priority for trucks by distance

### Game version

v.0.4.10

**Comment by MaFi-Games** [comment]
Locality of truck jobs is something we might explore in the future. But we track that separately. Closing this as working as intdended.
