### ISSUE TITLE
Mining issues

### ISSUE THREAD

**Issue by scottdean1** [MaFi-Games/Captain-of-Industry-issues#723]
**The issue**
Assigning a specific product to a mine excavator is a waste of time as they will remove what ever they seem to want to.  This causes MAJOR issues as problem is usually not noticeable until what ever resource is being mined is no longer available.

**Expected behavior**
On a mining control tower with several excavators working one would be assigned to mine resource required (say Coal) while any other excavators would mine what ever the needed to. So long as "Coal" resource is accessible assigned excavator should mine ONLY that and nothing else.

**To Reproduce**
1. Assign two excavators to a mine control tower
2. Assign two mining regions in control tower zone, with one closer to mine control tower
3. Set closest one up as a down ramp starting in the dirt leading to resource.
4. Set the other one up further from control tower to gather surface resources 
5. Assign 1 excavator to mine resource (say Coal)
6. either assign other excavator to remove dirt or leave unassigned
7. Watch BOTH excavators start mining nearest the control tower with both removing dirt!!!!

**Additional context**
 - Game version: [e.g. 0.2.1a, see main menu]

**Attachments**
If applicable, attach a save file (zipped), screenshots, or log files to help us resolve the issue. You can find them in your Documents (`%userprofile%\Documents\Captain Of Industry\`). If your issue is severe, like a crash or rendering glitches, also include Unity logs from `%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\`. Thanks for taking your time writing this report!

**Comment by MaFi-Games** [comment]
This would be much easier if you would provide a save file of this happening. We are not aware of the priority being broken.

**Comment by scottdean1** [comment]
Attached (I hope) is a new game save that has only 2 mines with 1 excavator each. Both have their priority set one for coal one for iron ore.  Look at the coal excavator digging dirt, assigned coal available.  This was done from a new game so that there is minimal clutter from other game constructs
[Look_at_Coal_excavator_activity.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9388199/Look_at_Coal_excavator_activity.zip)

**Comment by MaFi-Games** [comment]
![image](https://user-images.githubusercontent.com/90082857/204058744-2e52f278-14c1-47e8-bc80-4666c9848590.png)
You were just unlucky. All the designations that can be mined (green) contain dirt. The ones that contain coal (red) are not available yet. So the priority is not broken actually, you need to get to the coal first.
