### ISSUE TITLE
Settlement Recycling tech un-researched after latest patch 0.4.10

### ISSUE THREAD

**Issue by Lancar223** [MaFi-Games/Captain-of-Industry-issues#725]
### Issue description

Settlement Recycling tech un-researched after latest patch 0.4.10
Building next to settlement still exists and still works, but the tech is available to be researched once again.

### Expected behavior

Peace on earth.
I know. I'm just as disappointed as you are.

### Reproduction steps

load attached save, open research screen and behold (the world of tomorrow!)

### Game version

v0.4.10

### Attachments

[Golden Peak3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9358116/Golden.Peak3.zip)

**Comment by MaFi-Games** [comment]
That works as intended. The building is still available, so there should be no blocker by having that node not unlocked.
