### ISSUE TITLE
Blueprint (or kind off)

### ISSUE THREAD

**Issue by MaxNLIT** [MaFi-Games/Captain-of-Industry-issues#726]
### Issue description

I think it would be useful if the "COPY" or "CUT" of a Factory Setup could be saved in some kind of form.
I've started many games, and I have some building setup for the smelting setup, the maintenance, etc.
Having to redo everything manually every time it's frustrating... especially with the difficulties of - in my case - matching all the input and output in a buslike, tileable approach.

### Expected behavior

It would be something like:

1. player press CTRL-C or CTRL-X
2. while in this mode the player can access a menu where it can save/load/delete a "blueprint"

### Game version

v0.4.10

**Comment by MaFi-Games** [comment]
We track mainly issues here. Please file features ideas and upvote here: https://ideas.captain-of-industry.com/
