### ISSUE TITLE
Recipes not available in 0.4.10

### ISSUE THREAD

**Issue by ksorbo** [MaFi-Games/Captain-of-Industry-issues#727]
### Issue description

When I click the recipe button on the far right left, nothing happens.

If I click just a little toward the top of the icon, the Statistics panel opens.

This was not the case in the previous release (0.4.9c)

### Expected behavior

Expect the recipe panel to open

### Game version

v.0.4.10

**Comment by ksorbo** [comment]
This apparently only happens in windowed mode. If I go to full screen, everything works as expected

**Comment by zuff-coi** [comment]
Duplicate of #667
