### ISSUE TITLE
Angle of repose

### ISSUE THREAD

**Issue by Grollstein** [MaFi-Games/Captain-of-Industry-issues#728]
### Issue description

the angle of repose of slag is incorrectly represented. The technical literature describes it as 28-35 %, depending on the moisture content.

### Expected behavior

the right reposeangle

### Reproduction steps

1 have a look to the picture please

### Game version

0.4.10

### Attachments

![schüttwinkel](https://user-images.githubusercontent.com/109280532/185232871-204f4542-e6dc-43be-b99b-f5115d2196c4.jpg)

**Comment by MaFi-Games** [comment]
Thanks but we are not really setting repose angles based on exact real params but based on gameplay.
