### ISSUE TITLE
Maintenance Parts Cap not reduced when demoing secondary Depot

### ISSUE THREAD

**Issue by LinkinBreak** [MaFi-Games/Captain-of-Industry-issues#729]
### Issue description

When you upgrade a Maintenance Depot to level 2, your global max of Maintenance Parts goes up by 2250. But, when you remove an upgraded depot, the global max only drops by 630, the amount of a Maintenance Depot Level 1. 

### Expected behavior

It is expected that when you remove a structure, that the global max will go down the correct amount as you no longer have that structure to store your parts.

### Reproduction steps
1. Built a Maintenance Depot level 1. Your global max is 630 Maintenance Parts.
2. Upgrade Maintenance Depot to Level 2. Your global max is 2880 Maintenance Parts. (2,250 were added to the global max when you upgraded.)
3. Build another Maintenance Depot. Doesn't matter which one. Say it's the level 1. Your global max will now be 3510, as you added 630 from the new level 1 Maintenance Depot.
4. Demolish the level 2 Maintenance Depot that you upgraded earlier. Your global max goes down to 2880, instead of 630 like it should as you only have the level 1 Maintenance Depot now. 
Note: If you build a level 2 Maintenance Depot from scratch and not from an upgrade, when you demolish that building, your global max goes down by 2880. It only doesn't go down if it was an upgrade. I have tested it over and over and have a single Level 1 Maintenance Depot that has 11880 global max of Maintenance Parts as I did this 5 times. (2250 * 5)+630=11880
### Game version

v0.4.10

### Attachments

_No response
![20220817234325_1](https://user-images.githubusercontent.com/111479149/185296250-bad3ceda-6aa3-466f-b8fc-5ef29a28b887.jpg)
_

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
