### ISSUE TITLE
Cannot Initialize Game (New in Beta)

### ISSUE THREAD

**Issue by Subzero121800** [MaFi-Games/Captain-of-Industry-issues#73]
**Describe the issue**
Multiple issues not allowing the game to initialize.

**To Reproduce**
1. Configure New Game
2. Attempt to Launch New Game
3. Error pop up that game cannot initialize.

**Expected behavior**
Game Should Start

**Additional context**
Beta 0.3.1
[Player.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7771050/Player.zip)

**Comment by Subzero121800** [comment]
Update: Turned off the MODS Tick option and reload game solved the issue this time.

**Comment by MaFi-Games** [comment]
Mods support is very experimental, we need to verify that game with mods can be started. I will leave this open until that verification is done, thanks!

**Comment by MaFi-Games** [comment]
We have improved mods error reporting in our previous updates.
