### ISSUE TITLE
World mine workers do not free up on shift change until inventory emptied

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#730]
### Issue description

From yandersen on discord:

> If it is paused due to full input and u change shifts down,  u do not get free workers till the cargo ship arrive and get the mine running again. Workaround is to stop the mine,  then level up shifts to the desired level.

### Expected behavior

When shift changes, get workers back immediately

### Game version

v0.4.10

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
