### ISSUE TITLE
NO Food

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#731]
### Issue description

The warehouse is full of food, but people are dying of hunger.

### Expected behavior

To Correct

### Game version

v.0.4.10

### Attachments

![nofood](https://user-images.githubusercontent.com/110474947/185682797-83f95593-b34b-441b-9e81-35df85aba764.png)

**Comment by MaFi-Games** [comment]
Please provide save file

**Comment by utdrmac** [comment]
Do you have another city block that is not adjacent to any existing blocks? In order for food to be used, all city blocks must be touching. If you have city blocks not touching then those are considered a _separate_ city block and must have _their own_ food storage buildings attached.
