### ISSUE TITLE
вычислительные центры

### ISSUE THREAD

**Issue by DyaDyaBaH9I** [MaFi-Games/Captain-of-Industry-issues#732]
### Issue description

вычислительные центры не работают и не выделяют ТФЛОПС , ставил сервера с первого по 48 и вода не остужается и все равно нет выделения ТФЛОПС , игра дальше продвинуться не может так как встала наука без строительных материалов 4 уровня, вода охлождается , но деть охложденнуя воду некуда не слить ее не остудить  , почему холодную воду только можно заводить в научные центры ? 
![тфлопс](https://user-images.githubusercontent.com/111636599/185741288-327df0ef-7d2c-46f7-8c48-5657accd0378.PNG)

### Expected behavior

ожирал что вычислительные центры , будут работать даже с 4 серверами как это требует автоматическая линия
![автоматическая линия](https://user-images.githubusercontent.com/111636599/185741450-2a25d1b8-7514-4be6-a567-9030c87f3e64.PNG)

### Game version

версия 0.4.10

**Comment by DyaDyaBaH9I** [comment]
стрим встал игра дальше не продвигается

**Comment by MaFi-Games** [comment]
Your warm coolant output buffer is full, thus the datacenter cannot work. Also for next time please provide save files, otherwise we can't investigate issues easily.

**Comment by DyaDyaBaH9I** [comment]
Во первых что такое буфер теплового хладагента , и Во вторых как его опусташить если охлажненная вода не применяется не где ??? в бочку она не наливается , в океан она тоже не сливается ?

**Comment by DyaDyaBaH9I** [comment]
все разобрался спасибо , интересно когда разработчики сделают посадку леса , очень не хватает

**Comment by MaFi-Games** [comment]
ok, glad it got resolved
