### ISSUE TITLE
crashing game constantly while playing

### ISSUE THREAD

**Issue by rgpatton** [MaFi-Games/Captain-of-Industry-issues#733]
### Issue description

The game seems to crash often. sometimes after playing for a while, and then sometimes within a few minutes of play time. 

### Expected behavior

continuous play

### Game version

0.4.10

### Attachments

[22-08-20_09-22-46_9651.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9387190/22-08-20_09-22-46_9651.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9387194/Player.log)

**Comment by rgpatton** [comment]
This is what is in the windows event log: 
Faulting application name: Captain of Industry.exe, version: 2021.3.6.41869, time stamp: 0x62bd0844
Faulting module name: UnityPlayer.dll, version: 2021.3.6.41869, time stamp: 0x62bd0972
Exception code: 0x80000003
Fault offset: 0x0000000000db4fd3
Faulting process id: 0x28c8
Faulting application start time: 0x01d8b49127d6cbfd
Faulting application path: D:\SteamLibrary\steamapps\common\Captain of Industry\Captain of Industry.exe
Faulting module path: D:\SteamLibrary\steamapps\common\Captain of Industry\UnityPlayer.dll
Report Id: d445b00c-99dd-424c-bf0d-87e3ec0532a5
Faulting package full name: 
Faulting package-relative application ID:

**Comment by MaFi-Games** [comment]
I'm sorry the game is crashing. Unfortunately I can't see anything in the logs. Would you have more logs avaialble? Also does this end with blue screen or just the app crashes? Are there any useful information in Event Viewer? https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/

**Comment by rgpatton** [comment]
only the app crashes. i get a grey window pops up from COI, seems to be gathering info, then it goes away and then the game disappears. It freezes in game once this happens. I have been playing it in full screen and now trying in a window. I run an fx8350 black edition, twin gtx980 Ti cards and 32gb ram. please let me know which logs you need to help figure this out. Thank you.

**Comment by rgpatton** [comment]
[report.zip.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9387240/report.zip.zip)
will this help?

**Comment by MaFi-Games** [comment]
Unfortunately there are no useful information in there.  Would you have more logs similar to the ones in 22-08-20_09-22-46_9651.log, Player.log?

**Comment by rgpatton** [comment]
I have tried going from full screen, to borderless and windowed. It does not seem to make a difference. I have had performance monitor open on a second screen and nothing stands out. It seems to be very sporadic. Some times it plays for an our or so, other times ten to fifteen minutes in and it freezes, then shuts down. Hopefully this log shows something?

[22-08-21_19-09-50_1801.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9390168/22-08-21_19-09-50_1801.log)

and another one: this one seems to have much more info in it.

[22-08-21_11-41-09_7104.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9390189/22-08-21_11-41-09_7104.log)

**Comment by rgpatton** [comment]
I found these files that may help figure this out....I hope.
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9390274/Player.log)
[crash.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9390290/crash.zip)

**Comment by rgpatton** [comment]
Looking through some of these reports, I noticed I had an error with windows video media error crashing the game. I found on the internet that unity once had this issue and I went into windows features, unchecked the windows media player, rebooted, then turned it back on in windows feature. It has not crashed since if this helps. I will continue to report back if the problem persists. Thanks.

**Comment by MaFi-Games** [comment]
I believe that we found the issue, it will be fixed in the next path. Thanks for the report!
