### ISSUE TITLE
Can't open saved game.

### ISSUE THREAD

**Issue by drewstur** [MaFi-Games/Captain-of-Industry-issues#734]
### Issue description

Was playing last night saved manually and then closed the game. The game did crash when selected "Quit" this has happened many times before thought nothing of it. Came to play this morning and got a "really sorry, but it looks like the save is corrupted error."

### Expected behavior

The game opens a saved file.

### Reproduction steps

Saved game manually
closed game
game crashed when closing (happens often) caused my computer to restart
came back the next day and save will not open

### Game version

4.10

### Attachments

[Save and Log.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9387197/Save.and.Log.zip)

**Comment by MaFi-Games** [comment]
Exception during game load.
 ---> CorruptedSaveException: Failed to finalize deserialization of 'Terrain chunk (-9, -5)' (type 'TerrainChunk'. Previous deserialized object: Terrain chunk (1, 5) (type TerrainChunk)
  at Mafi.Serialization.BlobReader.FinalizeLoading (Mafi.Option`1[T] resolver) [0x0003d] in Mafi\Serialization\BlobReader.cs:166 
  at Mafi.Core.SaveGame.GameLoader.FinishGameLoadAndDispose (Mafi.DependencyResolverBuilder resolverBuilder, Mafi.Core.Game.SpecialSerializerFactories specialSerializers) [0x00071] in Mafi.Core\SaveGame\GameLoader.cs:156 
  at Mafi.Core.Game.GameBuilder+<BuildLoadedGameTimeSliced>d__2.MoveNext () [0x0022f] in Mafi.Core\Game\GameBuilder.cs:194 
 ---> IndexOutOfRangeException: Index was outside the bounds of the array.

**Comment by MaFi-Games** [comment]
Thanks for reporting this. Could you please also share us all your logs so we can get more insight?

**Comment by MaFi-Games** [comment]
This issue contains this crash in logs as well: https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/686

**Comment by MaFi-Games** [comment]
Thanks for reporting. By any chance do you have a save (like an auto-save) before this issue occurred? I can see the issue with the save file but it is really hard to know how it may have occurred. A save before the issue could help us reproduce this.

**Comment by MaFi-Games** [comment]
The issue was found and will be fixed in the next patch. Unfortunately, the save file is corrupted and not recoverable, sorry!
