### ISSUE TITLE
Large Cooling Tower has incorrect behavior

### ISSUE THREAD

**Issue by FioraAeterna** [MaFi-Games/Captain-of-Industry-issues#735]
### Issue description

For most recipes in Captain of Industry, production does not trigger until a full load of input has arrived. For example, if a recipe is 16 steam lo -> 12 water, it would wait until 16 steam lo has arrived, then begins producing 12 water.

However, the Large Cooling Towers seem to not quite obey this; they start running even before 16 steam has actually arrived, even though their recipe states otherwise. This can be seen in the attached save, in the rightmost cooling tower in the coal power plant to the south.

While this may sound extremely minor, it actually has consequences. In my coal power plant, I pipe Steam Depleted (48 * 3 = 144 per 60 cycles) and Steam Lo from a scrubber (~14.4 per 60 cycles) into two cooling towers. These cooling towers _should_ be able to handle 96*2 = 192 per 60 cycles, but they don't, and as a result, the Steam Depleted ends up slightly backlogged, periodically jamming the power plant slightly.

To see the problem, watch the production of the aforementioned cooling tower. It will start venting Steam Lo _when only about 4 or 5 have arrived_, instead of waiting for the full 16, resulting in lower overall throughput than the theoretical max.

### Expected behavior

I would expect the Large Cooling Tower to only vent once its inputs have fully arrived, resulting in a full 96/60cycle production rate.

### Game version

v0.4.10

### Attachments

[mountain.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9388217/mountain.zip)

**Comment by MaFi-Games** [comment]
This is great observation! You are right that mixed recipes with partial utilization can reduce throughput significantly in cases like you've provided. We have made changes so that when there is a recipe with full input we disable partial utilization. That made the power plant you've shared us run smoothly. Fix will be in the next patch. Thanks!

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11. Thanks for your report!
