### ISSUE TITLE
Greenhouses should be able to be built on any type of terrain

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#739]
### Issue description

Unlike farms, greenhouses should be able to be built on any type of terrain.
![unknown](https://user-images.githubusercontent.com/108291414/185969620-641d820f-2cff-42dd-9bfe-12af9cdf2b1f.png)

### Expected behavior

Be able to build greenhouses on any type of terrain

### Game version

v0.4.10

**Comment by Frankdcoockle1** [comment]
Agree with this idea

**Comment by Jeferson-Emanuel** [comment]
I also agree with the idea. In the real world, green houses do not plant things on the ground, it uses "floating" structures where the plants are kept.

In game, a green house should be able to be placed in any kind of terrain, but, obviously, they need more water and fertilizer to compensate for not using the soil like other kinds of farms.

**Comment by MaFi-Games** [comment]
This works as intended. Allowing building a greenhouse on non-dirt tiles would require player to deliver dirt. Suddently that  requires to implement costs for greenhouses that dependend on current surface. Our greenhouses were not meant to be hydroponic vertical ones, if yes, they would require ongoing supply of compost. Anyway, let's please keep  feature requests on upvote and not here.
