### ISSUE TITLE
Pathfinding cant understand certain belt configuration.

### ISSUE THREAD

**Issue by Robinhoodthefletchling** [MaFi-Games/Captain-of-Industry-issues#74]
Target destination deemed unreachable when it should be.

**To Reproduce**
![image](https://user-images.githubusercontent.com/96559670/147294389-93d828e1-230c-44cf-93fe-d8689e105fe8.png)
[Bugs Ahoy V2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7771498/Bugs.Ahoy.V2.zip)

**Expected behavior**
Vehicle should be able to deliver to the unbuilt belt as it did for the other side

**Additional context**
 - Game version: Beta 0.3.1

**Comment by MaFi-Games** [comment]
This was actually a systematic issue with path-finding that was not able to reach buildings in tight areas. Thank you for reporting, your save file was very useful while debugging this! This will be fixed in the next patch!
