### ISSUE TITLE
Maintenance bug / not consuming materials

### ISSUE THREAD

**Issue by SirReycla** [MaFi-Games/Captain-of-Industry-issues#740]
### Issue description

I experienced a bug, where one of my maintenance facilities is stuck with full output. The maintenance is used correctly, but gets refilled instantly without using any matierials. When i pause the maintenance facility, the global maintenance is decreasing. And when unpaused again, maintenance gets filled up without consuming materials. I am not sure when that happened. I noticed it to late. I think this might have happened, when i switched the recipe to the one producing those recyclables. Or maybe a timing issue...

### Expected behavior

what goes wrong:
not consuming materials when providing maintenance
after pausing the facility, maintenance goes back to 100% in an instant
progress bar is always completely filled
changing recipes or their priority makes no difference

### Game version

v0.4.10

### Attachments

![MaintenanceBug](https://user-images.githubusercontent.com/111807697/186026295-4eb806fb-f828-427c-a5fd-ff1245e75a11.png)

**Comment by zuff-coi** [comment]
This issue has been resolved in the [latest experimental branch, v0.4.11](https://www.captain-of-industry.com/post/diary-30)
> Fixed internal buffers in the Maintenance depot that could accumulate large amounts of maintenance.
