### ISSUE TITLE
Shortcut Keys UI is overlapping when copying transport 

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#742]
### Issue description

When you have the build menu open and you use the copy tool to copy a transport , you get these overlapping icons
![image](https://user-images.githubusercontent.com/108291414/186197843-02ee93f0-1631-4088-9935-d70f5a8f47d5.png)

### Expected behavior

Those icons not to overlap

### Reproduction steps

1. Open build menu
2. Copy a transport using the copy tool

### Game version

v0.4.10

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.11.
