### ISSUE TITLE
Reclamation to the edge of the ocean will show the ground texture missing.

### ISSUE THREAD

**Issue by Corvus400** [MaFi-Games/Captain-of-Industry-issues#744]
### Issue description

![20220824162027_1](https://user-images.githubusercontent.com/13657682/186360697-c83d23af-5b2f-4e1a-9515-b79ecfeb9eca.jpg)

### Expected behavior

We had hoped that even if we reclaimed all the way to the edge of the ocean, the ground texture would show up without chipping.

### Reproduction steps

Reclamation to the edge of the sea.

### Game version

v0.4.10

### Attachments

[save_22-08-24_16-48-18.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9413996/save_22-08-24_16-48-18.zip)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
