### ISSUE TITLE
Status bar too big, keeps changing format

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#748]
### Issue description

I play with 2560x1600, Windowed (but full size), Scale 120%.

![2022-08-26 11_41_31-](https://user-images.githubusercontent.com/109154186/186962895-a45d6679-ef25-47b6-87d1-23a1e81a6cf6.jpg)
![2022-08-26 12_03_04-Captain of Industry](https://user-images.githubusercontent.com/109154186/186962907-27cb12e6-0b74-48df-bfab-bc182c96759e.jpg)

Apparently with 100% scale there is enough space, but at 120% scale sth. is wrong. Even if it stays single line, the shown items sometimes move sideways when content changes.

### Expected behavior

In 4.10 it still worked fine ...

### Game version

v0.4.11

**Comment by RealisticOptimist** [comment]
Update:
The items move sideways even with 100% scale. And I could clearly observe it happen on month changes. So (at least) the field length for displaying the month string is at fault.

**Comment by zuff-coi** [comment]
Just to clarify here, the bar is jumping back and forth between 1 and 2 bars at the end of each month?

**Comment by RealisticOptimist** [comment]
No, it's not a simple toggle:

See this (incomplete) collage:
![CoI_Statusbar](https://user-images.githubusercontent.com/109154186/187270873-a96f21a3-7562-4882-9168-8997db3f8db9.png)

Every time the date string changes length, the status bar changes. the placement of the object gets varied, in some cases it turns into two lines (which is correct when the window is too small).

There are two length changing events: 9th->10th every month. and every new month. Luckily the used font has mono spaced digits, otherwise the statusbar would jiggle a bit every day.

The space in the statusbar reserved for the date is not long enough.

When calculating the needed space for the date string within the status bar, for a given UI scaling for all 12 months (in the configured language, with a 2-digit day of month) the length needs to be calculated to determine the longest. Then that shall result in a stable statusbar for a given window size.

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
