### ISSUE TITLE
Silenced background music gets loud on terminating CoI

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#749]
### Issue description

Unfortunately I have to set music volume to 0%, as the music keeps playing even when I minimize CoI. And there is no sound mute button. Not good when I need the PC for phone calls, etc..

Since 4.10 I observe, on quitting CoI the music gets loud for a fraction of a second.

### Expected behavior

Music should respesct set loudness until the end.

Additionally I hope for:
- A mute button for the entire game sounds (not just one for notifications).
- Option to disable the music. Keeping it running at 0% loudness is an (admittedly small) waste of CPU resources (electricity).

### Game version

v0.4.10 (edited, I do not remember if it started 4.9 or 4.10)

**Comment by zuff-coi** [comment]
Can confirm. On close, even if the music is off, you get a split second of it at full blast before closing.
