### ISSUE TITLE
Redundant trucks dispatched when constructing many buildings at onces

### ISSUE THREAD

**Issue by FioraAeterna** [MaFi-Games/Captain-of-Industry-issues#754]
### Issue description

Sometimes, when building many buildings at once, some of the trucks carrying materials arrive at their destination only to find that their materials weren't needed, then return home to deposit them.

### Expected behavior

The game should not dispatch redundant trucks.

### Reproduction steps

1. Load attached save.
2. Watch the trucks go to build the solar panels.
3. If you watch carefully, you will see that some of them arrive carrying materials, realize they're not needed, then return home without doing anything.

### Game version

v0.4.11

### Attachments

[mountain2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9438655/mountain2.zip)
![extra truck](https://user-images.githubusercontent.com/7761472/187047810-b44b02e6-1239-43b0-81ef-cedbdcabaee9.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
