### ISSUE TITLE
Buffer Tank 2 cannot assign product

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#755]
### Issue description

Buffer Tank 2 can not assign a product, the only solution is to demolish and rebuild

### Expected behavior

to correct

### Game version

v.0.4.11

### Attachments

[spec11.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9439588/spec11.zip)

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
