### ISSUE TITLE
Load-time for savegames drastically increased since 0.4.10 

### ISSUE THREAD

**Issue by FrankBKK** [MaFi-Games/Captain-of-Industry-issues#756]
Is it only me or did the time to load a saved game drastically increase since 0.4.10 ? 

I noticed this the first time in 0.4.10  but it 0.4.11 it got even more worse. 

More than 5 minutes on a fast gaming rig with plenty of memory seems a bit over the top .... 

The savegame is a late game with lots of elements on a heavily terraformed map  so an increased load time can somehow be expected but THAT long ???

**Comment by zuff-coi** [comment]
Do you happen to have the save from 0.4.10 that I can test? Note: If it was saved in 0.4.11 it will not work.

**Comment by FrankBKK** [comment]
[Large Island 20.08.2022.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9446380/Large.Island.20.08.2022.zip)

here you go ...

**Comment by zuff-coi** [comment]
Loading your save file in v0.4.10 took 4:41
Loading it in v0.4.11 took 4:38 (roughly the same amount of time)

So no increase, but this is a good save to help us with load times so thanks for submitting it!

Below are the mods required to load the save file:
[Mods.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9446502/Mods.zip)

**Comment by FrankBKK** [comment]
Nice, will look forward to improvements in upcoming versions.

**Comment by MaFi-Games** [comment]
Thanks! Load durations were significantly improved in v0.4.12.
