### ISSUE TITLE
Windows 11 hangs/freeze randomically when playing Captain of Industry

### ISSUE THREAD

**Issue by venzo80** [MaFi-Games/Captain-of-Industry-issues#757]
### Issue description

Windows 11 hangs/freeze randomically when playing Captain of Industry. When it happens, sound in background continue to play but the OS is completely unresponsive, cannot exit the game, neither ctrl+alt+canc. No popup error, no warnings etc. The only thing to do in this situation is to force the shut down of the PC with the power switch button (4 sec) or with the reset button.
At the restart, no details are available in the application/system log of Windows. I suspect is something related to the version of Unity and something about Windows 11, same thing happen sometimes with anoter Unity game like "Farthest Frontier" that use the same version of this engine. 
it's not a temperature issue, it's very far from the threshold 

### Expected behavior

Not freezing the OS during gameplay

### Reproduction steps

1. Playing game
2. at a random time OS is freezing/hanging completely

### Game version

v0.4.10

### Attachments

[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9444099/Player-prev.log)
[Logs.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9444106/Logs.zip)

**Comment by MaFi-Games** [comment]
This is most likely driver or hardware issue. You can take a look into Event Viewer to get more information on why your PC has crashed: https://www.howtogeek.com/123646/htg-explains-what-the-windows-event-viewer-is-and-how-you-can-use-it/
