### ISSUE TITLE
Maintenance Problems

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#759]
### Issue description

Crusher
Cooled Caster
Cooled Castter (II)
Metal Caster
Metal Caster(II)
Boiler
Flyweel
Fuel station
Storage
 or somthing else do not consume Maintenance !

### Expected behavior

Add

### Game version

v.0.4.11

### Attachments

[spec13.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9450409/spec13.zip)

**Comment by MaFi-Games** [comment]
It's not meant that every machine has to have a maintenace. In some cases we made the choice to skip it.  We could add maintenance for crusher but we track this elsewhere.
