### ISSUE TITLE
Maintenance Problems (II)

### ISSUE THREAD

**Issue by Neek1ta** [MaFi-Games/Captain-of-Industry-issues#760]
### Issue description

Maintenance(ii)
They are being spent, but there are no consumers. Where does it go

### Expected behavior

To correct

### Game version

v.0.4.11

### Attachments

[spec14.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9450604/spec14.zip)

**Comment by MaFi-Games** [comment]
Duplicate of #778
