### ISSUE TITLE
Crash to Desktop

### ISSUE THREAD

**Issue by FlexibleGames** [MaFi-Games/Captain-of-Industry-issues#761]
### Issue description

This happens while I'm playing. Basic navigation around the map looking at various buildings.
I have a multi-monitor setup and I think that is contributing.

### Expected behavior

For it to not crash?

### Reproduction steps

While playing I sometimes accidentally click outside the game window causing the game to 'lose focus' and that is when it crashes.

### Game version

v0.4.11

### Attachments

[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9456622/Player.log)
[crash.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9456623/crash.zip)

**Comment by Voker57** [comment]
I believe setting screen mode to borderless works around this.

**Comment by FlexibleGames** [comment]
Another crash with borderless used. Crash didn't produce a crash dump as the game just locked and I had to end task. Attached is the log which hopefully helps. Though the crash itself isn't logged as the game locked hard before it could write the crash in the log file.

Also to note I use the Captain of Cheats mod to increase my max vehicles so the save has about 250 vehicles. The game seems to handle it fine. Also attached is the most recent save, maybe you can use your dev environment to track down the bug or stress test the game on your end.

[22-09-05_13-10-49_7048.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9491836/22-09-05_13-10-49_7048.log)
[MostRecentSave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9491840/MostRecentSave.zip)

**Comment by MaFi-Games** [comment]
This is crashing on 
"[Exception Breakpoint has been reached, Error 0x80000003](https://www.thewindowsclub.com/breakpoint-reached-error-0x80000003)"

This typically means somthing wrong in your os installation or drivers.

Here are some articles:
https://windowsreport.com/breakpoint-has-been-reached/
https://www.auslogics.com/en/articles/fix-breakpoint-error-0x80000003/

**Comment by MaFi-Games** [comment]
Closing as at this point there isn't much we can do.
