### ISSUE TITLE
Copper Production

### ISSUE THREAD

**Issue by GinnerProp** [MaFi-Games/Captain-of-Industry-issues#762]
### Issue description

When creating Copper with acid it says 16 will be produced but only 8 come out on the belts. You have to revert back to using water to get 13 again. Will there be a fix for this?

### Expected behavior

I expected 16 copper to be produced.
[Gods Land 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9463861/Gods.Land.2.zip)

### Reproduction steps

I have no idea i would imagine the wrong amount has been selected in the proframming.

### Game version

0.4.11

### Attachments

Not applicable unless you want my save game.
[Gods Land 2.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9463857/Gods.Land.2.zip)

**Comment by Neek1ta** [comment]
Confirm error
COPPER ELECTROLISYS Impure copper(16) + Asid(4) =Copper(16) **### but exit  Copper(14)**
COPPER ELECTROLISYS Impure copper(16) + Water(4) =Copper(13)  **### but exit  Copper(11)**

**Comment by VernonJv** [comment]
So that's why my copper is struggling...........

**Comment by zuff-coi** [comment]
I'll need a developer to chime in here but from what I understand is that this is a visual representation only. If you were to run a belt to an empty storage you would see the right amount is being produced. 

Products are "stacked" in a sense on the belt to help with performance and throughput.

**Comment by SillySMS** [comment]
I can confirm that products are often stacked 2-deep on T2 belts and at least 3-deep on T3 belts. That is also part of why you'll often see belts be only partially loaded right after upgrading them; the belts are still loaded just 1-deep (or 2-deep if upgrading T2-T3).

**Comment by MaFi-Games** [comment]
This is just a visual issue. We don't render stacked products at this point but soon we will. We already track this separately, so closing this one.
