### ISSUE TITLE
Large Tree Harvester and Overloaded Truck Edict bug.

### ISSUE THREAD

**Issue by CrazyOdd** [MaFi-Games/Captain-of-Industry-issues#763]
With T2 Overloaded Truck Edict, the truck has 78 cargo capacity and the each tree is 20 wood. 
Instead of going to storage at 60, it took a 4th tree aboard and so proofed 2 wood. 
Meaning that every 10th tree goes missing, when using this combo.

It would be worse using only T1 Overloaded Truck Edict, as that increases cargo to 69. Meaning 11 wood missing per 4th tree.

 - Game version: v0.4.11

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
