### ISSUE TITLE
Cargo depot gives free diesel when adjusting diesel sliders

### ISSUE THREAD

**Issue by kohrar** [MaFi-Games/Captain-of-Industry-issues#764]
**The issue**
Cargo depot becomes full of diesel when adjusting the 'fuel for ship' green or red sliders.

**Expected behavior**
No free diesel should be given

**To Reproduce**
1. Create a cargo depot. Fuel line does not need to be connected.
2. Adjust the fuel for ship sliders
3. Free diesel

**Additional context**
 - Game version: 0.4.11

**Attachments**
![free-diesel](https://user-images.githubusercontent.com/4450716/187999680-5acdc9c3-9e9c-48db-ae7f-61d7770f186b.gif)

Here's a gif of the bug. Note the ship has 80 diesel and the cargo depot has 0. The pipe leading to the depot is paused. After clicking on the slider, the cargo depot now has 220 diesel which drops down to 80 after the fuel is loaded to the ship. Clicking on the slider once more will fill the cargo depot again to 220 diesel.

This bug appears in a clean game as well, so it's likely not related to my save.

**Comment by Neek1ta** [comment]
I Confirm

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
