### ISSUE TITLE
A very stupid game logic

### ISSUE THREAD

**Issue by Sijko** [MaFi-Games/Captain-of-Industry-issues#765]
**The issue**
When multiple sized trucks go to unload a storage, the truck load order goes NOT by arrival order but by SIZE of the truck. So the larger trucks waste time, both PC and mine. Yay let's waste more electric power!!!   LMAO

**Expected behavior**
Developers go read a book abot the "if/while/until" conditions.

**Additional context**
 - it's 2022, babe... the fuckn future...we have spaceships u no...

**Comment by zuff-coi** [comment]
Please refrain from insults when reporting issues. There was no need for those remarks.
