### ISSUE TITLE
Trucks assigned to mining towers to dumping logic

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#766]
Low priority this one. 

Trucks which are assigned to mining towers, as of now, choose to dump their place at the nearest available dumping site.

That dumping site is based on the location of the tower, not the truck. 

See this video:

https://imgur.com/a/ooaMW2a

The highlighted truck is assigned to a mining tower, visible briefly in the bottom left halfway through the video. 

Even though the truck is directly next to a place it could dump it's load, it will drive miles away because there is another location that is "closer" to the mining tower. Ignoring the cost of actually getting there. 

To me: the solution seems simple. Make the "distance" logic of choosing a dumping location get chosen by the location of the truck, not the tower. A dumping location which is closest to the tower may not always make sense because that's not where the truck, with the cargo, actually is. 

I understand the temporary solution is just to move the mining towers accordingly. Or you can even manually assign transport routes for dumping specific material in a specific place. Which is the current stopgap I'm using. And it's made a lot easier considering the settings are (mostly) copied automagically. But it's annoying to manually have to change them all the time. It would be nice if the distance maths were done automatically rather than me having to force efficiency.

**Comment by lowstrife** [comment]
Another example is this.

![image](https://user-images.githubusercontent.com/65734844/188258389-13f4e6dd-cbae-4f57-bae2-1d0c09d1d174.png)

Please excuse the notation - it's hard to explain it all. I'm mining a shear-wall, going right to left. The circled mining tower is controlling all of those trucks.

As the mining progressed to the left, you would expect the trucks to dump to the Rock 1 dumping zone on the northwest of the picture. But no. That zone is "further" from the mining control tower, which is controlling these trucks, than the Rock 2 dumping zone. Even though the 2nd zone is actually further from where the trucks are currently mining. 

Here's the save

[New Mappy.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9481900/New.Mappy.zip)

**Comment by MaFi-Games** [comment]
Good catch! This was actually not intended. It is an outcome of mining & dumping designation search done via the same code path. Will be fixed in next patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
