### ISSUE TITLE
Clinic Bug?

### ISSUE THREAD

**Issue by VernonJv** [MaFi-Games/Captain-of-Industry-issues#767]
### Issue description

Hi

I have noticed today an issue with the clinic.
My clinic is set up as below with Medical supplies 1 at the top and 2 at the bottom.
The clinic is only giving the benefits on medical supplies 1 and not consuming medical supplies 2 at all.  
So only receiving 15 health bonus..

See screenshots below
![Clinic Setup](https://user-images.githubusercontent.com/112779559/188285633-3c6ba229-e6d0-4e6a-abe0-4aa7edf802a1.png)
![only 15 health](https://user-images.githubusercontent.com/112779559/188285736-b2a387b9-cee6-4ee4-a477-430cfdb68154.png)

If I completely remove medical supplies 1 from the building medical supplies 2 are then consumed and benefits are seen.
See below

![Clinic Setup 2](https://user-images.githubusercontent.com/112779559/188285792-345af5cb-4247-4efd-8a95-c7430d04c96e.png)
![20 health](https://user-images.githubusercontent.com/112779559/188285799-dcc4832b-8ed7-4248-98eb-af3eeb086f5a.png)

I have not tested if supplying both medical supplies in separate buildings provides the benefits of both. (yet)

Edit:  I did try 2x clinics (one supplied with medical supplies 1 and the other with Medical supplies 2)
It seems that with this configuration the game consumes both and gives an "Average" of 18 health.

![Two Clinics](https://user-images.githubusercontent.com/112779559/188286018-b0c84b2d-28e0-4a55-b08c-91ca503ca735.png)
![Average Health](https://user-images.githubusercontent.com/112779559/188286030-5b43d647-dfe5-4dc7-83b4-8993de885c54.png)

### Expected behavior

I would expect that if both are supplied the either only the highest one would be consumed or both would be consumed giving the bonus in an additive way (35 health)

### Game version

v 0.4.11

**Comment by MaFi-Games** [comment]
We have fixed this so the clinic always prioritizes consumption of better medical supplies when it has multiple to chose from. Synchronizing multiple clinics at the same time is tricky, that won't be supported at this moment.

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
