### ISSUE TITLE
Maintenance reduction is additive, not multiplicative

### ISSUE THREAD

**Issue by SillySMS** [MaFi-Games/Captain-of-Industry-issues#768]
### Issue description

Currently, maintenance reductions are additive rather than multiplicative, which makes the Statue of Maintenance and Maintenance Reducer edicts behave oddly at non-Captain difficulties. If you set the game difficulty's modifier negative (i.e. easier), the edicts are stronger than expected, whereas higher difficulty settings make the edicts weaker than expected.

### Expected behavior

Expected behavior from turning on both Maintenance Reducer edicts should be a reduction of either 25% or 23.5% from where you were prior to turning the edicts on.

However, on Sailor difficulty, what one gets is actually a 41% reduction.

I would expect a building requiring 1.0 maintenance/min at unmodified Captain to behave like one of these two scenarios

0.6 (Sailor difficulty) * 0.75 (both edicts) = 0.45
0.6 (Sailor difficulty) * 0.85 (edict I) * 0.9 (edict II) = 0.459

However, what is actually encountered in-game is this:

1 - 0.4 (Sailor difficulty) - 0.25 (both edicts) = 0.35

This isn't 25% less than your 0.6 baseline, it's 41% less. The same effect is observed with the Statue of Maintenance, albeit on a smaller scale.

On the flipside, Admiral difficulty would weaken the effect of the edicts, as you're subtracting a constant amount from a higher baseline.

### Reproduction steps

Turn on Maintenance Reducer edicts (and/or build the Statue of Maintenance) at different game difficulty settings.

### Game version

0.4.11

**Comment by MaFi-Games** [comment]
Thanks for your report! This was fixed in Update1
