### ISSUE TITLE
Number of Idle Unassigned Trucks sometimes wrong

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#769]
### Issue description

In Vehicle Management, _sometimes_ the number of idle "available to assign" trucks is (still) wrong. see attached screenshots.

Apparently the total number of idle trucks is right (I counted the idle trucks on  these occasions). So just the text output seems to use a wrong value.

### Expected behavior

Correct numbers.

### Game version

v.0.4.11

### Attachments

![Idle1](https://user-images.githubusercontent.com/109154186/188307965-1b18b3e5-ce0f-4fc0-bd2d-568574657e01.jpg)
![Idle2](https://user-images.githubusercontent.com/109154186/188307966-a9b9ae15-710c-433a-aff6-3e95493e9ed4.jpg)
![Idle3](https://user-images.githubusercontent.com/109154186/188307967-cb7d6108-9bc9-4305-89cd-4a31648109a3.jpg)
![Idle4](https://user-images.githubusercontent.com/109154186/188307968-c53eec2e-af5b-42ab-a798-cdf8c319ec11.jpg)

**Comment by MaFi-Games** [comment]
Can you please provide a save file where this is occuring?

**Comment by RealisticOptimist** [comment]
v0.4.12e: error still occurs.

While paused I had (among other things) assigned three trucks and a new excavator to a MCT. Then saved.
[save_22-11-24_19-59-58_00070607.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10087669/save_22-11-24_19-59-58_00070607.zip)

Steps:
Load.
Open Vehicles Management (then keep open). Initial values seem ok.
![0607](https://user-images.githubusercontent.com/109154186/203874860-f18e010f-92c6-49d8-8593-b27d1e621047.jpg)
Run for one day. Available to assign idle should be down to 1, still 3:
![0608](https://user-images.githubusercontent.com/109154186/203874932-eda89865-72cc-4c58-99c5-21150c2d8045.jpg)
Run again, Jun 10 idle should be 0, still shows 3:
![0610](https://user-images.githubusercontent.com/109154186/203874981-d8bda91b-564b-440f-98b4-7650eb3724e1.jpg)

Closing and reopening the Vehicles Management window does not fix the numbers.

**Comment by MaFi-Games** [comment]
Found the issue! Thanks!

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
