### ISSUE TITLE
Vehicle pathing issue in YSNP map

### ISSUE THREAD

**Issue by autocracy** [MaFi-Games/Captain-of-Industry-issues#77]
**Describe the issue**
Vehicle pathing on YSNP seems to not be able to find its way to the top coal patch. Once the trucks are too far around the top part past the ramp, they seem to give up. I think there's a point where it wraps too far around the island, tries to path the opposite side, and gives up.

I tried debugging this by building mining stations to bisect the pathing and it seemed rather close to the center of the lower island area.

**To Reproduce**
1. Load attached save 
2. Attempt to access upper coal mine

**Expected behavior**
Get to the choppa^W coal!

**Additional context**
 - Game version: Beta

**Attachments**
Pending

**Comment by MaFi-Games** [comment]
Could you please attach a save file if you have one?

**Comment by MaFi-Games** [comment]
This has been partially fixed in v0.3.2. Some vehicles may still get lost when searching for very long paths, but they should find them eventually. You can help them by building something half-way there. I will keep this open for now since it is not entirely resolved.

**Comment by autocracy** [comment]
My map from last night still exhibiting the issue:

[Beta Le Tired.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7775098/Beta.Le.Tired.zip)

**Comment by autocracy** [comment]
Fix verified for my case v0.3.2
