### ISSUE TITLE
Easy one - Text info describing Fuel distiller as making low-grade gasoline 

### ISSUE THREAD

**Issue by BoldInventions** [MaFi-Games/Captain-of-Industry-issues#772]
### Issue description

In the Basic Distiller dialog window, there is a info icon in the title bar.  If you click on this it says that the Basic Distiller makes low-grade gasoline.  

### Expected behavior

Should be Diesel, not Gasoline

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
