### ISSUE TITLE
Corrupt Save

### ISSUE THREAD

**Issue by RobBowden** [MaFi-Games/Captain-of-Industry-issues#773]
### Issue description

It's a relatively long played map came to load it today and it says the save is corrupted. 

I have attached the .save file but it is renamed to .zip
The previous autosave reloaded correctly I have attached that as a .zip as well

### Expected behavior

Save to load

### Reproduction steps

Version: Early Access 0.4.11 
load save

### Game version

0.4.11

### Attachments

[Uploading easy_22-08-02.zip…]()
[22-09-05_12-19-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9494335/22-09-05_12-19-autosave.zip)

**Comment by zuff-coi** [comment]
You're upload seemed to fail, can you try and upload the files again?

**Comment by MaFi-Games** [comment]
I have chaned the suffix of the file included from zip to save and it got loaded succesfully. There is nothing else here to investigate more so closing.
