### ISSUE TITLE
Transport supports shown as blueprints after cancelled upgrade

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#774]
### Issue description

![2022-09-06 01_34_16-Captain of Industry](https://user-images.githubusercontent.com/109154186/188595056-975dc268-f6c5-4ba3-83ea-3f9044bf7d11.jpg)

See the blueprint supports under the working pipe ... 

Just the graphics seems not ok, the pipe kept working.
After reloading the save game, graphics was fine, too.

### Expected behavior

Even with a planned/ cancelled upgrade transports should keep their supports.

### Reproduction steps

What I remember:

1. I had built the three pipes. The left one (water) is in use.
2. I requested to upgrade the left pipe. 
3. Before the actual upgrade started (lack of material), I added the connection to the mixers.
4. I cancelled the upgrade for the lower half of the pipe.

After everything was built/upgraded as intended I discovered the blueprint supports.

### Game version

v.0.4.11

**Comment by zuff-coi** [comment]
Would you mind sharing your saved game with this issue?

**Comment by RealisticOptimist** [comment]
Keep in mind, when loading the save game graphics looks fine.
[save_22-09-06_01-33-45_Pipe.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9496773/save_22-09-06_01-33-45_Pipe.zip)

**Comment by MaFi-Games** [comment]
The steps 1-4 above clearly reproduce the issue.

**Comment by MaFi-Games** [comment]
Also #510 seems related

**Comment by MaFi-Games** [comment]
Thanks for the report, this will be fixed in an upcoming patch.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
