### ISSUE TITLE
Save game location changing every other day

### ISSUE THREAD

**Issue by FelipeAlves99** [MaFi-Games/Captain-of-Industry-issues#775]
### Issue description

My game save files keep switching between **Documents\Captain of Industry\Saves** and **Steam\steamapps\common\Captain of Industry\Captain of Industry\Saves** when starting the game.

### Expected behavior

Keep the saves in the same place

### Reproduction steps

I don't know how to reproduce, because it randomly chooses one of the location every time I open the game

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
Duplicate of #896
