### ISSUE TITLE
Issues with AI emptying Port

### ISSUE THREAD

**Issue by tigertank909** [MaFi-Games/Captain-of-Industry-issues#776]
### Issue description

it seems like the AI in the game hates existing it never wants to do the most important thing first (like it should) (this mostly happens at the main port) they just refuse to empty the port unless theres a specified storage withing 2 feet of the port as of posting this i have 400 crude oil and its not being removed to save my life and theres (even tho there technically not alive)

### Expected behavior

anger, constant game restart and AI refusing on doing what there made for 

### Reproduction steps

1. play the game  (for me at least)
2. thats about it  annoyingly 

### Game version

newest 

### Attachments

Save File: 
[sdgf.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9551164/sdgf.zip)

**Comment by tigertank909** [comment]
ps some of it maybe my fault but its mostly the AI

**Comment by zuff-coi** [comment]
Please refrain from using derogatory titles and provide a save file

**Comment by tigertank909** [comment]
i would give you it but this site does not support saves ...... is there a different place i can send it

**Comment by tigertank909** [comment]
also i did not say its been doing this ever sense i bought the game on august 31

**Comment by tigertank909** [comment]
hello ?

**Comment by zuff-coi** [comment]
You need to have the save file inside a zip file or upload to another site and link it here.

**Comment by tigertank909** [comment]
discord likes it i can send it there i can send it privately or public (my name is the the same there just with a yt at the end)

**Comment by zuff-coi** [comment]
Please DM it to me on discord, Captain Zuff. You should see me at the top right of the channel

**Comment by tigertank909** [comment]
k

**Comment by zuff-coi** [comment]
Save file added to OP

**Comment by tigertank909** [comment]
k you can say that on discord nothing is stopping you

**Comment by zuff-coi** [comment]
The issue was there wasn't a fluid module connected to the port that was handling a Construction Parts 2 -> Crude Oil contract so the ship wasn't being emptied. Noted that we need to add a tutorial section covering that or alert the user that the port does not have the correct modules for the contract
