### ISSUE TITLE
Settlement Recycling Unlearned?

### ISSUE THREAD

**Issue by VernonJv** [MaFi-Games/Captain-of-Industry-issues#777]
### Issue description

Looking through the etch tree tonight I noticed that my Settlement Recycling has been forgotten.
Its available for me to research again...
I currently have the Recycling Collection attached to my settlement.

### Expected behavior

Research has been previously complete so I would expect the option to be greyed out like the other research projects.
![Captain of Industry Screenshot 2022 09 07 - 20 30 58 92](https://user-images.githubusercontent.com/112779559/188961971-5ee6e907-fa95-4066-9044-cb5b1f51c7f7.png)
![Captain of Industry Screenshot 2022 09 07 - 20 31 06 07](https://user-images.githubusercontent.com/112779559/188961987-81be0477-ea21-4d70-9e31-4bbbf23f97d7.png)

### Reproduction steps

Not sure when this happened.  
I haven't done any research for ages as i was gearing up for the final stages for a while.

### Game version

v 0.4.11

**Comment by MaFi-Games** [comment]
We had an update where we newly split that node. If you started playing before it might appear unresearched. But you will keep the unlocks.
