### ISSUE TITLE
Maintenance not beeing used anymore when overpruduced

### ISSUE THREAD

**Issue by Bluescht** [MaFi-Games/Captain-of-Industry-issues#778]
### Issue description

Since I made a new maintenance I buil there is an issue: When I acitivate enough maintenance depots maintenance doesn't get consumed anymore. The depots are idle and maintenance stays at 100%. As soon as I deactivate at least two of my four depots maintenance gets consumed and the two depts become acitve. But maintence also gets lower. Changing maintenance reducer in captain's office doesn't change anything.

### Expected behavior

Maintenance depots working according to the demand.

### Game version

v0.4.11

### Attachments

[The Challenge.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9539886/The.Challenge.zip)

**Comment by Bluescht** [comment]
Rebuilding the depots solved the problem.

**Comment by Bluescht** [comment]
Actually I had this issue again after rebuilding maintenance. As soon as I demolished the old maintenance build maintenance didn't get consumed anymore. I let the game run for a few hours. After a restart of the game everything was fine again.

**Comment by MaFi-Games** [comment]
We have been fixing this issue recently. Does it still occur?

**Comment by MaFi-Games** [comment]
Actually discovered that the fix did not entirely work, will be fixed in the next version.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
