### ISSUE TITLE
Upgrading Turbines to MkII makes them disconnect their output transports.

### ISSUE THREAD

**Issue by thetaphi** [MaFi-Games/Captain-of-Industry-issues#78]
Upgrading Turbines to MkII leads to them being unable to transport lo steam output.

**To Reproduce**
Build a MkI High Pressure Turbine, connect hi steam and lo steam in the usual way. Low Pressure Turbines, flywheels and generators don't matter.

Upgrade the MkI High Pressure Turbine. Observe it not transporting steam out.

(While finding the minimal test case, the shaft connected to a following Low Pressure Turbine disconnected as well.)

**Expected behavior**
Upgrading it should reconnect all pipes and the shaft, essentially working as a newly built turbine.

Beta 0.3.1

![image](https://user-images.githubusercontent.com/231587/147309329-492a639e-752b-433b-bce6-2082c0ab0c62.png)

The short term fix: After deconstructing the left turbine and reconstructing it, leaving the pipes alone:

![image](https://user-images.githubusercontent.com/231587/147309424-eb669ef0-e5c4-4e6e-bcc6-ab4c3cb80b22.png)

**Comment by autocracy** [comment]
Experienced the same issue, fixed only by replacing the turbine with a new build. Upgrading results in no low pressure steam through pipes.

**Comment by MaFi-Games** [comment]
This is fixed internally and will be pushed to Steam soon. Thanks for the report!

**Comment by mosbyNO** [comment]
Ah, I see you changed title to be for all turbines.. Good, I had this issue, thanks!
