### ISSUE TITLE
Research Lab II appears to consume slightly too much Lab Equipment

### ISSUE THREAD

**Issue by SillySMS** [MaFi-Games/Captain-of-Industry-issues#780]
### Issue description

Research Lab IIs appear to consume slightly more than 4 lab equipment/min, occurring in noticeable spikes in the consumption chart. In gameplay, you may not realize it unless you're running with a very small buffer, as it is on the order of 1-3 extra research parts every 10 or so in-game months.

I might not have noticed it if I hadn't started with a very small reserve and set an empty-storage alarm.

### Expected behavior

I expect Research Lab IIs to consume no more than 4 lab equipment/min; making 12 lab equipment/min should keep a trio of Research Lab IIs working indefinitely.

### Reproduction steps

Save file attached. Production seems very constant as expected, with every other month being either 8 or 16 items produced, but consumption sometimes spikes above 12/month.

If it helps, I often pause a lot to plan out a new facility.

### Game version

v0.4.11

### Attachments

[OccasionalRpartGlitch.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9542911/OccasionalRpartGlitch.zip)

**Comment by zuff-coi** [comment]
To detail:
Research I consumption spikes from 12 to 15 in a repeating pattern. 12 should be the norm as there is 3 Research Lab IIs.
![image](https://user-images.githubusercontent.com/108291414/199566181-fc79befd-4135-4c9f-a3f8-36ef01411d2a.png)
![image](https://user-images.githubusercontent.com/108291414/199566244-49ac15cd-febd-41cb-abf3-c34b6be11e4e.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
