### ISSUE TITLE
Description of loose modules mentions bauxite

### ISSUE THREAD

**Issue by burchov** [MaFi-Games/Captain-of-Industry-issues#781]
**The issue** The popup of the loose modules (S, M and L) still has bauxite in its description. 

**Expected behavior** As bauxite is not in the game, I would expect the description to not mention bauxite, but instead reference another resource, like coal or sulfur.

**To Reproduce** Look at the description of the loose modules (all sizes). See attached screenshots

**Game version** 0.4.11

![image](https://user-images.githubusercontent.com/34793744/189540376-872edc7d-34b6-4e9b-969a-c22b2f882029.png)
![image](https://user-images.githubusercontent.com/34793744/189540371-7b15e0a4-beec-4c01-8c1f-4860bc6ba499.png)
![image](https://user-images.githubusercontent.com/34793744/189540061-2015040b-335a-4137-ac0e-2e2d9f23184b.png)

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
