### ISSUE TITLE
manufacturing, The buttons for trucks "on,Off"

### ISSUE THREAD

**Issue by MarcinPL5510** [MaFi-Games/Captain-of-Industry-issues#782]
### Issue description

It meant to only affect truck as in game description, But also effects on factory working, although pipelines were connected for automation ect. It stops to work when you set Off truck input, output :(

### Expected behavior

Having enough supplies to actually work, it should have, add button to switch production off on

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
Logistics ON /  OFF buttons should only affect trucks. Can you provide specific example with a save file?

**Comment by MarcinPL5510** [comment]
[mp_save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9558698/mp_save.zip)

**Comment by MarcinPL5510** [comment]
for reference, use crude oil refinery 1st stage

**Comment by MarcinPL5510** [comment]
i think i might have miss judge of it as an issue. I mean i didn't noted that output was full and took me a moment to figure it out

**Comment by MarcinPL5510** [comment]
4.12E Game version atm so, no idea might be fix or its just me
