### ISSUE TITLE
captain of industry

### ISSUE THREAD

**Issue by KanKill** [MaFi-Games/Captain-of-Industry-issues#784]
### Issue description

the recipe for making servers and the electrolizer...
numbers incorrectly showing when set to  per 60.
servers show .. 0.4 steel + 1.5 electronics III = 1.5 servers.. (when set to show/60).
electrolizer show .. 0.8 water = 6 O2 and 1.5 H2.. (when set to show/60).

### Expected behavior

Correct the numbers if possible.

### Reproduction steps

assembly II
robotic I

electrolizer

placed any of them anywhere and switched to show /60

### Game version

early access 0.4.11

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
