### ISSUE TITLE
Incorrect navigation overlay when toggled for a first time

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#786]
### Issue description

"Toggle Navigation Overlay" in vehicle properties pressed for a first time shows overlay for a previously selected vehicle. Turning it off and then on shows the correct new overlay.

### Expected behavior

Excavator should have excavator overlay, trucks - trucks overlay. 

### Reproduction steps

1. Have a truck, an excavator and a transport that truck can go below, but excavator can't
2. Select truck, press "Toggle Navigation Overlay". _Note: overlay correctly allows to go below transport_
3. Select excavator, press "Toggle Navigation Overlay". _Note: overlay **incorrectly** allows to go below transport_
4. Toggle off then on. _Note: this time, overlay correctly disallows to go below transport_

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
Thanks for the report, this will be fixed in the next patch!

**Comment by MaFi-Games** [comment]
Thanks for reporting. We have finally found out the root cause of this issue. It will be fixed in the next patch!

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
