### ISSUE TITLE
Exacvator "can not reach destination" of digging while it can

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#788]
### Issue description

I am building a pier, that is generally inaccessible to excavators. However, by unbuilding and rebuilding pipes I managed to get excavator there. But it still states, that digging task in inaccessible!
This is most likely because digging task was created before excavator was assigned to mine and moved there.
![20220913061612_1](https://user-images.githubusercontent.com/25035071/189808670-d88bba37-fb63-43ab-b2d7-d8febe5f8c16.jpg)

### Expected behavior

The excavator should rethink spatial accessibility from time to time.

### Reproduction steps

Workaround:

1. Delete old digging task
2. Create same one in same place
3. Move excavator a little

Then it should start working.

### Game version

v0.4.11

### Attachments

[excavatorcannotstart.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9553508/excavatorcannotstart.zip)

**Comment by zuff-coi** [comment]
Good catch. The excavator needed to revist the tower for some reason but manually moving just a bit beside it fixed the issue the vehicle with the blue crosshair to the right of the orders page for the excavator: 
![image](https://user-images.githubusercontent.com/108291414/191022802-0d73198f-b92e-4b09-9c2a-c5bdff9debfa.png)

I'll see if the devs can figure out why this happened!

**Comment by MaFi-Games** [comment]
We have fixed a few issues likes this in Update 1. Unfortunately, I can't verify that for this save as these are no longer compatible. So closing as done. Please open a new ticket if this still happens in the new version.
