### ISSUE TITLE
impossible to load game

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#79]
**Describe the issue**
impossible to load my savegame of yesturday.
all saved game are now void on my folder (0 octet size)

**To Reproduce**
???

**Expected behavior**

**Additional context**
 - 0.3.1

**Attachments**
![image](https://user-images.githubusercontent.com/96617483/147345029-99c1ce8f-800b-4ec3-b3f8-685f5cbaed32.png)
[21-12-24_10-57-36_1213.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7773932/21-12-24_10-57-36_1213.log)

**Comment by fregate84** [comment]
look like a problem with steam because I have 2 PC. No problem on my primary PC.

**Comment by MaFi-Games** [comment]
It looks like your save files are empty files, 0kB. Please ensure that they are synced correctly.

**Comment by fregate84** [comment]
Impossible to reproduce... closing.
