### ISSUE TITLE
Computer Occasionally Freezes During Gameplay

### ISSUE THREAD

**Issue by gamr75** [MaFi-Games/Captain-of-Industry-issues#790]
**The issue**
Occasionally while playing, the game will suddenly freeze. It will play a very short, ~0.5 second, audio loop and remain in that state. Other applications and the OS are completely unresponsive and the only way I have found to recover is to force the computer to restart by holding the power button. The computer ignores all other input, including ctrl+alt+del. This has happened twice now in about 34 hours of game play.

**Expected behavior**
Game and computer to run normally

**To Reproduce**
Not certain, since it has only happened twice. Both times have been while time has been paused while working on factory layouts.

**Additional context**
 - Game version: 0.4.11
 - OS: Windows 10

**Attachments**
I have attached the game and Unity logs, as well as the save file. 
[22-09-13_19-43-31_6461.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9562076/22-09-13_19-43-31_6461.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9562079/Player.log)
[22-09-13_20-59-autosave-paused.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9562085/22-09-13_20-59-autosave-paused.zip)

**Comment by gamr75** [comment]
Just had another crash. Checking the window event viewer, I believe this is the error event:
The computer has rebooted from a bugcheck.  The bugcheck was: 0x0000003b (0x00000000c0000096, 0xfffff8022350913d, 0xfffff80228e87920, 0x0000000000000000). A dump was saved in: C:\WINDOWS\MEMORY.DMP. Report Id: cae95652-17b9-4b26-ae3c-071898b1bf83.

**Comment by zuff-coi** [comment]
This seems to be a Windows issue and not a COI issue. Googling 0x0000003b gives me me multiple threads of people having this similar crashes.  

0x00000000c0000096 led to a thread where [someone needed to disable Device Guard Virtualization](https://answers.microsoft.com/en-us/windows/forum/all/windows-10-system-service-exception/0dc93405-83b4-4247-89af-799cdd8fd589?page=2). 

I'm not saying that's your solution, but unless a dev can comment on this I believe this is going to be a wider problem happening with your machine/windows that isn't COI related.

Does this happen with other games?

**Comment by gamr75** [comment]
Thank you for looking into this. 
I checked, and device guard virtualization does not appear to be enabled. I do agree that this seems like a problem outside of COI, however, it has only occurred while running COI. I talked to McRib, and was given some suggestions about drivers to update. If the problem persists, I will try updating them and see if that fixes it.

**Comment by gamr75** [comment]
Issue is still present in version 0.4.12C and after updating graphics drivers

**Comment by gamr75** [comment]
I believe I found the cause of the problem. After uninstalling a Realtek audio driver, I have not experienced any more crashes. The driver was preinstalled on my computer, but uninstalling it seems to have not had any impact on my computer other than preventing the crashes.
