### ISSUE TITLE
Mouse button issue / game crash

### ISSUE THREAD

**Issue by kingsepp01** [MaFi-Games/Captain-of-Industry-issues#792]
### Issue description

First of all, middle mouse wheel (zoom in/zoom out) and also middle mouse button for rotation stops working (using keyboard for zoom keeps working). After this (maybe immediately, maybe later) saving game is no longer possible (new save-game name is created, but "Save"-Button keeps deactivated). Exit back to game causes a crash to desktop also skip saving and continue playing results in game crash.

### Expected behavior

Mouse wheel keeps normal function

### Reproduction steps

New game / continue / load game
Normal playing
Zoom in / zoom out using mouse wheel
...

### Game version

v0.4.11

### Attachments

![CoI_Savegame](https://user-images.githubusercontent.com/96915476/190468289-944a3586-2a55-4506-a7e5-d930e6820eea.jpg)
[22-09-15_19-00-14_3293.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9577501/22-09-15_19-00-14_3293.log)
[Player.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9577502/Player.log)

**Comment by zuff-coi** [comment]
Would you happen to be using Windows 11?

**Comment by kingsepp01** [comment]
Yes, I'm using Win11 (Version 22H2 Build 25201.1000). Same issue on my second machine (same O/S version) :-)

**Comment by kingsepp01** [comment]
Seems to be fixed using v0.4.12b
