### ISSUE TITLE
Update 0.4.12

### ISSUE THREAD

**Issue by TomC57** [MaFi-Games/Captain-of-Industry-issues#794]
### Issue description

Can load or start new game 

### Expected behavior

Game to load

### Reproduction steps

No

### Game version

v0.4.12

### Attachments

![image](https://user-images.githubusercontent.com/113644850/190519819-fb78ec3b-c86f-4ef0-994b-10d5b49e2888.png)

**Comment by EagleEyeLogic** [comment]
Why a new game version should be compatible with CaptainofCheats???

Deactivate the Mod and play or wait for a new version of the Mod.

**Comment by TomC57** [comment]
Thanks, I’m not sure I have a Mod running – how do I deactivate one?

 

Thanks

**Comment by TomC57** [comment]
Hi, sorry, I didn’t realise I had in installed.

 

I’ve turned off Mods and it is ok now – thanks

 

Tom

**Comment by MaciejPolanski** [comment]
@TomC57 You as an author should be able to close this issue. Button "Close issue" at comment box on the bottom of the page.

**Comment by TomC57** [comment]
Thanks
