### ISSUE TITLE
Fertility natural increase occurs on farms before construction

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#795]
### Issue description

See title. BTW, it also fills with water.

### Expected behavior

This not to happen, as it isn't built yet.

Alternatively, to start at 100%, I mean, why would the soil be at 80%?

### Reproduction steps

Place a farm in planning mode, wait. It will get up to 99.90% fertility eventually.

### Game version

0.4.11

**Comment by MaFi-Games** [comment]
I cannot reproduce, I can see here that fertility is updated only for farms that got built. Maybe we fixed that independently.
