### ISSUE TITLE
all trucks idle - logistics breakdown

### ISSUE THREAD

**Issue by Arhiphytmion** [MaFi-Games/Captain-of-Industry-issues#796]
### Issue description

all trucks idle
though enough fuel, transportmissions and maintenance available, the trucks standing around all over the map an do nothing...
even the reset doesn´t fix the problem
even newly produced trucks doesn´t begin their work

at first I didn´t mention the problem, thought it was a production problem (because I got a low maintenance warning), then I realized that all trucks stopped their work even with full tanks and high maintenance....

### Expected behavior

...?

### Reproduction steps

1. wanted to upload my save game here, but the *.save is not allowed....
2. no reproduction possible... just playing... and realizing that trucks do not work...

### Game version

v0.4.11

### Attachments

![2022-09-16 07_56_42-Captain of Industry](https://user-images.githubusercontent.com/113663165/190568913-f28798fc-821e-4d22-af17-6d14b1f62551.png)

**Comment by Honcharuk** [comment]
You can ZIP your save and then upload

**Comment by zuff-coi** [comment]
As Honcharuk said, please zip your save file and upload it so we can investigate the issue further.

**Comment by MaFi-Games** [comment]
Closing as there is unfrotunately no save file to repro this.
