### ISSUE TITLE
Maintenance doesn't drop

### ISSUE THREAD

**Issue by Kwapinero** [MaFi-Games/Captain-of-Industry-issues#798]
### Issue description

Hi! I've just rebuild my maintenance facilities and whenever I unpause them, even single one, maintenance stay at 100% and they are not working.

### Expected behavior

I've expected it to work as previously and give me this precious recyclables.

### Game version

v0.4.11

### Attachments

[2 .zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9586719/2.zip)
![1594320_screenshots_20220916212113_1](https://user-images.githubusercontent.com/113721585/190715737-79af5bb4-65f3-4e64-9ddb-790f19de2737.jpg)
![1594320_screenshots_20220916212125_1](https://user-images.githubusercontent.com/113721585/190715741-8fb73773-9eb5-49ac-8c03-fb6a4ce723d1.jpg)
![1594320_screenshots_20220916212139_1](https://user-images.githubusercontent.com/113721585/190715743-397dae2b-7861-481d-92ac-9ca918cac561.jpg)

**Comment by MaciejPolanski** [comment]
Isn't it because you have a maximum number of 23040 white maintenance?

**Comment by Kwapinero** [comment]
No, because when I pause all of maintenance depots it starts to drop, but as soon as at least one of them is functional it's instantly back to 100%, no matter how much white maintenance was left. I resolved this issue by rebuliding depots, but I think it's worth reporting.

**Comment by Deathotic** [comment]
I confirm the same issue as OP. Maintenance on my save hasn't change in over 100 years play. Pausing or unpausing doesn't change it. Multiple buildings are stuck at 100% cycle.

Save Game
[TallMountainHard.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9595224/TallMountainHard.zip)

Screenshot
![20220918144230_1](https://user-images.githubusercontent.com/113860516/190927842-dc8fb5d4-54e8-4b67-94db-7177009435ab.jpg)

**Comment by zuff-coi** [comment]
Can confirm. Loading OP's save if all maintenance is paused, the percentage island-wide goes down. As soon as you unpause one, it jumps to 100% and stays there without consume any materials and continues to stay there.

**Comment by MaFi-Games** [comment]
Fixed in v0.4.12. Thanks for your report!
