### ISSUE TITLE
When rotating or flipping farm, invalid boxes are in incorrect location

### ISSUE THREAD

**Issue by godkane1** [MaFi-Games/Captain-of-Industry-issues#799]
### Issue description

When placing a farm on parts that are not farmable, if you rotate or flip the bad boxes will be in the wrong location.

### Expected behavior

When rotating or flipping, invalid boxes are in correct location.

### Reproduction steps

1. Try to place farm on a flat piece of land that has invalid places, such as rock.
2. Flip or rotate
3. Invalid boxes will be in wrong location.

### Game version

v0.4.12a

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.12b, thanks for reporting!
