### ISSUE TITLE
Tree Harvester does nothing

### ISSUE THREAD

**Issue by c0nnex** [MaFi-Games/Captain-of-Industry-issues#8]
**Describe the issue**
Tree Harvesters sits in front of Contrcution hall saying "navigating" and burning fuel

Other Issues in this save:
all tanks full of fuel, and all of sudden it drops to 0 regulary

**To Reproduce**
1 Load attached save '...'
2. Watch Tree Harvester

**Expected behavior**
It should move to harvest location

**Additional context**
 - Game version: 0.2.4

**Attachments**
If applicable, add save files, screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`)
[21-09-23_06-47-07_1519.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7215085/21-09-23_06-47-07_1519.log)
[tree_harvester_does_nothing.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7215086/tree_harvester_does_nothing.zip)

![Screenshot_41](https://user-images.githubusercontent.com/8324035/134457406-97ac7e9b-5192-407d-ba80-36a8aeb3c988.png)

**Comment by c0nnex** [comment]
Seems to be a pathing problem (maybe a spacing issue)
Removed harverster and station, rebuild it up on the top near harvest aera and harvester started to work immediately.

**Comment by c0nnex** [comment]
And harvestester stuck again
![tree_harvester_stuck_again](https://user-images.githubusercontent.com/8324035/134628804-00353d85-f352-47bd-8c8e-60dfcd80d194.png)
[21-09-24_06-09-42_9190.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7223323/21-09-24_06-09-42_9190.log)
[tree_harvester_stuck_again.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7223337/tree_harvester_stuck_again.zip)

**Comment by MaFi-Games** [comment]
Thanks for the report, there are some cases in which the tree harvester will attempt to go to the closest trees which are not even reachable and will have troubles finding "valid" trees to harvest. We will be looking to improve this. Your saves were very helpful in understanding this situation.

**Comment by c0nnex** [comment]
I debugged that a bit. It's 100% Reproducible in my saves (tested with 2.0.5 as well):

- Harvest all tress on lower start ground. 
- Create ramps to 1st and 2nd high ground which are accessible by trucks.
- Create a depot on low ground
- create harvester. It will do nothing
- destroy harvster, destroy depot
- create deport on 1st high ground
- create harvester
- it will start harvesting for a while (roughly 20-30 mins). then suddenly stop (even if there are trees right next to him) and move back to the PORT and loop in navigating there. (It should not move to the Port ?!)

Same game with 2nd high ground. It will behave exactly the same.
Giving "Priority Tree harvesting zone" does not influence this in any form.

Not a real bug, but eats a lot of time potentially without wood. 
Detroy Harvester (get coffee while it moves from port to depot), destroy depot , create deport , create harvester (wait until it decides to go on strike and hope you recognize it, repeat)

**Comment by MaFi-Games** [comment]
This has been fixed in upcoming beta patch, thanks for reporting!
