### ISSUE TITLE
Radar system found but not the research is unlocked?

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#80]
This is from a User from the Discord that encounter the issue that he found the radar system but still cant research the radar system.
[Timo_Herausforderung_19.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7774657/Timo_Herausforderung_19.zip)

**Comment by arvidvillen** [comment]
I have the same problem.
Is there a workaround (e.g. a cheat code)?

**Comment by McRib33** [comment]
The issue is solved. You can get the radar system if you keep exploring the map more. The Radar MK II is to near the start area and the MK I is far out inside infested Piratspace. The Dev fix it with a patch some days ago so it will now spawn near the start point and the MK II will spawn far away.

**Comment by arvidvillen** [comment]
OK, thanks.

**Comment by MaFi-Games** [comment]
This was likely caused by radar "hidden" behind the initial village, this was fixed. If not, please report it again.
