### ISSUE TITLE
OXYGEN FURNACE 2

### ISSUE THREAD

**Issue by louie2cool** [MaFi-Games/Captain-of-Industry-issues#800]
It seems like the oxygen furnace two is running slower than it should.

**Comment by louie2cool** [comment]
It's avg 20 seconds slower at producing!

**Comment by zuff-coi** [comment]
It takes 40 seconds for one cycle and I've just confirmed this:
![image](https://user-images.githubusercontent.com/108291414/191288718-9a8cfefb-d4e1-4619-bcd5-c73a4330aaf2.png)

Are you sure you're looking at the right thing? Do you have the "Show/60" unchecked?
