### ISSUE TITLE
Paused symbol not shown after building update

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#801]
### Issue description

![2022-09-17 17_08_02-Pause](https://user-images.githubusercontent.com/109154186/190863833-17ba1e67-ddeb-4672-84d3-b13c930dc56a.jpg)

I updated a paused basic maint. depot to a maint. depot. It is still paused, but the orange paused symbol is not shown anymore.

Unpause/pause works around to show it again.

### Expected behavior

Paused symbol should be properly shown after update.

### Game version

v0.4.12a

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.12b, thanks for reporting!
