### ISSUE TITLE
The chicken farm hitbox is different from the placement box, so you have difficulty selecting something next to it

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#802]
### Issue description

Trying to select a pipe next to it fails, and selects the CF instead, probably due to the non-square shape. You can see where I mean in the screenshot

### Expected behavior

Selecting the pipe

### Reproduction steps

Place a CF, place a pipe at the water input so it isn't auto-selected, place a pipe in the indentation, try to select the pipe, fail

### Game version

0.4.12

### Attachments

![image](https://user-images.githubusercontent.com/8517039/190871147-0d2c2be0-2225-4b17-8170-e57ff2a3069d.png)

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.12e, thanks for reporting.
