### ISSUE TITLE
Unity quickbuild uses materials from contract dock modules before storage buildings

### ISSUE THREAD

**Issue by Rattja** [MaFi-Games/Captain-of-Industry-issues#803]
### Issue description

When quickbuilding with unity, materials are taken from docks assigned to contracts before normal storage if the needed material is present. This means that you can risk using all the materials intended for trade without even realizing.

### Expected behavior

Expected behavior would be it using materials from normal storage first, and maybe not even let you use from exporting dock modules at all, or at least have an option to disallow it the way you can do with trucks.

### Reproduction steps

Set up a trade that uses a certain material, I used solar panels.
Fill up the dock module for exporting with that material.
Build and fill a storage with the same material used for export.
Build anything that needs that material with unity quickbuild.

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
