### ISSUE TITLE
Chicken Trade not working

### ISSUE THREAD

**Issue by ComBenn** [MaFi-Games/Captain-of-Industry-issues#804]
### Issue description

 If I try to buy chicken in the settlement it says "Animals were delivered to your farm!" but the chicken counter is still 0 and my chicken farms are still empty. The Farms have food, worker and water.

I relocated all of my chicken production earlier and accidentaly slaughtered all the chickens I had on my island. Therefore I now need to buy new chicken. The first I buyed chicken (hours ago) the trade was succesfull. Now the chickens do not land in my farms.

### Expected behavior

To receive chickens from trading with settlement in my farms.

### Reproduction steps

The chicken trading with the settlement is not working in my savegame. All other trades even with the same settlement are succesfull and arrive on my island.

The chickens not.

### Game version

v0.4.11

### Attachments

[save_22-09-17_21-36-24.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9592608/save_22-09-17_21-36-24.zip)

**Comment by ComBenn** [comment]
Nevermind I found the mistake. My old farms were still there but with the order to slaughter all chickens inside. So every newly bought chicken got instantly slaughtered,

I now destroyed the old farms and the trade and delivery is working. The chicken counter in the trading window is still 0 though.

**Comment by MaciejPolanski** [comment]
@ComBenn  You as an author should be able to close this issue with "Close issue" button at the bottom.
