### ISSUE TITLE
Skip the task if possible

### ISSUE THREAD

**Issue by Honcharuk** [MaFi-Games/Captain-of-Industry-issues#805]
### Issue description

When the vehicle does not have access to the building, it stops and does not perform other tasks.

### Expected behavior

When the transport does not have access to the building, it must complete other tasks and return to what it could not complete. It would also be nice if the building warned if a certain mode of transport did not have access to it.

### Game version

0.4.11

### Attachments

[Uploading q1.zip…]()
![1](https://user-images.githubusercontent.com/15582553/190880354-ec45aece-536d-407e-b3fd-a348ee1d05d6.jpg)
![2](https://user-images.githubusercontent.com/15582553/190880359-7b6cefd9-2dcf-4295-8b8b-98d1eef42690.jpg)

**Comment by MaFi-Games** [comment]
Works as inteded. You want to be aware of any storage that is no longer accessible. Handling this silently could lead to supply issues and also would require more perf and tracking on our side. Feature here would be to treat haul trucks differently but we track this task elsewhere.
