### ISSUE TITLE
Toggling the direction of water flow leads to destruction of pipe last segment

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#807]
### Issue description

Toggling the direction of water flow in an apparently properly supported pipe leads to destruction of its last segment (dust, smoke and waste left on ground).
![20220919143553_1](https://user-images.githubusercontent.com/25035071/191022144-b4c776ea-6006-4618-9165-7928c3ff880b.jpg)
![20220919143453_1](https://user-images.githubusercontent.com/25035071/191022170-eddc14bb-c5ea-4609-b717-26d0ccd250b5.jpg)

### Expected behavior

Toggling liquid flow should not affect mechanical integrity of pipes.

### Reproduction steps

1. Load attached save
2. Select the center-left section of pipe, where the water flows to the right
3. Toggle direction, so the water flows to the left, 
5. The rightmost pipe segment of this section should be destroyed

### Game version

v0.4.11

### Attachments

[pipe_toggle_catastrophe.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9598995/pipe_toggle_catastrophe.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting, this was fixed and will be available in an upcoming patch v0.4.13.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
