### ISSUE TITLE
Service buildings able to be built on ghost settlements

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#809]
### Issue description

![image](https://user-images.githubusercontent.com/108291414/191060143-7a9b7e69-c404-49df-86cd-b9c6167a269f.png)

### Expected behavior

Not allow to be built

### Game version

v0.4.12

**Comment by MaFi-Games** [comment]
Hmm, and why not? I don't see anything wrong with this.
