### ISSUE TITLE
Nuclear Accident Incoming

### ISSUE THREAD

**Issue by VernonJv** [MaFi-Games/Captain-of-Industry-issues#810]
### Issue description

Hi
Zuff posted something similar so happy to delete if its the same issue.

Building my 8th Nuclear waste storage.  
When un-pausing the belt to start the transfer (Or transferring by truck) to the final storage the radiation levels jump up and people start to die.
I have done the same strategy with the waste each time the first one is full and never had this issue before.

![Captain of Industry Screenshot 2022 09 19 - 20 09 10 46](https://user-images.githubusercontent.com/112779559/191098560-c0566b15-c8d1-4b7d-8566-c19baafebff8.png)
![Captain of Industry Screenshot 2022 09 19 - 20 27 52 61](https://user-images.githubusercontent.com/112779559/191099930-49ce7740-6d1c-4c1b-828a-492a935e4abb.png)

I have tried demolishing the building and rebuilding with new.
I have tried transferring via truck rather than belt

Save file attached.

### Expected behavior

No radiation release.

### Reproduction steps

Not sure.
I did have the other full storages paused for a period so save workers.  all unpaused at the time of building new storage.

### Game version

v 0.4.12a (Experimental)

### Attachments

[Nuclear Hazard 2 - Copy.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9601837/Nuclear.Hazard.2.-.Copy.zip)

**Comment by zuff-coi** [comment]
Definitely the same thing happening in #783

**Comment by VernonJv** [comment]
Cool.  I will remove this one.
