### ISSUE TITLE
Excavator loses inventory when paused

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#811]
### Issue description

See title

### Expected behavior

Not to lose the inventory

### Reproduction steps

Have an excavator mine something, pause it, see the inventory become nothing.

Presumably this behavior is shared among all 3 types.

### Game version

0.4.12

**Comment by Prometheus0000** [comment]
BTW, it also loses the inventory when being unassigned or told to move.

**Comment by MaFi-Games** [comment]
This is working as intended. Having to handle inventory of an excavator while it is not digging would get a bit messy and the excavator logic is already fairly complex.
