### ISSUE TITLE
Visual glitch when deconstructing cooling tower

### ISSUE THREAD

**Issue by zuff-coi** [MaFi-Games/Captain-of-Industry-issues#812]
### Issue description

![image](https://user-images.githubusercontent.com/108291414/191285464-b465f17e-f4e2-4509-bb31-4f56d5bfdde5.png)

### Expected behavior

Only the building should have visual filter applied, not the particle effects.

### Game version

v0.4.12

**Comment by MaFi-Games** [comment]
Cannot reproduce

**Comment by MaFi-Games** [comment]
Closing as we can't reproduce and this was happening on the older version.
