### ISSUE TITLE
Farm using fallowing is punished for lack of crops rotation

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#814]
### Issue description

It seems that planting potatoes alternately with fallowing land doesn't count as rotation of crops. Thus farm is penalized with 50% faster fertility loss.
![20220920184034_1](https://user-images.githubusercontent.com/25035071/191319561-97547a32-28e9-4242-848e-8aa9a4d5a5fc.jpg)
![20220920184040_1](https://user-images.githubusercontent.com/25035071/191320801-133cbf2f-5415-44fa-a47f-b412170ea02b.jpg)

### Expected behavior

Leaving land fallow is traditional technique of rotating crops, so no penalty.

### Reproduction steps

1. Build a farm, set slots to potatoes and "no crops"
2. Wait ~7 months to second cycle
3. Note: Fertility loss has bold font and is raised about 50%

### Game version

v0.4.11

**Comment by MaFi-Games** [comment]
This actually works as intended. Crops rotation only works when you actually rotate different crops. Empty field does not count as a different crop.

**Comment by MaciejPolanski** [comment]
Oh. I thought it was kind of water-saving manure.
