### ISSUE TITLE
An unbuilt storage counts in the total storage monitor on the right side

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#815]
### Issue description

See title

### Expected behavior

Not to count until built

### Reproduction steps

Pin item, place storage set to item, see monitor bar go down.

### Game version

0.4.12

### Attachments

![image](https://user-images.githubusercontent.com/8517039/191361537-45d22735-e409-4f01-8a5e-e9b7e99399ec.png)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
