### ISSUE TITLE
Failed to Initialize

### ISSUE THREAD

**Issue by DeathGoat** [MaFi-Games/Captain-of-Industry-issues#816]
### Issue description

couldn´t start any of my saved games

### Expected behavior

That the game starts

### Game version

0.4.12c

### Attachments

![unknown_2022 09 21-07 55](https://user-images.githubusercontent.com/114050316/191425554-d086b314-0189-4b7d-9e02-1129a5be8e7a.png)

**Comment by asiart** [comment]
Hi, I already solved the issue I think. The problem was the mod that you enable in the settings. You need to download the new mod and paste it. Work for me.

Here the link https://github.com/altmank/CaptainOfCheats/releases/tag/v.1.8.3

Credit to altmank/CaptainOfCheats

Sorry if my English is bad.
