### ISSUE TITLE
Planning mode pause icon missing

### ISSUE THREAD

**Issue by kent974** [MaFi-Games/Captain-of-Industry-issues#817]
![Planning mode ON Pause icon missing](https://user-images.githubusercontent.com/114054687/191484876-1722681e-f546-4449-93cf-d16e84dac43c.PNG)
### Issue description

Hello,
The planning mode does not show the pause icon anymore since the installation of the last patch version 0.4.12c.
Cheers

### Expected behavior

Before the recent patch the icon was visible.

### Game version

v0.4.12c

**Comment by MaFi-Games** [comment]
This was changed deliberately. We have introduced ghosts coloring so we can get rid off the pause icon as previously it was cluttering the view. We have tested and selected colors that should be distinguishable by color blind people. In the future we are also planning on providing an option to override these colors in settings.
