### ISSUE TITLE
Research-screen doesn't use available space to display unlocked tech, shows scroll bars instead

### ISSUE THREAD

**Issue by Creat** [MaFi-Games/Captain-of-Industry-issues#82]
**Describe the issue**
Since v0.3.2 the display of unlocks provided by a selected technology on the research screen has to be scrolled despite having plenty of room to display everything at once. See screenshot.

**To Reproduce**
1. Open Research screen
2. Pick any technology that unlocks enough "stuff" so that it doesn't fit ("Advanced Diesel" is a good one, my screenshot used "Biofuel")
3. see only a small part of the display area is taken up.

**Expected behavior**
I can see everything unlocked by the tech at once, cause there is enough room.

**Additional context**
 - Game version: v0.3.2

**Attachments**
Screenshot (see the section on the right):
![image](https://user-images.githubusercontent.com/1364132/147390963-d4301df6-df87-427a-a6da-8b362c8eb324.png)

**Comment by MaFi-Games** [comment]
This is some UI bug that happens from time to time. You should be able to get rid of it by reloading the game. Does that help? How often does it happen?

**Comment by Creat** [comment]
When I originally posted the issue, i had it permanently. Since then I've seen it a lot less, but still basically every play session.

I don't have to reload my save or restart the game, it's enough to click on a different node in the research screen, and close/reopen that screen (esc followed by g). That usually fixes it, if not repeating it once will.

Unfortunately, I haven't noticed

**Comment by dylan-brasseur** [comment]
I can reproduce it consistently by switching in a loop from "Computing" to "Ship armor II" to "Uranium Enrichment", Uranium enrishment will have the UI bug

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates.
