### ISSUE TITLE
Research lab IV using Lab equipmenbt III for research belonging to Research lab III

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#821]
### Issue description

After research Research lab IV has been researched and research lab upgraded to Research lab IV it consumes Lab equipment III (red lab equipment) even for older research, that belongs to Research lab III so should use Lab equipment II (yellow equipment). 

This makes upgrading research lab pointless as player need to keep older ones, or enforces the only right order of research where whole older tier is completed before starting next one.

![20220922163929_1](https://user-images.githubusercontent.com/25035071/191783203-b69af641-7672-4d92-a766-87328b0c6f80.jpg)

_Let me also point out misnomer that Lab II uses Equipment I, Lab III Equipment II and so on. This makes game difficult to master for new players._

### Expected behavior

The type of Lab equipment used should depend on the research being conducted, not the type of Research lab being used.

### Game version

v0.4.12c

**Comment by MaFi-Games** [comment]
This works as intended. Lab tier is tight to the equipment tier even for older research. The motivaton for an upgrade can be that the research is faster.

**Comment by MaciejPolanski** [comment]
@MaFi-Games Well, so be it. And are you going to rename lab equipment so Lab II uses Equipment II and so on?
