### ISSUE TITLE
Retaining wall research seems to be in the wrong place

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#825]
### Issue description

All the other items past a research building need that research building, the RWs do not. It should be moved back. Alternatively, add the T2 RL as a prerequisite.

### Expected behavior

It to be logically placed.

### Game version

0.4.12

### Attachments

![Screenshot 2022-09-22 164441](https://user-images.githubusercontent.com/8517039/191847660-3ae5e6ce-75c9-429a-a1e9-9057a69f2f43.png)

**Comment by RealisticOptimist** [comment]
Efficient Concrete and Retaining walls should be moved one slot to the left then, too.

There is many more cases where research is not shown as far to the left as possible. In total this results in a far longer to scroll research map than necessary. But then the whole research map should be updated.

**Comment by MaFi-Games** [comment]
We do not strictly enforce that position of node has to strictly imply reserach level required. Sometimes for space reasons or for clarity (don't try to work on this tech too early, you might not need it).
