### ISSUE TITLE
COI won't start

### ISSUE THREAD

**Issue by Eagletrain** [MaFi-Games/Captain-of-Industry-issues#826]
### Issue description

COI won't start

### Expected behavior

That it works

### Game version

v 0.4.12C

### Attachments

![Schermafbeelding 2022-09-23 111442](https://user-images.githubusercontent.com/114223340/191929229-13d38c0e-7ebe-426f-8ab5-32837b779451.png)

**Comment by zuff-coi** [comment]
Your save has an outdated mod, "CaptainOfCheats" and you'll need to update that mod in order for it to work.
