### ISSUE TITLE
Rubber Trade not being deducted.

### ISSUE THREAD

**Issue by Almerra** [MaFi-Games/Captain-of-Industry-issues#83]
**Describe the issue**
Can trade Rubber at a settlement and it not be deducted from the trade - essentially getting free items. Only tried with a few, only noticed rubber causing the issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load attached save 'Merra'
2. Trade with Northern Settlement
3. Trade Rubber for Wood 

**Expected behaviour**
Rubber should be used from the trade but its not

**Additional context**
 - Game version: Beta 0.3.3

**Attachments**
[Merra.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7780992/Merra.zip)

**Comment by Almerra** [comment]
Just to note, this only seemed to happen when it was taking the full rubber from the trading dock. if all the rubber is in normal storage then its deducted as normal.

**Comment by MaFi-Games** [comment]
This was fixed in v0.3.6, thanks for reporting!
