### ISSUE TITLE
Truck out of fuel can still be moved with manual order

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#830]
### Issue description

See title. Honestly, this might be on purpose, I dunno.

### Expected behavior

Not to be able to move.

### Reproduction steps

Wait until a truck is out of fuel, order it to move.

### Game version

0.4.12

**Comment by MaFi-Games** [comment]
Yep, this is working as intended. One example could be a stuck excavator that can't be reached by a refulling truck.
