### ISSUE TITLE
Issue upgrading Cargo Depot

### ISSUE THREAD

**Issue by xxaugustasxx** [MaFi-Games/Captain-of-Industry-issues#831]
### Issue description

![image](https://user-images.githubusercontent.com/114313631/192117746-007d4d57-ddac-49d7-9cfd-66ad3744286a.png)

Have higher level of tech unlocked for Cargo Depot. I have in the past upgraded this without needing to demolish and rebuild.

Is this a feature or a bug?

### Expected behavior

I expected it to just upgrade, instead I seem to need to demolish and rebuild.

### Reproduction steps

![image](https://user-images.githubusercontent.com/114313631/192117815-5fbf1156-bca1-4bde-88a4-84a04bfe9eee.png)

To repeat, try and upgrade from Cargo Depot (4) to Cargo Depot (6).

### Game version

v0.4.12

### Attachments

![image](https://user-images.githubusercontent.com/114313631/192117881-af1e32a7-b895-44ed-a556-bf3ae9ec7a5c.png)

**Comment by godkane1** [comment]
2 upgrades to 4.  and 6 upgrades to 8.  There i no upgrade option from 4 to 6.  Because of the size, I understand why they did this, even though it seems odd if the space is valid to do.

**Comment by zuff-coi** [comment]
As godkane1 said, this is working as intended.
