### ISSUE TITLE
The tree harvester "green line" doesn't update while moving like trucks and excavators do

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#832]
### Issue description

See title and picture.

### Expected behavior

Update like trucks do.

### Reproduction steps

Order a tree harvester to go somewhere, see the start point of the green line stay in place. It's not just manual orders BTW.

### Game version

0.4.12

### Attachments

![image](https://user-images.githubusercontent.com/8517039/192119013-c2179833-1beb-46c7-acba-ccc9ca5dc882.png)

**Comment by MaFi-Games** [comment]
This was fixed in v0.4.12e, thanks for reporting.
