### ISSUE TITLE
Infinite Maintenance

### ISSUE THREAD

**Issue by jhauge-hsb** [MaFi-Games/Captain-of-Industry-issues#833]
### Issue description

My Maintenance 1 is infinite. The Maintenance Depot is paused, while the Basic Version is unable to output Maintenance due to an overflow. This has apperently been the case for the last ~300 years.

### Expected behavior

When I refitted the Maintenance, I expected the value to slowly drop and then phase in the automated versions. This did not happen.

### Reproduction steps

I do not know how exactly to reproduce the issue. What I did was to build 2 Basic Depots and one Automated Depot, destroy 1 Basic and pause the automated one while denying truckimports on the remaining Basic Depot.

### Game version

Earky Access 0.4.12c

### Attachments

[NewStart10.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9640852/NewStart10.zip)
![CoI_bugreport2](https://user-images.githubusercontent.com/59656411/192146255-5d736b9c-3fac-422f-900c-6ac928b57c55.png)
![CoI_bugreport3](https://user-images.githubusercontent.com/59656411/192146256-d13aba9e-cf20-4370-9177-7259e3ee105b.png)
![CoI_bugreport1](https://user-images.githubusercontent.com/59656411/192146259-a9ec4d36-84b1-4517-8eef-b271971dc465.png)

**Comment by MaFi-Games** [comment]
Hi, thanks for your report. We had an issue in maintenance production buffer which we fixed in 0.4.12c, if you reaload your game, the fix should propagate and you should no longer see infinite maintenance. Please let us know if not or if the issue happens again.

**Comment by jhauge-hsb** [comment]
It did indeed resolve itself just now, but a reload was not needed. Thanks for the fast reply.
