### ISSUE TITLE
Random excavator assigned to mine

### ISSUE THREAD

**Issue by MaciejPolanski** [MaFi-Games/Captain-of-Industry-issues#837]
### Issue description

I wanted to move an excavator from the mine on the left to the mine on the right. However, the game chose the excavator located far away, leaving the nearest one unallocated. 
This is very inconvenient, especially for small cleanups, when the waiting time for the excavator going around all the transports is much greater than the job itself.

![20220926211738_1](https://user-images.githubusercontent.com/25035071/192363587-640cc4b5-e43b-4e0c-9ea7-233e19d54460.jpg)

### Expected behavior

Given the choice, the game should assign the excavator closest to the mine.

### Game version

v0.4.12e

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
