### ISSUE TITLE
text "missing entry" is wrong

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#84]
**Describe the issue**
Hello, 
when 2 receipts are active, and output are full, the message on the GUI are wrong. Message said "missing input" but the good message should be "output are full".
![Screen Shot 12-27-21 at 02 22 PM](https://user-images.githubusercontent.com/96617483/147491424-1c51bf20-dae5-41e0-b730-8c9bafc68308.PNG)

**To Reproduce**
- activate 2 receipts.
- have output full
- look at the message on GUI.

**Expected behavior**
good message should be "output full".

**Additional context**
 - 0.3.2

**Comment by MaFi-Games** [comment]
This was fixed in v0.3.6, thanks for reporting!
