### ISSUE TITLE
Pipes clip through Arc Furnaces

### ISSUE THREAD

**Issue by lowstrife** [MaFi-Games/Captain-of-Industry-issues#843]
![image](https://user-images.githubusercontent.com/65734844/192629904-96bfd50a-5097-415b-ac64-2ed699984a38.png)

![image](https://user-images.githubusercontent.com/65734844/192629925-c2c58a83-7a24-4d50-aa86-97e3d8bde259.png)

https://user-images.githubusercontent.com/65734844/192630104-18c99eaf-aae3-4798-b103-b00ee66c1091.mp4

Searched and couldn't find previous reports. Cheers!

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
