### ISSUE TITLE
Building outputs 1 item even though output transport is paused

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#845]
### Issue description

See title. I've confirmed that the blast furnace outputs 1 unit of molten iron into the molten channel even though the channel is paused. This is mostly annoying when you want to shutter an old facility. I don't know if it affects other buildings, or other types of transports.

### Expected behavior

Not to output, since the output is paused.

### Reproduction steps

Build a BF, have output(s), pause them, and run the facility once.

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/192647626-a3845421-fe49-4cc4-9e61-48c4eb4b34e0.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
