### ISSUE TITLE
Large Tree Harvester(LTH) Dialog box doesn't open when produced without harvestable trees

### ISSUE THREAD

**Issue by nshoebox** [MaFi-Games/Captain-of-Industry-issues#848]
### Issue description

Produced a LTH after harvesting all my lower level trees. When I go to click on it to issue a command, to move, the dialog box of the units controls does not open up like the other vehicles.

### Expected behavior

I expect to be able to issues commands for my LTH, even though there are no trees available. 

### Reproduction steps

Have not tested this bug enough.

### Game version

v0.4.12e

### Attachments

![COI_bug_SC1](https://user-images.githubusercontent.com/114619646/192885775-a9cfe9cf-d94f-45f6-ba99-673d30b02bfc.png)

![COI_bug_SC2](https://user-images.githubusercontent.com/114619646/192885836-1fe20d01-f86f-4767-835e-6f18e7027f28.png)

![COI_bug_SC3](https://user-images.githubusercontent.com/114619646/192885870-ead00e06-9ac5-447e-85aa-0380176c6b66.png)

**Comment by nshoebox** [comment]
even after it gain access to trees, it's dialog box still did not open up so I could assign trucks to it. 

![COI_bug_SC4](https://user-images.githubusercontent.com/114619646/192905928-8a6dbe80-44f4-47c5-ab15-97fef4b41c6e.png)

**Comment by zuff-coi** [comment]
Could you provide a save file and share your resolution and UI scale?

**Comment by nshoebox** [comment]
Res 2560 x 1440
UI Scale 120%

![image](https://user-images.githubusercontent.com/114619646/193089520-96c56261-92bd-492f-bb87-d9abd0c54b16.png)


[Bug Issue saved.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9677082/Bug.Issue.saved.zip)

**Comment by nshoebox** [comment]
After reloading back into the game the dialog box did generate for the LRH.

**Comment by u01pei** [comment]
Just had the same issue as above. Version v0.4.12e. Game was not running for days, but say 6 hours. reloaded the safe game wich fixed the issue.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
