### ISSUE TITLE
Unity quick repair can be free at super low needed levels

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#849]
### Issue description

It seems that at certain minimal levels it will be less then 0.1 unity to repair something. I'm not sure if it's actually like 0.09 and just not shown, and I doubt anyone would bother to abuse this even if it was maint 3, but still.

### Expected behavior

Should either not allow repairing, be minimum 0.1, or show more decimal places.

### Reproduction steps

Let something need 1 point of maint, look at interface.

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/193158421-60158737-26c5-415b-9be2-99dabdc68416.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
