### ISSUE TITLE
10% of fertility or 20 % ?

### ISSUE THREAD

**Issue by fregate84** [MaFi-Games/Captain-of-Industry-issues#85]
**Describe the issue**
I found a little GUI problem on farm.
On receipts we see that potatos take 10% fertility on the GUI whi add a culture to a farm. But when the receipts is plant, the receipts have a wrong display (we see 20% for fertility) :

![Screen Shot 12-27-21 at 03 13 PM 001](https://user-images.githubusercontent.com/96617483/147492488-a1ac8acc-e7c4-400e-8bef-ce70341693df.PNG)
![Screen Shot 12-27-21 at 03 13 PM](https://user-images.githubusercontent.com/96617483/147492487-1fdd5a11-c2ca-4cba-935b-26c86fe9b52b.PNG)

**Expected behavior**
having the same receipts on all GUI

**Additional context**
 - 0.3.2

**Comment by MaFi-Games** [comment]
You probably planted two potatoes in row. There is fertility penalty for growing two of the same crops right after each other. This is explained in tool-tips but we could probably show 10%+10% instead of 20%

**Comment by fregate84** [comment]
It's the case. I had planted patatoes only. 
I didn't know that penalty.
So not a bug... just a suggestion to have a GUI more explicit :-)

**Comment by MaFi-Games** [comment]
This has been fixed in EA :) Thanks for your report.
