### ISSUE TITLE
The seawater in the evaporation pond is very much not flat

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#850]
### Issue description

See title and picture. Probably also affects the unheated one.

PS: you can also see it outside of photo mode, it's just less obvious.

### Expected behavior

Be flat, or maybe have slight ripples/waves.

### Reproduction steps

Turn it on and look at it while working.

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/193162668-5986fea6-4db9-4008-8c8b-2932d7416849.png)

**Comment by MaFi-Games** [comment]
Thanks but not something worth tracking. We will be revisting this model anyway.
