### ISSUE TITLE
The seawater to brine recipes for the evaporation pools don't show up on the research screen

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#854]
### Issue description

See title.

### Expected behavior

It to show up

### Reproduction steps

Look at research tab

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/193397732-6e14d701-ab34-44c3-8c24-00772064aa5a.png)
![image](https://user-images.githubusercontent.com/8517039/193397779-48bea3e7-7f94-4009-baa5-9099adb54116.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
