### ISSUE TITLE
Parts not delivered

### ISSUE THREAD

**Issue by Blottoo123** [MaFi-Games/Captain-of-Industry-issues#86]
Hey there, at first i thought i have found a problem with pathfinding. I build some buildings and pipes and my trucks wont deliver the materials to all planed buildings. It seems like they cant reach some of them.
Then i tried to build my setup step by step, so every building was directly reachable for the truck´s. That worked more or less good.
During that attempt i tried to place a flat belt between my farms and biogas plant. (0 Space between Farm - Belt - Plant) Now the trucks start to deliver to the belts, but only the rubber. They are stuck with the construction material II. 5 Trucks with 10 caonstr. mats. II say that they cant reach the belts, but before other trucks delivered the rubber.
I attached a photo and a savegame. I hope that will work, first time using github. Oo

![21-12-27_20-49-27_6316_photo](https://user-images.githubusercontent.com/96746820/147503299-80961733-d56a-46fd-a183-c1a2aae832b9.png)
[Blottoo 12-26- Pathfinding no building mats_ just rubber.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7781695/Blottoo.12-26-.Pathfinding.no.building.mats_.just.rubber.zip)

**Comment by Blottoo123** [comment]
Same problem again, now from other side.
![21-12-27_22-52-20_1323_photo](https://user-images.githubusercontent.com/96746820/147509579-a76fd31e-030b-4cbb-9ba0-70230eedeca6.png)

**Comment by MaFi-Games** [comment]
Thank you so much for reporting this and attaching your save file, we were able to identify the issue and fix it! The pathfinder was basically giving-up too early, since goal was unreachable.

Fix will land in the next patch.

If you ever encounter this again, please create another report.
