### ISSUE TITLE
The statistics screen for waste says I'm dumping it, but I'm burning it

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#863]
### Issue description

See title and picture.
Oh, it says 0 consumption too.

### Expected behavior

To show amount burned instead. I'm not sure if it's just a name thing or if they're combined.

### Reproduction steps

Burn waste, look at statistics screen.

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/194726610-cd263d0d-ab48-4129-80f1-a3bc57c90ae6.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
