### ISSUE TITLE
Server racks deleted somehow

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#864]
### Issue description

I'm not sure how I managed to do it, but I somehow lost about 4 racks' worth of servers while playing around with the data center in planning mode.

I have 60 in the "Bug" file, and 148 in the "nobug" one, but I didn't do anything to get rid of them besides playing with the building.

### Expected behavior

Not to have servers evaporate.

### Reproduction steps

I wish I knew, but I was copying, cutting, and moving the building around while increasing and decreasing the amount of servers. I didn't connect anything other than maybe another data center.

### Game version

0.4.12e

### Attachments

[Save files.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9740557/Save.files.zip)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
