### ISSUE TITLE
Server racks are not colored white or blue when building is not built

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#865]
### Issue description

See title and picture.

### Expected behavior

Them to be white/blue.

### Reproduction steps

Place building, add racks.

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/8517039/194733361-ea8158cb-ff24-4904-82ec-00a3532999ad.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
