### ISSUE TITLE
Server racks are sent back to the dock, not the storage they were in

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#866]
### Issue description

After playing with the data center adding and removing them, they got sent to the docks, not the storage, this is super annoying.

### Expected behavior

Sent to available storage other than the dock first.

### Reproduction steps

I think you can figure it out.

### Game version

0.4.12e

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
