### ISSUE TITLE
Vehicle parts III craftable with robotic assembly without researching mega vehicles

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#867]
### Issue description

See title.

### Expected behavior

Not to be craftable until you research mega vehicles.

### Reproduction steps

Research construction IV without researching mega vehicles and look at the list of things the robotic assembly can craft.

### Game version

0.4.12e

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
