### ISSUE TITLE
Large tree harvester green line messed up in a different way than last time

### ISSUE THREAD

**Issue by Prometheus0000** [MaFi-Games/Captain-of-Industry-issues#869]
### Issue description

When I click on one of the harvesters, it shows the green line for it for a fraction of a second, then shows it for another one that's paused. you can use the save I've supplied to see what I mean.

### Expected behavior

To show the green line for the right vehicle.

### Reproduction steps

Not sure aside from using the save and telling the unpaused tree harvester to move.

### Game version

0.4.12e

### Attachments

[Beta-5.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9752385/Beta-5.zip)
![image](https://user-images.githubusercontent.com/8517039/195030130-d8ab53f6-e199-49c5-8b09-265fac0c7b69.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
