### ISSUE TITLE
excavator not fueled even at vehicle depot

### ISSUE THREAD

**Issue by HarmLast** [MaFi-Games/Captain-of-Industry-issues#87]
**Describe the issue**
3 excavators are on the mine shoveling with one niveau difference. They skipped to make a ramp and started somwere else. so the trucks drived to them and filled op from the higher level. the excavators drived a little further but the trucks couldn't reach them anymore because of no ramp.  Diesel was on short supply so the excavators were not completely full and all excavators were empty on the same time.  The situation happened no fuel for the excavators,. And the trucs could not filled up anymore to create a way. So i decided to recover them. but at the vehicle depot they still got stuck with no fuel

**To Reproduce**
1. Load attached save '01-07'
2. Look at te vehicle depot and you see 3 excavators with no fuel

I have even added save 01-06 wich is one save more early the place happened on the coal mine on top 

**Expected behavior**
The excavators should be fueled and drive their way. 
Even attach the excavators to a mine does nothing 
And maybe when a truck not can reach an excavator the excavator goes back and clean the way for them.

**Additional context**
 - Game version: [Beta 0.3.4]

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.
[Saves.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7786271/Saves.zip)

**Comment by MaFi-Games** [comment]
This was fixed in v0.3.6, thanks for reporting!
