### ISSUE TITLE
Tour de contrôle des mines

### ISSUE THREAD

**Issue by Guany2** [MaFi-Games/Captain-of-Industry-issues#870]
### Issue description

Lors de la construction des tours de contrôle des mines 1° elles n'apparaissent pas après leurs construction, Un symbole en rouge # se trouve à leur place . 2° lors de la sélection de zone ,il n'apparait pas les carrés avec leurs niveaux pour permettre de creuser.

### Expected behavior

Fonctionnement normal décrit dans le jeux.

### Reproduction steps

se produit à chaque fois que j'arrive à ce niveau du jeux. Rechargement du jeux sur steam , essais nouvelles parties , Version :EARLY ACCESS 0.4.12e,meme problème.

### Game version

v0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/114601442/195097525-1ae45915-ad7b-473c-8cb3-ee56707c2f38.png)
E:\DOCUMENTS\Captain of Industry\Saves     save_22-09-28_22-55-24-ESSAIS04.save
[22-10-11_14-11-13_1318.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9756130/22-10-11_14-11-13_1318.log)
![image](https://user-images.githubusercontent.com/114601442/195100575-4bcfc11c-5bd9-4503-9e27-92b33aa2e031.png)

**Comment by zuff-coi** [comment]
Pouvez-vous s'il vous plaît télécharger votre fichier de sauvegarde?

**Comment by Guany2** [comment]
Comment je le télécharge , Il ne veut pas une copie .
[save_22-09-28_22-55-24-ESSAIS04.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9780249/save_22-09-28_22-55-24-ESSAIS04.zip)
j'espere que cela va aller.

**Comment by zuff-coi** [comment]
Cette construction a été interrompue

![image](https://user-images.githubusercontent.com/108291414/196198378-7d4b4d89-ae8c-4479-bc7b-502d1679f153.png)

Ces deux tours n'avaient pas leur domaine minier sur une affectation minière pouvant être démarrée (une affectation minière commençant à une zone accessible). Si la case de désignation minière a des bordures rouges, les excavatrices ne peuvent pas commencer à y travailler

![image](https://user-images.githubusercontent.com/108291414/196198657-bdb09da8-63ff-4df1-8434-b4baabaaec07.png)
