### ISSUE TITLE
Health Bonus incorrect

### ISSUE THREAD

**Issue by VernonJv** [MaFi-Games/Captain-of-Industry-issues#871]
### Issue description

Hi

I have noticed that the health bonus for supplying all food types only says 3 categories satisfied.
I'm making the assumption that the categories are "Carbs", "Protein", "Vitamins" & "Treats"

The calculation of Health matches the output from this screen so assuming a miscalculation.  Or just a UI bug?

![Captain of Industry Screenshot 2022 10 14 - 18 55 43 99](https://user-images.githubusercontent.com/112779559/195910931-d66f71f3-6473-4f01-b5d3-ad09728fa1a1.png)
![Captain of Industry Screenshot 2022 10 14 - 18 53 17 08](https://user-images.githubusercontent.com/112779559/195910939-876f9e58-2355-4196-a43f-b8d204a21606.png)

### Expected behavior

4 Categories satisfied giving 16 Health Bonus

### Game version

v 0.4.12C (Experimental)

**Comment by Prometheus0000** [comment]
Note there's no health icon over the treats category. This could probably be communicated better though.

**Comment by MaFi-Games** [comment]
Hi! This is by design, treats don't give a health bonus :)
