### ISSUE TITLE
Data Center

### ISSUE THREAD

**Issue by Madmark910** [MaFi-Games/Captain-of-Industry-issues#872]
### Issue description

Hello. Not sure if an issue or just operator headspace. I have installed the Data center with a whole load of servers (48), set up the chiller, and run pipes from to - to and from in all possible configurations including using a pipe balancer. I have read steam boards, and Reddit boards while using their suggestions to no avail.  Water flows in correct directions, and chill input is full as well as full water output. In some configurations it worked for 30 seconds and stopped.

### Expected behavior

Expected data center to run correctly with items supplied.

### Game version

0.4.12E

**Comment by zuff-coi** [comment]
Could you provide your save game file so we could take a look at what's going on?

**Comment by MaFi-Games** [comment]
Sorry but can't do much without a save file. Closing. Please, open a new one if you have it.
