### ISSUE TITLE
Irrigated farm has no Truck Import?!

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#874]
### Issue description

Why can't I configure Truck Import (water, fertilizer)? Am I forced to use pipes?

![2022-10-17 11_01_58-CoI](https://user-images.githubusercontent.com/109154186/196179214-108078a3-2ba6-4e0b-956c-ff053696c271.png)

### Expected behavior

Can configure Truck Import same as for any other building that needs inputs.

### Reproduction steps

In case it matters, it is a farm that got upgraded to an irrigated farm.

### Game version

v0.4.12e

**Comment by zuff-coi** [comment]
This is intended but maybe a dev can chime in on why this design choice was made.

**Comment by zuff-coi** [comment]
Talked the devs and they confirmed it's intended because of how inefficient it is for trucks to continuously import water. Use pipes instead!

**Comment by RealisticOptimist** [comment]
Hm, not what I was hoping for.
Thank you for clarification!
