### ISSUE TITLE
Large Tree Harvester: Cannot open vehicle menu.

### ISSUE THREAD

**Issue by Zmotive** [MaFi-Games/Captain-of-Industry-issues#877]
### Issue description

Playing on Sailor Difficulty on New Haven Map. I had constructed 1 large tree harvester while still having a small tree harvester and was able to assign a truck to it while I had a small harvester. After scrapping the small harvester, I am no longer able to open up the larger harvester menu to assign trucks (and this applies to any new large harvesters created). Once I create another small harvester, I can then open up the large harvester's menu again.

### Expected behavior

Menu should always open on the large tree harvester regardless of the presence of a small tree harvester.

### Reproduction steps

1. Create a large tree harvester. 
2. Scrap the small Tree harvester.
3. Menu fails to open on large tree harvester.

### Game version

v0.4.12e

### Attachments

[Run 3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/9839683/Run.3.zip)

This is saved with no small harvesters and the large harvester menu is failing to open.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
