### ISSUE TITLE
Graphics: Ain't No Sunshine when she's gone ...

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#878]
### Issue description

Observed twice, not yet reproducible:
![Shady](https://user-images.githubusercontent.com/109154186/197741087-79242175-022f-4fc8-b645-c3ac419d8ded.jpg)
![Sunny](https://user-images.githubusercontent.com/109154186/197741101-b8c5d8ae-733d-4363-867f-0ef2d01fe68c.jpg)

The sun is gone and does not return, not even on reload. Have to restart CoI.

PC is an AMD Ryzen 5900x with AMD Radeon 6800XT, graphics driver Adrenalin 22.8.2.

### Expected behavior

Sun shines when weather forecast says sunny.

### Reproduction steps

Unknown.

### Game version

v0.4.12e

**Comment by MaFi-Games** [comment]
Closing as not reproducible unless we have more data or logs.

**Comment by RealisticOptimist** [comment]
Can reproduce now. On my laptop (RTX3050mobile) and my PC (RX6800XT).

Start CoI.
[Sun.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10098091/Sun.zip)
Load Sun.save
Looks like this:
![Sunny](https://user-images.githubusercontent.com/109154186/204131795-c821535d-2ed3-40e4-bf25-48f2d66e3667.jpg)

[Rain.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10098093/Rain.zip)
Load Rain.save
Run for few seconds until about Jan 5 (still raining).

Load Sun.save again.
Looks like this:
![Gloomy](https://user-images.githubusercontent.com/109154186/204131880-a4442f6f-8109-47c8-818e-a8034161fe32.jpg)

Apparently there is still some shadows, not as dark as the original example. So it seems to be a gradual thing. Effect might add up over multiple run/loads cycles. Could also explain, why I had problems to nail when I observed it.

**Comment by MaFi-Games** [comment]
Thanks for the report, this was fixed and will be available in the next patch!

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
