### ISSUE TITLE
one way lading

### ISSUE THREAD

**Issue by 1podProgrammer** [MaFi-Games/Captain-of-Industry-issues#883]
### Issue description

Trucks rarely return from point of delivery with other lading waiting for pickup
This results in many vehicles returning or running empty in many directions

### Expected behavior

A truck will pick up its consist 
drive to the destination
drop the lading
proceed to the next closest consist waiting for pickup
deliver that consist and repeat this action.

### Reproduction steps

1 generate a waiting consist
2 truck dispatches to pick up the lading
3 truck takes the material to the destination
4 delivers as expected
5 either sits idle or leaves passing one or more consists waiting for delivery

### Game version

v04.12e

**Comment by Prometheus0000** [comment]
I think you need to explain what a "lading" is, because that's not a word.

**Comment by 1podProgrammer** [comment]
Oxford dictionary defines lading as "the action or process of loading a ship or other vessel with cargo." A Bill of Lading is a list of the goods on the vessel. A truck can be considered a vessel. Another common term for shipping goods is consist.
On a side note the term lading is often used in shipping.

**Comment by MaFi-Games** [comment]
Thanks for your feedback. We don't optimize jobs for nearest trucks or support "jobs stealing". These are bigger efforts  / moon shots that we know of and track separately so closing it here.
