### ISSUE TITLE
Priority build and no partial load setting not honored

### ISSUE THREAD

**Issue by 1podProgrammer** [MaFi-Games/Captain-of-Industry-issues#884]
### Issue description

When setting a priority build if auto partial load setting is OFF a truck will deliver less than a full load. On many occasions a priority build is supplied with less than full load. This is contrary to expected action if a supply can supply a full load; several trucks will take very small partial loads; rather than one full load.

### Expected behavior

If a full consist can be delivered a full consist should be delivered.

### Reproduction steps

1 ensure a build has sufficient quantity to satisfy a build (construct) request from a supply depot
2 set Auto Partial Load OFF
3 set Priority ON
4 examine a truck fulfilling the request... many will carry only one or two required supply item 

### Game version

v04.12e

**Comment by MaFi-Games** [comment]
Priority build has been redesigned after Update 1 and should now work better. So closing as fixed.
