### ISSUE TITLE
Contract Unity Per Ship Calculated Incorrectly

### ISSUE THREAD

**Issue by gamr75** [MaFi-Games/Captain-of-Industry-issues#885]
### Issue description

The gold for crude oil contract appears to calculate the unity cost per ship based on the number of gold on the ship rather than the amount of oil that can be returned. Using a 4 module cargo depot (3 oil, 1 gold), charges 6.12 unity per ship instead of the 2.2 unity displayed in the trade interface. All excess gold is still on the ship when it returns and the cargo depot tries to fully load the ship before it departs.

As an experiment, I sent the ship with less gold bars and checked the unity cost:
360 gold cost 6.12 unity
169 gold cost 2.24 unity

Both cases returned 1320 crude oil and any gold above the 132 required for the trade.

I have only tested this with the gold for oil contract, so I do not know if it happens with other contracts as well.

### Expected behavior

One ship to trade 132 gold for 1320 crude oil with a unity cost of 2.2 unity

### Reproduction steps

1. Establish the gold to crude oil contract and assign it to a cargo depot 4 with one module for gold and 3 modules for crude oil
2. Supply the unit module with sufficient gold to fully load the one slot on the ship assigned to gold
3. Allow the ship to depart and observe the unity cost

### Game version

v0.4.12e

**Comment by Strupstad** [comment]
I have the exact same problem, but with the Vehicle Parts II for Crude Oil contract. This problem occured with both a Cargo Depot 4 with Medium modules, and with a Cargo Depot 6 with Large modules. I also did the math, and it seems like the unity cost is calculated based on what the ship has loaded, not based on what it actually sells.

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
