### ISSUE TITLE
Plenty of food edict doesn't show total in Captain's Office

### ISSUE THREAD

**Issue by EstebanLB** [MaFi-Games/Captain-of-Industry-issues#886]
### Issue description

The total unity cost of the edict is not shown above the upper right corner of the edict box like all the other edicts

### Expected behavior

The total should be seen there

### Reproduction steps

Activate the edict with one or two levels.

### Game version

v0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/5374226/199082135-5eb54ab7-76ff-4bd1-b173-d8b1e05312a1.png)

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
