### ISSUE TITLE
Blast Furnace II output problem

### ISSUE THREAD

**Issue by yusufbogatepe** [MaFi-Games/Captain-of-Industry-issues#888]
Hi,

I found out a bug that related to Blast Furnace II. It should give us 48 molten iron but its only 24 molten iron can be claimed every turn.

**Comment by EstebanLB** [comment]
The Funace's actual output is 16 molten iron per turn of 10 days, not 48

**Comment by MaFi-Games** [comment]
Not aware of such issue, seems highly unlikely. If the issue persisten. please file a new one with screenshots and save file.
