### ISSUE TITLE
Harvester cannot reach tree in front of it

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#890]
### Issue description

In the middle of a driveable narrow slope stands a tree.
Harvester can't reach it from below or above. Though it's really close and all driveable up to the tree.
![Harvester](https://user-images.githubusercontent.com/109154186/200747884-81e30973-7e45-4df4-a79d-e350da2b20f5.jpg)
![Harvester2](https://user-images.githubusercontent.com/109154186/200747896-221bb429-31b0-4aae-a3d9-0d8e22cd81f5.jpg)

### Expected behavior

Trees within harvester boom range should be possible to cut down.

### Game version

v0.4.12e

**Comment by MaFi-Games** [comment]
We improved tree harvesting in Update 1, so closing as fixed. If this occurs in the new version again, please file a bug with a save file so we can take a look.
