### ISSUE TITLE
Phantom resources

### ISSUE THREAD

**Issue by laino** [MaFi-Games/Captain-of-Industry-issues#892]
**The issue**
The resource tracker shows resources that are nowhere to be found.

**Expected behavior**
The resource tracker should only show resources I actually have available.

**To Reproduce**
Load attached save and observe that around ~180 steel are nowhere to be found, despite showing up in the tracker.

[save_22-11-17_08-31-55.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10029003/save_22-11-17_08-31-55.zip)

**Notes**
Possibly related to https://github.com/MaFi-Games/Captain-of-Industry-issues/issues/112

**Comment by knmh84** [comment]
all the steel are in a storage near the chemical plant where nitrogen tanks are being formed
![image](https://user-images.githubusercontent.com/106634630/202424495-effe20e2-a5ea-4415-a79e-018dbca49faf.png)

**Comment by laino** [comment]
I need sleep. 

Closing.
