### ISSUE TITLE
Settings: Graphics quality vs. VSync count / FPS limit

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#898]
### Issue description

Tested on AMD and NVIDIA graphics, with 60Hz monitors.

A) Graphics quality seems to have a separate VSync setting per quality without showing it. I see it in the fps (steam overlay).

E.g. in the start screen, in settings,
set fps limit no limit.
set quality to Fast then VSync disabled: ~500fps
set quality to Great then VSync every frame: 60fps.
set quality to Fantastic then VSync every other frame: 30fps.

Ok, when you change graphics quality now, what do you expect? I expect 30fps, the last set value of VSync.

Set quality to Fast, do not touch vSync (still every other frame): ~500fps
Set quality to Great, do not touch vSync (still every other frame): 60fps
Set quality to Fantastic, do not touch vSync (still every other frame): 30fps

B) The FPS limit is also not considered consistently, but in a different way:
Pick any graphics quality, set fps limit to e.g. 30: 30fps
Exit COI
Start COI: 30fps
Change graphics quality: 60fps
...

### Expected behavior

User set VSync count and FPS limit shall always be respected, regardless of changing Graphics quality setting.

### Game version

v0.4.12e

**Comment by MaFi-Games** [comment]
This got resolved in Update 1 as we removed quality settings implemented by Unity. Thanks!
