### ISSUE TITLE
Transports shuffle cargo around same struct

### ISSUE THREAD

**Issue by c0nnex** [MaFi-Games/Captain-of-Industry-issues#9]
**Describe the issue**
2 directly connected "Loose Storage" Containers. 
A->B , B is Set to Empty 50% 
Trucks take cargo from B and oput it back in in A , resulting it being moved to B again and again being picked up ...

**To Reproduce**
1. Load save from #8 
2. Unlink B from screen shot from target container
3. Strange thing happens '...'

**Expected behavior**
Trucks schould not move cargo around in same dirctly connected structures

**Additional context**
 - Game version: 0.2.4

**Attachments**
If applicable, add save files, screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`)
See save from #8 
Location to see it
![Screenshot_1](https://user-images.githubusercontent.com/8324035/134458057-d9f1fdb8-0ee9-4711-9c92-702531978a83.png)
:

**Comment by MaFi-Games** [comment]
Thanks for the report. We are working on ability to explicitly control logistics on storages which should resolve this by by disabling logistics import on A.

**Comment by MaFi-Games** [comment]
In v0.2.6 we introduced ability to explicitly control logistics for storages and machines which makes this solvable by disabling truck import to the storage A.
