### ISSUE TITLE
Height not working correctly for Molten Channel

### ISSUE THREAD

**Issue by maxhawk** [MaFi-Games/Captain-of-Industry-issues#90]
**Describe the issue**
Molten Channel not behaiving correctly when started on one height level and it is inceased or decreased. It freezes and after a few seconds "Transport to selected position not found" message appears.

**To Reproduce**
1. Select Molten Chanel and place starting point.
2. Press Q or E to change height.

**Expected behavior**
Height controls should be disabled for Molten Channel (atleast after first node is placed).

**Additional context**
 - Game version: 0.3.5

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by maxhawk** [comment]
Molten Channel can be started at any level and built if you don't change its height. Not sure if this is useful or not, since ports are on groud level. Can Furnaces and Casters be built on slightly elevated ground so they are connected by Molten Channel on level 2 or 3?..

**Comment by MaFi-Games** [comment]
This is working as intended, molten metal channels cannot go up/down since there is a molten metal in them. Perhaps we should do a better job explaining this in game.

**Comment by maxhawk** [comment]
There is a mention in tutorial messages that not all transports can go up/down.
What this issue is that E/Q keys still try to raise/lower its height, but it shouldn't do that for Molten Chanel because it's not possible.

**Comment by MaFi-Games** [comment]
Thanks for submitting this issue and sorry for being so late. This was finally fixed and will be available in the next patch.
