### ISSUE TITLE
UI: Game window resize ignored by Inventory

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#900]
### Issue description

The inventory list on the right partially ignores when the game window gets resized. 
![TooLong](https://user-images.githubusercontent.com/109154186/204167362-262c18e5-7944-4cec-9a98-eed5715a7e15.jpg)

It should switch to multi columns. It does remain centrered, though.

There is a work around, add/remove an item. That triggers to resize the inventory.

### Expected behavior

Inventory should switch between 1 and 2 (, 3...?) columns depending on window height. Apparently the window resize event is not fully handled.

### Reproduction steps

Reduce window height until inventory is too tall.
or
Increase window height until space is enough for single column.

### Game version

v0.4.12e

**Comment by zuff-coi** [comment]
This has been closed as of 0.4.13! Please let us know if you have any further problems with this issue.
