### ISSUE TITLE
Trucks not transporting some resources

### ISSUE THREAD

**Issue by BritishSpuds** [MaFi-Games/Captain-of-Industry-issues#901]
### Issue description

Some resources, such are ore, construction parts and other random things are not being moved by trucks. but for some reason, other things are such as waste and potatoes. i have no clue why. they were working yesterday when i closed the game but not after i opened it today.

### Expected behavior

Trucks to be transporting stuff correctly

### Reproduction steps

not sure how to reproduce. its randomly happened and i dont think i did anything to make it happen.

### Game version

v0.4.12e

### Attachments

[Trucks not transporting stuff.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10115372/Trucks.not.transporting.stuff.zip)

**Comment by BritishSpuds** [comment]
I've managed to figure out the problem, I had the truck export option deselected for all my storages, I apologise for any inconveniences.

**Comment by MaFi-Games** [comment]
No worries, closing!
