### ISSUE TITLE
None of the trucks could be moved

### ISSUE THREAD

**Issue by BRJunior** [MaFi-Games/Captain-of-Industry-issues#903]
### Issue description

All the trucks gradually stopped moving.

### Expected behavior

I can't move any track.

### Reproduction steps

I'm just building a factory

### Game version

v0.4.8

### Attachments

[3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10134597/3.zip)
[Captain of Industry.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10134603/Captain.of.Industry.zip)

**Comment by MaFi-Games** [comment]
This is most likely vehicles stalling issue due to PF. We have fixed this after Update 1. Thanks for your report!
