### ISSUE TITLE
I seem to have a mining bug.

### ISSUE THREAD

**Issue by catloverjerrygarcia** [MaFi-Games/Captain-of-Industry-issues#906]
Even reassigning the excavator doesn't clear the trouble.  I also saved the game exited completely out of the game and relaunched the game to no effect.

![CaptainOfIndustryBug](https://user-images.githubusercontent.com/103367399/205758742-820e119b-1383-45af-9047-43b50bcc78b8.jpg)

**Comment by catloverjerrygarcia** [comment]
I managed to fix the issue using the recover button on the excavator.

**Comment by MaFi-Games** [comment]
Thanks! Closing as not actionable.
