### ISSUE TITLE
Missing assembly building

### ISSUE THREAD

**Issue by brucemcook** [MaFi-Games/Captain-of-Industry-issues#91]
An unlocked recipe for electronics shows a robotic assembler as being required yet no such building appears in the general machines UI. I could not identify any research that would reveal this machine.
 - Game version: beta 0.3.6

**Comment by MaFi-Games** [comment]
This recipe was unlocked by accident, robotics assembler is not in beta yet. Sorry for the confusion and thanks for the report.
