### ISSUE TITLE
Hospital signs use a red cross on a white background (Geneva Convention violation)

### ISSUE THREAD

**Issue by JammyDuck** [MaFi-Games/Captain-of-Industry-issues#911]
### Issue description

The red cross is a protected symbol used by the International Committee of the Red Cross, it is protected under international law in all contexts and uses.

Use of it in a video game is a minor issue, I doubt anybody is confusing the in-game hospital with one ran by the ICRC, but contributes to watering down it's use during war time that can lead people to incorrectly assume a red cross just means medical rather than the ICRC.

https://www.icrc.org/en/doc/resources/documents/article/other/57jmbg.htm

other developers have also been caught out; https://www.pcgamer.com/how-the-prison-architect-developers-broke-the-geneva-conventions/

### Expected behavior

An alternative symbol such as a green cross should be used

### Reproduction steps

1. build a hospital
2. observe

### Game version

0.4.12e

### Attachments

![image](https://user-images.githubusercontent.com/39169253/208200339-1d435900-e36b-4ff7-b978-feff4483b946.png)

**Comment by heavyk** [comment]
@JammyDuck  what do you think about these conventions:
https://github.com/heavyk/nextdocs/blob/master/concepts/captain-of-3d.md

**Comment by heavyk** [comment]
also, didn't add your save file to verify the bug.

**Comment by JammyDuck** [comment]
It's an illegality with the models rather than a bug so a save file makes no sense.On 22 Dec 2022 06:36, kenny ***@***.***> wrote:
also, didn't add your save file to verify the bug.

**Comment by heavyk** [comment]
you sound upset

**Comment by MaFi-Games** [comment]
The cross was changed to green color in Update 1. Thanks four your report!
