### ISSUE TITLE
Bug in tutorial "Cement Production"

### ISSUE THREAD

**Issue by Darkomage** [MaFi-Games/Captain-of-Industry-issues#913]
Hello,
Just started a fresh game with the latest update

I'm reporting a "bug" with the "Cement Production Tutorial". 
The tutorial should  make you research "ConcreteProduction".
At the moment, step one is "Mine Limestone", then "Build Rotary Kiln".
But at that point, even if I already researched construction 2, I was not asked to research "Concrete Production".
Maybe it's the intended way, but I think the tutorail should be more step by step at this point, for new players.

Bye
Thomas

PS: Awesme work in this latest update !!!

**Comment by MaFi-Games** [comment]
This was fixed in update 1. Thanks for your report!
