### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by Fehzito2907** [MaFi-Games/Captain-of-Industry-issues#915]
### Issue description

The trucks don't do the construction with the required products. also, I can't use the unity in the window to do the structure because the window is too big for my screen and I can't solve this problem.

### Expected behavior

You can do a way to reduce the window to fit the size of the window, or you can create a way to attribute tasks to the truck to do the construction correctly.

### Game version

v0.4.13 early acess

**Comment by MaFi-Games** [comment]
Can you please provide screenshot of the window that is too bug for your screen? And also what is your resolution?

**Comment by MaFi-Games** [comment]
Closing as not enough information available.
