### ISSUE TITLE
Cement Mixer Recipe Selection Missing

### ISSUE THREAD

**Issue by darthchris4** [MaFi-Games/Captain-of-Industry-issues#917]
### Issue description

When clicking on the Cement Mixer unit, the list of recipe options is missing. This is also occurring when hovering over the icon in the build ribbon. I am unable to select a recipe option, making the unit unusable.

### Expected behavior

The user should see the list of available recipe options.

### Game version

v0.4.13

### Attachments

![image](https://user-images.githubusercontent.com/22137419/209698664-d0aba4fc-91bc-45d0-905f-cb0e8f93c833.png)

**Comment by darthchris4** [comment]
Someone on the Discord helped me understand that the Concrete recipe was updated in a recent game update, and it is further down the tech tree. However, it's weird that I was able to build a Concrete Mixer before researching that tech. So that might be a bug.

**Comment by MaFi-Games** [comment]
Did you already play the game before update v0.4.13 when this happened? Or did this happen in a new game that was started after v0.4.13 landed?

**Comment by darthchris4** [comment]
I think this is just an issue where I had a save file created before the 0.4.13 update and then after the update the game sort of glitched. I created a new game on 28 Dec and don't see the issue repeating itself.

**Comment by MaFi-Games** [comment]
This should be gone after Update 1. Thanks for your report!
