### ISSUE TITLE
Cargo Depot II Requirement Mapping in research

### ISSUE THREAD

**Issue by ElliottBott** [MaFi-Games/Captain-of-Industry-issues#918]
**Describe the issue**
One of the requirements for 'Cargo Depot II' is 'Cargo Depot'. The visual line indicating the requirement at first glance suggests 'Gas Combustion' is required before 'Cargo Depot II', not 'Cargo Depot'. Selecting 'Cargo Depot II' correctly shows a highlighted line going to 'Cargo Depot'. 

**Expected behavior**
Researching 'Cargo Depot II' should either have 'Gas Combustion' as a requirement or the 'Cargo Depot' requirement should not pass through 'Gas Combustion' on the "Research Menu". 'Gas Combustion' should be moved to not overlap with the line between 'Cargo Depot' and 'Cargo Depot II'

**Additional context**
Game Version 'v0.4.13'

**Attachments**
![ss (2022-12-28 at 06 48 18)](https://user-images.githubusercontent.com/47416035/209778143-e1e1a6d8-7ff6-4fa1-a7a9-4c3e8965ef79.jpg)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks!
