### ISSUE TITLE
Show inputs/outputs when building is selected

### ISSUE THREAD

**Issue by RussKie** [MaFi-Games/Captain-of-Industry-issues#92]
**Describe the issue**

It is not possible to know what inputs/outputs are unless you build a new building. E.g. if I'm clonning the electrolyzers here, and I have no idea what the ports are:
![image](https://user-images.githubusercontent.com/4403806/147871960-210ce1a4-fe3b-4d83-83cd-e9a28466c9ac.png)

Please always show the input/output materials/substances for "green" and "red" arrow. It would be great to have the same for the "yellow" arrows too.

**Additional context**
 - Game version: v0.3.4

**Comment by MaFi-Games** [comment]
Thanks for the report, we will look into this.

**Comment by MaFi-Games** [comment]
Thanks for you report. This has been fixed in one of our previous updates, selected buildings show their products next to ports.
