### ISSUE TITLE
unintentional pausing of transports under construction

### ISSUE THREAD

**Issue by heavyk** [MaFi-Games/Captain-of-Industry-issues#920]
**The issue**
it's unclear that the construction has been paused, so often times I have to go hunting for why it's not building.

**Expected behavior**
it should always build.

**To Reproduce**
- build a pipe
- unity build the pipe (it turns blue)
- before the first pipe can build, build a second pipe that connects to the first pipe anywhere.
- when the second pipe connects to the pipe in the process of being built, it gets paused (pipe turns white)
- look at the first pipe, it still has all of its CP, so all I have to do is unpause it

**Additional context**
0.4.13

**Comment by MaFi-Games** [comment]
I cannot reproduce this issue in Update 1. Seems like it was already fixed.
