### ISSUE TITLE
failed load

### ISSUE THREAD

**Issue by heavyk** [MaFi-Games/Captain-of-Industry-issues#921]
**The issue**
not likely a huge issue because it's an old save from. 0.4.12

what I think the bug is, is that this is a save on the initial new game. I'm not even sure if the update/sim loop has even begun, because I think the clock is jan 1 0001 (or whatever first date is... I noticed 0.4.13 starts on jan 2 0001)

**To Reproduce**
1. Load [p- 0.0.0 - initial.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10314178/p-.0.0.0.-.initial.zip)

**Comment by MaFi-Games** [comment]
Thanks for reporting this. We have noticed this issue but it occured rarely between v12 and v13 only if player started fresh game in v12 and did not get very far. The fix was not feasible without breaking all saves from experimental so we made the trade off and let it be.
