### ISSUE TITLE
phantom yellow truck highlight in centre of map

### ISSUE THREAD

**Issue by heavyk** [MaFi-Games/Captain-of-Industry-issues#926]
![2022-12-28 12_58_48-Captain of Industry](https://user-images.githubusercontent.com/1226324/209866578-da1e0f1f-9274-4c96-a2cf-22865644f72d.png)
![2022-12-28 12_59_13-Captain of Industry](https://user-images.githubusercontent.com/1226324/209866589-056b7832-f301-4d2c-ab5e-f897c66d621a.png)

**The issue**
loaded trucks that just had their cargo unity removed show the yellow highlight in the centre of the map

**To Reproduce**
1.  [q- 0006.9 production.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10316215/q-.0006.9.production.zip)
2. select tree harvester truck in the centre and unity empty the cargo

0.4.13

**Comment by MaFi-Games** [comment]
This is hopefully gone with Update 1. Thanks for your report!
