### ISSUE TITLE
Game crash, no crash log

### ISSUE THREAD

**Issue by Llewelyn1966** [MaFi-Games/Captain-of-Industry-issues#928]
### Issue description

Random game crash, but there's no crash log in the normal place.
Has the crash log been combined into player.log?

### Expected behavior

Didn't expect the game to crash :) 
Expected crash log in the normal directory but there is none. 

### Reproduction steps

I don't know what triggered it.  I have never noticed a common trigger for these crashes.

### Game version

0.4.13

### Attachments

[Playerlog.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10320728/Playerlog.zip)

**Comment by zuff-coi** [comment]
Thanks for reporting this and we'll look into it.

**Comment by MaFi-Games** [comment]
Closing as this an older version and we don't have enough information. Please file a new bug if this happens in the new version.
