### ISSUE TITLE
Please stop using my OneDrive for logs and saves

### ISSUE THREAD

**Issue by Haggle1996** [MaFi-Games/Captain-of-Industry-issues#929]
### Issue description

COI has always saved to my OneDrive, which is frustrating enough, but since the recent updates it's also now storing logs which are topping out near a gig so far. For those of us with only the free-tier of space (15GB), this is a huge amount of wasted space. Please use the game's Steam folder for at least log data, if you won't move everything over to there. I'm getting close to 600 hours into this game and this bug is really making me hate on this game. A lot of things on a Windows computer stop working when the cloud drive is full.

![image](https://user-images.githubusercontent.com/11808184/210023850-3ddbe986-1594-4d0d-aa9c-4af2b3ce8976.png)

### Expected behavior

Not save logs, save games, in OneDrive

### Game version

v0.4.13

**Comment by MaFi-Games** [comment]
Not sure how your Documents ended up on OneDrive. But Update 1 changed the save location anyway, so this issue is gone no matter what. Marking as closed.
