### ISSUE TITLE
Game goes hellwire when using VLC player

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#93]
Edit: Removed see comment section

**Comment by McRib33** [comment]
The issue is much bigger and it was cause by the VLC running in frontscreen which cause everything to go hellwire. Issue is solved.

**Comment by MaFi-Games** [comment]
This sounds like some GPU issue, do you run the game Full screen or windowed? What is your GPU and driver version?

**Comment by McRib33** [comment]
It run on fullscreen without boarders. My GPU is a 2070 RTX Super from Gigabyte with the newest Driver (need to look up the version later in a train at the moment)

**Comment by McRib33** [comment]
It run on fullscreen without boarders. My GPU is a 2070 RTX Super from Gigabyte with the newest Driver (need to look up the version later in a train at the moment)

**Comment by MaFi-Games** [comment]
Closing as we did not receive any other similar report for very long time. Feel free to file a new one if there is more observations.
