### ISSUE TITLE
Bricks with wood

### ISSUE THREAD

**Issue by SEBrotherhood** [MaFi-Games/Captain-of-Industry-issues#930]
Just a typo, nothing game-breaking! I've enjoyed CoI and look forward to the change with the bricks.

During the tutorial, one of the "quests" is to use the Trading post to purchase bricks. Your wording states "purchase bricks for wood" when it should state: Purchase bricks with wood.
![image](https://user-images.githubusercontent.com/10410824/210410986-cf3f4a6a-4126-4084-b4a0-463f7151fede.png)

**Comment by ArtClark** [comment]
I think the language is correct as is.

**Comment by MaFi-Games** [comment]
I don't see anything wrong, "for" is correct in this context.

**Comment by SEBrotherhood** [comment]
Purchase groceries for money.
Purchase gas for money.
I paid my bills for money.
None of these are correct. WITH is the correct conjunction. 

IF the wording was: Purchase 10 Bricks FOR 10 wood, then that is what makes it different. With no number value, "with" should be used.
