### ISSUE TITLE
Anaerobic digester is missing from wasterwater treatment research.  

### ISSUE THREAD

**Issue by 1podProgrammer** [MaFi-Games/Captain-of-Industry-issues#931]
### Issue description

Anaerobic digester is missing from the latest from wastewater treatment. Was available in previous release.

### Expected behavior

Upon researching wastewater treatment anaerobic digester would appear and available.
It is not...

### Reproduction steps

1 research wastewater treatment
2 upon completion add the digester to the map

### Game version

v04.12e

**Comment by zuff-coi** [comment]
Thanks for submitting. The Anaerobic digester has been moved to "Biofuel" research:
![image](https://user-images.githubusercontent.com/108291414/210835993-a9a9fc7d-49a8-4615-af3c-4dbf5d5c4b0a.png)

**Comment by 1podProgrammer** [comment]
Didn’t see that in the release notes.

Allen
