### ISSUE TITLE
No place to dump dirt but it's right there in the same mine all lit up pretty

### ISSUE THREAD

**Issue by jthill** [MaFi-Games/Captain-of-Industry-issues#932]
### Issue description

The truck has dirt, the mine's zoned for dirt dumping, there's the dump markers and the truck.

### Expected behavior

I expect the truck to dump the dirt in a dump area it can reach zoned for dirt.

### Reproduction steps

1. load the attached save, follow the alert.

I think it might be that I set up the zones before placed the tower, and before I'd even researched vehicles?

### Game version

0.4.13

### Attachments

[save_23-01-04_06-06-57 bugged.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10344815/save_23-01-04_06-06-57.bugged.save.zip)
![20230104062147_1](https://user-images.githubusercontent.com/80352/210575920-7538aac9-b516-42eb-a6f1-93c2f4b7b85b.jpg)

**Comment by zuff-coi** [comment]
Thanks for reporting.

The truck with dirt by the tower was trying to reach the farther away designation for some reason. You can temporarily resolve this by removing the inaccessible dumping area. We'll look into what caused this problem.

**Comment by MaFi-Games** [comment]
This was a bug and thanks to your save file we were able to find it and fix it! It will be available in the next patch (likely tomorrow). Thanks!

**Comment by jthill** [comment]
It's a good world. Thanks.
