### ISSUE TITLE
Game crashes Unpredicatably

### ISSUE THREAD

**Issue by ksorbo** [MaFi-Games/Captain-of-Industry-issues#933]
### Issue description

I have had this problem since I started playing the game.

The game will crash without warning. There is no way to predict when this will happen.

It seems to happen when I have only played the game for a few (5-10) minutes. It also seems to have something to do with movement on the screen.

When the crash occurs, a COI dialog pops up briefly and then the game exits to the OS.

### Expected behavior

Game crashes

### Reproduction steps

Can't predictably reproduce the error.

### Game version

v.0.4.12

**Comment by zuff-coi** [comment]
Sorry to hear this, could you provide log files? 

You can find your logs in "Documents\Captain of Industry\Logs" and "%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\".

**Comment by zuff-coi** [comment]
> I have attached 2 logs. Not sure if this will be of any value.

I'm sorry but I do not see any log files attached, could you try again?

**Comment by ksorbo** [comment]
I am zipping the logs this time.

**Comment by MaFi-Games** [comment]
Closing as not enough information available.
