### ISSUE TITLE
Vehicle parts 3 gets stuck and won’t produce

### ISSUE THREAD

**Issue by h1978n** [MaFi-Games/Captain-of-Industry-issues#934]
### Issue description

Vehicle parts 3 gets stuck and won’t produce. Workt earlier. I see that another step was added so now you need electronics 2. Unfortunate change as it means rebuilding a lot.

### Expected behavior

Vehicle parts 3 to contiune to work

### Reproduction steps

I see that another step was added so now you need electronics 2. Unfortunate change as it means rebuilding a lot.

### Game version

v.04.13

**Comment by zuff-coi** [comment]
Could you provide the save file this is happening in?

You'll find your saved games in "Documents\Captain of Industry\Saves"

**Comment by h1978n** [comment]
[bra 3.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10467863/bra.3.zip)

Hi
Here is the save file, had to zip it to be able to upload it. 
As I wrote, I think I found what the problem is, you added a step in tech-tree after I fished my building, so now  more steps are needed.

**Comment by MaFi-Games** [comment]
Closing as we changed the research tree around electronics II in Update 1 a lot so this is most likely obsolete.
