### ISSUE TITLE
"Produce Diesel" Tutorial Task incomplete even when producing Diesel

### ISSUE THREAD

**Issue by RavenDreamer** [MaFi-Games/Captain-of-Industry-issues#935]
**The issue**
The fourth tutorial step for "Diesel Production", "Produce Diesel (0/16)" is unable to be completed, even when running a basic distiller and producing Diesel. In my case, the fifth tutorial step, "Dump Waste Water (0/8)" is already complete, which is only possible if Diesel were produced.

**Expected behavior**
It should be impossible to complete "Dump Waste water" without necessarily completing "Produce Diesel" first.

**To Reproduce**
Unknown, but save attached. 

Problem persists through reload.

**Additional context**

 - Game version: 0.4.13

**Attachments**

[Captain Mortis.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10348926/Captain.Mortis.zip)

**Comment by zuff-coi** [comment]
Thanks for the report!

**Comment by MaFi-Games** [comment]
This is fixed now! Thanks for the save, it was very helpful!
