### ISSUE TITLE
Tutorial mission is not finishing after product produced

### ISSUE THREAD

**Issue by samzzzsam** [MaFi-Games/Captain-of-Industry-issues#936]
### Issue description

I started a new game and finished the first tutorial parts without a problem.
but the game can't seem to detect me producing Maintenance 1 same with Diesel.

I have done screenshots of both issues:

![diesel bug](https://user-images.githubusercontent.com/122026050/210785260-6a1e9a0b-7c47-488d-8e1a-11dee5f1602d.PNG)

![maintance bug](https://user-images.githubusercontent.com/122026050/210785263-e5d440a0-3e83-4b8c-a469-a12da1004b6e.PNG)

### Expected behavior

It should just have finished the tutorial mission.

### Game version

0.4.13

### Attachments

savegame:

[0.4.13 bug report savegame.save.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10352348/0.4.13.bug.report.savegame.save.zip)

**Comment by zuff-coi** [comment]
Thanks for reporting this. I can confirm that it is indeed stuck!
