### ISSUE TITLE
Excavator silently stuck

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#938]
### Issue description

Excavator tries to get to an unreachable place. Instead of going somewhere else or at least notifying the player, it is silently stuck in an endless loop.

![Stuck](https://user-images.githubusercontent.com/109154186/211553474-42ccb3b3-5b19-4115-abe5-9e55bc3ea1cd.jpg)

I think I have seen sth. similar with vehicles trying to dump in an unreachable spot. Also without informing the player.

### Expected behavior

No vehicle should get silently stuck.
Ideally find another place.
If not, notify player (like e.g. the harvester with unreachable trees).

### Reproduction steps

Load attached save and unpause.

### Game version

v0.4.13 (148)

### Attachments

[Stuck.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10382781/Stuck.zip)

**Comment by zuff-coi** [comment]
Thanks for your submission. We find that digging near the coast causes issues at times. I was able to resolve yours by undesignating and redesignating the mining job.

The issue with the excavator not alerting the player is a valid one, and I've forwarded it to the team.

**Comment by NanoCE** [comment]
I'm facing a similar issue. My excavator is trying to reach a dig location that is not possible for it at this current moment. I'm using the leveling tool in this situation so once the fill in front of the dig position is placed, this will resolve itself, just in the meantime the excavator is going to/from the position in the below screenshot every other second. It should also be noted that their are multiple other valid mining positions for the excavator to take in this case.
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8260901/3e1a1953-9e8f-4cc6-aa31-36d7e9f25fce)
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/8260901/dae5e429-036b-4175-a9b2-08bc83ec98ee)

World:
[save_23-06-02_12-51-02.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/11638432/save_23-06-02_12-51-02.zip)

**Comment by MaFi-Games** [comment]
We have fixed several issues of excavators being stuck in a loop in Update 1. So marking this as resolved.
