### ISSUE TITLE
Pressing Numpad0 pauses game

### ISSUE THREAD

**Issue by rdsuperpup** [MaFi-Games/Captain-of-Industry-issues#943]
### Issue description

I have remapped keyboard shortcuts in the game to suit my preferences, but every time I press NumPad0, the screen rotates (the intended keyboard shortcut), but the game also pauses. It doesn't matter what speed the game is on, the game goes straight to pause. Pressing the key again does not un-pause the game. 

### Expected behavior

Screen should rotate, but the game should not pause

### Reproduction steps

While in game, press NumPad0

### Game version

0.4.13

### Attachments

![image](https://user-images.githubusercontent.com/22315355/212558659-c6474489-8aa4-4a4d-b7eb-92abae992877.png)

**Comment by QuantoSolo** [comment]
There seem to be several not mentioned keyboard shortcuts for game speed:
Num-0 - Pause
Num-1 - Normal speed setting
Num-2 - Fast speed setting
Num-3 - Fastest speed setting

**Comment by MaFi-Games** [comment]
After Update 1, we now allow to remap these keys, so marking this as fixed. Thanks for your report!
