### ISSUE TITLE
Pinned resources's occupation percentage bar counts unfinished storage buildings

### ISSUE THREAD

**Issue by EstebanLB** [MaFi-Games/Captain-of-Industry-issues#944]
![image](https://user-images.githubusercontent.com/5374226/212772067-01618171-5979-44b5-9f81-bc25f89816ad.png)
The occupation bar under a pinner resource takes into account unfinished storage buildings, even those with paused construction and 0% progress

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
