### ISSUE TITLE
Can't save anymore

### ISSUE THREAD

**Issue by pogocool66** [MaFi-Games/Captain-of-Industry-issues#945]
### Issue description

Its freeze every time and want to save a game. A Uninstall it a install it again and keep with the same issue. I loaded a game before the last one, and I'm unavailable to save the game.

### Expected behavior

Solve it

### Game version

v0.4.13

### Attachments

Freeze saving game

**Comment by zuff-coi** [comment]
Please provide log files and the save file that are creating these issues.

You can find your log files in two locations:
`"Documents\Captain of Industry\Logs"`
and 
`"%USERPROFILE%\AppData\LocalLow\Mafi Games\Captain of Industry\"`

You'll find your saved games in "Documents\Captain of Industry\Saves"

**Comment by MaFi-Games** [comment]
Closing as there is not enough information available.
