### ISSUE TITLE
Entering Photo Mode bug

### ISSUE THREAD

**Issue by MrJoshua023** [MaFi-Games/Captain-of-Industry-issues#946]
### Issue description

If you are holding the "Free Look Mode" button when you press "Photo Mode"  it bugs out, doesn't enter photo mode, and key presses don't work properly.

I have free look bound to a secondary button and it does it there as well.

### Expected behavior

Enter photo mode.

### Reproduction steps

1.)  Hold Free Look button (default middle mouse)
2.)  Press Enter Photo Mode (default F11)
3.)  try to click hot keys such as Upgrade tool or Unity tool.

### Game version

0.4.1.3 (148)

**Comment by MaFi-Games** [comment]
Tried this now and it seems this issue is already fixed. Thanks for your report!
