### ISSUE TITLE
visual bug filling in ocean

### ISSUE THREAD

**Issue by tippyc2** [MaFi-Games/Captain-of-Industry-issues#947]
### Issue description

![20230120131045_1](https://user-images.githubusercontent.com/123210195/213806519-9873087f-17ba-4ba6-baab-f7d8c87747f4.jpg)
I encountered a visual bug in an area i was filling in.  This area had already been filled in by the trucks.  The ocean texture updated to the correct area at long viewing distance, but the ground didn't update until zoomed in

### Expected behavior

expected both the ocean visual and the ground visual to update at the same time

### Reproduction steps

issue occurred in an area that was quickly being filled by many trucks

### Game version

0.4.13

### Attachments

[visual issue submission.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10470319/visual.issue.submission.zip)

**Comment by MaFi-Games** [comment]
We have changed our terrain significantly in Update 1. So I marking this as resolved. If this occurs with the new terrain as well, please let us know.
