### ISSUE TITLE
Radar system 1 not found

### ISSUE THREAD

**Issue by daMaura** [MaFi-Games/Captain-of-Industry-issues#95]
I have explored the entire world map accessible by ship, but I have **not found radar system 1**. I have found radar system 2. This means that further research is no longer possible.

**Expected behavior**
Since I can no longer upgrade my ship, it is impossible to continue playing. I would have expected to find radar system 1 first.

**Additional context**
 - Game version: Beta 0.3.7
 - Game seed: hb936roqyjfw
 - Difficulty: Captain
 
![Radar1](https://user-images.githubusercontent.com/80401121/147936874-f6e695c9-bc39-4400-93e3-68ed415cdbcf.jpg)
![Radar2](https://user-images.githubusercontent.com/80401121/147936907-8f703343-3ef8-45ba-b4be-474162fe26c0.jpg)
![Version](https://user-images.githubusercontent.com/80401121/147936912-e429a463-0874-4b37-93e5-e79040c64c1a.jpg)
[RadarSystemOneNotFound.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7802173/RadarSystemOneNotFound.zip)

**Comment by daMaura** [comment]
Here is the map
![Map](https://user-images.githubusercontent.com/80401121/147937577-eb2542d3-5edc-45a6-a23b-c5f652d91915.jpg)p

**Comment by McRib33** [comment]
The radar MK I is very far outside than it should be it aas fix 1 week ago but that doesnt effect old save. So please exploring further you will find it.

**Comment by MaFi-Games** [comment]
Hi, thanks for your report. The radar system was behind the village north from your location:
![image](https://user-images.githubusercontent.com/90082857/148866812-0e7320a1-746d-4ab0-86bb-c95863e8b070.png)
![image](https://user-images.githubusercontent.com/90082857/148866857-093e44ca-d8c7-4b69-8a1f-17a21fa32262.png)

We have made the nodes next to the initial village discovered by default in new saves.
