### ISSUE TITLE
UI - Planned Farm - Crop Selection Window not properly drawn

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#950]
### Issue description

Select crops on a planned (Ghost) Farm:
![PlannedFarm](https://user-images.githubusercontent.com/109154186/215028636-b1534537-a746-45c9-89b2-aa24d29dd6a2.jpg)
The Crop Selection Dialog is not properly drawn in front of the Farm Dialog.
The issue does not occur on already built Farms or planned Irrigated Farms. I did not test the greenhouses.

### Expected behavior

Crop selection dialog properly drawn in foreground.

### Reproduction steps

[PlannedFarm.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10516382/PlannedFarm.zip)

### Game version

v0.4.13 (148)

**Comment by MaFi-Games** [comment]
This was fixed around Update 1. Thanks for your report!
