### ISSUE TITLE
flickering screen

### ISSUE THREAD

**Issue by JCindustry** [MaFi-Games/Captain-of-Industry-issues#954]
### Issue description

My stats

11th gen i5 11400F
32gb mem
samsung SSD 980 pro
geforce rtx 3080 graphics card

I have been playing for a few weeks now with some issues. Playing on a 4k monitor is nearly impossible once the world get slightly big and I don't have a weak setup. So I play on the 2k instead even keep it at 60fps but once the map gets big it struggles to make 42fps. Not huge problems but.
Today this morning it started flickering right after I left the save screen while playing. I played Apex and rocket league right away,its not my monitor. Went back the flickering is gone,but comes back. 

### Expected behavior

I dont know how lower grade computers play this game my son has a more powerful computer than me and as you can see I'm no sissy. Maybe make machines not animate until we zoom in a certain distance maybe that saves resources. The game is not smooth once you get some building up but its a great game. 

### Reproduction steps

The flickering seems to happen after I leave the menu while playing. Once its happening I have to restart the game many times for it to stop. 

### Game version

v0,4.13

**Comment by MaFi-Games** [comment]
We have made several performance improvements in Update 1 and one of our upcoming patches. Frames for endgame factories are always a struggle, but we are getting better. The flickering, I'm not sure what you exactly mean by that, but it might also be something related to vsync or refresh rate. Or something in Unity does not play well with your GPU. However, many things have changed, including updated Unity. So I will close this for now. Feel free to file a new ticket with more information if it still occurs on the latest version.
