### ISSUE TITLE
Transport Pillar Ghosts

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#956]
### Issue description

Seem to have found a race condition:
Deleting a transport while building one leaves ghost pillars behind.
![Pipes1](https://user-images.githubusercontent.com/109154186/216962163-2ede61c9-6d8e-4bb2-a57d-494ada894683.jpg)
![Pipes2](https://user-images.githubusercontent.com/109154186/216962174-4e28d088-22d6-4433-b7e6-2310b51d8e44.jpg)
![Pipes3](https://user-images.githubusercontent.com/109154186/216962967-80dd5820-7bfe-4124-b785-f3a161c48f36.jpg)
![Pipes4](https://user-images.githubusercontent.com/109154186/216962983-d3143d09-6b9c-48b0-90e4-7d1ce8295333.jpg)

### Expected behavior

No ghost pillars on built transport.

### Reproduction steps

See pics.

### Game version

v0.4.14(151)

**Comment by MaFi-Games** [comment]
Thanks for the helpful report, this will be fixed in the next patch!
