### ISSUE TITLE
Liquid Dump block access to harbor

### ISSUE THREAD

**Issue by McRib33** [MaFi-Games/Captain-of-Industry-issues#959]
hi Zuff,

a another small bug i found is that the liquid dump is blocking the accesss to harbor without telling that directly.

How to reproduces:

Load the same and launch the game. Dismantel the liquid dump and the harbor is free. But when you try to build it you dont get any indication that it cause some kind of problem. 

Idea to solve it: Make it like the harbor so it will indicated in red if there are collision on the sea. That would block the Harbor.

Version: 4.14

[23-02-07_19-48-autosave.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10678525/23-02-07_19-48-autosave.zip)

**Comment by MaFi-Games** [comment]
Closing as fixed as this was significantly improved in Update 1. Thanks!
