### ISSUE TITLE
Maybe memory leaks: Having the game open for >48h led to sluggishness and a 5GB mem footprint

### ISSUE THREAD

**Issue by thetaphi** [MaFi-Games/Captain-of-Industry-issues#96]
I've tried to keep a game instance open for a while, pausing instead of closing the game, for about 48h.
Play time maybe 10-14h, didn't keep track. Memory image >5GB (Fresh load of the same save is 3GB in RAM), game gets sluggish, closing it took ages and a force close in the end.

Attaching the log, and the savegame in case it's not a problem of the long run time in the first place, but something with the setup there.

A lot of "~Sim: Path finder crazy busy: XX tasks is waiting in the queue." where 25 < XX < 40.
[22-01-03_03-48-24_8939.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7804058/22-01-03_03-48-24_8939.log)

The Beach, 323 years, 109 vehicles.
[The Beach_ Great Coal Line.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7804066/The.Beach_.Great.Coal.Line.zip)

**Comment by thetaphi** [comment]
Latest log from running the map for two days.

Memory footprint went up to 6GB. Still waiting for the game to actually close after hitting quit five minutes ago ^^

[22-01-04_07-17-43_8611.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/7819757/22-01-04_07-17-43_8611.zip)

**Comment by MaFi-Games** [comment]
Thanks for the reports, we will look into this.

**Comment by MaFi-Games** [comment]
Was this several subsequent game reloads or one really lonf sessioin?

**Comment by thetaphi** [comment]
One really long session. That save game is out of date, do you want me to try to build a new test case after all the refactoring you've done?

**Comment by MaFi-Games** [comment]
I believe we have fixed memory issues during EA 1. If you still experience this on the latest version, please file a new bug. Thanks!
