### ISSUE TITLE
blueprints folder Back key sometimes locked

### ISSUE THREAD

**Issue by convict-vx** [MaFi-Games/Captain-of-Industry-issues#963]
### Issue description

i created a blueprint folder for smelting setups, sometimes the back key to go to the homescreen of the blueprints is locked as in having a blueprint that requires a building that is not researched yet.

Might have to do with having locked blueprints on the main blueprints screen

### Expected behavior

never lock that button

### Reproduction steps

1. have blueprints from other save file (or imported trough bp sharing)
2. make folder and add in a BP
3. go in folder and sometimes the button will be locked

### Game version

0.4.14 (152)

### Attachments

Pic of locked key
![image](https://user-images.githubusercontent.com/6298792/218273864-7f290cd2-6128-4c8c-b084-3807c24ef5ca.png)

my main BP screen
![image](https://user-images.githubusercontent.com/6298792/218273880-35590dee-7fb5-4996-abea-a6add7bb81c8.png)

**Comment by MaFi-Games** [comment]
I think this was fixed, as I can reproduce this anymore, so closing as done. If this occurs again in the new version, please file a new bug. Thanks!
