### ISSUE TITLE
Harvester - "No Fuel" causes faulty extra "No Trees"

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#969]
### Issue description

Harvester with "No fuel" shows an additional "No trees" notification. However, that is clearly wrong. The trees are only unreachable because the harvester cannot move anymore.
![Harvester](https://user-images.githubusercontent.com/109154186/218739750-dcbe4a71-fa79-4b41-9e26-2aceebe61b2c.jpg)

### Expected behavior

"No Fuel" should not cause "No Trees" for the same harvester.
However if "No Trees" occurs first, and then "No Fuel", either way looks sensible.

### Reproduction steps

Let harvester run dry while there is still trees to cut within reach.

### Game version

v0.4.14a(154)

### Attachments

[Harvester.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10732373/Harvester.zip)

**Comment by willsmith9182** [comment]
I think I also encountered this when the harvester was out of maintanence

**Comment by MaFi-Games** [comment]
This was fixed shortly after Update 1. Thanks for your report!
