### ISSUE TITLE
Planning mode icon is off after reloading

### ISSUE THREAD

**Issue by a-casual** [MaFi-Games/Captain-of-Industry-issues#97]
**Describe the issue**
When you save and reload a game with planning mode enabled, the planning mode itself is on, but its icon is off (gray).

**To Reproduce**
1. New game
2. Enable planning mode
3. Note that the icon is orange, and new buildings are placed paused
3. Save
4. Load the save
5. Note that the icon is now gray (❌), and new buildings are placed paused

**Expected behavior**
Icon state on reload should match the feature state:
- either orange icon and planning mode enabled
- or gray icon and planning mode disabled

**Additional context**
 - Game version: 0.3.8 and earlier

**Attachments**
![image](https://user-images.githubusercontent.com/57562727/148162670-531a01b1-5e29-4a7e-8e26-2e3f20245b3f.png)

**Comment by MaFi-Games** [comment]
Thanks for the report, we will look into this.

**Comment by MaFi-Games** [comment]
Fixed in 0.3.11.d. Thanks for reporting!
