### ISSUE TITLE
Beacon - Note outdated

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#975]
### Issue description

Pausing the Beacon (even no power, no Unity) does not reset the progress anymore. The Note in the Beacon window should be removed.
![BeaconNote](https://user-images.githubusercontent.com/109154186/220217589-f0c9bf8e-8800-4097-a917-187a19ad1f8d.jpg)

### Expected behavior

Behavior and in game note text match.

### Reproduction steps

Pause the beacon. Unpause the beacon. Progress is still there.

### Game version

v0.4.14a(156)

**Comment by RealisticOptimist** [comment]
Could it be, the beacon sometimes does reset when paused too long?

**Comment by MaFi-Games** [comment]
The way it works is that the beacon will gradually lose its progress. Every second it's paused wipes a second from the progress it made so far. So this works as intended.
