### ISSUE TITLE
Cannot find valid pillars placement

### ISSUE THREAD

**Issue by Xaosmaster** [MaFi-Games/Captain-of-Industry-issues#977]
### Issue description

When copy-pasting, or loading blueprints, parts of the copied group or blueprint fail to paste.  It appears that there are differing standards as to what counts as satisfying gravity and physics in regards to pillar placement.  In the live game, transport connections to building ports or connectors count towards satisfying pillar placement, while the copied or blueprinted version do not.

### Expected behavior

Groups of objects or blueprints place correctly.

### Game version

v0.4.14a (156)

### Attachments

![pillar placement](https://user-images.githubusercontent.com/39066835/220784648-9be47c17-b24b-49bd-89eb-01a47d2af250.jpg)

**Comment by MaFi-Games** [comment]
We made several changes in Update 1. Also, we don't have the save file/blueprint here to reproduce. I'm closing this as obsolete, but please file this again if this persists in the new version with more repro info.
