### ISSUE TITLE
Connectors  - not reverted to Transport after Building got deleted

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#979]
### Issue description

![Before](https://user-images.githubusercontent.com/109154186/221352493-d7832b0b-e049-438a-ab11-0f6ba98c2faa.jpg)
Some storages get deleted.
![After](https://user-images.githubusercontent.com/109154186/221352494-c854aa3b-2c4a-476e-8b4d-7b632c1f0ffd.jpg)
Connectors should have been automatically reverted to plain transports.
Workround: e.g. toggle transport direction (twice).

### Expected behavior

Connectors should be automatically reverted to plain transports. Iirc this was working until some weeks ago.

### Reproduction steps

Delete the empty storages.

### Game version

v0.4.14b (157)

### Attachments

[Connector.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10830908/Connector.zip)

**Comment by MaFi-Games** [comment]
This does not happen when transport gets deleted, but it happens in this case when storage gets deleted. So it happens only when a building is deleted from a connector.
