### ISSUE TITLE
Dumping unwanted resources (ie Sand) 

### ISSUE THREAD

**Issue by ymer234** [MaFi-Games/Captain-of-Industry-issues#98]
When you dig unwanted resources you can set them to be dumped, either within a mini are or outside one. The problem comes when you need a resources and dig for it and at the same time accidently dig it up, you can't get rid of it.

Example: sand
You need sand for some recipies, you setup a mining job for it. All well and good. 
Your silo gets full after a while and the digging terminates, because there are no space in the silo. Still good and well.
At the same time your other mining jobs carry on as usual until they dig up sand. The trucks have nowhere to go with this sand and the dighing on that site stops. Not good.

You could solve this issue by setting up sand in your normal "dump area", but then the normal sand-digging-site trucks will start dumping sand there too.

**Comment by MaFi-Games** [comment]
You can modify global dumping filters. Also storages have priority over dumping designations. There are also custom routes that can improve this as well - e.g. send mining trucks are only assigned to sand silos. Finally if truck is really stuck one can use the "discard cargo" option. So probably there isn't any action item for us at this stage.
