### ISSUE TITLE
Pumps can not be placed on reclaimed land when on the edge of buildable aerea 

### ISSUE THREAD

**Issue by FrankBKK** [MaFi-Games/Captain-of-Industry-issues#980]
**The issue**
When you reclaim land up to the out-most  possible point it is not possible to place pumps on this land. 
It shows a message 'Outside of build able area'  

**Expected behavior**
Reclaimed land should be usable 

**To Reproduce**
Describe steps to reproduce the issue here, for example:
1. Reclaim land up to the most far possible point
2. Try to place a pump there 

**Additional context**
 - Game version: 0.4.14b

![image](https://user-images.githubusercontent.com/12725516/221500996-3f07ecb3-52cb-4a71-86fe-47adf98a9e3a.png)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
