### ISSUE TITLE
Statistics - Max - CoI crash / MS Windows freeze

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#985]
### Issue description

Load Neet Engineer's "good for benchmark save.save"

Open Statistics - choose e.g. Fuel. - choose "Max" time. RAM consumption grows from 6.3GB to 21.2GB. CoI freezes for some seconds to a minute, then exits.

1st time it happened, my 32GB PC did not have enough RAM available (other SW running), Windows got unresponsive, had to hard reset my PC.

![2023-03-03 14_28_44-Task Manager](https://user-images.githubusercontent.com/109154186/222648275-da3385a7-96d2-42d4-b0cf-ce4ecc206f74.png)

### Expected behavior

Only few datapoints per item can be shown anway (no more than the width of the statistics window display area adjusted by scaling). That's maybe like 4k data points per item on a 8k display. Unity has 22 items, each data point 8 bytes, 

If the data gets processed before being shown, that's well below 1MB.
Even without preprocessing, 6.2M days, 22 items: 1GB.

Never ever, this may be allowed to eat GBs of RAM until CoI or even the PC crash!

### Reproduction steps

See above.

### Game version

v0.4.14b (157)

### Attachments

Neet Engineer's
[good for benchmark save.save](https://drive.google.com/file/d/1iydQNGxsFhlXDLkb6nzdgqJRiZCn3tsq/view?usp=sharing)

The logfiles:
[23-03-03_14-24-29_2099.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10878979/23-03-03_14-24-29_2099.log)
[Player-prev.log](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10878954/Player-prev.log)

Regarding: C:/Users/Michael/AppData/Local/Temp/Mafi Games/Captain of Industry/Crashes
There is no folder C:/Users/Michael/AppData/Local/Temp/Mafi Games

**Comment by MaFi-Games** [comment]
I have tried a late-game save file in Update 1 and couldn't find any measurable memory increase. However, we should still limit/sample the amount of data points we show at once as it's really hard to read.

**Comment by MaFi-Games** [comment]
We actually fixed this sometime after Update 1. Max stats are now limited and are grouped into even bigger aggregated blobs.
