### ISSUE TITLE
Cargo ship is clipping landfill

### ISSUE THREAD

**Issue by TheOldGuy56** [MaFi-Games/Captain-of-Industry-issues#99]
![cargo ship clipping](https://user-images.githubusercontent.com/91866893/148478118-2f83594b-9600-4549-bf64-036b4df22bc4.png)
**Describe the issue**
When leaving the dock my Cargo ship is clipping land filled area of ocean

**To Reproduce**
See attached screenshot
**Expected behavior**
Ship should back away from dock instead of going forward

**Additional context**
 - Game version: v0.3.8

**Attachments**
If applicable, add save files (zipped), screenshots, or log files to help explain the issue. You can find them in your Documents (`%userprofile%/Documents/CaptainOfIndustry/`). You might need to ZIP the attached files.

**Comment by thetaphi** [comment]
Oh, you can make it clip the whole premade island, if you place the cargo dock strategically. ie, on a pier perpendicular to the coast.

**Comment by fregate84** [comment]
have this issue too :-)

**Comment by MaFi-Games** [comment]
Thanks for the report, ship animation is currently ignoring the land. We will be working on fixing this in the Early Access version.

**Comment by MaFi-Games** [comment]
Thanks for the report, this is now fixed and will be part of the Early Access build released in May.
