### ISSUE TITLE
Empty Pickup Cannot Deliver

### ISSUE THREAD

**Issue by RealisticOptimist** [MaFi-Games/Captain-of-Industry-issues#991]
### Issue description

How can this be?
The storage has enough space and parts. Probably not the same as when truck started, though.
![Pickup](https://user-images.githubusercontent.com/109154186/225484716-96de21de-1918-4dcb-98e7-7724fab852ea.jpg)

### Expected behavior

No wrong notification.

### Reproduction steps

Load attached save.

### Game version

v0.4.14b (157)

### Attachments

[Pickup.zip](https://github.com/MaFi-Games/Captain-of-Industry-issues/files/10985799/Pickup.zip)

**Comment by orthemius** [comment]
what is storage export setting?

**Comment by RealisticOptimist** [comment]
See below. Anyway, an empty truck should not complain it cannot deliver ...
![Storage](https://user-images.githubusercontent.com/109154186/226281387-ac027d0f-ac7b-4474-a577-5b8a34b1ca93.jpg)

**Comment by daz96050** [comment]
Perhaps you've fallen prey an issue like this one: #1206 

Typically, it would say what it cannot deliver
![image](https://github.com/MaFi-Games/Captain-of-Industry-issues/assets/16062219/31b22150-f73e-474d-9518-38ab9f01b14a)
