### ISSUE TITLE
Rain does not render across the whole screen when zoomed out on an ultrawide display. 

### ISSUE THREAD

**Issue by tiersin** [MaFi-Games/Captain-of-Industry-issues#995]
### Issue description

When zoomed out mid to far on an ultrawide resolution, the rain particles do not render towards the edge of the screen, causing it to look like it is only raining on the center area of the screen. This effect is even more noticeable when panning the camera over the map. 
Specs:
Nvidia RTX 4080 using drivers 531.41
AMD Ryzen 5800X
Windows 10, Steam edition. 
Monitor: MSI MAG342CQRV @ 3440x1440

### Expected behavior

Rain effects are consistent across all portion of the screen.

### Reproduction steps

1. Run game at widescreen resolution, borderless, highest graphics settings. v-sync enabled
2. Zoom out to farthest level during a rain storm
3. Rain will not be visible towards the left and right of the screen and can be seen rendering in during panning. 

### Game version

v0.4.14b

### Attachments

![COI_Rain](https://user-images.githubusercontent.com/248581/229170372-2dc7283b-1fe3-4887-941b-9664a77839c5.JPG)

**Comment by RealisticOptimist** [comment]
I can confirm this for a Radeon RX 6800 XT on 4k. Zooming out with F11 shows the effect even more. It only rains in a certain cube.
![RainCube](https://user-images.githubusercontent.com/109154186/229347140-e34d36e6-b45d-434c-b135-7308b0c3bcf5.jpg)

**Comment by MaFi-Games** [comment]
This was fixed in Update 1. Thanks for your report!
