### ISSUE TITLE
Visual bug in Tech-Tree

### ISSUE THREAD

**Issue by Kev100c** [MaFi-Games/Captain-of-Industry-issues#998]
### Issue description

In the research menu, the information window is not displayed properly when clicking back to the previous research after hiding the window. One can see a window opening on the right-hand side, but it doesn't seem to be wide enough.

### Expected behavior

I expected the information window to reopen after clicking on the research.

### Reproduction steps

1. Open the research menu.
2. Select a research.
3. Right-click.
4. Click on the selected research again.

### Game version

0.4.14b (157)

**Comment by MaFi-Games** [comment]
I can't reproduce this issue. Please file a new bug if you have exact steps or some screenshots. Thanks!
